### ISSUE TITLE
Auto Scroller (scroll the pages for you)

### ISSUE THREAD

**Issue by WeMayNeverKnow** [tachiyomiorg/tachiyomi#5087] opened 2021-05-16 03:52 UTC
## Why/User Benefit/User Problem
This feature is good if you are trying to multitask for example you are trying to fold your clothes or doing smth else

## What/Requirements
A button to set it on and a sliding button to adjust the speed

**Comment by arkon** [comment] 2021-05-16 13:09
Duplicate of #2093

**Closed by arkon** 2021-05-16 13:09 UTC
Labels: feature
