### ISSUE TITLE
App Crash when reading downloaded chapter and weird crash log [0.13.6 / Android 7]

### ISSUE THREAD

**Issue by mlengka93** [tachiyomiorg/tachiyomi#7957] opened 2022-09-05 18:32 UTC
### Steps to reproduce

1. Open downloaded chapter
2. Read for a while..
3. Scrolling
4. Random Crash happen <-- always 90% happen btw

### Expected behavior

Not Crashed while reading also my crash log is weird cant read it at all, is the isssue because of OS?

### Actual behavior

Crash while reading randomly only for downloaded chapter, if I read it online it is perfectly fine tho. I enabled cbz option for download, is that why?

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/9491588/tachiyomi_crash_logs.txt)

here is my traces.txt from ANR https://pastebin.com/mbChQTSb since my crash log look like gibberish, hope this helps

### Tachiyomi version

App version: 0.13.6 (standard, 1f79444, 82, 2022-08-14T15:52Z)

### Android version

Android version: 7.1.2 (SDK 25)

### Device

Device brand: Xiaomi Redmi 2

### Other details

My APK installed on Internal, and my Download path in external sdcard

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by mlengka93** [comment] 2022-09-08 08:46
It happen only if I tried downloaded chapter as CBZ format, if I tried the old fashion way its fine, please help

**Comment by arkon** [comment] 2022-09-18 20:16
Duplicate of #6669

**Closed by arkon** 2022-09-18 20:16 UTC
Labels: Bug
