### ISSUE TITLE
App crashes when trying to open Browse View

### ISSUE THREAD

**Issue by hXtreme** [tachiyomiorg/tachiyomi#7991] opened 2022-09-11 17:08 UTC
### Steps to reproduce
1. Open the app
2. Click on Browse in the navbar

### Expected behavior
Browse view should open 

### Actual behavior
App crashes and exits

---

details and crash log will be added here soon.

**Comment by ghostbear** [comment] 2022-09-11 17:17
Duplicate of #7642

**Closed** 2022-09-11 17:29 UTC
