### ISSUE TITLE
Reading statistics 

### ISSUE THREAD

**Issue by olo1990pl** [tachiyomiorg/tachiyomi#115] opened 2016-02-04 09:20 UTC
Is there any chance to add option to sort manga Catalog Alphabetically? 
Its pain for looking after short name manga (someone posted an issue about it) when you want to add less popular or new manga when it's sorted by popularity. 
Also reading statistics would be great - info about how much time you waste on reading "chinese images"  would be good.

**Comment by inorichi** [comment] 2016-02-04 12:58
Don't ask for totally unrelated features on the same issue.

Sorting alphabetically requires new methods on the parsers. And statistics a database upgrade and code changes.

Both of them aren't going to happen soon.

**Comment by Bloodwork** [comment] 2016-02-04 14:32
> Also reading statistics would be great - info about how much time you waste on reading "chinese images" would be good.

Use https://www.rescuetime.com/ for that.

**Comment by radry** [comment] 2017-01-08 18:57
I would suggest to add more sorting options like: rating, last chapter released, first chapter released.
That would make it easier to find new, interesting Mangas from within the app.

**Comment by arkon** [comment] 2022-07-09 22:11
Duplicate of #7213

**Closed by arkon** 2022-07-09 22:11 UTC
Labels: Feature request
