### ISSUE TITLE
Crash on Search, Filter activation on Library

### ISSUE THREAD

**Issue by Xanokei** [tachiyomiorg/tachiyomi#10077] opened 2023-10-28 05:03 UTC
### Steps to reproduce

when opening to Library clicking search and typing anything in will crash the application, this is reoccurring to turning on filters like downloaded and unread.

### Expected behavior

when trying to do things in above it crashes

### Actual behavior

Library Page when turning on filters should show downloaded/all mangas saved.
In library when searching through it should show letter or word of the included titles.

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/13194510/tachiyomi_crash_logs.txt)

### Tachiyomi version

Preview Version R6132

### Android version

Android 14

### Device

Google Pixel 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-10-28 13:38
```
10-27 21:37:34.118 26524 26524 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Index 2, size 2
10-27 21:37:34.118 26524 26524 E AndroidRuntime: 	at androidx.compose.foundation.lazy.layout.MutableIntervalList.checkIndexBounds(SourceFile:31)
10-27 21:37:34.118 26524 26524 E AndroidRuntime: 	at androidx.compose.foundation.lazy.layout.MutableIntervalList.get(SourceFile:1)
10-27 21:37:34.118 26524 26524 E AndroidRuntime: 	at androidx.compose.foundation.lazy.layout.LazyLayoutKt.getKey(SourceFile:5)
10-27 21:37:34.118 26524 26524 E AndroidRuntime: 	at androidx.compose.foundation.lazy.LazyListItemProviderImpl.getKey(SourceFile:11)
10-27 21:37:34.118 26524 26524 E AndroidRuntime: 	at androidx.compose.foundation.lazy.LazyListKt$rememberLazyListMeasurePolicy$1$1$measuredItemProvider$1.getAndMeasure(SourceFile:9)
10-27 21:37:34.118 26524 26524 E AndroidRuntime: 	at androidx.compose.foundation.lazy.LazyListMeasureKt.measureLazyList-50ZNEM8(SourceFile:67)
10-27 21:37:34.118 26524 26524 E AndroidRuntime: 	at androidx.compose.foundation.lazy.LazyListKt$rememberLazyListMeasurePolicy$1$1.invoke(SourceFile:482)
10-27 21:37:34.118 26524 26524 E AndroidRuntime: 	at androidx.compose.foundation.lazy.layout.LazyLayoutKt$LazyLayout$3$2$1.invoke(SourceFile:22)
10-27 21:37:34.118 26524 26524 E AndroidRuntime: 	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1.measure-3p2s80s(SourceFile:99)
10-27 21:37:34.118 26524 26524 E AndroidRuntime: 	at androidx.compose.ui.node.InnerNodeCoordinator$LookaheadDelegateImpl.measure-BRTryo0(SourceFile:63)
10-27 21:37:34.118 26524 26524 E AndroidRuntime: 	at androidx.compose.foundation.AndroidOverscrollKt$StretchOverscrollNonClippingLayer$1.invoke-3p2s80s(SourceFile:45)
10-27 21:37:34.118 26524 26524 E AndroidRuntime: 	at androidx.compose.foundation.AndroidOverscrollKt$StretchOverscrollNonClippingLayer$1.invoke(SourceFile:32)
10-27 21:37:34.118 26524 26524 E AndroidRuntime: 	at androidx.compose.ui.layout.LayoutModifierImpl.measure-3p2s80s(SourceFile:7)
10-27 21:37:34.118 26524 26524 E AndroidRuntime: 	at androidx.compose.ui.node.InnerNodeCoordinator$LookaheadDelegateImpl.measure-BRTryo0(SourceFile:98)
10-27 21:37:34.118 26524 26524 E AndroidRuntime: 	at androidx.compose.foundation.AndroidOverscrollKt$StretchOverscrollNonClippingLayer$1.invoke-3p2s80s(SourceFile:8)
10-27 21:37:34.118 26524 26524 E AndroidRuntime: 	at androidx.compose.foundation.AndroidOverscrollKt$StretchOverscrollNonClippingLayer$1.invoke(SourceFile:17)
10-27 21:37:34.118 26524 26524 E AndroidRuntime: 	at androidx.compose.ui.layout.LayoutModifierImpl.measure-3p2s80s(SourceFile:7)
10-27 21:37:34.118 26524 26524 E AndroidRuntime: 	at androidx.compose.ui.node.InnerNodeCoordinator$LookaheadDelegateImpl.measure-BRTryo0(SourceFile:98)
10-27 21:37:34.118 26524 26524 E AndroidRuntime: 	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(SourceFile:1)
10-27 21:37:34.118 26524 26524 E AndroidRuntime: 	at androidx.compose.ui.node.InnerNodeCoordinator$LookaheadDelegateImpl.measure-BRTryo0(SourceFile:98)
10-27 21:37:34.118 26524 26524 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performLookaheadMeasure$1.invoke(SourceFile:18)
10-27 21:37:34.118 26524 26524 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(SourceFile:61)
10-27 21:37:34.118 26524 26524 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SourceFile:52)
10-27 21:37:34.118 26524 26524 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SourceFile:171)
10-27 21:37:34.118 26524 26524 E AndroidRuntime: 	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(SourceFile:3)
10-27 21:37:34.118 26524 26524 E AndroidRuntime: 	at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release(SourceFile:11)
10-27 21:37:34.118 26524 26524 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate.access$performLookaheadMeasure-BRTryo0(SourceFile:25)
10-27 21:37:34.118 26524 26524 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$LookaheadPassDelegate.remeasure-BRTryo0(SourceFile:144)
10-27 21:37:34.118 26524 26524 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNode.lookaheadRemeasure-_Sx5XlM$ui_release(SourceFile:18)
10-27 21:37:34.118 26524 26524 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNode.lookaheadRemeasure-_Sx5XlM$ui_release$default(SourceFile:7)
10-27 21:37:34.118 26524 26524 E AndroidRuntime: 	at androidx.compose.ui.node.MeasureAndLayoutDelegate.doLookaheadRemeasure-sdFAvZA(SourceFile:16)
10-27 21:37:34.118 26524 26524 E AndroidRuntime: 	at androidx.compose.ui.node.MeasureAndLayoutDelegate.remeasureAndRelayoutIfNeeded(SourceFile:106)
10-27 21:37:34.118 26524 26524 E AndroidRuntime: 	at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureAndLayout(SourceFile:67)
10-27 21:37:34.118 26524 26524 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidComposeView.measureAndLayout(SourceFile:26)
10-27 21:37:34.118 26524 26524 E AndroidRuntime: 	at androidx.compose.ui.node.Owner$-CC.measureAndLayout$default(SourceFile:4)
10-27 21:37:34.118 26524 26524 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(SourceFile:12)
10-27 21:37:34.118 26524 26524 E AndroidRuntime: 	at android.view.View.draw(View.java:23892)

...
```

**Comment by arkon** [comment] 2023-10-28 13:39
Duplicate of #10069

**Closed by arkon** 2023-10-28 13:39 UTC
Labels: Bug
