### ISSUE TITLE
Auto add titles from a list 

### ISSUE THREAD

**Issue by 3bdullah-3bdeen** [tachiyomiorg/tachiyomi#9673] opened 2023-07-05 22:49 UTC
### Describe your suggested feature

So what if the app can import your list from MAL or any other tracker, and would start searching the sources for titles and add them automatically in your library under a tap called MAL imports for example, and before adding it would organize the search results into three categories, one for titles searched and found exact mach, titles with approximate or close match, and titles with no mach but might be what you're looking for under a different name, and an option to add all for each of these categories, that way whenever you add an anime in your list in MAL you can just add all chapters in the app here instead of searching one by one 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-07-05 22:53
Duplicate of #2205

**Closed by arkon** 2023-07-05 22:53 UTC
Labels: Feature request
