### ISSUE TITLE
[Bug] <Mangas keep getting removed from my library without my approval (happened multiple times)

### ISSUE THREAD

**Issue by lilshinya** [tachiyomiorg/tachiyomi#3390] opened 2020-06-26 19:14 UTC
---

### Device information
* Tachiyomi version: 0.9.2
* Android version: 10
* Device: S9

## Steps to reproduce
1. First step: Save a manga into the library
2. Second step: Don't do anything

### Expected behavior
Manga stays in my library

### Actual behavior
Gets removed from library

### Other details
I don't know whether it's because I completed the manga that it got removed or something else but they keep getting removed here's 2 examples below:
![Screenshot_20200626-150213_Tachiyomi](https://user-images.githubusercontent.com/67482252/85892855-ac905c80-b7bf-11ea-954a-3052620a2c2d.jpg)
![Screenshot_20200626-010446_Tachiyomi](https://user-images.githubusercontent.com/67482252/85892873-b4500100-b7bf-11ea-9bb2-fd447a8ccbdc.jpg)

Notice I have read all their chapters and I'm confident I saved them for sure

**Comment by arkon** [comment] 2020-06-26 19:51
Certainly concerning, but unactionable from our side without any reproduction steps.

**Comment by AkoSiJam** [comment] 2020-06-30 13:48
I have the same problem. I saved atleast 200+ manga in my library when I first downloaded the app but recently I noticed some of them got removed all of a sudden. Even some of the manga I just read recently got removed. I don't know if its has something to do with the source (mangadex) or if its because I have too many saved manga. I hope you find a fix for this
--------------------------------------------------
Tachiyomi version: 0.9.2
Android 10
Device: Huawei Y9 Prime 2019
--------------------------------------------------
If that helps

**Comment by AvalonTheDivine** [comment] 2020-07-21 14:33
![image](https://user-images.githubusercontent.com/68600956/88065851-445d4c80-cbac-11ea-829e-8defa64044fc.png)
![image](https://user-images.githubusercontent.com/68600956/88065893-50e1a500-cbac-11ea-8221-935071e1ea77.png)
![image](https://user-images.githubusercontent.com/68600956/88066033-766eae80-cbac-11ea-9200-7086022e9681.png)

These images show the manga used as a test, currently the issue happened where the Downloaded manga "disappear".  

However they are still on the SD card as per the 3rd image. 

When the manga shown to be downloaded on the SD Card is opened without Wi-Fi, the manga opens as it should without internet. this demonstrates the manga are still downloaded and open as expected.

As far as I can tell in my instance, The Tachiyomi app, for some reason erases the downloaded tag, so manga show as not downloaded. but when accessed offline, the downloaded manga work as expected. just do not appear in the downloaded filter.

Is there a way to prevent Tachiyomi from forgetting what it has in the download folder, or displaying what is present in the download folder already?

**Comment by arkon** [comment] 2020-07-21 14:34
@AvalonTheDivine This is not the correct repo for J2K issues.

**Comment by AvalonTheDivine** [comment] 2020-07-21 14:34
oh sorry

**Comment by AvalonTheDivine** [comment] 2020-07-21 14:34
feel free to delete

**Comment by arkon** [comment] 2021-04-17 15:28
Closing as this is unactionable without consistent reproduction steps.

**Closed by arkon** 2021-04-17 15:28 UTC
Labels: bug, needs more info
