### ISSUE TITLE
Feature to change the names of comics

### ISSUE THREAD

**Issue by AmriG** [tachiyomiorg/tachiyomi#6862] opened 2022-04-04 06:03 UTC
### Describe your suggested feature

Due to the huge volumes of data the sources process, they often fail to update the small details of their content, like covers and names. For example, some comics often retain their Japanese names and featured-on-the-front magazine covers, even after multiple foreign language volumes are published with translated names and cover art.

But, while a feature to change the covers exists, there is no feature to change the names of the comics in the main Tachiyomi app. I would really like a feature to change the name of the comics.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment] 2022-04-04 06:04
Duplicate of #4398

**Closed by loocool2** 2022-04-04 06:04 UTC
Labels: Feature request
