### ISSUE TITLE
Show number of chapters in a manga in the extension search/migration screen

### ISSUE THREAD

**Issue by paulo27ms** [tachiyomiorg/tachiyomi#6195] opened 2021-11-04 04:17 UTC
### Describe your suggested feature

Like we have badges for this in our library, those badges can also be added to the search screens.
These badges will only display AFTER you have opened a manga.
This would be most useful when migrating a manga because after you open the manga in a source you don't have to reopen to double check the total chapters compared to other sources.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment] 2021-11-04 10:12
Hmm after clicking the manga would work, the only down side i see is the chapter number would now be stored in the db, and a search in say 5 months for the same manga would show the outdated chapter counts on sources that were not chosen

**Comment by paulo27ms** [comment] 2021-11-04 13:39
If we don't want to show outdated info then we pick a time (say 1 month) and past that no chapter badges is displayed, like if you didn't check it at all, until you refresh again.

**Comment by vengiare** [comment] 2021-11-05 11:24
Could be misleading for most users (how others have chapter badges and others not)

**Comment by arkon** [comment] 2021-11-19 21:16
Mostly duplicate of #2867

**Closed by arkon** 2021-11-19 21:16 UTC
Labels: Feature request
