### ISSUE TITLE
Start/Continue reading button on manga cover

### ISSUE THREAD

**Issue by ARiyou2000** [tachiyomiorg/tachiyomi#6034] opened 2021-10-04 12:26 UTC
### Describe your suggested feature

The same feature as J2K.
A little button at bottom-right position of manga cove that let you continue or start manga if new chapters available. 
![Screenshot_2021-10-04-15-49-56](https://user-images.githubusercontent.com/35896230/135850792-c1828bef-1fb7-403f-a3d3-54f11d657f87.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2021-10-04 13:10
Duplicate of #3071

**Closed by arkon** 2021-10-04 13:11 UTC
Labels: Feature request
