### ISSUE TITLE
Manga demon no chapter found error 

### ISSUE THREAD

**Issue by Hawksaran** [tachiyomiorg/tachiyomi#9875] opened 2023-08-26 11:17 UTC
### Steps to reproduce

![Screenshot_2023-08-26-16-46-05-99_79aa9bf7c61e266c5f841e42245e214b](https://github.com/tachiyomiorg/tachiyomi/assets/132247482/4c69e005-c5ab-4a9e-b6ac-58415dc2c772)

### Expected behavior

Should be able to view chapter 

### Actual behavior

But no chapter found

### Tachiyomi version

R6019

### Android version

Android 13

### Device

One plus 8t

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment] 2023-08-26 11:33
Duplicate of tachiyomiorg/tachiyomi-extensions#17669

**Closed by AntsyLich** 2023-08-26 11:33 UTC
Labels: Bug
