### ISSUE TITLE
[Feature Request] option to add widgets on smartphone/tablet home screen

### ISSUE THREAD

**Issue by matheuswr89** [tachiyomiorg/tachiyomi#5264] opened 2021-06-01 23:21 UTC
## Why/User Benefit/User Problem
With this option the user will be able to access some functionality of the app directly through the widgets instead of opening the app all the time.

## What/Requirements
This option would be good for browsing and/or updating the library on the device's main screen. Besides being more practical.
Widgets examples:
![widgets](https://user-images.githubusercontent.com/44068234/120401687-d975b980-c316-11eb-85c6-00b84ec1e010.jpg)

**Comment by arkon** [comment] 2021-06-01 23:24
Duplicate of #746

**Closed by arkon** 2021-06-01 23:24 UTC
Labels: feature
