### ISSUE TITLE
I'm new here

### ISSUE THREAD

**Issue by Pillcoops** [tachiyomiorg/tachiyomi#4359] opened 2021-01-26 22:14 UTC
1-I was wondering is there any way to keep manga covers i changed permanent?
For example when i change the cover of a manga from a specific extension and then delete the app and reinstall it again, the manga covers revert back to it's original cover by that extension. can i make the change permanent

2-Also can i link my Email to the app so it saves up my library or is that not possible?

**Comment by arkon** [comment] 2021-01-26 22:17
1. Duplicate of #3851
2. No, there's no account system. You can save your backup file somewhere if you want.

**Closed** 2021-01-26 22:17 UTC
Labels: feature

**Comment by Pillcoops** [comment] 2021-01-26 22:33
Thank alot
