### ISSUE TITLE
Animation pages

### ISSUE THREAD

**Issue by Wabaya** [tachiyomiorg/tachiyomi#7762] opened 2022-08-14 19:44 UTC
### Describe your suggested feature

It should work like this :when you press a button while reading the page pass automatically every like 6 sec  and you can change the time 

### Other details

You can change the time of moving and the speed and if it's from right to left or up to down

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-08-14 21:56
Duplicate of #2093

**Closed by arkon** 2022-08-14 21:56 UTC
Labels: Feature request
