### ISSUE TITLE
Add an X to manually skip in the global search the search of single sources

### ISSUE THREAD

**Issue by Palloxin** [tachiyomiorg/tachiyomi#9176] opened 2023-03-05 16:41 UTC
### Describe your suggested feature

![IMG_20230305_173632](https://user-images.githubusercontent.com/75091899/222973517-0e791e06-77c4-4110-9dd9-175019bf7965.jpg)
A simple X to instruct the app to skip the search in specific extensions to accelerate the global search. Like in the image i am fairly sure that nhentai doesn't have the manga "the gamer" in its source sk i would like to skip it since it is a waste of time. Personally i have 50+ extensions installed so it would be useful in accelerating searches.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-03-05 16:42
Duplicate of #3720

**Closed by arkon** 2023-03-05 16:42 UTC
Labels: Feature request

**Comment by Palloxin** [comment] 2023-03-05 16:48
It is similar but it is different. The skip count only on that global search. my suggestuon doesn't involce pinned sources or exclusion of sources from global search
