### ISSUE TITLE
Local Source filter not working 

### ISSUE THREAD

**Issue by TheKingTermux** [tachiyomiorg/tachiyomi#9003] opened 2023-01-30 15:04 UTC
### Steps to reproduce

1. Open local source
2. Select filter
3. Didn't show anything

### Expected behavior

Showing like Genre, Alphabetical, etc

### Actual behavior

Show nothing

### Tachiyomi version

0.14.3

### Android version

Android 11

### Device

Realme 7i

### Other details

![IMG_20230130_220357](https://user-images.githubusercontent.com/50316075/215513815-0416e87e-6942-44d0-b5b7-0a0cfd037ced.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-01-30 15:07
Duplicate of #4967

**Closed** 2023-01-30 15:07 UTC
Labels: Bug
