### ISSUE TITLE
add some rating like star 1-10 and comment section 

### ISSUE THREAD

**Issue by ableimmo** [tachiyomiorg/tachiyomi#9756] opened 2023-07-25 12:13 UTC
### Describe your suggested feature

it should work like this, the readers will create an account for tachiyomi only and  if they want to rate some sertain manwha or manga they can add 8 out of 10 just like that. and the comment section i want that so the readers can interact to each other. 

> 

### Other details

like the myanimelist they have ratings and comment section 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment] 2023-07-25 12:14
Duplicate of #4336

**Closed by loocool2** 2023-07-25 12:14 UTC
Labels: Feature request
