### ISSUE TITLE
ManhuaScan extension is not working. Chapters in ManhuaScan extension is not working

### ISSUE THREAD

**Issue by murasakibara2002** [tachiyomiorg/tachiyomi#5116] opened 2021-05-20 00:53 UTC
DO NOT OPEN AN ISSUE IN THIS REPO. SEE https://github.com/tachiyomiorg/tachiyomi-extensions

ManhuaScan extension is not working. Chapters in ManhuaScan extension is not working

**Comment by h-hyuuga** [comment] 2021-05-20 00:57
> DO NOT OPEN AN ISSUE IN THIS REPO. SEE https://github.com/tachiyomiorg/tachiyomi-extensions
> 
> ManhuaScan extension is not working. Chapters in ManhuaScan extension is not working

As you noted, extension issues belong in this repo  https://github.com/tachiyomiorg/tachiyomi-extensions 

This issue has already been reported, and is a duplicate of  https://github.com/tachiyomiorg/tachiyomi-extensions/issues/7088

**Closed** 2021-05-20 01:00 UTC
Labels: catalog, invalid
