### ISSUE TITLE
Number of chapters to the migration

### ISSUE THREAD

**Issue by Makishimu120** [tachiyomiorg/tachiyomi#6455] opened 2022-01-09 11:37 UTC
### Describe your suggested feature

When migrating a manga to another site, it is not visible how many chapters are currently available there. you have to enter each one for a long time. If the number of chapters on the cover could be seen, for example, it would be easier and faster.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment] 2022-01-09 11:56
Duplicate of https://github.com/tachiyomiorg/tachiyomi/issues/2867

**Closed by curche** 2022-01-09 11:56 UTC
Labels: Feature request
