### ISSUE TITLE
Black splash screen when using dark mode in MIUI

### ISSUE THREAD

**Issue by XarhsSta** [tachiyomiorg/tachiyomi#7515] opened 2022-07-11 22:46 UTC
### Steps to reproduce

First step. Just open the app in a device using MIUI and has Dark Mode enabled

### Expected behavior

It should show the app logo

### Actual behavior

It shows a black circle. Because I am an Android engineer I know this is an issue with Splash Screen API  which I assume you use. You should update it in the build.gradle file and if this implementation is done correctly it should fix itself.

### Tachiyomi version

0.13.5

### Android version

Android 10

### Device

Xiaomi Redmi Note 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-07-11 22:53
Duplicate of #6678

**Closed by alessandrojean** 2022-07-11 22:53 UTC
Labels: Bug

**Comment by arkon** [comment] 2022-07-12 12:08
The new version of the library has larger bugs.
