### ISSUE TITLE
[Feature Request] import local manga with proper tachiyomi structure

### ISSUE THREAD

**Issue by Omar-Abdul-Azeez** [tachiyomiorg/tachiyomi#4480] opened 2021-02-14 22:00 UTC
Being able to import already downloaded manga from other sources and have the ability to read it using tachiyomi's reader would be a great addition.
I currently have a different app for reading but its just not enough

All it needs is an import button that opens a file browsing dialog that you could aim at a folder with proper tachiyomi structure and then tachiyomi would ask which library to import it to and import it into the app exactly as it does to manga imported from extensions. the manga poster would either be a poster.jpg file or the first chapter's first image in case the poster isn't there.

The supported structure should be:

```
Chainsaw man/poster.jpg      might or might not exist
Chainsaw man/Chapter 1/001.jpg
Chainsaw man/Chapter 1/002.jpg
Chainsaw man/Chapter 2/001.jpg
```

Now I know that flexible support of this would just create more issues and so I'll only ask for simple flexibility:
1. Common image formates support (mainly png and jpg)
2. No chapter folders support eg. `Chainsaw man/001.jpg` in this case tachiyomi should put all images under `chapter 1` in the app
3. Support different digit numbers other than the current 3-digit eg. `1.jpg 01.jpg 0001.jpg` now this doesn't necessarily give support for `1.jpg` and `10.jpg` in the same folder because I know that depending on the current sorting approach this might be a nightmare to code. This would just mean that if `1.jpg` exists then there exists 9 images at max.
4. Support aiming tachiyomi at a folder of mangas eg. `manga/manga 1/chapter 1/001.jpg` `manga/manga 2/001.jpg`

Syncing should also be possible for local manga too

As for the other info a manga has (status/source/author/genres/synopsis)
being able to edit them in the app would be great but mainly it would just be left blank for local manga.

This is irrelevant but this feature would also help with manga imported from webtoon before webtoon took the chapters off of their site and now tachiyomi doesn't recognize already downloaded chapters of that manga. This would either create a solution to make tachiyomi able to recognize downloaded chapters of that manga and all that would be left is implement it or just enable us to import those chapters locally to be able to read them.

**Comment by Seishirou101** [comment] 2021-02-14 22:04
duplicate of #2289

**Comment by Omar-AbdulAzeez** [comment] 2021-02-14 22:19
It definitely is a duplicate since both request manga that doesn't exist in sources but I would say that the other one is a duplicate of mine rather than the opposite since mine is more broad and asking for more features/addresses issues that come from not having a source... the ability to read deleted manga from a source is just a bonus and is merely mentioned in the very last section

**Closed** 2023-01-29 13:56 UTC
Labels: Feature request
