### ISSUE TITLE
Scrolling is less smooth than previous version

### ISSUE THREAD

**Issue by acknologia** [tachiyomiorg/tachiyomi#8470] opened 2022-11-07 15:32 UTC
### Steps to reproduce

Go into browse then any source then scroll the manga list

### Expected behavior

Testing against previous version, scrolling used to feel fluid and had inertia

### Actual behavior

Scrolling feels abrupt

### Tachiyomi version

0.14.2

### Android version

Android 12 

### Device

Galaxy tab s7 plus

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-11-08 03:10
Duplicate of #8310

**Closed by arkon** 2022-11-08 03:10 UTC
Labels: Bug
