### ISSUE TITLE
Webtoon view incorrect loading

### ISSUE THREAD

**Issue by yohanim** [tachiyomiorg/tachiyomi#7452] opened 2022-07-04 05:03 UTC
### Steps to reproduce

I have this from time to time.
It's been there for a long time but for once I'm reporting it.
Usually when launching read for a manga after hours of sleep and the manga is set to show in webtoon mode we end up having the images with "large" gaps and the error messages inviting to reload or show in WebView like when a page failed download.
![Screenshot_2022-07-04-06-54-12-568_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/2168165/177084643-2309d42b-8186-4929-87bb-44b2048076f1.jpg)

### Expected behavior

As all is properly downloaded, no large gap and no error.

### Actual behavior

See previous explanation 

### Tachiyomi version

r4553

### Android version

Android 12

### Device

Mi 11t

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by yohanim** [comment] 2022-07-09 12:38
I just got it with r4622

**Comment by arkon** [comment] 2022-07-09 17:30
Duplicate of #5687

**Closed by arkon** 2022-07-09 17:30 UTC
Labels: Bug
