### ISSUE TITLE
Tachiyomi crashed

### ISSUE THREAD

**Issue by jferdous70** [tachiyomiorg/tachiyomi#7797] opened 2022-08-18 10:20 UTC
### Steps to reproduce

1. Open app
2. click History/browse/whatever
3. click More nav button 

### Expected behavior

app shouldn't crash

### Actual behavior

app crashed instead of opening More screen

### Crash logs

[tachiyomi_crash.txt](https://github.com/tachiyomiorg/tachiyomi/files/9372584/tachiyomi_crash.txt)

### Tachiyomi version

Preview 4799

### Android version

Android 12

### Device

Galaxy A72

### Other details

not easy to reproduce 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2022-08-18 12:03
Looks like some duplicate key of MangaDex extension. But `VerticalFastScroller` is only used in `MangaScreen` and `UpdateScreen` for chapter lists so I suppose there's no key of extension?
```
java.lang.IllegalArgumentException: Key eu.kanade.tachiyomi.extension.all.mangadex was already used. If you are using LazyColumn/Row please make sure you provide a unique key for each item.
  ...
  at eu.kanade.presentation.components.VerticalFastScrollerKt$VerticalFastScroller$2$1.invoke(VerticalFastScroller.kt:7)
  ...
```

**Comment by arkon** [comment] 2022-08-18 12:12
Duplicate of #7642

**Closed by arkon** 2022-08-18 12:12 UTC
Labels: Bug
