### ISSUE TITLE
Sync Between Devices using Tracking services 

### ISSUE THREAD

**Issue by RavitejaLam** [tachiyomiorg/tachiyomi#5903] opened 2021-09-13 14:53 UTC
### suggested feature

It would be great if there is a sync between the app installed on different devices. I believe that setting up a separate account only for multiple device sync is high maintenance. But by using current Tracking service (MAL, AniList, etc) in the app sync can be achieved.

It should work similar to the tracking where we connect each manga to a Tracking service. ( which is one way right now )

Sync should be enabled if user connects the specific manga to Tracking service. Chapters to be updated as the Tracking service data.  

![image](https://user-images.githubusercontent.com/22323518/133105188-152e766c-0c7b-4a7a-ba98-d418ced863b9.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2021-09-13 14:57
Duplicate of #1626, basically.

**Closed by arkon** 2021-09-13 14:57 UTC
Labels: Feature request
