### ISSUE TITLE
Local library hosted by a NAS

### ISSUE THREAD

**Issue by stany24** [tachiyomiorg/tachiyomi#9106] opened 2023-02-18 09:03 UTC
### Describe your suggested feature

The objective is to have the local library hosted in a NAS shared folder on the local network. 
The shared folder could be nfs,samba or any other alternatives.
Tachiyomi shouldn't download the fills from the NAS only read them.
I tried mounting the shared folder with root privilege on the local folder of Tachiyomi but I couldn't make it work.
I think it would be easier to implement it directly to the application as a feature.
Thanks to anybody trying to make it work.

### Other details

benefits:
A NAS is made to host large amount of data.
All Tachiyomi application on the network can access the local library on the NAS.
Reduce traffic with web sources.

Cons:
Potential conflict with the local library on the phone.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment] 2023-02-18 09:36
Duplicate of #6422

**Closed by loocool2** 2023-02-18 09:36 UTC
Labels: Feature request
