### ISSUE TITLE
[Feature Request] <Linking Tracking Status and Categories>

### ISSUE THREAD

**Issue by zayin02** [tachiyomiorg/tachiyomi#5024] opened 2021-05-05 18:14 UTC
I thought of this idea after reading #200

## Why/User Benefit/User Problem
When adding manga to library it defaults the tracker status to reading even when the user's status is different and would require to manually change it. My idea will not only solve this problem  but it will also make changing tracker statuses hassle free.

## What/Requirements
To explain here is an example, if I'm reading and manga and it's categories/tracker status are set as:
![20210505_193736](https://user-images.githubusercontent.com/76571965/117186015-ba990b80-adda-11eb-98ed-33bbd657941c.jpg)
![20210505_192035](https://user-images.githubusercontent.com/76571965/117186067-c553a080-adda-11eb-9a69-c3ee2c828a0a.jpg)

Now if I decide I want to put it on hold, it should change the statues of the manga once the category has changed instead of manually changing it and changing the category. 

Step 1(Changing the category):
![20210505_195144](https://user-images.githubusercontent.com/76571965/117186736-6e9a9680-addb-11eb-8612-c031fbc8e9e6.jpg)

Step 2(Automatically changing status):
![20210505_194539](https://user-images.githubusercontent.com/76571965/117186877-9689fa00-addb-11eb-9bcb-c49811e59600.jpg)
 
The same steps can be produced with the other statues 

##Important things to note
•Not everyone's Categories are the same as mine:
The way to solve this is if in the Categories settings there is an option to assign a specific tracker statue to each category.
![20210505_192413](https://user-images.githubusercontent.com/76571965/117187940-c1288280-addc-11eb-8934-bf4d5dcb6707.jpg)

•Changes in assigned categories while user is offline:
Not sure how to address the issue, if you have ideas suggestions will help 

•User selects more than one assigned categories:
A pop up message asking the user which category do they want status preferences of.

##Conclusion 
It's just a rough idea I have. I'm not sure whether it will be able to be implemented. If you have read till here thanks for reading and have a good day.

**Comment by CarlosEsco** [comment] 2021-05-06 10:31
Duplicate of #1730

**Closed by CarlosEsco** 2021-05-06 10:31 UTC
Labels: feature
