### ISSUE TITLE
App crashing after removing manga from library

### ISSUE THREAD

**Issue by 14amnesia14** [tachiyomiorg/tachiyomi#9019] opened 2023-02-04 05:03 UTC
### Steps to reproduce

Removing manga from library 

### Expected behavior

Removing without crash

### Actual behavior

Crashing after few second

### Crash logs

--------- beginning of main
02-04 11:34:27.479 23986 23986 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
02-04 11:34:27.632 23986 24016 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
02-04 11:34:27.633 23986 24019 E libc    : Access denied finding property "vendor.debug.prerotation.disable"
02-04 11:34:28.578 23986 24026 E libc    : Access denied finding property "vendor.debug.prerotation.disable"
02-04 11:34:28.578 23986 24026 E libc    : Access denied finding property "ro.vendor.graphics.memory"
02-04 11:34:28.578 23986 24026 E libc    : Access denied finding property "vendor.debug.prerotation.disable"
02-04 11:34:28.579 23986 24026 E libc    : Access denied finding property "vendor.debug.prerotation.disable"
02-04 11:34:28.579 23986 24026 E libc    : Access denied finding property "vendor.debug.prerotation.disable"
02-04 11:34:28.967 23986 24083 E SQLiteLog: (284) automatic index on C(manga_id)
02-04 11:34:28.967 23986 24083 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.14.3 (standard, 817418f, 93, 2023-01-07T17:15Z)
Android version: 9 (SDK 28)
Android build ID: 52.0.C.5.295
Device brand: KDDI
Device manufacturer: Sony
Device name: SOV38
Device model: SOV38
Device product name: SOV38_jp_kdi

### Tachiyomi version

0.14.3

### Android version

Android 9

### Device

Sony Xz2 premium

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment] 2023-02-04 08:41
Probably the same as #7997, but crash logs don't have the error in it. Could you make a new crash log to confirm that it's the same issue?

> To dump crash logs go to **More → Settings → Advanced** then enable **verbose logging** then restart Tachiyomi.
Reproduce the crash and go to **More → Settings → Advanced** then tap **Dump crash logs**.
You can disable **verbose logging** afterwards.

**Comment by 14amnesia14** [comment] 2023-02-04 15:07
Thank you for responding my report , here the following log

--------- beginning of main
02-04 22:02:31.467 17078 17078 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
02-04 22:02:31.654 17078 17111 E libc    : Access denied finding property "vendor.debug.prerotation.disable"
02-04 22:02:33.191 17078 17133 E libc    : Access denied finding property "vendor.debug.prerotation.disable"
02-04 22:02:33.192 17078 17133 E libc    : Access denied finding property "ro.vendor.graphics.memory"
02-04 22:02:33.192 17078 17133 E libc    : Access denied finding property "vendor.debug.prerotation.disable"
02-04 22:02:33.193 17078 17133 E libc    : Access denied finding property "vendor.debug.prerotation.disable"
02-04 22:02:33.196 17078 17133 E libc    : Access denied finding property "vendor.debug.prerotation.disable"
02-04 22:02:33.639 17078 17210 E SQLiteLog: (284) automatic index on C(manga_id)
02-04 22:02:33.640 17078 17210 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
02-04 22:03:19.657 17078 17226 E CursorWindow: Failed to read row 675, column 0 from a CursorWindow which has 675 rows, 26 columns.
02-04 22:03:19.664 17078 17214 E ACRA    : ACRA caught a NullPointerException for eu.kanade.tachiyomi
02-04 22:03:19.664 17078 17214 E ACRA    : java.lang.NullPointerException
02-04 22:03:19.664 17078 17214 E ACRA    : 	at eu.kanade.tachiyomi.app.LibraryViewQueriesImpl$library$1.invoke(DatabaseImpl.kt:19)
02-04 22:03:19.664 17078 17214 E ACRA    : 	at com.squareup.sqldelight.Query.executeAsList(Query.kt:18)
02-04 22:03:19.664 17078 17214 E ACRA    : 	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToList$1$1.invokeSuspend(FlowExtensions.kt:6)
02-04 22:03:19.664 17078 17214 E ACRA    : 	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToList$1$1.invoke(FlowExtensions.kt:13)
02-04 22:03:19.664 17078 17214 E ACRA    : 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:8)
02-04 22:03:19.664 17078 17214 E ACRA    : 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:50)
02-04 22:03:19.664 17078 17214 E ACRA    : 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
02-04 22:03:19.664 17078 17214 E ACRA    : 	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToList$$inlined$map$1$2.emit(Collect.kt:76)
02-04 22:03:19.664 17078 17214 E ACRA    : 	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:2)
02-04 22:03:19.664 17078 17214 E ACRA    : 	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:19)
02-04 22:03:19.664 17078 17214 E ACRA    : 	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:1)
02-04 22:03:19.664 17078 17214 E ACRA    : 	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$asFlow$1.invokeSuspend(FlowExtensions.kt:130)
02-04 22:03:19.664 17078 17214 E ACRA    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
02-04 22:03:19.664 17078 17214 E ACRA    : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
02-04 22:03:19.664 17078 17214 E ACRA    : 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
02-04 22:03:19.664 17078 17214 E ACRA    : 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
02-04 22:03:19.664 17078 17214 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
02-04 22:03:19.664 17078 17214 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:66)
02-04 22:03:19.664 17078 17214 E ACRA    : 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [CoroutineName(eu.kanade.tachiyomi.ui.library.LibraryTab:eu.kanade.tachiyomi.ui.library.LibraryScreenModel:default:ScreenModelCoroutineScope), StandaloneCoroutine{Cancelling}@2f8dcdc, Dispatchers.IO]
02-04 22:03:19.988 17367 17367 E .tachiyomi:acr: Not starting debugger since process cannot load the jdwp agent.
02-04 22:03:20.138 17367 17383 E SQLiteLog: (283) recovered 11 frames from WAL file /data/data/eu.kanade.tachiyomi/databases/tachiyomi.db-wal
02-04 22:03:22.304 17484 17484 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
02-04 22:03:22.447 17484 17535 E libc    : Access denied finding property "vendor.debug.prerotation.disable"
02-04 22:03:22.447 17484 17532 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
02-04 22:03:23.351 17484 17542 E libc    : Access denied finding property "vendor.debug.prerotation.disable"
02-04 22:03:23.352 17484 17542 E libc    : Access denied finding property "ro.vendor.graphics.memory"
02-04 22:03:23.352 17484 17542 E libc    : Access denied finding property "vendor.debug.prerotation.disable"
02-04 22:03:23.353 17484 17542 E libc    : Access denied finding property "vendor.debug.prerotation.disable"
02-04 22:03:23.353 17484 17542 E libc    : Access denied finding property "vendor.debug.prerotation.disable"
02-04 22:03:23.758 17484 17620 E SQLiteLog: (284) automatic index on C(manga_id)
02-04 22:03:23.758 17484 17620 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.14.3 (standard, 817418f, 93, 2023-01-07T17:15Z)
Android version: 9 (SDK 28)
Android build ID: 52.0.C.5.295
Device brand: KDDI
Device manufacturer: Sony
Device name: SOV38
Device model: SOV38
Device product name: SOV38_jp_kdi

**Comment by scb261** [comment] 2023-02-04 15:21
Yeah, it's the same crash. Duplicate of #7997

**Closed** 2023-02-04 15:24 UTC
Labels: Bug
