### ISSUE TITLE
Crash by Clicking Hanging Copy Button

### ISSUE THREAD

**Issue by eskerwiln** [tachiyomiorg/tachiyomi#9584] opened 2023-06-05 07:28 UTC
### Steps to reproduce

1. Open a manga description box and tap and hold until cursors appear, along with a button to copy selected text.
2. Use the android system navigation back button to exit the manga page and return to library.
3. The Copy Button will move to the top left of the screen. Clicking it will cause the app to crash.

### Expected behavior

The Copy Button should disappear, as there is no existing selection and there is nothing to copy.

### Actual behavior

The Copy Button stays in the top left while navigating menus or viewing other manga's pages. To make it disappear, open another description box, select more text, then tap outside of it to cancel the selection.

The Copy Button does temporarily disappear when reading a manga chapter but it reappears in top left upon returning to the menus.

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/11649795/tachiyomi_crash_logs.txt)

### Tachiyomi version

0.14.6

### Android version

Android 12

### Device

OnePlus N200

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2023-06-05 10:35
Duplicate of #9073

**Closed by stevenyomi** 2023-06-05 10:35 UTC
Labels: Bug
