### ISSUE TITLE
Auto hide top and bottom bar when scrolling down library 

### ISSUE THREAD

**Issue by sombresu** [tachiyomiorg/tachiyomi#8948] opened 2023-01-19 11:31 UTC
### Describe your suggested feature

Similar to TachiJ2k. Please don't ask me to use it instead. I prefer using Tachiyomi.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2023-01-19 11:38
Duplicate of #8101, #8315

**Closed by stevenyomi** 2023-01-19 11:38 UTC
Labels: Feature request
