### ISSUE TITLE
Garbage Collector

### ISSUE THREAD

**Issue by wruizcanal** [tachiyomiorg/tachiyomi#6094] opened 2021-10-13 13:02 UTC
### Describe your suggested feature

Hi there. 

I would like a way to check the tachiyomi directory for garbage. 

As you know, tachiyomi creates temporary folders when downloading chapters (_tmp). These folders can accumulate over time if you leave unfinished downloads or cancel downloads. 

I also want to know if there are any manga folders that are not in the library. 

It can be a utility similar to that of other cleaner-type apps that show the content and you select what you want to remove. 

Thanks

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2021-10-16 02:25
I'll consider this as a duplicate of #1767

**Closed by arkon** 2021-10-16 02:25 UTC
Labels: Feature request
