### ISSUE TITLE
Downloaded chapters gets deleted when reloaded

### ISSUE THREAD

**Issue by Seijooooo** [tachiyomiorg/tachiyomi#8534] opened 2022-11-14 17:31 UTC
### Steps to reproduce

1. I download some manhwa chapters to read
2. It's been a while since i've read it so i reload it to download the latest chapters
3. When reloaded the chapters downloaded disappeared 

### Expected behavior

When i reload it i expect to see the latest chapter of that manhwa and the downloaded chapters remains

### Actual behavior

But when i reload it, the downloaded chapters gets removed but i did saw the latest chapters

### Tachiyomi version

0.14.2

### Android version

8.1.0

### Device

Oppo a12e CPH1853

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-11-15 03:41
Duplicate of #8438

**Closed by arkon** 2022-11-15 03:41 UTC
Labels: Bug

**Comment by Seijooooo** [comment] 2022-11-17 00:34
> Can you check your Download location using a File Manager to see if the downloaded chapters are still there
> 
> Also what Source/Website are you downloading from

Yes, it is still there and also when i click only "downloaded only" it shows up but the chapters are not there. And i use a bunch of extension but the problem occur in Mangakakalot (EN) extension.
