### ISSUE TITLE
[Feature Request] Custom library update time

### ISSUE THREAD

**Issue by Shrekbastian** [tachiyomiorg/tachiyomi#5382] opened 2021-06-11 15:30 UTC
## Why/User Benefit/User Problem
There is currently no way to set your library to update at a specific time. Having this feature would be very beneficial for updating at times when the manga is released, e.g 6:00 for shonen jump manga.

## What/Requirements
(explain how this feature would behave)
An additional setting it updates, which would allow you to set a custom time. Could be included in the same section as the update intervals, under a new option titled "custom".

**Comment by CrepeTF** [comment] 2021-06-14 00:01
You can actually set the update at a specific time, just do it at the exact time you want, and that's the time it sets.

**Comment by CrepeTF** [comment] 2021-06-14 00:04
Also dupe of #3589

**Closed by CrepeTF** 2021-06-14 00:04 UTC
Labels: feature
