### ISSUE TITLE
Tachiyomi completely freezes when trying to refresh library or search for new manga on versions 13.2+

### ISSUE THREAD

**Issue by Benetsu** [tachiyomiorg/tachiyomi#7681] opened 2022-08-04 06:43 UTC
### Steps to reproduce

1. Open Tachiyomi
2. Try to refresh the library or search for new manga

### Expected behavior

Tachiyomi refreshes the content

### Actual behavior

Tachiyomi permanently freezes

### Crash logs

[logcat_08-04-2022_14-25-16.txt](https://github.com/tachiyomiorg/tachiyomi/files/9257279/logcat_08-04-2022_14-25-16.txt)
[tachiyomi_crash_logs_1.txt](https://github.com/tachiyomiorg/tachiyomi/files/9257280/tachiyomi_crash_logs_1.txt)
![Screenshot_20220804-142955](https://user-images.githubusercontent.com/110590275/182780584-03f8898a-2ab2-43cc-b189-0f60738c18f7.png)

### Tachiyomi version

13.5

### Android version

8.1.0

### Device

Boyue Likebook P6

### Other details

The last version where everything works as it should is 13.1, starting from 13.2 onwards things are broken.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-08-04 13:17
Duplicate of #7006

**Closed by arkon** 2022-08-04 13:17 UTC
Labels: Bug
