### ISSUE TITLE
[Feature Request] <Multi manga migration like j2k>

### ISSUE THREAD

**Issue by ImMapple** [tachiyomiorg/tachiyomi#5246] opened 2021-05-31 04:16 UTC
## Why/User Benefit/User Problem
Since manganelo became manganato I lost over 1037 manga in my library. Multi migration for migrating that manga to a different source so I don't have to migrate one by one

## What/Requirements
A new migration feature on the migrate thing to migrate all the manga.

**Comment by loocool2** [comment] 2021-05-31 04:17
Duplicate of #1729

**Closed by loocool2** 2021-05-31 04:17 UTC
Labels: feature
