### ISSUE TITLE
[Feature Request] Adding Viewing Settings For Categories

### ISSUE THREAD

**Issue by ItsTashi** [tachiyomiorg/tachiyomi#2518] opened 2020-01-19 19:05 UTC
I usually make two categories for Manga and Webtoons. I noticed that in normal cases we have to change the reading view for each manga/webtoon individually or change the reader settings. I thought it would make it easier if there was also a setting to change viewing settings per category

**Comment by LandChit** [comment] 2021-06-02 15:02
This is my concept image![Untitled8.png](https://user-images.githubusercontent.com/78423278/120504335-a0147b00-c3f6-11eb-9034-eb9cc026fb32.png)

**Comment by arkon** [comment] 2023-03-05 23:16
Duplicate of #6337

**Closed by arkon** 2023-03-05 23:16 UTC
Labels: Feature request
