### ISSUE TITLE
top bar not transparent after clicking the title in toolbar in reader

### ISSUE THREAD

**Issue by CVIUS** [tachiyomiorg/tachiyomi#6394] opened 2021-12-27 03:14 UTC
### Steps to reproduce

1. open a chapter
2. click the title on the toolbar to go back to the manga page

### Expected behavior

top bar shud be transparent in edge-to-edge manga details

### Actual behavior

top bar in edge-to-edge manga details is not transparent

### Tachiyomi version

r4045

### Android version

Android 11

### Device

redmi note 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MohitMandalia** [comment] 2022-01-01 18:40
Please post a video or screenshot I am not able to reproduce this may be its giving issue on particular version of Android or on a particular device.

**Comment by CVIUS** [comment] 2022-01-02 04:20
> Please post a video or screenshot I am not able to reproduce this may be its giving issue on particular version of Android or on a particular device.

this is also the same steps to reproduce #6393 

https://user-images.githubusercontent.com/84634607/147866080-31c2a523-1dbc-40b3-88ac-d97f8a8cbde9.mp4

**Comment by MohitMandalia** [comment] 2022-01-04 15:43
ok thanks for the info

**Comment by afreakyelf** [comment] 2022-01-22 03:16
Hi, Can i work on this issue?

**Comment by loocool2** [comment] 2022-01-22 03:17
@afreakyelf work on whatever you want, you don't need to get permission to work on something

**Comment by afreakyelf** [comment] 2022-01-22 03:21
Can you assign it to me?.

**Comment by arkon** [comment] 2022-01-22 03:46
No need, we usually don't assign issues in this project. Comment should be sufficient enough.

**Comment by afreakyelf** [comment] 2022-01-22 03:51
Cool

**Closed** 2022-02-12 15:58 UTC
Labels: Bug
