### ISSUE TITLE
Ability to hide a category, like a "family view"

### ISSUE THREAD

**Issue by schasti** [tachiyomiorg/tachiyomi#6221] opened 2021-11-11 20:14 UTC
### Describe your suggested feature

So you should be able to hide and lock categories, where you can only access them through a fingerprint or code.
So if i open the app normally it doesn't show the category in library, but then i can click like an "eye" icon top right and enter a password to then be able to enter all the locked categories.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2021-11-11 20:17
Duplicate of #1508

**Closed** 2021-11-11 20:17 UTC
Labels: Feature request
