### ISSUE TITLE
Updating library not working properly

### ISSUE THREAD

**Issue by Lordminnion1** [tachiyomiorg/tachiyomi#10351] opened 2024-01-07 23:29 UTC
### Steps to reproduce

1. I swipe down or press the refresh button to update all my manga 3. Nothing appears

### Expected behavior

The chapters should be updating

### Actual behavior

Nothing it shows its updating but its going to fast

### Tachiyomi version

0.15.1

### Android version

Android 9

### Device

Galaxy S8

### Other details

If I manually go through my manga and update them by their self it loads new chapters just not when I do it for all at once

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Lordminnion1** [comment] 2024-01-07 23:39
I closed it because I didn't fully check all the other issues but now I'm reopening it since none of what I saw helped me

**Comment by arkon** [comment] 2024-01-07 23:41
Duplicate of #10151

**Closed by arkon** 2024-01-07 23:41 UTC
Labels: Bug
