### ISSUE TITLE
Tracking support for new platform

### ISSUE THREAD

**Issue by amboxer21** [tachiyomiorg/tachiyomi#9588] opened 2023-06-05 16:33 UTC
### Describe your suggested feature

Can you add support for AP( can't post name or the stupid fucking bot auto closes my feature request) tracking like you have for MAL?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2023-06-05 16:39
Duplicate of #1785.

**Closed by Seishirou101** 2023-06-05 16:39 UTC
Labels: Feature request
