### ISSUE TITLE
Export library data as an excel table

### ISSUE THREAD

**Issue by fkrsr** [tachiyomiorg/tachiyomi#8038] opened 2022-09-19 14:10 UTC
### Describe your suggested feature

Could you please add an option that can export library data as an excel table? At least it includes manga‘s name and author.  I want to make an "already read list", however, it's very difficlut for me to deal all mangas in my library one by one, they are more than 1500+.

By the the way, I wander that if I can updata my library by "sources" or "extensions"?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2022-09-19 14:41
Duplicate of #1393, you can decode the backup and convert it to excel if you want

**Closed by Seishirou101** 2022-09-19 14:41 UTC
Labels: Feature request
