### ISSUE TITLE
An "Exclude mangas in my library" Button

### ISSUE THREAD

**Issue by Retro70** [tachiyomiorg/tachiyomi#8787] opened 2022-12-22 19:45 UTC
### Describe your suggested feature

Just as the title says- the feature allows you to toggle whether you want the mangas you already have in your library be shown or not while browsing an extension (just like how filtering works). For someone like me who reads A LOT of mangas from the same extension, it's a helpful feature for finding new mangas to read rather than just scrolling through the entire feed of said extension. Thanks

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-12-22 20:01
Duplicate of #2941

**Closed** 2022-12-22 20:01 UTC
Labels: Feature request
