### ISSUE TITLE
Storage Convert JPG to AVIF / WEBP 40% 

### ISSUE THREAD

**Issue by aminoginji** [tachiyomiorg/tachiyomi#7719] opened 2022-08-10 21:30 UTC
### Describe your suggested feature

REF [#1526](https://github.com/tachiyomiorg/tachiyomi/pull/1526#issuecomment-846491231) 

The CBZ archives do not address compression of the files. JPG will not compress unless you resize them. The CBZ are the same size as a full folder of JPG. The CBZ archives are nice keeping the JPG bundled together but still do not cut down on space. Add an option to convert the downloaded files to AVIF or WEBP. Both use better compression than JPG dropping a 120kb image down to 80kb WEBP or 70kb AVIF allowing 40% or more manga to fit on someone's device. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-08-10 21:33
Duplicate of #4415

**Closed by arkon** 2022-08-10 21:33 UTC
Labels: Feature request
