### ISSUE TITLE
[Feature Request] <Custom Covers Backup>

### ISSUE THREAD

**Issue by AlexMiniReal** [tachiyomiorg/tachiyomi#4604] opened 2021-03-06 17:11 UTC
## Why/User Benefit/User Problem
(explain why this feature should be added)
It could be useful for people because instead of resetting all the covers by hand it could be done automatically.

## What/Requirements
(explain how this feature would behave)
When you create a backup it should backup also che custom covers you uploaded and when you restore it it should testore the custom covers.

**Comment by curche** [comment] 2021-03-08 17:45
Duplicate of #3851

**Closed** 2021-03-08 18:03 UTC
Labels: feature
