### ISSUE TITLE
[Multiple Migrate] can migrate multiple library to one source same like fork SY

### ISSUE THREAD

**Issue by Andi234Pisces** [tachiyomiorg/tachiyomi#4475] opened 2021-02-14 06:43 UTC
benefit user, if tachiyomi stable can multiple migrates, the for user who have many bookmark library from many source no need to back up and restore to other fork, coz for whom who like tachiyomi stable tobe main drive for reading, they will take along time for restore on tachiyomi fork, 

the problem is back up system usualy all category, but cannot just take some or a part of category we want, ,  so if back up and restore to other fork its to take a long time to just want to migrate many library in a part of category or source,

**Comment by Andi234Pisces** [comment] 2021-02-14 06:46
i have more than 4K library from many source, and my main drive for reading is tachiyomi stable, hope get feature multiple migrate like Fork SY,
and on tab browse on source, can u give labeled 18+, same like tab extension ?

**Comment by joseph619** [comment] 2021-02-14 13:11
Duplicate of #1231

**Closed** 2021-02-14 14:20 UTC
Labels: feature
