### ISSUE TITLE
Per-category update frequency

### ISSUE THREAD

**Issue by dtrazzi** [tachiyomiorg/tachiyomi#822] opened 2017-05-29 00:25 UTC
I follow a lot of manga using the app, and library updates can take a very long time. However, a lot of the manga are weekly or monthly, and therefore don't need to be updated that frequently. 

An option to change the update frequency based on category (either accessible from the three dot menu in the upper right corner in the "My library" screen or under "General" in the settings where "Library Update Frequency" is) would reduce the number of checks needed, while still allowing users to keep up to date with more frequently-updated manga. 

Version: v0.5.2
(Android 7.0 on HTC 10)

**Comment by 9cxndy** [comment] 2022-08-11 09:30
Hi, my issue #6698 is closed as duplicate of this, but my idea in that issue is not represented here. And my issue isn't about per-category update frequency update at all, I don't understand why was it changed to be that.

I will copy from that issue here:

> So instead of update everything all at once, once per update interval; maybe tachiyomi can spread it out into multiple chunks across the whole update interval. The number of chunks could be made configurable.

**Comment by rookiegrammer** [comment] 2022-08-21 07:15
If Tachiyomi really wanted to reduce some of the load on web servers, this should've been a priority IMO.

They should also add a text indicating when each library was last updated. And make it user-friendly to move Manga between libraries.

**Comment by d-najd** [comment] 2022-10-23 19:28
I am looking into this.

**Comment by d-najd** [comment] 2022-11-01 08:04
> Hi, my issue #6698 is closed as duplicate of this, but my idea in that issue is not represented here. And my issue isn't about per-category update frequency update at all, I don't understand why it was changed to be that.
> 
> I will copy from that issue here:
> 
> > So instead of update everything all at once, once per update interval; maybe tachiyomi can spread it out into multiple chunks across the whole update interval. The number of chunks could be made configurable.

I think such feature already exists, code from `LibraryUpdateService`
```
        // Warn when excessively checking a single source
        val maxUpdatesFromSource = mangaToUpdate
            .groupBy { it.manga.source }
            .filterKeys { sourceManager.get(it) !is UnmeteredSource }
            .maxOfOrNull { it.value.size } ?: 0
        if (maxUpdatesFromSource > MANGA_PER_SOURCE_QUEUE_WARNING_THRESHOLD) {
            notifier.showQueueSizeWarningNotification()
        }

```
so unless you are getting notifications it should be fine

**Comment by arkon** [comment] 2023-10-08 20:41
Intelligently skipping updates based on expected release times (#5734) is more hands-off for the user, so opting to just have that rather than this.

**Closed by arkon** 2023-10-08 20:41 UTC
Labels: Feature request
