### ISSUE TITLE
[Feature Request] track series by ratio of height anf number of page

### ISSUE THREAD

**Issue by Noname-noragami** [tachiyomiorg/tachiyomi#4486] opened 2021-02-15 09:59 UTC
## Why/User Benefit/User Problem
(explain why this feature should be added)
b/c some series have very, very long page, or just one page but its  is all series
## What/Requirements
You just need to track by height ratio of page and page numbers or height ratio of series without worry about page numbers
Thanks team that supports, make,  maintain, dev,... In taichiyomi project

**Comment by arkon** [comment] 2021-02-15 14:19
Duplicate of #3322

**Closed by arkon** 2021-02-15 14:19 UTC
Labels: feature
