### ISSUE TITLE
Set default reader mode per source

### ISSUE THREAD

**Issue by tholomew92** [tachiyomiorg/tachiyomi#9884] opened 2023-08-27 11:39 UTC
### Describe your suggested feature

I read a varied amount of manga, manwha and comic books generally from different sources. Allowing me to set the default reader mode per source would make the user experience a lot smoother since I wouldn't need to change the reader mode as often.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-08-27 13:03
Duplicate of #3318

**Closed** 2023-08-27 13:03 UTC
Labels: Feature request
