### ISSUE TITLE
[Feature Request] Add a badge if there is a problem with sync

### ISSUE THREAD

**Issue by i2324561w2** [tachiyomiorg/tachiyomi#4710] opened 2021-03-24 09:29 UTC
(I'm on v0.10.9)
Since problems with sync sometimes happen (at least for me; on MAL; now it was "http error 401"; log-out and log-in fixed it), I suggest to add a badge on History next to the manga if it's not synchronizing. I discovered I had a problem only because I was trying to sync a new manga.

**Comment by scb261** [comment] 2021-03-24 09:39
Duplicate of #4501, just different ways to let user know about it

**Closed** 2021-03-24 12:25 UTC
Labels: feature
