### ISSUE TITLE
Crashing every 5 minute

### ISSUE THREAD

**Issue by vanrenson** [tachiyomiorg/tachiyomi#10304] opened 2024-01-06 23:18 UTC
### Steps to reproduce

Fix it plz

### Expected behavior

Not to crash after latest update

### Actual behavior

Happened after updating to latest version

### Crash logs

https://discord.com/channels/349436576037732353/349436576037732355/1193331497302769714

### Tachiyomi version

0.15.0

### Android version

13

### Device

Samsung Galaxy A04

### Other details

It keeps crashing every 5 minutes

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2024-01-06 23:19
Duplicate of #9720 (already fixed for next release, but you could try clearing your chapter cache from the app's "Data and storage" settings to see if it helps with the frequency).

**Closed by arkon** 2024-01-06 23:19 UTC
Labels: Bug
