### ISSUE TITLE
Migrating sources not working in preview version

### ISSUE THREAD

**Issue by EdwinRodger** [tachiyomiorg/tachiyomi#8047] opened 2022-09-21 16:17 UTC
### Steps to reproduce

Migrate a manga

### Expected behavior

Manga should get searched in the list of extensions

### Actual behavior

App closes/crashes

### Crash logs

This log is taken after reopening the app
[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/9618510/tachiyomi_crash_logs.1.txt)

### Tachiyomi version

r4929

### Android version

11

### Device

Redmi Note 8

### Other details

https://user-images.githubusercontent.com/92982808/191556852-1703dcf2-a0f5-4480-b644-525f293d43cb.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-09-21 16:20
Do you have any obsolete extensions? If so, uninstall them and try migrating again.

**Comment by EdwinRodger** [comment] 2022-09-21 16:23
I don't have any obsolete extension

**Comment by piratefinn** [comment] 2022-09-23 13:41
[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/9634124/tachiyomi_crash_logs.txt)
I'm experiencing the same issue with the same version of the preview on my Poco X4 GT, no obsolete extensions.

**Comment by arkon** [comment] 2022-09-24 13:28
Duplicate of #8049

**Closed by arkon** 2022-09-24 13:28 UTC
Labels: Bug
