### ISSUE TITLE
I can't update my Extentions nor can I install them anymore 

### ISSUE THREAD

**Issue by AppKiller1412** [tachiyomiorg/tachiyomi#6750] opened 2022-03-08 15:50 UTC
### Steps to reproduce

I can't update my Extentions nor can I install new extension through the app I have to manually goto the website and download the extension from there and manually install it.

### Expected behavior

When I press update all it should update all the extension which need to be updated. After I press update all it should start giving promt messages for me to install the new updates.

### Actual behavior

But what happenes instead is that it shows it's downloading but doesnt do anything after that, it just keeps showing me that it's downloading instead of a promt messages for me update.

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/8207604/tachiyomi_crash_logs.txt)

### Tachiyomi version

0.13.1

### Android version

Android 12

### Device

OnePlus 9 pro 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [x] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-03-09 22:34
Duplicate of #6723

Error logs don't show anything useful.

**Closed by arkon** 2022-03-09 22:34 UTC
Labels: Bug
