### ISSUE TITLE
tachiyomi crash when remove favourite manga

### ISSUE THREAD

**Issue by Endowpea** [tachiyomiorg/tachiyomi#9111] opened 2023-02-19 10:07 UTC
### Steps to reproduce

remove favourite manga

### Expected behavior

removed manga will disappear in bookshelf and stay at manga page

### Actual behavior

removed and crash

### Crash logs

--------- beginning of system
--------- beginning of main
02-19 17:55:17.510 31196 28520 E CursorWindow: Failed to read row 747, column 0 from a CursorWindow which has 747 rows, 26 columns.
02-19 17:55:17.529 31196 28561 E ACRA    : ACRA caught a NullPointerException for eu.kanade.tachiyomi
02-19 17:55:17.529 31196 28561 E ACRA    : java.lang.NullPointerException
02-19 17:55:17.529 31196 28561 E ACRA    : 	at tachiyomi.data.data.LibraryViewQueriesImpl$library$1.invoke(DatabaseImpl.kt:17)
02-19 17:55:17.529 31196 28561 E ACRA    : 	at com.squareup.sqldelight.Query.executeAsList(Query.kt:18)
02-19 17:55:17.529 31196 28561 E ACRA    : 	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToList$1$1.invokeSuspend(FlowExtensions.kt:6)
02-19 17:55:17.529 31196 28561 E ACRA    : 	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToList$1$1.invoke(FlowExtensions.kt:13)
02-19 17:55:17.529 31196 28561 E ACRA    : 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:8)
02-19 17:55:17.529 31196 28561 E ACRA    : 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:50)
02-19 17:55:17.529 31196 28561 E ACRA    : 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
02-19 17:55:17.529 31196 28561 E ACRA    : 	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToList$$inlined$map$1$2.emit(Collect.kt:76)
02-19 17:55:17.529 31196 28561 E ACRA    : 	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:2)
02-19 17:55:17.529 31196 28561 E ACRA    : 	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:18)
02-19 17:55:17.529 31196 28561 E ACRA    : 	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:1)
02-19 17:55:17.529 31196 28561 E ACRA    : 	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$asFlow$1.invokeSuspend(FlowExtensions.kt:120)
02-19 17:55:17.529 31196 28561 E ACRA    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
02-19 17:55:17.529 31196 28561 E ACRA    : 	at kotlinx.coroutines.flow.internal.SafeCollector.invokeSuspend(SafeCollector.kt:22)
02-19 17:55:17.529 31196 28561 E ACRA    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
02-19 17:55:17.529 31196 28561 E ACRA    : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
02-19 17:55:17.529 31196 28561 E ACRA    : 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
02-19 17:55:17.529 31196 28561 E ACRA    : 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
02-19 17:55:17.529 31196 28561 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
02-19 17:55:17.529 31196 28561 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:63)
02-19 17:55:17.529 31196 28561 E ACRA    : 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [CoroutineName(eu.kanade.tachiyomi.ui.library.LibraryTab:eu.kanade.tachiyomi.ui.library.LibraryScreenModel:default:ScreenModelCoroutineScope), StandaloneCoroutine{Cancelling}@45ff5d9, Dispatchers.IO]
02-19 17:55:17.825 29718 29718 E .tachiyomi:acr: Not starting debugger since process cannot load the jdwp agent.
02-19 17:55:18.034 29718 29742 E SQLiteLog: (283) recovered 377 frames from WAL file /data/user/0/eu.kanade.tachiyomi/databases/tachiyomi.db-wal
02-19 17:55:19.634 29770 29770 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
02-19 17:55:19.767 29770 29806 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
02-19 17:55:20.754 29770 29942 E SQLiteLog: (284) automatic index on C(manga_id)
02-19 17:55:20.754 29770 29942 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
02-19 17:57:43.284 29770 29770 E libc    : Access denied finding property "ro.vendor.df.effect.conflict"
02-19 17:57:43.284 29770 29770 E libc    : Access denied finding property "ro.vendor.knock.type"
02-19 17:57:49.166 32716 32716 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
02-19 17:57:49.359 32716 32750 E SQLiteLog: (283) recovered 5 frames from WAL file /data/user/0/eu.kanade.tachiyomi/databases/tachiyomi.db-wal
02-19 17:57:50.581 32716   693 E SQLiteLog: (284) automatic index on C(manga_id)
02-19 17:57:50.581 32716   693 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
02-19 17:58:45.662 32716   681 E CursorWindow: Failed to read row 747, column 0 from a CursorWindow which has 747 rows, 26 columns.
02-19 17:58:45.678 32716   623 E ACRA    : ACRA caught a NullPointerException for eu.kanade.tachiyomi
02-19 17:58:45.678 32716   623 E ACRA    : java.lang.NullPointerException
02-19 17:58:45.678 32716   623 E ACRA    : 	at tachiyomi.data.data.LibraryViewQueriesImpl$library$1.invoke(DatabaseImpl.kt:17)
02-19 17:58:45.678 32716   623 E ACRA    : 	at com.squareup.sqldelight.Query.executeAsList(Query.kt:18)
02-19 17:58:45.678 32716   623 E ACRA    : 	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToList$1$1.invokeSuspend(FlowExtensions.kt:6)
02-19 17:58:45.678 32716   623 E ACRA    : 	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToList$1$1.invoke(FlowExtensions.kt:13)
02-19 17:58:45.678 32716   623 E ACRA    : 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:8)
02-19 17:58:45.678 32716   623 E ACRA    : 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:50)
02-19 17:58:45.678 32716   623 E ACRA    : 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
02-19 17:58:45.678 32716   623 E ACRA    : 	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToList$$inlined$map$1$2.emit(Collect.kt:76)
02-19 17:58:45.678 32716   623 E ACRA    : 	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:2)
02-19 17:58:45.678 32716   623 E ACRA    : 	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:18)
02-19 17:58:45.678 32716   623 E ACRA    : 	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:1)
02-19 17:58:45.678 32716   623 E ACRA    : 	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$asFlow$1.invokeSuspend(FlowExtensions.kt:120)
02-19 17:58:45.678 32716   623 E ACRA    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
02-19 17:58:45.678 32716   623 E ACRA    : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
02-19 17:58:45.678 32716   623 E ACRA    : 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
02-19 17:58:45.678 32716   623 E ACRA    : 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
02-19 17:58:45.678 32716   623 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
02-19 17:58:45.678 32716   623 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:63)
02-19 17:58:45.678 32716   623 E ACRA    : 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [CoroutineName(eu.kanade.tachiyomi.ui.library.LibraryTab:eu.kanade.tachiyomi.ui.library.LibraryScreenModel:default:ScreenModelCoroutineScope), StandaloneCoroutine{Cancelling}@a7a9446, Dispatchers.IO]
02-19 17:58:45.982  2438  2438 E .tachiyomi:acr: Not starting debugger since process cannot load the jdwp agent.
02-19 17:58:46.123  2438  2475 E SQLiteLog: (283) recovered 11 frames from WAL file /data/user/0/eu.kanade.tachiyomi/databases/tachiyomi.db-wal
02-19 17:58:47.034  2498  2498 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
02-19 17:58:47.165  2498  2591 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
02-19 17:58:48.137  2498  2760 E SQLiteLog: (284) automatic index on C(manga_id)
02-19 17:58:48.137  2498  2760 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.14.4 (standard, 477e3d9, 95, 2023-02-05T15:37Z)
Android version: 11 (SDK 30)
Android build ID: RKQ1.200826.002 test-keys
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: enuma
Device model: M2105K81C
Device product name: enuma

### Tachiyomi version

0.14.4

### Android version

Android 11

### Device

MI pad5 pro

### Other details

because I have 10000+ favourited manga and every remove behavior will crash app

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-02-19 15:36
Duplicate of #7997

**Closed by arkon** 2023-02-19 15:36 UTC
Labels: Bug
