### ISSUE TITLE
Firefox 'open in app' feature: bottom menu not hiding anymore

### ISSUE THREAD

**Issue by bieel1503** [tachiyomiorg/tachiyomi#6244] opened 2021-11-17 18:14 UTC
### Steps to reproduce

video:

https://user-images.githubusercontent.com/42154006/142257355-93cde0b9-0fcb-4e61-8c98-6de27eca4406.mp4

### Expected behavior

Bottom menu should hide in this case.

### Actual behavior

Bottom menu doesn't hide and stays on top of selected chapter context menu.

### Tachiyomi version

0.12.3

### Android version

Android 11

### Device

Redmi Note 6 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by vengiare** [comment] 2021-11-17 20:46
I believe this is a duplicate of #6012

**Closed** 2021-11-19 15:18 UTC
Labels: Bug
