### ISSUE TITLE
Grouping in updates Tab

### ISSUE THREAD

**Issue by VGFlash** [tachiyomiorg/tachiyomi#9356] opened 2023-04-17 17:55 UTC
### Describe your suggested feature

Hi Team,
Below is the specification for a feature request.

Currently when I update a manga and if it had multiple chapter being updated. They are all listed in the update tab as seperate. Can we group them together. 
![IMG_20230417_231824](https://user-images.githubusercontent.com/78352889/232568259-8b1100fa-3583-44a0-99cd-263d762d8850.jpg)

Thanks for your consideration.

Below are the points which will be improved because of this 

1. It will have less clutter and it will be more organized.
2. Users will be able to see all the unique manga/manhwa they are reading and check which of them received updates at a glance.

Regards,
VGFlash

[ Thanks for the great app, Team 👍 ]

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2023-04-17 17:56
Duplicate of #2774

**Closed by Seishirou101** 2023-04-17 17:56 UTC
Labels: Feature request
