### ISSUE TITLE
Half-page zoom (2x zoom)

### ISSUE THREAD

**Issue by bosslamas** [tachiyomiorg/tachiyomi#9189] opened 2023-03-09 17:46 UTC
### Describe your suggested feature

I've recently stopped using Neko, because it's unable to retrieve chapters from mangadex from certain mangas, so I've switched back to Tachiyomi. Unfortunately, the biggest reason why I switched to Neko in the first place is the half page zoom, where when reading a double page, it would automatically zoom to a 2x, showing half of the page (so i could easily tap or scroll to read everything). Instead, Tachiyomi only allows either fit width, height, or fill screen. Fill screen is the worst, and gives a claustrophobic experience when reading. Not only that, but my screen corner are chamfered (round), so I can't see everything.

Please, add the half-page zoom option into Tachiyomi. I hate having to zoom manually in double pages.

Thank you very much.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment] 2023-03-09 18:18
Have you tried enabling the  "Zoom Landscape Image" setting?
Have a look at the [video demo](https://cdn.discordapp.com/attachments/566585518171881493/942312591231954944/screencam_20220213_122135.mp4) of the setting, because it looks to me like what you needed
It is a main Tachiyomi feature which was added to Neko

> I've recently stopped using Neko, because it's unable to retrieve chapters from mangadex from certain mangas
Create an issue in Neko github repo or just ask in the #neko-for-mangadex channel in [our Discord](https://discord.gg/tachiyomi)

**Comment by GameBle** [comment] 2023-03-10 14:50
@curche exactly

**Comment by stevenyomi** [comment] 2023-03-11 17:58
Duplicate of #8825

**Closed by stevenyomi** 2023-03-11 17:58 UTC
Labels: Feature request
