### ISSUE TITLE
Edit the informations

### ISSUE THREAD

**Issue by eouuuu** [tachiyomiorg/tachiyomi#6281] opened 2021-11-26 22:28 UTC
### Describe your suggested feature

Please add the feature to edit the information on a manga. Sometimes it’s annoying to look at, especially the titles. For example the mangas on nhentai, they’re very annoying to track since I need to delete words on every manga. Please add it, Thank you. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2021-11-26 22:30
Duplicate of #4398

**Closed by arkon** 2021-11-26 22:30 UTC
Labels: Feature request
