### ISSUE TITLE
[Feature Request] Zoom with long press

### ISSUE THREAD

**Issue by garulovilla** [tachiyomiorg/tachiyomi#4827] opened 2021-04-12 18:39 UTC
## Why/User Benefit/User Problem
Sometimes, there are manga or comics that contain a dialogue with very small letters or details that you want to see quickly without the need to do a double-tap zoom or a two-finger zoom.

## What/Requirements
Show a small zoom box in the corner when long press is trigger. It would help to quickly zoom without the need to zoom the page. This idea comes from the Perfect Viewer app.
This option could be placed as optional in: Settings > Reader, and the user can choose the option to perform when long tap is trigger. As a user, you could choose between the current option "Show long tab dialog" and the new option "Show Magnifier". Maybe put another option to specify "how much magnification" should be applied (0.5, 1.5, 2.0, etc.) depending on the size of the image or taking into account the resolution, I don't know.

![Magnifier](https://user-images.githubusercontent.com/4468146/114441487-13390800-9b91-11eb-9ba8-34d9fe7ca532.jpg)

**Comment by arkon** [comment] 2021-04-12 18:49
Duplicate of #2599

**Closed by arkon** 2021-04-12 18:49 UTC
Labels: feature
