### ISSUE TITLE
[Bug] unless i am reading downloaded chapters, the reader crashes within seconds of opening a chapter.

### ISSUE THREAD

**Issue by solidunicorn6** [tachiyomiorg/tachiyomi#5172] opened 2021-05-24 15:08 UTC
If I miss anything major I am sorry, normally I just sit through till the next patch and don't really scroll through these pages.

It has happened every time I try reading undownloaded chapters for the last 2 days. 

I was just going to leave it and start downloading before I read, but its started crashing while downloading too.

## Device information
* Tachiyomi version: 0.10.12
* Android version: 10
* Device: SM-G960U

**Comment by arkon** [comment] 2021-05-24 15:09
As the template said:

> If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.

**Comment by solidunicorn6** [comment] 2021-05-24 15:19
> As the template said:
> 
> > If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.

I was going to get them just now, reader crashes twice. Finally got them open and they were clean. Is this normal?

**Comment by solidunicorn6** [comment] 2021-05-24 16:28
Here's a crash log that actually came in.

05-24 11:22:04.991  9152  9152 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
05-24 11:22:20.110  9152 23865 E ACRA    : ACRA caught a IllegalStateException for eu.kanade.tachiyomi
05-24 11:22:20.110  9152 23865 E ACRA    : java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
05-24 11:22:20.110  9152 23865 E ACRA    : 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:57)
05-24 11:22:20.110  9152 23865 E ACRA    : 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
05-24 11:22:20.110  9152 23865 E ACRA    : 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05-24 11:22:20.110  9152 23865 E ACRA    : 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
05-24 11:22:20.110  9152 23865 E ACRA    : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-24 11:22:20.110  9152 23865 E ACRA    : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-24 11:22:20.110  9152 23865 E ACRA    : 	at java.lang.Thread.run(Thread.java:919)
05-24 11:22:20.110  9152 23865 E ACRA    : Caused by: rx.exceptions.OnErrorNotImplementedException: java.lang.Exception: Failed to bypass Cloudflare
05-24 11:22:20.110  9152 23865 E ACRA    : 	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386)
05-24 11:22:20.110  9152 23865 E ACRA    : 	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383)
05-24 11:22:20.110  9152 23865 E ACRA    : 	at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
05-24 11:22:20.110  9152 23865 E ACRA    : 	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:153)
05-24 11:22:20.110  9152 23865 E ACRA    : 	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
05-24 11:22:20.110  9152 23865 E ACRA    : 	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onError(OnSubscribeMap.java:88)
05-24 11:22:20.110  9152 23865 E ACRA    : 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
05-24 11:22:20.110  9152 23865 E ACRA    : 	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1$requestArbiter$1.request(OkHttpExtensions.kt:43)
05-24 11:22:20.110  9152 23865 E ACRA    : 	at rx.Subscriber.setProducer(Subscriber.java:209)
05-24 11:22:20.110  9152 23865 E ACRA    : 	at rx.Subscriber.setProducer(Subscriber.java:205)
05-24 11:22:20.110  9152 23865 E ACRA    : 	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
05-24 11:22:20.110  9152 23865 E ACRA    : 	at rx.Subscriber.setProducer(Subscriber.java:205)
05-24 11:22:20.110  9152 23865 E ACRA    : 	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1.call(OkHttpExtensions.kt:58)
05-24 11:22:20.110  9152 23865 E ACRA    : 	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1.call(OkHttpExtensions.kt:26)
05-24 11:22:20.110  9152 23865 E ACRA    : 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
05-24 11:22:20.110  9152 23865 E ACRA    : 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
05-24 11:22:20.110  9152 23865 E ACRA    : 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
05-24 11:22:20.110  9152 23865 E ACRA    : 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
05-24 11:22:20.110  9152 23865 E ACRA    : 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
05-24 11:22:20.110  9152 23865 E ACRA    : 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
05-24 11:22:20.110  9152 23865 E ACRA    : 	at rx.Observable.subscribe(Observable.java:10423)
05-24 11:22:20.110  9152 23865 E ACRA    : 	at rx.Observable.subscribe(Observable.java:10390)
05-24 11:22:20.110  9152 23865 E ACRA    : 	at rx.Observable.subscribe(Observable.java:10195)
05-24 11:22:20.110  9152 23865 E ACRA    : 	at eu.kanade.tachiyomi.multisrc.madara.Madara.fetchPageList(Madara.kt:616)
05-24 11:22:20.110  9152 23865 E ACRA    : 	at eu.kanade.tachiyomi.data.download.Downloader$downloadChapter$1.call(Downloader.kt:285)
05-24 11:22:20.110  9152 23865 E ACRA    : 	at eu.kanade.tachiyomi.data.download.Downloader$downloadChapter$1.call(Downloader.kt:49)
05-24 11:22:20.110  9152 23865 E ACRA    : 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
05-24 11:22:20.110  9152 23865 E ACRA    : 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
05-24 11:22:20.110  9152 23865 E ACRA    : 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
05-24 11:22:20.110  9152 23865 E ACRA    : 	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
05-24 11:22:20.110  9152 23865 E ACRA    : 	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
05-24 11:22:20.110  9152 23865 E ACRA    : 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
05-24 11:22:20.110  9152 23865 E ACRA    : 	... 6 more
05-24 11:22:20.110  9152 23865 E ACRA    : Caused by: java.io.IOException: java.lang.Exception: Failed to bypass Cloudflare
05-24 11:22:20.110  9152 23865 E ACRA    : 	at eu.kanade.tachiyomi.network.CloudflareInterceptor.intercept(CloudflareInterceptor.kt:75)
05-24 11:22:20.110  9152 23865 E ACRA    : 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
05-24 11:22:20.110  9152 23865 E ACRA    : 	at eu.kanade.tachiyomi.network.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:19)
05-24 11:22:20.110  9152 23865 E ACRA    : 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
05-24 11:22:20.110  9152 23865 E ACRA    : 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
05-24 11:22:20.110  9152 23865 E ACRA    : 	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
05-24 11:22:20.110  9152 23865 E ACRA    : 	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1$requestArbiter$1.request(OkHttpExtensions.kt:36)
05-24 11:22:20.110  9152 23865 E ACRA    : 	... 30 more
05-24 11:22:20.110  9152 23865 E ACRA    : Caused by: java.lang.Exception: Failed to bypass Cloudflare
05-24 11:22:20.110  9152 23865 E ACRA    : 	at eu.kanade.tachiyomi.network.CloudflareInterceptor.resolveWithWebView(CloudflareInterceptor.kt:168)
05-24 11:22:20.110  9152 23865 E ACRA    : 	at eu.kanade.tachiyomi.network.CloudflareInterceptor.intercept(CloudflareInterceptor.kt:69)
05-24 11:22:20.110  9152 23865 E ACRA    : 	... 36 more
05-24 11:22:20.443 24203 24203 E .tachiyomi:acr: Not starting debugger since process cannot load the jdwp agent.
05-24 11:25:26.370 12670 12670 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
05-24 11:25:28.357 12670 25165 E SQLiteLog: (284) automatic index on C(manga_id)
05-24 11:25:28.357 12670 25165 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)

**Comment by arkon** [comment] 2021-05-24 16:29
Thanks. Looks like a duplicate of #5151.

**Closed by arkon** 2021-05-24 16:29 UTC
Labels: bug
