### ISSUE TITLE
Categories scroll position incorrect after changing tabs

### ISSUE THREAD

**Issue by mm12** [tachiyomiorg/tachiyomi#7060] opened 2022-05-02 03:44 UTC
### Steps to reproduce

1) have enough categories where you can scroll between them. 
2) change tabs (ie, to updates or history) and change back

### Expected behavior

the selected category should remain where it was before changing tabs

### Actual behavior

the category is scrolled from where it should be, often off-screen 

### Tachiyomi version

0.13.4

### Android version

Android 12

### Device

Google Pixel 3

### Other details

possibly related to #6860

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by CVIUS** [comment] 2022-05-02 12:15
Duplicate of #7043(?)

**Closed** 2022-05-02 12:34 UTC
Labels: Bug
