### ISSUE TITLE
anilist set entry private 

### ISSUE THREAD

**Issue by Jeluxe** [tachiyomiorg/tachiyomi#10272] opened 2023-12-26 22:21 UTC
### Describe your suggested feature

I want when I add tracking to an entry to have some checkbox that indicates whether to make the entry private or not.

### Other details

and I already checked that in the schema of their create/update entry, there is a property called private which boolean.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Jeluxe** [comment] 2023-12-26 22:23
![Screenshot 2023-12-27 002234](https://github.com/tachiyomiorg/tachiyomi/assets/59278268/ab5d54d1-319b-4dd3-b8ec-e03baeac6727)

**Comment by arkon** [comment] 2023-12-26 22:32
Duplicate of #1671

**Closed by arkon** 2023-12-26 22:32 UTC
Labels: Feature request
