### ISSUE TITLE
AniList HTTP error 400

### ISSUE THREAD

**Issue by Neverdusk** [tachiyomiorg/tachiyomi#9254] opened 2023-03-24 05:52 UTC
### Steps to reproduce

When adding AniList to a new manga:
1. Open a library manga.
2. Click "trackers"
3. Click "Add Tracking" for AniList
4. Receive an "HTTP error 400" page

When viewing a manga that already has AniList tracking:
1. Open a library manga.
2. Click "trackers"
3. A popup appears saying "AniList error: HTTPS error 400"

Aside from these error messages, tracking is no longer copied to AniList. I only realized this now, but AniList hasn't updated for any of my Tachiyomi manga in 4 weeks. 

### Expected behavior

You should be able to add AniList as a tracker, similar to MyAnimeList, and have it update AniList.

### Actual behavior

You cannot enter AniList as a new tracker on any manga. On manga that already have AniList tracking, AniList isn't updated.

### Tachiyomi version

0.14.5

### Android version

Android 11

### Device

TCL 20xe

### Other details

This currently affects all manga I have on Tachiyomi, regardless of source.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment] 2023-03-24 06:29
Duplicate of #8013

**Closed by scb261** 2023-03-24 06:29 UTC
Labels: Bug
