### ISSUE TITLE
Crash issue

### ISSUE THREAD

**Issue by Pipixel** [tachiyomiorg/tachiyomi#10132] opened 2023-11-12 13:32 UTC
### Steps to reproduce

reduce and reopen the app, I don't understand why

### Expected behavior

Reopen without crashing

### Actual behavior

I'm not sure but I believe I have reduced the app with the in-app webview open

### Crash logs

Crash logs :
[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/13328096/tachiyomi_crash_logs.txt)

Crash report:
![Screenshot_2023-11-12-14-16-16-41](https://github.com/tachiyomiorg/tachiyomi/assets/66361896/e96e714e-a0cb-4a05-b34c-1003b2087ad9)

### Tachiyomi version

0.14.7

### Android version

Android 13

### Device

Oneplus 8T

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-11-13 03:34
Duplicate of #9352

**Closed by arkon** 2023-11-13 03:34 UTC
Labels: Bug
