### ISSUE TITLE
Add a section where you can see the completed download chapters and view from there directly

### ISSUE THREAD

**Issue by yurishein** [tachiyomiorg/tachiyomi#7456] opened 2022-07-04 15:54 UTC
### Describe your suggested feature

its a hassle to find your completed downloads when you have many categories so i suggest to put a section (or botton/what is it called) to view your completed downloads not only on notifications but on the app itself. And when you click the certain 'completed downloaded series' you can directly read it when you click it.

### Other details

(Hope you understand huhu)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by zbue** [comment] 2022-07-06 01:05
You can simply create a new category, include all your manga in your newly created category, then enable downloaded filter.

**Comment by AntsyLich** [comment] 2022-07-07 14:47
Updates only contains chapters that were uploaded in last 3 months.

**Comment by hyoretsu** [comment] 2022-07-09 15:29
> Updates only contains chapters that were uploaded in last 3 months.

I've got stuff from September 2021 there

**Comment by arkon** [comment] 2022-07-09 16:45
Duplicate of #2177

**Closed by arkon** 2022-07-09 16:45 UTC
Labels: Feature request
