### ISSUE TITLE
Auto Scroll

### ISSUE THREAD

**Issue by staticshock129** [tachiyomiorg/tachiyomi#8308] opened 2022-10-28 17:09 UTC
### Describe your suggested feature

this app is perfect but for me it lack just one thing auto scroll which helps in scrolling without lifting a finger hopefully you will take my request in consideration 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-10-28 17:10
Duplicate of #2093

**Closed by arkon** 2022-10-28 17:10 UTC
Labels: Feature request
