### ISSUE TITLE
show two images in one page

### ISSUE THREAD

**Issue by wzzdsz** [tachiyomiorg/tachiyomi#9903] opened 2023-09-03 08:36 UTC
### Describe your suggested feature

Put two images in one page so it's easier to read on the pad.

### Other details

![Screenshot_20230903_163402_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/113838793/8f78ac6c-b06b-4bcd-b95f-e393ff6b5946)
just worked like many tankōbon shows in app

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment] 2023-09-03 08:40
Duplicate of #149

**Closed by AntsyLich** 2023-09-03 08:40 UTC
Labels: Feature request
