### ISSUE TITLE
[Feature Request] Can customize extensions and library categories colour

### ISSUE THREAD

**Issue by 54RaSuWi** [tachiyomiorg/tachiyomi#4882] opened 2021-04-17 05:01 UTC
## Why/User Benefit/User Problem
Customize extensions and library categories colour

## What/Requirements
Coloured extensions and library categories enabled.

Since grouping extension seem impossiblle. Maybe customize extensions and library colour possible to identify "what source is it"
Sorry if this request already exist since im new on github and english not my native languange.

**Comment by arkon** [comment] 2021-04-17 14:25
For categories, duplicate of #3073. I'll make a note of the extensions there too.

**Closed by arkon** 2021-04-17 14:25 UTC
Labels: feature
