### ISSUE TITLE
Automatically download next chapter

### ISSUE THREAD

**Issue by Rafaeruo** [tachiyomiorg/tachiyomi#6193] opened 2021-11-03 14:21 UTC
### Describe your suggested feature

Have a toggle in settings to allow the next chapter to be automatically downloaded while reading the current one.

### Other details

Example: with the option toggled on, as soon as the user enters chapter 1, chapter 2 (if exists) should start downloading.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment] 2021-11-03 14:56
Duplicate of #3295

**Closed by loocool2** 2021-11-03 14:56 UTC
Labels: Feature request
