### ISSUE TITLE
[Feature Request] ask the user to delete chapters when migrating to a different source

### ISSUE THREAD

**Issue by MrAndre96** [tachiyomiorg/tachiyomi#3529] opened 2020-07-26 23:19 UTC
### Why/User Benefit/User Problem
Currently when you migrate from a source for a manga and you had downloaded chapters in the previous source they will stay which takes in unwanted space.

### What/Requirements
When you migrate you get a popup like when you unfavorite a source to delete the chapters you had downloaded before for the source you had migrated from.

**Comment by arkon** [comment] 2023-07-16 03:27
Duplicate of #9153

**Closed by arkon** 2023-07-16 03:27 UTC
Labels: Feature request
