### ISSUE TITLE
Light Novel Support?

### ISSUE THREAD

**Issue by 1-minute-to-midnight** [tachiyomiorg/tachiyomi#9821] opened 2023-08-07 04:23 UTC
### Describe your suggested feature

Can Light Novel Support be added? It should be able to parse text from various websites and have extensions that can be updated at any time from within the app. Look at this project for reference: https://www.github.com/lnreader/lnreader. This project has some good stuff but is not nearly as refined as Tachiyomi. 

### Other details

It could have two different modes to switch between: Manga mode and Light Novel Mode. The interface and other features (like categories) can stay pretty much the same.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by THElegend5** [comment] 2023-08-07 04:27
Duplicate of #685

**Closed** 2023-08-07 04:28 UTC
Labels: Feature request
