### ISSUE TITLE
Direct Link to Chapter On Site

### ISSUE THREAD

**Issue by Webmetz** [tachiyomiorg/tachiyomi#5678] opened 2021-08-09 05:25 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

Have a button or context menu on each chapter that allows us to go to the webpage containing for the chapter without needing to go through the base webpqge page for the Manga.

**Comment by arkon** [comment] 2021-08-09 12:18
This is impossible with the current architecture. To be addressed in the 1.x rewrite.

**Closed by arkon** 2021-08-09 12:18 UTC
Labels: Feature request

**Comment by arkon** [comment] 2021-08-09 13:11
Anyway I misread this as chapter deeplinks. 

Duplicate of #4770

**Comment by arkon** [comment] 2021-08-09 13:13
tehepelo
