### ISSUE TITLE
NullPointerException while checking for updated mangas

### ISSUE THREAD

**Issue by SqueezedByte** [tachiyomiorg/tachiyomi#9984] opened 2023-10-05 08:55 UTC
### Steps to reproduce

Launch a refresh of last updated

### Expected behavior

To check for updated manga without crash

### Actual behavior

Is not a always reproducible error. Sometimes it keep crashing every time , sometime after have checked a number of item, sometimes it not crash at all.

### Crash logs

------- beginning of main
10-05 10:47:22.969  5606  5652 E CursorWindow: Failed to read row 2142, column 0 from a CursorWindow which has 2142 rows, 14 columns.
10-05 10:47:22.972  5606  5606 E ACRA    : ACRA caught a NullPointerException for eu.kanade.tachiyomi
10-05 10:47:22.972  5606  5606 E ACRA    : java.lang.NullPointerException
10-05 10:47:22.972  5606  5606 E ACRA    :  at tachiyomi.data.data.UpdatesViewQueriesImpl$updates$1.invoke(DatabaseImpl.kt:19)
10-05 10:47:22.972  5606  5606 E ACRA    :  at com.squareup.sqldelight.Query.executeAsList(Query.kt:18)
10-05 10:47:22.972  5606  5606 E ACRA    :  at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToList$1$1.invokeSuspend(FlowExtensions.kt:6)
10-05 10:47:22.972  5606  5606 E ACRA    :  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
10-05 10:47:22.972  5606  5606 E ACRA    :  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
10-05 10:47:22.972  5606  5606 E ACRA    :  at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
10-05 10:47:22.972  5606  5606 E ACRA    :  at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
10-05 10:47:22.972  5606  5606 E ACRA    :  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
10-05 10:47:22.972  5606  5606 E ACRA    :  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:63)
10-05 10:47:22.972  5606  5606 E ACRA    :  Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@fbdff8b, Dispatchers.Main.immediate]
10-05 10:47:32.106  6077  6110 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
10-05 10:47:32.147  6077  6150 E chromium: [1005/104732.147004:ERROR:variations_seed_loader.cc(69)] Failed to open file for reading. Errno: 2
10-05 10:47:32.877  6077  6309 E SQLiteLog: (284) automatic index on C(manga_id)
10-05 10:47:32.877  6077  6309 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.14.6 (standard, c615f4d, 101, 2023-04-16T15:14Z)
Android version: 14 (SDK 34)
Android build ID: UP1A.231005.007
Device brand: google
Device manufacturer: Google
Device name: cheetah
Device model: Pixel 7 Pro
Device product name: cheetah

### Tachiyomi version

0.14.6

### Android version

Android 14

### Device

Pixel 7 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-10-06 02:24
Duplicate of #8400

**Closed by arkon** 2023-10-06 02:24 UTC
Labels: Bug
