### ISSUE TITLE
[Feature Request] DualPage Split

### ISSUE THREAD

**Issue by ImPudding-tech** [tachiyomiorg/tachiyomi#4288] opened 2021-01-13 09:06 UTC
Ability to auto split DualPages
**Current**(Fit Screen) 
![Screenshot_20210111_221620_eu kanade tachiyomi](https://user-images.githubusercontent.com/65703094/104429684-de80d900-55c0-11eb-92db-6ae85d201efc.jpg)
**Current** (Smart Fit) it Consumes the Whole Screen
![Screenshot_20210111_221636_eu kanade tachiyomi](https://user-images.githubusercontent.com/65703094/104429797-f9534d80-55c0-11eb-9de6-fca9f1b1e313.jpg)
**Request** Looks Like A Normal Page
![Screenshot_20210111_221628_eu kanade tachiyomi](https://user-images.githubusercontent.com/65703094/104430254-66ff7980-55c1-11eb-97a7-041565ad0cdb.jpg)

**Comment by ghostbear** [comment] 2021-01-13 10:03
Duplicate of #1384

**Closed** 2021-01-13 12:32 UTC
Labels: feature
