### ISSUE TITLE
[Bug] <you can't use the area outside the webtoon to scroll>

### ISSUE THREAD

**Issue by uomar8** [tachiyomiorg/tachiyomi#4400] opened 2021-02-07 16:18 UTC
## Device information
App version: 0.10.8 (standard, 45a19d1, 55)
Android version: 9 (SDK 28)
Android build ID: PPR1.180610.011.T825JXU3CTE1
Device brand: samsung
Device manufacturer: samsung
Device name: gts3llte
Device model: SM-T825
Device product name: gts3lltexx

## Steps to reproduce
1. Zoom out from webtoon ( use webtoon or vertical view)
2. Try to scroll from the right and left edge 
![1612714082455](https://user-images.githubusercontent.com/7046347/107152406-b6df1f80-6978-11eb-89ca-e4fca20c9f37.jpg)

### Expected behavior
It will always me to scroll

### Actual behavior
It doesn't scroll you need to scroll from the area display the webtoon

**Comment by scb261** [comment] 2021-02-07 17:29
Duplicate of #3127

**Closed** 2021-02-07 17:30 UTC
Labels: bug
