### ISSUE TITLE
[Feature Request] <backup covers >

### ISSUE THREAD

**Issue by boybeast** [tachiyomiorg/tachiyomi#3851] opened 2020-09-27 06:02 UTC
## Why/User Benefit/User Problem
The app allows the user to change the cover of favorite works and thus build a nice library, however when he needs to do a backup restoration he loses his personalized cover choices, it would be interesting if the user could choose the  option to backup the covers as if they were miniatures saved directly in the backup file as well as the information of the favorite works.

## What/Requirements
this feature would be an option that the user may or may not use at the time of making a backup, it will allow the user to choose to back up their library covers, obviously the backup would be larger in size as it would include the covers in it, and  when restoring these backups he will only restore the covers that correspond with the other information of the favorite work such as source, category and others, it does not have to be a mandatory resource, but optional for the user.

**Comment by arkon** [comment] 2021-11-19 22:20
Duplicate of #5836

**Closed by arkon** 2021-11-19 22:20 UTC
Labels: Feature request
