### ISSUE TITLE
Introduce "branch" concept for chapter grouping by translators in extensions

### ISSUE THREAD

**Issue by MWGuy** [tachiyomiorg/tachiyomi#6816] opened 2022-03-25 07:46 UTC
### Describe your suggested feature

On many sites you can find many translation branches of the same manga. I propose to add the ability to select a translation branch by the user, as well as to allow extensions to offer the user more than one translation branch.

I think this feature will solve a lot of problems in extensions for sites such as mangadex, mangalib (hentailib), readmanga, remanga and many others.

As a developer of one of these sites, I think that we need to let the user choose the best translation for him.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-03-25 12:00
Duplicate of #969

**Closed by arkon** 2022-03-25 12:00 UTC
Labels: Feature request
