### ISSUE TITLE
Per-category filter

### ISSUE THREAD

**Issue by zerakori** [tachiyomiorg/tachiyomi#7859] opened 2022-08-25 18:35 UTC
### Describe your suggested feature

The filter should also be different for each category 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2022-08-25 18:39
duplicate of #305

**Closed by Seishirou101** 2022-08-25 18:39 UTC
Labels: Feature request
