### ISSUE TITLE
Keyboard Input not working properly

### ISSUE THREAD

**Issue by Haprus** [tachiyomiorg/tachiyomi#8807] opened 2022-12-27 07:43 UTC
### Steps to reproduce

Go to `Browse > Extensions`.

Type in the searchbox.

### Expected behavior

It shouldn't lag.

### Actual behavior

https://user-images.githubusercontent.com/84674702/209630051-b66ac5ae-ae13-406d-9107-8f1a8b54d66c.mp4

### Tachiyomi version

0.14.2

### Android version

A13

### Device

Redmi Note 9S

### Other details

This doesn't seem to happen on other searchboxes. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2023-01-31 17:27
Duplicate of #8469

**Closed by stevenyomi** 2023-01-31 17:27 UTC
Labels: Bug
