### ISSUE TITLE
[Feature Request]  Alternative name

### ISSUE THREAD

**Issue by e-shl** [tachiyomiorg/tachiyomi#4303] opened 2021-01-17 05:09 UTC
## Why/User Benefit/User Problem
Sites have alternative titles or titles in other languages ​​and users want to see the manga title in their native language
![image](https://user-images.githubusercontent.com/35057681/104831565-fc458b00-58ab-11eb-900b-66aade694b51.png)
https://github.com/tachiyomiorg/tachiyomi-extensions/commit/a28d14fc698f9fa7cb230b68fe8823b012f739e1
https://github.com/tachiyomiorg/tachiyomi-extensions/commit/f9ac810129590a3df771acef88dd754b90b7b73c (something similar)
![image](https://user-images.githubusercontent.com/35057681/104831708-319ea880-58ad-11eb-9503-b2952f5ecd08.png)
## What/Requirements
Add a separate field for alternative names (the ability to add such names through the extension)

**Comment by scb261** [comment] 2021-01-17 12:02
Duplicate of #2190

**Closed** 2021-01-17 14:22 UTC
Labels: feature
