### ISSUE TITLE
[Bug] downloaded chapters don't get deleted

### ISSUE THREAD

**Issue by mraleksander** [tachiyomiorg/tachiyomi#2445] opened 2020-01-06 07:51 UTC
### Device information
* Tachiyomi version: 0.8.4
* Android version: 10

## Steps to reproduce
1. First step
Download a chapter
2. Second step
Make the source delete said chapter or replace it with another one
### Expected behavior

The chapter should be deleted or better yet it shouldn't disappear from the list 
### Actual behavior
This happened instead.
Chapter disappear into oblivion while the downloaded files stay on device with out able to access them or delete them
### Other details
Additional details and attachments.
![Screenshot_20200106-085025](https://user-images.githubusercontent.com/6317261/71803645-a49dfe00-3061-11ea-8b5f-06b4f22a8b70.jpg)
![Screenshot_20200106-085035](https://user-images.githubusercontent.com/6317261/71803661-abc50c00-3061-11ea-8d3c-03042273056e.jpg)

**Comment by arkon** [comment] 2020-01-06 12:31
> Make the source delete said chapter or replace it with another one

You mean the source changed the chapter?

**Comment by mraleksander** [comment] 2020-01-06 12:33
Yes when they upload a unedited chapter and it gets replace by a higher quality one

**Comment by CarlosEsco** [comment] 2020-01-06 12:53
I assume there was a name change in the chapter?

**Comment by mraleksander** [comment] 2020-01-06 12:56
That or that the old chapter got deleted and a new one was put in its place. And as the old chapter is not there anymore tachiyomi dosent display it on the list anymore

**Comment by CarlosEsco** [comment] 2020-01-06 12:58
your scenario doesn't make sense. 
If a source deletes a chapters and puts a new one with a new name then yes it will be orphaned which is a bug.
If a source deletes a chapters and puts a new one with same name.  It will not be orphaned

**Comment by mraleksander** [comment] 2020-01-06 13:10
![Screenshot_20200106-140642](https://user-images.githubusercontent.com/6317261/71820037-23109500-308e-11ea-8b0d-b01d3738ab2c.jpg)
![Screenshot_20200106-140928](https://user-images.githubusercontent.com/6317261/71820047-2a37a300-308e-11ea-92df-02c15a659910.jpg)
Well here you can see the chapter is downloaded and it is showing on the poster that there is one downloaded chapters but in the index it is missing

**Comment by arkon** [comment] 2020-01-06 13:13
The badge is a bug, it's similar to how it counts tmp folders.

The orphaning issue is a bug too.

A chapter being replaced with something with an identical name would actually result in the download being reused incorrectly, so I guess that's a bug too.

**Comment by CarlosEsco** [comment] 2020-01-06 13:23
The screen shows the chapter was renamed from Ch 13. Assassin's Dagger to Vol.2 Ch 13. - Assassin's Dagger

**Comment by sinhaaritro** [comment] 2020-04-25 15:10
Same problem.
And this is eating away my space. Atleast give us a way to clear it from the UI.
![Screenshot_20200425-201029](https://user-images.githubusercontent.com/34037263/80283419-01b6e000-8735-11ea-9bd4-75bbc6cc2465.png)
![Screenshot_20200425-201040](https://user-images.githubusercontent.com/34037263/80282937-e39bb080-8731-11ea-8187-8e1324f274df.png)
![Screenshot_20200425-201043](https://user-images.githubusercontent.com/34037263/80282931-dc74a280-8731-11ea-9306-5df909439aa7.png)

**Comment by mastermasher** [comment] 2020-05-02 12:35
So apparently if you remove a manga or chapter, the downloaded chapter is still in your storage. I just updated the app and there's now a popup notif to delete the downloaded chapter when removing it from your library. All this time i thought the "Clear Database" option is to clear out the chapters or manga that's in your storage, but not in your library, but turns out it's to delete records of "read" manga. So sorry for the nob question, but is there a way to do that? To delete chapters/manga from your storage that's not in your library? I'm still new to all this

**Comment by mastermasher** [comment] 2020-05-02 12:44
And there's now gigabytes of "ghost" manga chapters, all mangled up in my storage. I can just format the storage, but the problem is there are tons of downloaded manga that is IN my library. Couple of my friends also did the same by Clearing Database and facing similar problem(english is not our native tongue).

**Comment by CarlosEsco** [comment] 2020-05-03 12:06
@mastermasher go on discord and ask for help. Your issue is unrelated to this

**Comment by arkon** [comment] 2022-07-09 23:13
Duplicate of #2108

**Closed by arkon** 2022-07-09 23:13 UTC
Labels: Bug
