### ISSUE TITLE
Extensions not downloading or installing

### ISSUE THREAD

**Issue by H1ghSyst3m** [tachiyomiorg/tachiyomi#6723] opened 2022-03-03 00:31 UTC
### Steps to reproduce

1. Press install or update on any source
2. It says retry

### Expected behavior

It Download and Installs the Extension

### Actual behavior

It say retry and doesnt download and install the source

### Tachiyomi version

0.13.1

### Android version

Android 12

### Device

Mi 11

### Other details

This bug issue has been created and closed before, but unfortunately it wasn't solved.

I tried to Install the new updated sources, but they also didn't work.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-03-03 01:03
Is the installer set to "Legacy" in advanced settings? Package Installer is broken in most versions of MIUI.

**Comment by H1ghSyst3m** [comment] 2022-03-03 01:04
I also tried it with legacy mode, but it didnt work

**Comment by H1ghSyst3m** [comment] 2022-03-03 21:42
Here I am sending a link to the Issue with the Video

https://github.com/tachiyomiorg/tachiyomi/issues/6574#issuecomment-1030657166

**Comment by Dhs92** [comment] 2022-03-20 04:03
Having the same issue on Android 12 with all 3 installer options. 

Here's my log

`
03-19 20:53:06.130 32645 32645 E anade.tachiyom: Unknown bits set in runtime_flags: 0x40000000 03-19 20:53:06.132 32645 32645 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent. 03-19 20:53:06.191 32645 32673 E anade.tachiyom: Loaded layer handle (13678770393681023115) for layer /my_product/lib64/libcolorx-loader.so 03-19 20:53:06.191 32645 32673 E anade.tachiyom: Looking for entrypoint ColorX_Check 03-19 20:53:06.191 32645 32673 E anade.tachiyom: Found ColorX_Check for /my_product/lib64/libcolorx-loader.so 03-19 20:53:06.191 32645 32673 E anade.tachiyom: Check failed --------- beginning of system 03-19 20:53:06.203 32645 32645 E OplusCustomizeRestrictionManager: sInstance is null, start a new sInstance 03-19 20:53:06.369 32645 32692 E SQLiteLog: (284) automatic index on C(manga_id) 03-19 20:53:06.369 32645 32692 E SQLiteLog: (284) automatic index on mangas_categories(manga_id) 03-19 20:53:06.378 32645 32671 E ExtensionsLoader: dlopen failed: library "libhwuiextimpl.so" not found App version: 0.13.1 (standard, d6386ce, 74, 2022-02-01T17:35Z) Android version: 12 (SDK 31) Android build ID: LE2125_11_C.44 Device brand: OnePlus Device manufacturer: OnePlus Device name: OnePlus9Pro Device model: LE2125 Device product name: OnePlus9Pro
`

**Comment by frankenstein11** [comment] 2022-03-31 17:06
I am having the same issue
My Device:- realme x7pro 5g
Android version:- 12

**Comment by M3thAster** [comment] 2022-04-30 10:02
Same issue for me. Got any fixes?

**Comment by Dhs92** [comment] 2022-04-30 14:17
> Same issue for me. Got any fixes? 

Only work around I've found is downloading the extension APK directly from the GitHub page

**Comment by arkon** [comment] 2022-07-03 21:58
Duplicate of https://github.com/tachiyomiorg/tachiyomi/issues/4106

**Closed by arkon** 2022-07-03 21:58 UTC
Labels: Bug
