### ISSUE TITLE
[Feature Request] Desktop support

### ISSUE THREAD

**Issue by BlackXDragon** [tachiyomiorg/tachiyomi#4741] opened 2021-03-29 17:21 UTC
Although I love reading manga on my phone, I would very much like to read it on a big screen on my Windows PC. I figure there would be others who would like that too.

While I do understand that there is the option of using an emulator to use the mobile version on PC, I'd prefer not to have to spend extra computing resources on an emulator.

I realize that Tachiyomi is written in Kotlin and that any attempt to port it for desktop would require a re-write of the entire source code, and hence, I think converting to Flutter may help solve the cross-platform issue.

**Comment by Seishirou101** [comment] 2021-03-29 17:23
duplicate of #2587

**Comment by arkon** [comment] 2021-03-29 17:24
Flutter is a no-go too.

**Closed by arkon** 2021-03-29 17:24 UTC
Labels: feature
