### ISSUE TITLE
Missing ".nomedia" file in tachiyomi folder

### ISSUE THREAD

**Issue by jonaslam94** [tachiyomiorg/tachiyomi#6632] opened 2022-02-12 14:19 UTC
### Steps to reproduce

    Download a few manga
    Enter a gallery app like Google Photos
    Manga pages appear as folders.

### Expected behavior

The app normally creates a ".nomedia" file in the tachiyomi folder to hide manga downloads from being media scanned, which can help declutter gallery apps. That, or create an option for users to toggle that.

### Actual behavior

downloaded manga pages show up in phone gallery

### Tachiyomi version

0.13.1 

### Android version

Android 12

### Device

Galaxy s10+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-02-12 14:34
The app does create the file: https://github.com/tachiyomiorg/tachiyomi/blob/master/app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadProvider.kt#L36

Duplicate of #6499, but let us know if the app is seemingly actually not creating the files. It works on my own Android 12 Samsung device.

**Closed by arkon** 2022-02-12 14:34 UTC
Labels: Bug
