### ISSUE TITLE
Download bugs From Tachiyomi 0.14.5 to 0.14.7 

### ISSUE THREAD

**Issue by Ricky-mandem** [tachiyomiorg/tachiyomi#10220] opened 2023-12-07 11:36 UTC
### Steps to reproduce

Steps to reproduce
1. Update all extensions.
2. Try downloading any entry
3. It downloads everything but can't load it up hence the download seems lost but the files are loaded 
4. Cbz archive fails on samsung a02s android 12
5. The library update is also very sluggish same with the library covers updates

### Expected behavior

It should download and load it up as previous versions have 

### Actual behavior

Cannot load input stream

### Tachiyomi version

0.14.5 to 0.14.7

### Android version

Android 12

### Device

Samsung A02s

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-12-10 22:04
Duplicate of #8560 (you can try the Preview build if you want).

**Closed by arkon** 2023-12-10 22:04 UTC
Labels: Bug
