### ISSUE TITLE
[Bug] Webtoon Scrolling Problem

### ISSUE THREAD

**Issue by exaltedcelestial** [tachiyomiorg/tachiyomi#4771] opened 2021-04-03 20:13 UTC
**Expected behavior**:
- Scroll down more

**Actual Behavior**:
- Can't scroll down anymore

**Methods to reproduce**:
- Not sure but I think happens when I minimize tachiyomi, go to other apps, then lock, then go back to tachiyomi later?
- Not sure about this second method also, if I continuously read many webtoon chapters, it happens at times.

[Videos of the bug](https://drive.google.com/drive/folders/1psfFKqz7aJiYkYVkjDaAAmJHe7_Wm835?usp=sharing)

**Comment by giosann** [comment] 2021-04-08 15:48
I think it could be related / a duplicate of https://github.com/tachiyomiorg/tachiyomi/issues/3052 and https://github.com/tachiyomiorg/tachiyomi/issues/3555

**Comment by arkon** [comment] 2021-04-08 21:51
Yes, I think they're related so I'm going to close this one.

**Closed by arkon** 2021-04-08 21:51 UTC
Labels: bug
