### ISSUE TITLE
UI overlapping when opening manga chapter list

### ISSUE THREAD

**Issue by Nydid** [tachiyomiorg/tachiyomi#5942] opened 2021-09-19 20:01 UTC
### Steps to reproduce

1. Have a manga in library
2. Open it

### Expected behavior

UI not overlapping

### Actual behavior

UI overlapping but goes back to normal when scrolling

https://user-images.githubusercontent.com/30263820/133941321-05cf7067-b4cd-4040-ad77-285f67db9400.mp4

### Tachiyomi version

0.12.2

### Android version

10

### Device

Oneplus 7 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by vengiare** [comment] 2021-09-19 20:06
Duplicate of #5888

**Comment by vengiare** [comment] 2021-09-19 20:07
Nvm, don't know if it's the same bug or not.

**Closed** 2021-09-21 21:35 UTC
Labels: Bug
