### ISSUE TITLE
Constant deselect of chapters while one is downloading in the same entry

### ISSUE THREAD

**Issue by deidouji** [tachiyomiorg/tachiyomi#7528] opened 2022-07-13 17:07 UTC
### Steps to reproduce

Start a download of a chapter then try selecting that chapter or any other in the same entry, it'll constantly deselect 

### Expected behavior

It probably shouldn't

### Actual behavior

It does

### Tachiyomi version

Latest Tachi Preview Commits 

### Android version

Android 11

### Device

Galaxy Tab A7 SM-T500

### Other details

https://user-images.githubusercontent.com/62192522/178790845-1f3fa9fa-dc06-457c-9f55-b0723540a414.mp4

https://user-images.githubusercontent.com/62192522/178791382-5429b147-1777-4b4e-a195-a1c27f24ad57.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form

.

**Comment by arkon** [comment] 2022-07-13 17:24
Duplicate of #7429

**Closed by arkon** 2022-07-13 17:24 UTC
Labels: Bug
