### ISSUE TITLE
Default category doesn't reappear after deleting the only category an entry is associated with

### ISSUE THREAD

**Issue by Disposablegloves** [tachiyomiorg/tachiyomi#10128] opened 2023-11-12 02:23 UTC
### Steps to reproduce

1. Have multiple categories (I have 9) with entries in the default one (no category assigned)
2. Make a category and add the ones in the default category to the new one (or add them to an existing category)
3. Delete the category they were assigned to

### Expected behavior

Default library should reappear along with orphaned entries when the only category the entries are assigned to are deleted

### Actual behavior

Default category and its supposed entries isn't visible in the library until you add a new entry to the library

### Tachiyomi version

0.14.7 (standard, c8d6859, 102, 2023-10-25T16:11Z)

### Android version

12 (SDK 31)

### Device

Xiaomi Mi 10t Pro (M2007J3SG)

### Other details

App restart does not fix the issue, only adding new entries does.

I have not tested if this happens when there's only a single category and that category is then deleted.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-11-12 03:46
Duplicate of #8922, but it hasn't made it to a stable release yet.

**Closed by arkon** 2023-11-12 03:46 UTC
Labels: Bug
