### ISSUE TITLE
Removing an entry from a category from the library often causes crash

### ISSUE THREAD

**Issue by mm12** [tachiyomiorg/tachiyomi#9634] opened 2023-06-24 22:11 UTC
### Steps to reproduce

1. have multiple categories
2. press and hold an entry from the library screen. 
3. Select as many entries as you like (more seems to correlate with the crash)
4. remove entries from a category (seems to occur more frequently when the category is the current one)

### Expected behavior

Entries are removed from the selected cateogry(s)

### Actual behavior

Entries are removed from the selected cateogry(s), however the app crashes immediately 

### Crash logs
```
--------- beginning of main
06-24 17:04:39.184 25314 25341 E SQLiteLog: (283) recovered 200 frames from WAL file /[data/user/0/eu.kanade.tachiyomi/databases/tachiyomi.db-wal](http://data/user/0/eu.kanade.tachiyomi/databases/tachiyomi.db-wal)
06-24 17:04:40.216 25314 25465 E SQLiteLog: (284) automatic index on C(manga_id)
06-24 17:04:40.216 25314 25465 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
06-24 17:05:27.772 25314 25456 E CursorWindow: Failed to read row 619, column 0 from a CursorWindow which has 619 rows, 26 columns.
06-24 17:05:27.812 25314 25456 E ACRA    : ACRA caught a NullPointerException for eu.kanade.tachiyomi
06-24 17:05:27.812 25314 25456 E ACRA    : java.lang.NullPointerException
06-24 17:05:27.812 25314 25456 E ACRA    : 	at tachiyomi.data.data.LibraryViewQueriesImpl$library$1.invoke(DatabaseImpl.kt:17)
06-24 17:05:27.812 25314 25456 E ACRA    : 	at com.squareup.sqldelight.Query.executeAsList(Query.kt:18)
06-24 17:05:27.812 25314 25456 E ACRA    : 	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToList$1$1.invokeSuspend(FlowExtensions.kt:6)
06-24 17:05:27.812 25314 25456 E ACRA    : 	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToList$1$1.invoke(FlowExtensions.kt:13)
06-24 17:05:27.812 25314 25456 E ACRA    : 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:8)
06-24 17:05:27.812 25314 25456 E ACRA    : 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:50)
06-24 17:05:27.812 25314 25456 E ACRA    : 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
06-24 17:05:27.812 25314 25456 E ACRA    : 	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToList$$inlined$map$1$2.emit(Collect.kt:76)
06-24 17:05:27.812 25314 25456 E ACRA    : 	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:2)
06-24 17:05:27.812 25314 25456 E ACRA    : 	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:18)
06-24 17:05:27.812 25314 25456 E ACRA    : 	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:1)
06-24 17:05:27.812 25314 25456 E ACRA    : 	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$asFlow$1.invokeSuspend(FlowExtensions.kt:120)
06-24 17:05:27.812 25314 25456 E ACRA    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
06-24 17:05:27.812 25314 25456 E ACRA    : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
06-24 17:05:27.812 25314 25456 E ACRA    : 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
06-24 17:05:27.812 25314 25456 E ACRA    : 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
06-24 17:05:27.812 25314 25456 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
06-24 17:05:27.812 25314 25456 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:63)
06-24 17:05:27.812 25314 25456 E ACRA    : 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [CoroutineName(eu.kanade.tachiyomi.ui.library.LibraryTab:eu.kanade.tachiyomi.ui.library.LibraryScreenModel:default:ScreenModelCoroutineScope), StandaloneCoroutine{Cancelling}@b65e307, Dispatchers.IO]
06-24 17:05:28.444 25619 25643 E SQLiteLog: (283) recovered 42 frames from WAL file /[data/user/0/eu.kanade.tachiyomi/databases/tachiyomi.db-wal](http://data/user/0/eu.kanade.tachiyomi/databases/tachiyomi.db-wal)
06-24 17:05:30.831 25853 25901 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
06-24 17:05:31.417 25853 26017 E SQLiteLog: (284) automatic index on C(manga_id)
06-24 17:05:31.417 25853 26017 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.14.6 (standard, c615f4d, 101, 2023-04-16T15:14Z)
Android version: 12 (SDK 31)
Android build ID: SP1A.210812.016.C2
Device brand: google
Device manufacturer: Google
Device name: blueline
Device model: Pixel 3
Device product name: blueline
```
### Tachiyomi version

0.14.6

### Android version

Android 12

### Device

Google Pixel 3

### Other details

I think it is trying to get the next entry to remove when there is none - just a theory. I included all lines in the crash logs that were in the timeframe I was testing this.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

EDIT: fixed log formating

**Comment by arkon** [comment] 2023-06-24 22:32
Duplicate of #7997

**Closed by arkon** 2023-06-24 22:32 UTC
Labels: Bug
