### ISSUE TITLE
hope to add progress modification function

### ISSUE THREAD

**Issue by Aragamiz** [tachiyomiorg/tachiyomi#10035] opened 2023-10-18 14:30 UTC
### Describe your suggested feature

When progress confusion, need a way to setting progress

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-10-18 14:40
Huh?

**Comment by Aragamiz** [comment] 2023-10-18 14:44
> Huh?

Although the button in the bottom right corner of the comic detail page continues, this progress cannot be modified.
In some cases, such as when the progress of the image source and the number of sessions are chaotic, or when I want to review, I want to modify this progress status, but it seems that it is not possible at present. You can only revisit it through bookmarks.
I used a translation, I'm not sure if I can explain it clearly. Thank you

**Comment by Aragamiz** [comment] 2023-10-18 14:48
I have read 29 chapters of a certain comic book for example. But I want to revisit a chapter in the third episode, but Tachiyomi is currently unable to modify the progress or bookmark. Once I exit this session, I can only rely on memory to find the number of pages.

**Comment by arkon** [comment] 2023-10-18 15:15
You can write in Chinese if you're more comfortable with that, we can get someone to translate.

**Comment by Aragamiz** [comment] 2023-10-18 15:34
> You can write in Chinese if you're more comfortable with that, we can get someone to translate.

请求开发一个“调整漫画进度”的功能，因为在某些书源和漫画下，话和卷的顺序是混乱的。假如一个漫画，因为卷标章节标注不同或者点错了的原因，进度被提前到29话第十页，但我只读到第20话，这时就很难记忆我的真实阅读进度，因为目前的tachiyomi阅读进度无法修改。
并请求完善书签功能，目前的书签功能也比较基础，我无法在漫画界面快速定位到我书签的章节，仍然需要往下翻很多页，也无法用书签功能来标记某个章节的某个页面。
以上，谢谢，thks。

**Comment by arkon** [comment] 2023-10-19 02:54
DeepL translation:

> I'd like to request a feature to "adjust manga progress" because in some sources and manga, the order of words and volumes is messed up. For example, if a manga's progress is advanced to page 10 of 29 because the chapter labeling is different or I clicked on the wrong page, but I'm only on page 20, then it's hard to remember my real reading progress because I can't change the current tachiyomi reading progress.
And a request to improve the bookmarking feature, which is also rather basic at the moment, I can't quickly locate the chapters I've bookmarked in the manga interface, and still need to scroll down many pages, and I can't use the bookmarking feature to mark a certain page of a chapter.
Above, thanks, thks.

---

I'm not sure I understand the progress. Progress is also based on the last page you were on, so you'd have to go back to the "correct" page; there's no way for the app to know what a "real" or "wrong" progress is.

The page bookmarking is a duplicate of #565.

**Comment by Aragamiz** [comment] 2023-10-19 03:15
> I'm not sure I understand the progress. Progress is also based on the last page you were on, so you'd have to go back to the "correct" page; there's no way for the app to know what a "real" or "wrong" progress is.
> 
> The page bookmarking is a duplicate of #565.

the bookmark system also can solve it.
"progress" maen the manga "Resume" can't change.

**Comment by stevenyomi** [comment] 2023-10-19 14:53
可以描述得更具体一点吗？没看懂“进度被提前到29话第十页，但我只读到第20话”说的是什么。

“继续”按钮总是打开最旧的未读章节。你不小心读了新章节也不会影响“继续”按钮才对。

**Comment by stevenyomi** [comment] 2023-10-19 15:11
> 大概就是迁移之后的问题。
> 
> 比如我之前看过的某个漫画源A，源只有分话，没有录入卷，此时我看到29话，序号为29。
> 
> 一段时间之后这个源失效，我把这个漫画迁移了。但是迁移源之后，新源的 “话” 排序在 “卷” 之后， 在目前的7个单行本之后才开始 话1、2、3这样排列，这样话29的顺序就变成了7+29=36。这时，我想从单行本卷5开始继续看，但这个时候 “继续” 按钮会直接跳转到29话（序号36），直接忽略前面的部分，也无法记录我看前面单行本时的页数。

这个没有办法的，软件只能记录你看过了哪几章，根本不可能具体到新出现的单行本里面的页数。

你如果说有一话读到一半，想要迁移的时候保留页数还更现实一点。

**Closed by stevenyomi** 2023-10-19 15:11 UTC
Labels: Feature request
