### ISSUE TITLE
Is Hide bottom bar on scroll are Removed 

### ISSUE THREAD

**Issue by Solovertical** [tachiyomiorg/tachiyomi#8351] opened 2022-10-30 04:26 UTC
### Steps to reproduce

1.Open Tachiyomi
2.Go to Appearance
3.No option of this

### Expected behavior

1.It should show the option
![Screenshot_2022-10-30-09-52-36-241_xyz jmir tachiyomi mi](https://user-images.githubusercontent.com/109901807/198862460-ee23e28e-5885-4cfb-9129-53d3d1a242be.png)

### Actual behavior

Option is  not there 
If it possible to add again please add 

### Tachiyomi version

0.14.1

### Android version

10

### Device

Xiaomi

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Solovertical** [comment] 2022-10-30 08:41
Is it Removed permanently or there a chance in future to add that option again

**Comment by arkon** [comment] 2022-10-30 13:57
Duplicate of #8315

**Closed** 2022-10-30 13:57 UTC
Labels: Bug
