### ISSUE TITLE
Sudden Force Closing 

### ISSUE THREAD

**Issue by AriaZen0kis** [tachiyomiorg/tachiyomi#8979] opened 2023-01-24 19:10 UTC
### Steps to reproduce

Tachiyomi new updates
The previous versions were better but the new updates drag a lot , sometimes I get scared when there's a new update but I end up getting my hope up that the new update might fix the issue but I end up being disappointed, I sometimes think if I should uninstall the new update and put back the old version if it could appease my anxiety of the updates.
One of the new things I recognize in the new update of 0.14.3 is the Statistics, it's good but I hope the lagging issues and sudden force closing when I'm going through the Tachiyomi app should be fixed 

### Expected behavior

The app should smoothly migrate the comics.
Search on a global search for comics .
When I go for a global search to be smooth and fast .
When I open my library or any comic should be quick .

### Actual behavior

But when I'm migrating or going through my library it suddenly force closes itself.
When I go for a global search the extensions say cannot bypass cloudfare .
When I search for any comics on global search it takes a lot of time and it lags a lot.
When I open up my Tachiyomi library or any comic in the library it takes a lot of time to open.

### Crash logs

--------- beginning of system--------- beginning of mainApp version: 0.14.3 (standard, 817418f, 93, 2023-01-07T17:15Z)Android version: 11 (SDK 30)Android build ID: PR652B-F6317-11.0-OP-V64-20220728Device brand: InfinixDevice manufacturer: InfinixDevice name: Infinix-PR652BDevice model: Infinix PR652BDevice product name: F6317

### Tachiyomi version

0.14.3

### Android version

Android 11

### Device

Infinix PR652B

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2023-01-24 19:43
If you meet with a crash, reproduce it and dump the crash logs again. The crash logs you posted have nothing useful.

You can use an old version but we provide no support for any bugs with it. The jank is known and we will improve it in the long run; the Android system will also optimize the app as you use it.

**Comment by stevenyomi** [comment] 2023-01-24 19:44
Duplicate of #8310

**Closed by stevenyomi** 2023-01-24 19:44 UTC
Labels: Bug
