### ISSUE TITLE
Add pause for each source and compression option

### ISSUE THREAD

**Issue by yamato44** [tachiyomiorg/tachiyomi#8039] opened 2022-09-19 20:08 UTC
### Describe your suggested feature

Add pause for each source so we can give priority for the source we want first and compression option in the settings so we can download large sized chapters to low size ones

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-09-20 04:15
> Add pause for each source so we can give priority for the source we want first

Just reorder the queue.

> compression option in the settings so we can download large sized chapters to low size ones

Duplicate of #4415

**Closed by arkon** 2022-09-20 04:15 UTC
Labels: Feature request

**Comment by yamato44** [comment] 2022-09-21 21:08
> > Add pause for each source so we can give priority for the source we want first
> 
> Just reorder the queue.
> 
> > compression option in the settings so we can download large sized chapters to low size ones
> 
> Duplicate of #4415

That doesn't work when i said source i mean extensions i have manhwas in 3 extensions in the queue when i start the download the first one of each extension starts to download the method you told me it would just reorder the chapters in each extension that's why pause of each extension is usefull. What do you think?
