### ISSUE TITLE
[Bug] no WiFi connection while VPN is enabled

### ISSUE THREAD

**Issue by LoLyeah** [tachiyomiorg/tachiyomi#2795] opened 2020-03-31 02:29 UTC
**App version:**
r1955 (dev version)
**Android version:**
Android 10 (MIUI 11)

**Issue:**
When 'Only Download over WiFi' is enabled while using VPN, even though I'm already on WiFi, I can't download any chapter at all. The notification says 'no WiFi connection'

**Steps to reproduce (if applicable)**

 1. Turn on VPN while on WiFi
 2. Download a chapter after you turned on 'Only Download over WiFi'

**Other details:**
It's either bug in the app or Android 10, since I both updated the app and the Android recently.
![Screenshot_2020-03-31-09-16-12-028_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/11774211/77980668-0785f500-7332-11ea-955a-8d6b67812b72.jpg)
![Screenshot_2020-03-31-09-15-33-559_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/11774211/77980679-0ead0300-7332-11ea-9171-8f25b4b1ab30.jpg)

**Comment by X9VoiD** [comment] 2020-04-04 20:14
I also use the same VPN as you use but I can't reproduce your issue. Might be a bug present only in Android 10 as I am running Android 9

**Comment by LoLyeah** [comment] 2020-05-03 10:16
> I also use the same VPN as you use but I can't reproduce your issue. Might be a bug present only in Android 10 as I am running Android 9

Yeah, probably caused by the Android 10.
Also this issue happened too on Flud torrent apps. Apparently by using VPN, the wifi counts as metered connection.

I'll do another test with another app later.

**Comment by arkon** [comment] 2021-01-04 21:33
Was addressed in #3489

**Closed by arkon** 2021-01-04 21:33 UTC
Labels: bug
