### ISSUE TITLE
[Feature Request] Category wise sorting in Library

### ISSUE THREAD

**Issue by joseph619** [tachiyomiorg/tachiyomi#5234] opened 2021-05-29 15:04 UTC
## Why/User Benefit/User Problem
Similar to category wise display, this will sort manga independently per category in Library. 

## What/Requirements
Could use https://github.com/tachiyomiorg/tachiyomi/pull/5232 as reference

**Comment by arkon** [comment] 2021-05-29 15:06
Duplicate of #3722

**Closed by arkon** 2021-05-29 15:06 UTC
Labels: feature
