### ISSUE TITLE
Mass migrate mangas

### ISSUE THREAD

**Issue by Spectre178** [tachiyomiorg/tachiyomi#4421] opened 2021-02-09 13:04 UTC
## Issue/Request
add option to mass migrate mangas from a source to another/ migrate all manga to another source

##additional info
The extension always update and removed, so this is to ease the migration process to another source.

**Comment by joseph619** [comment] 2021-02-09 13:07
Duplicate of #1231

**Closed** 2021-02-09 13:19 UTC
