### ISSUE TITLE
Tachiyomi crashes when clicking on comics for random unknown events

### ISSUE THREAD

**Issue by Jacfger** [tachiyomiorg/tachiyomi#10233] opened 2023-12-13 18:18 UTC
### Steps to reproduce

Not sure exactly what's happening, but I was thinking if it has anything to do with updated comics list. But sometimes comic list that's not updated also causes the apps to crash. I'm posting it here because I've experienced this in both mangadex and manhuagui. So I don't think it's caused by specific extension. But it could also be small sample size.

(Also I can't update manhuagui because manhuagui had some weird issues which made my comics disappear (i.e. turns them into unknown source), I can't risk ruining my library. But mangadex was updated to the newest)

1. Open any source (I've experienced this on manhuagui, and mangadex)
2. Browsing. After somewhile, click on any comics. Crashing.

To reproduce the bug in Magadex, here's what I did.
1. Open mangadex, go to latest.
2. Switch apps to chrome, lock screen and went watch YouTube (on PC).
3. Roughly around 20 minutes, pick up the phone, switch back to Tachiyomi, we should still in the MangaDex source. After some loading, click on any comics (not sure if we need to switch to latest first or what). It crashed.

In the crash report, I seemed to see both crash had been caused by the same error message. So I suspect it's probably the same problem too.

### Expected behavior

Not crashed.

### Actual behavior

crashed. very randomly.

### Crash logs
```
--------- beginning of crash
11-30 23:29:05.258 26358 26358 E AndroidRuntime: FATAL EXCEPTION: main
11-30 23:29:05.258 26358 26358 E AndroidRuntime: Process: eu.kanade.tachiyomi, PID: 26358
11-30 23:29:05.258 26358 26358 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{eu.kanade.tachiyomi/eu.kanade.tachiyomi.ui.main.MainActivity}: java.lang.NullPointerException
11-30 23:29:05.258 26358 26358 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4169)
11-30 23:29:05.258 26358 26358 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4325)
11-30 23:29:05.258 26358 26358 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
11-30 23:29:05.258 26358 26358 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
11-30 23:29:05.258 26358 26358 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
11-30 23:29:05.258 26358 26358 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
11-30 23:29:05.258 26358 26358 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-30 23:29:05.258 26358 26358 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
11-30 23:29:05.258 26358 26358 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
11-30 23:29:05.258 26358 26358 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8762)
11-30 23:29:05.258 26358 26358 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-30 23:29:05.258 26358 26358 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
11-30 23:29:05.258 26358 26358 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
11-30 23:29:05.258 26358 26358 E AndroidRuntime: Caused by: java.lang.NullPointerException
11-30 23:29:05.258 26358 26358 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.browse.extension.details.SourcePreferencesFragment.onCreatePreferences(SourcePreferencesScreen.kt:34)
11-30 23:29:05.258 26358 26358 E AndroidRuntime: 	at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:73)
11-30 23:29:05.258 26358 26358 E AndroidRuntime: 	at androidx.fragment.app.Fragment.performCreate(Fragment.java:27)
11-30 23:29:05.258 26358 26358 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:41)
11-30 23:29:05.258 26358 26358 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:110)
11-30 23:29:05.258 26358 26358 E AndroidRuntime: 	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:31)
11-30 23:29:05.258 26358 26358 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:28)
11-30 23:29:05.258 26358 26358 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:10)
11-30 23:29:05.258 26358 26358 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:12)
11-30 23:29:05.258 26358 26358 E AndroidRuntime: 	at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:5)
11-30 23:29:05.258 26358 26358 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:13)
11-30 23:29:05.258 26358 26358 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.base.activity.BaseActivity.onCreate(BaseActivity.kt:11)
11-30 23:29:05.258 26358 26358 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.main.MainActivity.onCreate(MainActivity.kt:19)
11-30 23:29:05.258 26358 26358 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8591)
11-30 23:29:05.258 26358 26358 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8570)
11-30 23:29:05.258 26358 26358 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
11-30 23:29:05.258 26358 26358 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4150)
11-30 23:29:05.258 26358 26358 E AndroidRuntime: 	... 12 more
--------- beginning of main
12-14 01:23:21.673 26038 26098 E SQLiteLog: (283) recovered 32 frames from WAL file /data/user/0/eu.kanade.tachiyomi/databases/tachiyomi.db-wal
12-14 01:23:22.335 26038 26038 E BufferQueueProducer: Unable to open libpenguin.so: dlopen failed: library "libpenguin.so" not found.
12-14 01:23:30.495 26038 26038 E ACRA    : ACRA caught a IllegalArgumentException for eu.kanade.tachiyomi
12-14 01:23:30.495 26038 26038 E ACRA    : java.lang.IllegalArgumentException: Key Screen#0:transition:lifecycle was used multiple times 
12-14 01:23:30.495 26038 26038 E ACRA    : 	at androidx.compose.runtime.saveable.SaveableStateHolderImpl$SaveableStateProvider$1$1.invoke(SaveableStateHolder.kt:71)
12-14 01:23:30.495 26038 26038 E ACRA    : 	at androidx.compose.runtime.DisposableEffectImpl.onRemembered(Effects.kt:7)
12-14 01:23:30.495 26038 26038 E ACRA    : 	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:94)
12-14 01:23:30.495 26038 26038 E ACRA    : 	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:81)
12-14 01:23:30.495 26038 26038 E ACRA    : 	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:6)
12-14 01:23:30.495 26038 26038 E ACRA    : 	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:218)
12-14 01:23:30.495 26038 26038 E ACRA    : 	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:9)
12-14 01:23:30.495 26038 26038 E ACRA    : 	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:34)
12-14 01:23:30.495 26038 26038 E ACRA    : 	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:13)
12-14 01:23:30.495 26038 26038 E ACRA    : 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1299)
12-14 01:23:30.495 26038 26038 E ACRA    : 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
12-14 01:23:30.495 26038 26038 E ACRA    : 	at android.view.Choreographer.doCallbacks(Choreographer.java:923)
12-14 01:23:30.495 26038 26038 E ACRA    : 	at android.view.Choreographer.doFrame(Choreographer.java:847)
12-14 01:23:30.495 26038 26038 E ACRA    : 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
12-14 01:23:30.495 26038 26038 E ACRA    : 	at android.os.Handler.handleCallback(Handler.java:942)
12-14 01:23:30.495 26038 26038 E ACRA    : 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-14 01:23:30.495 26038 26038 E ACRA    : 	at android.os.Looper.loopOnce(Looper.java:226)
12-14 01:23:30.495 26038 26038 E ACRA    : 	at android.os.Looper.loop(Looper.java:313)
12-14 01:23:30.495 26038 26038 E ACRA    : 	at android.app.ActivityThread.main(ActivityThread.java:8762)
12-14 01:23:30.495 26038 26038 E ACRA    : 	at java.lang.reflect.Method.invoke(Native Method)
12-14 01:23:30.495 26038 26038 E ACRA    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
12-14 01:23:30.495 26038 26038 E ACRA    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
12-14 01:23:30.495 26038 26038 E ACRA    : 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@7241ffd, androidx.compose.ui.platform.MotionDurationScaleImpl@6cee4f2, StandaloneCoroutine{Cancelling}@5056743, AndroidUiDispatcher@99591c0]
12-14 01:23:31.124 26721 26743 E SQLiteLog: (283) recovered 3 frames from WAL file /data/user/0/eu.kanade.tachiyomi/databases/tachiyomi.db-wal
12-14 01:23:32.293 26815 26853 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
12-14 01:23:32.683 26815 26815 E BufferQueueProducer: Unable to open libpenguin.so: dlopen failed: library "libpenguin.so" not found.
12-14 01:23:32.721 26815 27042 E SQLiteLog: (284) automatic index on C(manga_id)
12-14 01:23:32.721 26815 27042 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
12-14 01:24:34.262 27656 27698 E SQLiteLog: (283) recovered 14 frames from WAL file /data/user/0/eu.kanade.tachiyomi/databases/tachiyomi.db-wal
12-14 01:24:34.621 27656 27656 E BufferQueueProducer: Unable to open libpenguin.so: dlopen failed: library "libpenguin.so" not found.
12-14 01:24:34.664 27656 27854 E SQLiteLog: (284) automatic index on C(manga_id)
12-14 01:24:34.664 27656 27854 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
12-14 01:34:05.719 28948 28948 E BufferQueueProducer: Unable to open libpenguin.so: dlopen failed: library "libpenguin.so" not found.
12-14 01:34:06.620 28948 29120 E SQLiteLog: (284) automatic index on C(manga_id)
12-14 01:34:06.620 28948 29120 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
12-14 01:42:31.103 28948 31334 E MangaDex: Connecting to MD@Home node at https://cpdnh97kz2dyw.b43khn6qp7jz0.mangadex.network/r9-PSlg6iaCmwCiZANnSWZI3TWhqx4v7mGT9IwHruoL3udF_OPGvt4_4X9aGfLUHoWl49q6v5TBom3U5GYO6-NZF9MMBNSYggBxSp6dZ2F93wQ9c6ZMhgDOCCWMvgqfSDiUg1A2NIq2axrYPcEQqio4nZLLsyWpCGTTilP8Gwt25mTrkvuNZ00O-jR64aA/data-saver/bada8e3d8566f19f350906dea5a7d2e0/1-657a626a3b572942bc729ee4dcc251221de8fec1752b8dece812856edd707365.jpg
12-14 01:42:31.883 28948 31334 E MangaDex: Connecting to MD@Home node at https://cpdnh97kz2dyw.b43khn6qp7jz0.mangadex.network/r9-PSlg6iaCmwCiZANnSWZI3TWhqx4v7mGT9IwHruoL3udF_OPGvt4_4X9aGfLUHoWl49q6v5TBom3U5GYO6-NZF9MMBNSYggBxSp6dZ2F93wQ9c6ZMhgDOCCWMvgqfSDiUg1A2NIq2axrYPcEQqio4nZLLsyWpCGTTilP8Gwt25mTrkvuNZ00O-jR64aA/data-saver/bada8e3d8566f19f350906dea5a7d2e0/2-5f33beb70246bf501f8d7748fb7aa7a53fc424f0660507263c3d9344286a37fd.jpg
12-14 01:42:32.287 28948 31334 E MangaDex: Connecting to MD@Home node at https://cpdnh97kz2dyw.b43khn6qp7jz0.mangadex.network/r9-PSlg6iaCmwCiZANnSWZI3TWhqx4v7mGT9IwHruoL3udF_OPGvt4_4X9aGfLUHoWl49q6v5TBom3U5GYO6-NZF9MMBNSYggBxSp6dZ2F93wQ9c6ZMhgDOCCWMvgqfSDiUg1A2NIq2axrYPcEQqio4nZLLsyWpCGTTilP8Gwt25mTrkvuNZ00O-jR64aA/data-saver/bada8e3d8566f19f350906dea5a7d2e0/3-07eeed7225a818f2a1f22437e35f22c553ba8ceaaa1cb40fa66dadf4d40fb933.jpg
12-14 01:42:32.496 28948 31334 E MangaDex: Connecting to MD@Home node at https://cpdnh97kz2dyw.b43khn6qp7jz0.mangadex.network/r9-PSlg6iaCmwCiZANnSWZI3TWhqx4v7mGT9IwHruoL3udF_OPGvt4_4X9aGfLUHoWl49q6v5TBom3U5GYO6-NZF9MMBNSYggBxSp6dZ2F93wQ9c6ZMhgDOCCWMvgqfSDiUg1A2NIq2axrYPcEQqio4nZLLsyWpCGTTilP8Gwt25mTrkvuNZ00O-jR64aA/data-saver/bada8e3d8566f19f350906dea5a7d2e0/4-a8d8bca5a46a27f73607c87da3cc4c334d344e815bdbbbce5e6c40281f8c2d4d.jpg
12-14 01:42:32.888 28948 31334 E MangaDex: Connecting to MD@Home node at https://cpdnh97kz2dyw.b43khn6qp7jz0.mangadex.network/r9-PSlg6iaCmwCiZANnSWZI3TWhqx4v7mGT9IwHruoL3udF_OPGvt4_4X9aGfLUHoWl49q6v5TBom3U5GYO6-NZF9MMBNSYggBxSp6dZ2F93wQ9c6ZMhgDOCCWMvgqfSDiUg1A2NIq2axrYPcEQqio4nZLLsyWpCGTTilP8Gwt25mTrkvuNZ00O-jR64aA/data-saver/bada8e3d8566f19f350906dea5a7d2e0/5-66e9b93d0f499395b9be282faa601e56fd0f255e11a41caa2c1cb88a124618e5.jpg
12-14 01:42:33.289 28948 31334 E MangaDex: Connecting to MD@Home node at https://cpdnh97kz2dyw.b43khn6qp7jz0.mangadex.network/r9-PSlg6iaCmwCiZANnSWZI3TWhqx4v7mGT9IwHruoL3udF_OPGvt4_4X9aGfLUHoWl49q6v5TBom3U5GYO6-NZF9MMBNSYggBxSp6dZ2F93wQ9c6ZMhgDOCCWMvgqfSDiUg1A2NIq2axrYPcEQqio4nZLLsyWpCGTTilP8Gwt25mTrkvuNZ00O-jR64aA/data-saver/bada8e3d8566f19f350906dea5a7d2e0/6-d30f67e5f4639c81ad41d7b906d08568734d40729bcddbcca3d55c54da187035.jpg
12-14 01:42:33.498 28948 31334 E MangaDex: Connecting to MD@Home node at https://cpdnh97kz2dyw.b43khn6qp7jz0.mangadex.network/r9-PSlg6iaCmwCiZANnSWZI3TWhqx4v7mGT9IwHruoL3udF_OPGvt4_4X9aGfLUHoWl49q6v5TBom3U5GYO6-NZF9MMBNSYggBxSp6dZ2F93wQ9c6ZMhgDOCCWMvgqfSDiUg1A2NIq2axrYPcEQqio4nZLLsyWpCGTTilP8Gwt25mTrkvuNZ00O-jR64aA/data-saver/bada8e3d8566f19f350906dea5a7d2e0/7-8eff578213cc61614345a837cc11c47f09425877e0a23269da25dfa171a761ad.jpg
12-14 01:42:34.402 28948 31343 E MangaDex: Connecting to MD@Home node at https://cpdnh97kz2dyw.b43khn6qp7jz0.mangadex.network/r9-PSlg6iaCmwCiZANnSWZI3TWhqx4v7mGT9IwHruoL3udF_OPGvt4_4X9aGfLUHoWl49q6v5TBom3U5GYO6-NZF9MMBNSYggBxSp6dZ2F93wQ9c6ZMhgDOCCWMvgqfSDiUg1A2NIq2axrYPcEQqio4nZLLsyWpCGTTilP8Gwt25mTrkvuNZ00O-jR64aA/data-saver/bada8e3d8566f19f350906dea5a7d2e0/8-01937af21a3d522ae913aa57d1aa0418116a7d4a8ba65af5b5c841badc117876.jpg
12-14 01:42:36.934 28948 31334 E MangaDex: Connecting to MD@Home node at https://cpdnh97kz2dyw.b43khn6qp7jz0.mangadex.network/r9-PSlg6iaCmwCiZANnSWZI3TWhqx4v7mGT9IwHruoL3udF_OPGvt4_4X9aGfLUHoWl49q6v5TBom3U5GYO6-NZF9MMBNSYggBxSp6dZ2F93wQ9c6ZMhgDOCCWMvgqfSDiUg1A2NIq2axrYPcEQqio4nZLLsyWpCGTTilP8Gwt25mTrkvuNZ00O-jR64aA/data-saver/bada8e3d8566f19f350906dea5a7d2e0/9-2455ad1ac591ded7b6f270247b4b2d3de60b7c3efdbcdc79f9ee2b8183f2396d.jpg
12-14 01:42:38.778 28948 31343 E MangaDex: Connecting to MD@Home node at https://cpdnh97kz2dyw.b43khn6qp7jz0.mangadex.network/r9-PSlg6iaCmwCiZANnSWZI3TWhqx4v7mGT9IwHruoL3udF_OPGvt4_4X9aGfLUHoWl49q6v5TBom3U5GYO6-NZF9MMBNSYggBxSp6dZ2F93wQ9c6ZMhgDOCCWMvgqfSDiUg1A2NIq2axrYPcEQqio4nZLLsyWpCGTTilP8Gwt25mTrkvuNZ00O-jR64aA/data-saver/bada8e3d8566f19f350906dea5a7d2e0/10-93e8d876635c7b060dab7225acbe8f871181a6d86d01f09485088c3a51a4ba99.jpg
12-14 01:42:38.983 28948 31343 E MangaDex: Connecting to MD@Home node at https://cpdnh97kz2dyw.b43khn6qp7jz0.mangadex.network/r9-PSlg6iaCmwCiZANnSWZI3TWhqx4v7mGT9IwHruoL3udF_OPGvt4_4X9aGfLUHoWl49q6v5TBom3U5GYO6-NZF9MMBNSYggBxSp6dZ2F93wQ9c6ZMhgDOCCWMvgqfSDiUg1A2NIq2axrYPcEQqio4nZLLsyWpCGTTilP8Gwt25mTrkvuNZ00O-jR64aA/data-saver/bada8e3d8566f19f350906dea5a7d2e0/11-2faa924b3402b69c121b0c103c5b7b942f2c82044a1e53c4c233a42e456ead0c.jpg
12-14 01:42:39.187 28948 31343 E MangaDex: Connecting to MD@Home node at https://cpdnh97kz2dyw.b43khn6qp7jz0.mangadex.network/r9-PSlg6iaCmwCiZANnSWZI3TWhqx4v7mGT9IwHruoL3udF_OPGvt4_4X9aGfLUHoWl49q6v5TBom3U5GYO6-NZF9MMBNSYggBxSp6dZ2F93wQ9c6ZMhgDOCCWMvgqfSDiUg1A2NIq2axrYPcEQqio4nZLLsyWpCGTTilP8Gwt25mTrkvuNZ00O-jR64aA/data-saver/bada8e3d8566f19f350906dea5a7d2e0/12-f9bae8dcb7de1132c45bdc82d5679aec6a4f0567f0d934f537afc4725ccb6563.jpg
12-14 01:42:41.130 28948 31334 E MangaDex: Connecting to MD@Home node at https://cpdnh97kz2dyw.b43khn6qp7jz0.mangadex.network/r9-PSlg6iaCmwCiZANnSWZI3TWhqx4v7mGT9IwHruoL3udF_OPGvt4_4X9aGfLUHoWl49q6v5TBom3U5GYO6-NZF9MMBNSYggBxSp6dZ2F93wQ9c6ZMhgDOCCWMvgqfSDiUg1A2NIq2axrYPcEQqio4nZLLsyWpCGTTilP8Gwt25mTrkvuNZ00O-jR64aA/data-saver/bada8e3d8566f19f350906dea5a7d2e0/13-9a32a0b9dc69ce5e8ea9824e9682287e57d471a1e14d5e33978a51fd79baa7e9.jpg
12-14 01:42:41.333 28948 31346 E MangaDex: Connecting to MD@Home node at https://cpdnh97kz2dyw.b43khn6qp7jz0.mangadex.network/r9-PSlg6iaCmwCiZANnSWZI3TWhqx4v7mGT9IwHruoL3udF_OPGvt4_4X9aGfLUHoWl49q6v5TBom3U5GYO6-NZF9MMBNSYggBxSp6dZ2F93wQ9c6ZMhgDOCCWMvgqfSDiUg1A2NIq2axrYPcEQqio4nZLLsyWpCGTTilP8Gwt25mTrkvuNZ00O-jR64aA/data-saver/bada8e3d8566f19f350906dea5a7d2e0/14-3af436e310a6e0ba20a3ecb3ae1fb0de579b11f9ca50ba663e95efc18a95be6f.jpg
12-14 01:42:41.543 28948 31346 E MangaDex: Connecting to MD@Home node at https://cpdnh97kz2dyw.b43khn6qp7jz0.mangadex.network/r9-PSlg6iaCmwCiZANnSWZI3TWhqx4v7mGT9IwHruoL3udF_OPGvt4_4X9aGfLUHoWl49q6v5TBom3U5GYO6-NZF9MMBNSYggBxSp6dZ2F93wQ9c6ZMhgDOCCWMvgqfSDiUg1A2NIq2axrYPcEQqio4nZLLsyWpCGTTilP8Gwt25mTrkvuNZ00O-jR64aA/data-saver/bada8e3d8566f19f350906dea5a7d2e0/15-da89cdccb75a3584333296069b2b50f461e882dbd8249306c226e33bdfffa3c2.jpg
12-14 02:11:33.872  5108  5150 E SQLiteLog: (283) recovered 494 frames from WAL file /data/user/0/eu.kanade.tachiyomi/databases/tachiyomi.db-wal
12-14 02:11:34.819  5108  5108 E BufferQueueProducer: Unable to open libpenguin.so: dlopen failed: library "libpenguin.so" not found.
12-14 02:11:37.882  5108  5108 E ACRA    : ACRA caught a IllegalArgumentException for eu.kanade.tachiyomi
12-14 02:11:37.882  5108  5108 E ACRA    : java.lang.IllegalArgumentException: Key Screen#0:transition:lifecycle was used multiple times 
12-14 02:11:37.882  5108  5108 E ACRA    : 	at androidx.compose.runtime.saveable.SaveableStateHolderImpl$SaveableStateProvider$1$1.invoke(SaveableStateHolder.kt:71)
12-14 02:11:37.882  5108  5108 E ACRA    : 	at androidx.compose.runtime.DisposableEffectImpl.onRemembered(Effects.kt:7)
12-14 02:11:37.882  5108  5108 E ACRA    : 	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:94)
12-14 02:11:37.882  5108  5108 E ACRA    : 	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:81)
12-14 02:11:37.882  5108  5108 E ACRA    : 	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:6)
12-14 02:11:37.882  5108  5108 E ACRA    : 	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:218)
12-14 02:11:37.882  5108  5108 E ACRA    : 	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:9)
12-14 02:11:37.882  5108  5108 E ACRA    : 	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:34)
12-14 02:11:37.882  5108  5108 E ACRA    : 	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:13)
12-14 02:11:37.882  5108  5108 E ACRA    : 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1299)
12-14 02:11:37.882  5108  5108 E ACRA    : 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
12-14 02:11:37.882  5108  5108 E ACRA    : 	at android.view.Choreographer.doCallbacks(Choreographer.java:923)
12-14 02:11:37.882  5108  5108 E ACRA    : 	at android.view.Choreographer.doFrame(Choreographer.java:847)
12-14 02:11:37.882  5108  5108 E ACRA    : 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
12-14 02:11:37.882  5108  5108 E ACRA    : 	at android.os.Handler.handleCallback(Handler.java:942)
12-14 02:11:37.882  5108  5108 E ACRA    : 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-14 02:11:37.882  5108  5108 E ACRA    : 	at android.os.Looper.loopOnce(Looper.java:226)
12-14 02:11:37.882  5108  5108 E ACRA    : 	at android.os.Looper.loop(Looper.java:313)
12-14 02:11:37.882  5108  5108 E ACRA    : 	at android.app.ActivityThread.main(ActivityThread.java:8762)
12-14 02:11:37.882  5108  5108 E ACRA    : 	at java.lang.reflect.Method.invoke(Native Method)
12-14 02:11:37.882  5108  5108 E ACRA    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
12-14 02:11:37.882  5108  5108 E ACRA    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
12-14 02:11:37.882  5108  5108 E ACRA    : 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@b838bc8, androidx.compose.ui.platform.MotionDurationScaleImpl@49a461, StandaloneCoroutine{Cancelling}@376bb86, AndroidUiDispatcher@654dc47]
12-14 02:11:38.646  6142  6167 E SQLiteLog: (283) recovered 3 frames from WAL file /data/user/0/eu.kanade.tachiyomi/databases/tachiyomi.db-wal
12-14 02:11:40.000  6298  6378 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
12-14 02:11:40.418  6298  6298 E BufferQueueProducer: Unable to open libpenguin.so: dlopen failed: library "libpenguin.so" not found.
12-14 02:11:40.477  6298  6519 E SQLiteLog: (284) automatic index on C(manga_id)
12-14 02:11:40.477  6298  6519 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.14.7 (standard, c8d6859, 102, 2023-10-25T16:11Z)
Android version: 13 (SDK 33)
Android build ID: TP1A.220624.014.G9910ZHS6EWJ1
Device brand: samsung
Device manufacturer: samsung
Device name: o1q
Device model: SM-G9910
Device product name: o1qzhx
```

### Tachiyomi version

0.14.7 stable

### Android version

Android 13

### Device

Galaxy S21 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-12-16 15:11
Duplicate of #9352

**Closed by arkon** 2023-12-16 15:11 UTC
Labels: Bug
