### ISSUE TITLE
Lack of folders and Its hard to move categories

### ISSUE THREAD

**Issue by Mistikitten** [tachiyomiorg/tachiyomi#10317] opened 2024-01-07 06:10 UTC
### Describe your suggested feature

As a person who makes too many categories it would be nice if i could organize them by putting them inside a folder.

WHY CANT I JUST EASILY DRAG MY CATEGORY TO THE TOP AND NOT SUFFER BY CLICKING UP, I LITERALLY HAVE +30 CATEGORIES PLZ LET ME DRAG IT.

Thanks.
-MK

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by THElegend5** [comment] 2024-01-07 07:55
Duplicate of #8325

**Closed** 2024-01-07 13:06 UTC
Labels: Feature request
