### ISSUE TITLE
some feature i like to request

### ISSUE THREAD

**Issue by kucingkembar** [tachiyomiorg/tachiyomi#6212] opened 2021-11-07 17:45 UTC
### Describe your suggested feature

hi, sorry for my bad English, I have some features for future release
1. if the title is too long, I can't read the chapter number, something like this
  isekai another world became hero brave with unique skill chapter 1
  isekai another world became hero brave with unique skill chapter 2
  in chapter list reader as
  isekai another world became hero brave with,,,
  isekai another world became hero brave with...
 
    please add slide feature at text chapter list or something so I can read chapter number

2. if the image(s) is too "tall" sometimes the smartphone is lagging, I know there is a software called ImageMagick that can detect image height and split it to the desired height, please split them is too tall

3. please add "HTML page to chapter" (I don't know what it should be called), I have some manga, comic, or whatever it is called, that is not in tachiyomi extension, but I like to read it in tachiyomi, this is the link: 
https://www.kmansin01.com/bbs/board.php?bo_table=2001&wr_id=2805&sfl=wr_subject&stx=%E9%81%A0%E6%85%AE%E3%81%AA%E3%81%8F%E5%8F%AC%E3%81%97%E4%B8%8A%E3%81%8C%E3%82%8C
I don't know how it supposes to works, but if you put the chapter link, tachiyomi  will analyze the page and download the images

thank you for reading, and have a nice day

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2021-11-07 23:19
You should open 1 issue per issue in the future.

---

1. You can change the display mode to chapter numbers from the filter sheet. Otherwise, if you think the chapter names can be shortened appropriately, open a request in the extensions repository.
2. Duplicate of #1908
3. You can request new sources in the extensions repository.

**Closed by arkon** 2021-11-07 23:19 UTC
Labels: Feature request
