### ISSUE TITLE
 APPLICATION CRASHES WHEN READING MANGA NORMALLY WHEN CHANGE PAGE

### ISSUE THREAD

**Issue by talhamantam** [tachiyomiorg/tachiyomi#9131] opened 2023-02-22 19:39 UTC
### Steps to reproduce

1. Open any manga (it will look better if it has more pages)
2. Switch between pages

### Expected behavior

There should be a smooth and seamless transition between pages.

### Actual behavior

App freezes and crashes when switching between pages while reading manga

### Crash logs

--------- beginning of main
02-22 22:16:12.650 17672 17728 E SQLiteLog: (283) recovered 24 frames from WAL file /data/data/eu.kanade.tachiyomi/databases/tachiyomi.db-wal
02-22 22:16:12.685 17672 17672 E ResourceType: Style contains key with bad entry: 0x0101056c
02-22 22:16:12.706 17672 17672 E ResourceType: Style contains key with bad entry: 0x0101056d
02-22 22:16:12.706 17672 17672 E ResourceType: Style contains key with bad entry: 0x0101058c
02-22 22:16:12.706 17672 17672 E ResourceType: Style contains key with bad entry: 0x01010604
02-22 22:16:12.706 17672 17672 E ResourceType: Style contains key with bad entry: 0x01010605
02-22 22:16:12.723 17672 17672 E ResourceType: Style contains key with bad entry: 0x0101056d
02-22 22:16:12.723 17672 17672 E ResourceType: Style contains key with bad entry: 0x0101058c
02-22 22:16:12.723 17672 17672 E ResourceType: Style contains key with bad entry: 0x01010604
02-22 22:16:12.723 17672 17672 E ResourceType: Style contains key with bad entry: 0x01010605

### Tachiyomi version

0.14.5

### Android version

Android 7

### Device

Galaxy Note 5

### Other details

I recorded the problem as a video.

https://drive.google.com/file/d/18q9VKnUqG9gTK07E6-uIZgm2OPunkFBD/view?usp=drivesdk

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-02-23 23:45
Duplicate of #1908

**Closed by arkon** 2023-02-23 23:45 UTC
Labels: Bug
