### ISSUE TITLE
Can update library in tachiyomi

### ISSUE THREAD

**Issue by RoSiCyBeR** [tachiyomiorg/tachiyomi#9898] opened 2023-08-31 12:06 UTC
### Steps to reproduce

1. I'm open app
2. Go to extension
3. And I'm tap update all or update 1 by 1 i'ts nothing happened

### Expected behavior

Before I'm update in latest app this never happens I'm update the extension

### Actual behavior

The original incident can usually be directly updated but now the Update must be downloaded via the web and not through the application... the original can be updated using VPN... But now even using a VPN can't

*note: sorry my bad english

### Tachiyomi version

"0.14.6"

### Android version

Android 11

### Device

Sony Xperia xz2 (SOV37) 

### Other details

![Screenshot_20230831-185441](https://github.com/tachiyomiorg/tachiyomi/assets/34416860/30bb1c73-b275-4add-a017-f0229cd6a764)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by joaoandre120** [comment] 2023-08-31 19:40
Happened something similar with me. Try to reboot the system, worked for me.

**Comment by arkon** [comment] 2023-09-03 14:13
Duplicate of #4106

**Closed by arkon** 2023-09-03 14:13 UTC
Labels: Bug
