### ISSUE TITLE
Extensions Sometime Can Go Missing / No Longer Detected

### ISSUE THREAD

**Issue by nevrending** [tachiyomiorg/tachiyomi#5540] opened 2021-07-12 15:42 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 11

### Device

Mi 11

### Steps to reproduce

Extensions sometime can go missing / no longer detected.

<details>
  <summary>They're gone!</summary>

  ![1626103564786](https://user-images.githubusercontent.com/4745298/125315025-12736600-e37a-11eb-9236-b18515cf9c2c.jpg)

  ![1626103564784](https://user-images.githubusercontent.com/4745298/125315092-20c18200-e37a-11eb-96cc-82f495ef9ac5.jpg)

</details>

This happens at random, without any additional installation/removal of extensions or library items.
When this happens, it will break the library auto-update (ie all library items are marked as update failed).

### Expected behavior

This should not happen.

### Actual behavior

Extensions can go missing / no longer detected at random.

### Other details

Toggling the "Show in sources list" option under NSFW (18+) sources then restarting the app, "solves" the issue (all of the currently installed extensions are detected again, and library update can be performed normally).

See: https://github.com/tachiyomiorg/tachiyomi/issues/4972#issuecomment-828218167

<details>
  <summary>1. Toggle "Show in sources list" & restart app.</summary>

  ![1626103564782](https://user-images.githubusercontent.com/4745298/125315965-fcb27080-e37a-11eb-9059-45019080edfd.jpg)

</details>

<details>
  <summary>2. After restarting the app, all installed extensions are detected.</summary>

  ![1626103564779](https://user-images.githubusercontent.com/4745298/125315974-ff14ca80-e37a-11eb-9554-0387523c3681.jpg)

</details>

**Comment by alessandrojean** [comment] 2021-07-12 15:49
Sounds to be related to the nonstandard practices Xiaomi does with Miui.

**Comment by arkon** [comment] 2021-07-12 15:50
Duplicate of #4313

**Closed by arkon** 2021-07-12 15:50 UTC
Labels: Bug
