### ISSUE TITLE
When the library is large, update only a portion of it at a time.

### ISSUE THREAD

**Issue by messageXX** [tachiyomiorg/tachiyomi#9300] opened 2023-04-06 05:45 UTC
### Describe your suggested feature

If update a large number of manga/comics from the same source might hurts the source, can there be an option to let us update only a portion of the library when updating.
Like update 1 manga and wait for a second, then update the next, until all the content in the library is updated.
Thank you!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Sakurahime08** [comment] 2023-04-06 07:54
May I also suggest for your library/bookmarked titles to update automatically as they appear or when you browse to see the chapter updates in the bwrose source tab? 

So that we don't have to update all the titles in the library especially if there are a lot. Thank you

**Comment by arkon** [comment] 2023-04-06 13:09
Duplicate of #6968

**Closed by arkon** 2023-04-06 13:09 UTC
Labels: Feature request
