### ISSUE TITLE
Put a "new" sticker on the new added extensions 

### ISSUE THREAD

**Issue by DeltaBeam** [tachiyomiorg/tachiyomi#6001] opened 2021-10-01 12:03 UTC
### Describe your suggested feature

Add "NEW" sticker to the newly added extensions which last for few days or weeks 

### Other details

In the extention page if a new extension is added there should be a "New Added" sticker on it so we can try it, its difficult to distinguish new added and old extensions 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2021-10-01 12:16
Duplicate of #4363

**Closed by arkon** 2021-10-01 12:16 UTC
Labels: Feature request
