### ISSUE TITLE
landscape library view is obstructed by navigation bar

### ISSUE THREAD

**Issue by zdanee2** [tachiyomiorg/tachiyomi#6216] opened 2021-11-09 12:10 UTC
### Steps to reproduce

Start Tachiyomi in landscape
If you have a visible navigation bar, it will hover above the covers

### Expected behavior

Expected to scale the library view to fit

### Actual behavior

The covers will be partially covered by the navigation bar.

Example: https://ibb.co/tX6qLGG

### Tachiyomi version

0.12.3 (Stable 2021-10-04)

### Android version

Android 11

### Device

LG V50s

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2021-11-19 15:21
Did this happen on earlier versions too? I believe this is an issue with some ROMs' custom navigation bar hiding implementation, since we've seen it happen on older versions of Samsung's One UI too which eventually got replaced/fixed.

**Comment by zdanee2** [comment] 2021-11-21 10:20
It did not happen in 0.10.12 stable. I use a vanilla LG ROM on the latest Android 11 patch on a V50s (also known as a G8x), non-rooted.

**Comment by zdanee2** [comment] 2021-11-21 10:29
I own a second G8x which is on Android 10, rooted. The bug is also present on Android 10 with 0.12.3 but not in 0.10.12

**Comment by blackholeearth** [comment] 2021-11-21 10:48
![screengrab-20211121-134542](https://user-images.githubusercontent.com/7512105/142758766-0267466d-9123-498a-90a3-e25358d1aa1e.jpg)


I have Moto g4 .  Android 8.1 .  same things happens .
 10.12 didn't have this problem.

**Comment by ghostbear** [comment] 2021-12-11 11:13
Duplicate of #6102

Was fixed in #6104 which will be included in the next release of Tachiyomi and is currently in the Preview version

**Closed** 2021-12-11 12:39 UTC
Labels: Bug
