### ISSUE TITLE
download five chapters ahead feature 

### ISSUE THREAD

**Issue by bodint** [tachiyomiorg/tachiyomi#7540] opened 2022-07-15 18:30 UTC
### Describe your suggested feature

Each time I download unreaded chapters from a title I haven't read for a while. I have a message about downloading too many chapters may cause harm to sources.
It would be nice to have a feature downloading a few chapters to where we're at, and each time a chapter is read it would download a new one.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2022-07-15 19:00
Duplicate of #3295

**Closed** 2022-07-15 19:02 UTC
Labels: Feature request
