### ISSUE TITLE
Saving Filters

### ISSUE THREAD

**Issue by sylenso** [tachiyomiorg/tachiyomi#6775] opened 2022-03-13 17:35 UTC
an option that can allow users to save the filters they set up in an extension. maybe beside the reset button. 

for example, in some extensions, there are a lot of option for the filters, and choosing them one by one each and every time can be exhausting and so to make it more efficient, once were done choosing the filters, maybe the option to save the filter gets activated and it gets stored along with other saved filters

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-03-13 17:42
Duplicate of #1484

**Closed by arkon** 2022-03-13 17:42 UTC
Labels: Feature request
