### ISSUE TITLE
Download speed limit

### ISSUE THREAD

**Issue by hamoody348** [tachiyomiorg/tachiyomi#9262] opened 2023-03-26 14:44 UTC
### Describe your suggested feature

The option to choose the download speed like 512/kp
Or 128/kp

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-03-26 14:50
Duplicate of #7319

**Closed** 2023-03-26 14:50 UTC
Labels: Feature request
