### ISSUE TITLE
Option to display Chapter Quantity in All Extension & Global seaches

### ISSUE THREAD

**Issue by REFLEXGAMING007** [tachiyomiorg/tachiyomi#9966] opened 2023-09-29 06:46 UTC
### Describe your suggested feature

It's really gonna save a lot of time searching for stuff if we have a 'display chapter quantity' option for all extension & global searches similar to library's 'unread chapter' option.

![20230929_101504](https://github.com/tachiyomiorg/tachiyomi/assets/56241882/fdd1fb80-d140-4eff-9b88-def0df1cc89d)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by BrutuZ** [comment] 2023-09-29 07:12
The way I see it, this would require one request for each manga entry shown in the results just for that little bit of information. Search results come in bulk with basic information like title and cover, while their details - including chapter list - are on a separate step. Just notice how it takes a couple of seconds to populate the chapter list, description, tags, etc when you first open a manga entry.

If I'm right, this would go against Tachiyomi's anti-DDoS policy\measures

**Comment by AntsyLich** [comment] 2023-09-29 15:38
Duplicate of #2867

**Closed by AntsyLich** 2023-09-29 15:38 UTC
Labels: Feature request
