### ISSUE TITLE
Not downloading new chapters

### ISSUE THREAD

**Issue by Leverpastej** [tachiyomiorg/tachiyomi#9560] opened 2023-05-30 16:43 UTC
### Steps to reproduce

Hi,

The app isn't downloading new chapters.
The queue in Download queue isn't changing 

### Expected behavior

I expected that the download queue should go down in number 

### Actual behavior

It's staying at the same number of chapters or increasing 

### Tachiyomi version

App version: 0.14.6-5813 (standard, 46efd4c13, 103, 2023-05-27T21:08Z) Android version: 13 (SDK 33) Android build ID: TQ2A.230505.002 Device brand: google Device manufacturer: Google Device name: cheetah Device model: Pixel 7 Pro Device product name: cheetah

### Android version

13

### Device

Pixel pro 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Leverpastej** [comment] 2023-05-30 16:44
App version: 0.14.6-5813 (standard, 46efd4c13, 103, 2023-05-27T21:08Z)
Android version: 13 (SDK 33)
Android build ID: TQ2A.230505.002
Device brand: google
Device manufacturer: Google
Device name: cheetah
Device model: Pixel 7 Pro
Device product name: cheetah

**Comment by Two-Ai** [comment] 2023-05-31 22:18
Could you please attach a screenshot or video?

**Comment by Leverpastej** [comment] 2023-06-02 14:58
Here's a video:
https://photos.app.goo.gl/8DcVyAmu3X2VQs6i6

**Comment by Two-Ai** [comment] 2023-06-04 02:36
I tested locally with the same source and was able to reproduce the issue. It seems like there are two problems:

1. After a few chapters, MangaHub started rate limiting, causing downloads to fail.
   * `API rate limit excessed! Go to mangahub.io to continue reading!`
   * This is an issue with MangaHub or the MangaHub extension, should be raised in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
2. Failed downloads look the same as queued downloads when looking at the downloads queue.
   * The downloader is trying each download in the queue and failing on each because of the rate limiting. Since failed downloads look the same as queued downloads, it looks like nothing is happening. Eventually the downloader will reach the end of the queue and pause itself, but this takes a long time because there are many chapters in the queue.

**Comment by Leverpastej** [comment] 2023-06-04 22:56
> I tested locally with the same source and was able to reproduce the issue. It seems like there are two problems:
> 
> 1. After a few chapters, MangaHub started rate limiting, causing downloads to fail.
>    
>    * `API rate limit excessed! Go to mangahub.io to continue reading!`
>    * This is an issue with MangaHub or the MangaHub extension, should be raised in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
> 2. Failed downloads look the same as queued downloads when looking at the downloads queue.
>    
>    * The downloader is trying each download in the queue and failing on each because of the rate limiting. Since failed downloads look the same as queued downloads, it looks like nothing is happening. Eventually the downloader will reach the end of the queue and pause itself, but this takes a long time because there are many chapters in the queue.

Thank you @Two-Ai!
I figured that the issue was with MangaHub so I'll check the extension repository.
I had the same issue with Mangakakalot but that has been resolved since those downloads are without issue.

As for number 2; I don't remember this behavior in previous versions (like a year ago). If I remember correctly it said "failed" (or something) in the download queue. 

So what do I/we do with this issue (the nr 2). Do we keep it open?

**Comment by Leverpastej** [comment] 2023-06-04 22:59
FYI
This started when I switch phones and when I did the backup and restore procedure. 
After the restore, it wanted to download old manga (those have ended and not been updated) and those I've already read.
I think the backup doesn't track which chapters that are unread or my backup failed somehow.

**Comment by Leverpastej** [comment] 2023-06-04 23:01
A bug report for MangaHub has already been done :)
![image](https://github.com/tachiyomiorg/tachiyomi/assets/20172244/befa6c97-b187-4b19-a7c8-06bd2c2701a3)

**Comment by manavchaudhary1** [comment] 2023-06-18 16:15
@leverpastej Maybe the extension you are trying to download has Cloudflare protection .
SOLUTION:Change your extension then try to download

**Comment by alessandrojean** [comment] 2023-07-09 19:25
Closing as this is an extension issue likely and these cases are listed in the troubleshooting guide in the acknowledgements section.

**Closed by alessandrojean** 2023-07-09 19:25 UTC
Labels: Bug
