### ISSUE TITLE
Extension Search Crashes Index Out of Bounds

### ISSUE THREAD

**Issue by Flat** [tachiyomiorg/tachiyomi#10084] opened 2023-10-28 19:06 UTC
### Steps to reproduce

1. Go to "Browse"
2. Go to "Extensions"
3. Tap Search Icon
4. Type fl
5. Crash

(Specifically it seemed to only crash on "fl" for me, with other searching being ok.)

### Expected behavior

It should filter the extensions by the typed text.

### Actual behavior

Crash

### Crash logs
```
--------- beginning of crash
10-28 14:59:09.572 23109 23109 E AndroidRuntime: FATAL EXCEPTION: main
10-28 14:59:09.572 23109 23109 E AndroidRuntime: Process: eu.kanade.tachiyomi.debug, PID: 23109
10-28 14:59:09.572 23109 23109 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Index 8, size 8
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at androidx.compose.foundation.lazy.layout.MutableIntervalList.checkIndexBounds(SourceFile:31)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at androidx.compose.foundation.lazy.layout.MutableIntervalList.get(SourceFile:1)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at androidx.compose.foundation.lazy.layout.LazyLayoutKt.getKey(SourceFile:5)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at androidx.compose.foundation.lazy.LazyListItemProviderImpl.getKey(SourceFile:11)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at androidx.compose.foundation.lazy.LazyListKt$rememberLazyListMeasurePolicy$1$1$measuredItemProvider$1.getAndMeasure(SourceFile:9)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at androidx.compose.foundation.lazy.LazyListMeasureKt.measureLazyList-50ZNEM8(SourceFile:67)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at androidx.compose.foundation.lazy.LazyListKt$rememberLazyListMeasurePolicy$1$1.invoke(SourceFile:482)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at androidx.compose.foundation.lazy.layout.LazyLayoutKt$LazyLayout$3$2$1.invoke(SourceFile:22)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1.measure-3p2s80s(SourceFile:99)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at androidx.compose.ui.node.InnerNodeCoordinator$LookaheadDelegateImpl.measure-BRTryo0(SourceFile:63)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at androidx.compose.foundation.AndroidOverscrollKt$StretchOverscrollNonClippingLayer$1.invoke-3p2s80s(SourceFile:45)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at androidx.compose.foundation.AndroidOverscrollKt$StretchOverscrollNonClippingLayer$1.invoke(SourceFile:32)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at androidx.compose.ui.layout.LayoutModifierImpl.measure-3p2s80s(SourceFile:7)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at androidx.compose.ui.node.InnerNodeCoordinator$LookaheadDelegateImpl.measure-BRTryo0(SourceFile:98)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at androidx.compose.foundation.AndroidOverscrollKt$StretchOverscrollNonClippingLayer$1.invoke-3p2s80s(SourceFile:8)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at androidx.compose.foundation.AndroidOverscrollKt$StretchOverscrollNonClippingLayer$1.invoke(SourceFile:17)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at androidx.compose.ui.layout.LayoutModifierImpl.measure-3p2s80s(SourceFile:7)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at androidx.compose.ui.node.InnerNodeCoordinator$LookaheadDelegateImpl.measure-BRTryo0(SourceFile:98)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(SourceFile:1)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at androidx.compose.ui.node.InnerNodeCoordinator$LookaheadDelegateImpl.measure-BRTryo0(SourceFile:98)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performLookaheadMeasure$1.invoke(SourceFile:18)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(SourceFile:61)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SourceFile:52)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SourceFile:171)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(SourceFile:3)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release(SourceFile:11)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate.access$performLookaheadMeasure-BRTryo0(SourceFile:25)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$LookaheadPassDelegate.remeasure-BRTryo0(SourceFile:144)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNode.lookaheadRemeasure-_Sx5XlM$ui_release(SourceFile:18)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNode.lookaheadRemeasure-_Sx5XlM$ui_release$default(SourceFile:7)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at androidx.compose.ui.node.MeasureAndLayoutDelegate.doLookaheadRemeasure-sdFAvZA(SourceFile:16)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at androidx.compose.ui.node.MeasureAndLayoutDelegate.remeasureAndRelayoutIfNeeded(SourceFile:106)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureAndLayout(SourceFile:67)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidComposeView.measureAndLayout(SourceFile:26)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at androidx.compose.ui.node.Owner$-CC.measureAndLayout$default(SourceFile:4)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(SourceFile:12)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at android.view.View.draw(View.java:23892)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22756)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4540)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4513)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22712)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4540)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4513)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22712)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4540)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4513)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22712)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4540)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4513)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22712)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4540)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4513)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22712)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4540)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4513)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22712)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:694)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:700)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:798)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4939)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4643)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3822)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2465)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9305)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1339)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1348)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:952)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:882)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1322)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:958)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:205)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:294)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8177)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
10-28 14:59:09.572 23109 23109 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
10-28 14:59:11.023 23542 23542 E tachiyomi.debug: Not starting debugger since process cannot load the jdwp agent.
10-28 14:59:11.155 23542 23615 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
10-28 14:59:11.228 23542 23632 E chromium: [1028/145911.227199:ERROR:variations_seed_loader.cc(69)] Failed to open file for reading. Errno: 2
App version: 0.14.6-6132 (standard, 8057f067b, 107, 2023-10-25T13:24Z)
Android version: 14 (SDK 34)
Android build ID: UD1A.230803.041
Device brand: google
Device manufacturer: Google
Device name: husky
Device model: Pixel 8 Pro
Device product name: husky
WebView: Android System WebView 118.0.5993.111

```

### Tachiyomi version

0.14.6-6132

### Android version

14

### Device

Google Pixel 8 Pro

### Other details

https://github.com/tachiyomiorg/tachiyomi/assets/2048861/cbe55bc5-c616-462e-a354-aefb5013035d

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-10-28 19:08
Duplicate of #10069 (fixed for the next release).

**Closed by arkon** 2023-10-28 19:08 UTC
Labels: Bug
