### ISSUE TITLE
[Feature Request] Default Reading Mode by Extension/Source

### ISSUE THREAD

**Issue by ConorORiordan** [tachiyomiorg/tachiyomi#5036] opened 2021-05-07 15:20 UTC
## Why/User Benefit/User Problem
Currently, all series are automatically set to use the reading mode chosen as default when first opened and must be changed on a case-by-case basis.

For the most part, this is perfectly fine, but it can be frustrating when using sources that primarily deal with series that are best suited for a different reading mode than the default.

The out-of-the-box default reading mode is set to 'Right to Left' (which makes sense considering that Tachiyomi is primarily designed to read manga), but some sources (i.e. Webtoon, Comicpunch, etc) primarily deal with content that has a different reading direction than manga and as such requires that each series from them will need the user to manually change the reading mode.

Adding the ability to set the default reading mode on a per-extension basis would help improve the user experience by removing the need to constantly change the reading mode for everything, only needing to change it when the series in question is not the 'standard' format the user expects from a given source.

## What/Requirements
A setting would need to be added to the extensions (likely located in the existing extension settings menu), allowing the user to set the reading mode for the extension. The options should match the reading modes options given in the reader itself (allowing the choice of the defined app default or a specific mode), and should be set to app default when extensions are first installed.

Some care will need to be given to ensure that changing the extension default reading mode does not override any user selected reading modes for series under that extension.

Priority for reading mode should be Series -> Extension -> App

**Comment by Seishirou101** [comment] 2021-05-07 15:28
duplicate of #4649

**Closed** 2021-05-07 15:34 UTC
Labels: feature
