### ISSUE TITLE
Pin manga on top

### ISSUE THREAD

**Issue by antocs** [tachiyomiorg/tachiyomi#7333] opened 2022-06-18 17:11 UTC
### Describe your suggested feature

It would Pin the selected manga on top of the category (since many categories can be on the library) or enable this just for the default category.
Useful if you wanna highlight the manga you are focussing on, to avoid searching it among all the titles in the library.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-06-19 20:22
Duplicate of #3656

**Closed by arkon** 2022-06-19 20:22 UTC
Labels: Feature request
