### ISSUE TITLE
Jerky or non-existent scrollbar in manga with few chapters

### ISSUE THREAD

**Issue by Xori71** [tachiyomiorg/tachiyomi#10354] opened 2024-01-08 00:23 UTC
### Steps to reproduce

1. Select a manga.
2. Start scrolling slowly.
3. Pay attention to the scrollbar.

### Expected behavior

The scrollbar should always exhibit smooth movement, from top to bottom, and should always stop right above the “Resume” button, or at the bottom of the screen, should the aforementioned button not exist.

Also, and that's obvious, the scrollbar should always be visible when scrolling.

### Actual behavior

The scrollbar exhibits jerky movement at some points of its travel, that lessens in magnitude the more chapters a manga has.

Furthermore, if the chapter number is too small, the scrollbar will end its movement further up, rather than right above the “Resume” button.

Also, when the chapter number is small enough so as for the scrolling to be minimal, the scrollbar will make its appearance and swiftly disappear before reaching the bottom of the chapter list.

https://github.com/tachiyomiorg/tachiyomi/assets/101265862/5aeca182-03a1-4878-99ed-8b162212a774

https://github.com/tachiyomiorg/tachiyomi/assets/101265862/9b4ef8af-c3f4-442f-9ffc-2d779d09a83e

### Tachiyomi version

0.15.1

### Android version

Android 14

### Device

Redmi Note 9 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2024-01-08 02:54
Duplicate of #9730 and #8091

**Closed by arkon** 2024-01-08 02:54 UTC
Labels: Bug
