### ISSUE TITLE
Manual update excluding chapters from app list

### ISSUE THREAD

**Issue by dashenio** [tachiyomiorg/tachiyomi#6729] opened 2022-03-03 13:28 UTC
### Steps to reproduce

Select series, drag to update

### Expected behavior

Update new chapters, leaving the already downloaded ones alone

### Actual behavior

Deletes downloaded chapters from the list (they are marked as not downloaded), although they are still intact in the chapter file directory.

### Tachiyomi version

0.13.1

### Android version

10

### Device

Infinix Zero 8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by dashenio** [comment] 2022-03-03 15:07
> Which source/manga What's your Library Update Frequency? And do you use an sdcard?

Source: Bato.to
Update frequency: whole library once a day, but also click individual series throughout the day
Scared: yes

**Comment by curche** [comment] 2022-03-03 15:16
Maybe this might be something to with the sdcard. Please create a Crashlog from `More > Settings > Advanced > Dump crashlogs` and Upload the generated file here

**Comment by dashenio** [comment] 2022-03-03 17:38
[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/8179813/tachiyomi_crash_logs.txt)

**Comment by curche** [comment] 2022-03-03 18:11
Thanks! 
looking at the crash there indeed seems to be a Permission issue (somehow...)
this makes this a possible duplicate of #6714 where the user was unable to read downloaded files after restarting the app
Please do check out the issue, and upload the file there. If you have something more to add, you can comment on that issue

I'll close this for now
If you feel both issues need to be separate, you can comment here

**Closed by curche** 2022-03-03 18:11 UTC
Labels: Bug
