### ISSUE TITLE
The library updating progress bar broken on force update

### ISSUE THREAD

**Issue by Helltraitor** [tachiyomiorg/tachiyomi#7002] opened 2022-04-24 13:55 UTC
### Steps to reproduce

1. Start library update via button or force update of some category
2. Force update any other category

### Expected behavior

Progress bars merged:
1 category 11 / 70
2 category 1 / 60
^^^ Become to vvv
Updating library... 12 / 130

### Actual behavior

One bar replaced by another but not bar counter (see other details)

### Tachiyomi version

0.13.4

### Android version

Android 11

### Device

Realme 8 Pro

### Other details

Screen recording of the issue (Note of library update numbers `a / b`, a > b)

https://user-images.githubusercontent.com/95148327/164979868-1f75591f-d5da-405c-8a89-0b7006f5fcbb.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-04-24 13:57
Duplicate of #6825

**Closed by arkon** 2022-04-24 13:57 UTC
Labels: Bug
