### ISSUE TITLE
Multi selection entry update

### ISSUE THREAD

**Issue by Amejonah1200** [tachiyomiorg/tachiyomi#9033] opened 2023-02-05 19:02 UTC
### Describe your suggested feature

It would be nice to select multiple entries in library and have an option for updating them, so I don't need to update all my entries just for 2 entries which came out some monutes ago.
Alternative would be to create another category, but this is troublesome because you need to move them.

**Comment by arkon** [comment] 2023-02-05 19:17
Duplicate of #4060

**Closed by arkon** 2023-02-05 19:17 UTC
Labels: Feature request
