### ISSUE TITLE
History no longer chooses last read chapter

### ISSUE THREAD

**Issue by Pever3ll** [tachiyomiorg/tachiyomi#8624] opened 2022-11-26 22:31 UTC
### Steps to reproduce

1. Take a manga that is fully read
2. Open up to a random chapter in the middle
3. Go to history and press on the manga to open it

### Expected behavior

It should open up to the random chapter you just opened up

### Actual behavior

It says there are no more chapters because it only checks for unread chapters in history instead of the latest chapter you read

### Tachiyomi version

0.14.2

### Android version

Android 12

### Device

OnePlus 8

### Other details

While the history still shows the chapter number of the chapter you opened up, it doesn't act the way it feels like it should saying that there are no chapters.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-11-26 22:33
Duplicate of #8454

**Closed by arkon** 2022-11-26 22:33 UTC
Labels: Bug
