### ISSUE TITLE
No Chapters Found (Mangaowl)

### ISSUE THREAD

**Issue by kaoru013** [tachiyomiorg/tachiyomi#6739] opened 2022-03-05 15:45 UTC
### Steps to reproduce

1. Opened a manga from mangowl
2. Opening a chapter to read
3. It keeps on loading
4. At the bottom, it says "no chapter found"
5. Tried to reload it
6. Download latest mangaowl from extension repository  which is ​version 1.2.24
8. Reload it again
9. Tried deleting cache, reload tracks
10. Still it says "no chapter found"
11. I can open it in the website

### Expected behavior

This should happen, the manga will load itself in the application so that I won't keep on opening the website to read the manga.

### Actual behavior

This happened instead, I always read in the website. There are various advertisements as well in the website.

### Crash logs

App version: 0.13.1 (standard, d6386ce, 74, 2022-02-01T17:35Z)
Android version: 9 (SDK 28)
Android build ID: PPR1.180610.011.G955FXXUCDUD1
Device brand: samsung
Device manufacturer: samsung
Device name: dream2lte
Device model: SM-G955F
Device product name: dream2ltexx

### Tachiyomi version

Tachiyomi v.0.13.1

### Android version

Android v. 9

### Device

Samsung galaxy s8+

### Other details

Whenever I refresh my library, these errors pops out.
![Screenshot_20220305-234402_HTML Viewer](https://user-images.githubusercontent.com/81219627/156890315-6859d9ea-faed-4a4d-8db0-b933e547ae2f.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-03-05 15:46
Wrong repo, duplicate of https://github.com/tachiyomiorg/tachiyomi-extensions/issues/10463

**Closed by arkon** 2022-03-05 15:46 UTC
Labels: Bug

**Comment by kaoru013** [comment] 2022-03-05 15:48
@arkon, thank you very much!
