### ISSUE TITLE
Tachiyomi keeps crashing

### ISSUE THREAD

**Issue by Prometheus0000** [tachiyomiorg/tachiyomi#9064] opened 2023-02-10 10:25 UTC
### Steps to reproduce

I'm not sure how to reproduce for sure, but it's happened multiple times while scrolling down (dragging my finger up to go down) on a comic in webtoon mode, with the split chapter option on (if that matters), that was downloaded. It happened ~3 times in the same chapter at the same point, so I thought it might just be that one, but now it's happened with a different series' chapter too. It seems be be only happening since the last update?

### Expected behavior

Not to crash

### Actual behavior

Crashes

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/10706267/tachiyomi_crash_logs.txt)

BTW, your help thing doesn't list where to actually find the crash log, I had to crawl through previous issues to find that out.

### Tachiyomi version

0.14.4

### Android version

7.0

### Device

Asus Zenpad (3S 10? Not sure about this part) P027 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-02-11 15:24
> BTW, your help thing doesn't list where to actually find the crash log, I had to crawl through previous issues to find that out.

The form literally says "If you're experiencing crashes, share the crash logs from More → Settings → Advanced then press Dump crash logs.".

---

Excerpt from logs:

```
02-10 04:35:59.199  9348 15532 E SubsamplingScaleImageView: Failed to initialise bitmap decoder
02-10 04:35:59.199  9348 15532 E SubsamplingScaleImageView: java.lang.Exception: Image decoder failed to initialize and get image size
02-10 04:35:59.199  9348 15532 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.decoder.ImageDecoder.init(ImageDecoder.java:46)
02-10 04:35:59.199  9348 15532 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:8)
02-10 04:35:59.199  9348 15532 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1)
02-10 04:35:59.199  9348 15532 E SubsamplingScaleImageView: 	at android.os.AsyncTask$2.call(AsyncTask.java:304)
02-10 04:35:59.199  9348 15532 E SubsamplingScaleImageView: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-10 04:35:59.199  9348 15532 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
02-10 04:35:59.199  9348 15532 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
02-10 04:35:59.199  9348 15532 E SubsamplingScaleImageView: 	at java.lang.Thread.run(Thread.java:761)
```

**Comment by arkon** [comment] 2023-02-11 15:25
Duplicate of #8261

**Closed by arkon** 2023-02-11 15:25 UTC
Labels: Bug

**Comment by Prometheus0000** [comment] 2023-02-12 19:04
> > BTW, your help thing doesn't list where to actually find the crash log, I had to crawl through previous issues to find that out.
> 
> The form literally says "If you're experiencing crashes, share the crash logs from More → Settings → Advanced then press Dump crash logs.".
> 

Yes, that's how I created the crash log, but it doesn't say what folder it gets created in though. And while you can dump more logs to see a notification with a shortcut to open it or share it (which I didn't realize at first), I'm not entirely sure that tells you the location, and it seems to overwrite the file, too, so it might not have the error anymore (maybe? I'm not certain how it works). I don't think it's asking a lot to just add the folder it dumps to to the help page.

Hopefully you can fix it soon as it was happening every couple minutes today.
