### ISSUE TITLE
"The image couldn't be loaded" but shows image/page

### ISSUE THREAD

**Issue by Megalobst** [tachiyomiorg/tachiyomi#9512] opened 2023-05-17 07:54 UTC
### Steps to reproduce

None (don't know)

### Expected behavior

A black page with Image couldn't be loaded error with option to retry loading page and open webview
Or
A normal image/page

### Actual behavior

Error is layered on top of chapter page. Get's resolved after reopening chapter a couple of times.

![Screenshot_20230517_093112_TachiyomiJ2K](https://github.com/tachiyomiorg/tachiyomi/assets/99219589/bcc9b0ed-f865-4972-850e-c88d7d233a75)

### Tachiyomi version

1.6.6 j2k

### Android version

13

### Device

Samsung Galaxy Tab S8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [x] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by krae93** [comment] 2023-05-18 06:35
![Screenshot_20230518_013358_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/37887569/5905548d-5a2f-4a42-a92d-b1b0af01204d)

When attempting to download these chapters this error pops up

**Comment by arkon** [comment] 2023-05-21 13:42
Duplicate of #5687

**Closed by arkon** 2023-05-21 13:42 UTC
Labels: Bug
