### ISSUE TITLE
Download queue jumps up when re ordering

### ISSUE THREAD

**Issue by kaizerboo** [tachiyomiorg/tachiyomi#9130] opened 2023-02-22 05:59 UTC
### Steps to reproduce

1. Add about 20 manga chapters to download queue.
2. Go to download queue.
3. Drag the 2nd last chapter to the bottom of the queue

### Expected behavior

2nd last chapter should be brought to the bottom of the queue 

### Actual behavior

Entire queue jumps up, making the re-ordering of the download queue difficult.

### Tachiyomi version

Stable 0.14.5

### Android version

Android 12

### Device

Oppo reno 3 pro

### Other details

https://user-images.githubusercontent.com/29338688/220535709-c0481ce2-1351-42b5-b2ad-26b8994514d6.mp4

Recording of issue

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2023-02-22 07:32
Duplicate of #8996

**Closed by stevenyomi** 2023-02-22 07:32 UTC
Labels: Bug
