### ISSUE TITLE
Deleting Categories Crashes the Application

### ISSUE THREAD

**Issue by vishesh211** [tachiyomiorg/tachiyomi#9021] opened 2023-02-04 12:53 UTC
### Steps to reproduce

1. Go to More and click on categories.
2. Created some categories.
3. Go to browser and add some manga in the categories.
4. Go back to more and delete the categories.

### Expected behavior

After deleting the categories the manga should still be displayed in the library but instead the app crashes.

### Actual behavior

The application crashes when you go back to library after deleting the categories.

### Crash logs

[tachiyomi_crash_logs (2).txt](https://github.com/tachiyomiorg/tachiyomi/files/10608675/tachiyomi_crash_logs.2.txt)

### Tachiyomi version

0.14.3-5488 (dev, f2c48480b, 94, 2023-02-01T20:38Z)

### Android version

Android 11

### Device

Redmi Note 9

### Other details

https://user-images.githubusercontent.com/61341524/216768626-5d3eb17f-cb64-4d91-8f18-1f3682d263ae.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by TheSeriousYoungBoy** [comment] 2023-02-04 14:16
Editing the Category's name also gives me a fatal error but it sometimes occurs.

**Comment by arkon** [comment] 2023-02-04 14:58
Duplicate of #8921

**Closed by arkon** 2023-02-04 14:58 UTC
Labels: Bug
