### ISSUE TITLE
1stkiss extension show http error 403

### ISSUE THREAD

**Issue by Yuiling** [tachiyomiorg/tachiyomi#6113] opened 2021-10-15 16:38 UTC
### Steps to reproduce

Cannot update library list.
Cannot access 1st kiss extension to search manga.

### Expected behavior

It should appear the manga list when i enter the source. Library also should be able to update.

### Actual behavior

1st kiss extension cannot use to watch manga.
Show error HTTP 403: try webview to see website

### Tachiyomi version

Latest version

### Android version

Android 10

### Device

Huawei Nova

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment] 2021-10-15 16:47
>  If this is an issue with an extension, I should be opening an issue in the extensions repository.

Duplicate of https://github.com/tachiyomiorg/tachiyomi-extensions/issues/9377

**Closed by CarlosEsco** 2021-10-15 16:47 UTC
Labels: Bug
