### ISSUE TITLE
[Bug] pages not loading constantly clearing cache

### ISSUE THREAD

**Issue by Peachymo** [tachiyomiorg/tachiyomi#5028] opened 2021-05-06 05:00 UTC
Using version stable 0.10.12
I'm using my Samsung galaxy tab s6 lite with android 11

For a couple weeks I've been constantly having to clear my cache in the middle of reading on the app. This happens with every source I'm using. I'll be reading, then the next page won't load. The reload thing is there but clicking it does nothing. I go clear my cache and the issue is fixed. But it will happen again randomly. Tonight alone I've had to do it at least 6 times while reading 4-5 chapters of one Manga. I've tried all the troubleshooting I read about doing. I'm just looking for a more permanent fix because this is excessive and frustrating.

Edit: still having this issue, but mostly with the bato.to source. Not sure what f it's actually a more frequent issue with this source or if I'm just using it more than others.

**Comment by MIC132** [comment] 2021-07-08 01:55
I have exactly the same issue, on latest preview (literally updated today) and using Mangadex, so it's probably not source specific.
This is on Huawei Nova.

Been happening for a long time, probably should have written an issue earlier.

I noticed that usually when it happens and I go to clear the cache it's just shy of 100MB, do that might be related. (Or maybe it just auto cleans above that, and it's unrelated)

**Comment by arkon** [comment] 2022-07-10 00:08
Duplicate of #4633

**Closed by arkon** 2022-07-10 00:08 UTC
Labels: Bug
