### ISSUE TITLE
App lightens after using an arrow key to change the page

### ISSUE THREAD

**Issue by mekiah343** [tachiyomiorg/tachiyomi#5648] opened 2021-08-02 19:32 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 11

### Device

Galaxy Tab s7+

### Steps to reproduce

1. Connect a physical keyboard to andriod device
2. Open a manga
3. Use an arrow key to change the page

### Expected behavior

The app should display the next page, nothing else should change.

### Actual behavior

The app lightens, blacks become dark greys.

**Comment by arkon** [comment] 2021-08-02 19:46
Duplicate of #5555

**Closed by arkon** 2021-08-02 19:46 UTC
Labels: Bug
