### ISSUE TITLE
Random Generator Manga/Manhwa/Manhua

### ISSUE THREAD

**Issue by Dexter0211** [tachiyomiorg/tachiyomi#6202] opened 2021-11-06 10:55 UTC
### Describe your suggested feature

It will generate random manga/manhwa/manhua in your default category or other category. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment] 2021-11-06 10:59
Duplicate of #1248

**Closed by loocool2** 2021-11-06 10:59 UTC
Labels: Feature request
