### ISSUE TITLE
Additional Tracker

### ISSUE THREAD

**Issue by Dark723** [tachiyomiorg/tachiyomi#10321] opened 2024-01-07 07:09 UTC
### Describe your suggested feature

Please add support for anime-planet as a tracker.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment] 2024-01-07 07:12
Duplicate of #1785

**Closed by AntsyLich** 2024-01-07 07:12 UTC
Labels: Feature request

**Comment by Dark723** [comment] 2024-01-07 07:17
Will it ever happen in the future?
