### ISSUE TITLE
Application always crashes while update and viewing manga

### ISSUE THREAD

**Issue by Beji-kun** [tachiyomiorg/tachiyomi#8742] opened 2022-12-14 22:26 UTC
### Steps to reproduce

Device: Poco X3 Při, Android 12, MIUI 13
Application version: Stable 0.14.2 (battery optimization off on MIUI)

Scenario
Open app -->
Click and globally update manga (try from history or manga list) -->

### Expected behavior

Application will normally update withouts crashed app

### Actual behavior

Applications after some time (about 2-3 min) crash andust open a donut retry update. On the old version 0.13.6 withouts problem updates 

### Crash logs

--------- beginning of main
12-14 22:59:55.120  9904  9938 E SQLiteLog: (5) statement aborts at 1: [PRAGMA journal_mode=TRUNCATE] database is locked
12-14 22:59:57.184  9904 10022 E SQLiteLog: (284) automatic index on C(manga_id)
12-14 22:59:57.184  9904 10022 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
12-14 23:02:53.251  9904 12132 E CursorWindow: Failed to read row 2385, column 0 from a CursorWindow which has 2385 rows, 13 columns.
12-14 23:02:53.255  9904  9904 E ACRA    : ACRA caught a NullPointerException for eu.kanade.tachiyomi
12-14 23:02:53.255  9904  9904 E ACRA    : java.lang.NullPointerException
12-14 23:02:53.255  9904  9904 E ACRA    : 	at eu.kanade.tachiyomi.app.UpdatesViewQueriesImpl$updates$1.invoke(DatabaseImpl.kt:19)
12-14 23:02:53.255  9904  9904 E ACRA    : 	at com.squareup.sqldelight.Query.executeAsList(Query.kt:18)
12-14 23:02:53.255  9904  9904 E ACRA    : 	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToList$1$1.invokeSuspend(FlowExtensions.kt:6)
12-14 23:02:53.255  9904  9904 E ACRA    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
12-14 23:02:53.255  9904  9904 E ACRA    : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
12-14 23:02:53.255  9904  9904 E ACRA    : 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
12-14 23:02:53.255  9904  9904 E ACRA    : 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
12-14 23:02:53.255  9904  9904 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
12-14 23:02:53.255  9904  9904 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:66)
12-14 23:02:53.255  9904  9904 E ACRA    : 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@477e495, Dispatchers.Main.immediate]
12-14 23:02:53.903 12302 12328 E SQLiteLog: (283) recovered 993 frames from WAL file /data/user/0/eu.kanade.tachiyomi/databases/tachiyomi.db-wal
12-14 23:03:01.624 12435 12478 E SQLiteLog: (5) statement aborts at 1: [PRAGMA journal_mode=TRUNCATE] database is locked
12-14 23:03:03.901 12435 12698 E SQLiteLog: (284) automatic index on C(manga_id)
12-14 23:03:03.901 12435 12698 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
12-14 23:12:39.814 12435 13848 E CursorWindow: Failed to read row 2385, column 0 from a CursorWindow which has 2385 rows, 13 columns.
12-14 23:12:39.816 12435 12435 E ACRA    : ACRA caught a NullPointerException for eu.kanade.tachiyomi
12-14 23:12:39.816 12435 12435 E ACRA    : java.lang.NullPointerException
12-14 23:12:39.816 12435 12435 E ACRA    : 	at eu.kanade.tachiyomi.app.UpdatesViewQueriesImpl$updates$1.invoke(DatabaseImpl.kt:19)
12-14 23:12:39.816 12435 12435 E ACRA    : 	at com.squareup.sqldelight.Query.executeAsList(Query.kt:18)
12-14 23:12:39.816 12435 12435 E ACRA    : 	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToList$1$1.invokeSuspend(FlowExtensions.kt:6)
12-14 23:12:39.816 12435 12435 E ACRA    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
12-14 23:12:39.816 12435 12435 E ACRA    : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
12-14 23:12:39.816 12435 12435 E ACRA    : 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
12-14 23:12:39.816 12435 12435 E ACRA    : 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
12-14 23:12:39.816 12435 12435 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
12-14 23:12:39.816 12435 12435 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:66)
12-14 23:12:39.816 12435 12435 E ACRA    : 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@6807e3f, Dispatchers.Main.immediate]
12-14 23:12:40.511 13945 14001 E SQLiteLog: (283) recovered 468 frames from WAL file /data/user/0/eu.kanade.tachiyomi/databases/tachiyomi.db-wal
12-14 23:14:23.796 14278 14322 E SQLiteLog: (5) statement aborts at 1: [PRAGMA journal_mode=TRUNCATE] database is locked
12-14 23:14:26.913 14278 14466 E SQLiteLog: (284) automatic index on C(manga_id)
12-14 23:14:26.913 14278 14466 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
12-14 23:18:13.637 14278 17562 E CursorWindow: Failed to read row 2385, column 0 from a CursorWindow which has 2385 rows, 13 columns.
12-14 23:18:13.639 14278 14278 E ACRA    : ACRA caught a NullPointerException for eu.kanade.tachiyomi
12-14 23:18:13.639 14278 14278 E ACRA    : java.lang.NullPointerException
12-14 23:18:13.639 14278 14278 E ACRA    : 	at eu.kanade.tachiyomi.app.UpdatesViewQueriesImpl$updates$1.invoke(DatabaseImpl.kt:19)
12-14 23:18:13.639 14278 14278 E ACRA    : 	at com.squareup.sqldelight.Query.executeAsList(Query.kt:18)
12-14 23:18:13.639 14278 14278 E ACRA    : 	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToList$1$1.invokeSuspend(FlowExtensions.kt:6)
12-14 23:18:13.639 14278 14278 E ACRA    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
12-14 23:18:13.639 14278 14278 E ACRA    : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
12-14 23:18:13.639 14278 14278 E ACRA    : 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
12-14 23:18:13.639 14278 14278 E ACRA    : 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
12-14 23:18:13.639 14278 14278 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
12-14 23:18:13.639 14278 14278 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:66)
12-14 23:18:13.639 14278 14278 E ACRA    : 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@b57617e, Dispatchers.Main.immediate]
12-14 23:18:14.324 17723 17753 E SQLiteLog: (283) recovered 755 frames from WAL file /data/user/0/eu.kanade.tachiyomi/databases/tachiyomi.db-wal
12-14 23:18:23.523 17919 17957 E SQLiteLog: (5) statement aborts at 1: [PRAGMA journal_mode=TRUNCATE] database is locked
12-14 23:18:25.424 17919 18046 E SQLiteLog: (284) automatic index on C(manga_id)
12-14 23:18:25.424 17919 18046 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.14.2 (standard, 3222247, 91, 2022-10-31T21:42Z)
Android version: 12 (SDK 31)
Android build ID: SKQ1.211006.001 test-keys
Device brand: POCO
Device manufacturer: Xiaomi
Device name: vayu
Device model: M2102J20SG
Device product name: vayu_id

### Tachiyomi version

0.14.2

### Android version

Android 12

### Device

Poco X3 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment] 2022-12-14 22:47
>  12-14 22:59:55.120 9904 9938 E SQLiteLog: (5) statement aborts at 1: [PRAGMA journal_mode=TRUNCATE] database is locked

do you have MIUI optimisations turned on or off? 
if its on, turn it off and try again. if its off, turn it on and try it again

**Comment by Beji-kun** [comment] 2022-12-15 09:37
MIUI battery optimization is OFF 😓.

**Comment by Beji-kun** [comment] 2022-12-15 10:49
Application crash even while reading manga...

**Comment by scb261** [comment] 2023-02-04 04:48
Duplicate of #8400

**Closed** 2023-02-04 14:20 UTC
Labels: Bug
