### ISSUE TITLE
Mirrored Pages option

### ISSUE THREAD

**Issue by AlexFsk** [tachiyomiorg/tachiyomi#9722] opened 2023-07-15 23:12 UTC
### Describe your suggested feature

Can you guys please add the possibility of mirroring the page because some pages are mirrored in the opposite direction and confuse the reading direction, love from italy

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-07-16 02:54
Duplicate of #8258

**Closed by arkon** 2023-07-16 02:54 UTC
Labels: Feature request
