### ISSUE TITLE
Black Line in middle if an image

### ISSUE THREAD

**Issue by ARiyou2000** [tachiyomiorg/tachiyomi#8702] opened 2022-12-08 16:51 UTC
### Steps to reproduce

It only happens sometimes but i was able to reproduce it. 

1. Open a manhua on any source. (e.g. Flame Scans (EN), Omniscient Reader’s Viewpoint, Ch. 136, Pg. 5) 
2. Make note that it happens to only some pages. 
3. Consider following conditions:

* In "Webtoon" and "Continuous Vertical" mode The Black Line:
----Is visible at 100% Zoom(normal view). 
----Will display even when scrolling.
----Will not display if you Zoom-in or Zoom-out a little. 

* In other view mode:
----Is Visible at maximum zoom-in and only when scrolling. 
----Will not display if you zoom-out or stop scrolling. 

* It happens to one image and it's not something that shown as gap between two continues pages. 

* It will usually occurs In approximately 50% of image height. 

* Pictures and manhua are completely fine and will show correctly on web view

* Picture itself have no issues (i went to "Tachiyomi/downloads/Flame Scans (EN)/Omniscient Reader’s Viewpoint/Chapter 136" and opened that image with other apps and it shown perfectly)

* I tried it with local source, online and download chapter but The Black Line was still there.

* I tried it with both folder and CBZ. 

* I don't know if it happenes to short image as well but i think it should happen to tall images.

* My split tall image when download if OFF. 

* Following picture is from Flame Scans (EN), Omniscient Reader’s Viewpoint, Ch. 136, Pg. 5 (in webtoon mode):
![IMG_20221208_185315](https://user-images.githubusercontent.com/35896230/206508733-c3b30836-52aa-46ee-b486-c360bafc07c5.jpg)

* Same image in webtoon mode with little zoom-in / zoom-out :
![Screenshot_20221208-182237](https://user-images.githubusercontent.com/35896230/206508863-04756c0a-e475-42fc-a713-6fc1e4a7b45a.jpg)

* Web view mode of same image :
![Screenshot_20221208-190645](https://user-images.githubusercontent.com/35896230/206509044-7148c6d4-8fde-435a-bf68-bd0a14937b37.jpg)

### Expected behavior

Image must be shown without the Black Line.

### Actual behavior

Image with Black line at the Middle

### Tachiyomi version

0.14.2 (standard, 3222247, 91, 2022-10-31T21:42Z)

### Android version

Android 8.0.0 (SDK 26)

### Device

HUAWEI Mate 10 lite (RNE-L21)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-12-08 16:53
Duplicate of #6840

**Closed** 2022-12-08 16:53 UTC
Labels: Bug
