### ISSUE TITLE
[Feature Request] Ability to set custom colors

### ISSUE THREAD

**Issue by rayes0** [tachiyomiorg/tachiyomi#5416] opened 2021-06-17 16:51 UTC
## Why/User Benefit/User Problem

This is a relatively low importance feature, but it would be cool to have a settings window where the user would be able to set a custom colors for parts of the app (bg, fg, checkbox colors, slider colors etc.), so that users could use a custom theme in addition to the built-in ones.

## What/Requirements

Add a dedicated theme window with an assortment of themable ui elements. The user can choose custom colors with a color picker. The current built-in themes could be set as presets, and there should be an add button where the user can add and name a custom theme.

**Comment by Seishirou101** [comment] 2021-06-17 17:00
Duplicate of #3451

**Closed** 2021-06-17 17:00 UTC
Labels: feature
