### ISSUE TITLE
[Feature Request] Migrate obsolete extensions

### ISSUE THREAD

**Issue by Ashu11-A** [tachiyomiorg/tachiyomi#4762] opened 2021-04-01 23:33 UTC
There is a possibility to migrate all manga (or some) from an obsolete, or not obsolete, extension to a given  extension.

If the extension provided does not have a specific manga, notify or classify it in the category: Default  

that would be very useful! Since it takes a lot of work having to migrate a manga at a time

**Comment by SamSensei** [comment] 2021-04-02 06:10
Mass migration of manga is supported by Tachiyomi forks , it may be available in Tachiyomi itself in future.

**Comment by arkon** [comment] 2021-04-03 14:22
Duplicate of #1231.

**Closed by arkon** 2021-04-03 14:22 UTC
Labels: feature
