### ISSUE TITLE
Manga in Library does not get downloaded whenever there is updates

### ISSUE THREAD

**Issue by richylyq** [tachiyomiorg/tachiyomi#6673] opened 2022-02-18 06:27 UTC
### Steps to reproduce

1. go to Updates Tab
2. Press the refresh/sync button

### Expected behavior

Mangas with new updates should get queued automatically for download

### Actual behavior

Extensions that does not get automatically queued for download.
1. MangaRock Team 
2. Mangakakalot
3. Mangahere
4. MangaLife

### Tachiyomi version

0.13.1

### Android version

Android 12

### Device

Samsung S10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by BhaturaGuy** [comment] 2022-02-20 05:03
I second this. Ignoring the android version or the device. It pretty much happens to me and my friends too. Whenever I exclude any category from downloading it doesn't download _any_ new chapter. Only workaround is to NOT use Auto-Download based on Categories.

**Comment by FourTOne5** [comment] 2022-02-20 06:08
Duplicate of #6541

**Comment by chacho2me** [comment] 2022-02-20 06:12
please do add NINEMANGA as well. 

webview shows updated chapters but not on the app

**Closed** 2022-02-20 13:14 UTC
Labels: Bug
