### ISSUE TITLE
Random missing pages that reappear if the app is closed and reopened

### ISSUE THREAD

**Issue by Bsrihg** [tachiyomiorg/tachiyomi#9906] opened 2023-09-03 15:16 UTC
### Steps to reproduce

1. Open a manhwa try to Read it and it has missing pages/images
2. Close the chapter and re open it and the page/images appear correctly and after some seconds some disappear (in webview it work and if downloaded it work) 

### Expected behavior

All the pages Should load

### Actual behavior

The re are same page missing

### Tachiyomi version

App version: 0.14.6-6027 (standard, f32243899, 105, 2023-08-26T21:08Z)

### Android version

Android 13

### Device

Samsung s22

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Ashraf-Ali-aa** [comment] 2023-09-18 14:58
Looks like there is a bug in the scroll view, I am getting the same issue, if you rotate the screen and rotate it back it resolves the issue.

**Comment by arkon** [comment] 2023-09-21 02:33
Duplicate of #8433, probably.

**Closed by arkon** 2023-09-21 02:33 UTC
Labels: Bug
