### ISSUE TITLE
[Bug] Covers from Mangamx won't load

### ISSUE THREAD

**Issue by Mtkmanjaro** [tachiyomiorg/tachiyomi#4721] opened 2021-03-27 19:40 UTC
The covers in Mangamx do not load, however if you go to see the chapters the cover will load

**Comment by arkon** [comment] 2021-03-27 19:41
Duplicate of https://github.com/tachiyomiorg/tachiyomi-extensions/issues/6313; do not open duplicates (or in the wrong repo) please.

**Closed by arkon** 2021-03-27 19:41 UTC
