### ISSUE TITLE
Sort downloads by comic name and chapter

### ISSUE THREAD

**Issue by TheKingTermux** [tachiyomiorg/tachiyomi#8974] opened 2023-01-23 05:11 UTC
### Describe your suggested feature

Able to sort by comic name and able to sort by chapter name in the comic

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment] 2023-01-23 05:40
What do you mean by "sort downloads"? If you're looking at downloads via a file manager, then you should install a file manager that allows an alphabetical sort.

About sorting in the library - you can already filter only downloaded entries and sort them alphabetically.

About sorting chapters - it's a bit weird to sort them by name instead of their number / source order / upload date. Could you give a use case where it actually would be useful?

**Comment by TheKingTermux** [comment] 2023-01-23 05:52
> What do you mean by "sort downloads"? If you're looking at downloads via a file manager, then you should install a file manager that allows an alphabetical sort.
> 
> About sorting in the library - you can already filter only downloaded entries and sort them alphabetically.
> 
> About sorting chapters - it's a bit weird to sort them by name instead of their number / source order / upload date. Could you give a use case where it actually would be useful?

No no
I mean at the download section
Like this
![Screenshot_2023-01-23-12-50-01-75_afd66b7916d19a60815f56273408b73e.jpg](https://user-images.githubusercontent.com/50316075/213973736-41bed832-5ea9-4ff7-a5dc-2d60a5a7f917.jpg)

This download section is randomizer
And the chapter is randomizer too
Because that the downloaded comic in the library like this
![Screenshot_2023-01-23-12-51-13-54_afd66b7916d19a60815f56273408b73e.jpg](https://user-images.githubusercontent.com/50316075/213973893-7afa8597-1fb8-4220-a963-bb9c652246b9.jpg)

**Comment by scb261** [comment] 2023-01-23 06:02
Related: #3730

As for your issue, I'm not sure why it downloaded in random order, but there is an option to sort the download queue by chapter number (`⋮` > `Reorder` > `By chapter number` > `Ascending`)

**Comment by stevenyomi** [comment] 2023-01-24 17:01
Duplicate of #3730

And partially exists.

**Closed by stevenyomi** 2023-01-24 17:01 UTC
Labels: Feature request
