### ISSUE TITLE
"Source not found" for background updates

### ISSUE THREAD

**Issue by hyoretsu** [tachiyomiorg/tachiyomi#9667] opened 2023-07-03 12:18 UTC
### Steps to reproduce

Not sure how to reproduce, but it happens on automatic (12h) updates, probably after the app's been killed in the background (all battery optimizations are disabled).

### Expected behavior

It should update mangas in the background.

### Actual behavior

It doesn't. It's not a "Too many requests" issue, because if I open the app and do a manual update, I get a lot of new chapters. Sometimes this goes for days on end, until I do a manual update.

### Tachiyomi version

Preview r5882

### Android version

Android 13

### Device

Xiaomi Redmi Note 11

### Other details

![Screenshot_2023-07-03-09-13-08-887_com microsoft emmx](https://github.com/tachiyomiorg/tachiyomi/assets/20804322/74202dd0-78cd-4b51-9c0b-084fc73c4b30)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment] 2023-07-03 21:24
Possibly relevant #9569

**Comment by hyoretsu** [comment] 2023-07-03 22:19
It's quite possible that we're facing the same issue. My downloads also disappear when coming back from background.

**Comment by arkon** [comment] 2023-09-03 14:21
Duplicate of #9569

**Closed by arkon** 2023-09-03 14:21 UTC
Labels: Bug
