### ISSUE TITLE
Auto Split Long Images after download

### ISSUE THREAD

**Issue by saud-97** [tachiyomiorg/tachiyomi#6973] opened 2022-04-22 01:54 UTC
### Describe your suggested feature

The feature is basically to add an option to enable auto splitting of the long images of 5000px height or more to equal parts.
This is doable via ImageMagick package or maybe make use of this project [TachiyomiImageSplitter](https://github.com/Lightjohn/TachiyomiImageSplitter) (This app doesn't work due to outdated libraries).

Whole idea is to run a command to split the images after they are downloaded.
For example 001.png [2500x12000] will become:
001.1.png [2500x4000]
001.2.png [2500x4000]
001.3.png [2500x4000].

### Other details

This will solve many memory and loading issues / crashes affecting webtoons. 
Eg.: [Long Strip Split for Webtoon](https://github.com/tachiyomiorg/tachiyomi/pull/5759)

**My suggestion is only affecting downloaded chapters so this has nothing to do with the reader code spaghetti at all to simplify solving the issue.**

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by FourTOne5** [comment] 2022-04-22 22:46
This has one issue what if it's splits manga like chapters? That won't be fun to read.

**Comment by saud-97** [comment] 2022-04-23 03:03
> This has one issue what if it's splits manga like chapters? That won't be fun to read.

Well first of all it doesn't matter what type of manga if it has very long images it would still affect memory and causes instability.
Secondly I'm suggesting adding this as an option inside the reader settings with it being on by default.

**Comment by arkon** [comment] 2022-04-24 19:27
Ultimately a duplicate of #1908.

**Closed by arkon** 2022-04-24 19:27 UTC
Labels: Feature request

**Comment by saud-97** [comment] 2022-04-24 22:27
@arkon I know this feature can help with the issue you mentioned. However my solution doesn't really solve the reader original issue and root cause. Therefore if my solution was applied it would still not have no effect on chapters being read on the fly without downloading beforehand afaik. 

Hear me out. Why not keep this feature for 0.x, and for 1.x the reader code will be optimized more and there will be no need for this feature for 1.x?
