### ISSUE TITLE
Impossible to download chapter

### ISSUE THREAD

**Issue by o01210o** [tachiyomiorg/tachiyomi#6039] opened 2021-10-04 20:55 UTC
### Steps to reproduce

I tried to download from other sources and it's the same
![image](https://user-images.githubusercontent.com/45663409/135922003-ad27d1ff-59d8-4e70-9c2a-d7acba44f01c.png)

### Expected behavior

The download is starting and the circle is rotating and show the progress

### Actual behavior

![GIF 2021-10-04 16-51-52](https://user-images.githubusercontent.com/45663409/135923174-de83c447-5237-4d46-9377-3f9330db9d35.gif)

![image](https://user-images.githubusercontent.com/45663409/135922305-7a18568a-e88d-42ff-ae25-6c6c67335487.png)

It says an error happened during the download and it says to try in the download sectio

### Tachiyomi version

0.12.3

### Android version

11

### Device

Google Pixel 3

### Other details

Happens after today's update

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2021-10-04 21:06
Duplicate of #6038

**Closed by arkon** 2021-10-04 21:06 UTC
Labels: Bug

**Comment by o01210o** [comment] 2021-10-04 21:08
> Duplicate of #6038

Oh, I guess we were writting at the same time, I've search for duplicate but I'didn't see it.
