### ISSUE TITLE
Chapters appear wrongly greyed out

### ISSUE THREAD

**Issue by dumitrache-adrian92** [tachiyomiorg/tachiyomi#9897] opened 2023-08-30 19:51 UTC
### Steps to reproduce

Note: check out [this](https://github.com/tachiyomiorg/tachiyomi/assets/67505529/51574ecd-2d44-4a45-be69-9314c7bf0dce
) video to see the behavior in action

These steps don't always reproduce the problem on my end, but it happens fairly often (and is something rather simplistic):
1. Open a series with a lot of chapters
2. Scroll down past the unread chapters
3. Scroll up

Some chapters may now appear greyed out, even though they weren't a second ago. They don't seem to count as read by other metrics besides being greyed out: it doesn't decrement the number of unread chapters and if you press the mark as read/unread button it first marks it as read and then as unread. It may be relevant that I had the chapters downloaded or that the series has multiple translators.
Things I've done recently: imported my library from my old phone (Xiaomi Redmi Note 8 Pro) to my new phone (Samsung A34), installed the app through Samsung's weird transfer app, reinstalled it cause I thought it would fix this bug

### Expected behavior

Chapters should not be greyed out when scrolling past them.

### Actual behavior

Sometimes chapters grey out fairly randomly.

### Tachiyomi version

0.14.6

### Android version

Android 13

### Device

Samsung A34 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-08-30 21:06
Duplicate of #9043, it's fixed for the next release

**Closed** 2023-08-30 21:06 UTC
Labels: Bug

**Comment by dumitrache-adrian92** [comment] 2023-08-31 09:32
Damn, sorry for the bother then and thank you for fixing it. I only looked up "grey" instead of "gray" when searching for duplicates :)))
