### ISSUE TITLE
Download ahead does not work

### ISSUE THREAD

**Issue by DatHypnoboi** [tachiyomiorg/tachiyomi#9651] opened 2023-06-29 12:16 UTC
### Steps to reproduce

1. Enable downloading 2 chapters ahead
2. Download first 2 chapters of a series
3. Start reading first chapter

### Expected behavior

The third chapter should begin downloading

### Actual behavior

The third chapter does not begin downloading

### Tachiyomi version

0.14.6 Preview r5863

### Android version

Android 13

### Device

Google Pixel 6a

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-06-29 12:25
Duplicate of #9471, it'll be in the next build.

**Closed** 2023-06-29 12:25 UTC
Labels: Bug
