### ISSUE TITLE
[Feature request] Custom predetermined autozoom

### ISSUE THREAD

**Issue by Jae4th** [tachiyomiorg/tachiyomi#5325] opened 2021-06-06 05:21 UTC
I tend to read most of my manga with one hand, which sometimes makes it hard to read without zooming in. Luckily, by double tapping you can zoom in, but it's inconsistent as it can zoom in too much/not enough depending on the manga and panel. That's why I believe there should be a feature that allows you to customize how much the screen will zoom in when double tapping. This will help those who read with one hand such as myself.

I'm not developer so I don't know how hard it would be to implement this, but there should be a section in the readers tab of settings where you can change how much you want the autozoom to zoom in (Maybe with a visual example of how much it will zoom in with a manga page or something for easy experimenting). If possible, you can even make a feature where if you hold the screen, you can freely zoom in and out by moving your finger up and down so you can easily read certain panels depending on labels. Since holding on the screen already has a purpose, it could be an option that can be toggled on and off so it won't get it the way with everything else. That is all. Other than that Tachiyomi is a great application 👍🏼

**Comment by loocool2** [comment] 2021-06-06 05:27
Duplicate of #228

**Closed by loocool2** 2021-06-06 05:27 UTC
Labels: feature
