### ISSUE TITLE
Local Source location 

### ISSUE THREAD

**Issue by Solovertical** [tachiyomiorg/tachiyomi#9244] opened 2023-03-21 17:46 UTC
### Describe your suggested feature

Currently local source only detect sources when it's in Structure
" Internal shared storage > Tachiyomi > local "

So let say if we moved whole structure inside a Folder "Internal shared storage > Folder > Folder1 >Tachiyomi > local"
It didn't detect sources from local  structure. Even changing download location only help in downloaded location
So add option to manually change desired location of local source.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment] 2023-03-21 17:49
Duplicate of #2086

**Closed by loocool2** 2023-03-21 17:49 UTC
Labels: Feature request
