### ISSUE TITLE
[Feature Request] <Please add a feature to back-up bookmarks>

### ISSUE THREAD

**Issue by IAmBestR2J** [tachiyomiorg/tachiyomi#4718] opened 2021-03-27 03:43 UTC
---

## Why/User Benefit/User Problem
(I bookmarked more than 400 chapters from various manga/manhwa but, I had to reset my mobile, so I did a manual back-up and saved the file to Google drive. When I tried to restore some manga/manhwa didn't restore (like 9~10 out of 85 which I can add to library without any problem) So did the bookmarks (there's no way I can do that for bookmarks as there are so many that don't even remember). In the end, I lost those bookmarked chapters Everyone bookmarks something coz they might read those again, in future. So, please add the feature as it will be very helpful for many people. Thanks in advance.)

## What/Requirements
(It could either be a seperate feature, or embedded in the existing back-up feature the later one is preferred.)

**Comment by arkon** [comment] 2021-03-28 14:56
Backups already contain chapter bookmark flags, so I'm not sure what you're describing.

**Comment by arkon** [comment] 2021-03-30 22:01
Closing since this should already be working. Open a bug report if it not, preferably with a backup file to reproduce the issue.

**Closed by arkon** 2021-03-30 22:01 UTC
Labels: feature
