### ISSUE TITLE
[Feature Request] Allow folder additions to non-local source manga to fill missing chapter gaps

### ISSUE THREAD

**Issue by Matakor** [tachiyomiorg/tachiyomi#3956] opened 2020-10-21 00:30 UTC
Mostly this would just allow one to say take from an old downloaded source that has now dropped a series and move it to the new source that has picked it up.

Ideally, it would even move using migrate, but just adding the chapter folders to the base source folder should also work. If it was done this way, could have a small indication next to the chapter number or name showing that it was an "alt" or "old" source, or "migrated source".

I don't particularly like using aggregates for this because they tend to grab the first source regardless of quality and sorting through each chapter is just annoying (not to mention some aggregates also don't have every chapter either).

**Comment by monMusu** [comment] 2020-10-23 10:25
So like we have 20 chapters from Mangahere, but chapter 5 is missing. We then **individually** import the missing chapter 5 from another site like Mangafreak. This needs to be **implemented** pronto.

**Comment by arkon** [comment] 2022-10-08 17:18
Duplicate of #3958

**Closed by arkon** 2022-10-08 17:18 UTC
Labels: Feature request
