### ISSUE TITLE
Unable to download due to illegal name to create system folder

### ISSUE THREAD

**Issue by xwyjhs** [tachiyomiorg/tachiyomi#10214] opened 2023-12-04 10:43 UTC
### Steps to reproduce

Try to download a manga with too long name or name contain illegal char. 
Folder names in the system have a maximum character limit. And certain special symbols cannot appear in the folder name. If the name of the downloaded comic has the above characteristics, the software will make an error when downloading and creating a folder, causing the folder to be unable to be created and thus unable to be downloaded.

For example, search [Tororo gunso] hitoku no kuchibiru ~ reikoku kishi wa joyoku o kakushi kirenai ~ in E-hentai or 美龍艶笑譚 in Jmcomics.

### Expected behavior

Click the download button to download。

### Actual behavior

No response after clicking the download button or the continue button. Check the file directory, no corresponding folder is created.

### Crash logs

--------- beginning of main
12-04 17:43:04.572 29324 29362 E SQLiteLog: (283) recovered 2 frames from WAL file /data/user/0/eu.kanade.tachiyomi/databases/tachiyomi.db-wal
12-04 17:43:04.933 29324 29505 E SQLiteLog: (284) automatic index on C(manga_id)
12-04 17:43:04.933 29324 29505 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
12-04 18:03:19.799  7213  7279 E SQLiteLog: (283) recovered 40 frames from WAL file /data/user/0/eu.kanade.tachiyomi/databases/tachiyomi.db-wal
12-04 18:03:20.080  7213  7423 E SQLiteLog: (284) automatic index on C(manga_id)
12-04 18:03:20.080  7213  7423 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
12-04 18:03:52.386  7213  7213 E DecorView[]: Destroying unexpected ActionMode instance of TYPE_FLOATING; com.android.internal.view.FloatingActionMode@117c9c5 was not the current floating action mode! Expected null
12-04 18:03:58.562  7213  8522 E BufferQueueProducer: [ImageReader-1x1f23u256m2-7213-0](id:1c2d00000006,api:3,p:7213,c:7213) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:03:58.706  7213  8522 E BufferQueueProducer: [ImageReader-1x1f23u256m2-7213-0](id:1c2d00000006,api:3,p:7213,c:7213) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:03:59.084  7213  8522 E BufferQueueProducer: [ImageReader-1x1f23u256m2-7213-0](id:1c2d00000006,api:3,p:7213,c:7213) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:03:59.228  7213  8522 E BufferQueueProducer: [ImageReader-1x1f23u256m2-7213-0](id:1c2d00000006,api:3,p:7213,c:7213) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:03:59.376  7213  8522 E BufferQueueProducer: [ImageReader-1x1f23u256m2-7213-0](id:1c2d00000006,api:3,p:7213,c:7213) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:03:59.520  7213  8522 E BufferQueueProducer: [ImageReader-1x1f23u256m2-7213-0](id:1c2d00000006,api:3,p:7213,c:7213) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:03:59.669  7213  8522 E BufferQueueProducer: [ImageReader-1x1f23u256m2-7213-0](id:1c2d00000006,api:3,p:7213,c:7213) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:03:59.826  7213  8522 E BufferQueueProducer: [ImageReader-1x1f23u256m2-7213-0](id:1c2d00000006,api:3,p:7213,c:7213) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:03:59.837  7213  8522 E BufferQueueProducer: [ImageReader-1x1f23u256m2-7213-0](id:1c2d00000006,api:3,p:7213,c:7213) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:03:59.981  7213  8522 E BufferQueueProducer: [ImageReader-1x1f23u256m2-7213-0](id:1c2d00000006,api:3,p:7213,c:7213) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:04:00.128  7213  8522 E BufferQueueProducer: [ImageReader-1x1f23u256m2-7213-0](id:1c2d00000006,api:3,p:7213,c:7213) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:04:00.272  7213  8522 E BufferQueueProducer: [ImageReader-1x1f23u256m2-7213-0](id:1c2d00000006,api:3,p:7213,c:7213) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:04:49.737  7213  7213 E DecorView[]: Destroying unexpected ActionMode instance of TYPE_FLOATING; com.android.internal.view.FloatingActionMode@840e6cc was not the current floating action mode! Expected null
12-04 18:04:56.378  7213  7281 E CursorWindow: Failed to read row 714, column 0 from a CursorWindow which has 714 rows, 26 columns.
12-04 18:04:56.391  7213  7497 E ACRA    : ACRA caught a NullPointerException for eu.kanade.tachiyomi
12-04 18:04:56.391  7213  7497 E ACRA    : java.lang.NullPointerException
12-04 18:04:56.391  7213  7497 E ACRA    : 	at tachiyomi.data.data.LibraryViewQueriesImpl$library$1.invoke(DatabaseImpl.kt:17)
12-04 18:04:56.391  7213  7497 E ACRA    : 	at com.squareup.sqldelight.Query.executeAsList(Query.kt:18)
12-04 18:04:56.391  7213  7497 E ACRA    : 	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToList$1$1.invokeSuspend(FlowExtensions.kt:6)
12-04 18:04:56.391  7213  7497 E ACRA    : 	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToList$1$1.invoke(FlowExtensions.kt:13)
12-04 18:04:56.391  7213  7497 E ACRA    : 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:8)
12-04 18:04:56.391  7213  7497 E ACRA    : 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:50)
12-04 18:04:56.391  7213  7497 E ACRA    : 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
12-04 18:04:56.391  7213  7497 E ACRA    : 	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToList$$inlined$map$1$2.emit(Collect.kt:76)
12-04 18:04:56.391  7213  7497 E ACRA    : 	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:2)
12-04 18:04:56.391  7213  7497 E ACRA    : 	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:18)
12-04 18:04:56.391  7213  7497 E ACRA    : 	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:1)
12-04 18:04:56.391  7213  7497 E ACRA    : 	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$asFlow$1.invokeSuspend(FlowExtensions.kt:120)
12-04 18:04:56.391  7213  7497 E ACRA    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
12-04 18:04:56.391  7213  7497 E ACRA    : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
12-04 18:04:56.391  7213  7497 E ACRA    : 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
12-04 18:04:56.391  7213  7497 E ACRA    : 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
12-04 18:04:56.391  7213  7497 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
12-04 18:04:56.391  7213  7497 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:63)
12-04 18:04:56.391  7213  7497 E ACRA    : 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [CoroutineName(eu.kanade.tachiyomi.ui.library.LibraryTab:eu.kanade.tachiyomi.ui.library.LibraryScreenModel:default:ScreenModelCoroutineScope), StandaloneCoroutine{Cancelling}@cfd29ae, Dispatchers.IO]
12-04 18:04:57.220 10362 10397 E SQLiteLog: (283) recovered 21 frames from WAL file /data/user/0/eu.kanade.tachiyomi/databases/tachiyomi.db-wal
12-04 18:04:58.845 10567 10606 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
12-04 18:04:59.127 10567 10730 E SQLiteLog: (284) automatic index on C(manga_id)
12-04 18:04:59.162 10567 10730 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
12-04 18:05:20.118 10567 10567 E DecorView[]: Destroying unexpected ActionMode instance of TYPE_FLOATING; com.android.internal.view.FloatingActionMode@4c9b211 was not the current floating action mode! Expected null
12-04 18:05:35.343 10567 10567 E DecorView[]: Destroying unexpected ActionMode instance of TYPE_FLOATING; com.android.internal.view.FloatingActionMode@6432360 was not the current floating action mode! Expected null
12-04 18:09:26.292 10567 10567 E DecorView[]: Destroying unexpected ActionMode instance of TYPE_FLOATING; com.android.internal.view.FloatingActionMode@6eed1f1 was not the current floating action mode! Expected null
12-04 18:11:14.085 10567 17985 E BufferQueueProducer: [ImageReader-1x1f23u256m2-10567-0](id:294700000015,api:3,p:10567,c:10567) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:11:14.229 10567 17985 E BufferQueueProducer: [ImageReader-1x1f23u256m2-10567-0](id:294700000015,api:3,p:10567,c:10567) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:11:14.373 10567 17985 E BufferQueueProducer: [ImageReader-1x1f23u256m2-10567-0](id:294700000015,api:3,p:10567,c:10567) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:11:14.517 10567 17985 E BufferQueueProducer: [ImageReader-1x1f23u256m2-10567-0](id:294700000015,api:3,p:10567,c:10567) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:11:14.661 10567 17985 E BufferQueueProducer: [ImageReader-1x1f23u256m2-10567-0](id:294700000015,api:3,p:10567,c:10567) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:11:14.805 10567 17985 E BufferQueueProducer: [ImageReader-1x1f23u256m2-10567-0](id:294700000015,api:3,p:10567,c:10567) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:11:14.949 10567 17985 E BufferQueueProducer: [ImageReader-1x1f23u256m2-10567-0](id:294700000015,api:3,p:10567,c:10567) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:11:15.093 10567 17985 E BufferQueueProducer: [ImageReader-1x1f23u256m2-10567-0](id:294700000015,api:3,p:10567,c:10567) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:11:15.237 10567 17985 E BufferQueueProducer: [ImageReader-1x1f23u256m2-10567-0](id:294700000015,api:3,p:10567,c:10567) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:11:15.381 10567 17985 E BufferQueueProducer: [ImageReader-1x1f23u256m2-10567-0](id:294700000015,api:3,p:10567,c:10567) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:11:15.525 10567 17985 E BufferQueueProducer: [ImageReader-1x1f23u256m2-10567-0](id:294700000015,api:3,p:10567,c:10567) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:11:15.669 10567 17985 E BufferQueueProducer: [ImageReader-1x1f23u256m2-10567-0](id:294700000015,api:3,p:10567,c:10567) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:11:15.813 10567 17985 E BufferQueueProducer: [ImageReader-1x1f23u256m2-10567-0](id:294700000015,api:3,p:10567,c:10567) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:11:15.957 10567 17985 E BufferQueueProducer: [ImageReader-1x1f23u256m2-10567-0](id:294700000015,api:3,p:10567,c:10567) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:11:18.346 10567 11089 E chromium: [ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -101
12-04 18:11:23.350 10567 11089 E chromium: [ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -101
12-04 18:14:47.178 10567 17985 E BufferQueueProducer: [ImageReader-1x1f23u256m2-10567-4](id:294700000021,api:3,p:10567,c:10567) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:14:47.189 10567 17985 E BufferQueueProducer: [ImageReader-1x1f23u256m2-10567-4](id:294700000021,api:3,p:10567,c:10567) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:14:47.333 10567 17985 E BufferQueueProducer: [ImageReader-1x1f23u256m2-10567-4](id:294700000021,api:3,p:10567,c:10567) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:14:47.701 10567 17985 E BufferQueueProducer: [ImageReader-1x1f23u256m2-10567-4](id:294700000021,api:3,p:10567,c:10567) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:14:47.711 10567 17985 E BufferQueueProducer: [ImageReader-1x1f23u256m2-10567-4](id:294700000021,api:3,p:10567,c:10567) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:14:47.856 10567 17985 E BufferQueueProducer: [ImageReader-1x1f23u256m2-10567-4](id:294700000021,api:3,p:10567,c:10567) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:14:48.006 10567 17985 E BufferQueueProducer: [ImageReader-1x1f23u256m2-10567-4](id:294700000021,api:3,p:10567,c:10567) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:14:48.151 10567 17985 E BufferQueueProducer: [ImageReader-1x1f23u256m2-10567-4](id:294700000021,api:3,p:10567,c:10567) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:14:48.298 10567 17985 E BufferQueueProducer: [ImageReader-1x1f23u256m2-10567-4](id:294700000021,api:3,p:10567,c:10567) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:14:48.695 10567 17985 E BufferQueueProducer: [ImageReader-1x1f23u256m2-10567-4](id:294700000021,api:3,p:10567,c:10567) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:14:48.706 10567 17985 E BufferQueueProducer: [ImageReader-1x1f23u256m2-10567-4](id:294700000021,api:3,p:10567,c:10567) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:14:48.851 10567 17985 E BufferQueueProducer: [ImageReader-1x1f23u256m2-10567-4](id:294700000021,api:3,p:10567,c:10567) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:14:49.000 10567 17985 E BufferQueueProducer: [ImageReader-1x1f23u256m2-10567-4](id:294700000021,api:3,p:10567,c:10567) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:14:49.144 10567 17985 E BufferQueueProducer: [ImageReader-1x1f23u256m2-10567-4](id:294700000021,api:3,p:10567,c:10567) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:14:51.191 10567 11089 E chromium: [ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -101
12-04 18:14:56.196 10567 11089 E chromium: [ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -101
12-04 18:22:47.933 28906 28949 E SQLiteLog: (283) recovered 187 frames from WAL file /data/user/0/eu.kanade.tachiyomi/databases/tachiyomi.db-wal
12-04 18:22:48.271 28906 29053 E SQLiteLog: (284) automatic index on C(manga_id)
12-04 18:22:48.271 28906 29053 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
12-04 18:22:51.174 28906 29145 E chromium: [ERROR:simple_index_file_posix.cc(61)] Could not get file info for /data/user/0/eu.kanade.tachiyomi/cache/WebView/Default/HTTP Cache/Code Cache/js/d3ad7fbedee5b66c_0
12-04 18:22:51.174 28906 29145 E chromium: [ERROR:simple_index_file_posix.cc(61)] Could not get file info for /data/user/0/eu.kanade.tachiyomi/cache/WebView/Default/HTTP Cache/Code Cache/js/30c85d9bf67354c4_0
12-04 18:22:51.174 28906 29145 E chromium: [ERROR:simple_index_file_posix.cc(61)] Could not get file info for /data/user/0/eu.kanade.tachiyomi/cache/WebView/Default/HTTP Cache/Code Cache/js/dc3e162088949b03_0
12-04 18:22:51.174 28906 29145 E chromium: [ERROR:simple_index_file_posix.cc(61)] Could not get file info for /data/user/0/eu.kanade.tachiyomi/cache/WebView/Default/HTTP Cache/Code Cache/js/82720183f6485926_0
12-04 18:22:51.174 28906 29145 E chromium: [ERROR:simple_index_file_posix.cc(61)] Could not get file info for /data/user/0/eu.kanade.tachiyomi/cache/WebView/Default/HTTP Cache/Code Cache/js/cb5b3ce60793dd72_0
12-04 18:22:51.174 28906 29145 E chromium: [ERROR:simple_index_file_posix.cc(61)] Could not get file info for /data/user/0/eu.kanade.tachiyomi/cache/WebView/Default/HTTP Cache/Code Cache/js/c61bc4dec4eb00fa_0
12-04 18:22:51.174 28906 29145 E chromium: [ERROR:simple_index_file_posix.cc(61)] Could not get file info for /data/user/0/eu.kanade.tachiyomi/cache/WebView/Default/HTTP Cache/Code Cache/js/7ce9551ad84f7204_0
12-04 18:22:51.174 28906 29145 E chromium: [ERROR:simple_index_file_posix.cc(61)] Could not get file info for /data/user/0/eu.kanade.tachiyomi/cache/WebView/Default/HTTP Cache/Code Cache/js/dfa3110e6c5ca78c_0
12-04 18:22:51.174 28906 29145 E chromium: [ERROR:simple_index_file_posix.cc(61)] Could not get file info for /data/user/0/eu.kanade.tachiyomi/cache/WebView/Default/HTTP Cache/Code Cache/js/dfeb42ef8be67856_0
12-04 18:22:51.174 28906 29145 E chromium: [ERROR:simple_index_file_posix.cc(61)] Could not get file info for /data/user/0/eu.kanade.tachiyomi/cache/WebView/Default/HTTP Cache/Code Cache/js/60b2e4e8b3a94c3e_0
12-04 18:22:51.174 28906 29145 E chromium: [ERROR:simple_index_file_posix.cc(61)] Could not get file info for /data/user/0/eu.kanade.tachiyomi/cache/WebView/Default/HTTP Cache/Code Cache/js/fdc40ad6021cbd2a_0
12-04 18:22:51.174 28906 29145 E chromium: [ERROR:simple_index_file_posix.cc(61)] Could not get file info for /data/user/0/eu.kanade.tachiyomi/cache/WebView/Default/HTTP Cache/Code Cache/js/bd8fb63cebaec297_0
12-04 18:22:51.174 28906 29145 E chromium: [ERROR:simple_index_file_posix.cc(61)] Could not get file info for /data/user/0/eu.kanade.tachiyomi/cache/WebView/Default/HTTP Cache/Code Cache/js/18619c97321295b8_0
12-04 18:22:51.174 28906 29145 E chromium: [ERROR:simple_index_file_posix.cc(61)] Could not get file info for /data/user/0/eu.kanade.tachiyomi/cache/WebView/Default/HTTP Cache/Code Cache/js/c8c68e6c2e47e20c_0
12-04 18:22:51.174 28906 29145 E chromium: [ERROR:simple_index_file_posix.cc(61)] Could not get file info for /data/user/0/eu.kanade.tachiyomi/cache/WebView/Default/HTTP Cache/Code Cache/js/2ddafd371228d4ea_0
12-04 18:22:51.174 28906 29145 E chromium: [ERROR:simple_index_file_posix.cc(61)] Could not get file info for /data/user/0/eu.kanade.tachiyomi/cache/WebView/Default/HTTP Cache/Code Cache/js/280062e42de5eca7_0
12-04 18:22:59.394 28906 29886 E BufferQueueProducer: [ImageReader-1x1f23u256m2-28906-2](id:70ea00000004,api:3,p:28906,c:28906) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:22:59.405 28906 29886 E BufferQueueProducer: [ImageReader-1x1f23u256m2-28906-2](id:70ea00000004,api:3,p:28906,c:28906) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:22:59.548 28906 29886 E BufferQueueProducer: [ImageReader-1x1f23u256m2-28906-2](id:70ea00000004,api:3,p:28906,c:28906) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:22:59.692 28906 29886 E BufferQueueProducer: [ImageReader-1x1f23u256m2-28906-2](id:70ea00000004,api:3,p:28906,c:28906) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:22:59.835 28906 29886 E BufferQueueProducer: [ImageReader-1x1f23u256m2-28906-2](id:70ea00000004,api:3,p:28906,c:28906) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:22:59.979 28906 29886 E BufferQueueProducer: [ImageReader-1x1f23u256m2-28906-2](id:70ea00000004,api:3,p:28906,c:28906) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:23:00.125 28906 29886 E BufferQueueProducer: [ImageReader-1x1f23u256m2-28906-2](id:70ea00000004,api:3,p:28906,c:28906) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:23:00.269 28906 29886 E BufferQueueProducer: [ImageReader-1x1f23u256m2-28906-2](id:70ea00000004,api:3,p:28906,c:28906) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:23:00.413 28906 29886 E BufferQueueProducer: [ImageReader-1x1f23u256m2-28906-2](id:70ea00000004,api:3,p:28906,c:28906) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:23:00.557 28906 29886 E BufferQueueProducer: [ImageReader-1x1f23u256m2-28906-2](id:70ea00000004,api:3,p:28906,c:28906) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:23:00.701 28906 29886 E BufferQueueProducer: [ImageReader-1x1f23u256m2-28906-2](id:70ea00000004,api:3,p:28906,c:28906) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:23:00.845 28906 29886 E BufferQueueProducer: [ImageReader-1x1f23u256m2-28906-2](id:70ea00000004,api:3,p:28906,c:28906) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:23:00.990 28906 29886 E BufferQueueProducer: [ImageReader-1x1f23u256m2-28906-2](id:70ea00000004,api:3,p:28906,c:28906) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:23:01.134 28906 29886 E BufferQueueProducer: [ImageReader-1x1f23u256m2-28906-2](id:70ea00000004,api:3,p:28906,c:28906) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:23:01.278 28906 29886 E BufferQueueProducer: [ImageReader-1x1f23u256m2-28906-2](id:70ea00000004,api:3,p:28906,c:28906) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:23:04.341 28906 29886 E BufferQueueProducer: [ImageReader-1x1f23u256m2-28906-3](id:70ea00000008,api:3,p:28906,c:28906) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:23:04.351 28906 29886 E BufferQueueProducer: [ImageReader-1x1f23u256m2-28906-3](id:70ea00000008,api:3,p:28906,c:28906) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:23:04.495 28906 29886 E BufferQueueProducer: [ImageReader-1x1f23u256m2-28906-3](id:70ea00000008,api:3,p:28906,c:28906) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:23:04.642 28906 29886 E BufferQueueProducer: [ImageReader-1x1f23u256m2-28906-3](id:70ea00000008,api:3,p:28906,c:28906) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:23:04.785 28906 29886 E BufferQueueProducer: [ImageReader-1x1f23u256m2-28906-3](id:70ea00000008,api:3,p:28906,c:28906) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:23:04.933 28906 29886 E BufferQueueProducer: [ImageReader-1x1f23u256m2-28906-3](id:70ea00000008,api:3,p:28906,c:28906) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:23:05.591 28906 29886 E BufferQueueProducer: [ImageReader-1x1f23u256m2-28906-3](id:70ea00000008,api:3,p:28906,c:28906) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:23:05.734 28906 29886 E BufferQueueProducer: [ImageReader-1x1f23u256m2-28906-3](id:70ea00000008,api:3,p:28906,c:28906) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:23:05.881 28906 29886 E BufferQueueProducer: [ImageReader-1x1f23u256m2-28906-3](id:70ea00000008,api:3,p:28906,c:28906) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:23:06.025 28906 29886 E BufferQueueProducer: [ImageReader-1x1f23u256m2-28906-3](id:70ea00000008,api:3,p:28906,c:28906) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:23:06.338 28906 29886 E BufferQueueProducer: [ImageReader-1x1f23u256m2-28906-3](id:70ea00000008,api:3,p:28906,c:28906) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:23:06.349 28906 29886 E BufferQueueProducer: [ImageReader-1x1f23u256m2-28906-3](id:70ea00000008,api:3,p:28906,c:28906) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:23:06.493 28906 29886 E BufferQueueProducer: [ImageReader-1x1f23u256m2-28906-3](id:70ea00000008,api:3,p:28906,c:28906) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:23:06.640 28906 29886 E BufferQueueProducer: [ImageReader-1x1f23u256m2-28906-3](id:70ea00000008,api:3,p:28906,c:28906) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:23:06.784 28906 29886 E BufferQueueProducer: [ImageReader-1x1f23u256m2-28906-3](id:70ea00000008,api:3,p:28906,c:28906) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:23:06.932 28906 29886 E BufferQueueProducer: [ImageReader-1x1f23u256m2-28906-3](id:70ea00000008,api:3,p:28906,c:28906) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:23:07.076 28906 29886 E BufferQueueProducer: [ImageReader-1x1f23u256m2-28906-3](id:70ea00000008,api:3,p:28906,c:28906) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:23:07.090 28906 29886 E BufferQueueProducer: [ImageReader-1x1f23u256m2-28906-3](id:70ea00000008,api:3,p:28906,c:28906) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:23:07.235 28906 29886 E BufferQueueProducer: [ImageReader-1x1f23u256m2-28906-3](id:70ea00000008,api:3,p:28906,c:28906) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:23:07.384 28906 29886 E BufferQueueProducer: [ImageReader-1x1f23u256m2-28906-3](id:70ea00000008,api:3,p:28906,c:28906) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:23:07.528 28906 29886 E BufferQueueProducer: [ImageReader-1x1f23u256m2-28906-3](id:70ea00000008,api:3,p:28906,c:28906) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:23:07.674 28906 29886 E BufferQueueProducer: [ImageReader-1x1f23u256m2-28906-3](id:70ea00000008,api:3,p:28906,c:28906) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:23:07.817 28906 29886 E BufferQueueProducer: [ImageReader-1x1f23u256m2-28906-3](id:70ea00000008,api:3,p:28906,c:28906) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:23:07.966 28906 29886 E BufferQueueProducer: [ImageReader-1x1f23u256m2-28906-3](id:70ea00000008,api:3,p:28906,c:28906) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:23:08.113 28906 29886 E BufferQueueProducer: [ImageReader-1x1f23u256m2-28906-3](id:70ea00000008,api:3,p:28906,c:28906) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:23:08.258 28906 29886 E BufferQueueProducer: [ImageReader-1x1f23u256m2-28906-3](id:70ea00000008,api:3,p:28906,c:28906) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:23:08.604 28906 29886 E BufferQueueProducer: [ImageReader-1x1f23u256m2-28906-3](id:70ea00000008,api:3,p:28906,c:28906) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:23:08.614 28906 29886 E BufferQueueProducer: [ImageReader-1x1f23u256m2-28906-3](id:70ea00000008,api:3,p:28906,c:28906) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:23:08.758 28906 29886 E BufferQueueProducer: [ImageReader-1x1f23u256m2-28906-3](id:70ea00000008,api:3,p:28906,c:28906) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:23:08.909 28906 29886 E BufferQueueProducer: [ImageReader-1x1f23u256m2-28906-3](id:70ea00000008,api:3,p:28906,c:28906) dequeueBuffer: waitForFreeSlotThenRelock error -38
12-04 18:23:09.054 28906 29886 E BufferQueueProducer: [ImageReader-1x1f23u256m2-28906-3](id:70ea00000008,api:3,p:28906,c:28906) dequeueBuffer: waitForFreeSlotThenRelock error -38
App version: 0.14.7 (standard, c8d6859, 102, 2023-10-25T16:11Z)
Android version: 13 (SDK 33)
Android build ID: TP1A.220624.014 release-keys
Device brand: vivo
Device manufacturer: vivo
Device name: PD2243
Device model: V2243A
Device product name: PD2243

### Tachiyomi version

0.14.7

### Android version

Android 13

### Device

IQOO 11

### Other details

The reason is my guess, because I tried to create a folder with the corresponding name in the system but failed.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-12-05 03:24
Duplicate of #8874

**Closed by arkon** 2023-12-05 03:24 UTC
Labels: Bug
