### ISSUE TITLE
[Zoom/Width Lock] <Basically adds a lock when zooming manga/webtoon like when reading in online manga websites>

### ISSUE THREAD

**Issue by mish20011** [tachiyomiorg/tachiyomi#4528] opened 2021-02-22 12:04 UTC
---

## Why/User Benefit/User Problem
(It makes webtoons with small text/panels easier to swipe and read rather than crop borders because it ruins some of the panels making some zoom and making the images unbalanced in size)

## What/Requirements
(This feature is added in reader settings in webtoon since it is vertical can reading so you can read with ease)

**Comment by arkon** [comment] 2021-02-22 13:23
Duplicate of #1822

**Closed by arkon** 2021-02-22 13:23 UTC
Labels: feature
