### ISSUE TITLE
Zoom out / saved reading mode

### ISSUE THREAD

**Issue by llreizh** [tachiyomiorg/tachiyomi#7239] opened 2022-06-01 12:35 UTC
### Describe your suggested feature

I usually read in landscape + original size.  
The problem is when there 2 spread page, where I picture exceed phone display. This is where zoom out feature come handy.
Another is webtoon, where I need fir width + forced potrait. With saved reading mode for each manga make easier.
Thank you, sorry for broken english

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-06-26 02:24
Duplicate of #3348

**Closed by arkon** 2022-06-26 02:24 UTC
Labels: Feature request
