### ISSUE TITLE
Update categories on multiple categories simultaneously without removing existing categories

### ISSUE THREAD

**Issue by Efreak** [tachiyomiorg/tachiyomi#2169] opened 2019-08-06 18:09 UTC
**App version:**
0.8.4, r1519

**Android version:**
Pie, Oreo

**Issue/Request:**
Retain existing categories when categorizing multiple items. Perhaps use a three-state check box to show if part of the selection includes a category.

**Steps to reproduce (if applicable)**

 1. Select multiple items with differing categories (ie, one is in fantasy and one is in sf)
 2. Add categories (ie drama)
 3. Original categories are lost

**Other details:**
My library has grown over time, and checking for updates now takes too long. I'm in the process of adding items to an auto-update category to speed it up, however each item has to be added individually to prevent losing existing categories. If Tachiyomi could update categories instead of replacing them, I could simply add them all at once.

**Comment by hXtreme** [comment] 2019-08-06 18:32
In the mean time to improve update speed, goto General Settings and set Library Update Order to Last Updated.

**Comment by arkon** [comment] 2021-04-12 22:10
Duplicate of #961

**Closed by arkon** 2021-04-12 22:10 UTC
Labels: feature
