### ISSUE TITLE
Webtoon view load slow while other view load faster

### ISSUE THREAD

**Issue by amirulfaiz98** [tachiyomiorg/tachiyomi#7072] opened 2022-05-03 21:29 UTC
### Steps to reproduce

Webtoon view for reading mode 

### Expected behavior

It should load smoothly between page

### Actual behavior

Load for more then 2 minutes. Sometimes still loading after exit and open the app back

### Tachiyomi version

0.13.4

### Android version

Android 10

### Device

Samsung Galaxy J6+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by saud-97** [comment] 2022-05-04 02:05
Can you share the source and manga/chapter details. I suspect this is caused by long-strip webtoon images where they are too long for tachiyomi to handle. This is a known issue.

**Comment by amirulfaiz98** [comment] 2022-05-06 18:24
manhwa18.com & manhwa18.net.

**Comment by amirulfaiz98** [comment] 2022-05-06 18:25
Yeah it is a long-strip webtoon image

**Comment by saud-97** [comment] 2022-05-07 10:09
Then this would be fixed soon by adding a new option to auto split downloaded images. #7029

**Comment by arkon** [comment] 2022-05-07 12:42
Duplicate of #1908

**Closed by arkon** 2022-05-07 12:42 UTC
Labels: Bug
