### ISSUE TITLE
Add ability to filter installed extension and read/unread on updates tab

### ISSUE THREAD

**Issue by tsunaliew** [tachiyomiorg/tachiyomi#6872] opened 2022-04-06 19:29 UTC
### Describe your suggested feature

Example:
1. The Updates tab has the ability to filter manga updates by installed extension
2. The Updates tab has a read/unread filter, similar to [#4047](https://github.com/tachiyomiorg/tachiyomi/issues/4047)

### Other details

Users that read manga in many languages, such as myself, would benefit from the ability to filter manga that belongs to the installed extensions.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-04-08 20:12
1. I don't understand the point of this. If you need to figure out what items belong to sources that aren't installed, use the migrate menu.
2. Duplicate of #6622

**Closed by arkon** 2022-04-08 20:12 UTC
Labels: Feature request

**Comment by tsunaliew** [comment] 2022-04-08 22:04
No, point 1 is only to filter installed extensions, never mentioned anything about un-installed extensions.
