### ISSUE TITLE
"Now the cover can be changed, it is suggested that the name can also be changed."

### ISSUE THREAD

**Issue by 610364023** [tachiyomiorg/tachiyomi#9221] opened 2023-03-17 06:05 UTC
### Describe your suggested feature

"Now the cover can be changed, it is suggested that the name can also be changed."

Mechanical turnover

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment] 2023-03-17 06:44
Duplicate of #4398

**Closed by loocool2** 2023-03-17 06:44 UTC
Labels: Feature request
