### ISSUE TITLE
[Feature Request] <For Library, Chapter List, Download Queue, Extensions>

### ISSUE THREAD

**Issue by NevGi-cpu** [tachiyomiorg/tachiyomi#4730] opened 2021-03-28 12:11 UTC
Feature Needed:
1. Better Multi-Select feature than the one we currently have(For All Sections)
The current multi-select feature doesn't allow to skip over few manga/chapter during selection. So adding checkboxes would solve the problem. Having this feature in Extension would allow us download and install/uninstall multiple extensions at once. Similarly, having this extension in dowload queue will allow us to remove multiple chapters from the  downloading queue at once rather than doing it one by once in both extension and download queue cases.

2. Search Feature(For Download Queue & Extension)
Having search feature in download queue would help us to filter a manga from others in the queue if the chapters were scrambled with one another so that again i can remove them form the queue. And I know that there is a search feature for extension section which is used to search manga throughout the installed extensions but i would like to add a search feature to filter the extensions by name so we wont have to scroll through looking for the extension we want to browser or install/uninstall from the huge list of extensions provided by taichiyomi

Hope it makes sense to the users reading it.

**Comment by scb261** [comment] 2021-03-28 12:37
1.1. Checkboxes will only change one chapter selection (right now it's long tap, but with checkbox it would be single tap). After selecting one chapter everything will still be the same, i.e. single tap to select/unselect one chapter and long tap to range select. So I don't see any point of them.
1.2. Select multiple extensions for install/uninstall - I'll leave this up to maintainers.
1.3. Select chapters in download queue - duplicate of #2860 and #3688.

2.1. Search in download queue - also up to maintainers.
2.2. `And I know that there is a search feature for extension section` and `add a search feature to filter the extensions by name so we wont have to scroll through looking for the extension we want [...] from the huge list of extensions provided by taichiyomi` - not sure what you mean.

Next time open separate issue for each request.

**Comment by arkon** [comment] 2021-03-28 15:02
To expand on the above:

1.1: I'm not sure how checkmarks fix your issue. Create a separate issue if we're misunderstanding. Do note there's already long-press shortcuts to select ranges of items in some views.
1.2: Not possible, app (un)installations always require user interaction.

2.1: Create a separate issue.
2.2: The search functionality in the tabs are different; you can already search the extensions list.

**Closed by arkon** 2021-03-28 15:02 UTC
Labels: feature
