### ISSUE TITLE
Incognito mode per series & Bookmark tab

### ISSUE THREAD

**Issue by arichua** [tachiyomiorg/tachiyomi#6575] opened 2022-02-05 12:14 UTC
### Describe your suggested feature

1. Incognito - when you're browsing/reading Chapter
, wish there's an incognito option in the settings (For this series> reading mode) so you don't need to leave the manga you are reading and go to 'MORE'  just to on the incognito option
![Screenshot_2022-02-05-20-10-54-732_eu kanade tachiyomi](https://user-images.githubusercontent.com/96766003/152641571-68e9e0fd-43c5-4fd4-955f-4f3164dcb6b6.jpg)

2. Bookmark tab- Wish there's just a tab where you can view all your bookmarked chapters from different manga

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CVIUS** [comment] 2022-02-05 19:07
Only one feature request per issue. Also, your 2nd suggestion is a duplicate of #5046

**Comment by alessandrojean** [comment] 2022-02-05 19:09
Please open a new issue regarding only the first request.

**Closed by alessandrojean** 2022-02-05 19:09 UTC
Labels: Feature request
