### ISSUE TITLE
[Bug] <Crashes once a download is started>

### ISSUE THREAD

**Issue by Wrath1412221** [tachiyomiorg/tachiyomi#5208] opened 2021-05-26 22:41 UTC
## Device information
* Tachiyomi version: 0.10.12
* Android version: 7
* Device: Samsung galaxy A7 (2016)
Steps to reproduce

## Steps to reproduce
1. Start Download and wait or start then stop download for it to happen instantly

### Expected behavior
it should download.

### Actual behavior
it crashes.

## Other details
Note: It worked for a couple days before this started happening

--------- beginning of main
05-26 16:52:00.999 27014 29939 E ConnectivityManager.CallbackHandler: callback not found for RELEASED message
05-26 16:52:01.928 27014 29941 E ACRA : ACRA caught a IllegalStateException for eu.kanade.tachiyomi
05-26 16:52:01.928 27014 29941 E ACRA : java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add onError handling.
05-26 16:52:01.928 27014 29941 E ACRA : at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:57)
05-26 16:52:01.928 27014 29941 E ACRA : at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
05-26 16:52:01.928 27014 29941 E ACRA : at java.util.concurrent.FutureTask.run(FutureTask.java:237)
05-26 16:52:01.928 27014 29941 E ACRA : at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
05-26 16:52:01.928 27014 29941 E ACRA : at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
05-26 16:52:01.928 27014 29941 E ACRA : at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
05-26 16:52:01.928 27014 29941 E ACRA : at java.lang.Thread.run(Thread.java:762)
05-26 16:52:01.928 27014 29941 E ACRA : Caused by: rx.exceptions.OnErrorNotImplementedException: interrupted
05-26 16:52:01.928 27014 29941 E ACRA : at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386)
05-26 16:52:01.928 27014 29941 E ACRA : at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383)
05-26 16:52:01.928 27014 29941 E ACRA : at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
05-26 16:52:01.928 27014 29941 E ACRA : at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:153)
05-26 16:52:01.928 27014 29941 E ACRA : at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
05-26 16:52:01.928 27014 29941 E ACRA : at rx.internal.operators.OnSubscribeMap$MapSubscriber.onError(OnSubscribeMap.java:88)
05-26 16:52:01.928 27014 29941 E ACRA : at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
05-26 16:52:01.928 27014 29941 E ACRA : at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1$requestArbiter$1.request(OkHttpExtensions.kt:43)
05-26 16:52:01.928 27014 29941 E ACRA : at rx.Subscriber.setProducer(Subscriber.java:209)
05-26 16:52:01.928 27014 29941 E ACRA : at rx.Subscriber.setProducer(Subscriber.java:205)
05-26 16:52:01.928 27014 29941 E ACRA : at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
05-26 16:52:01.928 27014 29941 E ACRA : at rx.Subscriber.setProducer(Subscriber.java:205)
05-26 16:52:01.928 27014 29941 E ACRA : at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1.call(OkHttpExtensions.kt:58)
05-26 16:52:01.928 27014 29941 E ACRA : at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1.call(OkHttpExtensions.kt:26)
05-26 16:52:01.928 27014 29941 E ACRA : at rx.Observable.unsafeSubscribe(Observable.java:10327)
05-26 16:52:01.928 27014 29941 E ACRA : at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
05-26 16:52:01.928 27014 29941 E ACRA : at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
05-26 16:52:01.928 27014 29941 E ACRA : at rx.Observable.unsafeSubscribe(Observable.java:10327)
05-26 16:52:01.928 27014 29941 E ACRA : at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
05-26 16:52:01.928 27014 29941 E ACRA : at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
05-26 16:52:01.928 27014 29941 E ACRA : at rx.Observable.subscribe(Observable.java:10423)
05-26 16:52:01.928 27014 29941 E ACRA : at rx.Observable.subscribe(Observable.java:10390)
05-26 16:52:01.928 27014 29941 E ACRA : at rx.Observable.subscribe(Observable.java:10195)
05-26 16:52:01.928 27014 29941 E ACRA : at eu.kanade.tachiyomi.multisrc.madara.Madara.fetchPageList(Madara.kt:616)
05-26 16:52:01.928 27014 29941 E ACRA : at eu.kanade.tachiyomi.data.download.Downloader$downloadChapter$1.call(Downloader.kt:285)
05-26 16:52:01.928 27014 29941 E ACRA : at eu.kanade.tachiyomi.data.download.Downloader$downloadChapter$1.call(Downloader.kt:49)
05-26 16:52:01.928 27014 29941 E ACRA : at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
05-26 16:52:01.928 27014 29941 E ACRA : at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
05-26 16:52:01.928 27014 29941 E ACRA : at rx.Observable.unsafeSubscribe(Observable.java:10327)
05-26 16:52:01.928 27014 29941 E ACRA : at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
05-26 16:52:01.928 27014 29941 E ACRA : at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
05-26 16:52:01.928 27014 29941 E ACRA : at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
05-26 16:52:01.928 27014 29941 E ACRA : ... 6 more
05-26 16:52:01.928 27014 29941 E ACRA : Caused by: java.io.InterruptedIOException: interrupted
05-26 16:52:01.928 27014 29941 E ACRA : at okio.Timeout.throwIfReached(Timeout.kt:98)
05-26 16:52:01.928 27014 29941 E ACRA : at okio.OutputStreamSink.write(JvmOkio.kt:53)
05-26 16:52:01.928 27014 29941 E ACRA : at okio.AsyncTimeout$sink$1.write(AsyncTimeout.kt:99)
05-26 16:52:01.928 27014 29941 E ACRA : at okio.RealBufferedSink.flush(RealBufferedSink.kt:267)
05-26 16:52:01.928 27014 29941 E ACRA : at okhttp3.internal.http2.Http2Writer.connectionPreface(Http2Writer.kt:62)
05-26 16:52:01.928 27014 29941 E ACRA : at okhttp3.internal.http2.Http2Connection.start(Http2Connection.kt:497)
05-26 16:52:01.928 27014 29941 E ACRA : at okhttp3.internal.http2.Http2Connection.start$default(Http2Connection.kt:495)
05-26 16:52:01.928 27014 29941 E ACRA : at okhttp3.internal.connection.RealConnection.startHttp2(RealConnection.kt:358)
05-26 16:52:01.928 27014 29941 E ACRA : at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:341)
05-26 16:52:01.928 27014 29941 E ACRA : at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
05-26 16:52:01.929 27014 29941 E ACRA : at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
05-26 16:52:01.929 27014 29941 E ACRA : at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
05-26 16:52:01.929 27014 29941 E ACRA : at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
05-26 16:52:01.929 27014 29941 E ACRA : at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
05-26 16:52:01.929 27014 29941 E ACRA : at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
05-26 16:52:01.929 27014 29941 E ACRA : at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
05-26 16:52:01.929 27014 29941 E ACRA : at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
05-26 16:52:01.929 27014 29941 E ACRA : at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
05-26 16:52:01.929 27014 29941 E ACRA : at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
05-26 16:52:01.929 27014 29941 E ACRA : at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
05-26 16:52:01.929 27014 29941 E ACRA : at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
05-26 16:52:01.929 27014 29941 E ACRA : at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
05-26 16:52:01.929 27014 29941 E ACRA : at eu.kanade.tachiyomi.network.CloudflareInterceptor.intercept(CloudflareInterceptor.kt:57)
05-26 16:52:01.929 27014 29941 E ACRA : at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
05-26 16:52:01.929 27014 29941 E ACRA : at eu.kanade.tachiyomi.network.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:19)
05-26 16:52:01.929 27014 29941 E ACRA : at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
05-26 16:52:01.929 27014 29941 E ACRA : at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
05-26 16:52:01.929 27014 29941 E ACRA : at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
05-26 16:52:01.929 27014 29941 E ACRA : at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1$requestArbiter$1.request(OkHttpExtensions.kt:36)
05-26 16:52:01.929 27014 29941 E ACRA : ... 30 more
05-26 16:52:04.635 30012 30012 E ResourceType: Style contains key with bad entry: 0x0101056c
05-26 16:52:05.906 30012 30050 E SQLiteLog: (284) automatic index on C(manga_id)
05-26 16:52:05.906 30012 30050 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
05-26 16:52:07.145 30012 30012 E BoostFramework: BoostFramework() : Exception_1 = java.lang.ClassNotFoundException: Didn't find class "com.qualcomm.qti.Performance" on path: DexPathList[[],nativeLibraryDirectories=[/system/lib, /vendor/lib]]
App version: 0.10.11 (standard, 0eb8d7d, 58)
Android version: 7.0 (SDK 24)
Android build ID: NRD90M.A710MUBS2CTJ1
Device brand: samsung
Device manufacturer: samsung
Device name: a7xelte
Device model: SM-A710M
Device product name: a7xelteub

**Comment by arkon** [comment] 2021-05-26 22:43
Duplicate of #5207.

**Closed by arkon** 2021-05-26 22:43 UTC
Labels: bug
