### ISSUE TITLE
Auto Update/Sync Trackers

### ISSUE THREAD

**Issue by jonsarz16** [tachiyomiorg/tachiyomi#8852] opened 2023-01-07 07:28 UTC
### Describe your suggested feature

1. Update Tracker 1
2. Automatically sync with other Trackers (if there is other tracker accounts logged in or detected.)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by lasersPew** [comment] 2023-01-07 08:04
Duplicate of #7479

**Closed** 2023-01-07 08:59 UTC
Labels: Feature request
