### ISSUE TITLE
Add "data saver" option like TachiyomiSy

### ISSUE THREAD

**Issue by Berserk0001** [tachiyomiorg/tachiyomi#10090] opened 2023-10-30 07:32 UTC
### Describe your suggested feature

Is it possible to add this option?..This feature is useful for sites with high quality images to lower the image quality for optimized reading performance..

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2023-10-30 10:45
Duplicate of #2021

**Closed by Seishirou101** 2023-10-30 10:45 UTC
Labels: Feature request
