### ISSUE TITLE
[Feature Request] <multiple migration>

### ISSUE THREAD

**Issue by kasakaka** [tachiyomiorg/tachiyomi#5385] opened 2021-06-12 04:13 UTC
---

## Why/User Benefit/User Problem
(Due to some recent changes some sources needed to migrate their library to the same extension giving some difficulties to users who have a large amount of collected mangas in their library by adding this feature not only it will make things easier. When some manga sites get taken down this will serve as a lifesaver for it can move many manga, source to another source)

## What/Requirements
(the migrate button will have a choice to migrate multiple mangas while on the final process of migrating it shows us how many chapters are there in both sources so we can confirm while also giving a choice to cancel basically just like tachiyomij2k migrate feature)

**Comment by Seishirou101** [comment] 2021-06-12 05:05
Duplicate of #1729

**Closed** 2021-06-12 05:06 UTC
Labels: feature
