### ISSUE TITLE
Volume tracking for Manga in Myanimelist And Anilist

### ISSUE THREAD

**Issue by NathPrashant** [tachiyomiorg/tachiyomi#9597] opened 2023-06-10 09:14 UTC
### Describe your suggested feature

Their are some site that provide manga in volume but we cann't then in manga form. So their should be a option while adding tracking to manga in which it ask the choice to be tracked from volume or chapter.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-06-12 02:13
Duplicate of #8143

**Closed by arkon** 2023-06-12 02:13 UTC
Labels: Feature request
