### ISSUE TITLE
[Feature Request] Auto backup on cloud

### ISSUE THREAD

**Issue by GianniTrattore** [tachiyomiorg/tachiyomi#5118] opened 2021-05-20 14:36 UTC
I think it would be useful to be able to backup automatically on google drive or other services, just like when creating manual backups.
The reason is that I use multiple devices and would like to have them all up to track when I use any one of them

**Comment by arkon** [comment] 2021-05-20 14:38
Duplicate of #912, sort of.

**Closed by arkon** 2021-05-20 14:38 UTC
