### ISSUE TITLE
[Bug] Lag when scrolling in the reader

### ISSUE THREAD

**Issue by westinn** [tachiyomiorg/tachiyomi#4454] opened 2021-02-11 20:14 UTC
## Device information
* Tachiyomi version: Stable 0.10.8
* Android version: Android 11, One UI 3.1
* Device: Samsung S21 Ultra

## Steps to reproduce
1. Open "Fatal Code" from the MangaDex source
2. Scroll from Chapter 2-Page 1 to Chapter 2-Page 3 and the delay appears on a portion of the screen with a black background and white text bubble.

### Expected behavior
Scrolling does not cause lag or lowering of refresh rate.

### Actual behavior
Lag is seen/introduced when a portion of the comic is on screen.
Either lag is introduced from the app - enough to reduce performance during scrolling, or the Samsung OS decides that while a specific portion of the comic is on screen, lowering the refresh rate of the screen is a good idea.

## Other details
I have turned on the dev option for adding the refresh rate to the screen, and it says it maintains at "120". So either that option describes what I have "set" the refresh rate to be (adaptive/120 vs the normal 60), or the phone is truly at 120Hz and the app has a performance issue.

Linked below are 2 screen recordings of the issue and a screenshot highlighting the portion the part of the comic that introduces the lag. The issue is more severe in person and the screen recording isn't that great at showing the stuttering.
https://photos.app.goo.gl/w2n8GqhZdwfQGUBd6

**Comment by ghostbear** [comment] 2021-02-11 20:18
Try turning off 32-bit color `More > Settings > Reader > Turn off 32-bit color`

**Comment by scb261** [comment] 2021-02-11 20:19
Duplicate of #1908

**Comment by arkon** [comment] 2021-02-11 20:19
The second page (which ends at the red circled part) is 1800px x 19478px.

**Comment by arkon** [comment] 2021-02-11 20:20
Duplicate of #1908

**Closed by arkon** 2021-02-11 20:20 UTC
Labels: bug

**Comment by westinn** [comment] 2021-02-11 20:22
> Try turning off 32-bit color `More > Settings > Reader > Turn off 32-bit color`

This worked! Forgot I had that setting on. Thanks!
