### ISSUE TITLE
No Cover for Locals

### ISSUE THREAD

**Issue by Satomar** [tachiyomiorg/tachiyomi#6003] opened 2021-10-01 15:31 UTC
### Steps to reproduce

there is no cover for local manga. Even though I added a photo named cover.  I also did edit the cover, but nothing appeared, it is just black

### Expected behavior

It should show the cover from the file, or update to the new cover I added

### Actual behavior

To show the cover

### Tachiyomi version

0.12.2

### Android version

Android 8

### Device

Samsung Galaxy S7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Nonamow** [comment] 2021-10-01 19:24
I have this problem. Sometimes all ok, but often it is not. It depends on the name. Just for imaginary e.g:
"name" - we can't see cover. And app doesn't generate cover. And "Even though I added a photo named cover." - yes. This is doesn't work too.
" name" - this one works fine.

**Comment by Satomar** [comment] 2021-10-01 19:33
But the name I add is for real manga such as Martial Peak, Tales of Demons and Gods, etc.

**Comment by Nonamow** [comment] 2021-10-01 19:42
And I am.

**Comment by arkon** [comment] 2021-10-01 22:23
Duplicate of #932

**Closed by arkon** 2021-10-01 22:23 UTC
Labels: Bug
