### ISSUE TITLE
Make chapter readable even if it's not fully downloaded 

### ISSUE THREAD

**Issue by InYoFace69** [tachiyomiorg/tachiyomi#7583] opened 2022-07-23 03:27 UTC
### Describe your suggested feature

Lately I have been getting issues while downloading chapters when suddenly the download stops because of a missing page(usually 1 or 2 page). Due to the missing pages , the download doesn't get completed and I can't even read it through the app  so I have to go through the trouble of reading it through opening it with either Photos or Gallery app. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-07-23 14:08
Duplicate of #3957

**Closed by arkon** 2022-07-23 14:08 UTC
Labels: Feature request
