### ISSUE TITLE
[Bug] Manga (chapters) not updating.

### ISSUE THREAD

**Issue by dhimanAdhikari** [tachiyomiorg/tachiyomi#4397] opened 2021-02-07 11:39 UTC
## Device information
* Tachiyomi version: r3085
* Android version: 10
* Device: Motorola G5 Plus

## Steps to reproduce
1. Update manga from global
2. Update manga individually

### Expected behavior
New chapters should appear

### Actual behavior
Nothing happening as if no new chapters. 

## Other details
Using MangaDex. WebView is working fine when opened from a particular manga (showing new chapters and can read them).
Was working just fine until 2 days ago. Nothing changed except for Tachiyomi update. Also tried re-installing the app and troubleshooting guide on website.

Tachiyomi page:
![1](https://user-images.githubusercontent.com/20817945/107145368-fd2b8300-6966-11eb-8781-22f929433db1.png)

WebView page:
![2](https://user-images.githubusercontent.com/20817945/107145371-fef54680-6966-11eb-9a8a-13861af107e0.png)

**Comment by scb261** [comment] 2021-02-07 12:26
Wrong repo and duplicate of https://github.com/tachiyomiorg/tachiyomi-extensions/issues/5627

**Closed** 2021-02-07 14:27 UTC
Labels: bug

**Comment by dhimanAdhikari** [comment] 2021-02-07 21:48
Just curious, would it fix by itself in a couple days or will it take time? Will I have to do something from my side?

**Comment by dhimanAdhikari** [comment] 2021-02-08 09:49
Just curious, will it fix by itself in a couple days (or more) or will I have to do something from my end?
