### ISSUE TITLE
Save filter combination as a "filter profile" for later use. 

### ISSUE THREAD

**Issue by MutennRoshii** [tachiyomiorg/tachiyomi#9655] opened 2023-07-01 00:14 UTC
### Describe your suggested feature

Example:
Let's say you're browsing the magalife extension and have some filters selected: action, comedy,... And maybe a publish status or sorting method selected.

With the feature there should be a button to save the current filter combination so next time you're looking for a Manga you don't have to remember what combination you used.

For simplicity it can be limited to one saved "filter profile" per extension. 

### Other details

Just save the selected options in a json file so it can be read easily. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2023-07-01 00:17
Duplicate of #1484

**Closed by Seishirou101** 2023-07-01 00:17 UTC
Labels: Feature request
