### ISSUE TITLE
Sort by random

### ISSUE THREAD

**Issue by Susuys** [tachiyomiorg/tachiyomi#6581] opened 2022-02-06 09:45 UTC
### Describe your suggested feature

It's can work like this

When you open library and click on sort there is option to sort by random 

### Other details

It's a really useful feature

I have a really big library and when ever I try to find something that i haven't read yet i have to scroll for a really long time

I think for people like me this feature will be really useful

So please add this feature as soon as possible 🥺

Thank you

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by SrW0nka** [comment] 2022-02-06 10:09
a button to chose a random manga looks cool, but just use categories to separate the ones you've read from the ones you haven't

**Comment by Riztard** [comment] 2022-02-06 10:30
> a button to choose a random manga looks cool, but just use categories to separate the ones you've read from the ones you haven't

yes... unless its not small in number. and even more in my case
<img width="300dp" src="https://user-images.githubusercontent.com/16263232/152676703-3865c726-7e19-49b9-89bf-aea797310039.png">

**Comment by arkon** [comment] 2022-02-06 13:17
Duplicate of #4648

#1248 would be more preferable.

**Closed by arkon** 2022-02-06 13:17 UTC
Labels: Feature request

**Comment by Riztard** [comment] 2022-02-06 13:40
> #1248 would be more preferable.

that opener would be only one by one, so shouldnt be count as duplicate, and i prefer sort :)

**Comment by azealyx** [comment] 2022-02-06 14:16
> that opener would be only one by one, so shouldnt be count as duplicate

there's actually a good reason that was discussed in that thread

![image](https://user-images.githubusercontent.com/95056079/152685116-31b86a27-dcd1-4754-be19-55635c64db90.png)

**Comment by vengiare** [comment] 2022-02-06 14:17
> that opener would be only one by one, so shouldnt be count as duplicate, and i prefer sort :)

there's actually a good reason that was discussed in that thread

![image](https://user-images.githubusercontent.com/63973749/152685166-dd7dce77-f117-4760-af89-029cb54b991f.png)

**Comment by Riztard** [comment] 2022-02-06 14:31
personally i dont think so

**Comment by Susuys** [comment] 2022-02-07 07:39
> personally i dont think so

Why

**Comment by Susuys** [comment] 2022-02-07 07:57
> > a button to choose a random manga looks cool, but just use categories to separate the ones you've read from the ones you haven't
> 
> yes... unless its not small in number. and even more in my case <img alt="" width="300dp" src="https://user-images.githubusercontent.com/16263232/152676703-3865c726-7e19-49b9-89bf-aea797310039.png">

Same 
I also have this problem

**Comment by Susuys** [comment] 2022-02-07 07:58
> > that opener would be only one by one, so shouldnt be count as duplicate, and i prefer sort :)
> 
> there's actually a good reason that was discussed in that thread
> 
> ![image](https://user-images.githubusercontent.com/63973749/152685166-dd7dce77-f117-4760-af89-029cb54b991f.png)

That also a good idea

**Comment by Susuys** [comment] 2022-02-07 08:30
> Duplicate of #4648
> 
> #1248 would be more preferable.

Well i really don't know about them

But I still wish that you would make this option available in future updates

I have been using this app for almost 2 years now and have a really big library 

there are many people like me who could appreciate this option

sorry for the trouble 🥺
