### ISSUE TITLE
It won't update all manga

### ISSUE THREAD

**Issue by KenDxD** [tachiyomiorg/tachiyomi#6633] opened 2022-02-12 15:07 UTC
### Steps to reproduce

1. Update the manga
2. Wait to update all list
3. There's a notification view that all chapter is updated

### Expected behavior

I expected that all of my manga is updated (243 manga) 

### Actual behavior

It only update 29 manga using the latest tachiyomi version 0.13.1

### Tachiyomi version

0.13.1

### Android version

Android 11

### Device

OPPO A9 2020

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-02-12 15:08
Duplicate of #6599

**Closed by arkon** 2022-02-12 15:08 UTC
Labels: Bug
