### ISSUE TITLE
Keep swiping in Webtoon or Continuous vertical mode cause navigation layout shift

### ISSUE THREAD

**Issue by Myuki** [tachiyomiorg/tachiyomi#5955] opened 2021-09-22 11:16 UTC
### Steps to reproduce

1. Use `Webtoon` or `Continuous vertical` mode to read manga.
2. Use swiping up instead of tap to turn the page.
3. Keep read some chapters. I can't exactly find out how to reproduce this bug. But it always occurs if keep reading some chapters. Reopen reader can fix the problem.

### Expected behavior

Navigation layout should keep as its position.
* Top: Previous page
* Middle: Menu
* Bottom: Next page

### Actual behavior

Navigation layout upward shift just like my swiping also affect it not only pages. It will become:
* Top: Menu
* Middle: Next page
* Bottom: Next page

or:
* Top: Previous page
* Middle: Previous page
* Bottom: Menu

### Tachiyomi version

0.12.2

### Android version

Android 11

### Device

OnePlus 9R

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Myuki** [comment] 2021-09-22 11:34
I had tested the `Continuous vertical` mode, and it also occurred.

**Comment by arkon** [comment] 2021-09-22 12:37
Did you zoom?

**Comment by Myuki** [comment] 2021-09-22 12:54
> 
> 
> Did you zoom?

I just tested and assure not zoom, and the problem is solved. It seems to relate to zoom. Scrolling is really easy to become a double tap zoom.

**Comment by arkon** [comment] 2021-09-22 12:57
Duplicate of #4875

**Closed by arkon** 2021-09-22 12:57 UTC
Labels: Bug
