### ISSUE TITLE
OCR dictionary

### ISSUE THREAD

**Issue by dogs-1985** [tachiyomiorg/tachiyomi#7191] opened 2022-05-24 09:25 UTC
### Describe your suggested feature

I know its a huge enhancement to have an OCR dictionary features. But I still want the OCR dictionary features to able translate directly with simple finger highlighting.

I know there will definitely be someone who suggest to share the image to third party app like google lens, but I really don't need a full page translation, just a single word or few. Also I don't like to keep switching apps to see translation results.

I tried kaku app recently and found it difficult to use. (No intention to speak ill of the developer, don't get me wrong)

The features should work like this
1. There is a floating translate button 
2. When I click on floating translate button, it will activate the translation mode
3. After I circle the word to be translated, another action will appear
4. Press on action translate, wait for couple minutes and result will popup

I didn't say that this features is necessary,
If the developer thinks this feature can be done, just assign this issue to the relevant person.
If the developer thinks this features cannot be done, that's ok, please close this issue. (I won'd be depressed)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2022-05-24 09:27
Duplicate of #3383 basically

**Closed by Seishirou101** 2022-05-24 09:27 UTC
Labels: Feature request
