### ISSUE TITLE
History tab no longer working properly

### ISSUE THREAD

**Issue by Dostic** [tachiyomiorg/tachiyomi#8780] opened 2022-12-20 21:20 UTC
### Steps to reproduce

1. Go to "History" Tab

### Expected behavior

Checking the history tab displays the chapter I last read, clicking it should take me to that chapter like it did before.

### Actual behavior

Clicking "Chapter 9"for a manga for example takes me to the highest, unread chapter instead and if there are none does not allow me to click it.

### Tachiyomi version

0.14.2

### Android version

Android 10

### Device

Samsung Galaxy S10E

### Other details

Chapter Pages also no longer save

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-12-20 22:01
Duplicate of #8454

**Closed by arkon** 2022-12-20 22:01 UTC
Labels: Bug
