### ISSUE TITLE
Provide switches to disable double click zoom / two-finger pinch zoom

### ISSUE THREAD

**Issue by zzh4n** [tachiyomiorg/tachiyomi#6996] opened 2022-04-24 05:59 UTC
### Describe your suggested feature

It's easy to zoom when I tap the screen quickly to turn pages. There are already two ways to zoom (two-finger pinch and double-tap), but no way to quickly turn pages (quick swiping is difficult on large-screen devices).

Please provide a switch to disable double tap zoom so I can quickly turn pages (two quick taps for two pages, three quick taps for three pages, and so on). This is more in line with the reader's use logic, double-click zoom is more like using an album.

And zooming is almost useless on a tablet (screen size is big enough). If possible, please also provide a switch to disable the two-finger pinch zoom to reduce accidental touches.

_- from Google Translate_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment] 2022-04-24 06:01
Have you tried using the volume rocker to turn pages?

**Comment by curche** [comment] 2022-04-24 06:41
Or Navigation Layouts: you can tap in particular regions of page to go to next/previous pages. If you have a Samsung tablet with supported S-Pen (air) actions, you can configure those as well

Read more about Navigation Overlay at the website: https://tachiyomi.org/help/guides/reader-settings/#navigation-layout

If you're facing automatic zooming issues, disable "Zoom Landscape" in Reader settings

**Comment by zzh4n** [comment] 2022-04-24 06:41
> Have you tried using the volume rocker to turn pages quickly?

This affects the life of the keys.  It is not suitable as the primary way to turn pages.

**Comment by zzh4n** [comment] 2022-04-24 07:18
> Or Navigation Layouts: you can tap in particular regions of page to go to next/previous pages. If you have a Samsung tablet with supported S-Pen (air) actions, you can configure those as well
> 
> Read more about Navigation Overlay at the website: https://tachiyomi.org/help/guides/reader-settings/#navigation-layout
> 
> If you're facing automatic zooming issues, disable "Zoom Landscape" in Reader settings
> 

I have "tap in particular regions" of page to go to next/previous pages. But when I tap twice quickly, the screen zooms.  Instead of turning two pages as expected.

**Comment by arkon** [comment] 2022-05-26 02:36
Duplicate of #4145

**Closed by arkon** 2022-05-26 02:36 UTC
Labels: Feature request
