### ISSUE TITLE
Custom manga details

### ISSUE THREAD

**Issue by Xorio71** [tachiyomiorg/tachiyomi#8083] opened 2022-09-26 11:12 UTC
### Describe your suggested feature

Just like TachiJ2K, users should be able to edit the manga's title, author, artist, about, and status by tapping an 'Edit' button in the manga screen.

### Other details

![Screenshot_20220926-141050_TachiyomiJ2K](https://user-images.githubusercontent.com/101265862/192262387-c86d6d67-6c67-4051-8076-0c57ac69e907.png)
![Screenshot_20220926-141116_TachiyomiJ2K](https://user-images.githubusercontent.com/101265862/192262393-1d0d26d6-e314-4040-9510-edbab503987f.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2022-09-26 11:41
Duplicate of #4398.

**Closed** 2022-09-26 12:11 UTC
Labels: Feature request
