### ISSUE TITLE
[Bug]Chapter titles with the same manga titles get removed (local source)

### ISSUE THREAD

**Issue by AbdulM7iz** [tachiyomiorg/tachiyomi#6786] opened 2022-03-16 19:09 UTC
### Steps to reproduce

1. Have a local source manga
2. Have a chapter title that has the manga title in it somewhere
3. Browse the chapter lost of said local manga in tachiyomi

### Expected behavior

All chapters including the ones that have the manga title in their chapter titles should appear normally

### Actual behavior

The part that has the manga title of the chapter title gets removed as seen in these screenshots
Browsing chapters inside of tachiyomi
![Screenshot_2022-03-16-20-02-53-677_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/101192926/158667981-386e1252-0d53-4cbd-96a5-66a3fb8f6e83.jpg)
Browsing chapters inside of a file explorer
![Screenshot_2022-03-16-18-20-57-758_pl solidexplorer2](https://user-images.githubusercontent.com/101192926/158668043-f42706e2-fb0d-4702-a949-64a311df1176.jpg)

You can clearly notice the title get demolished in chapter 225 and 226.

### Tachiyomi version

App version: 0.13.1-4197

### Android version

Android 11

### Device

Xiaomi Redmi note 8 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-03-16 19:24
Duplicate of #6578

**Closed by arkon** 2022-03-16 19:24 UTC
Labels: Bug
