### ISSUE TITLE
Double tap Browse to go to last used source

### ISSUE THREAD

**Issue by vengiare** [tachiyomiorg/tachiyomi#7549] opened 2022-07-16 23:47 UTC
### Describe your suggested feature

Title. Should either "not work" or "default to Local source" if there is no last used source (app first run)

### Other details

Browse is the last navbar item to not have a double tap action so I'm just throwing this idea out there

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Safayy** [comment] 2022-07-29 09:59
I'm not sure if it works the same for new features, but as per contributing guidelines I'd like to state I'm working on this.

**Comment by arkon** [comment] 2022-10-08 17:00
Duplicate of #6515

**Closed by arkon** 2022-10-08 17:00 UTC
Labels: Feature request
