### ISSUE TITLE
[Feature Request] migrate a manga to local source

### ISSUE THREAD

**Issue by SamSensei** [tachiyomiorg/tachiyomi#4764] opened 2021-04-02 06:08 UTC
Requesting option to migrate a manga to local source through an option in app instead of manually doing it , manually doing it does not provide good results (i have tried few times) such as missing metadata info and cover,etc
## Why
As we know many manga sources are dying or keep changing their manga details such as chapter name which causes our download manga to not appear as downloaded in Tachiyomi.

User Benefit
No need to migrate manually which is a hassle to create folders and proper names , directory, adding metadata,etc.

## Requirements
Option to migrate a manga to local source.

**Comment by arkon** [comment] 2021-04-03 14:14
Duplicate of #2289

**Closed by arkon** 2021-04-03 14:14 UTC
Labels: feature
