### ISSUE TITLE
Per category settings for filters

### ISSUE THREAD

**Issue by oge2k** [tachiyomiorg/tachiyomi#7413] opened 2022-06-29 23:15 UTC
### Describe your suggested feature

Since the app already has a per category settings for sort and update(under settings -> library), i thought it would be nice to have the same per category customisation but for filters, so maybe a category can be made to show only downloaded manga and another to show only unread manga

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2022-06-29 23:25
Duplicate of #6337, though that one asks for more than just filters

**Closed by Seishirou101** 2022-06-29 23:25 UTC
Labels: Feature request
