### ISSUE TITLE
Search select all

### ISSUE THREAD

**Issue by kingtie** [tachiyomiorg/tachiyomi#8324] opened 2022-10-29 06:09 UTC
### Steps to reproduce

Search a extension name in library.
![Screenshot_20221029-150719_Tachiyomi](https://user-images.githubusercontent.com/62863320/198816641-a15049e0-144a-49a6-947d-4ee8f5b588a4.png)

Top right corner select all
Selects everything inside of the category including from extensions that were not searched.
![Screenshot_20221029-150728_Tachiyomi](https://user-images.githubusercontent.com/62863320/198816653-a6486d51-3c01-45af-8178-06e68b7eaf85.png)

### Expected behavior

Before updating to 14.0 it would only select things that were from the extension or tag that were searched

### Actual behavior

It selects everything that's in the category even when not searched

### Tachiyomi version

14.0

### Android version

Android 12

### Device

Galaxy s22 Ultra

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment] 2022-10-29 07:14
Duplicate of #8287

**Closed by AntsyLich** 2022-10-29 07:14 UTC
Labels: Bug
