### ISSUE TITLE
incorrect behavior of direction pad

### ISSUE THREAD

**Issue by lpuglia** [tachiyomiorg/tachiyomi#8028] opened 2022-09-18 09:27 UTC
### Steps to reproduce

open the app
select scale type: fit width
turn the phone on the side
open a manga
execute:  adb shell input keyevent DPAD_DOWN

### Expected behavior

page scroll down

### Actual behavior

switch to next page

### Tachiyomi version

0.13.6

### Android version

10

### Device

One Plus 5

### Other details

Am i missing anything? is this to be expected?

i'm trying to navigatea using a keyboard (i added the adb shell command for clarity) but when i press the "down key", instead of navigating down, the page get switched for the next one. Is there any way to change this behavior or are there alternatives to direction pad?

thanks for the help!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-09-18 14:57
Duplicate of #4532

**Closed by arkon** 2022-09-18 14:57 UTC
Labels: Bug
