### ISSUE TITLE
Auto-skip pages

### ISSUE THREAD

**Issue by Ouinon0** [tachiyomiorg/tachiyomi#7012] opened 2022-04-25 15:39 UTC
### Describe your suggested feature

I'm actually reading a manga with very few pages and for each new chapter I need to swipe the team trad's page, the opening and the outer. 
Can we set up a way to auto-skip these pages (by example: skip the first and the last page of each chapter).
Or even better a way to report none useful pages and auto-skip these pages for all readers in the same source (like Sponsor Block on ytb) (but I can't see a world where it's possible).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-04-25 15:53
Duplicate of #3274

**Closed by arkon** 2022-04-25 15:53 UTC
Labels: Feature request
