### ISSUE TITLE
File Picker not working on inkBOOK Calypso Plus

### ISSUE THREAD

**Issue by rpr13** [tachiyomiorg/tachiyomi#8012] opened 2022-09-15 06:22 UTC
### Steps to reproduce

Hi.
I have problem on my android ebook reader.
inkBOOK Calypso Plus have custom Android 8.1 (detected by adb as "rockchip CalypsoPlus").
I wanted to change download location but cannot.
Tachiyomi cannot detect any file picker (file manager). I've installed many but none is detected.

### Expected behavior

Able to change download location

### Actual behavior

Cannot open file picker ("No file picker app found")

### Tachiyomi version

0.13.6

### Android version

Android 8.1

### Device

inkBOOK Calypso Plus

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-09-18 20:17
Duplicate of #7900

**Closed by arkon** 2022-09-18 20:17 UTC
Labels: Bug
