### ISSUE TITLE
Per-manga settings for scale

### ISSUE THREAD

**Issue by wopian** [tachiyomiorg/tachiyomi#5864] opened 2021-09-06 16:24 UTC
### Describe your suggested feature

In the settings modal, only Viewer for this series/Default viewer and rotation is per-manga.

For example, if your global reader setting for Scale type is Fit height, changing this to Stretch in the modal will make all manga open with that setting.

### Other details

https://github.com/tachiyomiorg/tachiyomi/issues/452#issue-175140088

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by NotPageD** [comment] 2021-09-07 04:30
Yes, this would be so helpful. I dont have to constantly change scale type between series.

**Comment by Disposablegloves** [comment] 2022-06-02 02:02
+1 for this. I have a few manga that I like reading in landscape + fit width. Mostly 4komas like Gekkan Shoujo and that Tensei slime spin-off. Everything else I read in portrait + fit height.

**Comment by arkon** [comment] 2022-07-10 00:17
Duplicate of #1849

**Closed by arkon** 2022-07-10 00:17 UTC
Labels: Feature request
