### ISSUE TITLE
backup via email

### ISSUE THREAD

**Issue by hinorashi57** [tachiyomiorg/tachiyomi#6748] opened 2022-03-07 23:02 UTC
### Describe your suggested feature

it should be able to access your email to save the backup to like how mobile games do with your playstore account, or apple games account but with your email. Like some kinda cloud storage. This would make it much easier to restore and use the app over multiple devices.

### Other details

i dont know if this is a bad idea, but I'd think it be hjelpful.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-03-07 23:03
Duplicate of #912

**Closed by arkon** 2022-03-07 23:03 UTC
Labels: Feature request
