### ISSUE TITLE
Export library or individual items as Comic Book Archive (CBZ)

### ISSUE THREAD

**Issue by Yugen42** [tachiyomiorg/tachiyomi#5723] opened 2021-08-15 18:20 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

This might be out of scope if the vision for this is app is to remain only an aggregator/viewer, however for me Tachiyomi has evolved into a central hub for finding and downloading manga. I'd like to be able to use these downloads easily on other platforms or systems such as e-readers. The most common format for exchanging such data is https://en.wikipedia.org/wiki/Comic_book_archive which is essentially just a zip of what Tachiyomi already has in its file system. Currently I'd need to manually zip and share those files. I propose an "export" dialog that does the zipping and passes the file to a share intent (could be split into multiple dialogs, not sure about the UX). This could the be used to one-click transfer downloaded data to different devices that might not even run android.

Let me know if you think this is out of scope, otherwise I might look into doing the implementation myself. If you think it is out of scope I might create a separate app or some script to do that process.

**Comment by curche** [comment] 2021-08-15 18:38
Duplicate of https://github.com/tachiyomiorg/tachiyomi/issues/918
Planned as part of 1.x rewrite

In addition, refer comment: https://github.com/tachiyomiorg/tachiyomi/pull/1526#issuecomment-846491231

**Closed by curche** 2021-08-15 18:38 UTC
Labels: Feature request
