### ISSUE TITLE
History/resume not working properly 

### ISSUE THREAD

**Issue by sjpeters79** [tachiyomiorg/tachiyomi#8517] opened 2022-11-13 00:26 UTC
### Steps to reproduce

After the last update, any time I try to resume any of my mangas, it does not take me to where I left of.

### Expected behavior

It's suppose to let me resume from where I left off but it's not working right now.

### Actual behavior

It takes me to the beginning of the manga instead of resuming at the chapter I left off. Sometimes it takes me to random chapters instead.

This happens for all my mangas.

### Crash logs

--------- beginning of main
11-12 19:15:32.448 26721 26721 E ViewRootImpl: sendUserActionEvent() mView returned.
11-12 19:15:32.484 26721 26721 E ViewRootImpl: sendUserActionEvent() mView returned.
11-12 19:15:54.721 26721 26721 E ViewRootImpl: sendUserActionEvent() mView returned.
App version: 0.14.2 (standard, 3222247, 91, 2022-10-31T21:42Z)
Android version: 12 (SDK 32)
Android build ID: SP2A.220305.013.F711WVLS3DVI4
Device brand: samsung
Device manufacturer: samsung
Device name: b2q
Device model: SM-F711W
Device product name: b2qcsx

### Tachiyomi version

App version: 0.14.2

### Android version

Android 12

### Device

Z flip 3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-11-13 00:34
Duplicate of #8454

**Closed by arkon** 2022-11-13 00:34 UTC
Labels: Bug
