### ISSUE TITLE
Download option on manga update notification

### ISSUE THREAD

**Issue by GustavoDill** [tachiyomiorg/tachiyomi#6335] opened 2021-12-09 14:23 UTC
### Describe your suggested feature

![20211209_111703](https://user-images.githubusercontent.com/43525892/145413139-44f54e15-aeb1-40cf-a7b7-c41706fe383e.jpg)

When the library updates and the notification above apears it would be nice to have a download option along with the **"Mark as Read | View Chapters"** something like **"Mark as Read | View Chapters | Download Chapters"**

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2021-12-09 14:24
Duplicate of #2986

**Closed by arkon** 2021-12-09 14:24 UTC
Labels: Feature request
