### ISSUE TITLE
[Feature Request] option to let extension set manga as webtoon

### ISSUE THREAD

**Issue by Light-Wing** [tachiyomiorg/tachiyomi#2898] opened 2020-04-19 05:08 UTC
### Why/User Benefit/User Problem
Having to choose for each webtoon to read it as a webtoon gets old... So I thought if extensions would be able to add a category (like manga.webtoom = true), and then the main app reads that and sets the reading mode to webtoon automatically would be great...

### What/Requirements
When the source is setting the info of the genres, usually webtoons have a genre to indicate it (long-strip, webtoon, web comic etc.). And by checking for that genre the source can set the type of reading mode... (I think Neko (the mangadex fork) already does this...)

**Comment by Soitora** [comment] 2020-04-19 05:49
Do you read a lot of manga too? Otherwise you could set the default as Webtoon and then change manually for manga

**Comment by Light-Wing** [comment] 2020-04-19 06:21
I read plenty of both, my default is already vertical reading, but I like
the difference, as I crop the borders for non webtoon manga, and for
webtoons cropping borders would ruin the smooth transition between
images... So I only crop regular manga...

**Comment by Soitora** [comment] 2020-04-19 06:48
That's reasonable

**Comment by gotson** [comment] 2020-04-19 07:47
It would be interesting for Komga as well, since Komga has metadata about books including the reading direction. With this all books could be set with the proper reading direction, as set on server side.

**Comment by scb261** [comment] 2021-03-22 18:05
Duplicate of #1664

**Closed** 2021-03-22 18:08 UTC
Labels: feature
