### ISSUE TITLE
Suggestion:- Seperate manga with 100+ chapter into selectable groups/button

### ISSUE THREAD

**Issue by soymadip** [tachiyomiorg/tachiyomi#9150] opened 2023-02-26 10:16 UTC
### Describe your suggested feature

- When an anime/manga has 100/200+ episodes/chapters, the episode list becomes too long.
- if we wanna watch/read a episode/chapter that is at the end of list, we have to scroll a long way to reach that chapter. 
- Now if the app devides the chapters into groups of 50/100 chapters and with button we can switch to groups, it will be far more easier to reach the chapters.
- And it will make the app a little bit cleaner too.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by soymadip** [comment] 2023-02-26 10:17
Well there is a similar issue , but i guess it's not related and it's old too

**Comment by Seishirou101** [comment] 2023-02-26 10:56
Duplicate of #6710

**Closed by Seishirou101** 2023-02-26 10:56 UTC
Labels: Feature request

**Comment by soymadip** [comment] 2023-02-26 12:34
😮‍💨 repeat again huh!
