### ISSUE TITLE
Ability to reuse the last set filter

### ISSUE THREAD

**Issue by Johb404** [tachiyomiorg/tachiyomi#8293] opened 2022-10-26 07:54 UTC
### Describe your suggested feature

I use a lot of filter options when I look for new stuff and it's kinda annoying to go through every time ticking every box for stuff I like/dislike. I think it would be cool if there were a button that just reused the last filter settings you picked. I attached an image of what I think it could look like.

### Other details

![filter example](https://user-images.githubusercontent.com/116712232/197965380-4ccfc0b6-b7b3-458c-99e8-109e9e95d544.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-10-26 21:43
Duplicate of #1484

**Closed by alessandrojean** 2022-10-26 21:43 UTC
Labels: Feature request
