### ISSUE TITLE
Framerate drop

### ISSUE THREAD

**Issue by Pipixel** [tachiyomiorg/tachiyomi#7434] opened 2022-07-01 23:18 UTC
### Steps to reproduce

It depends the chapters, without any methods to reproduce

### Expected behavior

Something always smooth

### Actual behavior

The framerate drop for no reason

### Tachiyomi version

0.13.4

### Android version

Android 12.1 (Nameless AOSP)

### Device

Oneplus 8t (Europe)

### Other details

https://drive.google.com/file/d/1-2W3ncLp4kzgP4Qz-n35AkFRkc5Lb472/view?usp=drivesdk video with framerate overlay

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-07-02 01:01
Duplicate of #1908

**Closed by arkon** 2022-07-02 01:01 UTC
Labels: Bug
