### ISSUE TITLE
Library update strange behavior

### ISSUE THREAD

**Issue by Jokerdrim** [tachiyomiorg/tachiyomi#9097] opened 2023-02-16 21:49 UTC
### Steps to reproduce

1. Tried to update all extentions and tachiyomi.
2. Cleared cache
3. Tried to reinstall and this issue still exist

### Expected behavior

The problem would be solved

### Actual behavior

The problem stayed

### Crash logs

App did not crash

### Tachiyomi version

Preview r5513

### Android version

Android 11

### Device

Samsung Galaxy A50

### Other details

In the settings I have it so that when updating the manga is not skipped. But after updating the library, I have two reports. One is about failed updates and the other is about missing manga. And when I try to open the missed manga report, I am thrown to the FAQ.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-02-18 15:12
Maybe duplicate of #9074, issue never actually describes what the issue is.

**Closed by arkon** 2023-02-18 15:12 UTC
Labels: Bug
