### ISSUE TITLE
<feature request>  screen off when app inactive

### ISSUE THREAD

**Issue by alexphilip0019** [tachiyomiorg/tachiyomi#5244] opened 2021-05-30 23:39 UTC
New feature request:
Have a drop-down with screen timeout options like 15sec, 30sec, 1min, never etc.
Basically when there is no activity for selected amount of time the screen switched off and locks.

**Comment by arkon** [comment] 2021-05-31 14:14
Duplicate of #3251

**Closed by arkon** 2021-05-31 14:14 UTC
