### ISSUE TITLE
Ui overly slow after 0.14.0

### ISSUE THREAD

**Issue by LucasGGamerM** [tachiyomiorg/tachiyomi#8540] opened 2022-11-15 21:10 UTC
### Steps to reproduce

Navigate between tabs in the library or extension manager 

### Expected behavior

Be a fast app

### Actual behavior

Quite slow when switching tabs or scrolling. Actual reader is fine though.

### Crash logs

It doesn't crash, but it's rather slow

### Tachiyomi version

0.14.2

### Android version

Android 13 

### Device

Google pixel 3 running CalyxOS and Moto G5s running LineageOS 17.1

### Other details

In previous versions before the whole UI rewrite, tachiyomi felt a lot more fluid than after the UI rewrite. Please 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-11-15 21:11
Duplicate of #8310

**Closed** 2022-11-15 21:11 UTC
Labels: Bug
