### ISSUE TITLE
Category Widget

### ISSUE THREAD

**Issue by Amadeusart01** [tachiyomiorg/tachiyomi#9116] opened 2023-02-20 22:52 UTC
### Describe your suggested feature

A widget that work just like the one that already exist, but it contains a category from your library, or the recent open mangas.
Thank!

### Other details

It would be cool if we could change the widget color. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-02-20 23:08
Duplicate of #8411

**Closed by arkon** 2023-02-20 23:08 UTC
Labels: Feature request
