### ISSUE TITLE
Can't save covers when they are gifs/animated

### ISSUE THREAD

**Issue by Adham-A** [tachiyomiorg/tachiyomi#9779] opened 2023-07-30 18:08 UTC
### Steps to reproduce

Go to an entry with an animated cover
Click on the cover
Click on the save button
Success message displays
Nothing in the phone gallery 

### Expected behavior

Cover should be saved in phone gallery 

### Actual behavior

Cover isn't saved even if successful display message is shown

### Tachiyomi version

App version: 0.14.6

### Android version

Android version: 13 (SDK 33) Android build ID: TQ3A.230705.001

### Device

Pixel 6A

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-07-30 18:13
Duplicate of #6487

**Closed by arkon** 2023-07-30 18:13 UTC
Labels: Bug
