### ISSUE TITLE
extension dmzj can't use

### ISSUE THREAD

**Issue by rain-0** [tachiyomiorg/tachiyomi#5403] opened 2021-06-16 01:02 UTC
**PLEASE READ THIS**

I acknowledge that:

- I have updated:
  - To the latest version of the app (stable is v0.11.1)
  - All extensions
- I have tried the troubleshooting guide: https://tachiyomi.org/help/guides/troubleshooting-problems/
- If this is an issue with an extension, that I should be opening an issue in https://github.com/tachiyomiorg/tachiyomi-extensions
- I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another open issue

## Device information
* Tachiyomi version: App version: 0.11.1 (standard, 0f3f1e9, 63, 2021-05-31T23:39Z)
Android version: 10 (SDK 29)
Android build ID: ALP-AL00 10.0.0.175(C00E175R2P4)
Device brand: HUAWEI
Device manufacturer: HUAWEI
Device name: HWALP
Device model: ALP-AL00
Device product name: ALP-AL00

while open the dmzj，it's a massage that
"unable to resolve host "v3api. dmzj1. com": no address associated with host name"
other extension can use normally

**Comment by loocool2** [comment] 2021-06-16 01:03
Duplicate of #5501

**Closed by loocool2** 2021-06-16 01:03 UTC
Labels: bug
