### ISSUE TITLE
Backup manga covers

### ISSUE THREAD

**Issue by Xorio71** [tachiyomiorg/tachiyomi#7355] opened 2022-06-21 14:44 UTC
### Describe your suggested feature

We should be able to backup assigned manga covers, when backing-up Tachiyomi.

### Other details

The option should be with the other backup options (Library, History, Trackers, etc.) and should be tickable.

Also, limit it to self-assigned covers (From our gallery), as I believe source-assigned cover backup would be too hard to implement (Unless, of course, you like the challenge).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-06-21 17:01
Duplicate of #5836

**Closed by arkon** 2022-06-21 17:01 UTC
Labels: Feature request
