### ISSUE TITLE
[Feature request] Reader remembering the percentage instead of page numbers 

### ISSUE THREAD

**Issue by Jjjggh** [tachiyomiorg/tachiyomi#7175] opened 2022-05-20 17:43 UTC
### Describe your suggested feature

Reader remembering the percentage were you left of instead of the page or picture, Would be useful in case of long pictures and webtoons .

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-05-20 17:59
Duplicate of #3322

**Closed by arkon** 2022-05-20 17:59 UTC
Labels: Feature request
