### ISSUE TITLE
deleting manga while library is updating adds the manga back

### ISSUE THREAD

**Issue by ebarruel** [tachiyomiorg/tachiyomi#5580] opened 2021-07-19 09:23 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

Preview r3606

### Android version

Android 11

### Device

OnePlus 7 Pro

### Steps to reproduce

1. Update library (or category)
2. Remove manga from library (or category) before library update gets to it

### Expected behavior

The update should skip over the removed manga (or at least check it and leave it removed).

### Actual behavior

The manga will be added back to the library.

**Comment by arkon** [comment] 2021-07-19 12:15
Duplicate of #3281

**Closed by arkon** 2021-07-19 12:15 UTC
Labels: Bug
