### ISSUE TITLE
Chapter numbers are constantly reset to -1

### ISSUE THREAD

**Issue by stevenyomi** [tachiyomiorg/tachiyomi#7326] opened 2022-06-17 22:15 UTC
### Steps to reproduce

None

### Expected behavior

Chapter numbers should not change after they are recognized.

### Actual behavior

Chapter numbers are constantly reset to -1. Haven't found any pattern yet. Affected chapters can be:

- All chapters
- All but the latest
- One or two
- None

### Crash logs

None

### Tachiyomi version

r4466

### Android version

Not related

### Device

Not related

### Other details

None

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment] 2022-06-18 15:32
Duplicate of #7292

**Closed** 2022-06-18 15:44 UTC
Labels: Bug
