### ISSUE TITLE
Read double page for horizontal tablet view.

### ISSUE THREAD

**Issue by Saray1129** [tachiyomiorg/tachiyomi#10310] opened 2024-01-07 03:43 UTC
### Describe your suggested feature

I am a person who reads a lot on the tablet and I would like that when reading a manga horizontally there is the option for two pages to appear at the same time as if I were reading a physical manga.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2024-01-07 03:45
Duplicate of #149

**Closed by arkon** 2024-01-07 03:45 UTC
Labels: Feature request
