### ISSUE TITLE
Tachiyomi crashes when migrating since update

### ISSUE THREAD

**Issue by lovablesweet35** [tachiyomiorg/tachiyomi#9302] opened 2023-04-07 00:39 UTC
### Steps to reproduce

1.open app
2.go to migrate
3. Be able to migrate from different sources

### Expected behavior

1.open app
2.go to migrate
3. Be able to migrate from different sources

### Actual behavior

1.open app
2.go to migrate
3. App crashes after the transfer to different source.

### Crash logs

[tachiyomi_crash_logs-1.txt](https://github.com/tachiyomiorg/tachiyomi/files/11175225/tachiyomi_crash_logs-1.txt)

### Tachiyomi version

0.14.5

### Android version

S21

### Device

S21

### Other details

I tried to do the pinned extensions and its still crashed then i tried to install the preview but it still crashed. It happened when i updated to the new latest app version.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment] 2023-04-07 04:59
Duplicate of #8400

It's probably due to library size. How many titles do you have in your library?

**Closed** 2023-04-07 04:59 UTC
Labels: Bug, Duplicate

**Comment by lovablesweet35** [comment] 2023-04-08 01:43
> Duplicate of #8400
> 
> It's probably due to library size. How many titles do you have in your library?

Around 5000 titles and 45 extensions
