### ISSUE TITLE
Option to make sure, that while switching pages, scrolling would move a zoomed in page to its end, before switching it

### ISSUE THREAD

**Issue by AnataBakka** [tachiyomiorg/tachiyomi#6312] opened 2021-12-05 01:52 UTC
### Describe your suggested feature

Reproduction:
1. Have Reader on fit screen and left-right mode.
2. Zoom in on a page.
3. Scroll left until you reach the left-end of the page.
4. Scroll again left to enter page-switching mode. (Note: to scroll you swipe the screen, but do not remove your finger).
5. Now scroll right while still being in the switching mode (i.e don't remove finger).

What currently happens:
While you scroll right on the first page you had zoomed in, the moment your screen reaches the same position it had been upon starting the page-switching mode (i.e at the 4th point above) or rather, after scrolling a fixed amount (depending on your screen i guess), you will start switching to the next page. i.e the zoomed in page will remain zommed in while you're switching pages.

What i would like for it to happen:
While you keep on scrolling, your zoomed in page would start moving instead until it reaches its end side, and only then it would start switching.

Why?
I don't always remove my finger from the screen, and when i switch pages back and forward, i remain in the page-switching mode, and thus i end up, by mistake, on switching to the next page, without being able to see the entire width of the previous zoomed page, which is annoying.
I can understand how something like this may be useful for people who read on fit height (and width > height) / original size, allowing them to more quickly switch pages (since they're zoomed in by default), but i feel like it's really bad for those who use fit width / screen and who manually zoom in (and who already have maximum speed when switching pages).

Edit:
I found out about continuous vertical, and this issue is not there. I would be fully happy if it weren't for another issue https://github.com/tachiyomiorg/tachiyomi/issues/6325.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2021-12-11 18:18
Duplicate of #2161

**Closed by arkon** 2021-12-11 18:18 UTC
Labels: Feature request
