### ISSUE TITLE
Chapters keep deleting automatically

### ISSUE THREAD

**Issue by LimeytheLime** [tachiyomiorg/tachiyomi#8495] opened 2022-11-10 17:20 UTC
### Steps to reproduce

1. I download all chapters of One Piece through MangaLife(EN).
2. I try to read it the following day.
3. It's gone.

### Expected behavior

It should stay downloaded until I need it deleted

### Actual behavior

It somehow deletes itself and I have to redownload it, only for it to go away the following day. It's doing it by itself somehow and I don't get how.

### Tachiyomi version

App version: 0.14.2

### Android version

Android 13

### Device

Samsung s22 

### Other details

I've used MangaLife before for downloads with no issues with keeping downloads but it is just One Piece that is doing this, and it hasn't even happened before. It once kept all my chapters for it and now it doesn't

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Zodiarkcsr** [comment] 2022-11-12 20:18
As for me the downloaded chapter will automatically deleted if long press the downloaded arrow symbol.

**Comment by arkon** [comment] 2022-11-14 02:56
Duplicate of #8438

**Closed by arkon** 2022-11-14 02:56 UTC
Labels: Bug
