### ISSUE TITLE
Move downloaded Comic to Local Source 

### ISSUE THREAD

**Issue by TheKingTermux** [tachiyomiorg/tachiyomi#7688] opened 2022-08-05 11:05 UTC
### Describe your suggested feature

Please add the ability to move downloaded comics (especially finished ones) to reduce storage usage on internal memory and move to external memory on local sources

### Other details

Allows users to move comics that have been downloaded on tachiyomi (from internal memory) to be moved to local sources on external memory by creating folders in external memory title, description, genre, etc. to automatically create details.json file along with the cover and can be directly inserted  in the library category without going to the "local source" source first to add comics to the library category.

To delete it, you can do it in library categories such as comics from other sources (not local sources) so that you can delete comics from local sources without having to delete them manually.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-08-05 12:21
Duplicate of #2289

**Closed by arkon** 2022-08-05 12:21 UTC
Labels: Feature request
