### ISSUE TITLE
Mangadex Login 

### ISSUE THREAD

**Issue by JDKamalakar** [tachiyomiorg/tachiyomi#10255] opened 2023-12-21 08:14 UTC
### Describe your suggested feature

Ability to login in mangadex & update it's reading count (Tracking For Mangadex)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment] 2023-12-21 10:13
Tracking part of MangaDex hasn't been live yet in v5

**Comment by AntsyLich** [comment] 2023-12-21 10:14
Also duplicate of #2370

**Closed by AntsyLich** 2023-12-21 10:14 UTC
Labels: Feature request
