### ISSUE TITLE
Add music 

### ISSUE THREAD

**Issue by Rifal783** [tachiyomiorg/tachiyomi#5632] opened 2021-07-30 16:41 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

I recently found out that some webcomics have music so I suggest if you can to add a button like a volume icon or something that we can press to turn it on or off

### Other details

If it isn't too hard to add this feature am sure other people who use this app will enjoy it

**Comment by loocool2** [comment] 2021-07-30 16:48
Duplicate of #3738

**Closed by loocool2** 2021-07-30 16:48 UTC
Labels: Feature request
