### ISSUE TITLE
Add Hex Color Code Picker For App Theme In Appearance

### ISSUE THREAD

**Issue by shawkik** [tachiyomiorg/tachiyomi#6278] opened 2021-11-25 11:39 UTC
### Describe your suggested feature

User can choose a color from **Hex Color Code Picker** for **App Theme**

### Other details

More > Settings > Appearence > **App Theme** > [**(Add:Custom) > Hex Color Code Picker**]

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2021-11-25 12:01
Duplicate of #3451

**Closed** 2021-11-25 12:01 UTC
Labels: Feature request
