### ISSUE TITLE
Allow to remigrate all mangas in one source

### ISSUE THREAD

**Issue by mmalyska** [tachiyomiorg/tachiyomi#7755] opened 2022-08-14 11:17 UTC
### Describe your suggested feature

When something changes in source and urls stops working and remigrating is required and you have a lot of mangas this takes a lot of time and is error prone to what is remigrate and what is not.
What would be nice is to make it possible to refresh manga without doing it one by one. 
Connected issue https://github.com/tachiyomiorg/tachiyomi-extensions/issues/12969

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-08-14 12:42
Duplicate of #1729

**Closed** 2022-08-14 12:42 UTC
Labels: Feature request
