### ISSUE TITLE
[Bug] Android status bar (notification bar) doesn't disappear when opening chapter

### ISSUE THREAD

**Issue by Zero-G-Sys** [tachiyomiorg/tachiyomi#4749] opened 2021-03-31 02:04 UTC
## Device information
* Tachiyomi version: Nightly 0.10.9-3185
* Android version: 7.0
* Device: Samsung 7 Edge

## Steps to reproduce
1. Open any chapter
2. Alternately switch to another app then back to Tachiyomi what it is still reading a chapter.

### Expected behavior
Status bar (notification bar) should be hidden and reading should be in full screen mode.

### Actual behavior
When opening a chapter it goes to full screen mode, but Status bar (notification bar) is still visible.

## Other details
- Can hide the Status bar (notification bar) by tapping in the middle of the screen to show controls, and tapping again to hide them.
- This started happening on the last update, previous one didn't have this behavior.

No crashes

**Comment by scb261** [comment] 2021-03-31 02:07
Duplicate of #4723 (fixed for the next release)

**Comment by Zero-G-Sys** [comment] 2021-03-31 02:12
Ah, sorry, I did search for an open issue, forgot to search for in the closed ones.

**Closed** 2021-03-31 02:13 UTC
Labels: bug
