### ISSUE TITLE
[Feature Request] Subcategories

### ISSUE THREAD

**Issue by TMD44** [tachiyomiorg/tachiyomi#4164] opened 2020-12-20 17:21 UTC
## Why/User Benefit/User Problem
It would be a very handy feature if we could make subcategories under the normal categories. If there are a lot of manga in one category that could be really chaotic and this feature can solve this issue.

## What/Requirements
In the category add page, we could add not just the name, but if i want to make a subcategory, i have to choose the parent category. The naming convention could be like: Main Category/Subcategory
Gmail has a same solution with labels.
![hqdefault](https://user-images.githubusercontent.com/39030834/102719734-021d7000-42f0-11eb-9015-51967398d867.jpg)

**Comment by Sam-Oak** [comment] 2020-12-20 17:26
duplicate of #1803

**Closed** 2020-12-20 17:35 UTC
Labels: feature
