### ISSUE TITLE
Suggestions for local source

### ISSUE THREAD

**Issue by 12ohit** [tachiyomiorg/tachiyomi#7270] opened 2022-06-08 07:05 UTC
### Describe your suggested feature

* Local source should refresh every time you open Tachiyomi and remove it from Global or automatic update as every time you open the app it's gonna be up to date. Keep the pull down to refresh option for it though.
* Add a delete option inside the app to delete chapters from your phone's storage.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [x] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by BhaturaGuy** [comment] 2022-06-09 07:23
I second this

**Comment by arkon** [comment] 2022-12-05 20:19
1. It's far simpler to have similar behaviour between local and non-local sources.
2. Duplicate of #7178

**Closed by arkon** 2022-12-05 20:19 UTC
Labels: Feature request
