### ISSUE TITLE
[Feature Request] Manga/comic folders for library page

### ISSUE THREAD

**Issue by CommicKick69ing** [tachiyomiorg/tachiyomi#8195] opened 2022-10-14 04:42 UTC
### Why and how this would befit user
Because of the big list of manga and comics and I am reading or am planning on reading it can get hard to sort through my library page.

So I am suggesting a feature for the library page in which you can create custom named folder and place which place as manga and comics in folder as need be.

The manga and comic not in a folder will still remain visible in the library page, but the comics and manga that are stored in a folder will require you to tap a folder icon which will open a separate page which only features the manga and comics stored in that folder

**_Image Mock ups_**

![Screenshot_20221014-001156](https://user-images.githubusercontent.com/40266764/195763645-b25fe8e1-a89c-451e-865f-ddbb00868561.png)
![Screenshot_20221013-235532](https://user-images.githubusercontent.com/40266764/195763640-bde57559-49c2-48ab-af77-7fd3b3f36ba9.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by mobi2002** [comment] 2022-10-14 04:45
Duplicate of #1803

**Closed** 2022-10-14 04:53 UTC
Labels: Feature request
