### ISSUE TITLE
[Bug] New chapters in MangaDex show in WebView, but not in app, even when refreshing page.

### ISSUE THREAD

**Issue by Weifarers** [tachiyomiorg/tachiyomi#4411] opened 2021-02-08 15:33 UTC
## Device information
* Tachiyomi version: Stable 0.10.8
* Android version: 11
* Device: Google Pixel 3

## Steps to reproduce
1. Open up manga in Tachiyomi app (example is attached).
2. Open up WebView for manga via the page, and see a new chapter.
3. Go back to the manga in the app, and refresh the app to pull new chapters.

### Expected behavior
It should update the app's page with the new chapters from the WebView. This is a behavior that used to work. 

### Actual behavior
It doesn't update, and when refreshing my library and checking for updates, they won't show up.

## Other details
Example attached. Last update on the app page is from November 27th, 2020, but the latest chapter is from 2 days ago as of posting this issue. This is occurs for almost all manga from the MangaDex source.
![148658940_2028122560662826_810822745212071709_n](https://user-images.githubusercontent.com/44651538/107240355-6fe04100-69ef-11eb-8611-c87ce8223c87.png)
![147701679_133428788629219_9022403833826011023_n](https://user-images.githubusercontent.com/44651538/107240361-71aa0480-69ef-11eb-8da5-f3edfd2482e5.png)

Similar to Issue #4382 although I don't download chapters onto my phone.

**Comment by scb261** [comment] 2021-02-08 15:35
Wrong repo and duplicate of tachiyomiorg/tachiyomi-extensions#5627

**Closed** 2021-02-08 15:35 UTC
Labels: bug
