### ISSUE TITLE
Toggleable "Unread chapters number" badge

### ISSUE THREAD

**Issue by Xorio71** [tachiyomiorg/tachiyomi#10283] opened 2024-01-02 22:28 UTC
### Describe your suggested feature

Make it so the little badge that displays the number of unread chapters in a manga is toggleable. 

### Other details

You could add the toggle in the "Display" section.

![Screenshot_20240103-002732](https://github.com/tachiyomiorg/tachiyomi/assets/101265862/01d8c6c3-3e14-44a3-a087-f37ccbc23584)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by BrutuZ** [comment] 2024-01-02 22:38
Duplicate of #9418

**Closed** 2024-01-02 22:38 UTC
Labels: Feature request
