### ISSUE TITLE
Option to Hide a Category or protect it with password 

### ISSUE THREAD

**Issue by hamdyahmed18** [tachiyomiorg/tachiyomi#9776] opened 2023-07-29 23:48 UTC
### Describe your suggested feature

It should hide a specific category from my library and require me to enter a password to unhide it. 

The most important step is to hide a category from the library. The password is not necessary. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-07-29 23:49
Duplicate of #1508

**Closed by arkon** 2023-07-29 23:49 UTC
Labels: Feature request
