### ISSUE TITLE
[Bug] 'Show Navigation layout overlay' doesn't fade away like 'Show Reading mode'

### ISSUE THREAD

**Issue by curche** [tachiyomiorg/tachiyomi#4737] opened 2021-03-29 14:12 UTC
## Device information
* Tachiyomi version: Sy Preview r348
* Android version: 10 (Lineage OS)
* Device: Redmi 7 onclite

## Steps to reproduce
1. Enable 'Show Navigation layout overlay' and 'Show Reading mode' in Reader settings
2. Try to open any chapter

### Expected behavior
Reading Mode and Nav layout overlay shows up, and then fades away

### Actual behavior
Reading Mode fades away
Nav layout overlay doesnt fade away unless user taps on it (makes #4736 even worse)

## Other details
Video attached

https://user-images.githubusercontent.com/72807749/112848552-d4517f80-90c5-11eb-8bd8-4a7d0975d0e3.mov

**Comment by CarlosEsco** [comment] 2021-03-29 14:16
Same as other you verified it is broken on main app?

**Comment by ghostbear** [comment] 2021-03-29 14:19
It was designed to make the user tap the screen to make it fade away

**Comment by curche** [comment] 2021-03-29 14:25
> Same as other you verified it is broken on main app?

checked in r3185. bug exists there also

> It was designed to make the user tap the screen to make it fade away

oh I thought it was like the 'Show Reading mode' setting. 
its fine if it is like that since after #4736 is fixed, it should be alright

**Comment by arkon** [comment] 2021-03-30 21:59
Closing since it's intentional.

**Closed by arkon** 2021-03-30 21:59 UTC
Labels: bug
