### ISSUE TITLE
[Feature Request] <How about adding manual refreshing?>

### ISSUE THREAD

**Issue by DanielBryan05** [tachiyomiorg/tachiyomi#5418] opened 2021-06-18 12:53 UTC
## Why/User Benefit/User Problem
My problem here is I noticed that whenever I refresh my library it takes a while longer to get my updated series 

## What/Requirements
We all know there is this thing called "Categories" which basically seperates the selected mangas,manhwas and manhuas to different sections. What manual refreshing do is by double tapping or the long swipe down(google like feature whenever we refresh something, we always swipe down until the refresh loading logo appears) Then it only refreshes the selected category. 
Like there is a seperate button for refresh all and manual refresh. 
It will be very efficient and reduce the loading time of the updates of the mangas that are selected by manual refresh button

**Comment by arkon** [comment] 2021-06-18 13:05
Duplicate of #4060

**Closed by arkon** 2021-06-18 13:05 UTC
Labels: feature
