### ISSUE TITLE
Switching category tabs makes them jitter when making a global update

### ISSUE THREAD

**Issue by KasaiDot** [tachiyomiorg/tachiyomi#7283] opened 2022-06-11 11:19 UTC
### Steps to reproduce

1. Stop Tachiyomi
2. Clear the cache
3. Restart Tachiyomi
4. Make a global update
5. Try to switch from one category to another (requires the "category tabs" switch to be "on" on the display settings)

### Expected behavior

This shouldn't happen, the category tabs shouldn't jitter.

### Actual behavior

The category tabs are jittering when making a global update.

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/8883732/tachiyomi_crash_logs.txt)

_they may be a bit old_

### Tachiyomi version

0.13.4-4446

### Android version

Android 12

### Device

Samsung Galaxy S21+ 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by KasaiDot** [comment] 2022-06-11 11:20
https://user-images.githubusercontent.com/8779667/173185702-bd79796a-f88f-4a5b-8628-7adb1caf6976.mp4

A recording, for demo purposes.

**Comment by arkon** [comment] 2022-07-10 03:36
Duplicate of #5064

**Closed by arkon** 2022-07-10 03:36 UTC
Labels: Bug
