### ISSUE TITLE
Add drop-down to updates tab for each new updates

### ISSUE THREAD

**Issue by heartlog** [tachiyomiorg/tachiyomi#9547] opened 2023-05-27 01:59 UTC
### Describe your suggested feature

Tachiyomi slows down if we `view updates tab`, with massive about of chapter updates of various manga.
Ex. This time a manga source gave me around 1000 new chapter updates, and after opening chapter tab it was mess !!

If chapter updates are wrapped in drop-down list for individual manga, it'll be easy and convenient for navigation in updates tab.

### Other details

![somethinglikethis?](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRb6GglsaSE09vMRKa-XfdSH4Cm8Q8x2kHYKA&usqp=CAU)
---

> drop-down list = (manga name)
>> Chapter 8
....
>> Chapter 1087

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-05-27 02:28
Duplicate of #2774

**Closed by arkon** 2023-05-27 02:28 UTC
Labels: Feature request
