### ISSUE TITLE
Crash if I open the "Browse" tab

### ISSUE THREAD

**Issue by alan-ford** [tachiyomiorg/tachiyomi#8420] opened 2022-11-02 10:26 UTC
### Steps to reproduce

1. Open Tachiyomi;
2. Open the "Browse" tab.

### Expected behavior

When I open the "Browse" tab, I expect to be able to see the list of extensions and update the obsolete ones.

### Actual behavior

If I open the "Browse" tab, the app closes.

### Crash logs

11-02 14:01:29.584  9955  9955 E ResourceType: Style contains key with bad entry: 0x01010604
11-02 14:01:29.584  9955  9955 E ResourceType: Style contains key with bad entry: 0x01010605
11-02 14:01:30.424  9955 10108 E SQLiteLog: (284) automatic index on C(manga_id)
11-02 14:01:30.424  9955 10108 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.14.2 (standard, 3222247, 91, 2022-10-31T21:42Z)
Android version: 7.1.2 (SDK 25)
Android build ID: lineage_ford-userdebug 7.1.2 NJH47F 827eae1c53 test-keys
Device brand: google
Device manufacturer: amzn
Device name: ford
Device model: Fire
Device product name: lineage_ford

### Tachiyomi version

0.14.2

### Android version

Android 7.1.2

### Device

Amazon Fire 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by BangtanExo27** [comment] 2022-11-12 08:13
It's almost the same for me, but not just when I browse, it also happens when I am reading chapters or scrolling through my library.

**Comment by DrD1sconnect** [comment] 2022-11-18 13:00
I have the same problem. As soon as I open the BROWSE tab it loads it but then immediately crashes afterwards.
)

**Comment by arkon** [comment] 2022-11-24 03:39
Duplicate of #8509

**Closed by arkon** 2022-11-24 03:39 UTC
Labels: Bug
