### ISSUE TITLE
Requesting auto scroll button

### ISSUE THREAD

**Issue by stonerockz11111** [tachiyomiorg/tachiyomi#5537] opened 2021-07-12 08:29 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

Something manga contains 10000+ images so its difficult to scroll by hand so an auto scroll feature is useful it should also comes with on or off switch with hide button ( must necessary) plus like speed control features 
![sketch-1626078199804](https://user-images.githubusercontent.com/79789462/125255663-49fdf600-e319-11eb-8e15-7ba80825699d.jpg)
||Above image is only and only for reference purposes||

**Comment by zayin02** [comment] 2021-07-12 09:44
Duplicate of #2093

**Closed** 2021-07-12 11:49 UTC
Labels: Feature request
