### ISSUE TITLE
Tachiyomi Force Closed when on the last page of chapter (after press "back")

### ISSUE THREAD

**Issue by nurananto** [tachiyomiorg/tachiyomi#9830] opened 2023-08-10 11:47 UTC
### Steps to reproduce

Open tachiyomi
Read till the last page of chapter

If still have chapter after that -- between chapter tachiyomi crash
when u on last chapter then press back to see main description page of manga/manhua/manhwa / library ---- tachiyomi crash.

### Expected behavior

read to the next chapter or see library or manga/manhwa/manhua description page.

### Actual behavior

tachiyomi forced closed

### Crash logs

https://drive.google.com/file/d/11LpNTveLDPWdDnBoAUqAhCcNjbmJ1mgt/view?usp=drivesdk
Log from mat log

### Tachiyomi version

Preview r6003

### Android version

Android 13 Miui 14

### Device

Redmi Yunluo

### Other details

Crash Video : https://photos.app.goo.gl/f3jZfiB4WcGhGkQs9

App version: 0.14.6-6003 (standard, 627f07408, 104, 2023-08-05T21:08Z)
Android version: 13 (SDK 33)
Android build ID: TP1A.220624.014
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: yunluo
Device model: 22081283G
Device product name: yunluo_id

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment] 2023-08-13 07:30
```
08-10 18:35:23.002 E/ACRA    (32723): ACRA caught a NullPointerException for eu.kanade.tachiyomi.debug
08-10 18:35:23.002 E/ACRA    (32723): java.lang.NullPointerException
08-10 18:35:23.002 E/ACRA    (32723): 	at tachiyomi.view.UpdatesViewQueries$getUpdatesByReadStatus$1.invoke(SourceFile:19)
08-10 18:35:23.002 E/ACRA    (32723): 	at app.cash.sqldelight.async.coroutines.QueryExtensionsKt$awaitAsList$2.invoke(SourceFile:9)
08-10 18:35:23.002 E/ACRA    (32723): 	at app.cash.sqldelight.async.coroutines.QueryExtensionsKt$awaitAsList$2.invoke(SourceFile:23)
08-10 18:35:23.002 E/ACRA    (32723): 	at app.cash.sqldelight.driver.android.AndroidQuery.executeQuery(SourceFile:17)
08-10 18:35:23.002 E/ACRA    (32723): 	at app.cash.sqldelight.driver.android.AndroidSqliteDriver$executeQuery$2.invoke(SourceFile:10)
08-10 18:35:23.002 E/ACRA    (32723): 	at app.cash.sqldelight.driver.android.AndroidSqliteDriver.execute-zeHU3Mk(SourceFile:27)
08-10 18:35:23.002 E/ACRA    (32723): 	at app.cash.sqldelight.driver.android.AndroidSqliteDriver.executeQuery(SourceFile:21)
08-10 18:35:23.002 E/ACRA    (32723): 	at tachiyomi.view.UpdatesViewQueries$GetUpdatesByReadStatusQuery.execute(SourceFile:31)
08-10 18:35:23.002 E/ACRA    (32723): 	at app.cash.sqldelight.async.coroutines.QueryExtensionsKt.awaitAsList(SourceFile:7)
08-10 18:35:23.002 E/ACRA    (32723): 	at app.cash.sqldelight.coroutines.FlowQuery$mapToList$1$1.invokeSuspend(SourceFile:29)
08-10 18:35:23.002 E/ACRA    (32723): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:12)
08-10 18:35:23.002 E/ACRA    (32723): 	at kotlinx.coroutines.DispatchedTask.run(SourceFile:112)
08-10 18:35:23.002 E/ACRA    (32723): 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(SourceFile:4)
08-10 18:35:23.002 E/ACRA    (32723): 	at kotlinx.coroutines.scheduling.TaskImpl.run(SourceFile:3)
08-10 18:35:23.002 E/ACRA    (32723): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(SourceFile:1)
08-10 18:35:23.002 E/ACRA    (32723): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:63)
08-10 18:35:23.002 E/ACRA    (32723): 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@49a4192,
```

**Comment by AntsyLich** [comment] 2023-08-13 07:32
Duplicate of #9704

**Closed by AntsyLich** 2023-08-13 07:32 UTC
Labels: Bug
