### ISSUE TITLE
Allow multiple choice of the manga 

### ISSUE THREAD

**Issue by Amr-Salah11** [tachiyomiorg/tachiyomi#6899] opened 2022-04-10 23:39 UTC
### Describe your suggested feature

I use Gmanga site and this site upload many versions or subtitles of chapters of a manga and on the site i can choose freely which version or subtitles to read . But when I use the extension of the site in your app i can't choose which version or subtitles to read , and it's only showing the first uploaded one to read but the rest subtitles are not . So please add the option of several subtitles and not the first version . if this feature on your app tell me how to use it

### Other details

![Screenshot_20220411-012901_Chrome](https://user-images.githubusercontent.com/103391403/162644673-31f05fdf-bdd9-439a-9d97-be9963773c99.jpg)

https://gmanga.org/mangas/8587/berserk
![Uploading Screenshot_20220411-012908_Chrome.jpg…]()

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-04-10 23:41
Duplicate of #969

**Closed by alessandrojean** 2022-04-10 23:41 UTC
Labels: Feature request
