### ISSUE TITLE
[Bug] <download queue keep pausing itself>

### ISSUE THREAD

**Issue by desmondk91** [tachiyomiorg/tachiyomi#4287] opened 2021-01-13 03:12 UTC
## Device information
* Tachiyomi version: stable 0.10.7
* Android version: 11
* Device: samsung galaxy note 10

## Steps to reproduce
1. Choose a brand new manga
2. Download all

### Expected behavior
The download queue will keep on download until it is finish.

### Actual behavior
The download will be pause automatically after a minute or 2. I will have to resume it manually and it will be pausing it again after a minute or 2.

**Comment by arkon** [comment] 2021-01-16 16:00
Duplicate of #959

**Closed by arkon** 2021-01-16 16:00 UTC
Labels: bug
