### ISSUE TITLE
Group bulk manga chapters update and show updates only for the past (n)th days feature

### ISSUE THREAD

**Issue by tsunaliew** [tachiyomiorg/tachiyomi#8685] opened 2022-12-06 01:34 UTC
### Describe your suggested feature

1. To group new updates of same manga from the same source in update page.
2. Options to only show update history on update page for (n)th amount of days (can be configured in settings).

### Other details

1. Sometime manga from certain source have 100 or more new chapters updated (even though it was previously released), the update page will be flooded by all the new chapters. 

2. Update page has history that can be track back to few years back.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-03-01 14:10
Duplicate of #2774

**Closed by arkon** 2023-03-01 14:10 UTC
Labels: Feature request
