### ISSUE TITLE
Improve MD3 navbar icon colours

### ISSUE THREAD

**Issue by CrepeTF** [tachiyomiorg/tachiyomi#6231] opened 2021-11-14 08:16 UTC
### Describe your suggested feature

Currently the colour for selected icons in the navbar are either are some kind of off-white colour for dark theme, and a really dark gray for white theme.

This can make the icons have bad visibility and just don't match what Google is doing.

Google Clock:
![Screenshot_20211114-075705__01](https://user-images.githubusercontent.com/70870719/141673175-59bb31cf-f2a8-4fdd-9b8e-ac577dc5c1ac.jpg)

Google Photos (Dark):
![Screenshot_20211114-080012__01](https://user-images.githubusercontent.com/70870719/141673185-c304b85e-517a-4dca-a5df-1b3322dff961.jpg)

Google Photos (Light):
![Screenshot_20211114-080029__01](https://user-images.githubusercontent.com/70870719/141673216-699cd62b-12af-462a-a6c9-35535a8927e2.jpg)

### Other details

FYI, here's some eyebleach :^) :
![Screenshot_20211114-081602](https://user-images.githubusercontent.com/70870719/141673238-c61d31b3-224b-419d-a5ab-92f33b9106a1.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Soitora** [comment] 2021-11-14 11:06
I do quite enjoy their selected color being based on a light version of the background

**Comment by arkon** [comment] 2021-11-14 15:22
Duplicate of #6229

**Closed by arkon** 2021-11-14 15:22 UTC
Labels: Feature request
