### ISSUE TITLE
Manga fixed

### ISSUE THREAD

**Issue by MrCryzza** [tachiyomiorg/tachiyomi#8608] opened 2022-11-24 00:28 UTC
### Describe your suggested feature

You can put the manga you are current reading fixed in the top of the list in the library. This will be very helpful.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment] 2022-11-24 01:15
Duplicate of #3656

**Closed by loocool2** 2022-11-24 01:15 UTC
Labels: Feature request
