### ISSUE TITLE
[Feature Request] Add multiple manga into category

### ISSUE THREAD

**Issue by NotRel** [tachiyomiorg/tachiyomi#4414] opened 2021-02-08 22:48 UTC
Lets say i imported (locally) 100 different kind of manga i.e. action, comedy, drama, etc... there is no convenient way to add each of them to its appropriate category. A simple soultion would be adding 'multiple selection' functionality (Same selection mechanism as on the library page) preferably hold and select mechanism for faster selection.

* I already checked most alternatives, but none of them has this feature.

**Comment by CrepeTF** [comment] 2021-02-08 22:56
As a workaround you could make a category which you can automatically add to from browse and sort them all with multi-select and set category.
![Screenshot_20210208-225414.jpg](https://user-images.githubusercontent.com/70870719/107291930-dd788580-6a60-11eb-9077-075609990716.jpg)

**Comment by scb261** [comment] 2021-02-08 22:57
Duplicate of #829

**Closed** 2021-02-08 22:59 UTC
Labels: feature
