### ISSUE TITLE
[Feature Request] <𝕊ℙ𝔼ℂ𝕀𝔽𝕀ℂ Settings for 𝙤𝙧𝙞𝙚𝙣𝙩𝙖𝙩𝙞𝙤𝙣 𝕡𝕖𝕣 𝙢𝙖𝙣𝙜𝙖 >

### ISSUE THREAD

**Issue by Unnnordinary** [tachiyomiorg/tachiyomi#4554] opened 2021-02-27 17:19 UTC
May I request to have a feature to have 𝗦𝗽𝗲𝗰𝗶𝗳𝗶𝗰 𝘀𝗲𝘁𝘁𝗶𝗻𝗴𝘀 for orientation 𝗽𝗲𝗿 manga. For example, I want to read manga in 𝗙𝗼𝗿𝗰𝗲𝗱 𝗹𝗮𝗻𝗱𝘀𝗰𝗮𝗽𝗲 𝗺𝗼𝗱𝗲 and Webtoon in 𝗽𝗼𝗿𝘁𝗿𝗮𝗶𝘁 𝗺𝗼𝗱𝗲. I see that you can change orientation when you start reading the manga but when you change that, It is applied to global settings, what I request is for it to be applied for the specific opened manga.
Thank you!

![IMG_20210228_014057](https://user-images.githubusercontent.com/79761416/109395188-0906d580-7966-11eb-8b86-ce6c634210bf.jpg)

**Comment by scb261** [comment] 2021-02-27 17:43
Duplicate of #452

**Comment by Unnnordinary** [comment] 2021-02-27 17:51
> Duplicate of #452

Not yet implemented or made?

**Closed** 2021-02-27 17:50 UTC
Labels: feature
