### ISSUE TITLE
Manga not deleting properly

### ISSUE THREAD

**Issue by Xellerate005** [tachiyomiorg/tachiyomi#5550] opened 2021-07-14 14:15 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 11

### Device

Samsung Galaxy A20e

### Steps to reproduce

1. First either download a manga with a lot of chapters (in the hundreds), or if you already have one go to step 2
2. Then try deleting those chapters and exit back into the library

### Expected behavior

What should happen is that when you exit to library with the filter to show downloaded option turned on, the manga with the deleted chapters wouldn't be shown

### Actual behavior

When you exit to the library,  the manga is still being shown and when you click it the chapters that you have just deleted have suddenly re appeared,  it usually for me takes about 10 possibly more attempts of deleting the chapters for the manga to get deleted

### Other details

Each picture is the steps followed in chronological order, the download filter in enabled  
![Screenshot_20210714-151256_Tachiyomi](https://user-images.githubusercontent.com/63415563/125637236-51206a73-76f1-45b8-b613-46b0a46777ff.jpg)
![Screenshot_20210714-151308_Tachiyomi](https://user-images.githubusercontent.com/63415563/125637266-1faebe9a-4de5-47ac-aaaa-9ece063e3b9f.jpg)
![Screenshot_20210714-151314_Tachiyomi](https://user-images.githubusercontent.com/63415563/125637294-ce80b15d-d59f-4589-a2ea-ab7cf417fa9c.jpg)
![Screenshot_20210714-151322_Tachiyomi](https://user-images.githubusercontent.com/63415563/125637317-f1741913-82b7-43f0-959c-8be89d041373.jpg)

**Comment by arkon** [comment] 2021-07-14 14:23
Duplicate of #4286

**Closed by arkon** 2021-07-14 14:23 UTC
Labels: Bug
