### ISSUE TITLE
Terrible transition animation performance in 0.14.1

### ISSUE THREAD

**Issue by GGG-KILLER** [tachiyomiorg/tachiyomi#8352] opened 2022-10-30 05:39 UTC
### Steps to reproduce

1. Open any manga chapter.
2. Start reading through it.
3. Realize page transitions stop working entirely.

Same happens for category transitions in the library, albeit it doesn't stop for over a full second as in the manga reader.

### Expected behavior

Page transitions work just fine as they did in pre-0.14.0

### Actual behavior

Page transitions stop midway as can be seen in the video:
[Screencast from 2022-10-30 02-35-08.webm](https://user-images.githubusercontent.com/5892127/198864207-b93def35-0968-4501-8496-c8a42e61fd48.webm)

### Tachiyomi version

0.14.1

### Android version

Android 11 (LineageOS)

### Device

Redmi Note 8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by GGG-KILLER** [comment] 2022-10-30 06:08
Disabling page transition animations and using the tap regions does not solve this issue.

**Comment by THElegend5** [comment] 2022-10-30 06:24
Duplicate of #8296.

**Closed** 2022-10-30 06:37 UTC
Labels: Bug
