### ISSUE TITLE
[Feature Request] <Add a way to not show Mangas when browsing, which are already in the library>

### ISSUE THREAD

**Issue by pnisi** [tachiyomiorg/tachiyomi#4583] opened 2021-03-03 14:34 UTC
## Why/User Benefit/User Problem
(explain why this feature should be added)
The benefit is, that you can unclutter your search in a source. It may not be the biggest problem, if you only have a few mangas in your library, however if you add a lot or if you use it for a long time, then you can add quite the number of mangas to your library. These mangas however are all shown, when you browse a source, making it so, that you need to work through these, if you want to find some new mangas. In the most basic searches, where you search for the latest releases or where you filter a language, you will not need this, however if you filter for specific Genres and Themes it can get pretty annoying. For example take the Isekai genre. If you have a decent number of the best (best rated or most viewed) in your library, then it can get as bad as half of the mangas already being in your library. All of them you dont care about in your search, since you already have them in your library. In short this feature would improve the ability to find new mangas.

## What/Requirements
(explain how this feature would behave)
There are multiple ways to implement this feature, you could add it as a checkmark in the filter when browsing or you could make it a setting (I think, that this here is the most appropriate place, under the browsing category). I know, that filter stuff is normally something, which needs to be done by the extensions, since the sources are just that different and for example the data on what series has what genres comes from them, however I believe, that this can be done without too big of an impact on the extensions. 
As it is now, you can go into any source, pick out a manga and there you can add it to your library in whatever categories you want. This feature would just make it so, that when using browse you can decide, if mangas, which are already in your library should still be displayed. 

Also I just realised, that this function has already been implemented halfway. In a source mangas you have in your libray are already greyed out. This means, that there is already a way, for a source to know, which mangas are in your library. Now there is only the need to implement a way to completely filter these out. Since ways to filter already exist in the library and the extensions there is only a need to correctly apply it here.

**Comment by Seishirou101** [comment] 2021-03-03 14:36
duplicate of #2941

**Closed** 2021-03-03 15:01 UTC
Labels: feature
