### ISSUE TITLE
[Feature Request] Default reading mode for categories

### ISSUE THREAD

**Issue by keyjeyelpi** [tachiyomiorg/tachiyomi#5331] opened 2021-06-07 03:04 UTC
## Why/User Benefit/User Problem
Since there is no automatic categorization of mangas and webtoons, I think that most users do the same thing as I do, which is categorize them manually. Once I've set a category to a certain reading mode, I'd have to manually set each series again if I want to change their reading mode.

## What/Requirements
Go into categories, long press a category and select edit. Underneath the rename textbox, there should be a dropdown list of the reading modes available.

**Comment by loocool2** [comment] 2021-06-07 03:05
Duplicate of #2518

**Closed by loocool2** 2021-06-07 03:05 UTC
Labels: feature
