### ISSUE TITLE
Add an option to choose page-ui style.

### ISSUE THREAD

**Issue by specterzxl** [tachiyomiorg/tachiyomi#5736] opened 2021-08-17 07:30 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

Add an option in the theme/ui/general settings to revert to the old page-style.

![Screenshot_2021-08-17-07-44-47-235_eu kanade tachiyomi](https://user-images.githubusercontent.com/12276160/129682624-739e7f4b-6745-4026-8cda-7e376b003f06.jpg)

Above is a picture of the new ui, and below is what I think should be added as an optional alternative.

![tmp](https://user-images.githubusercontent.com/12276160/129682731-5fd1f10c-193b-4f98-a9ed-c8d180cdd4c5.jpg)

(Excuse the light theme, not my screenshot.) This ui was much more pleasing to the eye and less intrusive in my opinion so I'd love to see an option to use it.

The "old ui" (the light mode sc) also had the "retry" etc buttons as just text with no gray border boxes around them. It'd be nice to see that incorporated too.

**Comment by arkon** [comment] 2021-08-17 12:00
Duplicate of #5518

**Closed by arkon** 2021-08-17 12:00 UTC
Labels: Feature request

**Comment by specterzxl** [comment] 2021-08-18 00:27
> Duplicate of #5518

This is not in any way related to that. This is simply a preference thing - a FEATURE request. Its not a straight up bug like #5518.

**Comment by arkon** [comment] 2021-08-18 01:06
Oh, you meant the toolbars.

Then no.

**Comment by specterzxl** [comment] 2021-08-18 02:10
Sorry, I didn't realise it would cost an arm and a leg to re-add a previous feature as an option.

I'll go back to enjoying frivolous ui updates that decrease the overall quality of apps now.

**Comment by arkon** [comment] 2021-08-18 02:20
I'd recommend checking out the TachiyomiAZ fork if you're interested in the feature of old UIs.
