### ISSUE TITLE
Add delay between entry update

### ISSUE THREAD

**Issue by RuiMarquesCardona** [tachiyomiorg/tachiyomi#9513] opened 2023-05-17 22:37 UTC
### Describe your suggested feature

Add an option to set a delay between each entry checks so that mass updates don't get skipped due to servers not responding as is the case with MangaKatana extension. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-05-17 22:40
Duplicate of #6968

**Closed** 2023-05-17 22:41 UTC
Labels: Duplicate, Feature request
