### ISSUE TITLE
weird skipping of pages in webtoon format

### ISSUE THREAD

**Issue by NotPageD** [tachiyomiorg/tachiyomi#6300] opened 2021-12-01 13:30 UTC
### Steps to reproduce

1.read any series that has webtoon format
2.scroll down

### Expected behavior

it should work normally without skipping

### Actual behavior

it does a weird skip of one or two pages and when i scroll back up it either prevents me from scrolling up or it skips again but this time to the beginning of the previous chapter or the one you're reading. 

### Tachiyomi version

tachiyomisy preview r414

### Android version

android 8

### Device

Samsung

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2021-12-04 15:01
Duplicate of #3279

**Closed by arkon** 2021-12-04 15:01 UTC
Labels: Bug
