### ISSUE TITLE
A downloaded chapter deleted in source, making it unable to be deleted from device

### ISSUE THREAD

**Issue by Luke-Grim** [tachiyomiorg/tachiyomi#9849] opened 2023-08-15 21:34 UTC
### Steps to reproduce

1: download a chapter
2: it gets deleted from the source
3: do the chapter update check thing
4: chapter that was deleted from source gets hidden, and is thus unable to be deleted

### Expected behavior

automatically delete downloaded chapter if deleted in source

### Actual behavior

preview in library showing 3 chapters downloaded
![juxrKJydRQy__8uS_lf9mg](https://github.com/tachiyomiorg/tachiyomi/assets/121507767/b012fb6c-c9f8-434c-a280-d0c65deb9424)

sorted by downloaded, only 1 chapter is shown, making hidden chapter unable to be deleted
![jiRhyOZZS2WfjaoQVA8WMg](https://github.com/tachiyomiorg/tachiyomi/assets/121507767/495a36aa-2495-42b6-832f-2f9f224be02c)

### Tachiyomi version

0.14.6

### Android version

Android 11

### Device

Fire HD 8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-08-15 21:39
Duplicate of #2108

**Closed** 2023-08-15 21:39 UTC
Labels: Bug, Duplicate
