### ISSUE TITLE
[Feature Request] Add toggle to disable double tap zoom

### ISSUE THREAD

**Issue by Myuki** [tachiyomiorg/tachiyomi#4970] opened 2021-04-27 14:13 UTC
## Why/User Benefit/User Problem
Disable double touch zoom can reduce some palm rejection. And most other comic readers like Perfect Viewer are support to disable this function.

**Comment by benji009** [comment] 2021-04-29 21:13
Yes, i second this. I tap quite fast through manga by scrolling down.. so i always accidently triggering the zoom function.

**Comment by kigiri** [comment] 2021-07-15 15:11
Yes, as I don't use it, I would also like to be able to skip pages faster and avoid accidental zooms

**Comment by arkon** [comment] 2022-05-26 02:36
Duplicate of #4145

**Closed by arkon** 2022-05-26 02:36 UTC
Labels: Feature request
