### ISSUE TITLE
add a button for update all Extensions which need to update by one tap

### ISSUE THREAD

**Issue by cyb233** [tachiyomiorg/tachiyomi#5532] opened 2021-07-11 23:49 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

add a button for update all Extensions which need to update by one tap

### Other details

I tried to search "update" in issue but it return 1/3 of all issue, so if it is a duplicate issue, please close it

**Comment by arkon** [comment] 2021-07-11 23:52
Duplicate of #4815

**Closed by arkon** 2021-07-11 23:52 UTC
Labels: Feature request
