### ISSUE TITLE
After initiating search in pinned only mode in global search changing to all doesn't change to all source

### ISSUE THREAD

**Issue by mozzaru** [tachiyomiorg/tachiyomi#9735] opened 2023-07-18 08:09 UTC
### Steps to reproduce

.

### Expected behavior

search global not work from  References

### Actual behavior

.
![Screenshot_2023-07-18-15-06-46-32_79aa9bf7c61e266c5f841e42245e214b](https://github.com/tachiyomiorg/tachiyomi/assets/100791931/60240f13-84b1-4c46-9710-166264939413)

### Tachiyomi version

r5933

### Android version

Android 11

### Device

Realme 7i

### Other details

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by mozzaru** [comment] 2023-07-18 08:21
Uploading Record_2023-07-18-15-20-41.mp4…

**Comment by AntsyLich** [comment] 2023-07-18 08:22
Wait for it to upload first

**Comment by mozzaru** [comment] 2023-07-18 08:39
![IMG_20230718_153447](https://github.com/tachiyomiorg/tachiyomi/assets/100791931/d04b06f3-215c-49fd-92aa-19d8fa95b132)
![IMG_20230718_153534](https://github.com/tachiyomiorg/tachiyomi/assets/100791931/560b4347-6d6f-4a02-9d8c-c8a0367aef80)

**Comment by AntsyLich** [comment] 2023-07-18 08:54
/edit-title "After initiating search in pinned only mode in global search changing to all doesn't change to all source"

**Comment by arkon** [comment] 2023-07-18 11:22
Duplicate of #9724

**Closed** 2023-07-18 11:22 UTC
Labels: Bug, Duplicate
