### ISSUE TITLE
crash at update library

### ISSUE THREAD

**Issue by infiku** [tachiyomiorg/tachiyomi#9602] opened 2023-06-11 08:57 UTC
### Steps to reproduce

Step to produce 
1. Open tachiyomi
2. Update global library

### Expected behavior

Library update

### Actual behavior

Crash

### Crash logs

--------- beginning of main
06-11 17:53:20.404 12704 12902 E CursorWindow: Failed to read row 2581, column 0 from a CursorWindow which has 2581 rows, 14 columns.
06-11 17:53:20.407 12704 12704 E ACRA    : ACRA caught a NullPointerException for eu.kanade.tachiyomi
06-11 17:53:20.407 12704 12704 E ACRA    : java.lang.NullPointerException
06-11 17:53:20.407 12704 12704 E ACRA    : 	at tachiyomi.data.data.UpdatesViewQueriesImpl$updates$1.invoke(DatabaseImpl.kt:19)
06-11 17:53:20.407 12704 12704 E ACRA    : 	at com.squareup.sqldelight.Query.executeAsList(Query.kt:18)
06-11 17:53:20.407 12704 12704 E ACRA    : 	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToList$1$1.invokeSuspend(FlowExtensions.kt:6)
06-11 17:53:20.407 12704 12704 E ACRA    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
06-11 17:53:20.407 12704 12704 E ACRA    : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
06-11 17:53:20.407 12704 12704 E ACRA    : 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
06-11 17:53:20.407 12704 12704 E ACRA    : 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
06-11 17:53:20.407 12704 12704 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
06-11 17:53:20.407 12704 12704 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:63)
06-11 17:53:20.407 12704 12704 E ACRA    : 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@7979467, Dispatchers.Main.immediate]
06-11 17:53:25.982 13760 13798 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
06-11 17:53:27.006 13760 13892 E SQLiteLog: (284) automatic index on C(manga_id)
06-11 17:53:27.006 13760 13892 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.14.6 (standard, c615f4d, 101, 2023-04-16T15:14Z)
Android version: 12 (SDK 31)
Android build ID: SKQ1.211006.001 test-keys
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: apollo
Device model: M2007J3SG
Device product name: apollopro_id

### Tachiyomi version

0.14.6

### Android version

android 12 

### Device

xiaomi mi 10 t pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-06-12 02:12
Duplicate of #8400

**Closed by arkon** 2023-06-12 02:12 UTC
Labels: Bug
