### ISSUE TITLE
Individual update intervals

### ISSUE THREAD

**Issue by Arctomachine** [tachiyomiorg/tachiyomi#8820] opened 2022-12-30 18:27 UTC
### Describe your suggested feature

Some titles in library are known to get new chapters weekly. Or even monthly. So there is no reason to check for updates of this title every hour/few/day along with the rest of library. How I view possible solution:

1. For settings of each title (on details page) add new sub menu: update interval. Contains list of possible options: "as global" (enabled by default), few values for hours, days, weeks, custom interval -> input exact value in months + weeks + days + hours
2. When doing global library update, check for this new value. If time since last chapter is less than interval, exclude from update. If bigger or set "as global", update it.

It will make updates faster as well as remove some stress from source providers

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment] 2022-12-30 19:06
addressed by #5734

**Comment by stevenyomi** [comment] 2022-12-30 19:58
Duplicate of #5885

**Comment by Arctomachine** [comment] 2022-12-30 20:03
> Duplicate of #5885

Right. It was closed, so I have not found it by search.

**Closed** 2022-12-30 20:08 UTC
Labels: Feature request
