### ISSUE TITLE
Auto Scrolling

### ISSUE THREAD

**Issue by Koreji-Yamisora** [tachiyomiorg/tachiyomi#9089] opened 2023-02-14 09:41 UTC
### Describe your suggested feature

Feature auto Scrolling in the viewer with speed control

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2023-02-14 09:46
Duplicate of #2093

**Closed by Seishirou101** 2023-02-14 09:46 UTC
Labels: Feature request
