### ISSUE TITLE
[Bug] Image not Showing with some titles

### ISSUE THREAD

**Issue by crest1993** [tachiyomiorg/tachiyomi#4599] opened 2021-03-05 23:21 UTC
## Device information
* Tachiyomi version: 0.10.9
* Android version: Nougat 7
* Device: Bluestacks (Oneplus 5 profile)

## Steps to reproduce
1. Open Manga
2. Loading circle is done, but image not showing after that (in Webtoon view mode).

### Expected behavior
Image showing up after finished loading.

### Actual behavior
Blank page, and no retry button (the same color as background). I think the image is already finished loading but the app fail to show it. The same happen with Downloaded chapter, and when i check with file manager the image is all there. Is this happen because the Webtoon view mode function? This happen after awhile, it used to be fine. I tried reset cache, clear data same thing happen. And it only happen for some titles only, some title still working in webtoon view mode.

![image](https://user-images.githubusercontent.com/20949355/110184972-c18bb800-7e43-11eb-8d9c-52ab1e43e267.png)

Another problem with title that work is, there is a gap between page in webtoon view, im confused. Is there a way to reset view preferences for each manga? Or reset the setting but keep the library and viewed chapter?

**Comment by scb261** [comment] 2021-03-05 23:28
It only happens in webtoon mode? Can you confirm if https://github.com/tachiyomiorg/tachiyomi/issues/3514#issuecomment-691688123 is the same for you?

**Comment by crest1993** [comment] 2021-03-06 17:32
It is exactly the same,

and yeah the vertical and fit screen indeed showing the image. Is there a way to fix this? with this mode i need to zoom in (double tap) every pages.

**Comment by scb261** [comment] 2021-03-06 17:37
Duplicate of #3514

crest1993, there is no fix for now. You can try [preview](https://tachiyomi.org/download/) to see if it works with the new decoder. If you do - please tell if it works for you.

**Closed** 2021-03-06 21:30 UTC
Labels: bug
