### ISSUE TITLE
Crash when trying to read downloaded chapters

### ISSUE THREAD

**Issue by JavierFlores09** [tachiyomiorg/tachiyomi#9048] opened 2023-02-07 18:06 UTC
### Steps to reproduce

1. Download the extension TuMangaOnline (I tested it with this one, but others have supposedly confirmed it with lectormanga and ninemanga, however I haven't yet tried this myself).
2. Download a chapter from any manga/manhwa/manhua.
3. Disable internet connectivity (Wi-Fi and/or mobile data).
4. Try to read the download chapter.

### Expected behavior

The app should be able to read the chapters as usual.

### Actual behavior

The app crashes. This however doesn't happen with internet connectivity, only with downloaded chapters and it also doesn't happen with all extensions.

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/10677947/tachiyomi_crash_logs.txt)
[tachiyomi_crash_logs (1).txt](https://github.com/tachiyomiorg/tachiyomi/files/10677948/tachiyomi_crash_logs.1.txt)
[tachiyomi_crash_logs (2).txt](https://github.com/tachiyomiorg/tachiyomi/files/10677949/tachiyomi_crash_logs.2.txt)

### Tachiyomi version

0.14.4

### Android version

Android 7 (SDK 24), Android 12 (SDK 31), Android 10 (SDK 29)

### Device

Samsung J7 2016 (SM-J710MN), Xiaomi Redmi Note 8 (biloba), HUAWEI P40 Lite (JNY-LX2)

### Other details

1. The first crash log contains some clutter, which are these lines specifically:
```log
02-07 13:26:56.044  3382  3382 E ResourceType: Style contains key with bad entry: 0x0101056c
```
From what I have researched, this is because of the compatibility layer for my android version, and not because of what I am experiencing here, the following SO threads say to just ignore it:
https://stackoverflow.com/a/9691550/20951309
https://stackoverflow.com/a/44322568/20951309

There's also an exception about the downloader in the first one, however that is most likely because when I thought this was an issue only of the TMO extesion, I started playing around with its config options to see if anything changed, since TMO has a "Método de Descarga" (Download Method) option, which allows you to change from the default cascading to paginated. The paginated option however doesn't work, and the exception might be because of that, when I tried to download chapters with that option, it straight out refused and Tachiyomi send a notification saying "http or https expected but no scheme found for <manga name>" and when trying to read normally, it just straight out refused to download the images unless the chapter was already started/cached from the previous cascading method. This however seems to be an issue with the extension an may be ignored.

2. The user that originally reported this to me said that downgrading to 0.14.3 solved this issue, so the new 0.14.4 may have broken some extensions. I don't know if that's up to the extensions to update something but if that's the case, I can move this issue to the extension repo (or I believe since it is an org, you can do it with github?)

3. Download times also seems to be vastly slower in the new version, but I also don't know if that's just an overall related to the issue or what exactly.

4. Only the first one has detailed crash logs, the others I do not know.

5. What I believe to be the issue is, this line exception specifically:
```log
02-07 13:37:13.915  3382 14101 E SubsamplingScaleImageView: Failed to initialise bitmap decoder
02-07 13:37:13.915  3382 14101 E SubsamplingScaleImageView: java.lang.Exception: Image decoder failed to initialize and get image size
```
however, I haven't seen the exception in all of the crash logs from a quick glance, I don't know if this is because of the detailed crash logs option that it is unrelated, I find the latter unlikely though.

I'll be adding more info if I test this again, I am not the one experiencing this but some spanish users in the discord support channel, I just decided to do a detailed report

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-02-09 02:50
Duplicate of https://github.com/tachiyomiorg/tachiyomi-extensions/issues/15263

Updating your extensions should address this.

**Closed by arkon** 2023-02-09 02:50 UTC
Labels: Bug
