### ISSUE TITLE
Can't download any extension

### ISSUE THREAD

**Issue by gekkan7** [tachiyomiorg/tachiyomi#6802] opened 2022-03-21 21:46 UTC
### Steps to reproduce

1. Open the app
2. Go to browse or explore tab
3. Go to extension 
4. Try download any extension
5. Stuck in download progress

### Expected behavior

Usually when trying to download any website extension, all you have to do is download the extension and wait for it to install on Tachiyomi

### Actual behavior

what happens is that the download process is stuck and won't run and the download process automatically stops when trying to switch tab in the app

### Tachiyomi version

App version: 0.13.1

### Android version

Android 12

### Device

Realme 9 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by frankenstein11** [comment] 2022-03-31 17:02
I have the same issue.
My Device:- realme x7pro 5g

**Comment by Michael-Adu** [comment] 2022-04-01 15:44
I have the same issue. It only occured when the OS updated to Android 12.
Device: Oneplus 9

**Comment by arkon** [comment] 2022-04-02 14:38
Duplicate of #6723

**Closed by arkon** 2022-04-02 14:38 UTC
Labels: Bug
