### ISSUE TITLE
AI Powered Raw Manga Translator

### ISSUE THREAD

**Issue by Nathan-MV** [tachiyomiorg/tachiyomi#8722] opened 2022-12-11 17:41 UTC
### Describe your suggested feature

It should work like this chrome extension:
https://chrome.google.com/webstore/detail/raw-manga-fan/lmojhocblnlnjboabeengdkgogipihmg
![image](https://user-images.githubusercontent.com/67521199/206919667-14a151ee-23d4-443a-89e2-4dd9a9c60de1.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by ghostbear** [comment] 2022-12-11 17:51
Duplicate of #6166

**Closed** 2022-12-11 17:53 UTC
Labels: Feature request
