### ISSUE TITLE
[Bug] tachiyomi keeps crashing when i read on any source

### ISSUE THREAD

**Issue by lovablesweet35** [tachiyomiorg/tachiyomi#5150] opened 2021-05-23 07:12 UTC
Hi, tachiyomi keeps crashing on me whenever i read on any source. It kept on doing thag whenever i tried to read in a different source because i thought that there may be a problem with the source but the problem persisted. I tried closing and opening the app again, clearing my cache, and restarting my device so far none of that helped solve the issue.

---

## Device information
* Tachiyomi version: 0.10.12
* Android version: G935FXXS8ETCB/G935FOJV8ETCB/G935FXXS8ETCA
* Device: samsung S7edge

## Steps to reproduce
1. Opening and reading on sources such as bato.to,1stkiss, mangahub, madara sources, and etc.
2. After reading 1 or 2 chapters it closes.

### Expected behavior
Not crashing when reading.

### Actual behavior
Keeps closing the app whenever i read a few chapters.

## Other details
[tachiyomi_crash_logs2.docx](https://github.com/tachiyomiorg/tachiyomi/files/6527675/tachiyomi_crash_logs2.docx)

**Comment by arkon** [comment] 2021-05-23 14:00
Duplicate of #5151.

Can you try downloading the Preview version from https://tachiyomi.org/download/ and seeing if reading the same thing there also crashes?

Please comment in #5151 to follow up.

**Closed by arkon** 2021-05-23 14:00 UTC
Labels: bug
