### ISSUE TITLE
Additional bookmarking feature 

### ISSUE THREAD

**Issue by TheSeriousYoungBoy** [tachiyomiorg/tachiyomi#9214] opened 2023-03-15 19:53 UTC
### Describe your suggested feature

Can you create where users can bookmark a certain page in a chapter instead of bookmarking the whole chapter.
i.e. I bookmarked ch5p16 after reading then if I were to open ch5, the app would redirect me to page16.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2023-03-15 19:57
Duplicate of #565

**Closed by Seishirou101** 2023-03-15 19:57 UTC
Labels: Feature request
