### ISSUE TITLE
[Bug] pages don't load [Retry]

### ISSUE THREAD

**Issue by TogataSan** [tachiyomiorg/tachiyomi#4646] opened 2021-03-14 09:50 UTC
## Device information
Tachiyomi version: App version: 0.10.9 (standard, f590378, 56)
Android version: 9 (SDK 28)
Android build ID: PKQ1.190616.001
Device brand: xiaomi
Device manufacturer: Xiaomi
Device name: ginkgo
Device model: Redmi Note 8
Device product name: ginkgo

## Steps to reproduce
1. Try to read manga 
2. Issues noticed while using Mangakakalot, Mangasee and couple others that I don't remember 

### Expected behavior
You should be able to read it. 

### Actual behavior
Doesn't load. Had the issue before updating the app and thought that the update might fix it but nothing changed. 
![IMG_20210314_134303](https://user-images.githubusercontent.com/80621859/111064182-0b237500-84cc-11eb-9015-3413f8381bd1.jpg)
![IMG_20210314_134243_1](https://user-images.githubusercontent.com/80621859/111064199-15457380-84cc-11eb-86d6-958d4f1e1140.jpg)

**Comment by scb261** [comment] 2021-03-14 12:36
Duplicate of tachiyomiorg/tachiyomi-extensions#6136

**Closed** 2021-03-14 14:30 UTC
Labels: bug

**Comment by kakardo** [comment] 2021-03-15 09:40
I was just about to report this. Mangas from "mangasee" has not been working for a couple of days.
