### ISSUE TITLE
[Feature Request] Jump to a certain page when you're searching for manga

### ISSUE THREAD

**Issue by Amazingduf** [tachiyomiorg/tachiyomi#1896] opened 2019-03-17 22:51 UTC
when you're searching for (a) manga, instead of scrolling endlessly until you find one, what about jumping multiple pages ? 

Like, when I want to read something but not sure what, I usually select a genre and search till I find something interesting, but every time I do that, I have to scroll over all the titles that I've read before/not interested in. And it takes a lot of time to reach the point where I stopped the last time, especially when you're searching through thousands of titles.

It feels like it's a good feature to add in the future.

**Comment by arkon** [comment] 2021-01-04 21:00
Duplicate of #407

**Closed by arkon** 2021-01-04 21:00 UTC
Labels: feature
