### ISSUE TITLE
Enable two-way tracking in the app

### ISSUE THREAD

**Issue by beyond9thousand** [tachiyomiorg/tachiyomi#8732] opened 2022-12-13 10:38 UTC
### Describe your suggested feature

Currently, tracking is only one-way. Having two-way tracking would allow coherent and synchronized experience across all devices.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment] 2022-12-13 10:40
Duplicate of https://github.com/tachiyomiorg/tachiyomi/issues/1626

**Closed by CarlosEsco** 2022-12-13 10:40 UTC
Labels: Feature request

**Comment by beyond9thousand** [comment] 2022-12-13 10:57
@CarlosEsco sorry for the ping but is there a reason why this is not planned? Technical limitation? Just looking for an explanation as to why, because I couldn't find any

**Comment by stevenyomi** [comment] 2022-12-13 11:00
This is a duplicate of #1626, which means someone already requested this feature in #1626.

**Comment by beyond9thousand** [comment] 2022-12-13 17:39
There's really no answers on that issue though? It was dead for almost a year until I commented on it again about a month ago.

**Comment by beyond9thousand** [comment] 2022-12-13 18:09
I was not implying that any of the contributors or devs are obligated. Only that there was no response at all on the issue. The lack of this response (even if its a simple no) is what drove me to open this issue. I hope that misunderstanding has been cleared.

Thanks for your time.

**Comment by stevenyomi** [comment] 2022-12-13 18:22
> Only that there was no response at all on the issue.

The issue being open (not closed) means that it's potentially doable (but in this case the reverse tracking might increase network traffic and cause more DDoS so I doubt whether it's good or not).

In fact, most issues don't have active replies. Currently the core developers are focusing on refactoring the project, so don't expect them to implement big feature requests. There aren't many active developers either so don't expect features to be implemened anytime soon.

**Comment by beyond9thousand** [comment] 2022-12-13 21:50
Understood
