### ISSUE TITLE
[Feature Request] make bookmarked manga in search global or extension become disappear

### ISSUE THREAD

**Issue by Hanestya** [tachiyomiorg/tachiyomi#4952] opened 2021-04-23 18:37 UTC
## Why/User Benefit/User Problem
When looking for manga I like not using filters but do random scrolling ,i have bookmarked lot of manga but sadly evertime when do a serach (global or just in one extension) i will see all manga even you bookmarked

## What/Requirements
I want make a request ,would you to hide the bookmarked manga when make a global search or you can make a options to make bookmarked manga gray or disappear

Sorry for bad English thanks you

**Comment by Seishirou101** [comment] 2021-04-23 19:06
duplicate of #2941

**Closed** 2021-04-23 19:12 UTC
Labels: feature
