### ISSUE TITLE
[Feature Request] Page/Chapter Notes

### ISSUE THREAD

**Issue by MoonIceBear** [tachiyomiorg/tachiyomi#4171] opened 2020-12-21 11:12 UTC
---

## Why/User Benefit/User Problem
On each page you could make notes of the manga your reading. This could come in handy when you want to look back on how you thought at that time. When you want to remember a certain paner or page etc.  Also when making theories or when you want to review a manga.

## What/Requirements
When you touch the touchscreen for a long time whilst reading you get the options to share, save and to set as cover. I would add it to that list. Then a box would appear where you can write your notes. Then I would a feature where you can view the notes you made per manga.

**Comment by arkon** [comment] 2020-12-21 22:20
Duplicate of #2155

**Closed by arkon** 2020-12-21 22:20 UTC
Labels: feature
