### ISSUE TITLE
Theme tabs jumps/stutters when changing the theme

### ISSUE THREAD

**Issue by Cjojojojo** [tachiyomiorg/tachiyomi#8377] opened 2022-10-31 03:56 UTC
### Steps to reproduce

1.Go to Appearance
2.Change to any theme
3. Screen stutters after you change the theme

### Expected behavior

It should not stutter and change to any theme normally

### Actual behavior

When trying to change theme, it stutters

### Tachiyomi version

0.14.1

### Android version

Android 12

### Device

Oppo A74

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-10-31 12:34
Duplicate of #8265

**Closed** 2022-10-31 12:34 UTC
Labels: Bug
