### ISSUE TITLE
Manga title get cropped

### ISSUE THREAD

**Issue by Riztard** [tachiyomiorg/tachiyomi#5646] opened 2021-08-02 11:03 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

r3644

### Android version

A10

### Device

Redmi 8

### Steps to reproduce

1. search manga with long title (im using "hazure skill gacha" from `west manga` indonesian source)
2. open that manga

### Expected behavior

some part of the title get cropped

### Actual behavior

show the beginning/all of the title

### Other details

<table>
<tr>
	<td>Potrait
	<td>Landscape
<tr>
	<td><img src="https://cdn.discordapp.com/attachments/825346400953827349/871708378009841674/IMG_20210802_175728.jpg">
	<td><img src="https://cdn.discordapp.com/attachments/825346400953827349/871708563075104768/Screenshot_2021-08-02-17-58-18-023_eu.kanade.tachiyomi.debug.jpg">
</table>

**Comment by arkon** [comment] 2021-08-02 13:17
Duplicate of #5617

**Closed by arkon** 2021-08-02 13:17 UTC
Labels: Bug
