### ISSUE TITLE
Crash in MangaScreen

### ISSUE THREAD

**Issue by Iamlooker** [tachiyomiorg/tachiyomi#9986] opened 2023-10-07 03:59 UTC
### Steps to reproduce

1. Open any manga with many pages
2. Scroll quickly down

### Expected behavior

Just scroll

### Actual behavior

Crash

### Crash logs

```
--------- beginning of main
10-06 21:03:33.639 13732 13732 E GraphicExt: GraphicExtModuleLoader::CreateGraphicExtInstance false
App version: 0.14.6-6080 (dev, b3dfe84f2, 106, 2023-10-06T15:16Z)
Android version: 10 (SDK 29)
Android build ID: 00WW_3_26L
Device brand: Nokia
Device manufacturer: HMD Global
Device name: PDA_sprout
Device model: Nokia 5.1 Plus
Device product name: Panda_00WW
WebView user agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.5195.136 Mobile Safari/537.36
Crash:
kotlin.UninitializedPropertyAccessException: lateinit property canSwipeTowardsLeft has not been initialized
    at me.saket.swipe.SwipeableActionsState.getCanSwipeTowardsLeft$swipe_release
    at me.saket.swipe.SwipeableActionsState$draggableState$1.invoke
    at me.saket.swipe.SwipeableActionsState$draggableState$1.invoke
    at kotlinx.serialization.descriptors.SerialDescriptorImpl$toString$1.invoke$bridge(SourceFile:0)
    at androidx.compose.foundation.gestures.DefaultDraggableState$dragScope$1.dragBy
    at androidx.compose.foundation.gestures.DefaultDraggableState$dragScope$1.dragBy$bridge
    at androidx.compose.foundation.gestures.DraggableNode$onAttach$1$1.invokeSuspend
    at androidx.compose.foundation.gestures.DraggableNode$onAttach$1$1.invoke
    at androidx.compose.foundation.gestures.DraggableNode$onAttach$1$1.invoke
    at androidx.compose.foundation.MutatorMutex$mutateWith$2.invokeSuspend
    at androidx.compose.foundation.MutatorMutex$mutateWith$2.invoke
    at androidx.compose.foundation.MutatorMutex$mutateWith$2.invoke
    at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn
    at okio.Utf8.processUtf16Chars
    at kotlinx.coroutines.CoroutineScopeKt.coroutineScope
    at kotlinx.coroutines.CoroutineScopeKt.coroutineScope
    at androidx.compose.foundation.MutatorMutex.mutateWith
    at androidx.compose.foundation.gestures.DefaultDraggableState$drag$2.invokeSuspend
    at androidx.compose.foundation.gestures.DefaultDraggableState$drag$2.invoke
    at androidx.compose.foundation.gestures.DefaultDraggableState$drag$2.invoke
    at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn
    at okio.Utf8.processUtf16Chars
    at kotlinx.coroutines.CoroutineScopeKt.coroutineScope
    at kotlinx.coroutines.CoroutineScopeKt.coroutineScope
    at androidx.compose.foundation.gestures.DefaultDraggableState.drag
    at androidx.compose.foundation.gestures.DraggableNode$onAttach$1.invokeSuspend
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith
    at kotlinx.coroutines.DispatchedTask.run
    at kotlinx.coroutines.DispatchedTask.run
    at androidx.compose.ui.platform.AndroidUiDispatcher.nextTask
    at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch
    at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch
    at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch
    at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch
    at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7356)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

### Tachiyomi version

Dev version

### Android version

Android 10/12/13

### Device

Nokia 5/Samsung S21FE

### Other details

This is a known issue in the `me.saket.swipe` library: **[here](https://github.com/saket/swipe/issues/19)**

But the reported version `1.3.0-SNAPSHOT` is no longer available on _jitpack.io_

Best option would be to remove extra dependency on a third party library.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-10-07 12:43
Duplicate of #9819

**Closed** 2023-10-07 12:43 UTC
Labels: Bug, Duplicate
