### ISSUE TITLE
Introduce secret/private categories in library

### ISSUE THREAD

**Issue by Finamore00** [tachiyomiorg/tachiyomi#9573] opened 2023-06-03 15:59 UTC
### Describe your suggested feature

How the feature should work:

- When creating a new category, besides from the category name a checkbox can be included to make the category private. Every new category could be public by default.
- The toggle for showing or hiding private categories can be included in the filter page for the library
- A password system would be put in place to protect access to private categories.
- The feature could potentially be enabled/disabled in the system settings, where the password setup would also take place. 

### Other details

I'm pretty sure a non-insignificant percentage of the user-base has at least _some_ form of guilty pleasure content that they would rather not be shown when sharing their manga library with others. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-06-03 16:08
Duplicate of #1508

**Closed** 2023-06-03 16:08 UTC
Labels: Feature request
