### ISSUE TITLE
Downloaded chapters that have been removed from source not shown in chapter list

### ISSUE THREAD

**Issue by Whitealion** [tachiyomiorg/tachiyomi#9711] opened 2023-07-13 17:18 UTC
### Steps to reproduce

1. Download chapter from source
2. Source removes chapter

### Expected behavior

Chapter should be listed.

Example of using local source as workaround:
<img src="https://cdn.discordapp.com/attachments/452140763543896074/1129046751706353774/WhatsApp_Image_2023-07-13_at_15.37.58.jpg" height="480px">

### Actual behavior

Tachiyomi sees downloaded chapter when counting but doesn't display it when opening chapter list

Example: 
<img src="https://cdn.discordapp.com/attachments/452140763543896074/1129046557468135566/WhatsApp_Image_2023-07-13_at_15.37.58.jpg" height="480px">
<img src="https://cdn.discordapp.com/attachments/452140763543896074/1129046729522683944/WhatsApp_Image_2023-07-13_at_15.37.58.jpg" height="480px">

### Tachiyomi version

0.14.6

### Android version

Android 11

### Device

Redmi Note 9 Pro

### Other details

Could probably be fixed by implementing #9591.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2023-07-13 17:37
Duplicate of #2108

**Closed by Seishirou101** 2023-07-13 17:37 UTC
Labels: Bug
