### ISSUE TITLE
add waiting time in "Keep screen on"

### ISSUE THREAD

**Issue by Gamefire238** [tachiyomiorg/tachiyomi#8768] opened 2022-12-18 07:49 UTC
### Describe your suggested feature

what I mean is
 > I set android screen life time to 30 seconds to save battery.

 > I want the tachiyomi screen to stay on longer than the android screen off time that I set before without using the "Keep screen on" feature

 > The feature I mean is, the user can optionally set the on time of the tachiyomi reading screen, for example: READING TIME = 1 minute, 5 minutes, 1 hour,... Forever. the screen will turn off once the timeout is reached.

### Other details

I enabled feature "Keep screen on" in app and read afterwards but i overslept while reading cause screen stay on seven hours till morning cause my android to get hot and drain battery due to my own carelessness :(
 I know that the solution to this is simply to turn off "Keep screen on", its quite annoying to keep screen on if screen is off while reading.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-12-18 14:21
Duplicate of #3251

**Closed** 2022-12-18 14:21 UTC
Labels: Feature request
