### ISSUE TITLE
"Download ahead" while reading not working at all

### ISSUE THREAD

**Issue by koinupapi** [tachiyomiorg/tachiyomi#10357] opened 2024-01-08 05:12 UTC
### Steps to reproduce

1. download chapter 1 & 2 of any manga or book
2. Start reading chapter 1 and get roughly 25% in
3. See that chapter 3 is NOT being downloaded.

### Expected behavior

After reading 25% of a chapter (from rough previous testing, I determined it to be roughly 25%), the chapter that is 2 ahead of the current one should download, as long as the current chapter +1 are already downloaded.

### Actual behavior

The chapter doesn't download.

### Tachiyomi version

0.15.1

### Android version

14

### Device

Samsung S21 Ultra 5G

### Other details

This wasn't an issue before the big 0.15.0 update, and 0.15.1 didn't fix it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by koinupapi** [comment] 2024-01-08 05:14
Sorry for borking the title. I also just realized it's "download ahead", not "Auto-Download".
I can open a new issue if you'd like.

**Comment by BrutuZ** [comment] 2024-01-08 05:38
You can edit the title and description of issues, no need to open a new one.

Maybe a dupe of #10151 ?

**Comment by koinupapi** [comment] 2024-01-08 06:01
> You can edit the title and description of issues, no need to open a new one.
> 
> Maybe a dupe of #10151 ?

Thanks, edited!


And I apologize, looks like it is a duplicate. The issue came for me with version 0.15.0, so I assumed it was a separate issue than #10151 which was posted 2 months ago.

Should I close this issue and add onto his?

**Comment by BrutuZ** [comment] 2024-01-08 06:05
Can close this one but no need to add there, that one was closed as fixed earlier. There was just no build since the fix

**Comment by koinupapi** [comment] 2024-01-08 06:09
> Can close this one but no need to add there, that one was closed as fixed earlier. There was just no build since the fix

Ah, just saw that. Gotta learn how to use GitHub haha.

Thanks so much! Excited to test out the  build with the (hopefully) fix.

**Closed** 2024-01-08 06:09 UTC
Labels: Bug
