### ISSUE TITLE
Chapters randomly grays out as if chapters was read

### ISSUE THREAD

**Issue by RoBoT095** [tachiyomiorg/tachiyomi#9236] opened 2023-03-19 04:09 UTC
### Steps to reproduce

I just enter a manga with unread chapters and one or two chapters are half way grayed out, this happens on any manga from any extension

### Expected behavior

Unread chapters should be white and read chapters should be grayed out

### Actual behavior

If I leave and return back into the same manga it either fixes itself or grays out other chapters

### Tachiyomi version

0.14.5

### Android version

Android 13

### Device

OnePlus 9 5G

### Other details

![IMG_20230318_235655](https://user-images.githubusercontent.com/38968333/226153075-b097dffd-cbe2-4c64-90b4-c12b3b63eb4c.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by mobi2002** [comment] 2023-03-19 04:50
Duplicate of #9043

**Closed** 2023-03-19 05:20 UTC
Labels: Bug
