### ISSUE TITLE
Stitching is odd when zooming in

### ISSUE THREAD

**Issue by de-odex** [tachiyomiorg/tachiyomi#2033] opened 2019-05-14 08:56 UTC
**App version: debug r1505**

**Android version: 9.0**

**Issue/Request: Zooming in to a large image shows odd behavior**

**Steps to reproduce (if applicable)**

 1. Open manga https://mangadex.org/manga/17720/
 2. Open Volume 2 Chapter 17
 3. Zoom into the first image

**Other details: It seems to be an issue to the loading of finer detail when zooming. Unsure if this is a dependency issue**

https://drive.google.com/file/d/1WaAfIVXlTmE3bq2xrCk7Hm0YBY8lJ9W9/view?usp=drivesdk
Video

**Comment by Flat** [comment] 2019-05-14 22:14
Can't reproduce. Can you please provide your default reader settings?

**Comment by de-odex** [comment] 2019-05-15 18:57
https://drive.google.com/file/d/1V0c9J8bSzHIv-vCyUYM_HVOB_NwQj1kq/view?usp=drivesdk

**Comment by arkon** [comment] 2021-04-17 15:33
Closing due to age. Could try 32-bit color if you haven't already.

**Closed by arkon** 2021-04-17 15:33 UTC
Labels: bug
