### ISSUE TITLE
[Feature Request] Individual filter for each category/library tab

### ISSUE THREAD

**Issue by jogerj** [tachiyomiorg/tachiyomi#2698] opened 2020-03-12 20:08 UTC
### Why/User Benefit/User Problem
![Screenshot_20200312-201229](https://user-images.githubusercontent.com/30559735/76558821-44cb3580-649e-11ea-88b3-3f7e7e6a6413.jpg)

So I have these categories sorted out but I want to sort each category differently (e.g. "Now Reading" category would sort by last read, "Ongoing" category sort by last updated, etc.)

### What/Requirements
Each category has an independent property which defines how it should be filtered, default being no filter. The filter should be saved and loaded each time the category is opened/viewed.

**Comment by arkon** [comment] 2022-07-09 23:04
Duplicate of #305

**Closed by arkon** 2022-07-09 23:04 UTC
Labels: Feature request
