### ISSUE TITLE
Add ability to set a default start screen.

### ISSUE THREAD

**Issue by daveylu** [tachiyomiorg/tachiyomi#9268] opened 2023-03-27 03:34 UTC
### Describe your suggested feature

Add back the setting to set a default start screen. It should ideally have the same behaviour as in Tachiyomi v0.13.6, where on app startup, it will automatically open whichever tab you want (Library, Updates, History, Browse), instead of the current default of Library.

### Other details

This feature was removed in the update from v0.13.6 to v0.14.0.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment] 2023-03-27 05:16
You're intended to use app shortcuts to open the app on a certain screen instead now. 
Tap and hold on the shortcut to make a shortcut on your homescreen that opens to that screen every time if you don't want to do that every time.

**Comment by scb261** [comment] 2023-03-27 06:03
Duplicate of #7061

**Closed by scb261** 2023-03-27 06:03 UTC
Labels: Feature request
