### ISSUE TITLE
[Bug] Extension Search results doesn't show after install a source

### ISSUE THREAD

**Issue by Ahsan40** [tachiyomiorg/tachiyomi#4464] opened 2021-02-13 00:21 UTC
## Device information
* Tachiyomi version: 0.10.9 (3113)
* Android version: 9
* Device: Redmi Note 5 (Whyred)

## Steps to reproduce
1. Search any source you want to install.
2. Install a source you like and return to app by pressing back button.

### Expected behavior
After return to the app, either search results should have shown like normal or should have cleared search string.

### Actual behavior
Doesn't show search results or clear search string.

## Other details
**Screenshots**
Before install
![Screenshot_2021-02-13-06-10-59-319_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/30434801/107835359-7857c380-6dc3-11eb-8c01-2bf928545a49.jpg)

After install
![Screenshot_2021-02-13-06-11-16-577_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/30434801/107835407-99b8af80-6dc3-11eb-9eb7-90d29214c03e.jpg)

(In this test I installed kissmanga . in)

**Comment by scb261** [comment] 2021-02-13 00:44
Duplicate of #4371

**Closed** 2021-02-13 00:45 UTC
Labels: bug
