### ISSUE TITLE
KissLove not responding 

### ISSUE THREAD

**Issue by JarvisTan123** [tachiyomiorg/tachiyomi#9742] opened 2023-07-20 07:50 UTC
### Steps to reproduce

The latest chapter won't show up

### Expected behavior

Should showing latest chapter and able to view in 'Kisslove' extension 

### Actual behavior

Keep showing no chapter found. In addition, now not showing any other chapter of manga

### Tachiyomi version

0.14.6

### Android version

Android 12

### Device

Vivo 1907

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2023-07-20 11:32
Duplicate of https://github.com/tachiyomiorg/tachiyomi-extensions/issues/17137

**Closed by stevenyomi** 2023-07-20 11:32 UTC
Labels: Bug
