### ISSUE TITLE
ability to hide specific copy/instance of a given manga

### ISSUE THREAD

**Issue by asdkant** [tachiyomiorg/tachiyomi#8729] opened 2022-12-12 17:10 UTC
### Describe your suggested feature

There are times when a copy of a given manga (the one in a given sorce, or one of the many available in a given source) has a terrible translation, or is of too low quality, or is in some shape or form broken, and I would like to hide that instance (but still be able to see other instances from that source if the source has more than one, and instances from other sources).

I'd like the ability to mark a specific instance of a manga as "do not show" so it doesn't show up when I'm browsing the source. I do not mind the app spending a bit of bandwidth grabbing it from a list, I just don't want to see it listed in the UI.

I understand that this may require extension-specific code for implementation, but there should be at least some general interface to make this functionality feasible in the first place.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-12-12 17:13
Duplicate of #2371

**Closed by arkon** 2022-12-12 17:13 UTC
Labels: Feature request
