### ISSUE TITLE
Pan images for single pages/tall images

### ISSUE THREAD

**Issue by asw3** [tachiyomiorg/tachiyomi#9387] opened 2023-04-24 02:44 UTC
### Describe your suggested feature

Implement an option similar to the Pan wide images when tapping [Reader -> Paged] for single pages as well (height > width) images.

### Other details

Having such an option will make Landscape mode Fit width reading way more comfortable, as well as Continuous vertical reading. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2023-04-27 17:52
Duplicate of #4690 and #8714

**Closed by stevenyomi** 2023-04-27 17:52 UTC
Labels: Feature request
