### ISSUE TITLE
PC Version with cloud save when.

### ISSUE THREAD

**Issue by chocoblin** [tachiyomiorg/tachiyomi#5520] opened 2021-07-09 08:27 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

For people who have trouble reading for hours on a small screen that of a mobile phone, and who stay the whole day on their laptops or desktops, this would be a boon!

1. All we need is a pc version of tachiyomi, not on any app player like bluestacks, but actual .exe application.
It should sport a cloud save feature so that we can sync our settings, reading progress, trackers, etc. on the go between our multiple devices.

2. Backing up and restoring takes sooooo long each time. That's why I request the cloud sync feature. But I understand it can be troublesome as these would require servers from your part. It can be skipped, but would be a great feature imo.

Hope my wish comes true!

**Comment by loocool2** [comment] 2021-07-09 08:42
Duplicate of issues #912 and #2587

**Closed by loocool2** 2021-07-09 08:42 UTC
Labels: Feature request

**Comment by chocoblin** [comment] 2021-07-09 11:10
NOT a duplicate or related to another **open** issue.
