### ISSUE TITLE
Incorrect counter increment in notification for Refreshing Covers

### ISSUE THREAD

**Issue by devansh08** [tachiyomiorg/tachiyomi#6431] opened 2022-01-02 19:46 UTC
### Steps to reproduce

Trigger manga cover refresh from: Settings -> Advanced -> Library -> Refresh library manga covers

### Expected behavior

Progress counter in notification goes from 0 to num_of_mangas in library

### Actual behavior

Progress counter in notification goes from 0 to 2 * num_of_mangas in library. Increment was doubled basically. I have 39 manga set for refresh and it went like so: 0/39... 2/39... 4/39...... 78/39... Done. It did cover every manga correctly, as I was looking at the names in the notification. Just the counter was incorrect.

### Crash logs

No crashes.

### Tachiyomi version

Stable 0.12.3

### Android version

Android 11

### Device

Samsung Galaxy M01

### Other details

Developer friendly PS: I went through the codebase and was able to pinpoint the function `updateCovers` in `app/src/main/java/eu/kanade/tachiyomi/data/library/LibraryUpdateService.kt` to likely be the one updating the counter in the notification but was not able to really follow the logic of `progressCount` variable, as I am new to Kotlin (but I am a Java developer, so I was not just bumbling around :) ) and so was not able to debug.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-01-02 20:21
Duplicate of #6134

**Closed by arkon** 2022-01-02 20:21 UTC
Labels: Bug
