### ISSUE TITLE
[Feature Request] Add an option to delete read chapters from front/main page 

### ISSUE THREAD

**Issue by PXLCR** [tachiyomiorg/tachiyomi#4403] opened 2021-02-07 21:41 UTC
I acknowledge that:

- I have updated to the latest version of the app (stable is v0.10.8)
- I have updated all extensions
- If this is an issue with an extension, that I should be opening an issue in https://github.com/tachiyomiorg/tachiyomi-extensions

---

## Why/User Benefit/User Problem
It would allow users to faster free up storage without having to delete all downloaded chapters or having to go into each manga separately to remove read chapters.

## What/Requirements
It could be implemented by adding a third option to the main menu delete button, which allows the deletion of read chapters

**Comment by scb261** [comment] 2021-02-07 21:46
You can use *After reading* option under *Delete chapters* in download settings

**Comment by PXLCR** [comment] 2021-02-07 22:04
This is an option, however I also keep some manga around, which I would like to keep. I could set these to unread, which is merely a slight inconvenience, however I am lazy and don't want to do this.
What is already there is non-discriminating, and as such not capable of doing what I am suggesting here

**Comment by CaptainHalflife** [comment] 2021-02-11 13:35
I used tachiJ2k before and it has this feature, when i migrated to tachiyomi I realise how useful it was.

**Comment by arkon** [comment] 2021-04-04 22:21
Duplicate of #1364

**Closed by arkon** 2021-04-04 22:21 UTC
Labels: feature
