### ISSUE TITLE
Sort Manga by Download Size

### ISSUE THREAD

**Issue by KenzKD** [tachiyomiorg/tachiyomi#9404] opened 2023-04-27 07:17 UTC
### Describe your suggested feature

Add an option to sort manga in the library by their accumulated download folder size. This would allow users to easily see which manga are taking up the most space and help them manage their library size more effectively.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment] 2023-04-27 07:25
Duplicate of #8009

**Closed** 2023-04-27 07:25 UTC
Labels: Duplicate, Feature request
