### ISSUE TITLE
pls add pin feature to library 

### ISSUE THREAD

**Issue by Mohamedelrabbat** [tachiyomiorg/tachiyomi#9115] opened 2023-02-20 18:40 UTC
### Describe your suggested feature

The usual pin feature for the favourite manga in my Library 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-02-21 15:29
Duplicate of #3656

**Closed by arkon** 2023-02-21 15:29 UTC
Labels: Feature request
