### ISSUE TITLE
Request to add a preview window

### ISSUE THREAD

**Issue by jjjjbow** [tachiyomiorg/tachiyomi#10153] opened 2023-11-19 16:02 UTC
### Describe your suggested feature

Request to add a preview window

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment] 2023-11-19 16:07
of what?

**Comment by arkon** [comment] 2023-11-19 19:22
I assume this is a duplicate of #1632

**Closed by arkon** 2023-11-19 19:22 UTC
Labels: Feature request
