### ISSUE TITLE
Webtoon mode can't scroll up on some downloaded manhwa.

### ISSUE THREAD

**Issue by AwesomeQuest** [tachiyomiorg/tachiyomi#6570] opened 2022-02-05 10:30 UTC
### Steps to reproduce

1. Download two chapters of a manhwa, I've found it working with ch 77 and 76 of https://bato.to/series/80485/villains-are-destined-to-die , 106 and 105 of https://www.webtoons.com/en/fantasy/your-throne/list?title_no=2009 , and 56 and 55 of https://bato.to/series/83381/father-i-don-t-want-this-marriage.
2. Start reading the latter chapter and scroll up, you may get stuck on the chapter transition but just go down then up again.
3. Now you'll see that you can't scroll upp further than about 3/5 up the screen.

I've got this working consistently with the manga above, tried redownloading, setting read and unread, and zooming in and out, does not fix it.
It is not exlusive to the latest chapters, and it is not consistent with every chapter of a given manga.

### Expected behavior

I should be able to scroll up

### Actual behavior

It doesn't scroll up.

### Tachiyomi version

 0.12.3

### Android version

12

### Device

Samsung A72

### Other details

App version: 0.12.3 (standard, e863e8c, 69, 2021-10-04T21:35Z)
Android version: 12 (SDK 31)
Android build ID: SP1A.210812.016.A725FXXU4BULA
Device brand: samsung
Device manufacturer: samsung
Device name: a72q
Device model: SM-A725F
Device product name: a72qnseea

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AwesomeQuest** [comment] 2022-03-09 08:25
Correction, this can also happen with not downloaded chapters

**Comment by arkon** [comment] 2022-04-20 22:23
Duplicate of #3749

**Closed by arkon** 2022-04-20 22:23 UTC
Labels: Bug
