### ISSUE TITLE
[Feature Request] Set Library Update by choosing the time manually

### ISSUE THREAD

**Issue by thegreatdk** [tachiyomiorg/tachiyomi#4467] opened 2021-02-13 06:30 UTC
## Why/User Benefit/User Problem
Sometimes, when I choose daily/per 12 hours for library update frequency, the time is changing by itself and we dont know exactly when the update will run, so I suggest to add feature we can choose/set the time manually(for example 3 p.m)

## What/Requirements
When user choose this feature, apps will let user choose the time, whne the time comes, apps will run the update at the exact time user selected before

Sorry for my english, thank you

**Comment by arkon** [comment] 2021-02-13 13:44
Duplicate of #3589

**Closed by arkon** 2021-02-13 13:44 UTC
Labels: feature
