### ISSUE TITLE
[Bug] Choppy scrolling when reading long strip manhua

### ISSUE THREAD

**Issue by chrintzis** [tachiyomiorg/tachiyomi#5351] opened 2021-06-08 14:39 UTC
## Device information
* Tachiyomi version: v0.11.1 (and older)
* Android version: 10
* Device: Samsung Galaxy A6+ (2018)

## Steps to reproduce
1. Read "Rebirth of the Immortal Venerable" from Manhua Plus source.
2. Scroll down through chapter 29 page 2.

### Expected behavior. 
Smooth scrolling. 

### Actual behavior
Scrolling becomes choppy. 

## Other details
Usually happens when reading long strip or high resolution manga.

**Comment by Seishirou101** [comment] 2021-06-08 14:43
duplicate of #1908

**Closed** 2021-06-08 15:16 UTC
Labels: bug
