### ISSUE TITLE
Language Selection/Filter for manga

### ISSUE THREAD

**Issue by KatsuneMiku** [tachiyomiorg/tachiyomi#7153] opened 2022-05-17 06:14 UTC
### Describe your suggested feature

Hello, I would like to suggest language selection/filter.
Since a manga has more than one language translation, it would be a benefit for the users to add this feature. Especially when a manga has dozen of translations, some of us struggle to find the specific translation of the chapter. It'd be nice to continually read until the next chapter than leaving the chapter you've finished and searching for a specified translation.

### Other details

Here's a similar sample of language selection/filter from comick.fun
![Screenshot 2022-05-17 140557](https://user-images.githubusercontent.com/75795885/168740592-db10e67a-56f7-40ef-9a5a-e07e7ab7c09b.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2022-05-17 06:21
Duplicate of #969 more or less.

**Closed by Seishirou101** 2022-05-17 06:21 UTC
Labels: Feature request
