### ISSUE TITLE
[Feature Request] Feature for manually sorting mangas

### ISSUE THREAD

**Issue by lordsteve751** [tachiyomiorg/tachiyomi#4591] opened 2021-03-04 16:12 UTC
## Why/User Benefit/User Problem

Because some mangas are in series and we want to put them in order or there are times where we want to sort the mangas in an order we like more

## What/Requirements

In the sort panel at the top there should be a "Manual" option which, when tapped, allows the user to manually sort the mangas just like we are able to sort categories.

Basically the same feature as 'categories' except its for the specific mangas.

**Comment by scb261** [comment] 2021-03-04 17:28
Not entirely sure if that's what the author wants, but looks like duplicate of #4548

**Closed** 2021-03-04 17:35 UTC
Labels: feature

**Comment by dmswd** [comment] 2021-03-04 19:37
Bro
Use a fork
Like tachiyomi SY
