### ISSUE TITLE
separate category update time 

### ISSUE THREAD

**Issue by vhiri** [tachiyomiorg/tachiyomi#9037] opened 2023-02-06 01:55 UTC
### Describe your suggested feature

Tachiyomi has an update warning notification with a lot of items, so if there was a way to make the automatic update have a different time for each category, it would be like increasing or decreasing the priority of the global update.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment] 2023-02-06 03:02
Duplicate of #822

**Closed by loocool2** 2023-02-06 03:02 UTC
Labels: Feature request
