### ISSUE TITLE
subgroup mangas in chatagories

### ISSUE THREAD

**Issue by goldast** [tachiyomiorg/tachiyomi#10297] opened 2024-01-06 17:56 UTC
### Describe your suggested feature

i have a lot of manga and some of them is same mangas but i cant group all of them in chatogories i need a subgroup selection.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2024-01-06 18:13
Duplicate of #1803

**Closed by arkon** 2024-01-06 18:13 UTC
Labels: Feature request
