### ISSUE TITLE
[Feature Request] Change default scrolling type by detecting webtoon and manga page size

### ISSUE THREAD

**Issue by DavianYang** [tachiyomiorg/tachiyomi#5147] opened 2021-05-23 03:25 UTC
## Why/User Benefit/User Problem
I think it's convenient for those who alternately both read manga and webtoon. But since webtoon size are quite vary from manga, I think it's difficult for conditions check.

## What/Requirements
(explain how this feature would behave)

**Comment by loocool2** [comment] 2021-05-23 03:27
Duplicate of #1664

**Closed** 2021-05-23 03:54 UTC
Labels: feature
