### ISSUE TITLE
[Feature Request] Include content pan in navigation

### ISSUE THREAD

**Issue by jRob2k** [tachiyomiorg/tachiyomi#5111] opened 2021-05-19 11:35 UTC
## Why/User Benefit/User Problem
Tachiyomi is a great comic/manga reader. In situations where fitting the content to the screen by height results in a comfortable zoom level the user can set the default view to the left/right side of the page and then only needs to swipe left and right to view the entire page and then progress to the next one. Since swipe navigation is enabled by default swiping too quickly often navigates to the next page rather than showing the left/right side of the current page. 

## What/Requirements
I think this experience can be improved with 1 or 2 tweaks. 

1) Include left/right pan (to the end of the content) in the navigation.
- Triggering navigation to the next page will pan content in that direction if not already at the end of content rather than navigating to the next page
- This should improve the overall comic reading experience since now the user can simply use their preferred navigation method to pan through the entire contents of a page before navigating to the next page.

2)Include the ability to disable swipe navigation.
- Swiping on a screen will only pan content and will not navigate to the next page.
- This should improve the panning experience since it will be harder to accidentally navigate to the next page

**Comment by arkon** [comment] 2021-05-19 12:09
Duplicate of #2161

**Closed by arkon** 2021-05-19 12:09 UTC
Labels: feature
