### ISSUE TITLE
refresh library not working

### ISSUE THREAD

**Issue by lcshiray** [tachiyomiorg/tachiyomi#10345] opened 2024-01-07 19:29 UTC
### Steps to reproduce

1.scroll to update library or press update library button

### Expected behavior

library should refresh with new available chapters

### Actual behavior

no new chapters unless it's refreshed directly from their individual series page

### Tachiyomi version

0.15.0

### Android version

android 13

### Device

samsung note 20

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2024-01-07 19:35
Duplicate of #10313

**Closed** 2024-01-07 19:35 UTC
Labels: Bug
