### ISSUE TITLE
All chapters are showing under the Updates tab

### ISSUE THREAD

**Issue by Florisius** [tachiyomiorg/tachiyomi#6491] opened 2022-01-23 17:22 UTC
### Steps to reproduce

1. Add mangas with existing chapters to library
2. Check later for updates
3. Recent updates appear under the updates tab

### Expected behavior

Only the new updates of the mangas in my library are to show under the updates tab

### Actual behavior

All chapters of mangas in my library plus recent updates show making it difficult to find which manga actually got updates 

### Tachiyomi version

0.12.3

### Android version

Android 11

### Device

Samsung s10+

### Other details

![Screenshot_20220122-043633_Tachiyomi](https://user-images.githubusercontent.com/98201221/150690111-797c00a2-f5ca-43d8-8bd5-4e5fe684915e.jpg)
![Screenshot_20220122-043651_Tachiyomi](https://user-images.githubusercontent.com/98201221/150690115-8f0a374b-166b-4671-a639-b5c24d35ae5f.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by FourTOne5** [comment] 2022-01-23 17:53
Did they got marked as unread too?

**Comment by Florisius** [comment] 2022-01-26 05:57
> Did they got marked as unread too?

No not all chapters. Just some

**Comment by janaeg87** [comment] 2022-01-28 02:09
I am interested in trying to fix this bug.

**Comment by loocool2** [comment] 2022-01-28 02:51
What source is this from?

**Comment by Seishirou101** [comment] 2022-01-28 03:27
If those chapters are from mangaowl, then it is a known issue as the extension is broken. You can open a new issue if that is not the case, but it is most likely due to the extension and not an app related bug so please open one in the extension repo with more information or reach out in discord

**Closed by Seishirou101** 2022-01-28 03:27 UTC
Labels: Bug

**Comment by Florisius** [comment] 2022-01-29 17:37
> 

It's not a mangaowl site issue

**Comment by Florisius** [comment] 2022-01-29 17:58
> What source is this from?

Source?

**Comment by FourTOne5** [comment] 2022-01-29 18:31
> > 
> 
> It's not a mangaowl site issue

The issue is that MangaOwl admin are intentionally changing stuff to break the MangaOwl source (or extension).
