### ISSUE TITLE
Exclude specific Extension when updating Library 

### ISSUE THREAD

**Issue by Reylith** [tachiyomiorg/tachiyomi#9070] opened 2023-02-11 19:44 UTC
### Describe your suggested feature

Currently When updating Library. If Extension's website is down. It still try to update library from that extension. If there a setting to toggle off. (Example: in that specific extension settings that isn't working right now or will be down for 1 week or so). so that it doesn't load from that extension.

### Other details

I'm talking about vanilla tachiyomi btw

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2023-02-11 20:05
Duplicate of #5664

**Closed by Seishirou101** 2023-02-11 20:05 UTC
Labels: Feature request
