### ISSUE TITLE
Naming bookmarks

### ISSUE THREAD

**Issue by BlipSpeed** [tachiyomiorg/tachiyomi#7906] opened 2022-08-31 10:53 UTC
### Describe your suggested feature

It would give you an option to either name why you bookmarked that chapter, whether it be something you want to reread, or because it has very important information. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-08-31 13:14
Duplicate of #5043

**Closed by arkon** 2022-08-31 13:14 UTC
Labels: Feature request
