### ISSUE TITLE
[Feature Request] Reading mode continuous horizontal, or webtoon but in horizontal

### ISSUE THREAD

**Issue by Noname-noragami** [tachiyomiorg/tachiyomi#4490] opened 2021-02-15 13:28 UTC
## Why/User Benefit/User Problem
(explain why this feature should be added)
Because some series have Short height but wide page, o know you have add split page func but with this reading mode make it more comfortable when you read between two page
## What/Requirements
(explain how this feature would behave)
[Feature Request] Reading mode continuous horizontal, or webtoon but in horizontal mode

**Comment by arkon** [comment] 2021-02-15 14:23
Duplicate of #2291

Please search for existing issues before creating new ones. You've already opened many duplicate ones. If you keep doing so, we will need to block you to avoid further spam.

**Closed by arkon** 2021-02-15 14:23 UTC
Labels: feature
