### ISSUE TITLE
Deletion of downloaded not-in-library Manga chapters

### ISSUE THREAD

**Issue by Baeconboy** [tachiyomiorg/tachiyomi#6476] opened 2022-01-16 14:00 UTC
### Describe your suggested feature

A button that lets you delete downloaded manga chapters from Manga that are no longer in your library (i.e due to migration), similar to the "Clear database" feature.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-01-16 15:05
Duplicate of #1767

**Closed by arkon** 2022-01-16 15:05 UTC
Labels: Feature request
