### ISSUE TITLE
Custom Themes

### ISSUE THREAD

**Issue by rileyhawk1417** [tachiyomiorg/tachiyomi#5606] opened 2021-07-25 15:38 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

Instead of asking for more themes and waiting for the next update just to get a new theme. Can users create custom themes that they can even share to others?

Hopefully it will be possible to consider these features in a future update: 
- Color picker in settings to tweak accents.
- As time goes by hopefully importing and exporting of custom themes will be possible (maybe even setting of transparent/custom wallpapers as background in the app).

**Comment by loocool2** [comment] 2021-07-25 15:43
Duplicate of #3541

**Closed by loocool2** 2021-07-25 15:43 UTC
Labels: Feature request

**Comment by rileyhawk1417** [comment] 2021-07-25 15:56
> Duplicate of #3451

whoops thought i searched it correctly, but thanks
