### ISSUE TITLE
Scroll by pressing the black border

### ISSUE THREAD

**Issue by JM150JM150** [tachiyomiorg/tachiyomi#9541] opened 2023-05-25 02:50 UTC
### Describe your suggested feature

When I try to read a manga, I put it horizontally, I zoom out a bit, so there are some black borders on the sides. When I try to go down by touching the black border in webtoon mode, it doesn't go down, and it doesn't go down either in page mode. You should add the option to be able to scroll still touching the black part when we zoom out, thanks

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-05-25 02:50
Duplicate of #3127

**Closed by arkon** 2023-05-25 02:50 UTC
Labels: Feature request
