### ISSUE TITLE
Cbr files? Release date estimate?

### ISSUE THREAD

**Issue by NERDforeverNF** [tachiyomiorg/tachiyomi#7662] opened 2022-07-31 16:36 UTC
### Describe your suggested feature

I'm always grabing files from get comics and they are cbr files but I like reading on this app soild 9/10, when is cbr compression becoming readable?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-07-31 16:44
Duplicate of #3988

**Closed by arkon** 2022-07-31 16:44 UTC
Labels: Feature request
