### ISSUE TITLE
Add option to backup tachiyomi settings

### ISSUE THREAD

**Issue by alexphilip0019** [tachiyomiorg/tachiyomi#9040] opened 2023-02-06 14:51 UTC
### Describe your suggested feature

Not sure if it's already there
But want option to backup settings of tachiyomi same way backup library and all
So that if someone wants to downgrade version or anything
Can just restore settings backup along with library backup

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2023-02-06 15:05
Duplicate of #1857

**Closed by alessandrojean** 2023-02-06 15:05 UTC
Labels: Feature request
