### ISSUE TITLE
download bug. chapter pages limited to <1000. download queue stops

### ISSUE THREAD

**Issue by Wyld-One** [tachiyomiorg/tachiyomi#5050] opened 2021-05-10 13:33 UTC
https://github.com/tachiyomiorg/tachiyomi/blob/5700c7a0c7bf532faadf50e261a03b84f36c6fe1/app/src/main/java/eu/kanade/tachiyomi/data/download/Downloader.kt#L341

format limits pages in single chapter to less than 1000, causes queue crash

fix? change to "%04d"

**Comment by CarlosEsco** [comment] 2021-05-10 13:35
what um source has 1000+ page chapters lol

**Comment by Wyld-One** [comment] 2021-05-10 13:39
ehentai
Artist Max Blackrabbit

precious, luscious API
Waifu Academy 3DCG Gallery

**Comment by arkon** [comment] 2021-05-15 19:34
Duplicate of #1561

**Closed by arkon** 2021-05-15 19:34 UTC
