### ISSUE TITLE
[Feature Request] "Update all" extensions button

### ISSUE THREAD

**Issue by hyoretsu** [tachiyomiorg/tachiyomi#5363] opened 2021-06-10 01:18 UTC
## Why/User Benefit/User Problem
Simply put, sometimes there are a lot of extensions which need is to click on every single one of them. That isn't too much of an issue, although this would still be a good QoL feature, but today extensions got updated twice. And I mean 15 of them. Back when icons for ex-Madara extensions were mass added, there were around 30 extensions which we had to update.

## What/Requirements
Simply placing a button on top of Extensions tab that'd auto-click on all updatable extensions

**Comment by alessandrojean** [comment] 2021-06-10 01:25
Duplicate of #4815.

**Closed by alessandrojean** 2021-06-10 01:25 UTC
Labels: feature
