### ISSUE TITLE
go to Page Number

### ISSUE THREAD

**Issue by Slezula** [tachiyomiorg/tachiyomi#1325] opened 2018-03-26 13:59 UTC
**Issue/Request:**
go to Page Number
**Steps to reproduce (if applicable)**
Is it possible to add a transition to the page number in the popular manga window?
In the window of the popular manga, there is no way to quickly go down, for example, to the manga in the catholus under the number 1000, it will take a long time to flip through, and if I know that on page 70 of the mangs, then when I select page 15 I can quickly go to it.

![pages](https://user-images.githubusercontent.com/37804368/37909675-3d10da44-3114-11e8-8940-f49e667b8010.jpg)

**Other details:**
or add a scrollbar

**Comment by hXtreme** [comment] 2019-05-24 18:16
Scroll bar seems nice-ish but that might interrupt the UI for the side panels.

**Comment by arkon** [comment] 2021-01-04 20:34
Duplicate of #407

**Closed by arkon** 2021-01-04 20:34 UTC
Labels: feature
