### ISSUE TITLE
Series title duplicate prompt didnt trigger

### ISSUE THREAD

**Issue by Riztard** [tachiyomiorg/tachiyomi#7093] opened 2022-05-08 02:22 UTC
### Steps to reproduce

1. add manga a from source 1 to fav
2. add manga a from source 2 to fav by hold tap the thumbnail

### Expected behavior

triggering duplicate series title prompt thinggy

### Actual behavior

instantly added to library fav

### Tachiyomi version

0.13.4

### Android version

A11

### Device

Redmi 8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-05-08 02:31
Duplicate of #6640

**Closed by arkon** 2022-05-08 02:31 UTC
Labels: Bug
