### ISSUE TITLE
Chapters marked "-1" are sorted after highest chapter in descending chapter number order

### ISSUE THREAD

**Issue by FarzadBT** [tachiyomiorg/tachiyomi#7369] opened 2022-06-25 23:32 UTC
### Steps to reproduce

Two examples from different extensions

Extension: MANGA Plus by SHUEISHA
Series: Monster X

Extension: Mangadex
Series: Isekai Ojisan

Sort by chapter number descending and display as chapter number.

### Expected behavior

"-1" chapters land at the bottom of the list, before chapter "0" or "1".

### Actual behavior

"-1" chapters appear at the top of the list, before the highest available chapters.

### Tachiyomi version

0.13.4

### Android version

10

### Device

Galaxy S9+

### Other details

Especially annoying on the mentioned Monster X as in this configuration you have to scroll past an entire screen of "-1" chapters before you can see the newest chapter. 
![Screenshot_20220626-011155_Tachiyomi](https://user-images.githubusercontent.com/7903778/175793379-2f2ae264-5ea9-408d-a572-85a23c069eaa.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Saud-97** [comment] 2022-06-25 23:59
Duplicate of #7247

**Comment by Saud-97** [comment] 2022-06-26 00:00
Use Sorting provided by source until the update is released.

**Comment by arkon** [comment] 2022-06-26 00:00
This is intentional, -1 precedes 0.

**Closed by arkon** 2022-06-26 00:00 UTC
Labels: Bug
