### ISSUE TITLE
Auto download next chapter which isn't downloaded.

### ISSUE THREAD

**Issue by THElegend5** [tachiyomiorg/tachiyomi#5952] opened 2021-09-22 07:57 UTC
### Describe your suggested feature

Please add a feature to make it so that we can enable a toggle or something to make tachiyomi automatically download next chapter which isn't downloaded when you are done reading a chapter . Something like smart downloads in Netflix.

Reason : This way we can just keep 4-5 chapters of a manga and when we are done reading a chapter tachiyomi downloads the next chapter , this way we can save a lot of space and this way we also won't have to download a lot at a time which will decrease the load on the extensions ( probably , I am not sure ) .

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment] 2021-09-22 08:08
Duplicate of #3295

**Closed by curche** 2021-09-22 08:08 UTC
Labels: Feature request
