### ISSUE TITLE
[Bug] App Crashes while reading manga offline with trackers enabled

### ISSUE THREAD

**Issue by loocool2** [tachiyomiorg/tachiyomi#4229] opened 2021-01-01 20:19 UTC
## Device information
* Tachiyomi version: Stable 0.10.7
* Android version: 10
* Device: Lenovo Tab 4 8 Plus with Lineage 16.1

## Steps to reproduce
1. Attach a tracker to a manga
2. Download a chapter
3. Turn off internet connectivity
4. Read that chapter to the end

### Expected behavior
The tracker should not be able to update, but the chapter should be able to finish

### Actual behavior
The app crashes upon reaching the last page and restarts

**Comment by scb261** [comment] 2021-01-01 20:31
Duplicate of #4207

**Closed** 2021-01-01 21:31 UTC
Labels: bug
