### ISSUE TITLE
[Different Category Sort] 

### ISSUE THREAD

**Issue by D3stroy3rSama** [tachiyomiorg/tachiyomi#4517] opened 2021-02-20 05:43 UTC
Feature- Different Sort feature for different categories

Description- Gives own sort feature exclusively to that category. Like on 1st Tab if you want to sort by number of chapters left unread, and on another you want to sort alphabetically. You can add an toggle option in settings where user can choose whether to use same sort feature everywhere or different sort settings on different categories.

Benefits- Adds another layer of customisation. Better user experience..

**Comment by arkon** [comment] 2021-02-20 13:38
Duplicate of #3722

**Closed by arkon** 2021-02-20 13:38 UTC
Labels: feature
