### ISSUE TITLE
Image issues

### ISSUE THREAD

**Issue by randommangareader** [tachiyomiorg/tachiyomi#6857] opened 2022-04-03 03:11 UTC
### Steps to reproduce

I just want to ask if there is a solution to my problem. When I try to open the chapters with long strips  or continues images on my phone, my phone suddenly becomes really slow. Mostly, happens with chapters that has 3-4 pages only, but has a really long strip of pictures. There is also a times that, when I open the chapter with 3-4 pages only, Tachiyomi kept on crashing. Is it because of my phones low processing speed for high quality images?(Only happens in Tachiyomi. When I open my the chapter in the files app it is smooth)

### Expected behavior

Hope to receive a solution to my given problem.

### Actual behavior

Hope to receive a solution to my given problem.

### Crash logs

04-03 11:01:07.975 24977 27238 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:231)
04-03 11:01:07.975 24977 27238 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:104)
04-03 11:01:07.975 24977 27238 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1056)
04-03 11:01:07.975 24977 27238 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1029)
04-03 11:01:08.433 24977 27238 E DatabaseUtils: Writing exception to parcel
04-03 11:01:08.433 24977 27238 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://eu.kanade.tachiyomi.provider/ext_cache_files/tachiyomi_crash_logs.txt from pid=28206, uid=1000 requires the provider be exported, or grantUriPermission()
04-03 11:01:08.433 24977 27238 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:740)
04-03 11:01:08.433 24977 27238 E DatabaseUtils: 	at android.content.ContentProvider.semEnforceReadPermission(ContentProvider.java:659)
04-03 11:01:08.433 24977 27238 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:602)
04-03 11:01:08.433 24977 27238 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:231)
04-03 11:01:08.433 24977 27238 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:104)
04-03 11:01:08.433 24977 27238 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1056)
04-03 11:01:08.433 24977 27238 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1029)
04-03 11:02:03.154 24977 24995 E DatabaseUtils: Writing exception to parcel
04-03 11:02:03.154 24977 24995 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://eu.kanade.tachiyomi.provider/ext_cache_files/tachiyomi_crash_logs.txt from pid=29309, uid=1000 requires the provider be exported, or grantUriPermission()
04-03 11:02:03.154 24977 24995 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:740)
04-03 11:02:03.154 24977 24995 E DatabaseUtils: 	at android.content.ContentProvider.semEnforceReadPermission(ContentProvider.java:659)
04-03 11:02:03.154 24977 24995 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:602)
04-03 11:02:03.154 24977 24995 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:231)
04-03 11:02:03.154 24977 24995 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:104)
04-03 11:02:03.154 24977 24995 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1056)
04-03 11:02:03.154 24977 24995 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1029)
04-03 11:02:03.609 24977 27239 E DatabaseUtils: Writing exception to parcel
04-03 11:02:03.609 24977 27239 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://eu.kanade.tachiyomi.provider/ext_cache_files/tachiyomi_crash_logs.txt from pid=29309, uid=1000 requires the provider be exported, or grantUriPermission()
04-03 11:02:03.609 24977 27239 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:740)
04-03 11:02:03.609 24977 27239 E DatabaseUtils: 	at android.content.ContentProvider.semEnforceReadPermission(ContentProvider.java:659)
04-03 11:02:03.609 24977 27239 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:602)
04-03 11:02:03.609 24977 27239 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:231)
04-03 11:02:03.609 24977 27239 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:104)
04-03 11:02:03.609 24977 27239 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1056)
04-03 11:02:03.609 24977 27239 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1029)
04-03 11:02:32.917 24977 27239 E DatabaseUtils: Writing exception to parcel
04-03 11:02:32.917 24977 27239 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://eu.kanade.tachiyomi.provider/ext_cache_files/tachiyomi_crash_logs.txt from pid=29309, uid=1000 requires the provider be exported, or grantUriPermission()
04-03 11:02:32.917 24977 27239 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:740)
04-03 11:02:32.917 24977 27239 E DatabaseUtils: 	at android.content.ContentProvider.semEnforceReadPermission(ContentProvider.java:659)
04-03 11:02:32.917 24977 27239 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:602)
04-03 11:02:32.917 24977 27239 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:231)
04-03 11:02:32.917 24977 27239 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:104)
04-03 11:02:32.917 24977 27239 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1056)
04-03 11:02:32.917 24977 27239 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1029)
04-03 11:02:33.115 24977 27239 E DatabaseUtils: Writing exception to parcel
04-03 11:02:33.115 24977 27239 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://eu.kanade.tachiyomi.provider/ext_cache_files/tachiyomi_crash_logs.txt from pid=29309, uid=1000 requires the provider be exported, or grantUriPermission()
04-03 11:02:33.115 24977 27239 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:740)
04-03 11:02:33.115 24977 27239 E DatabaseUtils: 	at android.content.ContentProvider.semEnforceReadPermission(ContentProvider.java:659)
04-03 11:02:33.115 24977 27239 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:602)
04-03 11:02:33.115 24977 27239 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:231)
04-03 11:02:33.115 24977 27239 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:104)
04-03 11:02:33.115 24977 27239 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1056)
04-03 11:02:33.115 24977 27239 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1029)
App version: 0.13.1 (standard, d6386ce, 74, 2022-02-01T17:35Z)
Android version: 10 (SDK 29)
Android build ID: QP1A.190711.020.J610GUBU6CUE3
Device brand: samsung
Device manufacturer: samsung
Device name: j6primelte
Device model: SM-J610G
Device product name: j6primelteub

### Tachiyomi version

0.13.1

### Android version

Android 10

### Device

samsung galaxy j6+

### Other details

None

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2022-04-03 03:17
duplicate of #1908

**Closed by Seishirou101** 2022-04-03 03:17 UTC
Labels: Bug
