### ISSUE TITLE
Pin manga in a category or create sub category

### ISSUE THREAD

**Issue by FrancescaFre** [tachiyomiorg/tachiyomi#6334] opened 2021-12-09 11:08 UTC
### Describe your suggested feature

I would like to pin one or more specific manga on top of a category. 

Or have a sub category to differentiate monthly/weekly release 

Just to see at the First glance of the update without new categories to create (i have at least 8 tabs, pls save me)

### Other details

the pin feature 
Favorites
OnePunchMan* nagatoro* .. others not pinned..

Or the sub cat something like
Favorite
     - more favorite 
     - monthly
Backlog 
    - shojo
    - isekai
 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2021-12-09 13:13
Duplicate of #1803

**Closed by arkon** 2021-12-09 13:13 UTC
Labels: Feature request
