### ISSUE TITLE
Double pages in sideways view

### ISSUE THREAD

**Issue by PeyonManuel** [tachiyomiorg/tachiyomi#6261] opened 2021-11-22 18:52 UTC
### Describe your suggested feature

You know how in webtoons the longest pages are sideways so that you have to scroll a lot to see them? Well I thought that it would be nice to have an option to do that with double pages in mangas, as to better appreciate double pages since in vertical reading double pages look small in comparison to normal ones ,and that's the oposite of the effect they are supposed to have.
Hope I explained it right.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment] 2021-11-22 18:55
Duplicate of #149

**Closed by loocool2** 2021-11-22 18:55 UTC
Labels: Feature request

**Comment by PeyonManuel** [comment] 2021-11-22 18:57
It's not a duplicate of #149 I read that one before posting this and it's not what I'm proposing.

**Comment by arkon** [comment] 2021-11-22 19:06
There's no plans to automatically change image orientation.

**Comment by PeyonManuel** [comment] 2021-11-22 19:15
Is it too hard to do? I really don't feel double pages when reading on my phone as opposed to reading physical manga or in a monitor, they look too small in comparison.
