### ISSUE TITLE
Backspace not working correctly in search field

### ISSUE THREAD

**Issue by sirikid** [tachiyomiorg/tachiyomi#8888] opened 2023-01-11 04:20 UTC
### Steps to reproduce

1. click search button in Library
2. type in string starting with a digit or `@`, e.g. `1ab`
3. delete last char
4. input another char, e.g. `c`

### Expected behavior

`1ac` in search field

### Actual behavior

`abc` in search field

### Tachiyomi version

0.14.3

### Android version

9

### Device

Samsung Galaxy A50

### Other details

App version: 0.14.3 (standard, 817418f7c, 932, 2023-01-09T20:50Z)
Android version: 9 (SDK 28)
Android build ID: treble_arm64_bvN-userdebug 9 PQ3A.190801.002 eng.crossg.20190910.075457 test-keys
Device brand: Android
Device manufacturer: unknown
Device name: phhgsi_arm64_ab
Device model: SM-A405FM
Device product name: treble_arm64_bvN

Installed from F-Droid and I don't care

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-01-11 04:20
Duplicate of #8807

**Closed by arkon** 2023-01-11 04:20 UTC
Labels: Bug

**Comment by sirikid** [comment] 2023-01-11 04:24
> Duplicate of #8807

wtf, it is not
