### ISSUE TITLE
[Feature Request] Delete all read chapters

### ISSUE THREAD

**Issue by ghost** [tachiyomiorg/tachiyomi#2106] opened 2019-06-30 12:43 UTC
Any plan to add option for Deleting all readed chapters of all manga with one click? 
After i backup all manga to my pc i have to manually delete readed chapters.

**Comment by eshanrh** [comment] 2019-07-02 10:11
There's already an option to filter chapters by read, shouldn't be incredibly difficult to add an option to delete them.

Would we rather first filter by read and then have a button to delete, or just a button to delete all read? I think that the first one would offer more flexibility, allowing the user to delete all downloaded/delete all bookmarked or something like that

**Comment by metroid112** [comment] 2019-07-03 12:18
@eshanrh that would delete all chapters not only read ones.

@Fahad1998 you can try to enable the feature "Delete Chapter After Reading" from the settings page, mark all chapters as unread then use "Mark previous chapters as read" on the chapter you want.

Then you can just keep the setting up or go and change it back.

**Comment by eshanrh** [comment] 2019-07-03 12:20
Sorry, I meant to say that you should filter only read chapters using the filter button first

**Comment by arkon** [comment] 2021-01-04 20:54
Duplicate of #1364

**Closed by arkon** 2021-01-04 20:54 UTC
Labels: feature
