### ISSUE TITLE
Book view in Landscape

### ISSUE THREAD

**Issue by asitgujar2** [tachiyomiorg/tachiyomi#7510] opened 2022-07-11 04:42 UTC
In Landscape mode especially for tablets, having two pages side by side while reading manga or comics like book would be of great help also with reading direction from right to left (comics) and left to right (manga).

Thankyou 
![OpenComic-ScreenShot-3](https://user-images.githubusercontent.com/30930055/178189852-89c36728-8897-44ad-a319-b9d17edcdb7f.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment] 2022-07-11 05:34
Duplicate of #149

**Closed by loocool2** 2022-07-11 05:34 UTC
Labels: Feature request
