### ISSUE TITLE
Search complete library

### ISSUE THREAD

**Issue by crwagn** [tachiyomiorg/tachiyomi#5659] opened 2021-08-05 07:06 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

Add an additional search option with the "global search", maybe called "Library Search" after you type a title.

The current search will only search in the current category of the library, so if the title is in another category you will not see it unless you are also in the same category. 

Rather than losing the useful category specific feature, I would like a library search function along with the global search to find the manga quickly without having to jump to all of the categories individually. 

Useful for those of us who read far too many manga and are overly organized with many categories.

**Comment by Seishirou101** [comment] 2021-08-05 17:04
Duplicate of #4493

**Closed** 2021-08-05 17:07 UTC
Labels: Feature request
