### ISSUE TITLE
[Bug] <Some pages don't load and are left black>

### ISSUE THREAD

**Issue by BlazingAbyss** [tachiyomiorg/tachiyomi#5026] opened 2021-05-06 03:49 UTC
## Device information
* Tachiyomi version: 0.10.12
* Android version: 6 & 7
* Device: Htc One m8 & Bluestacks (Samsung galaxy s8 plus)

## Steps to reproduce
1. Open the manhwa "The Demon King Who Lost His Job" chapters: 170, 171 from any of these sources (mangahere, mangairo, mangakakalot, mangabat) 
2. Scroll or navigate to the last pages (7 in chapter 170, 6 in chapter 171)

### Expected behavior
The page should load.

### Actual behavior
The pages didn't load and were left black, and when I checked them from web view the pages were there.

## Other details
The same problem occurred in my phone and in bluestacks
This problem also happened with others like (My Wife Is A Demon Queen and Survival Story Of A Sword King In A Fantasy World)

**Comment by arkon** [comment] 2021-11-19 15:57
Duplicate of #1908

**Closed by arkon** 2021-11-19 15:57 UTC
Labels: Bug
