### ISSUE TITLE
Application sometimes freezes while reading

### ISSUE THREAD

**Issue by vnnc** [tachiyomiorg/tachiyomi#7532] opened 2022-07-14 21:14 UTC
### Steps to reproduce

Read

( I could not identify any specific behavior triggering this)

### Expected behavior

No freezing while reading.

### Actual behavior

While reading the application sometimes becomes unresponsive, It comes back to normal at some point but the freeze is long enough that android asks if the application should be terminated.

### Tachiyomi version

0.13.5

### Android version

Android 11 -  One UI 3.1

### Device

Galaxy Tab S5e

### Other details

This did not happen before updating to 0.13.5, I haven't experienced this in 0.13.4, may be a regression.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by DchanN** [comment] 2022-07-15 01:48
Duplicate of #7240

**Closed** 2022-07-15 02:34 UTC
Labels: Bug
