### ISSUE TITLE
Automatic Reading Mode selection

### ISSUE THREAD

**Issue by BhaturaGuy** [tachiyomiorg/tachiyomi#6627] opened 2022-02-11 07:41 UTC
### Describe your suggested feature

TachiyomiJ2K has this feature where somehow the webtoons automatically defaults to Reading Mode = Webtoon and displays a bar at the bottom if the user doesn't want that and manga uses the default Right to Left reading mode.

### Other details

>

https://user-images.githubusercontent.com/93109835/153553781-af412fda-fca4-4cd8-ba76-dc2d4ada2b59.mp4

This is what it looks like in TachiyomiJ2K.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment] 2022-02-11 08:00
Duplicate of #1664

**Closed by curche** 2022-02-11 08:00 UTC
Labels: Feature request
