### ISSUE TITLE
Continuous horizontally

### ISSUE THREAD

**Issue by Xennnnnn** [tachiyomiorg/tachiyomi#4272] opened 2021-01-08 02:50 UTC
Using tachiyomi for almost a year now and is the best of all app I have use but i would like tachiyomi to add "Continuous horizontal scrolling mode" for better reading experience in manga and manhwa/webtoon reader ~~♡♡♡~~

Thank you

**Comment by arkon** [comment] 2021-01-08 03:04
Duplicate of #2291

**Closed by arkon** 2021-01-08 03:04 UTC
Labels: feature
