### ISSUE TITLE
Visible boolean value over sliders

### ISSUE THREAD

**Issue by ViktorVoloshko** [tachiyomiorg/tachiyomi#7070] opened 2022-05-03 17:06 UTC
### Steps to reproduce

1. Enable Incognito mode or Downloaded only mode

### Expected behavior

Slider must just move to change its state.

### Actual behavior

Over slider appers text: "false" or "true" and slider jot moving, just changed its color.
![Screenshot_20220503-194918_Tachiyomi](https://user-images.githubusercontent.com/87974065/166503004-6d69a1af-927e-4e18-819e-f33596861e42.png)
![Screenshot_20220503-200000_Tachiyomi](https://user-images.githubusercontent.com/87974065/166503015-e4641040-ec2b-4de9-b293-4b323a32ef94.png)

### Tachiyomi version

0.13.4-4338

### Android version

12.1 [Android version: 12 (SDK 32)Android build ID: SP2A.220405.004]

### Device

POCO M3

### Other details

Using custom ROM – crDroid.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-05-03 17:07
Duplicate of #7004

**Closed by arkon** 2022-05-03 17:07 UTC
Labels: Bug
