### ISSUE TITLE
its not a bug its more of a suggestion. can u please add a merge option that can automatically thee same manga from other site. So that we we dont have to search the same thing on other extension again and again. it would really help a lot.

### ISSUE THREAD

**Issue by DevGoswami2629** [tachiyomiorg/tachiyomi#4671] opened 2021-03-19 06:37 UTC
its not a bug its more of a suggestion. can u please add a merge option that can automatically thee same manga from other site. So that we we dont have to search the same thing on other extension again and again. it would really help a lot.

**Comment by scb261** [comment] 2021-03-19 07:36
Duplicate of #886

**Closed** 2021-03-19 12:20 UTC
Labels: bug
