### ISSUE TITLE
Scroller covered by Download button 

### ISSUE THREAD

**Issue by ColinLabDev** [tachiyomiorg/tachiyomi#6592] opened 2022-02-07 12:43 UTC
### Steps to reproduce

Open a manga
Click the scroller or Scroll the scroller it can't scroll because the scroller is behind the download button 

### Expected behavior

The Scroll will be leveled and not hindered by anything

![Screenshot_20220207_200626_eu kanade tachiyomi](https://user-images.githubusercontent.com/73845522/152788423-c56f77a2-ccef-4526-8ffa-aa854b656cf7.jpg)

### Actual behavior

Download button covers scroll

![Screenshot_20220207_200512_eu kanade tachiyomi](https://user-images.githubusercontent.com/73845522/152788377-4d1b4ad0-dc38-4f21-ad31-a10ff240fa1d.jpg)
![Screenshot_20220207_200533_eu kanade tachiyomi](https://user-images.githubusercontent.com/73845522/152789064-9922bcfa-d038-4df7-8285-a94235905bb5.jpg)

Edit: Added a screen recording

https://user-images.githubusercontent.com/73845522/152794619-813892dd-9310-467d-a553-f2be0ec2559f.mp4

### Tachiyomi version

0.13.1,  r4139

### Android version

Android 9.1

### Device

Huawei Y9 2019

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Riztard** [comment] 2022-02-07 12:55
that doesnt look like version 0.13.1 or r4139

**Comment by arkon** [comment] 2022-02-07 13:22
Duplicate of #6311

**Closed by arkon** 2022-02-07 13:22 UTC
Labels: Bug
