### ISSUE TITLE
New filter option "Uploader"

### ISSUE THREAD

**Issue by xShevy** [tachiyomiorg/tachiyomi#8752] opened 2022-12-16 19:44 UTC
### Describe your suggested feature

I've been using Tachiyomi for a few weeks and there's only one thing that bothers me everything else is perfect.

At least in Spanish all Chapters have 2 or more "uploaders" or Scans or whatever so if you want to download all chapters you have to go clicking one by one if you are reading once you finish one chapter you have to skip one chapter and it is kinda annoying.

Here's an example: (453 Chapters and it only has 281)
![Screenshot_20221216-150546](https://user-images.githubusercontent.com/12452852/208170962-0e779af9-ff59-486c-837d-ecf10e8d2867.jpeg)

In order to improve this you can add another option for filters, I did this using Paint as an example of how it can look :D
![Screenshot_20221216-150606](https://user-images.githubusercontent.com/12452852/208173888-0163716b-6d7a-409d-b6e9-a432c959e9e1.jpeg)

There's Issue pretty similar to this but I'm gonna submit it anyways

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2022-12-16 19:47
Duplicate of #969

**Closed by Seishirou101** 2022-12-16 19:47 UTC
Labels: Feature request
