### ISSUE TITLE
[Feature Request] Customize the crop feature

### ISSUE THREAD

**Issue by AwesomeQuest** [tachiyomiorg/tachiyomi#4995] opened 2021-05-01 14:32 UTC
## Why/User Benefit/User Problem
Often, a certain comic has one consistent flaw, like a black line on all pages, and the crop feature is excellent at removing these, but it is often overzealous and removes too much of the page and thus harming the experience.

This is especially noticable in webtoons where vertical alignment is important

## What/Requirements
Ideally you could set it so it would only crop the bottom/top/right/left side of the page.

**Comment by treva888** [comment] 2021-11-05 20:21
hope this gets added

**Comment by arkon** [comment] 2022-07-10 00:07
Duplicate of #2331

**Closed by arkon** 2022-07-10 00:07 UTC
Labels: Feature request
