### ISSUE TITLE
Ability to select chapters based on translation group

### ISSUE THREAD

**Issue by Veyieneq** [tachiyomiorg/tachiyomi#8458] opened 2022-11-05 19:05 UTC
### Describe your suggested feature

For extensions that provide chapters based on different translation groups, it's a tad bit hard to read as there are too many duped chapters (possibly in other languages). Being able to select chapters based on the group would allow easy marking of unwanted chapters as "read", and then filtering the manga/manhua/manhwa for "unread" to read without any trouble.
![Screenshot_20221105-220314_Tachiyomi~2](https://user-images.githubusercontent.com/116973078/200136711-5abfdddd-8402-466f-9b00-3cd7bbf68ba5.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment] 2022-11-05 19:09
Duplicate of #969

**Closed by curche** 2022-11-05 19:09 UTC
Labels: Feature request
