### ISSUE TITLE
Downloaded Chapters icon that they have been downloaded is not highlighted. 

### ISSUE THREAD

**Issue by psyscope** [tachiyomiorg/tachiyomi#10227] opened 2023-12-10 17:30 UTC
### Steps to reproduce

This began in 6247 with the arrow button not being highlighted when a chapter is downloaded.  It shows as if it isnt, but it really is.  These chapters in the image have all been downloaded. 
![Screenshot_20231210-122447](https://github.com/tachiyomiorg/tachiyomi/assets/9994143/e6595489-d445-4b11-b54d-57dc7a03693f)
![Screenshot_20231210-122425](https://github.com/tachiyomiorg/tachiyomi/assets/9994143/b0b79226-573b-4bee-803e-dfa2298a5616)

### Expected behavior

The icon should show it was downloaded. 

### Actual behavior

As if it wasn't downloaded. 
![Screenshot_20231210-122447](https://github.com/tachiyomiorg/tachiyomi/assets/9994143/b23d0a02-2588-4cc7-8f1e-b800fe663725)
![Screenshot_20231210-122425](https://github.com/tachiyomiorg/tachiyomi/assets/9994143/29114aa1-c8f3-49f3-b69d-8b4facb90eee)

### Crash logs

App version: 0.14.7-6274 (standard, 8c21aa86e, 112, 2023-12-09T23:25Z)
Android version: 14 (SDK 34; build AP11.231020.016)
Device brand: google
Device manufacturer: Google
Device name: husky (husky_beta)
Device model: Pixel 8 Pro
WebView: Android System WebView 121.0.6167.7

### Tachiyomi version

App version: 0.14.7-6274 (standard, 8c21aa86e, 112, 2023-12-09T23:25Z) Android version: 14 (SDK 34; build AP11.231020.016) Device brand: google Device manufacturer: Google Device name: husky (husky_beta) Device model: Pixel 8 Pro WebView: Android System WebView 121.0.6167.7

### Android version

Android 14

### Device

Pixel 8 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-12-10 22:02
Duplicate of #10218

**Closed by arkon** 2023-12-10 22:02 UTC
Labels: Bug
