### ISSUE TITLE
Extra special feature for reading novels

### ISSUE THREAD

**Issue by hani1998** [tachiyomiorg/tachiyomi#6301] opened 2021-12-02 07:20 UTC
### Describe your suggested feature

That the sources of novels are added and added to the application and the application is able to read novels or manga at the same time

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2021-12-02 07:21
Duplicate of #685

**Closed** 2021-12-02 07:21 UTC
Labels: Feature request
