### ISSUE TITLE
Can't download 

### ISSUE THREAD

**Issue by PHBN1964** [tachiyomiorg/tachiyomi#9954] opened 2023-09-23 22:32 UTC
### Steps to reproduce

1. Change Download Location to Micro SD
2. Enter any source
3. Chose a manga
4. Press download button
5. After some time it's downloaded

### Expected behavior

The app should download the chapters of the manga in my library on my micro sd

### Actual behavior

The app doesn't download from any source the chapters, and say local invalid: com.hippo.unfile.TreeDocumentFile@c152518 

### Crash logs
```
--------- beginning of main
09-23 19:28:55.767 17345  2258 E DocumentsContractApi21: Failed to createFile
09-23 19:28:55.767 17345  2258 E DocumentsContractApi21: java.lang.IllegalStateException: Failed to mkdir /storage/4424-18F7/Tachiyomi/Downloads/NHentai (EN)/(C87) [Great Canyon (Deep Valley)] Hitozuma Ikkousen to Tanetsuke Enshuu ~Akagi-san to Kaga-san no Houman na Sentai Megakete Kimoota Chinpou Kyuukouka Bakugeki & Seichuu Gyorai de Ranshi Gekichin Hanshoku Ninmu Seikou seri [English] [Fated 
09-23 19:28:55.767 17345  2258 E DocumentsContractApi21: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2434)
09-23 19:28:55.767 17345  2258 E DocumentsContractApi21: 	at android.os.Parcel.createException(Parcel.java:2410)
09-23 19:28:55.767 17345  2258 E DocumentsContractApi21: 	at android.os.Parcel.readException(Parcel.java:2393)
09-23 19:28:55.767 17345  2258 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
09-23 19:28:55.767 17345  2258 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
09-23 19:28:55.767 17345  2258 E DocumentsContractApi21: 	at android.content.ContentProviderProxy.call(ContentProviderNative.java:732)
09-23 19:28:55.767 17345  2258 E DocumentsContractApi21: 	at android.content.ContentResolver.call(ContentResolver.java:2450)
09-23 19:28:55.767 17345  2258 E DocumentsContractApi21: 	at android.provider.DocumentsContract.createDocument(DocumentsContract.java:1380)
09-23 19:28:55.767 17345  2258 E DocumentsContractApi21: 	at com.hippo.unifile.DocumentsContractApi21.createFile(DocumentsContractApi21.java:5)
09-23 19:28:55.767 17345  2258 E DocumentsContractApi21: 	at com.hippo.unifile.TreeDocumentFile.createDirectory(TreeDocumentFile.java:30)
09-23 19:28:55.767 17345  2258 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.DownloadProvider.getMangaDir$app_standardRelease(DownloadProvider.kt:28)
09-23 19:28:55.767 17345  2258 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.Downloader.$r8$lambda$JCgUpr3y-rfjPLUIYFWcs54zFLc(Downloader.kt:25)
09-23 19:28:55.767 17345  2258 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.Downloader$$ExternalSyntheticLambda5.call(R8$$SyntheticClass:5)
09-23 19:28:55.767 17345  2258 E DocumentsContractApi21: 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:2)
09-23 19:28:55.767 17345  2258 E DocumentsContractApi21: 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:1)
09-23 19:28:55.767 17345  2258 E DocumentsContractApi21: 	at rx.Observable.unsafeSubscribe(Observable.java:10)
09-23 19:28:55.767 17345  2258 E DocumentsContractApi21: 	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:12)
09-23 19:28:55.767 17345  2258 E DocumentsContractApi21: 	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:12)
09-23 19:28:55.767 17345  2258 E DocumentsContractApi21: 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:10)
09-23 19:28:55.767 17345  2258 E DocumentsContractApi21: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
09-23 19:28:55.767 17345  2258 E DocumentsContractApi21: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
09-23 19:28:55.767 17345  2258 E DocumentsContractApi21: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
09-23 19:28:55.767 17345  2258 E DocumentsContractApi21: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
09-23 19:28:55.767 17345  2258 E DocumentsContractApi21: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
09-23 19:28:55.767 17345  2258 E DocumentsContractApi21: 	at java.lang.Thread.run(Thread.java:1012)
09-23 19:29:12.701 17345  2258 E DocumentsContractApi21: Failed to createFile
09-23 19:29:12.701 17345  2258 E DocumentsContractApi21: java.lang.IllegalStateException: Failed to mkdir /storage/4424-18F7/Tachiyomi/Downloads/NHentai (EN)/(C87) [Great Canyon (Deep Valley)] Hitozuma Ikkousen to Tanetsuke Enshuu ~Akagi-san to Kaga-san no Houman na Sentai Megakete Kimoota Chinpou Kyuukouka Bakugeki & Seichuu Gyorai de Ranshi Gekichin Hanshoku Ninmu Seikou seri [English] [Fated 
09-23 19:29:12.701 17345  2258 E DocumentsContractApi21: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2434)
09-23 19:29:12.701 17345  2258 E DocumentsContractApi21: 	at android.os.Parcel.createException(Parcel.java:2410)
09-23 19:29:12.701 17345  2258 E DocumentsContractApi21: 	at android.os.Parcel.readException(Parcel.java:2393)
09-23 19:29:12.701 17345  2258 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
09-23 19:29:12.701 17345  2258 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
09-23 19:29:12.701 17345  2258 E DocumentsContractApi21: 	at android.content.ContentProviderProxy.call(ContentProviderNative.java:732)
09-23 19:29:12.701 17345  2258 E DocumentsContractApi21: 	at android.content.ContentResolver.call(ContentResolver.java:2450)
09-23 19:29:12.701 17345  2258 E DocumentsContractApi21: 	at android.provider.DocumentsContract.createDocument(DocumentsContract.java:1380)
09-23 19:29:12.701 17345  2258 E DocumentsContractApi21: 	at com.hippo.unifile.DocumentsContractApi21.createFile(DocumentsContractApi21.java:5)
09-23 19:29:12.701 17345  2258 E DocumentsContractApi21: 	at com.hippo.unifile.TreeDocumentFile.createDirectory(TreeDocumentFile.java:30)
09-23 19:29:12.701 17345  2258 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.DownloadProvider.getMangaDir$app_standardRelease(DownloadProvider.kt:28)
09-23 19:29:12.701 17345  2258 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.Downloader.$r8$lambda$JCgUpr3y-rfjPLUIYFWcs54zFLc(Downloader.kt:25)
09-23 19:29:12.701 17345  2258 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.Downloader$$ExternalSyntheticLambda5.call(R8$$SyntheticClass:5)
09-23 19:29:12.701 17345  2258 E DocumentsContractApi21: 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:2)
09-23 19:29:12.701 17345  2258 E DocumentsContractApi21: 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:1)
09-23 19:29:12.701 17345  2258 E DocumentsContractApi21: 	at rx.Observable.unsafeSubscribe(Observable.java:10)
09-23 19:29:12.701 17345  2258 E DocumentsContractApi21: 	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:12)
09-23 19:29:12.701 17345  2258 E DocumentsContractApi21: 	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:12)
09-23 19:29:12.701 17345  2258 E DocumentsContractApi21: 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:10)
09-23 19:29:12.701 17345  2258 E DocumentsContractApi21: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
09-23 19:29:12.701 17345  2258 E DocumentsContractApi21: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
09-23 19:29:12.701 17345  2258 E DocumentsContractApi21: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
09-23 19:29:12.701 17345  2258 E DocumentsContractApi21: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
09-23 19:29:12.701 17345  2258 E DocumentsContractApi21: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
09-23 19:29:12.701 17345  2258 E DocumentsContractApi21: 	at java.lang.Thread.run(Thread.java:1012)
App version: 0.14.6 (standard, c615f4d, 101, 2023-04-16T15:14Z)
Android version: 12 (SDK 31)
Android build ID: S0RCS32.41-10-19-14
Device brand: motorola
Device manufacturer: motorola
Device name: caprip
Device model: moto g(30)
Device product name: caprip_retail
```

### Tachiyomi version

0.14.6

### Android version

Android 12 S

### Device

Moto G30

### Other details

Local of Downloaded content is ona Micro SD, and today I already downloaded some chapters without any problems from the same sources

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2023-09-25 17:20
you might need to give permissions again? it might being denied. Those are also really long names, so it might not like those either possibly

**Comment by christmovies** [comment] 2023-09-30 23:02
Do You have Android 11+? I think is Google fault(blame?)

**Comment by ramo21** [comment] 2023-11-17 03:33
Have same issue but on latest tachiyomi 0.14.7, and using Android version 9

**Comment by Minecodes** [comment] 2023-11-26 16:49
Same here with a Samsung Galaxy Tab S8+ (Android 13) and TachiyomiJ2K and this the official Tachiyomi client

**Comment by arkon** [comment] 2024-01-06 22:13
Closing as duplicate of #3373

**Closed by arkon** 2024-01-06 22:13 UTC
Labels: Bug
