### ISSUE TITLE
Two-way Tracking

### ISSUE THREAD

**Issue by Fella2189** [tachiyomiorg/tachiyomi#6731] opened 2022-03-03 22:44 UTC
### Describe your suggested feature

I was wondering if it would be possible to add a feature by which if I update my progress in a tracker e.g MAL, when I go back to tachiyomi, the progress of the series would be updated as well? That way, there can be a form of syncing across devices without the need for a separate place to store an online sync.
Thanks!

Edit: Just flicked through previous open issues and found #1626 which said something similar I believe

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by BradleyDS2** [comment] 2022-07-05 12:06
Would love to see this added.
I use a tablet for reading Manga at home, and use my phone when outside of the house or the tablet is being used by someone else, so having progress synced across both devices would be incredibly convenient.

**Comment by arkon** [comment] 2022-07-09 22:39
Duplicate of #1626

**Closed by arkon** 2022-07-09 22:39 UTC
Labels: Feature request
