### ISSUE TITLE
[Feature Request] <a separate bookmark page and being able to bookmark a single page>

### ISSUE THREAD

**Issue by handhsjsj** [tachiyomiorg/tachiyomi#4367] opened 2021-01-29 21:01 UTC
Can you please add a feature where you can bookmark a specific page and also add a title to it. And then add a section called bookmarks so we can go back to it? 
--
## Why/User Benefit/User Problem
This can help going back to important scenes in a manga where there is important information or simply to go back to your favorite moment if you want to read it again.

## What/Requirements
When clicking the bookmark icon in a chapter it only bookmarks the page that I'm currently reading. Also a window pops up where i can write a title and/or a note then click on save. If i don't want to write a title or a note and just want to bookmark it then leave it blank and click save.
Now when I want to go back to it I'll open the manga and there would be a section called "bookmarks" (maybe next to web view and tracking. Or at the top right) and when i open it it'll have all the bookmarks and notes for that manga. Ps: i can edit the notes and they would be shown as a compact list with only the title and the number of chapter and when i open it I can read the full notes.

**Comment by scb261** [comment] 2021-01-29 21:35
Duplicate of #565

**Closed** 2021-01-29 23:13 UTC
Labels: feature
