### ISSUE TITLE
Adding WebP Support for Local Covers

### ISSUE THREAD

**Issue by rapdodge** [tachiyomiorg/tachiyomi#5829] opened 2021-08-31 09:25 UTC
### Steps to reproduce

1. Adding Local Sources
2. The content should be .webp

### Expected behavior

When change cover with WebP image, should be successfully

### Actual behavior

Cover in local sources can't displayed if the image is WebP

### Tachiyomi version

0.12.1

### Android version

Android 10

### Device

Nokia 3.1 Plus

### Other details

Here the video proof
https://streamable.com/uho15u

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by rapdodge** [comment] 2021-08-31 09:40
Update, not only WebP, but jpg too...

Video proof
https://streamable.com/5fsa1n

Crash logs
--------- beginning of main
08-31 16:34:48.007 21169 21169 E GraphicExt: GraphicExtModuleLoader::CreateGraphicExtInstance false
08-31 16:34:52.068 21169 21169 E GraphicExt: GraphicExtModuleLoader::CreateGraphicExtInstance false
08-31 16:34:56.352 21169 21223 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
08-31 16:34:56.352 21169 21223 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
08-31 16:34:56.506 21169 21223 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
08-31 16:34:56.507 21169 21223 E DRM/DcfDecoder: decodeDrmImageIfNeeded stream caught ClassCastException 
08-31 16:35:10.068 21169 21169 E GraphicExt: GraphicExtModuleLoader::CreateGraphicExtInstance false
App version: 0.12.1 (standard, 85791a9, 67, 2021-08-06T21:36Z)
Android version: 10 (SDK 29)
Android build ID: 00WW_3_15Z
Device brand: Nokia
Device manufacturer: HMD Global
Device name: ROON_sprout
Device model: Nokia 3.1 Plus
Device product name: Rooster_00WW

**Comment by ghostbear** [comment] 2021-08-31 09:44
It does support WebP but there is currently a bug with setting a custom cover for Local Manga

Duplicate of https://github.com/tachiyomiorg/tachiyomi/issues/5395

**Closed** 2021-08-31 12:33 UTC
Labels: Bug
