### ISSUE TITLE
Filter Saving

### ISSUE THREAD

**Issue by VirYouth** [tachiyomiorg/tachiyomi#7487] opened 2022-07-09 08:52 UTC
### Describe your suggested feature

Being able to save filter in extensions or atleast being able to go back to latest filter after closing the extension

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-07-09 13:15
Duplicate of #1484

**Closed by arkon** 2022-07-09 13:15 UTC
Labels: Feature request
