### ISSUE TITLE
Swiping categories in category tab is jittery after the update.

### ISSUE THREAD

**Issue by AgrMayank** [tachiyomiorg/tachiyomi#8368] opened 2022-10-30 16:58 UTC
### Steps to reproduce

1. Open tachiyomi 
2. Swipe left or right in category tabs

The animation feels sluggish/slow like it's running on 30hz on a 120hz phone. This didn't happen with 0.14.0

### Expected behavior

The animation should be smooth when swiping pages for categories in home.

### Actual behavior

The animation feels sluggish/slow like it's running on 30hz on a 120hz phone. This didn't happen with 0.14.0

### Tachiyomi version

0.14.1

### Android version

13

### Device

Samsung S22

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-10-30 17:06
Duplicate of #8310

**Closed** 2022-10-30 17:06 UTC
Labels: Bug
