### ISSUE TITLE
Sharing manga page stopped working recently

### ISSUE THREAD

**Issue by fotuoh** [tachiyomiorg/tachiyomi#8488] opened 2022-11-09 18:47 UTC
### Steps to reproduce

1. Open any manga;
2. Long press the manga page;
3. Click the "Share" button;
4. Error message - "No apps can perform this action". 

### Expected behavior

Tachiyomi would automatically write down the Chapter and Page numbers and we could forward it to the desired app. Android shows "Apps to share via", such as Discord, Messenger, WhatsApp, etc.

### Actual behavior

Error message shows "No apps can perform this action", with no options for sharing available. See image attached below:

![Screenshot_20221109_130911](https://user-images.githubusercontent.com/34987694/200911881-b098d6c7-7f42-4403-a54d-dc5ca223bbc2.jpg)

### Crash logs

The app is not crashing. Please let me know if I should update this report with my crash logs regardless.

### Tachiyomi version

0.14.2

### Android version

Android 9

### Device

HUAWEI Nova 3

### Other details

Interesting enough, while the "Share" button for specific Pages is not working anymore, the "Share" button for the whole Manga itself still works as normal. My phone has remained the same since I started using Tachiyomi. Attached below what the share button looks like when working properly:

![Screenshot_20221109_154127_com huawei android internal app](https://user-images.githubusercontent.com/34987694/200914551-28675707-4850-45c0-b7db-e8006cbbb3d1.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-11-20 03:42
Maybe fixed in preview (as a duplicate of #8539).

**Closed by arkon** 2022-11-20 03:42 UTC
Labels: Bug
