### ISSUE TITLE
backup to webdav

### ISSUE THREAD

**Issue by JackiePenghe** [tachiyomiorg/tachiyomi#9696] opened 2023-07-10 17:56 UTC
### Describe your suggested feature

I want a new function : backup anything( or something support backup) to webDAV.
it likes reading tool "legado".
I can comfig my own webDAV server.

All text content translate by translation tools.

### Other details

mothing

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-07-10 19:43
Duplicate of #912

**Closed by arkon** 2023-07-10 19:43 UTC
Labels: Feature request
