### ISSUE TITLE
Allow filtering by unread/read chapters on the Updates screen

### ISSUE THREAD

**Issue by Derjjerd** [tachiyomiorg/tachiyomi#9476] opened 2023-05-08 03:03 UTC
### Describe your suggested feature

As a user
I want to apply a filter on the Updates screen
So that I can either view all or a subset (read/unread) of available updates

---
On the "Updates" screen, a toggle/drop-down would be rendered next to the "refresh" icon (or somewhere else in the header) that allows the user to either: 

a) toggle between all updates/only unread updates 

b) select from a drop-down to filter by all/unread/read updates (in the case where there might be some value to viewing only already read updates).

### Other details

I'm torn on whether there's any merit to showing only "read" updates, but adding that as an option as well shouldn't be a very heavy lift. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment] 2023-05-08 04:50
Duplicate of #3365

**Closed** 2023-05-08 04:51 UTC
Labels: Duplicate, Feature request
