### ISSUE TITLE
[Bug] False Unread chapter counts on ongoing comics 

### ISSUE THREAD

**Issue by rsmyst** [tachiyomiorg/tachiyomi#4620] opened 2021-03-09 17:16 UTC
---
Description:
Incorrect unread chapter count displaying on comics. 

## Device information
* Tachiyomi version: 0.10.9
* Android version: 10
* Device: Galaxy S9+

Requirements for Bug reproduction:
Should've already had a comic tracked on a tracker. For example, I already have read God of Highschool comic up to chapter 500 on my laptop and had tracked it there. 

## Steps to reproduce
1. Add said comic to tracker in tachiyomi and add to library (GOH in this case)
2. Read the latest chapters on tachiyomi 

### Expected behavior
Tachiyomi will intelligently understand that if 500 chapters are tracked already, it means 500 chapters have been read and it shouldn't show up in unread chapter count. Only any latest chapter not yet tracked should show up as unread.
The point of unread chapters is to track well... unread chapters. Not chapter which weren't read ON TACHIYOMI.

### Actual behavior
Unread count includes latest unread chapters along with every chapter of the comic which we didn't read through tachiyomi.

## Other details
I use anilist.

**Comment by arkon** [comment] 2021-03-09 17:21
Duplicate of #1626

**Closed by arkon** 2021-03-09 17:21 UTC
Labels: bug
