### ISSUE TITLE
Save search filters

### ISSUE THREAD

**Issue by om3gakais3t** [tachiyomiorg/tachiyomi#1484] opened 2018-06-12 22:06 UTC
**App version:**
0.7.4
**Issue/Request:**
Requesting a save search filter function
**Steps to reproduce (if applicable)**

 1.Select catalogues
 2.open browse and then select search filter and enter the filter
 3.going back to catalogues and then browse the same catalogue then select search filter

**Other details:**
Actually a request to enable save search

**Comment by MatteCrystal** [comment] 2021-01-26 18:55
### Below is a more fleshed out draft of how saved filters might work.

It would be great if you were allowed to save multiple filters at once. You could then view your saved filters from a list and choose the one you feel like using. 

So for example if you often find yourself searching the tags **(naruto, ramen)** sorted by **(most recent)** but you also find yourself commonly searching the tags **(attack on titan, rage, eren)** sorted by **(most popular)**

It can be really annoying manually typing in these filters each time and the more custom searches you have the more annoying it becomes. 

It would be fantastic if above the filter button was a second button called saved filters which opens a list of saved filters which you could click to immediately search said filter preset. Then if you long press it could give you options like delete, rename, or edit. 

If adding another button above filters is undesirable then you could instead integrate these features directly into the filter button itself as another option.

**Comment by joseph619** [comment] 2021-02-08 06:10
This currently exists in TachiyomiSY, so it could be imported from there if the code is neat

**Comment by DarAmetis** [comment] 2021-02-26 13:35
The first request was over 2 years ago. Does this mean that this feature will not be introduced?

**Comment by ve1mi** [comment] 2021-09-07 19:08
It seems to me that in 3 years it's possible to add this useful function.

**Comment by Volern** [comment] 2022-03-24 13:24
Are we ever going to get this added? Seems like such a simple thing to do but no one has made it happen yet.

**Comment by Palloxin** [comment] 2022-03-25 21:58
Just adding this feature would make the app jump to 1.04 version

**Comment by arkon** [comment] 2022-04-05 21:41
Superfluous comments aren't helpful.

If someone wants to, they can refer to the implementation in the TachiyomiSY fork and PR it here. It'd likely need to be cleaned up a bit.

**Comment by arkon** [comment] 2023-10-08 20:44
Duplicate of #779

**Closed by arkon** 2023-10-08 20:44 UTC
Labels: Feature request
