### ISSUE TITLE
[Sub Category]

### ISSUE THREAD

**Issue by Humam-Hamdan** [tachiyomiorg/tachiyomi#4519] opened 2021-02-20 11:46 UTC
## Why/User Benefit/User Problem
I'll explain the usage in an example:
someone has these categories:
reading en, reading fr, reading ch, reading H
he can set them all in a category called: 
reading: #and then
     en
     fr
    ch
    H
etc, it's best if one could do two or three subs, like:
main:
  sub1:
    sub2:
     sub3:

## What/Requirements
from the category in more, one can move a category to ba a sub to another one

**Comment by arkon** [comment] 2021-02-20 13:36
Duplicate of #1803

**Closed by arkon** 2021-02-20 13:36 UTC
Labels: feature
