### ISSUE TITLE
Ability to hide some titles from extensions.

### ISSUE THREAD

**Issue by Lahnshen** [tachiyomiorg/tachiyomi#10196] opened 2023-12-01 22:34 UTC
### Describe your suggested feature

Ability to hide some titles from the results within extension such as in the default page/latest page/search results.

Grant users the ability to hide some of the titles which they don't want to see and not show them until they are set visible again from the extension settings.

This can help users prevent some titles with explicit cover from appearing when opening an extension as this sometimes also happens in extensions which are not marked 18+, sometimes these entries appear on the upper rows directly when opening an extension such as in `Mangabat/Mangakakalot`.

I hope this feature request will be taken into consideration, thanks.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-12-01 22:40
Duplicate of #2371

**Closed by arkon** 2023-12-01 22:40 UTC
Labels: Feature request
