### ISSUE TITLE
Remove Read manga from the Update Tab

### ISSUE THREAD

**Issue by KanariYabai** [tachiyomiorg/tachiyomi#8062] opened 2022-09-24 11:50 UTC
### Describe your suggested feature

To remove all the read Manga that is on the Update tab once its done. I have alot of read manga from the update tab but it still remains there and i need to scroll more to look for more unread updates 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-09-24 16:00
Duplicate of #3365

**Closed by arkon** 2022-09-24 16:00 UTC
Labels: Feature request
