### ISSUE TITLE
Incognito mode improvements

### ISSUE THREAD

**Issue by NorseFenris** [tachiyomiorg/tachiyomi#10115] opened 2023-11-06 17:36 UTC
### Steps to reproduce

Turn on incognito mode and read a chapter from any title with attached trackers.

### Expected behavior

No logged history. At least not when they are set to "planning to read" or anything that is not "Reading". 

Sometimes you just want to check if you want to start reading a title marked as planned or maybe you are taking a break and want to see if the latest chapter is interesting enough to catch up to. 

Currently I have no clue what the point of the incognito mode is. Why would I care if it logs my history on the app when it is not tracked anywhere? That's a simple mark unread, while an updated tracker could make you completely lose track of where you were before, especially if it is a title that has been migrated from a source that removed chapters, since the app doesn't remember chapters that don't exist. Examples of such sites is MangaPlus. 

Maybe add an option, like an ON/OFF button, to not track even when trackers are on?

### Actual behavior

It logs history and updates the trackers.

### Tachiyomi version

0.14.7

### Android version

Android 13

### Device

Samsung s22+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-11-06 17:43
Duplicate of #7228

**Closed** 2023-11-06 17:44 UTC
Labels: Bug, Duplicate

**Comment by NorseFenris** [comment] 2023-11-06 17:45
Not really a duplicate, they are writing this "When a manga is not being tracked, It should not log chapter read history but still mark the chapter as read upon reading." I  am asking for when a manga IS tracked.

**Comment by arkon** [comment] 2023-11-06 17:51
The closure was implementing no automatic tracker updates while incognito is enabled.

**Comment by NorseFenris** [comment] 2023-11-06 18:00
Ok, but it still does it for me, so then it is still a bug for me.

![Screenshot_20231106_185518_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/66540317/7cdd5cc6-41b9-4275-8ed5-92cbb876c5dd)

![Screenshot_20231106_185549_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/66540317/05e803dc-ab79-4d0c-8375-e6f013dfda37)

![Screenshot_20231106_185932_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/66540317/1d6e4944-8a5a-419e-b7b2-37025b87720f)


![Screenshot_20231106_185602_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/66540317/8ea9f2e5-3da8-4a11-8329-7431e390d8c5)

![Screenshot_20231106_185611_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/66540317/ebd3fe1b-096a-4b5b-8ccb-0ce503c4e8d8)

**Comment by NorseFenris** [comment] 2023-11-06 18:03
Oh, ok!
