### ISSUE TITLE
Tablet interface makes issue titles unreadable

### ISSUE THREAD

**Issue by bgarnz** [tachiyomiorg/tachiyomi#5346] opened 2021-06-08 04:14 UTC
## Device information
* Tachiyomi version: 0.11.1
* Android version: 9.0
* Device: Amazon Fire HD 8, 10th gen

## Steps to reproduce
1. Used the app and looked at it with my eyes

## Issue/Request
The new tablet interface now makes issue titles unreadable if they're more than a few characters long. There is no way to change this at the moment. 

## Other details
![Screenshot_20210608-000029](https://user-images.githubusercontent.com/66689464/121121823-565cd380-c7ee-11eb-912f-a288eb914cc7.png)

**Comment by loocool2** [comment] 2021-06-08 04:15
Duplicate of #5272

**Closed by loocool2** 2021-06-08 04:15 UTC
