### ISSUE TITLE
"Cover-only grid" display mode bug when using per-category settings for display

### ISSUE THREAD

**Issue by kou9221** [tachiyomiorg/tachiyomi#6915] opened 2022-04-13 05:09 UTC
### Steps to reproduce

1. Open library/filter sheet
2. Go to display tab and change the display mode into "Cover-only grid" in my "Reading" categories
3. When switching to other categories it should remain as "Cover-only grid"

### Expected behavior

When switching to other categories it should remain as "Cover-only grid"

### Actual behavior

When i switch to other categories it remains in "Compact grid" display mode

### Tachiyomi version

0.13.2

### Android version

Android 12

### Device

Redmi Note 10 with Custom Rom named PixelOS

### Other details

As you can see when I change display mode other than cover-only grid it's normal

https://user-images.githubusercontent.com/98811570/163104363-1f1fd36b-9d97-4ac7-a73a-c75c6c5451f5.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by micaelagimenez** [comment] 2022-04-16 17:23
this is strange, i can't reproduce the bug myself

**Comment by alessandrojean** [comment] 2022-04-16 17:26
Looks like you enabled the Settings per category for viewing and sorting in the Library settings. Try disabling it and it should apply to all categories.

**Comment by kou9221** [comment] 2022-04-17 04:29
> Looks like you enabled the Settings per category for viewing and sorting in the Library settings. Try disabling it and it should apply to all categories.
> 
> I have it disabled and I can't reproduce either. If you have it enabled, it's the expected behavior.

I intentionally enabled it, what I mean by "bug" is when using per-category settings for sort and display the cover-only grid go back/changes to what my other category display mode when switching between categories.

I take "list display mode" as an example in the video to see that the bug only applies to cover only grid and not the other three display mode

Anyway thanks for info!

**Comment by micaelagimenez** [comment] 2022-04-17 11:17
in my case, even with those settings on I cannot reproduce the bug you are showing, it works perfectly fine for me

**Comment by arkon** [comment] 2022-04-20 22:33
There was briefly a dev version where there was an incorrect overlap between some of the sort and display flags, but I don't think that was ever released as a stable nor preview version. It may also be possible that the data's polluted if it's coming from a backup from a fork.

Closing this since I can't reproduce this, but feel free to reopen/open a new one if you have consistent reproduction steps on a fresh install/library.

**Closed by arkon** 2022-04-20 22:33 UTC
Labels: Bug
