### ISSUE TITLE
There is no way to turn off vibration when quick switching pages using the slider

### ISSUE THREAD

**Issue by Tashotakoe** [tachiyomiorg/tachiyomi#6291] opened 2021-11-28 02:39 UTC
### Describe your suggested feature

So this is very annoying. Apparently, this was added in recent versions, but there is no way to disable it. When you do this often quickly looking through a bunch of different hentai a day, it gets to an extremely serious problem, you know

### Other details

Ahem, yes, thanks in advance

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2021-11-28 03:15
Duplicate of #6153

**Closed by arkon** 2021-11-28 03:15 UTC
Labels: Feature request
