### ISSUE TITLE
Library Search and Selecting all 

### ISSUE THREAD

**Issue by Architect-Ivy** [tachiyomiorg/tachiyomi#8441] opened 2022-11-04 06:11 UTC
### Steps to reproduce

1. Go to Library
2. Search one genre (for example horror)
3. Select all button from the right top screen 

### Expected behavior

Expecting to only select the horror genre

### Actual behavior

But this happened instead, it selected all in that category 

Note: I only have 38 horror genre manga and I have 643 overall manga

![Screenshot_20221104-134920_Tachiyomi](https://user-images.githubusercontent.com/107328165/199900088-a20cc9d8-9b80-45e5-ad7c-74f9c5589831.jpg)

### Tachiyomi version

0.14.2

### Android version

Android 11

### Device

Samsung Galaxy 

### Other details

Even back on version 0.14.1 is even much more better, if only the "app crashing while reading" was the only issue, I rather go back, issue for this version has too many to point out, lagging while switching categories, app crashing while scrolling in categories, searching 1 genre and selecting all that genre should happened but it selected all in that categories instead, app crashing while reading is still an issue, searching for new release/latest does not showcase all new releases and more, honestly it's ridiculously how it downgraded on only 1 version update, is the app updating forward or the other way ? Can't tell

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment] 2022-11-04 06:51
Duplicate of #8287

**Closed by AntsyLich** 2022-11-04 06:51 UTC
Labels: Bug
