### ISSUE TITLE
App crashes when I save a chapter image

### ISSUE THREAD

**Issue by Jeffersonrsds** [tachiyomiorg/tachiyomi#5742] opened 2021-08-18 17:43 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.0](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.12.0)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.12.1

### Android version

8.1.0

### Device

Samsung  J7 Pro.

### Steps to reproduce

1-open a manhwa 2-open any chapter 3-save any page

### Expected behavior

save pages and the APP doesn't close by itself.

### Actual behavior

The APP closes by itself when saving a page.

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/7009099/tachiyomi_crash_logs.txt)

### Other details

this happened in the old version of the APP

**Comment by arkon** [comment] 2021-11-19 15:54
Duplicate of #5375

**Closed by arkon** 2021-11-19 15:54 UTC
Labels: Bug
