### ISSUE TITLE
auto restart downloads

### ISSUE THREAD

**Issue by Jkccl9** [tachiyomiorg/tachiyomi#959] opened 2017-08-27 09:54 UTC
Getting a 503 error in most downloads which stops the download after a couple of pages and then jumps to the next in queue till it gets to the end of the queue, the download continues if I press the ▶ and then stops after a couple of pages again. Can an auto restart download be added in settings so then I don't have to sit there and watch the download progress and then manually press the ▶ button in top right hand side multiple times. It gets a bit tedious if I try download 30+ chapters in one go... ;) Also I don't know what the underlying cause for a 503 error is? Thanks

Version: v0.6.1
Nougat DU

**Comment by 444nonymous** [comment] 2017-08-27 21:38
That happens a lot when the connection is not perfect. It is very annoying. Since Tachoyomi is mainly a downloader app, it should akways retry until downloads complete.

1. When downloads are still queued, It should check if there is an internet connection. If not, wait / recheck until found.
2. Then retry forever, because with bad connections the default setting would only download a few images of a chapter, jump to the next and repeat. It does not download any chapter and after a while stops. It has to be retried manually. 
3. Only stop retying when internet connection is lost, and jump to point 1.

https://github.com/inorichi/tachiyomi/issues/828 Could also be implemented.

**Comment by jondoe2021** [comment] 2021-03-29 05:50
A lot of seemingly random issues tied to this one. People like to think they understand the problem.

Whether its caused by "auto-pause", a lack of "auto-resume", or a lack of "auto-re-download", the commonality amongst all reported issues is that Downloads stop while they are going.

As a Sr Software Engineer, here are a couple approaches I can recommend. All 3 would be required for a "complete" solution:

(1) If 1 download is stuck without progress, save it's progress and start another one, much like how CPU's decide which same-priority-level processes get to run next. Basically something to prioritize downloads that are actually making progress.

(2) A message queue or system inbox of some kind to communicate background-job feedback to the user. I would bet that there's good logical reason for the downloader to pause itself. The core issue is that users don't know why. I'd bet it's as simple as "the remaining downloads were attempted and failed to download"... for whatever reasons... timeouts, slowness, DNS, etc. Just let the user know. Communication is key.

(3) Since downloads do get auto-paused from time to time, and since network stability is a universal issue for everyone/everything, it would be a good idea to have an option to resume/retry all paused downloads every 15min/hour/day/etc... Feature would need to be disabled by default to reduce risk of accidental mobile data overages for those that don't restrict downloads over WIFI.

**Comment by Jaykoerner** [comment] 2021-05-13 19:20
I would add a something(s) to the list, 

When you add something to the download queue it has one or more of the following

(1) a option to unpause the queue from within the chapter list

(2) a toggle option in settings for a persistent notification of download status whenever a queue exists

And/or

(3) the option to set the chapters being added to the queue as priority and move them to the top of the list(with  in place of item (1) being able to restart the queue for just the items currently being added )


I state these because i assume as in my case the main pain with the download queue is that the user is attempting to download a a series while reading it,in the case of a paused queue leading to them having to leave the series and enter settings to resolve the issue.



> A lot of seemingly random issues tied to this one. People like to think they understand the problem.
> 
> Whether its caused by "auto-pause", a lack of "auto-resume", or a lack of "auto-re-download", the commonality amongst all reported issues is that Downloads stop while they are going.
> 
> As a Sr Software Engineer, here are a couple approaches I can recommend. All 3 would be required for a "complete" solution:
> 
> (1) If 1 download is stuck without progress, save it's progress and start another one, much like how CPU's decide which same-priority-level processes get to run next. Basically something to prioritize downloads that are actually making progress.
> 
> (2) A message queue or system inbox of some kind to communicate background-job feedback to the user. I would bet that there's good logical reason for the downloader to pause itself. The core issue is that users don't know why. I'd bet it's as simple as "the remaining downloads were attempted and failed to download"... for whatever reasons... timeouts, slowness, DNS, etc. Just let the user know. Communication is key.
> 
> (3) Since downloads do get auto-paused from time to time, and since network stability is a universal issue for everyone/everything, it would be a good idea to have an option to resume/retry all paused downloads every 15min/hour/day/etc... Feature would need to be disabled by default to reduce risk of accidental mobile data overages for those that don't restrict downloads over WIFI.

**Comment by arkon** [comment] 2022-07-09 21:54
Closing in favour of #7492

**Closed by arkon** 2022-07-09 21:54 UTC
Labels: Feature request
