### ISSUE TITLE
using webdav to synchronize between devices

### ISSUE THREAD

**Issue by sqq135** [tachiyomiorg/tachiyomi#7691] opened 2022-08-06 01:09 UTC
### Describe your suggested feature

![Screenshot_20220806_085650_com haleydu du](https://user-images.githubusercontent.com/78015121/183227484-071512a4-a888-4ac6-b1cd-88988bc13c62.jpg)
I found a chinese version which provide webdav function to synchronize between devices. I used it in my pad and phone, but it didn't update since last year. 

### Other details

I could download from https://haleydu.lanzoui.com/tp/iO3DTtkrheh
if my advice is usefull, I will very honored.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment] 2022-08-06 01:42
Unfortunately, that Tachiyomi fork being closed source makes it much harder for us to copy their implementation and use it int he main app

**Comment by arkon** [comment] 2022-08-06 02:15
Yeah, someone found this a while back but it's both closed source and was built using a packer to avoid easy reverse engineering.

WebDAV could be a valid option, but this is ultimately a duplicate of #912.

**Comment by sqq135** [comment] 2022-08-06 02:15
> Unfortunately, that Tachiyomi fork being closed source makes it much harder for us to copy their implementation and use it in the main app. If you can get the creator to open-source it, that would be helpful.

I would contact the author, but I didn't have too much hope on it. Many APP i used sustain webdav function which is very convenient on different devices. If you need, I would provide some open source APP from github, which are popular in China.

**Closed by arkon** 2022-08-06 02:15 UTC
Labels: Feature request

**Comment by AntsyLich** [comment] 2022-08-06 15:03
> If you need, I would provide some open source APP from github, which are popular in China.

It'll be very helpful if you can

**Comment by sqq135** [comment] 2022-08-06 15:44
> > If you need, I would provide some open source APP from github, which are popular in China.
> 
> It'll be very helpful if you can

The first is a very popular reading APP and I think it's synchronous function is the best.(And it can download books from webdav.)
The second is a online multifunctional video app. But it's great complex, so I use it few times.
The third is a very practical anime APP. I found it in gathub, but the author delet it.

https://github.com/gedoor/legado
https://github.com/qiusunshine/
the third https://github.com/SkyD666(he delet the project), I upload the apk to cloud.https://drive.google.com/file/d/1-6p5o3_0N24HPRg8NykpGDrP0ODMxO2_/view?usp=drivesdk

**Comment by sqq135** [comment] 2022-08-06 15:50
> > > If you need, I would provide some open source APP from github, which are popular in China.
> > 
> > 
> > It'll be very helpful if you can
> 
> The first is a very popular reading APP and I think it's synchronous function is the best.(And it can download books from webdav.) The second is a online multifunctional video app. But it's great complex, so I use it few times. The third is a very practical anime APP. I found it in gathub, but the author delet it.
> 
> https://github.com/gedoor/legado https://github.com/qiusunshine/ the third https://github.com/SkyD666(he delet the project), I upload the apk to cloud.https://drive.google.com/file/d/1-6p5o3_0N24HPRg8NykpGDrP0ODMxO2_/view?usp=drivesdk

The three APP all can synchronize by webdav. I don't know whether they can support English.
