### ISSUE TITLE
Natural sort for local manga

### ISSUE THREAD

**Issue by BaccanoMob** [tachiyomiorg/tachiyomi#10038] opened 2023-10-20 12:31 UTC
### Describe your suggested feature

Currently there are 3 sorting order (by source, chapter number, upload date). For reading manga online these 3 are enough but for local source it would be a great idea to include natural sort. So it's easier to navigate chapters.

For example, the order messes up via the number in the file name for by source or chapter number. 
 
![Screenshot_20231020_175236_TachiyomiJ2K](https://github.com/tachiyomiorg/tachiyomi/assets/82655889/9b9d8325-97af-4582-a4fd-234f955d0ae1)

Also, by upload date messes up the order
![Screenshot_20231020_175520_TachiyomiJ2K](https://github.com/tachiyomiorg/tachiyomi/assets/82655889/3d369a21-9207-4b87-b1d9-3fc7db2d4367)

But they are fine in natural sort in desktop or in file explorer in Android. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2023-10-20 14:45
Duplicate of #7065

**Closed by Seishirou101** 2023-10-20 14:45 UTC
Labels: Feature request
