### ISSUE TITLE
Make the migration process like the TachiJ2K migration. 

### ISSUE THREAD

**Issue by KineticDevil** [tachiyomiorg/tachiyomi#5682] opened 2021-08-09 13:21 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

The migration process is too slow. Its like manually searching again but is no filter options. TachiJ2K migration is quite good. It's easy to migrate in that app.

**Comment by Seishirou101** [comment] 2021-08-09 13:22
Duplicate of #1231

**Closed** 2021-08-09 13:22 UTC
Labels: Feature request
