### ISSUE TITLE
[Feature Request]It is better to pack the downloaded manga into compressed files instead many pictures in folders

### ISSUE THREAD

**Issue by teglaven** [tachiyomiorg/tachiyomi#5254] opened 2021-06-01 14:38 UTC
//ATTENTION: I am not an English speaker, so my expression May look weird, I am sorry.//

The default filesystem of SD card on Android is exFAT, and the default cluster size is may more than 64KB. Many pictures of mengas are less than 1MB, according to my experience, they are often just 300KBs. Storing them in a picture format on SD card would waste a lot of space, especially when the cluster size set up to 128KBs(I've experienced it myself when I'm using Sony xzp，it wasted at least 30GB of my card). 
Because backup mengas on SD card is easy, I thought give users a choice to test change all mengas Storage format from pictures to zip/7z can be works.

**Comment by curche** [comment] 2021-06-01 16:09
Duplicate of https://github.com/tachiyomiorg/tachiyomi/issues/918

**Closed** 2021-06-01 16:10 UTC
Labels: feature
