### ISSUE TITLE
Bug on page transition while going back in the middle of the page change motion

### ISSUE THREAD

**Issue by brunocabete** [tachiyomiorg/tachiyomi#2251] opened 2019-09-27 04:12 UTC
**App version:**
0.8.4
**Android version:**
Pie
**Issue/Request:**
There is a bug on the page transition. If you try to change pages, but in the middle of the motion you swipe the other way around, the page you were in doesn't pan back properly and instead the previous page appears.

**Steps to reproduce (if applicable)**

 1.go to the end of the page, and start the motion to swipe for the next image.
 2.without lifting your finger, start the reverse motion, as if you wanted to go back to the page you were
 3.the page you were will not pan properly, instead the page before it will start to appear

**Other details:**
[Video showing the issue](https://www.youtube.com/watch?v=RIfVWsYkjYs&feature=youtu.be)
Notice how the brown page scrolls normally, until the motion to go to the blue page starts. when this happens, the brown page doesn't pan properly, and the previous page (the white one) appears.

**Comment by Dark4Codrutz** [comment] 2021-05-01 21:22
no news on this bug ?

**Comment by arkon** [comment] 2022-07-09 23:03
Duplicate of #1980

**Closed by arkon** 2022-07-09 23:03 UTC
Labels: Bug
