### ISSUE TITLE
[Bug] App Chapter List takes 30+ seconds to load on first startup.

### ISSUE THREAD

**Issue by Silvermane06** [tachiyomiorg/tachiyomi#4565] opened 2021-02-28 23:19 UTC
---

## Device information
* Tachiyomi version: Stable 0.10.9
* Android version: Android 11 (One UI 3.0) G973USQS4FUA1
* Device: Galaxy S10

## Steps to reproduce
1. Restart the phone/force stop the app/wipe the cache
2. Open the app and then open any manga.

### Expected behavior
When opening the app after a restart/the app being put to sleep/the first time, opening any manga should immediately load the chapter list. This happened on the previous version (I believe it was 0.10.8? could be wrong.)

### Actual behavior
Now upon opening any manga for the first time, the chapter lists will take 20-30 seconds to load, no matter what extension is being used. You can even go to another manga and the same thing happens. Once one chapter list is loaded, however, all chapter lists load near instantaneously after that period. 

## Other details
I assume this has something to do with the cache, or with the way it handles android 11's scoped storage? So i wiped the cache partition and cleared the app cache, but this did not fix the problem.
This also only started occurring after updating the app from the version with the old download icons to the new download icons, so it might be something to do with resources? Who knows.

**One question**: 
I can no longer access /sdcard/android/data/eu.kanade.tachiyomi through my file explorer due to android 11's scoped storage. Does tachiyomi still download the manga to that location even though it shows as "no files" to me?

If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.

**Comment by arkon** [comment] 2021-02-28 23:23
This is due to Android 11's storage changes, which we don't actually handle explicitly (we're using the legacy behaviour). That said, it seems to be extra bad on Samsung software based on some user reports.

> Does tachiyomi still download the manga to that location even though it shows as "no files" to me?

That'll depend on what you set as the download location.

Note that using the default external SD card location is slow. Using a custom external SD card location is _extra_ slow.

**Comment by Silvermane06** [comment] 2021-02-28 23:49
Is there any future plans on using non-legacy behaviour to handle it? Or would it be fixable if the location was set to another non-"/android/data/" location?


> That'll depend on what you set as the download location.
> 
> Note that using the default external SD card location is slow. Using a custom external SD card location is _extra_ slow.

Does this still apply even if the sd card is a UHS class 3 card with a 150 MB/s read/write? In other words, is this dependent on the storage medium speed (UFS 2.0 vs External Flash) or the code of the app/android itself?

Thanks for the quick response by the way, it is very much appreciated.

**Comment by arkon** [comment] 2021-03-01 00:11
> Is there any future plans on using non-legacy behaviour to handle it instead of "requestLegacyExternalStorage "?

No one has worked on it, but Android 12 will likely force our hand into doing so.

> Or would it be fixable if the location was set to another non-"/android/data/" location?

That's not actually quite relevant to the root problem.

> In other words, is this dependent on the storage medium speed (UFS 2.0 vs External Flash) or the code of the app/android itself?

It's a bit of all of the above, but the main bottleneck is Android itself being really bad with I/O with external SD cards.

**Comment by orangpelupa** [comment] 2021-03-03 15:09
This issue happen after the new UX update of tachiyomi or very close to that update. IIRC it also brings database change that should be leaner?

**Comment by Silvermane06** [comment] 2021-06-24 05:51
Just leaving a comment/update on this topic for future reference.

Now rather than it being the chapter list that takes a long time to load, half the time it's the library itself instead. 

I assume something was changed so you couldn't interact with the manga until the entire chapter list for each one is loaded, at which point the manga in the library became visible.

**Comment by AwesomeQuest** [comment] 2021-10-30 13:37
Another thing to add is that while the list of manga/chapters is loading, if you had updates open before the manga reload and click a new chapter it opens just fine.

Is this actually the app being slow at loading a list, isn't there something else that's slowing it down that could be done later? I feel like just loading a text list shouldn't be this slow. I feel like computers are good at that nowadays.

**Comment by Charuru** [comment] 2021-12-20 18:36
Is it trying to read the entire directory? Should cache the list no?

**Comment by oldnomad** [comment] 2021-12-28 17:53
There are only a few places where directories with subdirectories are scanned, and it's unlikely that any other file operation can be that slow. One suspicious place is `eu.kanade.tachiyomi.data.download.DownloadCache`: it is intended to cache chapter download status and number of chapters per manga, but to do this it scans _all_ sources, _all_ mangas, and _all_ chapters in the library. This can be expensive for a large library, and `DownloadCache` does it at init and after that every hour. The class is instantiated from `eu.kanade.tachiyomi.data.download.DownloadManager`.

**Comment by Charuru** [comment] 2022-01-02 15:34
> There are only a few places where directories with subdirectories are scanned, and it's unlikely that any other file operation can be that slow. One suspicious place is `eu.kanade.tachiyomi.data.download.DownloadCache`: it is intended to cache chapter download status and number of chapters per manga, but to do this it scans _all_ sources, _all_ mangas, and _all_ chapters in the library. This can be expensive for a large library, and `DownloadCache` does it at init and after that every hour. The class is instantiated from `eu.kanade.tachiyomi.data.download.DownloadManager`.

Sounds like you found it, should a new issue be created?

**Comment by oldnomad** [comment] 2022-01-03 13:43
> Sounds like you found it, should a new issue be created?

I'm still not entirely convinced. I see these slow-downs much more often than once an hour, and, unfortunately, I don't write Kotlin so I'm not confident enough to test the hypothesis.

**Comment by ChrisJAllan** [comment] 2022-01-04 01:13
I believe `DownloadCache` is the issue. Both `getDownloadCount` and `isChapterDownloaded` call `checkRenew`, which blocks until the entire library is refreshed. It's a bit tricky to actually fix, though. You could replace the class-wide synchronization with `ConcurrentMap`s, but then you get no distinction between "No Downloads" and "Still Refreshing", and the UI might not update when the proper values become available.

**Comment by oldnomad** [comment] 2022-01-04 21:46
If `DownloadCache` is really the culprit, then the problem is not the synchronization, but the fact that `renew()` may take a lot of time. Since, as far as I can see, `DownloadCache` is not used to determine a full list of sources/manga/chapters, Is it really necessary to scan information that was not yet requested?

What I have in mind is:
- drop `lastRenew`.
- add a timestamp to `RootDirectory`/`SourceDirectory`/`MangaDirectory` internal classes.
- initialize `RootDirectory` with an empty map and zero timestamp.
- when `isChapterDownloaded()` or `getDownloadCount()` is called, look up the information for this manga in the map, and populate it (for this source/manga only) if not present or too old, updating the timestamps on the way.

Unfortunately, this is not a small change.

**Comment by ChrisJAllan** [comment] 2022-01-04 22:05
Because reading from the SD card is potentially very expensive, there is a benefit to caching this information before it is requested. And while not *all* manga need to be loaded at once, `getDownloadCount` will need to be called on every manga in the current category for the download badges. But a cache should not block because of unrelated data. Maybe something similar to your suggestion, but with a low-priority background loader.

A quick, dirty, "solution" might be to make the download badges and chapter download buttons a question mark until the cache is refreshed, but I would say to only use that if it is significantly faster to use `listFiles()` then checking each directories existence individually.

**Comment by Charuru** [comment] 2022-01-04 22:24
> A quick, dirty, "solution" might be to make the download badges and chapter download buttons a question mark until the cache is refreshed

Not dirty at all, just good practice in general.

**Comment by cecoates** [comment] 2022-01-26 01:45
I just ran into this when updated my Chromebook to m97.

It looks like for m97/m98 (this month and next month's update) a lot of devices will be upgraded to Android 11, and the performance is noticeably non-ideal.

You can revert to a previous version, but it's going to require a Powerwash, wiping your entire device.

Recommended folks don't upgrade for now if you use Tachiyomi (or really Android apps in general) and don't want to deal with Android 11 headaches.

**Comment by History-exe** [comment] 2022-03-29 01:43
Device: Android 9
Tachiyomi version: 0.13.1

Description:
For me, I have 3700+ mangas. 
Everytime when I first open the Tachiyomi, all the mangas are **disappeared**, but after a few minutes it will show. 
And when I search something in globle mode, this will reduce the manga load time. the manga list shows quicker than just wait it load.

**Comment by arkon** [comment] 2022-07-09 16:48
Closing in favour of #7433, since a bunch of stuff was rewritten since this issue.

**Closed by arkon** 2022-07-09 16:48 UTC
Labels: Bug
