### ISSUE TITLE
Infinite loading when browsing inside source in tachiyomi 4687

### ISSUE THREAD

**Issue by raziel100** [tachiyomiorg/tachiyomi#7595] opened 2022-07-24 04:12 UTC
### Steps to reproduce

1. Choose any source to browse for manga
2. Enter in any Manga do see chapters and so on
3. Turn back 

### Expected behavior

Show the other Manga in order to choose another one

### Actual behavior

After turned back from browsing any Manga its enter in a infinite loading forcing you to get out from source and entering again every time you click in a Manga, I have waited more than 10 min so see if fixed itself but it become stuck loading anyway. 

### Tachiyomi version

App version: 0.13.5-4687

### Android version

Android 11

### Device

Samsung a02

### Other details

I have see more than 10 different sources and it happened every time. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by raziel100** [comment] 2022-07-24 04:40
I have notice too that in library when you click in any Manga there. It force a loading for a couple of minutes until you could see the chapters and download chapters and if you return and enter another Manga, it will search again, I believed in this case is search for changes like downloaded chapters every single time. I don't know if this is related to the issue in source search

**Comment by DchanN** [comment] 2022-07-24 07:16
Duplicate of #7433

**Comment by raziel100** [comment] 2022-07-24 12:49
> Duplicate of #7433

No its not. I was using Tachiyomi Preview r4622 and it was not like this. Read again. Or maybe I didn't explain properly.

**Comment by DchanN** [comment] 2022-07-24 12:55
> > Duplicate of #7433
> 
> No its not. I was using Tachiyomi Preview r4622 and it was not like this. Read again. Or maybe I didn't explain properly.

this one i'm mean to be duplicate your comment 

> I have notice too that in library when you click in any Manga there. It force a loading for a couple of minutes until you could see the chapters and download chapters and if you return and enter another Manga, it will search again, I believed in this case is search for changes like downloaded chapters every single time. I don't know if this is related to the issue in source search

for the browsing not sure, but seems to be related with manga info page slow to load

**Comment by raziel100** [comment] 2022-07-24 13:01
> > > Duplicate of #7433
> > 
> > 
> > No its not. I was using Tachiyomi Preview r4622 and it was not like this. Read again. Or maybe I didn't explain properly.
> 
> this one i'm mean to be duplicate your comment
> 
> > I have notice too that in library when you click in any Manga there. It force a loading for a couple of minutes until you could see the chapters and download chapters and if you return and enter another Manga, it will search again, I believed in this case is search for changes like downloaded chapters every single time. I don't know if this is related to the issue in source search
> 
> for the browsing not sure, but seems to be related with manga info page slow to load

I though the same, because the source dosent have a reason to be that way, I think after you turn back he tried to enter a null page, because of that it never stop loading, but in library before takes some time but until he tried to search the download folder again to see if changes have happen it didn't slow down to enter Manga page, but now is in every single Manga

**Comment by DchanN** [comment] 2022-07-24 13:08
> > > > Duplicate of #7433
> > > 
> > > 
> > > No its not. I was using Tachiyomi Preview r4622 and it was not like this. Read again. Or maybe I didn't explain properly.
> > 
> > 
> > this one i'm mean to be duplicate your comment
> > > I have notice too that in library when you click in any Manga there. It force a loading for a couple of minutes until you could see the chapters and download chapters and if you return and enter another Manga, it will search again, I believed in this case is search for changes like downloaded chapters every single time. I don't know if this is related to the issue in source search
> > 
> > 
> > for the browsing not sure, but seems to be related with manga info page slow to load
> 
> I though the same, because the source dosent have a reason to be that way, I think after you turn back he tried to enter a null page, because of that it never stop loading, but in library before takes some time but until he tried to search the download folder again to see if changes have happen it didn't slow down to enter Manga page, but now is in every single Manga

yeah, it's started effect all manga in library since r4622

**Comment by raziel100** [comment] 2022-07-24 14:03
> > > > > Duplicate of #7433
> > > > 
> > > > 
> > > > No its not. I was using Tachiyomi Preview r4622 and it was not like this. Read again. Or maybe I didn't explain properly.
> > > 
> > > 
> > > this one i'm mean to be duplicate your comment
> > > > I have notice too that in library when you click in any Manga there. It force a loading for a couple of minutes until you could see the chapters and download chapters and if you return and enter another Manga, it will search again, I believed in this case is search for changes like downloaded chapters every single time. I don't know if this is related to the issue in source search
> > > 
> > > 
> > > for the browsing not sure, but seems to be related with manga info page slow to load
> > 
> > 
> > I though the same, because the source dosent have a reason to be that way, I think after you turn back he tried to enter a null page, because of that it never stop loading, but in library before takes some time but until he tried to search the download folder again to see if changes have happen it didn't slow down to enter Manga page, but now is in every single Manga
> 
> yeah, it's started effect all manga in library since r4622

And in 4687 become worse to the point where reading anything is a pain

**Closed** 2022-07-25 12:32 UTC
Labels: Bug

**Comment by Dragoon91786** [comment] 2022-07-27 19:45
Having same problem now with all versions post extensions update & database update to 19. Cannot restore to 18.
