### ISSUE TITLE
Try to restartthe download process automaticly

### ISSUE THREAD

**Issue by 362516282** [tachiyomiorg/tachiyomi#6611] opened 2022-02-09 14:35 UTC
### Describe your suggested feature

don't know why the download process will meet unexpected error just after one chapter is download, and another one can't be downloaded.
can you fix this problem or add the function to try to restartthe download process automaticly, the time can be changed in the settings.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2022-02-09 14:44
Duplicate of #959

**Closed by Seishirou101** 2022-02-09 14:44 UTC
Labels: Feature request
