### ISSUE TITLE
[Bug] Installed extensions not getting detected

### ISSUE THREAD

**Issue by the-codinator** [tachiyomiorg/tachiyomi#4972] opened 2021-04-27 18:28 UTC
## Device information
* Tachiyomi version: 0.10.12
* Android version: 9
* Device: OnePlus 3

## Steps to reproduce
1. Install an extension
2. Go to sources, but installed extension is missing
3. Check app list in Android settings - installed extensions are present (even when retrying install from tachiyomi is says "do u want to update the app" and not "new app")
4. Tried uninstalling from Android app list and reinstalling from tachiyomi, still source not visible
5. Existing sources are present, and updating them doesn't cause them to disappear

tried with Mangadex, MyReadingManga, Hitomi.la

### Expected behavior
Installed apps should show up in sources list

### Actual behavior
Do not show up, and going back to the extension page, it shows "Install" button again

## Other details
Additional details and attachments.

![Screenshot_20210427-235652__01.jpg](https://user-images.githubusercontent.com/4411711/116293256-4f38b380-a7b4-11eb-9ff8-1d4fec69901c.jpg)

![Screenshot_20210427-235452.jpg](https://user-images.githubusercontent.com/4411711/116293288-5a8bdf00-a7b4-11eb-9c5a-188165d60e9d.jpg)

![Screenshot_20210427-235444.jpg](https://user-images.githubusercontent.com/4411711/116293341-67a8ce00-a7b4-11eb-9ad2-bda481aca02a.jpg)

**Comment by curche** [comment] 2021-04-27 18:38
Did you enable the source in Extension settings?
Relevant link:
https://tachiyomi.org/help/faq/#how-can-i-see-sources-from-other-languages

**Comment by the-codinator** [comment] 2021-04-28 05:34
Yes I did try that. I even checked all the other languages and it doesn't show up.

![Screenshot_20210428-105510.jpg](https://user-images.githubusercontent.com/4411711/116350936-66a58a00-a810-11eb-8158-feba38e0952d.jpg)

Tachiyomi doesn't seem to detect the extension once it is installed, since as soon as u navigate out of the extensions sections and back to it, the "Install" button is again shown next to the name in the list.

Also, when u generally install an extension, it moves to the top of the list (where all other installed extensions are present) but it isn't happening for these.

I tried installing another extension (xkcd) and that worked successfully (it moved to the top with other installed extensions, AND shows in the sources tab). Maybe there's a specific property to what kind of extension it is causing some failure somewhere?

![Screenshot_20210428-110351.jpg](https://user-images.githubusercontent.com/4411711/116351514-72de1700-a811-11eb-89cf-fe7557ec3ece.jpg)

**Comment by the-codinator** [comment] 2021-04-28 05:38
My thoughts (by trial and error): Is there a check, that verifies if an extension was installed correctly, immediately after the install flow is completed? It doesn't seem to accept that the extension actually got installed. I suspect this bit might help figuring out the issue.

**Comment by curche** [comment] 2021-04-28 07:28
The sources you mentioned are:
>  Mangadex, MyReadingManga, Hitomi.la 

Could you try the following:
1. Go to More > Settings > Browse and enable NSFW 18+ Source (since all sources mentioned are labelled 18+). Restart the app
2. Go to Browse > Extensions and enable the Source in the language after clicking Settings. If required, do the steps from the link in my previous comment

**Comment by the-codinator** [comment] 2021-04-28 09:46
Ok looks like it was a stupid setting on my side. Enabling the setting "show in sources list" was disabled. Enabling it solved my problem.

![Screenshot_20210428-151212__01.jpg](https://user-images.githubusercontent.com/4411711/116383235-48518580-a834-11eb-95de-ab13376af974.jpg)

Suggestion: It might be a good idea to show the extension as "installed" in the extension list rather than show the "install" button next to it to avoid confusion. As anyway there already exists a setting for hiding it from the extension list.

**Comment by curche** [comment] 2021-04-28 11:48
Yeah, I think that's how it was intended to be or it could be a bug. One of the devs can confirm on which one it is

Here are the Steps to replicate:
1. Enable all settings for 18+ sources in Settings>Browse
2. Install an 18+ source. Eg: Batoto. Ensure batoto shows up under Browse>Sources
3. Turn off "Show in sources list" and restart the app
4. Check under Browse>Extensions: Batoto is shown under "ALL" with option "Install".
5. Install Batoto, and it shows up as "Installed" but under "ALL" same as before.
6. Click on "Installed", and it tries to install it again.

This can lead to a confusion as to whether the app installed it or not; like in your case. 
You'd have to enable 18+ sources from settings to view it again. 

Perhaps a Dialog can be shown when you press on "Installed". It will tell to enable 18+ sources rather than try to install the source again. Unsure whether it's possible tho

**Comment by the-codinator** [comment] 2021-04-28 12:06
+1

I feel the above behavior would make the UX more clearer/informative/intuative.

@curche should we tag someone for initial attention about the improvement possibility

**Comment by arkon** [comment] 2021-11-19 22:08
The settings were merged, so it's slightly less confusing now (i.e. you can't actually try to install an 18+ extension if the setting is off).

**Closed by arkon** 2021-11-19 22:08 UTC
Labels: Bug
