### ISSUE TITLE
Option to auto generate details.json on download

### ISSUE THREAD

**Issue by Shamicen** [tachiyomiorg/tachiyomi#5478] opened 2021-06-30 09:03 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

After downloading a Manga from any extension Tachiyomi would generate a details.json with all current information inside the Manga folder. 
This would help users who mainly use the download feature to have a local off device copy in case the online source goes down or users who want to migrate Manga from a dead extension to local source without losing the description, tags title, author, artist and status.

**Comment by Seishirou101** [comment] 2021-06-30 15:48
Duplicate of #2289

**Closed** 2021-06-30 15:49 UTC
Labels: Feature request
