### ISSUE TITLE
[Feature Request] sort option: manga source, indicator for read manga not present in library. batch migration to another source

### ISSUE THREAD

**Issue by sarweshMaharjan** [tachiyomiorg/tachiyomi#4733] opened 2021-03-29 04:34 UTC
## Why/User Benefit/User Problem
If you have a massive library and any manga source has when offline then finding each manga, changing it to new manga source takes a lot of time. So adding a sort option according to your present manga source is a must .Also, if you have read manga from a source till the latest chapter and not add to library yet, it should have some sort of indicator at the front to denote it has been read. 

## What/Requirements
1. You can add sort option with dropdown to sort according to manga source. 
2. Also add unknown source option, for those who manga is in library but the manga source is either remove or deleted 
    + This can be done either by notifying the user which manga extension source is missing or do batch migration to another source.
3. Allow user to do batch migrate from one source to another source. 
4. Shade the cover image into red color indicating it has been read till the latest chapter, yet hasn't been added to the library. Also different color, for instance "yellow" to indicate... it has been read up to certain chapter and not added to library

**Comment by scb261** [comment] 2021-03-29 05:10
You should have opened separate issues for each request.
1. Sort by source was removed. You can search source name in your library, or use `Browse > Migration` to see all used sources and manga that was added from them.
2. You can see them as numbers in `Browse > Migration`.
3. Duplicate of #1729.
4. Will wait for maintainers to answer, but this one is probably no.

**Comment by CarlosEsco** [comment] 2021-03-29 11:43
4 is not something that will be added, its pretty similar to https://github.com/tachiyomiorg/tachiyomi/issues/4089

**Closed by CarlosEsco** 2021-03-29 11:43 UTC
Labels: feature
