### ISSUE TITLE
Tracking Automation, Some Optimization, and Local Manga Improvements

### ISSUE THREAD

**Issue by lasersPew** [tachiyomiorg/tachiyomi#7212] opened 2022-05-28 13:41 UTC
### Describe your suggested feature

1. When a manga gets added to library, search from tracking sources that user has logged in. Ask user to check if the result if the series is right once they open the series again to prevent false positives.
2. When user didn't read the series for 1 week or more(would've love it if duration can be set in the settings), set tracking as On Hold. 
3. In library, if the category is named Reading, Plan to Read, Completed, Dropped, On Hold, set the series' tracking status to Reading, Plan to Read, Completed, Dropped or On Hold, respectively.
3.5 If the series is marked as completed while the series isn't completed(which can be checked by looking at other sources and/or checking it on trackers), revert it to reading and/or alert it to user.
4. Button to export a series' info into JSON.
5.1 Include tracking links and cover image file path into the local manga info.
5.2 Ability to read the local manga info into 1 or 2 or multiple file JSON file and place both image and info files into a single folder.
5.3 Interoperability of local manga between multiple Tachiyomi apps.(TL:DR; ability to read and place local manga to and from Tachiyomi, Aniyomi, TachiyomiAZ, TachiyomiSY and Neko's local manga directories.)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment] 2022-05-28 13:44
One request per issue please

**Comment by arkon** [comment] 2022-05-28 13:44
1 issue per request/report please.

For 1: open a new issue, with a description of the UX workflow that you're imagining.

For 2: I'll decline this since it seems too niche.

For 3: duplicate of #1730

For 4: declined before. External third-party tools can be created if desired.

**Closed by loocool2** 2022-05-28 13:44 UTC
Labels: Feature request
