### ISSUE TITLE
Screen freezes inoperable while reading Tachiyomi

### ISSUE THREAD

**Issue by ChoBitsZ7** [tachiyomiorg/tachiyomi#8003] opened 2022-09-13 12:07 UTC
### Steps to reproduce

Tachiyomi reads the manga that has been downloaded in the bookcase

### Expected behavior

Normal browsing Tachiyomi

### Actual behavior

Reading about 20 minutes to 40 minutes Tachiyomi will get stuck and cannot operate
At the moment Android pops up a dialog showing "stop working"
But after waiting for 5 minutes, it can work normally again, and then it is found that Tachiyomi will reload the comics in the SD external storage.

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/9556855/tachiyomi_crash_logs.txt)

### Tachiyomi version

0.13.6

### Android version

Android 12

### Device

Galaxy Tab S7

### Other details

In the previous Tachiyomi version, if you read for a long time, the manga in the SD external storage will be reloaded, but it will not "stop working" during reading.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-09-16 02:59
Should be a duplicate of #7847

**Closed by arkon** 2022-09-16 02:59 UTC
Labels: Bug
