### ISSUE TITLE
App keeps crashing when reading webtoon.

### ISSUE THREAD

**Issue by Syrisdia** [tachiyomiorg/tachiyomi#9592] opened 2023-06-06 22:13 UTC
### Steps to reproduce

Open app
Download webtoon.
Open webtoon.
App crashes after a few minutes.

### Expected behavior

App not crashing when reading.

### Actual behavior

App always crashes after a few minutes

### Tachiyomi version

0.14.6

### Android version

Android 7

### Device

Samsung Galaxy S6 edge plus

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-06-06 22:42
Probably a duplicate of #1908, given lack of actual details.

**Closed by arkon** 2023-06-06 22:42 UTC
Labels: Bug
