### ISSUE TITLE
Chapters are not Updating

### ISSUE THREAD

**Issue by Ashborn-Lucifer** [tachiyomiorg/tachiyomi#6631] opened 2022-02-12 08:55 UTC
### Steps to reproduce

1. Going to the Updates tab
2.Press Refress icon

### Expected behavior

All the chapters in my library should update.

### Actual behavior

Only few of the chapters are updating.

### Tachiyomi version

0.13.1

### Android version

Android 11

### Device

Poco x3 pro

### Other details

![Screenshot_2022-02-12-14-23-30-966_eu kanade tachiyomi](https://user-images.githubusercontent.com/90907197/153704590-64360805-2e10-417d-94cc-f0d7bf5ad53a.jpg)
![Screenshot_2022-02-12-14-23-56-517_eu kanade tachiyomi](https://user-images.githubusercontent.com/90907197/153704595-29ad8118-de74-4e1f-8c55-afca1e1df584.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment] 2022-02-12 09:07
> I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open issue.

Duplicate of #6599

**Closed by curche** 2022-02-12 09:07 UTC
Labels: Bug
