### ISSUE TITLE
Auto-download after loosing connection

### ISSUE THREAD

**Issue by ArthurDavletov** [tachiyomiorg/tachiyomi#6683] opened 2022-02-20 19:28 UTC
### Describe your suggested feature

Imagine, I was downloading several chapters, but I lost the Internet connection. After the phone connects to the Internet, the chapters don't download. You need to go to the "Download queue" and resume them. I would like the chapters to download immediately after connecting to the Internet

### Other details

- **App version**: 0.13.1-4170 (standard, `2f07f226b`, 75, 2022-02-19T21:08Z)
- **Android version**: 11 (SDK 30)
- **Device model**: Redmi Note 8 Pro
_My native language isn't English. If issue has mistakes, sorry for them._

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2022-02-20 19:41
Duplicate of #959

**Closed by Seishirou101** 2022-02-20 19:41 UTC
Labels: Feature request
