### ISSUE TITLE
Auto-rotate 

### ISSUE THREAD

**Issue by ramon671** [tachiyomiorg/tachiyomi#6771] opened 2022-03-12 23:03 UTC
### Describe your suggested feature

Automatically rotate double pages.

Double pages could be displayed vertically, so we can see them fullscreen without rotating the device

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment] 2022-03-12 23:27
Duplicate of #1977

**Closed by loocool2** 2022-03-12 23:27 UTC
Labels: Feature request
