### ISSUE TITLE
Dismiss snackbar after ~10 seconds, following Material Guidelines

### ISSUE THREAD

**Issue by vengiare** [tachiyomiorg/tachiyomi#5933] opened 2021-09-18 19:29 UTC
### Describe your suggested feature

![IMG_20210919_032802](https://user-images.githubusercontent.com/63973749/133906401-872367a8-4198-48c9-8689-496bc535792b.jpg)

![133896984-8d5ba14a-f720-46bc-a9e5-ddafcf12a1f9](https://user-images.githubusercontent.com/63973749/133906339-4ff93ac7-136a-483c-b285-4dec12cb3673.png)

*edit:* Dismiss snackbar after 4-10 secs. Idk really how long exactly.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2021-09-18 19:47
Duplicate of #5932

**Closed by arkon** 2021-09-18 19:47 UTC
Labels: Feature request
