### ISSUE TITLE
Local manga cover does not change when using set as cover (cbz)

### ISSUE THREAD

**Issue by Zcah07** [tachiyomiorg/tachiyomi#5704] opened 2021-08-12 09:34 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.0](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.12.0)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.12.1

### Android version

7.0

### Device

Samsung s6 edge

### Steps to reproduce

1. open a chapter on manga with .cbz extension
2. use the first picture, set as cover

### Expected behavior

it should change a picture instead of blank picture

### Actual behavior

it does nothing its stay blank

### Other details

i think it only happens on cbz extension atleast let it use the first picture as cover

**Comment by TheDevilsHyper** [comment] 2021-08-15 05:46
I second this.

**Comment by scb261** [comment] 2021-08-16 13:26
> Actual behavior
it does nothing its stay blank

Duplicate of #932

**Closed** 2021-08-16 13:26 UTC
Labels: Bug
