### ISSUE TITLE
[Feature request] Add "Group chapters" to the Updates tab

### ISSUE THREAD

**Issue by TanielianVB** [tachiyomiorg/tachiyomi#9165] opened 2023-03-01 13:23 UTC
### Describe your suggested feature

Currently, on the Updates tab, the only button visible is to refresh the updates. I suggest that a new filter button is added so we can filter the updates list for things like: "Group chapters" and "Show only unread updates" for example.

The **Group chapters** feature would be like:
- (current) Instead of showing 30 items that were updated for the same title.
- (proposed) Show only the Title and a subtitle: Chapters 1 ~ 30. And clicking would "play" the reading as it currently is.

The **Show only unread updates** is just like #3365 So that's why I focused on the **Group chapters** in this feature request.

### Other details

If I knew Kotlin I would like to contribute. A long time ago I coded in Java.
Let me know if this feature is something desirable. If it is, or if I find another interesting issue to work on, I'll look into learning. 😁 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-03-01 14:10
Duplicate of #2774

**Closed by arkon** 2023-03-01 14:10 UTC
Labels: Feature request
