### ISSUE TITLE
Tapping last read chapter on history opens up "oldest unread chapter" instead of resuming "last read chapter"

### ISSUE THREAD

**Issue by viainable** [tachiyomiorg/tachiyomi#8479] opened 2022-11-08 10:18 UTC
### Steps to reproduce

1. read any manga, any chapter except the first chapter
2. tap the last read chapter on history

### Expected behavior

last read chapter should open, resuming it

### Actual behavior

oldest unread chapter open up

### Tachiyomi version

0.14.2

### Android version

Android 12

### Device

Poco M4 Pro 4g

### Other details

this only happens in recent version

the expected behavior was the usual behavior in older version

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-11-08 13:01
Duplicate of #8454

**Closed by arkon** 2022-11-08 13:01 UTC
Labels: Bug
