### ISSUE TITLE
Problem bookmarking chapters

### ISSUE THREAD

**Issue by edmxn** [tachiyomiorg/tachiyomi#8072] opened 2022-09-25 00:51 UTC
### Steps to reproduce

Open a chapter
Try dialing it from the reader

### Expected behavior

It should be marked with no problem

### Actual behavior

The app freezes for a few seconds

### Tachiyomi version

0.13.6

### Android version

Android 12

### Device

Samsung s10+

### Other details

![192103599-3019970c-caa0-4810-9437-0489b13e9ebf](https://user-images.githubusercontent.com/101371218/192123653-049be3c6-ad39-4a17-bd9c-a62084a6074f.jpg)
Mark as favourite*

This pro now has only happened to me in TuMangaOnline and Senpai Ediciones, I don't know if it happens in other sources

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-09-25 03:00
Does this happen for any chapter or a specific one?

**Comment by edmxn** [comment] 2022-09-25 03:14
> Does this happen for any chapter or a specific one?

In all

**Comment by edmxn** [comment] 2022-09-25 03:17
> ### Steps to reproduce
> Open a chapter Try dialing it from the reader
> 
> ### Expected behavior
> It should be marked with no problem
> 
> ### Actual behavior
> The app freezes for a few seconds
> 
> ### Crash logs
> _No response_
> 
> ### Tachiyomi version
> 0.13.6
> 
> ### Android version
> Android 12
> 
> ### Device
> Samsung s10+
> 
> ### Other details
> ![192103599-3019970c-caa0-4810-9437-0489b13e9ebf](https://user-images.githubusercontent.com/101371218/192123653-049be3c6-ad39-4a17-bd9c-a62084a6074f.jpg) Mark as favourite*
For now this has only happened to me in TuMangaOnline and Senpai Ediciones, I don't know if it happens in other sources
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
> * [x]  I have written a short but informative title.
> * [x]  If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
> * [x]  I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
> * [x]  I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
> * [x]  I have updated all installed extensions.
> * [x]  I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-10-08 16:21
Can't reproduce, but the underlying logic's been rewritten in preview so I'll just optimistically close this. If it still happens in the next stable release, please open another issue.

**Closed by arkon** 2022-10-08 16:21 UTC
Labels: Bug
