### ISSUE TITLE
Can not update or download from CopyManga

### ISSUE THREAD

**Issue by firo1603** [tachiyomiorg/tachiyomi#5951] opened 2021-09-22 06:54 UTC
### Steps to reproduce

can not download any manga in CopyManga

### Expected behavior

download the manga

### Actual behavior

download stop and Pop up prompt “Missing Argument”0

### Tachiyomi version

0.12.2

### Android version

MIUI12.5.7

### Device

Mi 10 Pro

### Other details

CopyManga version1.2.15

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment] 2021-09-22 07:01
Duplicate of #9114

**Closed by loocool2** 2021-09-22 07:01 UTC
Labels: Bug
