### ISSUE TITLE
CBZ Converter for Existing Downloads

### ISSUE THREAD

**Issue by Srking91** [tachiyomiorg/tachiyomi#9363] opened 2023-04-19 00:11 UTC
### Describe your suggested feature

You have an option to convert files being downloaded to CBZ however I have a library that I want to convert without having to re-download every chapter I have. Could you make a bulk converter for global or for series?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2023-04-19 00:15
Duplicate of #7018, though you can probably just do it yourself a lot easier.

**Closed by Seishirou101** 2023-04-19 00:15 UTC
Labels: Feature request
