### ISSUE TITLE
Changing orientation rewinds chapter to beginning

### ISSUE THREAD

**Issue by norbitheeviljester** [tachiyomiorg/tachiyomi#8968] opened 2023-01-22 10:26 UTC
### Steps to reproduce

1. Choose reading mode webtoon or continuous vertical
2. Start reading a chapter in portrait orientation
3. Move several pages down
4. Change the orientation to landscape

### Expected behavior

Changing the orientation stays with the vicinity of the original page. Ideally switching the orientation back and forth doesn't change the page.

### Actual behavior

Current page will be rewinded to beginning of chapter

### Tachiyomi version

0.14.3

### Android version

Android 13

### Device

OnePlus 8 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment] 2023-01-22 10:44
Duplicate of #8881

**Closed by AntsyLich** 2023-01-22 10:44 UTC
Labels: Bug
