### ISSUE TITLE
[Feature Request] Smart Image Zoom and split

### ISSUE THREAD

**Issue by feilongfl** [tachiyomiorg/tachiyomi#2070] opened 2019-06-07 14:05 UTC
**App version:**
0.8.4

**Android version:**
android 6

**feature Request:**
I want to be able to intelligently match the display orientation or split the continuous image based on the image size and cut off the white border of the image.

#### Two pages are horizontally aligned
![photo_2019-06-07_21-51-19](https://user-images.githubusercontent.com/10269596/59109828-5ceeb100-8970-11e9-95c9-8fddf9d656c1.jpg)

#### Two pages are vertically aligned
![photo_2019-06-07_21-51-08](https://user-images.githubusercontent.com/10269596/59109797-48aab400-8970-11e9-959a-63f7d2435469.jpg)

#### need cut white border
![photo_2019-06-07_21-51-24](https://user-images.githubusercontent.com/10269596/59109823-595b2a00-8970-11e9-9809-0b82e6ca4a54.jpg)

#### The ratio is seriously not in line with the current size of the screen
![photo_2019-06-07_21-51-15](https://user-images.githubusercontent.com/10269596/59109815-53654900-8970-11e9-8da5-9579a80ce477.jpg)

**Comment by MerradOklom** [comment] 2019-06-07 14:36
If you enable "crop borders" inside the Settings > Reader, it will eliminate that white border, but it doesn't work if there is any text (as far as I know).

**Comment by feilongfl** [comment] 2019-06-07 14:54
@MerradOklom seems you're right,I have enable it when i took these pictures.
but I think the white border not only caused by text,also caused by zoom small pictures.

**Comment by arkon** [comment] 2022-07-09 22:59
Dual page split + duplicate of #1977.

**Closed by arkon** 2022-07-09 22:59 UTC
Labels: Feature request
