### ISSUE TITLE
add delay on show overlay during reading manga/manhua

### ISSUE THREAD

**Issue by johnvega** [tachiyomiorg/tachiyomi#9886] opened 2023-08-28 01:46 UTC
### Describe your suggested feature

Can you please add a sensitive delay of show/hide overlay when reading a content. Whenever I scroll down or up, the overlay will show. It's very annoying. I sometimes miss tap the > button and goes to another page.

### Other details

![371911505_673947747965606_3359023457041055679_n](https://github.com/tachiyomiorg/tachiyomi/assets/5159649/88357a76-b288-4f02-bb8b-83bd6dd0ba0b)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jjjjbow** [comment] 2023-08-31 12:21
作者采纳你的建议你了吗？

**Comment by KaiserBh** [comment] 2023-09-01 00:48
Does this only happen on a specific device? Because on my device `S20` overlay doesn't show when I am scrolling the only time overlay will show if I want it to show in this case I would tap middle of the page.

**Comment by johnvega** [comment] 2023-09-05 00:45
I am not sure if this is for specific device but i am reading it via "webtoon". When I scroll fast and try to stop the scrolling, the overlay will show. I guess the gesture tap will show the overlay. It would be nice to check first if the screen is scrolling and when user tap, it would not show the overlay. It would only show if the screen is not scrolling

**Comment by arkon** [comment] 2023-10-28 21:41
Duplicate of #9506

**Closed by arkon** 2023-10-28 21:41 UTC
Labels: Feature request
