### ISSUE TITLE
problem with scrolling between categories, it has become very slow

### ISSUE THREAD

**Issue by Pokoma** [tachiyomiorg/tachiyomi#8314] opened 2022-10-28 20:42 UTC
### Steps to reproduce

Every time I scroll through any category I have, it becomes very slow compared to the last update, the problem is with the new update.

### Expected behavior

smooth scrolling

### Actual behavior

slow scrolling

### Tachiyomi version

0.14.0

### Android version

Android 12

### Device

Samsung A13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-10-28 20:45
Duplicate of #8310

**Closed by arkon** 2022-10-28 20:45 UTC
Labels: Bug
