### ISSUE TITLE
Chapter Deletion Bug

### ISSUE THREAD

**Issue by shawkik** [tachiyomiorg/tachiyomi#5938] opened 2021-09-19 08:16 UTC
### Steps to reproduce

1.I deleted some downloaded chapter
2.I left the app
3.I open the app again
4.The chapters that I deleted is showing downloaded

### Expected behavior

If I delete chapters,it should show that the chapters are deleted and delete the chapter from my internal storage Tachiyomi download folder

### Actual behavior

The chapters are not deleted in single attempt....I needed to delete those chapters multiple times

### Tachiyomi version

0.12.0

### Android version

Android 11

### Device

Xiaomi Redmi Note 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [x] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2021-09-19 12:54
Duplicate of #4286

**Closed by arkon** 2021-09-19 12:54 UTC
Labels: Bug
