### ISSUE TITLE
Multi-select to add to library while browsing 

### ISSUE THREAD

**Issue by mjd515** [tachiyomiorg/tachiyomi#5968] opened 2021-09-26 00:33 UTC
### Describe your suggested feature

I would love if I could hold down on a selection in the browse menu and select more then one title to add to the library

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2021-09-26 00:44
Duplicate of #829

**Closed by arkon** 2021-09-26 00:44 UTC
Labels: Feature request
