### ISSUE TITLE
[Two page reading mode] <its like what mangarock did where you have two pages on the same screen while in landscape mode it whould be great because alot of manga have scenes where it goes across two pages>

### ISSUE THREAD

**Issue by NoiszGaming** [tachiyomiorg/tachiyomi#4880] opened 2021-04-17 03:12 UTC
## Why/User Benefit/User Problem
(explain why this feature should be added)
Manga will generally go across 2 page in one scene which if  this feature is added it will enhance the reading experience 

## What/Requirements
(explain how this feature would behave)

**Comment by arkon** [comment] 2021-04-17 03:19
Duplicate of #149

**Closed by arkon** 2021-04-17 03:19 UTC
Labels: feature
