### ISSUE TITLE
Search filter doesn't work in library

### ISSUE THREAD

**Issue by kevin01523** [tachiyomiorg/tachiyomi#8037] opened 2022-09-19 14:02 UTC
### Steps to reproduce

Type a word in the library search bar

### Expected behavior

Manga with same title or contains a word in title should appear or with the category on the search bar

### Actual behavior

App forces me to search for the word globally as an option to search globally appears and searches the word from different sources instead of just filtering the manga inside the Library 

### Tachiyomi version

App version: 0.13.6-4929 (standard, 0086743a5, 84, 2022-09-17T21:10Z) 

### Android version

Android version: 10 (SDK 29) 

### Device

Android build ID: lineage_twolip-userdebug 10 QQ3A.200805.001 10035824 Device brand: Xiaomi Device manufacturer: Xiaomi Device name: twolip Device model: Redmi Note 6 Pro  Device product name: lineage_twolip

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-09-19 14:31
Duplicate of #8031

**Closed by arkon** 2022-09-19 14:31 UTC
Labels: Bug
