### ISSUE TITLE
Missing Chapters Tooltip

### ISSUE THREAD

**Issue by MetOffi** [tachiyomiorg/tachiyomi#10299] opened 2024-01-06 18:15 UTC
### Describe your suggested feature

Currently it displays a Manga as having missing chapters if you have filtered them (e.g. filtering by unread). It might be good to have settings for this feature to either turn it off entirely or select what conditions it shows under. 
![Screenshot_20240106_181412_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/88634742/1e8859c4-e9cc-4685-8cee-1d72e8aeeb7d)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2024-01-06 18:16
Duplicate of #9259

**Closed by arkon** 2024-01-06 18:16 UTC
Labels: Feature request

**Comment by MetOffi** [comment] 2024-01-06 18:18
> Duplicate of #9259

Sorry, I wasn't aware this feature was in the app in previous versions since it hadn't appeared on mine. Is there a way to disable this feature?

**Comment by arkon** [comment] 2024-01-06 18:19
No, and there won't be.
