### ISSUE TITLE
Page disappearance 

### ISSUE THREAD

**Issue by Leunsensei** [tachiyomiorg/tachiyomi#10235] opened 2023-12-14 06:19 UTC
### Steps to reproduce

Read manhwa from certain extensions

### Expected behavior

Normal amount of pages

### Actual behavior

The chapter skips backward a few pages, and when you scroll back to resume where you were, the next page is missing.

### Tachiyomi version

Current version 

### Android version

Android 12

### Device

Redmi note 10 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Leunsensei** [comment] 2023-12-14 06:45
@
![Screenshot_2023-12-14-07-36-36-366_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/98178685/37ebd29b-3908-47a5-be66-2ce15985bdd0)

The second panel is incomplete because the page disappeared

**Comment by arkon** [comment] 2023-12-17 16:34
Duplicate of #3279

**Closed by arkon** 2023-12-17 16:34 UTC
Labels: Bug
