### ISSUE TITLE
[Bug] Crash at start : biometric hardware unavailable

### ISSUE THREAD

**Issue by arthus-leroy** [tachiyomiorg/tachiyomi#5120] opened 2021-05-21 00:10 UTC
## Device information
Tachiyomi version: v0.10.12
Android version: 10
Device: Samsung Galaxy Tab A

## Steps to reproduce
Enable the biometric hardware (aka unlock) feature
Kill the app
Try to reopen the app

### Expected behavior
The app starts normally

### Actual behavior
The app crashes at start, no way to enter the app

## Other details
This device has no hardware biometric sensor (fingerprint, etc).
A crash log doesn’t seem to have been generated as no Tachiyomi folder was created. The crash log was generated on TachiyomiSY though (where the folder previously existed).

A solution would be to disable this option altogether and warn people that try to allow it if no sensor is detected. Another would be to implement a pattern as fallback.

**Comment by arkon** [comment] 2021-05-21 00:18
Can you upload the logs from SY?

**Comment by arthus-leroy** [comment] 2021-05-21 00:20
[2021-05-21-release.log](https://github.com/tachiyomiorg/tachiyomi/files/6519287/2021-05-21-release.log)

**Comment by arkon** [comment] 2021-05-22 16:25
Duplicate of #4999

**Closed by arkon** 2021-05-22 16:25 UTC
Labels: bug
