### ISSUE TITLE
Ability to Rename Chapter 

### ISSUE THREAD

**Issue by TheKingTermux** [tachiyomiorg/tachiyomi#7734] opened 2022-08-12 22:11 UTC
### Describe your suggested feature

![IMG_20220813_050720](https://user-images.githubusercontent.com/50316075/184451079-449e9089-748f-4632-a1e6-57d49d8fd54c.jpg)

- Please add the ability to change chapter names.
As in the picture above, there are 2 chapters of 10, even though the chapter 10 below is chapter 11. When chapter 10 is finished downloading, the 2 chapters will display chapter 10 and not display chapter 11.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-08-12 22:26
Duplicate of #5270

**Closed by arkon** 2022-08-12 22:26 UTC
Labels: Feature request
