### ISSUE TITLE
[Feature Request] Migrate broken sources

### ISSUE THREAD

**Issue by KuronekoVII** [tachiyomiorg/tachiyomi#4676] opened 2021-03-20 01:16 UTC
## Why/User Benefit/User Problem
Sometimes users have a big library, so knowing that everything works can be difficult, so this would be a lot helpful and when it does its manga updates, we have no way knowing, it could ease everyone when changing phones too, since when you restore your library via backup, you can lost some mangas which you were reading.

## What/Requirements
Itought of 2 ways to making this work:
1- making an undeletable category that everytime it breaks, its added there until user migrate it
2- making an option at more menu where it will be listed there until user migrate it

**Comment by scb261** [comment] 2021-03-20 01:27
Duplicate of #4616

Also:
- Enable `Settings > Library > Show update errors notifications` to see list of failed updates
- New backup restores manga even if its source is missing or doesn't work

**Closed** 2021-03-20 01:40 UTC
Labels: feature
