### ISSUE TITLE
[Bug] Local source manga folders not displaying cover image

### ISSUE THREAD

**Issue by alexphilip0019** [tachiyomiorg/tachiyomi#5273] opened 2021-06-02 09:55 UTC
Local source manga folders don't display cove images.
Editing cover image also does not display cover image in library.

Also the cover image selected appears as cover.jpg in tachiyomi/local/samplefolder/cover.jpg

Issue occuring in tachiyomi version:. 0.11.1

**Comment by arkon** [comment] 2021-06-02 12:30
Duplicate of #932

**Closed by arkon** 2021-06-02 12:30 UTC
Labels: bug
