### ISSUE TITLE
Cover went blank if the name of local manga is not English

### ISSUE THREAD

**Issue by kevin930321** [tachiyomiorg/tachiyomi#10298] opened 2024-01-06 18:03 UTC
### Steps to reproduce

1.Create a local manga with Japanese name
2.Try to add a cover

### Expected behavior

Cover should appear correctly

### Actual behavior

No cover
![Screenshot_20240107-020158_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/78043580/efd567b3-f4f9-4733-a668-8f88f60c56bd)

### Tachiyomi version

0.15.0-6376 (standard, c4ceda59d, 115, 2024-01-06T14:57Z) 

### Android version

13 (SDK 33; build TKQ1.220807.001.33.0804.2060.204 release-keys) 

### Device

ASUS_AI2202 (WW_AI2202) 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2024-01-06 18:12
Duplicate of #1808

**Closed by arkon** 2024-01-06 18:12 UTC
Labels: Bug
