### ISSUE TITLE
option to turn on/off simultaneously download from different sources

### ISSUE THREAD

**Issue by oxsi91** [tachiyomiorg/tachiyomi#6398] opened 2021-12-27 22:31 UTC
### Describe your suggested feature

I see when download new chapter from 2 different manga, it download both simultaneously. when asking it in discord someone said it download 1 by 1 from same source, and simultaneously download if it from different source

Please add option to turn on/off simultaneously download from different sources. Dont know for other but for me it better if it download 1 by 1 even if it from different source

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2021-12-28 00:51
Duplicate of #3472

**Closed by Seishirou101** 2021-12-28 00:51 UTC
Labels: Feature request
