### ISSUE TITLE
Auto translate

### ISSUE THREAD

**Issue by CharlesMoreira1** [tachiyomiorg/tachiyomi#10256] opened 2023-12-21 17:38 UTC
### Describe your suggested feature

Hi, guys! Would it be feasible to add a new feature that translates speech bubbles manually?

For example, highlighting around each bubble, using OCR to identify the text, and then translating it using an API, such as ChatGPT itself?

Users who want to use this feature would need to create an account on OpenAI and generate a KEY there.

If it's feasible, I'd like to implement this feature.

Example:

![image4](https://github.com/tachiyomiorg/tachiyomi/assets/55266908/a6c042d1-5227-4bc0-ac8b-4633cd0f7fff)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-12-21 18:07
Duplicate of #9752

I don't know why you'd want to use a LLM like ChatGPT for translation though, unless you just want it to make up stuff.

**Closed by arkon** 2023-12-21 18:07 UTC
Labels: Feature request

**Comment by CharlesMoreira1** [comment] 2023-12-21 18:18
> Duplicado de #9752
> 
> Não sei porque você gostaria de usar um LLM como o ChatGPT para tradução, a menos que queira apenas inventar coisas.

The ChatGPT API was more like an example; it could be any other, like Google or DeepL.
