### ISSUE TITLE
Saving filters in sources as in tachiyomisy

### ISSUE THREAD

**Issue by ve1mi** [tachiyomiorg/tachiyomi#5873] opened 2021-09-07 19:04 UTC
### Describe your suggested feature

It's very annoying to constantly put the same filters for sorting. I like to read manhwa and usually filter by manhwa and update date. I don't really understand why this will not be added to the main application, it is very convenient and can be constantly used

### Other details
![Screenshot_2021-09-07-21-57-01-102_eu kanade tachiyomi sy](https://user-images.githubusercontent.com/45261656/132397688-f9e6fb32-b403-40c0-87a5-ff16caea3c04.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2021-09-07 19:05
Duplicate of #1484

**Comment by ve1mi** [comment] 2021-09-07 19:06
> ### Describe your suggested feature
> It's very annoying to constantly put the same filters for sorting. I like to read manhwa and usually filter by manhwa and update date. I don't really understand why this will not be added to the main application, it's very convenient and can be constantly used
> 
> ### Other details
> ![Screenshot_2021-09-07-21-57-01-102_eu kanade tachiyomi sy](https://user-images.githubusercontent.com/45261656/132397688-f9e6fb32-b403-40c0-87a5-ff16caea3c04.jpg)
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> * [x]  I have written a short but informative title.
> * [x]  If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
> * [x]  I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
> * [x]  I will fill out all of the requested information in this form.

**Closed** 2021-09-07 19:06 UTC
Labels: Feature request

**Comment by ve1mi** [comment] 2021-09-07 21:03
It seems to me that in 3 years it's possible to add this useful function. This is not a joke, but I'm really tired of pressing the same filters.

**Comment by CrepeTF** [comment] 2021-09-07 21:32
You could just use SY

**Comment by ve1mi** [comment] 2021-09-07 21:36
> You could just use SY
I know but I don’t want to. I don't like app icon and splash SY
