### ISSUE TITLE
Searching and Migrating became much much slower after the latest update

### ISSUE THREAD

**Issue by BlizzardFreeze** [tachiyomiorg/tachiyomi#8940] opened 2023-01-18 07:56 UTC
### Steps to reproduce

I tried migrating a series, but it took much much longer than usual. 
I also tried searching for a series and it took sooo much time than usual. 

### Expected behavior

Usually it only took the app seconds to show the result for migrating or searching a series. 

### Actual behavior

After the latest update, it took more than 2 minutes just to search or migrate a series. 
It also shows some cloudflare notification in some extension that usually has no issue whatsoever. 

### Tachiyomi version

0.14.3

### Android version

Android 12

### Device

Realme 8 4g

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2023-01-18 09:15
Searching time and cloudflare issues are usually related to network connection and website service changes. Also some extensions might have added rate limit to prevent being banned by the website. This is not an issue with the app.

**Comment by BlizzardFreeze** [comment] 2023-01-18 09:19
No man, my internet is perfectly fine. I can even play 1080p videos on youtube with no issue. 
Before the update, it just took seconds for migrating ot searching a series. After the update, it took minutes to search or migrate a series. 
I don't use VPN. 
Everything was fine before the latest update.

**Comment by stevenyomi** [comment] 2023-01-18 09:21
Are you experiencing slow search in every source that you use?

**Comment by BlizzardFreeze** [comment] 2023-01-18 09:26
Yes. It took a significant time in each extension to search a series. 
Usually, it took only less than 3 seconds for a result to show up.

**Comment by stevenyomi** [comment] 2023-01-18 09:51
Global search issue is #8906 and it's already fixed. Try installing the [latest preview](https://github.com/tachiyomiorg/tachiyomi-preview/releases) and search something in that version.

**Comment by BlizzardFreeze** [comment] 2023-01-18 09:58
I'm sorry, I don't understand what you mean by "installing the latest preview". Do I have to install a new tachiyomi apk? If yes, which one exactly do I need to install?

**Comment by CrepeTF** [comment] 2023-01-18 10:01
choose the largest apk

**Comment by BlizzardFreeze** [comment] 2023-01-18 10:11
I did installed the largest apk but the problem hasn't solved. It still took me ages to search or migrate a series.

**Comment by stevenyomi** [comment] 2023-01-18 10:33
Did you try searching in the newly installed version? It's not an extension and won't affect your original app.

**Comment by BlizzardFreeze** [comment] 2023-01-18 10:39
NIIIIICE. That's more like it! It worked!
@CrepeTF told me to install the largest apk but it was not the fix. 
I installed the apk in the first list and it worked. 
Thank you very much @stevenyomi.

**Comment by stevenyomi** [comment] 2023-01-18 10:45
In the next stable version this issue will be solved.

**Comment by stevenyomi** [comment] 2023-01-18 10:46
Duplicate of #8906

**Closed by stevenyomi** 2023-01-18 10:46 UTC
Labels: Bug
