### ISSUE TITLE
Cant Open Tachiyomi preview 4697 After Update

### ISSUE THREAD

**Issue by nurananto** [tachiyomiorg/tachiyomi#7615] opened 2022-07-26 13:49 UTC
### Steps to reproduce

Open tachiyomi

### Expected behavior

Tachiyomi opened

### Actual behavior

Forced closed

### Crash logs

>[Tachiyomi Log](https://drive.google.com/file/d/167594nyYuXHhot8rI38zuM-NuCivoJQ3/view?usp=drivesdk) 

### Tachiyomi version

4697

### Android version

12.1

### Device

Poco X3 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-07-26 21:19
Duplicate of #7616

**Closed by arkon** 2022-07-26 21:19 UTC
Labels: Bug
