### ISSUE TITLE
Webtoon reading mode scrolling stops early on last image of last chapter

### ISSUE THREAD

**Issue by AgentX2006** [tachiyomiorg/tachiyomi#8389] opened 2022-10-31 12:34 UTC
### Steps to reproduce

When reaching the end of the last available chapter in webtoon reading mode it sometimes stops scrolling before reaching the end of the last image. In the included screenshot the red line I added is where it stopped. You couldn't scroll past where the red line is.

Not sure how to reliably reproduce this as it's very intermittent. Scrolling up to a previous chapter may be a contributing factor. This happens with or without downloading the chapter and with or without the automatic resizing of long images turned on. Have experienced this bug through many versions of the app.

![Screenshot_20221031-0706572](https://user-images.githubusercontent.com/51245403/199005344-e630b91a-d9d6-46d9-b3f1-d121c22478ff.png)

### Expected behavior

The entirety of the image will be displayed when scrolling to the end of a chapter. After that the "There's no next chapter" message will be displayed and the navigation overlay will pop up.

### Actual behavior

You can't scroll to the end of the last image and the "There's no next chapter" message does not appear nor does the navigation overlay pop up.

### Tachiyomi version

0.14.1

### Android version

Android 11 & 13

### Device

SKY Devices Elite Octa tablet, Google Pixel 6a, Samsung Galaxy A10e

### Other details

Will try and get an actual screen recording next time it happens and add it to the report.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-10-31 13:28
Duplicate of #3052, I think.

**Closed by arkon** 2022-10-31 13:28 UTC
Labels: Bug
