### ISSUE TITLE
[Bug] <Komikcast NO RESULT FOUND>

### ISSUE THREAD

**Issue by Noobmaster27** [tachiyomiorg/tachiyomi#4669] opened 2021-03-19 02:22 UTC
## Device information
* Tachiyomi version: 0.10.9
* Android version: 12
* Device: Xiaomi redmi note 8 pro

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
This should happen.

### Actual behavior
This happened instead.

## Other details
Additional details and attachments.

If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.

**Comment by arkon** [comment] 2021-03-19 02:26
Duplicate of https://github.com/tachiyomiorg/tachiyomi-extensions/issues/6212

**Closed by arkon** 2021-03-19 02:26 UTC
Labels: bug
