### ISSUE TITLE
Writing notes in chapters 

### ISSUE THREAD

**Issue by Wannabeestic** [tachiyomiorg/tachiyomi#8598] opened 2022-11-22 17:39 UTC
### Describe your suggested feature

For example if you want to note something happened in that chapter 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2022-11-22 17:43
Duplicate of #2155

**Closed by Seishirou101** 2022-11-22 17:43 UTC
Labels: Feature request
