### ISSUE TITLE
Filter by source correctly

### ISSUE THREAD

**Issue by connortraveller** [tachiyomiorg/tachiyomi#9769] opened 2023-07-28 16:52 UTC
### Describe your suggested feature

When reading a series (in my case solo levelling from the mangadex extension), there are multiple different sources for each chapter, with no way to filter them out even when I select by source. Attatched are links to show my screen.

### Other details

https://imgur.com/Tow6noj
https://imgur.com/lb2HPSw

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2023-07-28 16:55
Duplicate of #969

**Closed by alessandrojean** 2023-07-28 16:55 UTC
Labels: Feature request

**Comment by Seishirou101** [comment] 2023-07-28 17:18
to clarify, the sort by source means that it will give you the sort that the source provides, so whatever mangadex returns as the chapter list without any sorting done locally in this case.
