### ISSUE TITLE
[Feature Request] Option to show manga source badge (or perhaps filter by source) in library

### ISSUE THREAD

**Issue by Vertiguous** [tachiyomiorg/tachiyomi#5396] opened 2021-06-14 13:42 UTC
## Why/User Benefit/User Problem
In some cases I (and perhaps others) have multiple "copies" of the same manga in my library, but from multiple sources. In my case it's usually because the source I trust most doesn't have all the chapters. This would make it easier to tell them apart.

e.g. Currently there are no new chapters on MangaDex (yet), so I have a copy of some of these manga on a different source.

## What/Requirements
You could make it similar to how you can already show a little badge next to a manga that's saved locally on the phone. Because not _everyone_ needs it, I think making it an option similar to Local badges would be appropriate.

Alternatively, make it possible to filter your library by source. Of course, being able to do both would be great, but having just one of these would really help.

**Comment by kiriya-aoi** [comment] 2021-06-14 19:10
To show only manga in your library from a particular source, you can search the source name.

**Comment by arkon** [comment] 2021-06-14 21:13
Duplicate of #3491

**Closed by arkon** 2021-06-14 21:13 UTC
Labels: feature
