### ISSUE TITLE
Add Migrate option when one tries to add to the library an entry with the same name.

### ISSUE THREAD

**Issue by Palloxin** [tachiyomiorg/tachiyomi#9175] opened 2023-03-05 16:33 UTC
### Describe your suggested feature

![IMG_20230305_172421](https://user-images.githubusercontent.com/75091899/222973120-b240432d-c5ff-4afc-b662-62fbe0faaf1b.jpg)
Add the Migrate option here.

### Other details

It is just a simple QoL change that removes the hassle of going to the migrate option of the already added entry. Actually one needs to exit the second same entry(image above), go to the library, find the entry already added, migrate, and wait the second same entry to be found again... it is a hassle.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-03-05 16:43
Duplicate of #7094

**Closed by arkon** 2023-03-05 16:43 UTC
Labels: Feature request
