### ISSUE TITLE
improvement and or change to the animate page transition feature

### ISSUE THREAD

**Issue by NotPageD** [tachiyomiorg/tachiyomi#6343] opened 2021-12-12 16:26 UTC
### Describe your suggested feature

so instead of just an animation of moving left and right, there would be a new animation option of actually flipping a page, sort of like this. 

https://user-images.githubusercontent.com/78807765/145720299-377b166c-e212-4136-ab10-9ee309b724fa.mp4

### Other details

also, i would like to ask for a slower speed of the old and the new animation of page transitions, i think if the speed is slower, it would look a lot nicer. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2021-12-12 16:27
Duplicate of #1397

**Closed by arkon** 2021-12-12 16:27 UTC
Labels: Feature request
