### ISSUE TITLE
Unable to install extension (Both packageinstaller and legacy)

### ISSUE THREAD

**Issue by wyue02** [tachiyomiorg/tachiyomi#9727] opened 2023-07-16 18:30 UTC
### Steps to reproduce

1. Tap the install button next to an extension

### Expected behavior

The icon of the extension loads for a second and the install menu pops up, giving the user the choice to select "Install" or "Cancel"

### Actual behavior

packageinstaller:
Nothing happens

Legacy:
"There was a problem while parsing the package" error

### Crash logs

Catlog for packageinstaller:

> 07-17 02:19:08.024   647 29035 E vold    : Failed to set project id on /data/media/0/Android/data/eu.kanade.tachiyomi/: Operation not supported on transport endpoint
> 07-17 02:19:08.025  1431  4622 E StorageManagerService: Failed to fixup app dir for eu.kanade.tachiyomi
> 07-17 02:19:08.061 28788 28821 V DownloadManager: Deleting /storage/emulated/0/Android/data/eu.kanade.tachiyomi/files/Download/tachiyomi-all.mangadex-v1.4.183.apk via provider delete
> 07-17 02:19:08.103  1431  1431 I NotificationService: Cannot find enqueued record for key: 0|com.android.providers.downloads|0|1:eu.kanade.tachiyomi|10049
> 07-17 02:19:08.179  1431  1431 I NotificationService: Cannot find enqueued record for key: 0|com.android.providers.downloads|0|1:eu.kanade.tachiyomi|10049
> 07-17 02:19:08.235  1431  1431 I NotificationService: Cannot find enqueued record for key: 0|com.android.providers.downloads|0|1:eu.kanade.tachiyomi|10049
> 07-17 02:19:08.252  1431  1431 I NotificationService: Cannot find enqueued record for key: 0|eu.kanade.tachiyomi|-402|null|10251

Catlog for legacy:

> 07-17 02:20:54.591   647 29035 E vold    : Failed to set project id on /data/media/0/Android/data/eu.kanade.tachiyomi/: Operation not supported on transport endpoint
> 07-17 02:20:54.593  1431  2917 E StorageManagerService: Failed to fixup app dir for eu.kanade.tachiyomi
> 07-17 02:20:54.609  1431  2959 I ActivityTaskManager: START u0 {dat=content://eu.kanade.tachiyomi.provider/... typ=application/vnd.android.package-archive flg=0x10000001 cmp=eu.kanade.tachiyomi/.extension.util.ExtensionInstallActivity (has extras)} from uid 10251
> 07-17 02:20:54.630  1431  2959 I ActivityTaskManager: The Process eu.kanade.tachiyomi Already Exists in BG. So sending its PID: 28065
> 07-17 02:20:54.639  1431  2917 I ActivityTaskManager: START u0 {act=android.intent.action.INSTALL_PACKAGE dat=content://eu.kanade.tachiyomi.provider/... typ=application/vnd.android.package-archive flg=0x1 cmp=com.google.android.packageinstaller/com.android.packageinstaller.InstallStart (has extras)} from uid 10251
> 07-17 02:20:54.659  1431  2917 D CoreBackPreview: Window{d2c1598 u0 eu.kanade.tachiyomi/eu.kanade.tachiyomi.extension.util.ExtensionInstallActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@a1e61d6, mPriority=0}
> 07-17 02:20:54.703  1431  6491 I ActivityTaskManager: START u0 {act=android.intent.action.INSTALL_PACKAGE dat=content://eu.kanade.tachiyomi.provider/... typ=application/vnd.android.package-archive flg=0x2000001 cmp=com.google.android.packageinstaller/com.android.packageinstaller.InstallStaging (has extras)} from uid 10060
> 07-17 02:20:54.733  1431  1431 I NotificationService: Cannot find enqueued record for key: 0|com.android.providers.downloads|0|1:eu.kanade.tachiyomi|10049
> 07-17 02:20:54.786  1431  1431 I NotificationService: Cannot find enqueued record for key: 0|com.android.providers.downloads|0|1:eu.kanade.tachiyomi|10049
> 07-17 02:20:54.803  1431  1431 I NotificationService: Cannot find enqueued record for key: 0|com.android.providers.downloads|0|1:eu.kanade.tachiyomi|10049

### Tachiyomi version

0.14.6

### Android version

13

### Device

Redmi Note 9S Global (miatoll)

### Other details

I am on a custom rom (Pixel Experience Plus 13)

A few things I tried to fix the issue:
- Clear data of download manager
- Clear data of package installer
- Reformat my phone
- run `adb shell cmd appops set eu.kanade.tachiyomi android:legacy_storage allow`

I am also facing this issue on TachiyomiSY stable and Tachiyomi preview (r5933)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2023-07-16 18:34
Disable MIUI optimizations under the developer settings of your phone in order to install extensions in the app.

**Comment by alessandrojean** [comment] 2023-07-16 18:35
Actually leaving it opened as it's a custom ROM.

**Comment by arkon** [comment] 2023-07-16 18:42
Probably worth trying a different ROM?

**Comment by nozwock** [comment] 2023-07-29 05:46
I have had the same issue for a long time now. On stock Rom OxygenOS 13.1 (Android 13)

"There was a problem parsing this package."

I'm able to install the Install/Update extensions if I download them from GitHub first.

**Comment by lightbulbatelier** [comment] 2023-07-29 21:35
I am under stock ROM (Moto G53 Power under Android 13) and I'm experiencing the same problem today.

**Comment by GitH-Michael** [comment] 2023-08-04 23:36
I have the same problem. MIUI 14 device: Redmi Note 12, rooted.

**Comment by PromStorY** [comment] 2023-08-13 19:42
I have the some problem. Redmi Note 9S + OFFICIAL custom ROM crDroid 9.7.

**Comment by CrepeTF** [comment] 2023-08-13 20:06
> I have the some problem. Redmi Note 9S + OFFICIAL custom ROM crDroid 9.7 (Android 13).

If you have a setting for miui optimization, turn that off

**Comment by PromStorY** [comment] 2023-08-14 14:05
> > I have the some problem. Redmi Note 9S + OFFICIAL custom ROM crDroid 9.7 (Android 13).
> 
> If you have a setting for miui optimization, turn that off

i didnt have it, or i didnt know where it, under the developer settings i didnt found it

**Comment by nozwock** [comment] 2023-08-15 03:56
No idea why this is happening? APKs downloaded by Tachiyomi are corrupted somehow. Maybe something's wrong with the code responsible for downloading them?

**Comment by arkon** [comment] 2023-10-28 21:40
Duplicate of #4106

**Closed by arkon** 2023-10-28 21:40 UTC
Labels: Bug
