### ISSUE TITLE
After updating 99% of the library, nothing comes out in notification

### ISSUE THREAD

**Issue by Kaankaas15474** [tachiyomiorg/tachiyomi#10150] opened 2023-11-19 11:33 UTC
### Steps to reproduce

Update the entire library (manually or automatically)

### Expected behavior

After updating everything, I should get a notification with the logs showing the mangas that were not updated and their reason

### Actual behavior

When reaching the last update of a manga, the notification disappears and the logs are not displayed

### Crash logs

--------- beginning of main
11-19 12:21:33.060 24530 24569 E SQLiteLog: (283) recovered 107 frames from WAL file /data/user/0/eu.kanade.tachiyomi/databases/tachiyomi.db-wal
11-19 12:21:33.109 24530 24588 E chromium: [1119/122133.108836:ERROR:variations_seed_loader.cc(69)] Failed to open file for reading. Errno: 2
11-19 12:21:33.358 24530 24618 E SQLiteLog: (284) automatic index on C(manga_id)
11-19 12:21:33.358 24530 24618 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
11-19 12:29:07.339 28424 28466 E SQLiteLog: (283) recovered 218 frames from WAL file /data/user/0/eu.kanade.tachiyomi/databases/tachiyomi.db-wal
11-19 12:29:07.367 28424 28485 E chromium: [1119/122907.366845:ERROR:variations_seed_loader.cc(69)] Failed to open file for reading. Errno: 2
11-19 12:29:07.592 28424 28512 E SQLiteLog: (284) automatic index on C(manga_id)
11-19 12:29:07.592 28424 28512 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.14.7 (standard, c8d6859, 102, 2023-10-25T16:11Z)
Android version: 14 (SDK 34)
Android build ID: UP1A.231005.007.S918BXXS3BWK5
Device brand: samsung
Device manufacturer: samsung
Device name: dm3q
Device model: SM-S918B
Device product name: dm3qxeea

### Tachiyomi version

0.14.7

### Android version

14

### Device

Samsung galaxy s23 ultra

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment] 2023-11-19 14:27
Refer to: https://tachiyomi.org/docs/faq/library#why-is-global-update-skipping-entries

Alternatively, duplicate of https://github.com/tachiyomiorg/tachiyomi/issues/6985

**Closed by curche** 2023-11-19 14:27 UTC
Labels: Bug
