### ISSUE TITLE
Tracking

### ISSUE THREAD

**Issue by SMY19** [tachiyomiorg/tachiyomi#10167] opened 2023-11-24 07:02 UTC
### Describe your suggested feature

Can you please add new tracking apps for manhwa?? It would be so much better if it had manhwa only.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment] 2023-11-24 09:11
There are no other sites that have APIs available for Tachiyomi to use so this is not feasible right now

**Comment by loocool2** [comment] 2023-11-24 09:12
Duplicate of #1785 and other issues

**Closed by loocool2** 2023-11-24 09:12 UTC
Labels: Feature request
