### ISSUE TITLE
Resuming chapter randomly giving a "the image couldn't be loaded" with webtoon view

### ISSUE THREAD

**Issue by yohanim** [tachiyomiorg/tachiyomi#8995] opened 2023-01-28 20:21 UTC
### Steps to reproduce

From time to time, while using the "resume" button, we get the error "the image couldn't be loaded" but the images are there and very big empty space are present between each image.
It happens only with webtoon for me.
Also, recently I can't have it at all if I launch the chapter directly from the recent view or the chapter list view, only with the "resume" button.

### Expected behavior

No error and right spacing between images

### Actual behavior

Error message, resulting buttons to reload (that solve nothing), big empty space between images
![Screenshot_2023-01-28-21-05-00-467_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/2168165/215289118-1fcc0c92-4f87-4a37-a1ba-c2bc7394402b.jpg)

![Screenshot_2023-01-28-21-04-46-580_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/2168165/215289126-69f5fd4a-a09f-4f9e-bc65-ecb53a222745.jpg)

### Crash logs

--------- beginning of crash
12-24 10:55:12.994 25969 25969 E AndroidRuntime: FATAL EXCEPTION: main
12-24 10:55:12.994 25969 25969 E AndroidRuntime: Process: eu.kanade.tachiyomi.debug, PID: 25969
12-24 10:55:12.994 25969 25969 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{eu.kanade.tachiyomi.debug/eu.kanade.tachiyomi.ui.main.MainActivity}: java.lang.NullPointerException
12-24 10:55:12.994 25969 25969 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3773)
12-24 10:55:12.994 25969 25969 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3940)
12-24 10:55:12.994 25969 25969 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
12-24 10:55:12.994 25969 25969 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
12-24 10:55:12.994 25969 25969 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
12-24 10:55:12.994 25969 25969 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2320)
12-24 10:55:12.994 25969 25969 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-24 10:55:12.994 25969 25969 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:210)
12-24 10:55:12.994 25969 25969 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:299)
12-24 10:55:12.994 25969 25969 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8268)
12-24 10:55:12.994 25969 25969 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-24 10:55:12.994 25969 25969 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
12-24 10:55:12.994 25969 25969 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
12-24 10:55:12.994 25969 25969 E AndroidRuntime: Caused by: java.lang.NullPointerException
12-24 10:55:12.994 25969 25969 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.browse.extension.details.SourcePreferencesFragment.onCreatePreferences(SourcePreferencesScreen.kt:34)
12-24 10:55:12.994 25969 25969 E AndroidRuntime: 	at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:73)
12-24 10:55:12.994 25969 25969 E AndroidRuntime: 	at androidx.fragment.app.Fragment.performCreate(Fragment.java:27)
12-24 10:55:12.994 25969 25969 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:44)
12-24 10:55:12.994 25969 25969 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:115)
12-24 10:55:12.994 25969 25969 E AndroidRuntime: 	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:31)
12-24 10:55:12.994 25969 25969 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:28)
12-24 10:55:12.994 25969 25969 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:10)
12-24 10:55:12.994 25969 25969 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:12)
12-24 10:55:12.994 25969 25969 E AndroidRuntime: 	at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:5)
12-24 10:55:12.994 25969 25969 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:13)
12-24 10:55:12.994 25969 25969 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.base.activity.BaseActivity.onCreate(BaseActivity.kt:11)
12-24 10:55:12.994 25969 25969 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.main.MainActivity.onCreate(MainActivity.kt:19)
12-24 10:55:12.994 25969 25969 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8191)
12-24 10:55:12.994 25969 25969 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8159)
12-24 10:55:12.994 25969 25969 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
12-24 10:55:12.994 25969 25969 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3746)
12-24 10:55:12.994 25969 25969 E AndroidRuntime: 	... 12 more
01-24 13:28:14.686 11852 11852 E AndroidRuntime: FATAL EXCEPTION: main
01-24 13:28:14.686 11852 11852 E AndroidRuntime: Process: eu.kanade.tachiyomi.debug, PID: 11852
01-24 13:28:14.686 11852 11852 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{eu.kanade.tachiyomi.debug/eu.kanade.tachiyomi.ui.main.MainActivity}: java.lang.NullPointerException
01-24 13:28:14.686 11852 11852 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3773)
01-24 13:28:14.686 11852 11852 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3940)
01-24 13:28:14.686 11852 11852 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
01-24 13:28:14.686 11852 11852 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
01-24 13:28:14.686 11852 11852 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
01-24 13:28:14.686 11852 11852 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2320)
01-24 13:28:14.686 11852 11852 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-24 13:28:14.686 11852 11852 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:210)
01-24 13:28:14.686 11852 11852 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:299)
01-24 13:28:14.686 11852 11852 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8268)
01-24 13:28:14.686 11852 11852 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-24 13:28:14.686 11852 11852 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
01-24 13:28:14.686 11852 11852 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
01-24 13:28:14.686 11852 11852 E AndroidRuntime: Caused by: java.lang.NullPointerException
01-24 13:28:14.686 11852 11852 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.browse.extension.details.SourcePreferencesFragment.onCreatePreferences(SourcePreferencesScreen.kt:34)
01-24 13:28:14.686 11852 11852 E AndroidRuntime: 	at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:73)
01-24 13:28:14.686 11852 11852 E AndroidRuntime: 	at androidx.fragment.app.Fragment.performCreate(Fragment.java:27)
01-24 13:28:14.686 11852 11852 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:41)
01-24 13:28:14.686 11852 11852 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:110)
01-24 13:28:14.686 11852 11852 E AndroidRuntime: 	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:31)
01-24 13:28:14.686 11852 11852 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:28)
01-24 13:28:14.686 11852 11852 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:10)
01-24 13:28:14.686 11852 11852 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:12)
01-24 13:28:14.686 11852 11852 E AndroidRuntime: 	at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:5)
01-24 13:28:14.686 11852 11852 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:13)
01-24 13:28:14.686 11852 11852 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.base.activity.BaseActivity.onCreate(BaseActivity.kt:11)
01-24 13:28:14.686 11852 11852 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.main.MainActivity.onCreate(MainActivity.kt:19)
01-24 13:28:14.686 11852 11852 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8191)
01-24 13:28:14.686 11852 11852 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8159)
01-24 13:28:14.686 11852 11852 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
01-24 13:28:14.686 11852 11852 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3746)
01-24 13:28:14.686 11852 11852 E AndroidRuntime: 	... 12 more
--------- beginning of main
01-28 20:54:38.993 19460 19504 E QT      : [QT]file does not exist
01-28 20:54:38.995 19460 19504 E QT      : [QT]file does not exist
01-28 20:54:39.000 19460 19498 E SQLiteLog: (283) recovered 203 frames from WAL file /data/user/0/eu.kanade.tachiyomi.debug/databases/tachiyomi.db-wal
01-28 20:54:39.476 19460 19617 E SQLiteLog: (284) automatic index on C(manga_id)
01-28 20:54:39.476 19460 19617 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
01-28 20:54:39.503 19460 19502 E OpenGLRenderer: fbcNotifyFrameComplete error: undefined symbol: fbcNotifyFrameComplete
01-28 20:54:39.503 19460 19502 E OpenGLRenderer: fbcNotifyNoRender error: undefined symbol: fbcNotifyNoRender
01-28 20:54:40.988 19460 19644 E ion     : ioctl c0044901 failed with code -1: Invalid argument
01-28 20:54:48.551 19460 19483 E SubsamplingScaleImageView: Failed to initialise bitmap decoder
01-28 20:54:48.551 19460 19483 E SubsamplingScaleImageView: java.lang.Exception: Image decoder failed to initialize and get image size
01-28 20:54:48.551 19460 19483 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.decoder.ImageDecoder.init(ImageDecoder.java:46)
01-28 20:54:48.551 19460 19483 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:8)
01-28 20:54:48.551 19460 19483 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1)
01-28 20:54:48.551 19460 19483 E SubsamplingScaleImageView: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
01-28 20:54:48.551 19460 19483 E SubsamplingScaleImageView: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
01-28 20:54:48.551 19460 19483 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
01-28 20:54:48.551 19460 19483 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
01-28 20:54:48.551 19460 19483 E SubsamplingScaleImageView: 	at java.lang.Thread.run(Thread.java:1012)
01-28 20:54:48.552 19460 19727 E SubsamplingScaleImageView: Failed to initialise bitmap decoder
01-28 20:54:48.552 19460 19727 E SubsamplingScaleImageView: java.lang.Exception: Image decoder failed to initialize and get image size
01-28 20:54:48.552 19460 19727 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.decoder.ImageDecoder.init(ImageDecoder.java:46)
01-28 20:54:48.552 19460 19727 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:8)
01-28 20:54:48.552 19460 19727 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1)
01-28 20:54:48.552 19460 19727 E SubsamplingScaleImageView: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
01-28 20:54:48.552 19460 19727 E SubsamplingScaleImageView: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
01-28 20:54:48.552 19460 19727 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
01-28 20:54:48.552 19460 19727 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
01-28 20:54:48.552 19460 19727 E SubsamplingScaleImageView: 	at java.lang.Thread.run(Thread.java:1012)
01-28 21:01:39.514 19460 19980 E SubsamplingScaleImageView: Failed to initialise bitmap decoder
01-28 21:01:39.514 19460 19980 E SubsamplingScaleImageView: java.lang.Exception: Image decoder failed to initialize and get image size
01-28 21:01:39.514 19460 19980 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.decoder.ImageDecoder.init(ImageDecoder.java:46)
01-28 21:01:39.514 19460 19980 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:8)
01-28 21:01:39.514 19460 19980 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1)
01-28 21:01:39.514 19460 19980 E SubsamplingScaleImageView: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
01-28 21:01:39.514 19460 19980 E SubsamplingScaleImageView: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
01-28 21:01:39.514 19460 19980 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
01-28 21:01:39.514 19460 19980 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
01-28 21:01:39.514 19460 19980 E SubsamplingScaleImageView: 	at java.lang.Thread.run(Thread.java:1012)
01-28 21:01:39.514 19460 20088 E SubsamplingScaleImageView: Failed to initialise bitmap decoder
01-28 21:01:39.514 19460 20088 E SubsamplingScaleImageView: java.lang.Exception: Image decoder failed to initialize and get image size
01-28 21:01:39.514 19460 20088 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.decoder.ImageDecoder.init(ImageDecoder.java:46)
01-28 21:01:39.514 19460 20088 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:8)
01-28 21:01:39.514 19460 20088 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1)
01-28 21:01:39.514 19460 20088 E SubsamplingScaleImageView: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
01-28 21:01:39.514 19460 20088 E SubsamplingScaleImageView: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
01-28 21:01:39.514 19460 20088 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
01-28 21:01:39.514 19460 20088 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
01-28 21:01:39.514 19460 20088 E SubsamplingScaleImageView: 	at java.lang.Thread.run(Thread.java:1012)
01-28 21:04:42.016 19460 20236 E SubsamplingScaleImageView: Failed to initialise bitmap decoder
01-28 21:04:42.016 19460 20236 E SubsamplingScaleImageView: java.lang.Exception: Image decoder failed to initialize and get image size
01-28 21:04:42.016 19460 20236 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.decoder.ImageDecoder.init(ImageDecoder.java:46)
01-28 21:04:42.016 19460 20236 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:8)
01-28 21:04:42.016 19460 20236 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1)
01-28 21:04:42.016 19460 20236 E SubsamplingScaleImageView: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
01-28 21:04:42.016 19460 20236 E SubsamplingScaleImageView: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
01-28 21:04:42.016 19460 20236 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
01-28 21:04:42.016 19460 20236 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
01-28 21:04:42.016 19460 20236 E SubsamplingScaleImageView: 	at java.lang.Thread.run(Thread.java:1012)
01-28 21:04:42.016 19460 20330 E SubsamplingScaleImageView: Failed to initialise bitmap decoder
01-28 21:04:42.016 19460 20330 E SubsamplingScaleImageView: java.lang.Exception: Image decoder failed to initialize and get image size
01-28 21:04:42.016 19460 20330 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.decoder.ImageDecoder.init(ImageDecoder.java:46)
01-28 21:04:42.016 19460 20330 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:8)
01-28 21:04:42.016 19460 20330 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1)
01-28 21:04:42.016 19460 20330 E SubsamplingScaleImageView: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
01-28 21:04:42.016 19460 20330 E SubsamplingScaleImageView: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
01-28 21:04:42.016 19460 20330 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
01-28 21:04:42.016 19460 20330 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
01-28 21:04:42.016 19460 20330 E SubsamplingScaleImageView: 	at java.lang.Thread.run(Thread.java:1012)
01-28 21:04:50.571 19460 20411 E SubsamplingScaleImageView: Failed to initialise bitmap decoder
01-28 21:04:50.571 19460 20411 E SubsamplingScaleImageView: java.lang.Exception: Image decoder failed to initialize and get image size
01-28 21:04:50.571 19460 20411 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.decoder.ImageDecoder.init(ImageDecoder.java:46)
01-28 21:04:50.571 19460 20411 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:8)
01-28 21:04:50.571 19460 20411 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1)
01-28 21:04:50.571 19460 20411 E SubsamplingScaleImageView: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
01-28 21:04:50.571 19460 20411 E SubsamplingScaleImageView: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
01-28 21:04:50.571 19460 20411 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
01-28 21:04:50.571 19460 20411 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
01-28 21:04:50.571 19460 20411 E SubsamplingScaleImageView: 	at java.lang.Thread.run(Thread.java:1012)
App version: 0.14.3-5465 (standard, a179327d9, 94, 2023-01-21T21:09Z)
Android version: 12 (SDK 31)
Android build ID: SP1A.210812.016
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: amber
Device model: 21081111RG
Device product name: amber_global

### Tachiyomi version

r5465

### Android version

Android 12

### Device

Mi 11t

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Dari8987898** [comment] 2023-01-30 09:13
Duplicate of #8969

**Comment by arkon** [comment] 2023-02-09 02:54
Might be related to #9001. I haven't seen this happen in recent builds, but please let me know if it still happens.

**Closed by arkon** 2023-02-09 02:54 UTC
Labels: Bug
