### ISSUE TITLE
Funciones para Novelas 

### ISSUE THREAD

**Issue by Jose1159** [tachiyomiorg/tachiyomi#7700] opened 2022-08-07 14:52 UTC
### Describe your suggested feature

Que se pueda leer novelas desde la aplicación 

### Other details

Que se pueda leer novelas utilizando extensiones
de paginas web
![Screenshot_20220807_094954_com android chrome](https://user-images.githubusercontent.com/78783435/183296889-c9eebadc-8a95-4077-b169-93695514868f.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2022-08-07 14:55
No, Tachiyomi is not a light novel reader.

https://tachiyomi.org/help/faq/#can-tachiyomi-read-light-novels

**Comment by AntsyLich** [comment] 2022-08-07 14:55
Duplicate of #3990

**Closed by alessandrojean** 2022-08-07 14:55 UTC
Labels: Feature request
