### ISSUE TITLE
[Bug] Everything is gone

### ISSUE THREAD

**Issue by emmt1998** [tachiyomiorg/tachiyomi#4556] opened 2021-02-27 23:33 UTC
## Device information
* Tachiyomi version: 10.9
* Android version: 10
* Device: Motorola One Fusion

## Steps to reproduce
1. First step
Set that when the phone is charging and is connected to the wifi, update the library
2. Second step
Put to charge the phone while connected to the wifi

### Expected behavior
It should update the library

### Actual behavior
Deletes all informacion in the app(added manga, history), only remaining the tracing from MAL and another pages, and the extension installed

## Other details
This is the second time that it has happend to me, the downloaded chapters are still in the device, but i have to add the manga from exactly the same source to read it from the app.

I have a backup, but i don't think that this is a feature lol.

**Comment by scb261** [comment] 2021-02-27 23:44
It's probably your system or some cleaning app that tries too hard on removing stuff

**Comment by emmt1998** [comment] 2021-02-28 01:02
But the cache and user data of the app remains, and i don't have any apps installed that remove those.
Also, i have being using tachiyomi in this phone for like 6 months now, and only with 10.9 has occured this bug, twice.

**Comment by arkon** [comment] 2021-02-28 21:35
If you can come up with consistent reproduction steps, then please share those.

**Comment by orangpelupa** [comment] 2021-03-03 15:10
IIRC I posted similar bug very long time ago. But I can't find it again

**Comment by arkon** [comment] 2021-03-28 15:13
Closing since unactionable. Please open another issue if you encounter this again and have sufficient steps for reproducing it.

**Closed by arkon** 2021-03-28 15:13 UTC
Labels: bug, needs more info
