### ISSUE TITLE
Trackers set the start date as blank when updating a chapter for an already in progress manga

### ISSUE THREAD

**Issue by hstraten** [tachiyomiorg/tachiyomi#9926] opened 2023-09-12 06:40 UTC
### Steps to reproduce

Add trackers to a manga (I use Anilist and MyAnimeList)
start reading, the start date and chapter progress is as expected.
When continueing to read at a later date, the chapter progress is updated, but the start date is set to a blank date, losing the actual start date.

### Expected behavior

If there is already a startdate in the progress, the tracker should not toch it.

### Actual behavior

The tracker overwrites the startdate with a blank

### Tachiyomi version

0.14.6

### Android version

Android 9

### Device

Nokia 6 (TA-1033)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-09-12 13:23
Duplicate of #6734

**Closed** 2023-09-12 13:24 UTC
Labels: Bug, Duplicate
