### ISSUE TITLE
Drag and drop option for moving categories in the settings tab.

### ISSUE THREAD

**Issue by Raizanad** [tachiyomiorg/tachiyomi#9366] opened 2023-04-19 05:06 UTC
### Describe your suggested feature

Currently you have to click up and down arrows that work one by one tile to rearrange categories.

I suggest adding the option to rearrange via drag and drop. Alternative (or together) with this suggestion, an option to send the category to the bottom or to the top of all categories right next to the arrows that move them one spot up or down.

### Other details

I have searched existing issues that aren't too old. Since I believe that this drag and drop option was possible in the past judging from Aniyomi having it (I know the projects aren't related but maybe it was an old feature before they forked from Tachi).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by kiriya-aoi** [comment] 2023-04-19 14:58
Duplicate of https://github.com/tachiyomiorg/tachiyomi/issues/8325

**Closed** 2023-04-19 15:15 UTC
Labels: Feature request
