### ISSUE TITLE
[Add a comment section] <im not sure if u guys can do this but i hope somewhere in the future u guys can add comment section for all manga that have comment section on their website i know this will be hard for u guys developer hope u read this>

### ISSUE THREAD

**Issue by badzz-05** [tachiyomiorg/tachiyomi#4790] opened 2021-04-07 09:03 UTC
## Why/User Benefit/User Problem
(It would be nice for us users to discuss about the manga or chapters we just completed)

## What/Requirements
(add a small button on reading page to open comment section while reading the manga or on the manga chapters page)

**Comment by Seishirou101** [comment] 2021-04-07 09:32
duplicate of #4336

**Closed** 2021-04-07 12:05 UTC
Labels: feature
