### ISSUE TITLE
[Feature Request] Category/Group for extension installed

### ISSUE THREAD

**Issue by joaoandre120** [tachiyomiorg/tachiyomi#4614] opened 2021-03-07 19:48 UTC
## Why/User Benefit/User Problem
There are several extensions, some of them are for its own types (manga/HQ/adult/manhwa/...), so when we install them, or we pin the main we use, but it makes difficult to search through the others, would have to do individually, or through all installed. ). 

## What/Requirements
It would be good if there wore the possibility to create category/lists for the installed extensions, like for the library.

**Comment by curche** [comment] 2021-03-08 05:46
Duplicate of #1904

**Closed** 2021-03-08 13:23 UTC
Labels: feature
