### ISSUE TITLE
[Feature Request] Custom settings for series

### ISSUE THREAD

**Issue by gonz1324** [tachiyomiorg/tachiyomi#3878] opened 2020-10-02 07:14 UTC
##  Why/User Benefit/User Problem
Each series is different so the default setting does not always reach maximum performance for all the series
## What/Requirements
- Custom rotation : Manhwa/Manhua suitable better with portrait while Manga (especially series with ton of words like Conan) suitable better with landscape
- Custom download new chapters : There are always some on-going series that I bookmarked but don't want to download new chapter yet. Adding an on/off custom download for each series solves that issue

**Comment by scb261** [comment] 2020-10-02 07:21
- Custom rotation: duplicate of #3521
- Custom download: you can use categories for this. For example create category *Reading* and choose only it in *Categories to include in download*

**Comment by gonz1324** [comment] 2020-10-02 12:39
Yes, I am using categories to ignoring download new chapter. The problem here is if the series has set even one category that allow download, It will still download new chapter. Like I have said, adding an on/off custom download for each series will solve that issue.

**Comment by arkon** [comment] 2021-04-28 12:34
Exclusion was added in a recent version which addresses this.

**Closed by arkon** 2021-04-28 12:34 UTC
Labels: feature
