### ISSUE TITLE
Change tracking status to complete and add completed date automatically on finishing the last chapter for AniList and MAL

### ISSUE THREAD

**Issue by loocool2** [tachiyomiorg/tachiyomi#5779] opened 2021-08-23 19:05 UTC
### Describe your suggested feature

When you finish the last chapter that a tracker has recorded in it's database, it could automatically change the reading status and add the finished date. i.e. Anilist has 39 chapters recorded for a finished manga, you finish chapter 39 and it'll automatically change the status to "Completed" and change the finished date to whatever day it is.

### Other details

I noticed Kitsu already has this feature

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2021-11-19 22:21
Duplicate of #3058

**Closed by arkon** 2021-11-19 22:21 UTC
Labels: Feature request
