### ISSUE TITLE
Local source poor loading performance

### ISSUE THREAD

**Issue by Maatteogekko** [tachiyomiorg/tachiyomi#9340] opened 2023-04-15 11:39 UTC
### Steps to reproduce

I have ~16GB of **zipped** files put inside `Tachiyomi/local` folder. When I go to browse it takes 5 to 6 minutes to load, every time.

### Expected behavior

The loading time should be way lower. Or at least it should be lower after the first time.

### Actual behavior

See  _**Steps to reproduce**_

### Tachiyomi version

0.14.5

### Android version

Android 12

### Device

OnePlus 7T Pro

### Other details

Is this a limit of the ZIP files? Would it run better if I had all the files uncompressed instead?

**NB:** The slowdown starts very soon. I'd say it takes an additional ~20 seconds to load for every GB of files.
So even with only 1GB it takes ~20 seconds

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment] 2023-04-15 11:52
Do you use internal storage or SD card for local manga? SD cards on Android are often much slower.

Also you can try this adb command, it can help in your case https://tachiyomi.org/help/faq/#android-11

**Comment by arkon** [comment] 2023-04-15 14:04
Duplicate of #3445

**Closed by arkon** 2023-04-15 14:04 UTC
Labels: Bug

**Comment by Maatteogekko** [comment] 2023-04-15 19:33
@scb261 thank you for the suggestion. I am using internal storage and unfortunately it didn't help
