### ISSUE TITLE
text search doesnt remove html formating

### ISSUE THREAD

**Issue by vallerydelexy** [tachiyomiorg/tachiyomi#5536] opened 2021-07-12 07:55 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 10

### Device

Redmi Note 9 Pro

### Steps to reproduce

copy text that have <h1> tag from internet (chrome), 
paste that text into search bar in browse tab.

### Expected behavior

only the text is pasted
![Uploading Screenshot_2021-07-12-14-43-09-454_eu.kanade.tachiyomi.jpg…]()

### Actual behavior

text and the h1 tag pasted
![Screenshot_2021-07-12-14-42-57-378_eu kanade tachiyomi](https://user-images.githubusercontent.com/17786532/125251047-18892880-e321-11eb-9105-f1d0bbe7a5de.jpg)

**Comment by arkon** [comment] 2021-07-12 13:28
Duplicate of #4828

**Closed by arkon** 2021-07-12 13:28 UTC
Labels: Bug
