### ISSUE TITLE
Allow the library to read from more than one folder

### ISSUE THREAD

**Issue by Megumin230** [tachiyomiorg/tachiyomi#5862] opened 2021-09-06 09:22 UTC
### Describe your suggested feature

My internal storage is full so I got an 8gb sd card to expand it a little, the problem is that when I set the new download path to the sd card, the library no longer loads the manga thats downloaded in the internal storage, I can't avoid this since the sd card has a smaller capacity than the internal 32gb and I can´t transfer everything to the sd card. Allowing tachiyomi to optionally use more than one folder would solve this and would also make future storage upgrades easier.

In short: Library only reads from download path, so give the library the option to read manga from more than one folder, 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment] 2021-09-06 13:27
Duplicate of #4781
> There's no plans to support multiple download locations as it'd make it much more complex.

**Closed** 2021-09-06 13:28 UTC
Labels: Feature request
