### ISSUE TITLE
Download Ahead features works at last chapter of a batch instead of as a sliding window

### ISSUE THREAD

**Issue by curche** [tachiyomiorg/tachiyomi#10151] opened 2023-11-19 14:10 UTC
### Steps to reproduce

1. Choose any manga with lot of (split) chapters like [Angel Next Door Spoils me Rotten](https://mangadex.org/title/2fec6641-beb1-4ae9-a32f-204dd06688ac/the-angel-next-door-spoils-me-rotten)
2. Download a bunch of chapters lets say 10.1 - 10.4
3. Make sure the Download Ahead feature is turned and set to 3 chapters ahead
4. Optionally, enable delete after read
5. Finish reading ch 10.1. Notice that there are no new downloads
6. Finishing reading ch 10.2, 10.3 - once again, no new downloads
7. Finish reading ch 10.4 - the next chapter 11.1 hasnt been downloaded
8. Come out of reader, notice the chapter has started downloading

For illustration purposes, the chapter layout is as follows
`[ ]` represents the currently downloaded chapter
`()` schedule to download/downloading aka in download queue

9.5 - [10.1 - 10.2 - 10.3 - 10.4] - 11.1 - 11.2 - 11.3 - 11.4 - 12.1 - 12.2 - 12.3 - 12.4

### Expected behavior

| Action | New State |
|---|---|
| Initially | 9.5 - **[10.1 - 10.2 - 10.3 - 10.4]** - 11.1 - 11.2 - 11.3 - 11.4 - 12.1 - 12.2 - 12.3 - 12.4 |
| Ch10.1 | 9.5 - 10.1 - **[10.2 - 10.3 - 10.4] - (11.1)** - 11.2 - 11.3 - 11.4 - 12.1 - 12.2 - 12.3 - 12.4 |
| Ch10.2 | 9.5 - 10.1 - 10.2 - **[10.3 - 10.4] - (11.1 - 11.2)** - 11.3 - 11.4 - 12.1 - 12.2 - 12.3 - 12.4 |
| Ch10.3 | 9.5 - 10.1 - 10.2 - 10.3 - **[10.4] - (11.1 - 11.2 - 11.3)** - 11.4 - 12.1 - 12.2 - 12.3 - 12.4 |
| Ch10.4 | 9.5 - 10.1 - 10.2 - 10.3 - 10.4 - **[11.1] - (11.2 - 11.3)** - 11.4 - 12.1 - 12.2 - 12.3 - 12.4 |

As a bare minimum for seamless reading, we assume just ch11.1 finishing downloading. Typically, all the next 3 chapters are downloaded
As you can hopefully see through my shitty attempt, the window of 3 chapters downloaded remains constant and _slides_ to the right

### Actual behavior

| Action | New State |
|---|---|
| Initially | 9.5 - **[10.1 - 10.2 - 10.3 - 10.4]** - 11.1 - 11.2 - 11.3 - 11.4 - 12.1 - 12.2 - 12.3 - 12.4 |
| Ch10.1 | 9.5 - 10.1 - **[10.2 - 10.3 - 10.4]** - 11.1 - 11.2 - 11.3 - 11.4 - 12.1 - 12.2 - 12.3 - 12.4 |
| Ch10.2 | 9.5 - 10.1 - 10.2 - **[10.3 - 10.4]** - 11.1 - 11.2 - 11.3 - 11.4 - 12.1 - 12.2 - 12.3 - 12.4 |
| Ch10.3 | 9.5 - 10.1 - 10.2 - 10.3 - **[10.4]** - 11.1 - 11.2 - 11.3 - 11.4 - 12.1 - 12.2 - 12.3 - 12.4 |
| Ch10.4 | 9.5 - 10.1 - 10.2 - 10.3 - 10.4 - **(11.1 - 11.2 - 11.3)** - 11.4 - 12.1 - 12.2 - 12.3 - 12.4 |

The windows diminishes and then suddenly inflates back, like sound moving through the air for lack of an analogy

### Tachiyomi version

r6194

### Android version

13

### Device

Galaxy Note 10 Lite

### Other details

Why is this a bug instead of feature request? because I remember it used to work like a sliding window in the past but then it kinda changed at some point

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by THElegend5** [comment] 2023-11-19 16:17
Duplicate of #9669

**Closed** 2024-01-07 22:31 UTC
Labels: Bug
