### ISSUE TITLE
Sync the status of a manga with MAL through the categories

### ISSUE THREAD

**Issue by doreori** [tachiyomiorg/tachiyomi#6692] opened 2022-02-22 21:09 UTC
### Describe your suggested feature

It should work like this : 
-Create a category "Stopped" and add the status of the category "Stopped"
-Move manga to the "Stopped" category 
-Refresh the category to update the manga
-It is now shown on MAL that the manga you were reading is currently stopped

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment] 2022-02-22 21:25
Duplicate of #1730

**Closed by loocool2** 2022-02-22 21:25 UTC
Labels: Feature request
