### ISSUE TITLE
[Feature Request] <Force download to finish>

### ISSUE THREAD

**Issue by MrChuw** [tachiyomiorg/tachiyomi#5425] opened 2021-06-19 14:33 UTC
## Why/User Benefit/User Problem
Some manga have one or two pages removed (for various reasons), and during download it never finishes because of that. And when more stuff comes up for download, it restarts downloading those chapters.

## What/Requirements
Some way to manually finish the download, even with missing pages. For him to be removed from downloads and appear offline.

**Comment by arkon** [comment] 2021-06-20 04:58
Duplicate of #3957, I guess. You can manually remove the `_tmp` from the folder name if the contents are okay to you.

**Closed by arkon** 2021-06-20 04:58 UTC
Labels: feature

**Comment by MrChuw** [comment] 2021-06-20 21:57
![SmartSelect_20210620-184714_Tachiyomi.jpg](https://user-images.githubusercontent.com/14945734/122689383-9bbecf00-d1f8-11eb-9fe8-0c1675f5f715.jpg) ![SmartSelect_20210620-184738_File Manager HD.jpg](https://user-images.githubusercontent.com/14945734/122689393-a8dbbe00-d1f8-11eb-9d94-e67d5c311e20.jpg) The chapter won't appear offline because the app didn't detect that the download ended (or I did something wrong). What I would be asking for is a button to finish the download, in this case, the site removed a page that would be ad, but it didn't change the number of pages, so the download is endless.
