### ISSUE TITLE
skips pages when reading 

### ISSUE THREAD

**Issue by HNEnd** [tachiyomiorg/tachiyomi#9952] opened 2023-09-23 12:24 UTC
### Steps to reproduce

1. Open a chapter and start reading in long strip
2. When scrolling it will skip pages (doesn't load and show them)
3. When scrolling back to previous chapter it gets stuck

### Expected behavior

When reading the page should load and if a problem arrives a screen should pop up saying that it couldn't load with the retry button.

Example how the chapter should be:

https://github.com/tachiyomiorg/tachiyomi/assets/74346601/750ba28a-4200-45a3-b970-50a1ab05ecec

### Actual behavior

When reading its skips pages and when scrolling back up it gets stuck.

Example where it goes wrong(had to compress it):

https://github.com/tachiyomiorg/tachiyomi/assets/74346601/108668f4-1d58-4da1-96dd-4693bdcc84e8

### Tachiyomi version

App version: 0.14.6-6053 

### Android version

13 (SDK 33)

### Device

Xiaomi Redmi Note 12S 

### Other details

Was reading 'Dr. Player' from the 'mangakakalot' extension. Did not have it in library or downloaded.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-09-23 13:06
Probably duplicate of #8433

**Closed** 2023-09-23 13:42 UTC
Labels: Bug
