### ISSUE TITLE
[Feature Request] Invert img and option to grayscale color images

### ISSUE THREAD

**Issue by akorshun** [tachiyomiorg/tachiyomi#4692] opened 2021-03-22 20:47 UTC
## Why/User Benefit/User Problem
It will be much more convenient to read manga at night, specially on amoled screenc and saving battery additionally

## What/Requirements
It may be on/two toggles in user color filter options menu
first to invert colors
second to forcibly paint color images in black and white and/or grayscale

**Comment by arkon** [comment] 2021-04-30 13:12
Rejecting inversion since it seems weird. Lowering your brightness would save battery already.

Grayscale is duplicate of #2822.

**Closed by arkon** 2021-04-30 13:12 UTC
Labels: feature
