### ISSUE TITLE
[Bug] <resume button>

### ISSUE THREAD

**Issue by kasakaka** [tachiyomiorg/tachiyomi#4940] opened 2021-04-22 17:25 UTC
---

## Device information
* Tachiyomi version: 0.10.11
* Android version: 10
* Device: samsung a10s

## Steps to reproduce
1. select a manga to read
2. press the resume/play button

### Expected behavior
continue to the last chapter where u left of reading

### Actual behavior
resumes to the latest chapter of the given manga

**Comment by Seishirou101** [comment] 2021-04-22 17:57
Duplicate of #4909

**Closed** 2021-04-22 18:12 UTC
Labels: bug
