### ISSUE TITLE
[Bug] Application Crash

### ISSUE THREAD

**Issue by Boy656** [tachiyomiorg/tachiyomi#5188] opened 2021-05-25 12:30 UTC
## Device information
* Tachiyomi version: App version: 0.10.12-3417 (standard, a462ce36, 61, 2021-05-23T18:33Z)
* Android version: 8.0.0
* Device: ndroid build ID: ATU-L31 8.0.0.164(C185)
Device brand: HUAWEI
Device manufacturer: HUAWEI
Device name: HWATU-QG
Device model: ATU-L31
Device product name: ATU-L31

## Steps to reproduce
1. After installing the application, I downloaded a lot of resources, then I went to the library, pressed the search button, then searched for kimetsu no Yaiba and found the result, I entered
2. After entering one of the results, I found that the number of chapters is 200 chapters, and I and I stopped at chapter 82. I wanted to continue where I left off before I watched. I pressed the download button for several chapters after the download of the first chapter was completed. The application crashed
3. After the application crashed, I returned to the application. I wanted to watch the chapter that I downloaded, but before the chapter opens, the application also crashes. I can no longer download the rest of the chapters because when I press the download button for chapters, the application crashes immediately when you start downloading the manga
4. Finally, the problem is solved when you delete the application data, but when you do these steps again, the application crash problem recurs

### Expected behavior
The download should complete smoothly while I am reading all the chapters while I am watching the downloaded chapter before the others

### Actual behavior
The application crashes after downloading the first manga and continues to crash when watching the manga or downloading the following chapters

## Other details
--------- beginning of system
--------- beginning of main
05-25 14:54:42.709  5142  5341 E NotificationManager: notifyAsUser: tag=null, id=-201, user=UserHandle{0}
05-25 14:54:47.324  5142  5341 E NotificationManager: notifyAsUser: tag=null, id=-201, user=UserHandle{0}
05-25 14:54:50.792  5142  5341 E NotificationManager: notifyAsUser: tag=null, id=-201, user=UserHandle{0}
05-25 14:54:54.205  5142  5341 E NotificationManager: notifyAsUser: tag=null, id=-201, user=UserHandle{0}
05-25 14:55:03.349  5142  5142 E ResourceType: Style contains key with bad entry: 0x0101056c
05-25 14:55:03.355  5142  5142 E ResourceType: Style contains key with bad entry: 0x0101056c
05-25 14:55:15.288  5142  5336 E ACRA    : ACRA caught a IllegalStateException for eu.kanade.tachiyomi.debug
05-25 14:55:15.288  5142  5336 E ACRA    : java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
05-25 14:55:15.288  5142  5336 E ACRA    : 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:57)
05-25 14:55:15.288  5142  5336 E ACRA    : 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
05-25 14:55:15.288  5142  5336 E ACRA    : 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05-25 14:55:15.288  5142  5336 E ACRA    : 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
05-25 14:55:15.288  5142  5336 E ACRA    : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
05-25 14:55:15.288  5142  5336 E ACRA    : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
05-25 14:55:15.288  5142  5336 E ACRA    : 	at java.lang.Thread.run(Thread.java:784)
05-25 14:55:15.288  5142  5336 E ACRA    : Caused by: rx.exceptions.OnErrorNotImplementedException: java.lang.Exception: فشل في تجاوز Cloudflare
05-25 14:55:15.288  5142  5336 E ACRA    : 	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386)
05-25 14:55:15.288  5142  5336 E ACRA    : 	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383)
05-25 14:55:15.288  5142  5336 E ACRA    : 	at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
05-25 14:55:15.288  5142  5336 E ACRA    : 	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:153)
05-25 14:55:15.288  5142  5336 E ACRA    : 	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
05-25 14:55:15.288  5142  5336 E ACRA    : 	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onError(OnSubscribeMap.java:88)
05-25 14:55:15.288  5142  5336 E ACRA    : 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
05-25 14:55:15.288  5142  5336 E ACRA    : 	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1$requestArbiter$1.request(OkHttpExtensions.kt:44)
05-25 14:55:15.288  5142  5336 E ACRA    : 	at rx.Subscriber.setProducer(Subscriber.java:209)
05-25 14:55:15.288  5142  5336 E ACRA    : 	at rx.Subscriber.setProducer(Subscriber.java:205)
05-25 14:55:15.288  5142  5336 E ACRA    : 	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
05-25 14:55:15.288  5142  5336 E ACRA    : 	at rx.Subscriber.setProducer(Subscriber.java:205)
05-25 14:55:15.288  5142  5336 E ACRA    : 	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1.call(OkHttpExtensions.kt:59)
05-25 14:55:15.288  5142  5336 E ACRA    : 	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1.call(OkHttpExtensions.kt:27)
05-25 14:55:15.288  5142  5336 E ACRA    : 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
05-25 14:55:15.288  5142  5336 E ACRA    : 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
05-25 14:55:15.288  5142  5336 E ACRA    : 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
05-25 14:55:15.288  5142  5336 E ACRA    : 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
05-25 14:55:15.288  5142  5336 E ACRA    : 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
05-25 14:55:15.288  5142  5336 E ACRA    : 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
05-25 14:55:15.288  5142  5336 E ACRA    : 	at rx.Observable.subscribe(Observable.java:10423)
05-25 14:55:15.288  5142  5336 E ACRA    : 	at rx.Observable.subscribe(Observable.java:10390)
05-25 14:55:15.288  5142  5336 E ACRA    : 	at rx.Observable.subscribe(Observable.java:10195)
05-25 14:55:15.288  5142  5336 E ACRA    : 	at eu.kanade.tachiyomi.multisrc.madara.Madara.fetchPageList(Madara.kt:616)
05-25 14:55:15.288  5142  5336 E ACRA    : 	at eu.kanade.tachiyomi.data.download.Downloader$downloadChapter$1.call(Downloader.kt:285)
05-25 14:55:15.288  5142  5336 E ACRA    : 	at eu.kanade.tachiyomi.data.download.Downloader$downloadChapter$1.call(Downloader.kt:49)
05-25 14:55:15.288  5142  5336 E ACRA    : 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
05-25 14:55:15.288  5142  5336 E ACRA    : 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
05-25 14:55:15.288  5142  5336 E ACRA    : 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
05-25 14:55:15.288  5142  5336 E ACRA    : 	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
05-25 14:55:15.288  5142  5336 E ACRA    : 	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
05-25 14:55:15.288  5142  5336 E ACRA    : 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
05-25 14:55:15.288  5142  5336 E ACRA    : 	... 6 more
05-25 14:55:15.288  5142  5336 E ACRA    : Caused by: java.io.IOException: java.lang.Exception: فشل في تجاوز Cloudflare
05-25 14:55:15.288  5142  5336 E ACRA    : 	at eu.kanade.tachiyomi.network.CloudflareInterceptor.intercept(CloudflareInterceptor.kt:74)
05-25 14:55:15.288  5142  5336 E ACRA    : 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
05-25 14:55:15.288  5142  5336 E ACRA    : 	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:221)
05-25 14:55:15.288  5142  5336 E ACRA    : 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
05-25 14:55:15.288  5142  5336 E ACRA    : 	at eu.kanade.tachiyomi.network.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:19)
05-25 14:55:15.288  5142  5336 E ACRA    : 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
05-25 14:55:15.288  5142  5336 E ACRA    : 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
05-25 14:55:15.289  5142  5336 E ACRA    : 	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
05-25 14:55:15.289  5142  5336 E ACRA    : 	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1$requestArbiter$1.request(OkHttpExtensions.kt:37)
05-25 14:55:15.289  5142  5336 E ACRA    : 	... 30 more
05-25 14:55:15.289  5142  5336 E ACRA    : Caused by: java.lang.Exception: فشل في تجاوز Cloudflare
05-25 14:55:15.289  5142  5336 E ACRA    : 	at eu.kanade.tachiyomi.network.CloudflareInterceptor.resolveWithWebView(CloudflareInterceptor.kt:164)
05-25 14:55:15.289  5142  5336 E ACRA    : 	at eu.kanade.tachiyomi.network.CloudflareInterceptor.intercept(CloudflareInterceptor.kt:68)
05-25 14:55:15.289  5142  5336 E ACRA    : 	... 38 more
05-25 14:55:20.727  6115  6184 E SQLiteLog: (284) automatic index on C(manga_id)
05-25 14:55:20.727  6115  6184 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
05-25 14:55:20.999  6115  6190 E vndksupport: Could not load vendor/lib64/egl/libGLES_mali.so from sphal namespace: dlopen failed: library "vendor/lib64/egl/libGLES_mali.so" not found.
05-25 14:55:59.145  6115  6115 E ResourceType: Style contains key with bad entry: 0x0101056c
05-25 14:56:11.163  6115  6188 E ACRA    : ACRA caught a IllegalStateException for eu.kanade.tachiyomi.debug
05-25 14:56:11.163  6115  6188 E ACRA    : java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
05-25 14:56:11.163  6115  6188 E ACRA    : 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:57)
05-25 14:56:11.163  6115  6188 E ACRA    : 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
05-25 14:56:11.163  6115  6188 E ACRA    : 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05-25 14:56:11.163  6115  6188 E ACRA    : 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
05-25 14:56:11.163  6115  6188 E ACRA    : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
05-25 14:56:11.163  6115  6188 E ACRA    : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
05-25 14:56:11.163  6115  6188 E ACRA    : 	at java.lang.Thread.run(Thread.java:784)
05-25 14:56:11.163  6115  6188 E ACRA    : Caused by: rx.exceptions.OnErrorNotImplementedException: java.lang.Exception: فشل في تجاوز Cloudflare
05-25 14:56:11.163  6115  6188 E ACRA    : 	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386)
05-25 14:56:11.163  6115  6188 E ACRA    : 	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383)
05-25 14:56:11.163  6115  6188 E ACRA    : 	at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
05-25 14:56:11.163  6115  6188 E ACRA    : 	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:153)
05-25 14:56:11.163  6115  6188 E ACRA    : 	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
05-25 14:56:11.163  6115  6188 E ACRA    : 	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onError(OnSubscribeMap.java:88)
05-25 14:56:11.163  6115  6188 E ACRA    : 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
05-25 14:56:11.163  6115  6188 E ACRA    : 	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1$requestArbiter$1.request(OkHttpExtensions.kt:44)
05-25 14:56:11.163  6115  6188 E ACRA    : 	at rx.Subscriber.setProducer(Subscriber.java:209)
05-25 14:56:11.163  6115  6188 E ACRA    : 	at rx.Subscriber.setProducer(Subscriber.java:205)
05-25 14:56:11.163  6115  6188 E ACRA    : 	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
05-25 14:56:11.163  6115  6188 E ACRA    : 	at rx.Subscriber.setProducer(Subscriber.java:205)
05-25 14:56:11.163  6115  6188 E ACRA    : 	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1.call(OkHttpExtensions.kt:59)
05-25 14:56:11.163  6115  6188 E ACRA    : 	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1.call(OkHttpExtensions.kt:27)
05-25 14:56:11.163  6115  6188 E ACRA    : 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
05-25 14:56:11.163  6115  6188 E ACRA    : 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
05-25 14:56:11.163  6115  6188 E ACRA    : 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
05-25 14:56:11.163  6115  6188 E ACRA    : 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
05-25 14:56:11.163  6115  6188 E ACRA    : 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
05-25 14:56:11.163  6115  6188 E ACRA    : 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
05-25 14:56:11.163  6115  6188 E ACRA    : 	at rx.Observable.subscribe(Observable.java:10423)
05-25 14:56:11.163  6115  6188 E ACRA    : 	at rx.Observable.subscribe(Observable.java:10390)
05-25 14:56:11.163  6115  6188 E ACRA    : 	at rx.Observable.subscribe(Observable.java:10195)
05-25 14:56:11.163  6115  6188 E ACRA    : 	at eu.kanade.tachiyomi.multisrc.madara.Madara.fetchPageList(Madara.kt:616)
05-25 14:56:11.163  6115  6188 E ACRA    : 	at eu.kanade.tachiyomi.data.download.Downloader$downloadChapter$1.call(Downloader.kt:285)
05-25 14:56:11.163  6115  6188 E ACRA    : 	at eu.kanade.tachiyomi.data.download.Downloader$downloadChapter$1.call(Downloader.kt:49)
05-25 14:56:11.163  6115  6188 E ACRA    : 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
05-25 14:56:11.163  6115  6188 E ACRA    : 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
05-25 14:56:11.163  6115  6188 E ACRA    : 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
05-25 14:56:11.163  6115  6188 E ACRA    : 	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
05-25 14:56:11.163  6115  6188 E ACRA    : 	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
05-25 14:56:11.163  6115  6188 E ACRA    : 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
05-25 14:56:11.163  6115  6188 E ACRA    : 	... 6 more
05-25 14:56:11.163  6115  6188 E ACRA    : Caused by: java.io.IOException: java.lang.Exception: فشل في تجاوز Cloudflare
05-25 14:56:11.163  6115  6188 E ACRA    : 	at eu.kanade.tachiyomi.network.CloudflareInterceptor.intercept(CloudflareInterceptor.kt:74)
05-25 14:56:11.163  6115  6188 E ACRA    : 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
05-25 14:56:11.163  6115  6188 E ACRA    : 	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:221)
05-25 14:56:11.163  6115  6188 E ACRA    : 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
05-25 14:56:11.163  6115  6188 E ACRA    : 	at eu.kanade.tachiyomi.network.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:19)
05-25 14:56:11.163  6115  6188 E ACRA    : 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
05-25 14:56:11.163  6115  6188 E ACRA    : 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
05-25 14:56:11.165  6115  6188 E ACRA    : 	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
05-25 14:56:11.165  6115  6188 E ACRA    : 	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1$requestArbiter$1.request(OkHttpExtensions.kt:37)
05-25 14:56:11.165  6115  6188 E ACRA    : 	... 30 more
05-25 14:56:11.165  6115  6188 E ACRA    : Caused by: java.lang.Exception: فشل في تجاوز Cloudflare
05-25 14:56:11.165  6115  6188 E ACRA    : 	at eu.kanade.tachiyomi.network.CloudflareInterceptor.resolveWithWebView(CloudflareInterceptor.kt:164)
05-25 14:56:11.165  6115  6188 E ACRA    : 	at eu.kanade.tachiyomi.network.CloudflareInterceptor.intercept(CloudflareInterceptor.kt:68)
05-25 14:56:11.165  6115  6188 E ACRA    : 	... 38 more
05-25 14:56:14.845  6366  6382 E MemoryLeakMonitorManager: MemoryLeakMonitor.jar is not exist!
05-25 14:56:14.847  6366  6366 E Minikin : Could not get cmap table size!
05-25 14:56:14.903  6366  6366 E ResourceType: Style contains key with bad entry: 0x0101056c
05-25 14:56:16.342  6366  6433 E SQLiteLog: (284) automatic index on C(manga_id)
05-25 14:56:16.342  6366  6433 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
05-25 14:56:16.823  6366  6439 E vndksupport: Could not load vendor/lib64/egl/libGLES_mali.so from sphal namespace: dlopen failed: library "vendor/lib64/egl/libGLES_mali.so" not found.
App version: 0.10.12-3417 (standard, a462ce36, 61, 2021-05-23T18:33Z)
Android version: 8.0.0 (SDK 26)
Android build ID: ATU-L31 8.0.0.164(C185)
Device brand: HUAWEI
Device manufacturer: HUAWEI
Device name: HWATU-QG
Device model: ATU-L31
Device product name: ATU-L31

**Comment by arkon** [comment] 2021-05-26 22:24
Duplicate of #5151.

**Closed by arkon** 2021-05-26 22:24 UTC
Labels: bug
