### ISSUE TITLE
Slow scrolling in: Extensions screen / Title Chapters

### ISSUE THREAD

**Issue by KasukeLp23** [tachiyomiorg/tachiyomi#7526] opened 2022-07-13 13:08 UTC
### Steps to reproduce

1. Scroll on the different screens already mentioned

### Expected behavior

They work normally

### Actual behavior

The scrolling is slow and bugged in direrence to previous versions of Tachiyomi.

### Tachiyomi version

0.13.5-r4631

### Android version

Android 7

### Device

Samsung

### Other details

**EXTENSIONS SCREEN**
**Latest Version:**

https://user-images.githubusercontent.com/70596255/178739390-b4670b38-23fa-42aa-b338-2ad0c4290a6f.mp4 

**Very Previous Version**

https://user-images.githubusercontent.com/70596255/178739417-cf079243-94ef-4c3c-b4aa-48741a86c437.mp4

**CHAPTER SCREEN**
**Latest Version:**

https://user-images.githubusercontent.com/70596255/178740079-3e1eb7aa-2334-4590-bcaf-f5f52edee796.mp4

**Very Previous Version**

https://user-images.githubusercontent.com/70596255/178740215-89b44711-8fdf-4c99-841a-0f3003c4fd6b.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-07-13 13:14
Duplicate of #6951

**Closed by arkon** 2022-07-13 13:14 UTC
Labels: Bug
