### ISSUE TITLE
Add "master" tracker sync.

### ISSUE THREAD

**Issue by Raizanad** [tachiyomiorg/tachiyomi#9364] opened 2023-04-19 02:53 UTC
### Describe your suggested feature

Just an idea as a time saver, I use more than one tracker... When scoring I would like that if I change the score in a "main" tracker row or to define one tracker as a master tracker it will change the rest of the options for the rest of the trackers currently in use.

Since the above point is already requested on March 15th (https://github.com/tachiyomiorg/tachiyomi/issues/9213), I wanted to focus on "mimicking" other data upon clicking a button in a manga. For example Anilist and MAL have the start date and end date box available, sometimes these are not synced together due to many reasons like tokens expiring... I would like that if my master is Anilist and it I fill the options or are properly filled, it would be copied over to the rest of the trackers I have in use.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-04-19 03:07
Duplicate of #8459

**Closed by arkon** 2023-04-19 03:07 UTC
Labels: Feature request
