### ISSUE TITLE
[Bug] Last chapter update not working

### ISSUE THREAD

**Issue by Krytiiq** [tachiyomiorg/tachiyomi#4435] opened 2021-02-10 18:12 UTC
After the Data migration of MangaDex the 4th of Febuary, the update/refresh function for the library is broken. It does check every favorites but does not update them even though they are updated on the website.

**Comment by scb261** [comment] 2021-02-10 18:13
Duplicate of tachiyomiorg/tachiyomi-extensions#5627

**Closed** 2021-02-10 18:18 UTC
Labels: bug
