### ISSUE TITLE
[Feature Request] Add option to sync all currently reading chapters from tracker to tachiyomi as a category

### ISSUE THREAD

**Issue by rsmyst** [tachiyomiorg/tachiyomi#5269] opened 2021-06-02 05:25 UTC
## Why/User Benefit/User Problem
When a first-time user opens the app, they are greeted with an empty library where all their favourite manga are missing. They are forced to manually search up every single manga in their reading list and add it into their library. TBH, when I first opened the app, I felt a little burdened to manually add all my manga AGAIN in the app.

## What/Requirements
So here is my solution. 
1. A welcome screen of some sort can be added on the first time of opening the app
2. In the screen, a page can be allocated for the user to login to their trackers (for eg: mal and anilist)
3. In the next page, an option can be provided which will scrape their logged in tracker for the different categories of manga, for eg: currently reading, planned, dropped, paused etc.
4. Enabling this option would allow tachiyomi to automatically create categories within the library named currently reading, planned etc. and search a few sources of the user's choice for the manga in them. 

Honestly, this would make the app experience a lot better. THere's also potential for a bunch of features that can be built with this as a core feature as well. 
Thank you for your time devs.

**Comment by rsmyst** [comment] 2021-06-02 10:29
Yes, It will definitely require a bit of work but it could be part of version 0.12 instead of a launch in 0.11. 
A big feature as part of another update with enough time to work on it.
I really hope the devs implement this since manually adding manga is a pain

**Comment by Seishirou101** [comment] 2021-06-02 15:19
Duplicate of #2205

**Closed** 2021-06-02 15:19 UTC
Labels: feature

**Comment by rsmyst** [comment] 2021-06-02 16:34
@Seishirou101 Has there been any progress on this feature at all?

**Comment by loocool2** [comment] 2021-06-02 16:38
Not really, there's a feature to mark chapters as read from trackers but that's about it

**Comment by rsmyst** [comment] 2021-06-03 12:13
Guess i'll just hope it gets added at some point for now.
