### ISSUE TITLE
Display Chapter Amount When Migrating

### ISSUE THREAD

**Issue by LemonSquaresYes** [tachiyomiorg/tachiyomi#6644] opened 2022-02-13 21:56 UTC
### Describe your suggested feature

Currently, when you're trying to migrate to another source the new source doesn't display how many chapters it has prior to actually transferring. This is an issue when you're migrating to another source and, unbeknownst to the migrator, the source actually has less chapters. Considering this, I'd like specifically request a chapter count (possibly like how it shows in the library) when trying to migrate. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-02-13 22:05
Duplicate of #2867

**Closed by arkon** 2022-02-13 22:05 UTC
Labels: Feature request
