### ISSUE TITLE
Reader scrolls up when screen orientation changes 

### ISSUE THREAD

**Issue by RedIODev** [tachiyomiorg/tachiyomi#9011] opened 2023-02-01 07:05 UTC
### Steps to reproduce

Scroll in a reader 
Rotate screen
Reader scrolls up to the top

### Expected behavior

The Reader should scroll to relative position based on your position before rotating the screen. 

### Actual behavior

Reader scrolls all the way back to the top regardless of where you were in the chapter before rotating. 

### Tachiyomi version

0.14.3

### Android version

Android 13

### Device

Samsung galaxy s21+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment] 2023-02-01 07:10
Duplicate of #8881 (fixed for the next release)

**Closed** 2023-02-01 08:20 UTC
Labels: Bug
