### ISSUE TITLE
Global Update feature does not work directly, you have to manually update every title by going into the title.

### ISSUE THREAD

**Issue by LordRIPPAR** [tachiyomiorg/tachiyomi#10369] opened 2024-01-08 11:11 UTC
### Steps to reproduce

When i try to update library from update menu or update a category nothing happens, but updating a manga directly works.

### Expected behavior

Update library

### Actual behavior

Nothing happens, but i can update a manga directly

### Crash logs

No response

### Tachiyomi version

0.15.1

### Android version

13

### Device

vivo t2 pro 5g

### Other details

I found a previous entry with the same issue that was faced on the older version "Tachiyomi doesn't update library #9074" from [Elecktronnick](https://github.com/Elecktronnick) opened this issue on Feb 13, 2023. It seems that the issue was solved for that version but a new issue seems to have popped up for this specific version.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Mhax67** [comment] 2024-01-08 13:46
I also have this issue, global update doesn't work. Any help for now?

**Comment by Umerasif8** [comment] 2024-01-08 13:56
I have the same issue.

**Comment by Abdallah-amara021** [comment] 2024-01-08 14:10
I have fix it go to MORE then setting then library smart update make it unselected all thing and that's it
![Screenshot_20240108-153650_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/104996176/65ead412-6f38-40cb-ab77-a6b585c040ae)
![Screenshot_20240108-153655_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/104996176/2591a092-6b79-442e-a3fa-2b4b874183fd)
![Screenshot_20240108-153705_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/104996176/1d8dd1bb-35a7-4360-855c-a2652044388f)
![Screenshot_20240108-153708_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/104996176/0db8d820-4088-4be5-b092-041936e59674)

**Comment by Abdallah-amara021** [comment] 2024-01-08 14:11
> I have the same issue.

See my comment

**Comment by arkon** [comment] 2024-01-08 14:11
Duplicate of #10313

**Closed by arkon** 2024-01-08 14:11 UTC
Labels: Bug

**Comment by LordRIPPAR** [comment] 2024-01-08 14:18
You closed this but what's the solution for this problem? I have over 1000 entries in my library, do I need to manually update all the titles? @arkon

**Comment by arkon** [comment] 2024-01-08 14:21
Refer to https://github.com/tachiyomiorg/tachiyomi/issues/10313#issuecomment-1880075632

**Comment by LordRIPPAR** [comment] 2024-01-08 14:28
@arkon I think the new update in smart update setting "predict next release time" is interfering with the global update. I unselected that option and it seems to work for me. @Umerasif8 @Mhax67

**Comment by LordRIPPAR** [comment] 2024-01-08 14:29
@arkon thank you for the help!

**Comment by arkon** [comment] 2024-01-08 14:30
Please by advised that those settings are designed to help alleviate unnecessary traffic. Turning those off may result in degraded experiences long-term.
