### ISSUE TITLE
Add proxy support

### ISSUE THREAD

**Issue by m3hdi404** [tachiyomiorg/tachiyomi#7463] opened 2022-07-06 05:47 UTC
### Describe your suggested feature

In some countries and networks, the sources are censored and blocked so it would be so good to add proxy support to the app for both downloading and browsing through sources.

### Other details

Also in some countries, VPNs are blocked too because of strong censorship system so it's hard to trying almost tens of VPNs for downloading manga. This feature would be a blessing

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment] 2022-07-06 05:49
Duplicate of #2791

**Closed by loocool2** 2022-07-06 05:49 UTC
Labels: Feature request
