### ISSUE TITLE
Auto scroll

### ISSUE THREAD

**Issue by azuukyun** [tachiyomiorg/tachiyomi#6477] opened 2022-01-16 19:59 UTC
### Describe your suggested feature

I'm new to this github so I would really appreciate it if the devs and mods make a feature for auto scrolling like it can scroll down continuously but the speed can be adjustable like slow fast etc.. 

### Other details

Please do inform me if its in your future plans too.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-01-16 20:04
Duplicate of #2093

**Closed by arkon** 2022-01-16 20:04 UTC
Labels: Feature request
