### ISSUE TITLE
Library Update Frequency

### ISSUE THREAD

**Issue by Dylans2090** [tachiyomiorg/tachiyomi#6272] opened 2021-11-24 06:00 UTC
### Describe your suggested feature

I feel there should be a way to update library by category. Currently, you can only exclude categories. However, might be better if along with that feature, there could be the option to update categories at different rates.

Eg: Categories/Update Frequency
Hiatus/once a week
Finished/never
Reading/Once a day
Want to read/twice a week
Caught up/every 6 hours

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2021-11-24 06:02
Duplicate of #822

**Closed** 2021-11-24 06:02 UTC
Labels: Feature request
