### ISSUE TITLE
[Bug] <Cant read downloaded mangas when source ist dead>

### ISSUE THREAD

**Issue by Rhonos** [tachiyomiorg/tachiyomi#5127] opened 2021-05-21 15:12 UTC
I write this here, because it seems to be a bug (first i thought this is normal, so i opened a feature request > #4904)

My problem is that i cant read the already downloaded mangas/chapters when the source goes "dead". At the moment, I have already downloaded plenty of mangas that I wanted to read in the future (already finished mangas), on my sd-card, but as soon as the source is "dead" > all the chapters are no longer tagged as "downloaded" and cant be read over the app. so its necessary to switch the source and download it all again. 

Before the sources goes dead, all the downloaded chapters where white (the downloaded icon). When the source goes dead > all icons change to "transparent (not downloaded).

The only error i get when i click on the already downloaded chapter (even when the icon/symbol now changed to "transparent") is "source not found".

---

## Device information
* Tachiyomi version: Stable 0.10.12
* Android version: 10
* Device: Galaxy Tab S5e

## Steps to reproduce
1. Download desired mangas
2. dead source (or just uninstall de extention)
3. try to read any of the already downloaded chapters

### Expected behavior
Even when the source is dead, you should be able to read the already downloaded chapters (before the source was "dead).

### Actual behavior
The downloaded chaptes (downloaded before the source was "dead")

## Other details
This happens all the time, not just sometimes or on specific sources

PS: Sorry, my english isn't very well. so if u cant unterstand specific sentences, please just tell me.

**Comment by arkon** [comment] 2021-05-21 16:08
Duplicate of #4904

You can move stuff to local source as a workaround for now.

**Closed by arkon** 2021-05-21 16:08 UTC
Labels: bug
