### ISSUE TITLE
Only Unread Chapters in Updates Tab Option

### ISSUE THREAD

**Issue by Datonn** [tachiyomiorg/tachiyomi#7335] opened 2022-06-19 05:56 UTC
### Describe your suggested feature

As it stands now, there is not an option to only show chapters that are unread in the updates tab. This would be a nice feature to have as it would remove the kind of clutter that remains after a bulk update by one or two manga even after reading through it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-06-19 12:37
Duplicate of #3365

**Closed by arkon** 2022-06-19 12:37 UTC
Labels: Feature request
