### ISSUE TITLE
Tapping to resume in history opens next chapter instead

### ISSUE THREAD

**Issue by jiwxn** [tachiyomiorg/tachiyomi#9081] opened 2023-02-13 13:25 UTC
### Steps to reproduce

1. i go to history to go back reading where i stopped bc its faster
2.  it shows exactly the chapter i stopped.
3. but then when i click... it takes me to 1 chapter ahead from where i was, even when i havent finished the previous chapter 🤡

exemple: i paused reading My Hero Acad. ch.59 and when i went back by the history button it took me to ch. 60, and from ch.60  it goes to ch. 61, 61 to 62...

### Expected behavior

i expected that the history button would take me to the chapter i stopped reading.

### Actual behavior

but it takes me one chapter ahead instead.

### Crash logs

not crashing to me.

### Tachiyomi version

0.14.4

### Android version

9

### Device

Samsung Galaxy S8

### Other details

already said all thats happening in the other boxes.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-02-13 17:24
Are you actually on 0.14.4? This was supposed to be fixed in it.

**Comment by jiwxn** [comment] 2023-02-13 17:39
> 

yes, i updated yesterday and thats when it started

**Comment by jiwxn** [comment] 2023-02-13 17:41
![Screenshot_20230213-144018_Tachiyomi](https://user-images.githubusercontent.com/118154420/218532234-a519a026-9837-4780-a984-19f443271def.jpg)

**Comment by arkon** [comment] 2023-02-13 18:16
Please share a video recording, including showing the chapter statuses.

**Comment by arkon** [comment] 2023-02-19 16:13
No additional info provided and can't reproduce.

**Closed by arkon** 2023-02-19 16:13 UTC
Labels: Bug, Needs more info
