### ISSUE TITLE
Manga Info Buggy

### ISSUE THREAD

**Issue by FourTOne5** [tachiyomiorg/tachiyomi#6140] opened 2021-10-20 19:29 UTC
### Steps to reproduce

Case 1:
    1. Open any non-libary manga for first time (clear database for more accurate result)

Case 2:
    1. Do 1 of Case 1 and open any chapter and wait until page count appears ant then go back..

### Expected behavior

Not be buggy.

### Actual behavior

Case 1:
When description is in open state Chevron is under tags (Fig 1) and in closed state tags disappear (Fig 2)

Case 2:
Tags doesn't appear in boath state.

Also in both case description doesn't expand.

Fig 1:
![Screenshot_20211017-184810](https://user-images.githubusercontent.com/59261191/138158162-04b7d5f8-db49-42b8-a613-9921e5a7f355.png)
Fig 2:
![Screenshot_20211017-184704](https://user-images.githubusercontent.com/59261191/138158901-15513af5-1509-4510-9fa8-26280641f608.png)

### Tachiyomi version

0.12.3-3903

### Android version

Android 6

### Device

LAVA iris820

### Other details

Probably a issue with low end or older devices.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by specterflare** [comment] 2021-11-11 22:11
@arkon I hate to ping, but this is a non-trivial issue and it's been several weeks without a response. Are you able to reproduce this?

**Comment by arkon** [comment] 2021-11-11 22:24
I'm not looking at this, but someone else could take it if they want.

**Comment by kiriya-aoi** [comment] 2022-01-01 02:32
> Ever since the "manga description adjustment" commit, descriptions are cut, not all but a lot of mangas that I'm reading I can't read the whole description. Here's an example. ![Screenshot_20211029-205338](https://user-images.githubusercontent.com/46979593/139439661-20e22137-ab86-4d77-a0a0-7b5c7ec90921.png) ![Screenshot_20211029-210411](https://user-images.githubusercontent.com/46979593/139439675-68681cb4-7cda-45c8-9be4-0ef5dbc0a373.png) ,

This truncation is present virtually everywhere in tablet mode, but doesn't appear anywhere I've seen in phone mode. It even appears when rotating (with tablet mode=landscape setting), with a full description prior to rotation then a truncated description in landscape, then back to full description in phone mode.

**Comment by specterflare** [comment] 2022-01-09 02:44
Could we please get a follow-up on this? I know a lot of thought was put into designing a tablet-friendly layout, but these truncated description stick out like a sore thumb and are kind of a pain, since I have to use WebView to actually see if I want to read a manga.

**Comment by arkon** [comment] 2022-01-09 03:55
Referenced PR: #6011

**Comment by arkon** [comment] 2022-01-30 15:49
The tablet issue (which wasn't even related to the original issue) was fixed in #6518.

I don't think @ivaniskandar was ever able to reproduce the original issue, so I'll close this since the issue's gotten a bit confusing to track. If it's still happening in newer previews, open another issue.

**Closed by arkon** 2022-01-30 15:49 UTC
Labels: Bug
