### ISSUE TITLE
Option to select only wanted text inside  description 

### ISSUE THREAD

**Issue by heartlog** [tachiyomiorg/tachiyomi#6892] opened 2022-04-10 02:30 UTC
### Describe your suggested feature

![Screenshot_20220410-075304_NewPipe](https://user-images.githubusercontent.com/76758776/162598575-4b1afdfd-722d-49ba-8cd3-7a98b96db855.jpg)
It's hard to copy the name and info of description.
It'll be easy to copy other name and original name which is in description.
Just like the newpipe app has...👆(see ref pic)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-04-10 02:31
Duplicate of #6548

**Closed by arkon** 2022-04-10 02:31 UTC
Labels: Feature request
