### ISSUE TITLE
Category deletion, series not deleted or in default.

### ISSUE THREAD

**Issue by HaarisAhmed2001** [tachiyomiorg/tachiyomi#8923] opened 2023-01-15 06:32 UTC
### Steps to reproduce

1. Create a random category.
2. Pick an extension you want to add a series from.
3. Pick a series and set it to the new category.
4. Delete the category itself.
5. Check default.
6. Check extension page.
7. Check the migrations tab to see if the series still appears on you extension series list.

### Expected behavior

When a category gets deleted the series that haven't been moved for the category, and instead are still within it, should either get deleted or sent back to default.

### Actual behavior

The series dissappear from your library but the extensions page and it's section in the migrate section still shows the series being within your library.
![Screenshot_20230115-005822_Tachiyomi](https://user-images.githubusercontent.com/60004984/212525959-1bcd3c25-b092-4bc6-88ee-e7ead3ca549e.jpg)
![Screenshot_20230115-005846_Tachiyomi](https://user-images.githubusercontent.com/60004984/212525970-0b878e35-6a81-4e63-94db-4ead2ea64087.jpg)
![Screenshot_20230115-005936_Tachiyomi](https://user-images.githubusercontent.com/60004984/212525981-463e71d1-9e93-4749-af42-f96c0eebab0f.jpg)
![Screenshot_20230115-010001_Tachiyomi](https://user-images.githubusercontent.com/60004984/212525992-b3c3f877-0789-4042-89c4-150f47ece2ba.jpg)
![Screenshot_20230115-010038_Tachiyomi](https://user-images.githubusercontent.com/60004984/212526026-5e04b81f-9acb-4044-99cd-b2c26c2eb1ee.jpg)
![Screenshot_20230115-010636_Tachiyomi](https://user-images.githubusercontent.com/60004984/212526032-1f97da0a-773d-41d7-b14a-5a8f1a1a52df.jpg)
![Screenshot_20230115-010707_Tachiyomi](https://user-images.githubusercontent.com/60004984/212526035-1821dbd8-1fbb-45ca-8031-797a99dab84e.jpg)

### Tachiyomi version

0.14.3

### Android version

Android 11

### Device

Samsung Galaxy A7/A70

### Other details

I would like for the option to either choose whether or not the series within a category gets deleted alongside the category as well. If I choose that the series gets deleted then they should be completely removed from the library and not show up in the migrations list and having it appear to be in the library, as well as be marked on the extensions' series pages. If I decide to keep the series, it should be relocated as the first thing in the default section (Depending on the filter of course). It should also work for huge bulk deletions, for say a category that has around 500 -20000+ series on it if possible. Otherwise it should just delete as much as it can.

Also as an extra tidbit, I hope the fix also sets back the missing series to default, I still have a series that is indeed lost because of this bug.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment] 2023-01-15 06:47
Duplicate of #8922

**Closed by AntsyLich** 2023-01-15 06:47 UTC
Labels: Bug
