### ISSUE TITLE
[Bug] extensions downloading but not installing 

### ISSUE THREAD

**Issue by oge2k** [tachiyomiorg/tachiyomi#3941] opened 2020-10-14 16:48 UTC
App version:
0.10.5 and former versions up to version 0.9.2
Android version:
7.0
Phone:
Vernee thor E
Issue/Request:
Can download extensions but there is an error while installing

Try to download extension
Extension Downloads
Android opens installer and gives error message about error while parsing package

Other details:
On version 0.8.5 the installation of extensions through tachiyomi worked fine but every update after that, has not worked.

Also does not work when updating extensions
I do not use VPN .

Downloading and installing extensions directly from tachiyomi site works fine(got link from discord) .

**Comment by yegorgunko** [comment] 2020-10-14 17:11
Can't reproduce on the latest dev build:

App version: 0.10.5-2774 (standard, b88e444c, 51)
Android version: 10 (SDK 29)
Android build ID: HD1913_14_200928
Device brand: OnePlus
Device manufacturer: OnePlus
Device name: OnePlus7TPro
Device model: HD1913
Device product name: OnePlus7TPro_EEA

**Comment by arkon** [comment] 2020-10-18 14:22
This tends to be an issue on obscure devices/ROMs. There was a change that made it work better for some other devices, but seemed to have had issues with others.

As a workaround, you'll just need to keep doing it from the website.

**Comment by Lightsockie** [comment] 2020-10-25 02:30
Having same issue. Was working before I updated to Android 11. Installing the extension directly from the repo did work, though.

```
App version: 0.10.5 (standard, 2769e27a2, 51)
Android version: 11 (SDK 30)
Android build ID: IN2015_15_201003
Device brand: OnePlus
Device manufacturer: OnePlus
Device name: OnePlus8
Device model: IN2015
Device product name: OnePlus8
```

**Comment by gil** [comment] 2020-11-04 12:44
I have the same issue after updating from my old OnePlus 6T (Android 10) to OnePlus 8T (Android 11). Extensions usually won't even download. After I click "Install", they are stuck on "Pending" for a long time before failing. Manual install/update works.

I tried deleting all cache, storage, clean install from the official website, checked all permissions. Nothing worked :/
Also noticed that F-Droid says there's no supported version, so I had to download the APK myself.

**Comment by gil** [comment] 2020-11-04 13:18
Update: I found the solution on Reddit, it seems that Blokada started blocking this. Not sure if only on Android 11 or it's just bad timing for me. Disabling it while installing extensions or adding Tachiyomi as an app exception worked.

**Comment by Lightsockie** [comment] 2020-11-06 18:47
I ain't postin' in no reddit thread. Also, I don't have Blokada installed (or any other ad blocker, as this seems to be). Fairly vanilla setup for me.

**Comment by gil** [comment] 2020-11-06 18:55
Sorry, @Lightsockie I wasn't talking about you. Just said that I saw 2 people discussing on Reddit about this and thought it would be a good idea to write that down somewhere if it's a common problem. For me it seems to be the case, I had Blokada before on Android 10 and it worked, but on Android 11 it blocks Tachiyomi for some reason.

**Comment by arkon** [comment] 2021-04-17 15:24
Closing in favour of #4106

**Closed by arkon** 2021-04-17 15:24 UTC
Labels: bug
