### ISSUE TITLE
Fail to convert downloaded to Cbz

### ISSUE THREAD

**Issue by XarisY** [tachiyomiorg/tachiyomi#10288] opened 2024-01-04 02:58 UTC
### Steps to reproduce

1. Dowload chapters
2. Dowload bar completed
3. Download bars stucked at full with download chapters displayed [!]...Disable cbz conversion will solve this issue however image will shown in gallery app.

### Expected behavior

Should seemlessly converted to cbz.

### Actual behavior

Seem to stucked at conversion to cbz.

### Tachiyomi version

0.14.7

### Android version

Android 14

### Device

Tab S9 ultra

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2024-01-07 14:32
Duplicate of #10314 (share your crash/error logs there too if it's still happening).

**Closed by arkon** 2024-01-07 14:32 UTC
Labels: Bug
