### ISSUE TITLE
Allow Us To Increase/Decrease Swipe Sensitivity For Changing Catagories

### ISSUE THREAD

**Issue by Fmoment1** [tachiyomiorg/tachiyomi#8335] opened 2022-10-29 15:17 UTC
### Describe your suggested feature

The swipe sensitivity after update v0.14.0 seems to have been decreased. I'm finding myself having to swipe a slightly longer distance for shifting between categories, often swiping twice because the first swipe wasn't successful.

Since swiping was quick and easy in v0.13.6, this change can be very jarring for those who are used to one-handed usage (we do have a lot of big phone screens these days, haha). 

I humbly request that we get an option to change the swipe sensitivity for changing catalogues, so that we can revert to the previous swiping speed, or set a speed that we are comfortable with. Thank you.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-10-29 15:24
Duplicate of #8310

**Closed by arkon** 2022-10-29 15:24 UTC
Labels: Feature request
