### ISSUE TITLE
能不能选择项有设置调整触发阅读菜单

### ISSUE THREAD

**Issue by lintonxue00** [tachiyomiorg/tachiyomi#9525] opened 2023-05-21 02:19 UTC
### Describe your suggested feature

就是阅读漫画点击一下就会触发阅读菜单来调整设置，但我不希望有这个功能，因为太容易触发了，能选择关闭阅读菜单选项或者连续点击3下触发等设置触发阅读菜单吗？降低误点触发阅读菜单。

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2023-05-21 06:07
Duplicate of #6948

**Closed by stevenyomi** 2023-05-21 06:07 UTC
Labels: Feature request
