### ISSUE TITLE
[Feature Request] Set library update frequency time

### ISSUE THREAD

**Issue by dhimanAdhikari** [tachiyomiorg/tachiyomi#4502] opened 2021-02-17 13:39 UTC
## Why/User Benefit/User Problem
Currently manga update frequency can be set as hourly, 2hrs, 6hrs, 12hrs, etc. 
Say a set 12hr update cycle normally happens at morning 11AM/11PM. If for whatever reason it fails (due to connection issues or whatever) and checks for updates a few hours later at say 3PM/3AM then the new 3AM/3PM cycle becomes the new updating time. I personally read manga while having lunch in the afternoon and before sleeping so the 11AM/11PM cycle is perfect for me but when update time changes I have check for updates manually.

## What/Requirements
Give us a time option along with pre-existing library update frequency settings. If I set it to 12hr frequency and 10AM time, it will check updates at 10AM/10PM etc.

**Comment by scb261** [comment] 2021-02-17 13:45
Duplicate of #3589

**Closed** 2021-02-17 13:46 UTC
Labels: feature
