### ISSUE TITLE
Tachiyomi FC when Updating Library

### ISSUE THREAD

**Issue by nurananto** [tachiyomiorg/tachiyomi#9051] opened 2023-02-08 13:58 UTC
### Steps to reproduce

Update some library

### Expected behavior

Updating until end

### Actual behavior

forced close / restart at some point

### Crash logs

https://pastebin.com/QHEW6rW3

### Tachiyomi version

0.14.4-5501

### Android version

13

### Device

Poco X3 Pro

### Other details

Crash Video

https://photos.app.goo.gl/29v5x9zNhYXwEDi47

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-02-09 02:47
Duplicate of #8400

**Closed by arkon** 2023-02-09 02:47 UTC
Labels: Bug
