### ISSUE TITLE
A setting to automatically add local content to library

### ISSUE THREAD

**Issue by Pheonix412** [tachiyomiorg/tachiyomi#9593] opened 2023-06-07 09:38 UTC
### Describe your suggested feature

It should be a setting that allows all content in the local folder to be automatically added to the users library, or a way to batch add from the local folder. If you have hundreds of files it can be quite annoying to add them all by waiting several minutes for the browse local source to load, just to spend a ages to tap and hold on all the the content.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-06-12 02:13
Duplicate of #4471

**Closed by arkon** 2023-06-12 02:13 UTC
Labels: Feature request
