### ISSUE TITLE
Different Default Reading Mode for different Extensions.

### ISSUE THREAD

**Issue by mohitelement** [tachiyomiorg/tachiyomi#7019] opened 2022-04-26 16:33 UTC
### Describe your suggested feature

It would make the experience even smoother if we don't need to change the reading mode. Usually, one Extention has comics of one reading style so it makes sense to have different default reading modes for different extensions.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by megnanamoose** [comment] 2022-09-16 15:55
Similarly, it would be helpful if a different default reading mode could be set for individual categories. Currently, I have separate categories for manga and manhwa, and my default reading mode is set to right to left. So each time I start a new manhwa series, I have to change the series reading mode to webtoon. If the default reading mode for series placed in the manhwa category could be webtoon, while also having right to left for series in the manga category that would be great.

**Comment by SamB** [comment] 2022-10-26 16:14
I was thinking it might make wense if extensions could suggest a better default mode; for example, mangadex seems to have webtoons tagged as such.

(Right-to-left vs left-to-right is unfortunately trickier, as this can even vary between chapters, especially if ex-license translations are involved.)

**Comment by TheVP** [comment] 2023-01-19 03:39
Just writing this post to echo what everyone has recommended. I use a separate source as well as category for Manhwas and Manhuas vs regular manga, and thus either extension specific reading defaults or category specific would be nice.

**Comment by xlogisticsx** [comment] 2023-01-26 18:43
I would also like to request per category reading modes. I read all of my manhwa and manhua in webtoons mode, but all of my manga in locked landscape with it zoomed out a tad. This is because I find most manga to have much smaller text in comparison in many cases due to fitting many blocks in the same reading area. This does make it so I have to frequently scroll up and down for larger reading areas, but I find that better than having to zoom in then out, either by tapping or pinching, or having to get closer to my screen, but I digress. 

As for per extension reading modes, I can easily see that being just as helpful.

**Comment by stevenyomi** [comment] 2023-01-26 20:01
> I would also like to request per category reading modes.

That was already requested in #6337.

**Comment by arkon** [comment] 2023-03-06 00:17
Duplicate of #3318

**Closed by arkon** 2023-03-06 00:17 UTC
Labels: Feature request
