### ISSUE TITLE
Status change/overwrite for mangas in library only

### ISSUE THREAD

**Issue by kingmj2000** [tachiyomiorg/tachiyomi#8945] opened 2023-01-18 19:27 UTC
### Describe your suggested feature

We should be able to overwrite the status (Ongoing, Completed, Hiatus, Dropped, etc. ) of the manga/manhwa that we have saved in our library locally regardless of the status provided by the extension source. Ot would be useful for filtering offline.

We should also be able to save this status change of respective manga when creating/restoring backups.

This feature is already there in Tachiyomi SY, I think you can implement it here in similar way 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-01-18 19:38
Duplicate of #4398

**Closed** 2023-01-18 19:38 UTC
Labels: Feature request
