### ISSUE TITLE
Strictly device orientated manga-info note taking

### ISSUE THREAD

**Issue by Skuldye** [tachiyomiorg/tachiyomi#5881] opened 2021-09-09 18:23 UTC
### Describe your suggested feature

First off I've checked the previous requests for this options and I've seen number #2155, however my request is slightly different. Which I thought would be better to explain in a new request.

**Explanation of the function:**
So the function of the feature is pretty simple. You have a button on the manga-info screen, that when pressed shows you your editable notes linked to that series. The maximum length of the notes can be the standard 255 character limit. 

The part that deviates from the other requests is that I don't need this to be saved into a backup, have any synchronization or cloudsaving. It just needs to make a .txt file on your device, somewhere in your Tachiyomi folders, that the serie's "note button" in the manga-info screen links to and opens up in a pop-up screen within the app.

I've added 2 recommendations for the placement of the button in details section as an image (I've marked them with a red square).

**Reasons for the function:**
The reason for my need for this options is that I sometimes use multiple sources for a single series which without explanation get confusing. This is because there are sometimes parts "missing" in one, that the other another source does have. Using a third-party application wouldn't tell me which one is which one.

Another reason is that when I use Tachiyomi as my main reader/platform to read on for awhile, I sometimes need to go to a site that isn't supported (yet) to read the latest chapters. This will make it so that the reading progress isn't complete anymore. This will confuse me later when I go back to this series.

I understand that the last problem can be solved by using a third-party application, however this adds a gigantic amount of time; and above all this means I will need to cross-reference and check a third-party application every time I go back to a series, in the off chance that I've already read ahead for that series.

### Other details

![1631210420464](https://user-images.githubusercontent.com/90412180/132741644-633110f9-6cd8-4a99-a1ab-f9678c085f4b.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2021-09-09 19:52
Subset of #2155, so closing as duplicate of that.

**Closed by arkon** 2021-09-09 19:52 UTC
Labels: Feature request

**Comment by Skuldye** [comment] 2021-09-10 02:22
...I literally talked about why it's not a duplicate.

**Comment by arkon** [comment] 2021-09-10 02:25
It's a lot of writing to describe what is just a subset of #2155. I'm not sure why it justified another issue.

**Comment by Skuldye** [comment] 2021-09-10 02:36
It's different mostly in the way that it would need to be set up. The other request could only be implemented if the way the database structure is set up is changed. However for this "bare bone" version that should not be needed.
