### ISSUE TITLE
adding a 'delete from list' button to tracking

### ISSUE THREAD

**Issue by sahil-code** [tachiyomiorg/tachiyomi#6946] opened 2022-04-16 19:08 UTC
### Describe your suggested feature

currently, on clicking on a manga on the tracking list, say for Anilist, it automatically adds it to your manga list in Anilist with the "planned" tag. often, i add the tracking on a manga i find, and then decide i don't want to read it.

there is a button to remove the tracking, but the manga still stays in your Anilist list, so i have to open Anilist to remove it manually.

i would appreciate a button to remove it from my Anilist directly from the Tachiyomi tracking menu.

Thanks, and i understand if it's not possible considering the APIs of the different trackers. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-04-16 19:46
Duplicate of #6260

**Closed by arkon** 2022-04-16 19:46 UTC
Labels: Feature request
