### ISSUE TITLE
Filter to hide mangas from 18+ sources

### ISSUE THREAD

**Issue by Aahnafwifi212** [tachiyomiorg/tachiyomi#7139] opened 2022-05-15 13:31 UTC
### Describe your suggested feature

![Screenshot_20220515192509](https://user-images.githubusercontent.com/95229081/168475409-23997bd6-9812-447a-a72c-b576c55e68aa.jpg)
another filter to hide mangas which are from 18+ sources

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2022-05-17 06:27
Duplicate of #1508 more or less.

**Closed by Seishirou101** 2022-05-17 06:27 UTC
Labels: Feature request
