### ISSUE TITLE
Different settings for outer and unfolded displays for foldable phones.

### ISSUE THREAD

**Issue by mrskizzex** [tachiyomiorg/tachiyomi#7965] opened 2022-09-07 20:41 UTC
### Describe your suggested feature

Outer display on Galaxy Fold 4 is pretty narrow so I use 0% margins when reading but when i want to unfold the display and read it, 0% margins for webtoons make them very hard to read as panels are bigger than display allows making it hard to read.

I would like there to be 2 sets of settings at least for margins for outer and inner display for foldable phones.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-09-07 20:58
Duplicate of #7904

**Closed by arkon** 2022-09-07 20:58 UTC
Labels: Feature request
