### ISSUE TITLE
[Feature Request] <Auto single page>

### ISSUE THREAD

**Issue by Deonchest** [tachiyomiorg/tachiyomi#3820] opened 2020-09-18 04:40 UTC
## Why/User Benefit/User Problem
There are often manga that's double paged, especially for Chinese sources or old manga that are released in volumes. 
It is hard to view them on phone. If viewed horizontally it's too small, if we fit height we can't see the whole page in a glance. It spoils the reading experience. 

## What/Requirements
Therefore I propose an auto single page function that auto separates an image exceeding x width into 2 images, the page order depends on the reading direction. 
When reading from right to left, the image on the right of the source image will be the 1st page, followed by the image on the left of the source image. 
It should be able to detect the white space in the middle of the source image and only do the cropping if there's any white space, to prevent splitting 2 pages that's meant to be viewed as a whole, for example, big action scenes in Japanese shonen manga.

**Comment by Tanyangfan** [comment] 2021-02-02 08:19
Need seme feature.

**Comment by curche** [comment] 2021-02-02 15:14
Can be addressed by and Duplicate of #1384

**Closed** 2021-02-02 15:37 UTC
Labels: feature
