### ISSUE TITLE
Add notes section just like library to each manga ..

### ISSUE THREAD

**Issue by royal78** [tachiyomiorg/tachiyomi#5714] opened 2021-08-14 08:47 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

I like Tachiyomi a lot . But sometimes it it feels like some features is needed to be added.
`Tachiyomi` is best manga reader app I used in my life..

> it's the feature I like to be added by dev to the Tachiyomi.
You know lots of people like to bookmark their favourite chapter in manga. Just like that I like to be a feature like 'Notes from user' just like we use tracking it'll be great if there is feature like NOTES or natepad for manga.

You know lots of manga scans and source not provide the manga information or provide less info .
So, it's pain to see all manga and search for the chapter you are willing to read. 

At that time the notes can be a big help . Then you can write something about that and that'll be saved in manga then you can refer that note anytime....

### Other details

Add the notes section to each of manga just like manga tracking...🥰

**Comment by loocool2** [comment] 2021-08-14 08:51
Duplicate of #2155

**Closed by loocool2** 2021-08-14 08:51 UTC
Labels: Feature request
