### ISSUE TITLE
cache renew() function causes Tachiyomi to freeze (probably)

### ISSUE THREAD

**Issue by Shamicen** [tachiyomiorg/tachiyomi#7847] opened 2022-08-23 11:29 UTC
### Steps to reproduce

1. Have a lot of Downloaded Manga
2. Read Manga until the `renewInterval` of  `DownloadCache.kt's` `checkRenew()` function is up (1 hour) 
3. Reach 5 pages before a Chapter transition in any chapter downloaded or online
4. Tachiyomi freezes and becomes totally unresponsive. Can't scroll up or down, open the menu or leave the reader

To read Manga again one must close Tachiyomi and wait until chapters show up again for any of the library Manga (they will be blank until `renew()` finishes). You can also wait it out on the frozen page, just choose wait in the Tachiyomi is not responding dialogue.

If you try reading a Manga from History before `renew()` finishes it will open up fine but get stuck 5 pages before the chapter transition again (step 4) .

Once `renew()` finishes and chapter show up again reading Manga works like expected again.  

### Expected behavior

Maybe start renew() in the background and keep using the old chapter cache until renew() finishes?
Or maybe do something in `isChapterDownloaded()` in either `DownloadMangaer.kt` or `chapterCache.kt` to check if the chapter cache is currently being renewed and just always use online sources until it finishes.

 

### Actual behavior

So why probably? I am pretty sure that the problem is being caused by `renew()` since it happens about every hour like clockwork and I traced the function chain from the `PagerViewer.kt` preload function all the way to the `DownloadCache.kt's` `checkRenew()` function. The preload function triggers at 5 pages before the chapter transition so that fits too and the problem is fixed as soon as chapters appear in the library again (presumably when `renew()` finishes). 

But I didn't really test it by for example setting `renewInterval` to 24 hours and checking if that actually fixes it. If someone with the same Issue wants to test it feel free. I could probably test it later this week if no one else can confirm the issue and a test to confirm if `renew()` is the culprit where to be be absolutely necessary.  

Lastly I am sorry for not using the fields of the Template correctly. If wanted I'll reopen the issue with correct Template usage but I thought this way made more sense.

### Tachiyomi version

0.13.6

### Android version

Android 11

### Device

Samsung Galaxy Tab S5e

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by DchanN** [comment] 2022-08-23 14:00
Duplicate of #7240 , you can try comment your issue there, because dev need more info for freeze issue

**Closed** 2022-10-21 19:00 UTC
Labels: Bug
