### ISSUE TITLE
Random crash while reading manga.

### ISSUE THREAD

**Issue by THElegend5** [tachiyomiorg/tachiyomi#6523] opened 2022-01-30 20:51 UTC
### Steps to reproduce

Reading a random manga.

### Expected behavior

Everythings fine.

### Actual behavior

App crashed.

### Crash logs
```
--------- beginning of system
--------- beginning of crash
01-30 11:22:07.246 18039 18039 E AndroidRuntime: FATAL EXCEPTION: main
01-30 11:22:07.246 18039 18039 E AndroidRuntime: Process: eu.kanade.tachiyomi.debug, PID: 18039
01-30 11:22:07.246 18039 18039 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.restoreHierarchyState(android.util.SparseArray)' on a null object reference
01-30 11:22:07.246 18039 18039 E AndroidRuntime: 	at com.bluelinelabs.conductor.Controller.restoreViewState(Controller.java:2)
01-30 11:22:07.246 18039 18039 E AndroidRuntime: 	at com.bluelinelabs.conductor.Controller.inflate(Controller.java:13)
01-30 11:22:07.246 18039 18039 E AndroidRuntime: 	at com.bluelinelabs.conductor.ControllerChangeHandler.executeChange(ControllerChangeHandler.java:17)
01-30 11:22:07.246 18039 18039 E AndroidRuntime: 	at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:22)
01-30 11:22:07.246 18039 18039 E AndroidRuntime: 	at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:29)
01-30 11:22:07.246 18039 18039 E AndroidRuntime: 	at com.bluelinelabs.conductor.Router.popController(Router.java:5)
01-30 11:22:07.246 18039 18039 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourceController$onCreateOptionsMenu$2.invoke(BrowseSourceController.kt:5)
01-30 11:22:07.246 18039 18039 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourceController$onCreateOptionsMenu$2.invoke(BrowseSourceController.kt:1)
01-30 11:22:07.246 18039 18039 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.base.controller.BaseController$fixExpand$1.onMenuItemActionCollapse(BaseController.kt:2)
01-30 11:22:07.246 18039 18039 E AndroidRuntime: 	at androidx.appcompat.view.menu.MenuItemImpl.collapseActionView(MenuItemImpl.java:4)
01-30 11:22:07.246 18039 18039 E AndroidRuntime: 	at androidx.appcompat.widget.ToolbarWidgetWrapper.collapseActionView(ToolbarWidgetWrapper.java:4)
01-30 11:22:07.246 18039 18039 E AndroidRuntime: 	at androidx.appcompat.app.ToolbarActionBar.collapseActionView(ToolbarActionBar.java:2)
01-30 11:22:07.246 18039 18039 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatDelegateImpl.dispatchKeyEvent(AppCompatDelegateImpl.java:44)
01-30 11:22:07.246 18039 18039 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:1)
01-30 11:22:07.246 18039 18039 E AndroidRuntime: 	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:410)
01-30 11:22:07.246 18039 18039 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:6091)
01-30 11:22:07.246 18039 18039 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5959)
01-30 11:22:07.246 18039 18039 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5452)
01-30 11:22:07.246 18039 18039 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5509)
01-30 11:22:07.246 18039 18039 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5475)
01-30 11:22:07.246 18039 18039 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5627)
01-30 11:22:07.246 18039 18039 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5483)
01-30 11:22:07.246 18039 18039 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5684)
01-30 11:22:07.246 18039 18039 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5456)
01-30 11:22:07.246 18039 18039 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5509)
01-30 11:22:07.246 18039 18039 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5475)
01-30 11:22:07.246 18039 18039 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5483)
01-30 11:22:07.246 18039 18039 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5456)
01-30 11:22:07.246 18039 18039 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5509)
01-30 11:22:07.246 18039 18039 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5475)
01-30 11:22:07.246 18039 18039 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5660)
01-30 11:22:07.246 18039 18039 E AndroidRuntime: 	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:5820)
01-30 11:22:07.246 18039 18039 E AndroidRuntime: 	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3210)
01-30 11:22:07.246 18039 18039 E AndroidRuntime: 	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2752)
01-30 11:22:07.246 18039 18039 E AndroidRuntime: 	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2743)
01-30 11:22:07.246 18039 18039 E AndroidRuntime: 	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3187)
01-30 11:22:07.246 18039 18039 E AndroidRuntime: 	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:143)
01-30 11:22:07.246 18039 18039 E AndroidRuntime: 	at android.os.MessageQueue.nativePollOnce(Native Method)
01-30 11:22:07.246 18039 18039 E AndroidRuntime: 	at android.os.MessageQueue.next(MessageQueue.java:335)
01-30 11:22:07.246 18039 18039 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
01-30 11:22:07.246 18039 18039 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7861)
01-30 11:22:07.246 18039 18039 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-30 11:22:07.246 18039 18039 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
01-30 11:22:07.246 18039 18039 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
--------- beginning of main
01-31 02:13:57.234 17633 17633 E AndroidRuntime: FATAL EXCEPTION: main
01-31 02:13:57.234 17633 17633 E AndroidRuntime: Process: eu.kanade.tachiyomi.debug, PID: 17633
01-31 02:13:57.234 17633 17633 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Index: 22, Size: 21
01-31 02:13:57.234 17633 17633 E AndroidRuntime: 	at java.util.ArrayList.add(ArrayList.java:483)
01-31 02:13:57.234 17633 17633 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.pager.PagerViewerAdapter.setChapters(PagerViewerAdapter.kt:16)
01-31 02:13:57.234 17633 17633 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.pager.PagerViewer.setChaptersInternal(PagerViewer.kt:8)
01-31 02:13:57.234 17633 17633 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.pager.PagerViewer.access$setIdle(PagerViewer.kt:3)
01-31 02:13:57.234 17633 17633 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.pager.PagerViewer$1.onPageScrollStateChanged(PagerViewer.kt:1)
01-31 02:13:57.234 17633 17633 E AndroidRuntime: 	at androidx.viewpager.widget.DirectionalViewPager.setScrollState(DirectionalViewPager.java:12)
01-31 02:13:57.234 17633 17633 E AndroidRuntime: 	at androidx.viewpager.widget.DirectionalViewPager$3.run(DirectionalViewPager.java:1)
01-31 02:13:57.234 17633 17633 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1058)
01-31 02:13:57.234 17633 17633 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:880)
01-31 02:13:57.234 17633 17633 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:809)
01-31 02:13:57.234 17633 17633 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1043)
01-31 02:13:57.234 17633 17633 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
01-31 02:13:57.234 17633 17633 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-31 02:13:57.234 17633 17633 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:236)
01-31 02:13:57.234 17633 17633 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7861)
01-31 02:13:57.234 17633 17633 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-31 02:13:57.234 17633 17633 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
01-31 02:13:57.234 17633 17633 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
01-31 02:13:57.259 17633 17633 E ACRA    : ACRA caught a IndexOutOfBoundsException for eu.kanade.tachiyomi.debug
01-31 02:13:57.259 17633 17633 E ACRA    : java.lang.IndexOutOfBoundsException: Index: 22, Size: 21
01-31 02:13:57.259 17633 17633 E ACRA    : 	at java.util.ArrayList.add(ArrayList.java:483)
01-31 02:13:57.259 17633 17633 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.viewer.pager.PagerViewerAdapter.setChapters(PagerViewerAdapter.kt:16)
01-31 02:13:57.259 17633 17633 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.viewer.pager.PagerViewer.setChaptersInternal(PagerViewer.kt:8)
01-31 02:13:57.259 17633 17633 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.viewer.pager.PagerViewer.access$setIdle(PagerViewer.kt:3)
01-31 02:13:57.259 17633 17633 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.viewer.pager.PagerViewer$1.onPageScrollStateChanged(PagerViewer.kt:1)
01-31 02:13:57.259 17633 17633 E ACRA    : 	at androidx.viewpager.widget.DirectionalViewPager.setScrollState(DirectionalViewPager.java:12)
01-31 02:13:57.259 17633 17633 E ACRA    : 	at androidx.viewpager.widget.DirectionalViewPager$3.run(DirectionalViewPager.java:1)
01-31 02:13:57.259 17633 17633 E ACRA    : 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1058)
01-31 02:13:57.259 17633 17633 E ACRA    : 	at android.view.Choreographer.doCallbacks(Choreographer.java:880)
01-31 02:13:57.259 17633 17633 E ACRA    : 	at android.view.Choreographer.doFrame(Choreographer.java:809)
01-31 02:13:57.259 17633 17633 E ACRA    : 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1043)
01-31 02:13:57.259 17633 17633 E ACRA    : 	at android.os.Handler.handleCallback(Handler.java:938)
01-31 02:13:57.259 17633 17633 E ACRA    : 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-31 02:13:57.259 17633 17633 E ACRA    : 	at android.os.Looper.loop(Looper.java:236)
01-31 02:13:57.259 17633 17633 E ACRA    : 	at android.app.ActivityThread.main(ActivityThread.java:7861)
01-31 02:13:57.259 17633 17633 E ACRA    : 	at java.lang.reflect.Method.invoke(Native Method)
01-31 02:13:57.259 17633 17633 E ACRA    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
01-31 02:13:57.259 17633 17633 E ACRA    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
01-31 02:13:57.508  7816  7816 E yomi.debug:acr: Not starting debugger since process cannot load the jdwp agent.
01-31 02:14:11.180  7895  7986 E SQLiteLog: (284) automatic index on C(manga_id)
01-31 02:14:11.180  7895  7986 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.12.3-4121 (standard, bf3bb8a37, 72, 2022-01-30T15:53Z)
Android version: 11 (SDK 30)
Android build ID: RKQ1.200826.002 test-keys
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: excalibur
Device model: Redmi Note 9 Pro Max
Device product name: excalibur_in
```

### Tachiyomi version

0.12.3 - 4121

### Android version

Android 11

### Device

Redmi note 9 pro max

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-12-05 20:37
Duplicate of #5987

**Closed by arkon** 2022-12-05 20:37 UTC
Labels: Bug
