### ISSUE TITLE
Allow "Paged Mode" to be manga specific.

### ISSUE THREAD

**Issue by Xorio71** [tachiyomiorg/tachiyomi#6755] opened 2022-03-09 13:44 UTC
### Describe your suggested feature

Changing the paged mode on a single manga shouldn't act as a universal switch.

I think it should work exactly how you've implemented the reader function. You go to a manga -> Press the gear -> Paged (Category) -> (E.g.) Original Size. Then, the change would be saved only for that manga.

The only way to change the setting on a global scale should be through the app's settings, and not through a single manga.

### Other details

![Screenshot_2022-03-09-15-42-27-077_eu kanade tachiyomi~2](https://user-images.githubusercontent.com/101265862/157453635-87a20278-34d6-42d2-a163-e585369287b9.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-03-09 13:48
Duplicate of #5864

**Closed by arkon** 2022-03-09 13:48 UTC
Labels: Feature request
