### ISSUE TITLE
Tachiyomi uses different versions of the library icon at different times

### ISSUE THREAD

**Issue by specterflare** [tachiyomiorg/tachiyomi#5521] opened 2021-07-09 09:46 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

r3571

### Android version

9.0

### Device

Kindle HD 10 2019

### Steps to reproduce

1. Set your Start Screen to "Browse"
2.  Open the app

### Expected behavior

App should use the "Libray" icon with the bookmark filled in

### Actual behavior

This:
![Screenshot_20210709-054121](https://user-images.githubusercontent.com/61708534/125059019-de95f900-e078-11eb-849f-0bc831b76282.png)

However, if you go to your library and then back out of it to any other tab, then it displays the proper icon:
![Screenshot_20210709-054130](https://user-images.githubusercontent.com/61708534/125059113-fbcac780-e078-11eb-97fb-ef1b1bb325c7.png)

Also the settings use the unfilled icon:
![Screenshot_20210709-054140](https://user-images.githubusercontent.com/61708534/125059163-071df300-e079-11eb-83c9-c5c00237cc33.png)

### Crash logs

N/A

### Other details

N/A

**Comment by arkon** [comment] 2021-07-09 10:38
Duplicate of #5447

**Closed by arkon** 2021-07-09 10:38 UTC
Labels: Bug
