### ISSUE TITLE
Crash w/ Specific Webtoon On-Screen

### ISSUE THREAD

**Issue by RobindaCoast** [tachiyomiorg/tachiyomi#6700] opened 2022-02-25 15:46 UTC
### Steps to reproduce

Have Flame Scans' "I Raised a Black Dragon" on-screen from anywhere in the app. Unclear if any other items do this.

### Expected behavior

I should safely scroll past it while browsing.

### Actual behavior

App crashes every time I scroll to it.

### Tachiyomi version

0.13.1

### Android version

Android 8.1.0

### Device

Samsung J7 plus

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by CrepeTF** [comment] 2022-02-25 15:47
Logs: https://ptb.discord.com/channels/349436576037732353/349436576037732355/946795196618768435

**Comment by resolritter** [comment] 2022-02-26 20:48
duplicate of https://github.com/tachiyomiorg/tachiyomi/issues/6689?

**Comment by RobindaCoast** [comment] 2022-02-27 03:04
Nope, entirely different, Flame Scans isn't a deleted source, nor is the webtoon.

**Comment by arkon** [comment] 2022-07-10 03:10
```
02-25 07:58:51.919  5225  5276 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x4 in tid 5276 (RenderThread), pid 5225 (anade.tachiyomi)
02-25 07:58:52.078  5543  5543 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
02-25 07:58:52.078  5543  5543 F DEBUG   : Build fingerprint: 'samsung/jadeltedx/jadelte:8.1.0/M1AJQ/C710FDXS6BUI1:user/release-keys'
02-25 07:58:52.078  5543  5543 F DEBUG   : Revision: '8'
02-25 07:58:52.078  5543  5543 F DEBUG   : ABI: 'arm'
02-25 07:58:52.078  5543  5543 F DEBUG   : pid: 5225, tid: 5276, name: RenderThread  >>> eu.kanade.tachiyomi <<<
02-25 07:58:52.078  5543  5543 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x4
02-25 07:58:52.078  5543  5543 F DEBUG   : Cause: null pointer dereference
02-25 07:58:52.079  5543  5543 F DEBUG   :     r0 00000004  r1 00000001  r2 b1477234  r3 00000000
02-25 07:58:52.079  5543  5543 F DEBUG   :     r4 b1477230  r5 dbe7023c  r6 00000000  r7 dbe701e0
02-25 07:58:52.079  5543  5543 F DEBUG   :     r8 b3e32c00  r9 00001908  sl be65545c  fp bdfff850
02-25 07:58:52.079  5543  5543 F DEBUG   :     ip d3a68b40  sp bdfff6b0  lr d21c2938  pc d21aa8c8  cpsr 200d0010
02-25 07:58:52.466  5543  5543 F DEBUG   : 
02-25 07:58:52.466  5543  5543 F DEBUG   : backtrace:
02-25 07:58:52.466  5543  5543 F DEBUG   :     #00 pc 004278c8  /system/vendor/lib/egl/libGLES_mali.so (egl_color_buffer_retain+8)
02-25 07:58:52.466  5543  5543 F DEBUG   :     #01 pc 0043f934  /system/vendor/lib/egl/libGLES_mali.so (egl_get_egl_image_template_gles+100)
02-25 07:58:52.466  5543  5543 F DEBUG   :     #02 pc 003f0808  /system/vendor/lib/egl/libGLES_mali.so (gles_texture_egl_image_target_texture_2d_oes+216)
02-25 07:58:52.466  5543  5543 F DEBUG   :     #03 pc 00035ca1  /system/lib/libhwui.so (android::uirenderer::debug::GlesErrorCheckWrapper::glEGLImageTargetTexture2DOES_(unsigned int, void*)+12)
02-25 07:58:52.466  5543  5543 F DEBUG   :     #04 pc 0004d1e5  /system/lib/libhwui.so (android::uirenderer::renderthread::OpenGLPipeline::allocateHardwareBitmap(android::uirenderer::renderthread::RenderThread&, SkBitmap&)+600)
02-25 07:58:52.466  5543  5543 F DEBUG   :     #05 pc 00052eab  /system/lib/libhwui.so (android::uirenderer::renderthread::RenderThread::allocateHardwareBitmap(SkBitmap&)+30)
02-25 07:58:52.466  5543  5543 F DEBUG   :     #06 pc 000519d1  /system/lib/libhwui.so (android::uirenderer::renderthread::Bridge_allocateHardwareBitmap(android::uirenderer::renderthread::allocateHardwareBitmapArgs*)+20)
02-25 07:58:52.466  5543  5543 F DEBUG   :     #07 pc 00051b8f  /system/lib/libhwui.so (android::uirenderer::renderthread::MethodInvokeRenderTask::run()+10)
02-25 07:58:52.466  5543  5543 F DEBUG   :     #08 pc 00051d0f  /system/lib/libhwui.so (android::uirenderer::renderthread::SignalingRenderTask::run()+10)
02-25 07:58:52.466  5543  5543 F DEBUG   :     #09 pc 00052a5f  /system/lib/libhwui.so (android::uirenderer::renderthread::RenderThread::threadLoop()+178)
02-25 07:58:52.466  5543  5543 F DEBUG   :     #10 pc 0000d23d  /system/lib/libutils.so (android::Thread::_threadLoop(void*)+144)
02-25 07:58:52.466  5543  5543 F DEBUG   :     #11 pc 00075575  /system/lib/libandroid_runtime.so (android::AndroidRuntime::javaThreadShell(void*)+80)
02-25 07:58:52.466  5543  5543 F DEBUG   :     #12 pc 00047f07  /system/lib/libc.so (__pthread_start(void*)+22)
02-25 07:58:52.466  5543  5543 F DEBUG   :     #13 pc 0001b209  /system/lib/libc.so (__start_thread+32)
```

Seems similar to #5375 (not enough memory to allocate an image).

**Closed by arkon** 2022-07-10 03:10 UTC
Labels: Bug
