### ISSUE TITLE
keep track of already read chapters that have been removed from the source

### ISSUE THREAD

**Issue by aspwil** [tachiyomiorg/tachiyomi#9167] opened 2023-03-02 06:27 UTC
### Describe your suggested feature

when chapter are removed from a source, they disappear.

if these are chapters you have read then the data that you have read said chapters is functionally lost.

ex:
i read chapter 1-100 of a manga

that source removes chapter 5-100
 
now it only displays chapters 1-5
 
if i were to migrate it only migrates up to chapter 5 for that manga, and i loose the data from the 95 chapters read.
 
while you could get around this using tracking, that relies on 3rd parties, and i think it would be best to have some sort of native solution. 

if there are missing chapters marked as read, keep track of the chapters and somehow tell the user that there are missing chapters, and what ones are missing.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2023-03-02 06:42
Duplicate of #3958 basically

**Closed by Seishirou101** 2023-03-02 06:42 UTC
Labels: Feature request
