### ISSUE TITLE
allow to disable/hide/delete option for extra chapter of manga

### ISSUE THREAD

**Issue by heartlog** [tachiyomiorg/tachiyomi#5925] opened 2021-09-18 02:10 UTC
### Describe your suggested feature

Many scans/translation group even websites upload more than 1 version of single chapter of manga.
Sometimes it goes like this-
### Manga 
>chapter 104
>chapter 104.5
>........
>chapter 105 
>....
>chapter 105 kun

`Here only 20 and 21 are main chapter of manga other are useless and time consuming also to go back and select an true complete chapter .`
--
For example :
![Screenshot_20210918-073316_Tachiyomi](https://user-images.githubusercontent.com/76758776/133868733-2f3397f9-e22c-404e-9c7e-942af0e865de.jpg)
--

So, i am requesting to add an option to hide/delete or disable manga/webtoon. So, It'll be easy to read manga or chapter after disabling extra chapter...

### Other details

# *all details I discribed in `Describe your suggested feature`

## For reference 
![Screenshot_20210918-073316_Tachiyomi](https://user-images.githubusercontent.com/76758776/133868733-2f3397f9-e22c-404e-9c7e-942af0e865de.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2021-09-18 02:23
Duplicate of #2542

**Closed** 2021-09-18 02:23 UTC
Labels: Feature request
