### ISSUE TITLE
[Feature Request] More advanced library update restrictions

### ISSUE THREAD

**Issue by paulo27ms** [tachiyomiorg/tachiyomi#4688] opened 2021-03-21 23:00 UTC
## Why/User Benefit/User Problem
A big issue Tachiyomi ends up creating is the load it puts on some sites because users try to get too many updates at once and most of the time it's completely unnecessary.

## What/Requirements
My first suggestion is something like adding an option for a restriction based on the upload date (or last new chapter appearance according to the Update tab) so Tachiyomi basically skips entries that received an update in the last X days.
These can both exist at the same time along with other potential restrictions to avoid redundant updates.
This could further be expanded to either be a global setting or a per-manga setting in case one manga is monthly and another weekly.

Another option to add would be to take upload frequency and only update that entries after that time frequency has passed. This would only really be possible on sources that include upload date.

To clarify, if you set Tachiyomi to update every hour, it'll still update every hour but imagine you set a restriction so a manga with a new chapter in the last 7 days isn't updated until another 7 pass, then when doing that hourly update, Tachiyomi simply doesn't check that manga and skips it.

**Comment by arkon** [comment] 2022-07-10 00:01
Duplicate of #6154 and #5885

**Closed by arkon** 2022-07-10 00:01 UTC
Labels: Feature request
