### ISSUE TITLE
[Feature Request] Add time since last backup to the More menu

### ISSUE THREAD

**Issue by Soitora** [tachiyomiorg/tachiyomi#5391] opened 2021-06-14 01:33 UTC
## Why/User Benefit/User Problem
This could help promote backing up to users if the app directly tells them when they last updated. If I saw "**Last updated: 7 months ago**" I would *for sure* update quickly.

## What/Requirements
The app would have to store information on when it was last backed up. Maybe every time it automatically/manually backs up, write to the database a timestamp.. or something?

## Extra comments
This could also be added somewhere to the actual backup page, but this request is mainly for the More controller.

## Concept
I realise I wrote "Updated" in the concept below, I dunno what I was thinking when I typed that word instead...

I meant "Last backup: 12 days ago"

![image](https://user-images.githubusercontent.com/10836780/121828846-1d76a000-ccc1-11eb-88cc-26563efb1093.png)

**Comment by arkon** [comment] 2021-06-14 21:18
Sort of duplicate of #3474, so I'll just merge these.

**Closed by arkon** 2021-06-14 21:18 UTC
Labels: feature
