### ISSUE TITLE
Support Auto Download next N unread chapters

### ISSUE THREAD

**Issue by cronjobsasha** [tachiyomiorg/tachiyomi#6361] opened 2021-12-18 18:42 UTC
### Describe your suggested feature

Right it supports auto download new chapter or manual download next N unread. It would be great if it kept downloading dynamically like Netflix Smart Download does.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2021-12-18 18:48
Duplicate of #3295

**Closed by Seishirou101** 2021-12-18 18:48 UTC
Labels: Feature request
