### ISSUE TITLE
Recommendations feature 

### ISSUE THREAD

**Issue by CherbyMina** [tachiyomiorg/tachiyomi#7626] opened 2022-07-27 13:22 UTC
### Describe your suggested feature

![Screenshot_20220727-211419](https://user-images.githubusercontent.com/86648349/181256718-b2589d8a-b081-486a-b97b-d671dd756586.jpg)

Here in the ss the arrow is where the recommendations feature is located like we can swipe from right to left the recommendations page and it will show up, ik it takes a lot of work to do but this one is a very very very very useful!! Feature in tachiyomi, because we can get recommendations inside the app and we can enjoy the same genre that we left off after we read a wholesome manga... I hope you take time to think about this feature and add it in the future too!.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-07-27 13:23
Duplicate of #376

**Closed by arkon** 2022-07-27 13:23 UTC
Labels: Feature request
