### ISSUE TITLE
When I zoom in it starts scrolling

### ISSUE THREAD

**Issue by enVi240** [tachiyomiorg/tachiyomi#10232] opened 2023-12-12 22:58 UTC
### Steps to reproduce

First I pinch. Well not pinch but you know the opposite of pinching to zoom in instead of double tapping so I can see small text
When I do that it starts to scroll intensely 

### Expected behavior

It should stay still

### Actual behavior

It scrolls for some reason

### Tachiyomi version

0.14.7

### Android version

Android 9

### Device

Huawei nova 3e

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-12-14 14:12
Duplicate of #2602

**Closed by arkon** 2023-12-14 14:12 UTC
Labels: Bug
