### ISSUE TITLE
Filter the comics by tags in the local comic details

### ISSUE THREAD

**Issue by Lyoke** [tachiyomiorg/tachiyomi#6172] opened 2021-10-30 01:09 UTC
### Describe your suggested feature

In the case of a large number of local comics,It's not easy to search for comics what i want,In the current version.In the local library, only the tags of local comics with the relevant theme can be searched, not the local comics with the tag, that is, the local comics with the same tags can be screened out from the comic details.Or you can add the filter tag function to the filter function in local library

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2021-10-30 03:25
Duplicate of #5078, essentially.

**Closed by arkon** 2021-10-30 03:25 UTC
Labels: Feature request
