### ISSUE TITLE
Saving the scene on the screen instead of the whole panel in webtoon 

### ISSUE THREAD

**Issue by Jjjggh** [tachiyomiorg/tachiyomi#7332] opened 2022-06-18 15:53 UTC
### Describe your suggested feature

On long press in the webtoon instead of Saving the whole panel , just Saving the scene on the screen,  just like it's taking a screen shot but instead Saving it in the folder of the webtoon directly as in the " save pages in separate folders " sitting but the only difference is that it doesn't save the whole panel 

I don't know if it's hard or easy but i hope it ain't much of hassle for you 

### Other details

Basically a screen shot but organized and done by the app itself 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-06-18 16:06
Duplicate of #7086

**Closed by arkon** 2022-06-18 16:06 UTC
Labels: Feature request
