### ISSUE TITLE
Downloaded chapter's not working for preview version 

### ISSUE THREAD

**Issue by Liking-Link** [tachiyomiorg/tachiyomi#10193] opened 2023-11-30 02:58 UTC
### Steps to reproduce

1.After updating new version no download shows .
2.I allowed rechecked storage location and permission, it's not working for preview version but works fine for stable version.
3.
![Screenshot_2023-11-29-19-14-25-71_79aa9bf7c61e266c5f841e42245e214b](https://github.com/tachiyomiorg/tachiyomi/assets/117823692/623cfae9-5520-4be2-b69b-422deeebf8a1)
![Screenshot_2023-11-29-19-14-18-87_79aa9bf7c61e266c5f841e42245e214b](https://github.com/tachiyomiorg/tachiyomi/assets/117823692/f3f1e0d3-7d72-40ec-9ea3-3b2ac36cd90d)
![Screenshot_2023-11-29-19-10-10-00_5734e8eb49b4234b62f913f831715b0f](https://github.com/tachiyomiorg/tachiyomi/assets/117823692/a9b3d375-8dfe-4f1d-a554-e4f757f4c7de)
Clicked on invalidate index , still not working.

### Expected behavior

In stable version it works fine as always, but preview version it should work after I allow .

### Actual behavior

Well it doesn't work anymore.

### Crash logs

No crash

### Tachiyomi version

r6237

### Android version

Android 11

### Device

Realme 6

### Other details

Preview r6237. App version: 0.14.7-6237 (standard, 27c4db752, 110, 2023-11-26T21:31Z) WebView: Android System WebView 119.0.6045.67

Not working downloaded chapter's anymore after this new update.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-11-30 03:10
I already answered [on Discord](https://discord.com/channels/349436576037732353/349436576037732355/1179436889799925770): 

> It's expecting the content to be in the "downloads" folder inside there. If you download something new, it'd probably show up in there.

If that doesn't address it, then duplicate of #10187.

**Closed by arkon** 2023-11-30 03:10 UTC
Labels: Bug
