### ISSUE TITLE
Tachi crash when remove a manga from libratory

### ISSUE THREAD

**Issue by leonminus** [tachiyomiorg/tachiyomi#10048] opened 2023-10-22 05:19 UTC
### Steps to reproduce

sometime when i remove a manga

### Expected behavior

the manga is remove and Tachi keep working

### Actual behavior

Tachi crash and close

### Tachiyomi version

0.14.6

### Android version

Android 11

### Device

Vivo Y21

### Other details
My Tachi have 7000 manga and that's maybe cause the problem but can anyone fix this

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by THElegend5** [comment] 2023-10-22 13:32
Duplicate of #7997

**Closed** 2023-10-25 13:25 UTC
Labels: Bug
