### ISSUE TITLE
Default Library Cover 

### ISSUE THREAD

**Issue by astralkill00** [tachiyomiorg/tachiyomi#8985] opened 2023-01-25 17:18 UTC
### Describe your suggested feature

I'd like this functionality to be able to search the previous cover artworks of the previous volumes of their respective series (like Neko) and use it as the default cover for all or selected series of the titles in the library.

Most latest covers of the series' volumes but not all usually gives a hint and some gives a definite spoiler to the future plots/story progress/etc of the series. (i.e. Volumr covers getting married and such)

I'd like to request an option in the Advance Settings under Library to have an option to make all series in the Library to be able to use their series' very first Volume Covers by default to those titles who have yet to be read even once. Even an additional option to only show the very first volume's cover when it has yet to be added to your library is also a wonderful future while searching.

Also, adding an additional option that will automatically change the cover art each time you finish a volume would also be nice instead of defaulting the Cover from the latest volume.
i.e. I currently reading Vol 1 and Vol 1's cover should be the only cover I see. If I were to successfully finish Vol1, Vol2's cover should appear and switch with the previous Vol's cover which is Vol1's.

### Other details

![Screenshot_2023-01-26-00-43-28-881-edit_eu kanade tachiyomi](https://user-images.githubusercontent.com/119454295/214634189-ba8fbf37-b3b1-466b-ac17-2cc738bd7910.jpg)
![IMG_20230126_004601](https://user-images.githubusercontent.com/119454295/214634210-ccad8114-011d-492b-99f6-26a74eb27ca4.png)
![Tensei Shitara Ken Deshita](https://user-images.githubusercontent.com/119454295/214634217-ffcb6c82-b40a-44db-811c-7344db47dcc3.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-01-25 17:22
Duplicate of #8133

**Closed** 2023-01-25 17:22 UTC
Labels: Feature request

**Comment by alessandrojean** [comment] 2023-01-25 18:13
Since you're using MangaDex, there's an extension setting to prefer using first volume covers when available, it may interest you.
