### ISSUE TITLE
2 extension's pointing to the same download causes a crash

### ISSUE THREAD

**Issue by Chkca** [tachiyomiorg/tachiyomi#10083] opened 2023-10-28 18:17 UTC
[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/13197419/tachiyomi_crash_logs.txt)
### Steps to reproduce

Flamescan extension has retired (did not remove)
Installed Flame comics (new extension)
Restarted Tachiyomi 
App version: 0.14.6-6132 (standard, 8057f067b, 107, 2023-10-25T13:24Z)
Go to  browse, sources and look for the new extension, Flamecomics not shown. 
Still in sources 😔 click on search and it crashes.
Try again and the same result.
Remove the new extension and repeat, still crashes.
When trying to browse, extension I view Flame comics, settings, English settings,  it displays flamescans.
Storage still has flamescans.
Remove flamescans(retired) from extensions, restart Tachiyomi.
Check flame comics and it now shows flame comics under English setting.
Storage is now showing flame comics with the flamescan added chapters.
Browse, sources, search does not crash.

Note, that the current release of Tachiyomi does not crash when using browse, sources, search.
It didn't display flame comics when flamescans extension was installed.

### Expected behavior

It shouldn't crash when extensions conflict.
It would be nice to have a warning that two or more  extensions are conflicting and display them.

### Actual behavior

Crashes whe 2 extensions are installed that are both trying to access the same download location

### Tachiyomi version

0.14.6-6132

### Android version

Android 12

### Device

Poco X3 NFC 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-10-28 18:34
Sounds like it'd actually a duplicate of #10069, but crash logs would confirm if that's the case.

**Comment by Chkca** [comment] 2023-10-29 07:18
> Sounds like it'd actually a duplicate of #10069, but crash logs would confirm if that's the case.

I have now added the crash logs.
Thanks

**Comment by arkon** [comment] 2023-10-29 14:11
```
10-28 18:06:41.013 11616 11616 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Index 3, size 3
10-28 18:06:41.013 11616 11616 E AndroidRuntime: 	at androidx.compose.foundation.lazy.layout.MutableIntervalList.checkIndexBounds(SourceFile:31)
10-28 18:06:41.013 11616 11616 E AndroidRuntime: 	at androidx.compose.foundation.lazy.layout.MutableIntervalList.get(SourceFile:1)
10-28 18:06:41.013 11616 11616 E AndroidRuntime: 	at androidx.compose.foundation.lazy.layout.LazyLayoutKt.getKey(SourceFile:5)
10-28 18:06:41.013 11616 11616 E AndroidRuntime: 	at androidx.compose.foundation.lazy.LazyListItemProviderImpl.getKey(SourceFile:11)
10-28 18:06:41.013 11616 11616 E AndroidRuntime: 	at androidx.compose.foundation.lazy.LazyListKt$rememberLazyListMeasurePolicy$1$1$measuredItemProvider$1.getAndMeasure(SourceFile:9)
10-28 18:06:41.013 11616 11616 E AndroidRuntime: 	at androidx.compose.foundation.lazy.LazyListMeasureKt.measureLazyList-50ZNEM8(SourceFile:67)
10-28 18:06:41.013 11616 11616 E AndroidRuntime: 	at androidx.compose.foundation.lazy.LazyListKt$rememberLazyListMeasurePolicy$1$1.invoke(SourceFile:482)
10-28 18:06:41.013 11616 11616 E AndroidRuntime: 	at androidx.compose.foundation.lazy.layout.LazyLayoutKt$LazyLayout$3$2$1.invoke(SourceFile:22)
10-28 18:06:41.013 11616 11616 E AndroidRuntime: 	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1.measure-3p2s80s(SourceFile:99)
10-28 18:06:41.013 11616 11616 E AndroidRuntime: 	at androidx.compose.ui.node.InnerNodeCoordinator$LookaheadDelegateImpl.measure-BRTryo0(SourceFile:63)
10-28 18:06:41.013 11616 11616 E AndroidRuntime: 	at androidx.compose.foundation.AndroidOverscrollKt$StretchOverscrollNonClippingLayer$1.invoke-3p2s80s(SourceFile:45)
10-28 18:06:41.013 11616 11616 E AndroidRuntime: 	at androidx.compose.foundation.AndroidOverscrollKt$StretchOverscrollNonClippingLayer$1.invoke(SourceFile:32)
10-28 18:06:41.013 11616 11616 E AndroidRuntime: 	at androidx.compose.ui.layout.LayoutModifierImpl.measure-3p2s80s(SourceFile:7)
10-28 18:06:41.013 11616 11616 E AndroidRuntime: 	at androidx.compose.ui.node.InnerNodeCoordinator$LookaheadDelegateImpl.measure-BRTryo0(SourceFile:98)
10-28 18:06:41.013 11616 11616 E AndroidRuntime: 	at androidx.compose.foundation.AndroidOverscrollKt$StretchOverscrollNonClippingLayer$1.invoke-3p2s80s(SourceFile:8)
10-28 18:06:41.013 11616 11616 E AndroidRuntime: 	at androidx.compose.foundation.AndroidOverscrollKt$StretchOverscrollNonClippingLayer$1.invoke(SourceFile:17)
10-28 18:06:41.013 11616 11616 E AndroidRuntime: 	at androidx.compose.ui.layout.LayoutModifierImpl.measure-3p2s80s(SourceFile:7)
10-28 18:06:41.013 11616 11616 E AndroidRuntime: 	at androidx.compose.ui.node.InnerNodeCoordinator$LookaheadDelegateImpl.measure-BRTryo0(SourceFile:98)
10-28 18:06:41.013 11616 11616 E AndroidRuntime: 	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(SourceFile:1)
10-28 18:06:41.013 11616 11616 E AndroidRuntime: 	at androidx.compose.ui.node.InnerNodeCoordinator$LookaheadDelegateImpl.measure-BRTryo0(SourceFile:98)
10-28 18:06:41.013 11616 11616 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performLookaheadMeasure$1.invoke(SourceFile:18)
10-28 18:06:41.013 11616 11616 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(SourceFile:61)
10-28 18:06:41.013 11616 11616 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SourceFile:52)
10-28 18:06:41.013 11616 11616 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SourceFile:171)
10-28 18:06:41.013 11616 11616 E AndroidRuntime: 	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(SourceFile:3)
10-28 18:06:41.013 11616 11616 E AndroidRuntime: 	at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release(SourceFile:11)
10-28 18:06:41.013 11616 11616 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate.access$performLookaheadMeasure-BRTryo0(SourceFile:25)
10-28 18:06:41.013 11616 11616 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$LookaheadPassDelegate.remeasure-BRTryo0(SourceFile:144)
10-28 18:06:41.013 11616 11616 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNode.lookaheadRemeasure-_Sx5XlM$ui_release(SourceFile:18)
10-28 18:06:41.013 11616 11616 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNode.lookaheadRemeasure-_Sx5XlM$ui_release$default(SourceFile:7)
10-28 18:06:41.013 11616 11616 E AndroidRuntime: 	at androidx.compose.ui.node.MeasureAndLayoutDelegate.doLookaheadRemeasure-sdFAvZA(SourceFile:16)
10-28 18:06:41.013 11616 11616 E AndroidRuntime: 	at androidx.compose.ui.node.MeasureAndLayoutDelegate.remeasureAndRelayoutIfNeeded(SourceFile:106)
10-28 18:06:41.013 11616 11616 E AndroidRuntime: 	at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureAndLayout(SourceFile:67)
10-28 18:06:41.013 11616 11616 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidComposeView.measureAndLayout(SourceFile:26)
10-28 18:06:41.013 11616 11616 E AndroidRuntime: 	at androidx.compose.ui.node.Owner$-CC.measureAndLayout$default(SourceFile:4)
10-28 18:06:41.013 11616 11616 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(SourceFile:12)
10-28 18:06:41.013 11616 11616 E AndroidRuntime: 	at android.view.View.draw(View.java:23005)
```

Looks like a duplicate of #10069, so should be fixed in the newer build.

**Closed by arkon** 2023-10-29 14:11 UTC
Labels: Bug
