### ISSUE TITLE
Sd Card + Cbz = No loading of downloaded chapters

### ISSUE THREAD

**Issue by 100lankiParth** [tachiyomiorg/tachiyomi#10098] opened 2023-11-01 17:39 UTC
### Steps to reproduce

1. Set download location to sd card
2. Set download type to cbz
3. Download some chapters
4. View the downloaded chapters

### Expected behavior

The chapters should open and be viewable

### Actual behavior

The downloaded itself works fine, its the loading part where the problem arises. When I try to open the downloaded chapter it just sends me back to he chapter list within a second.

### Tachiyomi version

0.14.7

### Android version

Android 13

### Device

Realme 10

### Other details

I think it has something to do with the extracting of the images from the cbz as when I tried to change the location of the cbz download folder to internal storage it worked fine.
Additionally it also worked fine in sd card but without the cbz file type,i.e. just normal folder and image structure.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-11-02 13:11
Duplicate of #9977

**Closed by arkon** 2023-11-02 13:11 UTC
Labels: Bug
