### ISSUE TITLE
Myanimelist tracking doesn't fill dates

### ISSUE THREAD

**Issue by Horodep** [tachiyomiorg/tachiyomi#8483] opened 2022-11-08 21:52 UTC
### Steps to reproduce

1. Turn on myanimelist tracking. 
2. Add tracking to an unread manga. 
3. Read first chapter of an unread manga. 

### Expected behavior

Status changes to reading, one chapter read, starting date — today. 

### Actual behavior

Status - ok, chapter counter - ok, date - empty. 

Same with finishing date.

### Tachiyomi version

0.14.2

### Android version

Android 11 (One UI 3.1)

### Device

Samsung A71

### Other details

Bug appeared in 0.14.?. 
Worked fine before. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-11-08 22:25
Duplicate of #6734 (although it is possibly a bug in some cases)

**Closed by arkon** 2022-11-08 22:25 UTC
Labels: Bug
