### ISSUE TITLE
Feature Request - Custom DNS Settings

### ISSUE THREAD

**Issue by 8227846265** [tachiyomiorg/tachiyomi#7782] opened 2022-08-17 01:51 UTC
### Describe your suggested feature

Please add a feature to add our own custom DNS-over-HTTPS on the settings in addition of the current options.

Screenshot
https://i.imgur.com/4y03ckH.jpg

For reference, while we could use DoT on the Android Settings. 

There are users that prefers using a specific DoH or DoT address on other apps. 

For example. I use DoT via Android setting while on Browser, I use DoH via the Browser settings. 

Since Tachiyomi already supports custom DoH except that's its pre-selected. It would be nice to go further and add a custom DNS settings 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2022-08-17 02:02
Duplicate of #6426

**Closed by Seishirou101** 2022-08-17 02:02 UTC
Labels: Feature request
