### ISSUE TITLE
Migrating a series with downloaded chapters causes Tachiyomi to leak storage

### ISSUE THREAD

**Issue by KiloJuliett** [tachiyomiorg/tachiyomi#5961] opened 2021-09-24 01:25 UTC
### Steps to reproduce

Migrating a series with downloaded chapters causes Tachiyomi to leak storage.*

1. Identify a series that is listed in two different extensions. In my testing I used *Ah... and Mm... Are All She Says* by Kondou Shouma, which is listed in the Dynasty and Mangakakalot extensions. Yeah yeah aggregate sites something something *ecchi* manga etc. etc.
2. Add one version (say, the one listed in the Mangakakalot extension) of the series to your library.
3. Download a couple chapters.
4. Migrate to the other version (the Dynasty version).
5. Go look through your device's files. Observe that the downloaded files remain on the device. There is no obvious indicator on the Tachiyomi app that these files exist, and the only way to know that these files exist without having encountered them by chance in your device's filesystem is to migrate back to the original (Mangakakalot) version and observe that the chapters have been downloaded there.

Clearing the database does not reclaim leaked storage.

6. While still having the second version (Dynasty) of the series in your library, attempt to clear the Tachiyomi app's history using the "Clear database" setting.
7. For fun I also cleared the chapter cache too to see if that would do anything.
8. Observe that the state of the downloaded chapters established at step 5 have not changed.

-----------

*So I'm gonna be totally honest with you, "storage leak" is a phrase that I invented just now. I am referring to the hard drive equivalent of a memory leak.

### Expected behavior

In my mind there are three reasonable behaviours for the Tachiyomi app when migrating with chapters downloaded:

1. The app could migrate downloaded chapters when migrating extensions. I can foresee the possibility of conflict if the versions of the chapter aren't identical, so maybe this behaviour is less reasonable than I think it is.
2. The app could delete downloaded chapters when migrating extensions. Until I noticed this issue, this is what I thought the app was doing.
3. The app could notify the user in some way that these downloaded chapters exist when migrating extensions.

I also expected that the "Clear database" button in the settings menu would rectify this leaked storage issue.

### Actual behavior

After migrating versions, the Tachiyomi app did none of the reasonable behaviours I listed above. The downloaded chapters remain on my device (this can be verified by migrating back to the original version or by going through the device's files) and the app has given no obvious indication to me that these downloaded chapters exist.

The "Clear database" button in the settings menu did not delete these files.

### Crash logs

*Section left blank. The app does not crash.*

### Tachiyomi version

0.12.2

### Android version

Android 10

### Device

Samsung Galaxy S9

### Other details

*Section left blank.*

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2021-09-24 01:32
Duplicate of #1767

**Closed** 2021-09-24 01:33 UTC
Labels: Bug
