### ISSUE TITLE
Option to "lock" reading mode per manga

### ISSUE THREAD

**Issue by CaptV0rt3x** [tachiyomiorg/tachiyomi#6758] opened 2022-03-09 19:19 UTC
### Describe your suggested feature

Option to "lock" the current manga's reading mode would make it so that you cannot change it without unlocking it.

I've had many accidental zoom-outs that messed up my manga view. I understand the view can be reset by re-selecting the reading mode, but it'd be much simpler to just allow users to lock their preferred reading mode per manga.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-03-09 19:39
Duplicate of #3059

**Closed by arkon** 2022-03-09 19:39 UTC
Labels: Feature request
