### ISSUE TITLE
[Feature Request] Delete local manga

### ISSUE THREAD

**Issue by NotRel** [tachiyomiorg/tachiyomi#4460] opened 2021-02-12 08:44 UTC
## Why/User Benefit/User Problem
If i have 500+ different local manga, and i finished one of them, how can i delete it from my storage without going in the trouble of going into file manager and delete it from there manually?
Ok maybe deleting 1 manga can be easy but what if i read and finished different 20+ manga, and i want to delete them now, it will be a frustrating task to go back and forth between the app and the file manager to delete each manga by name. 

## What/Requirements
So the feature I am asking is an option to delete the manga from storage within the app.

**Comment by scb261** [comment] 2021-02-12 11:22
Duplicate of #1770

**Comment by NotRel** [comment] 2021-02-12 11:59
Ok i tried the delete option by adding the manga to library then deleting it from there with both checkbox checked and nothing happen, i think this is will only work for the downloaded manga not the local one. 
However i tried it again with the following steps
1. Clear database
2. Clear cache within the app
3. Force stop and clear cache
4. Rebooted the device

Still the manga was inside local source and in the file manager.

**Closed** 2021-02-12 14:01 UTC
Labels: feature
