### ISSUE TITLE
Display chapters by Publishing/Scanslating Groups

### ISSUE THREAD

**Issue by AranyaMaji** [tachiyomiorg/tachiyomi#9583] opened 2023-06-05 06:26 UTC
### Describe your suggested feature

It would be very helpful if the chapters of an entry could be displayed based on the groups who have published/scanslated the chapter.

Some sources like Comick and Mangadex have many groups so there are many of the same chapter and that ends up causing one to skip through many chapters. 

The solution I suggest is to have the option in chapter filters to check (checkbox (add/remove)) groups that have chapters listed in the entry.

Expecting positive feedback. Thank you!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2023-06-05 16:41
Duplicate of #969

**Closed by Seishirou101** 2023-06-05 16:41 UTC
Labels: Feature request
