### ISSUE TITLE
Collapse items of the same manga in a single collapsible item in the updates tab

### ISSUE THREAD

**Issue by Anan5a** [tachiyomiorg/tachiyomi#10107] opened 2023-11-05 09:45 UTC
### Describe your suggested feature

Now it looks like this 
![Screenshot_2023-11-05-15-40-02-54_afd66b7916d19a60815f56273408b73e](https://github.com/tachiyomiorg/tachiyomi/assets/16373480/1584672d-ee61-4d93-a54a-dbe9a92fc64b)
But the it should be like this (it's from lnreader)
![Screenshot_2023-11-05-15-44-28-21_3c1c179116822eec69c21805387f0489](https://github.com/tachiyomiorg/tachiyomi/assets/16373480/002c9648-3352-4f71-82fb-4185f36b880d)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment] 2023-11-05 11:17
Duplicate of #2774

**Closed** 2023-11-05 11:17 UTC
Labels: Duplicate, Feature request
