### ISSUE TITLE
App Crashes when adding/removing Galleries from the Library

### ISSUE THREAD

**Issue by OdiumHypashoq** [tachiyomiorg/tachiyomi#9913] opened 2023-09-07 22:41 UTC
### Steps to reproduce

Example
Step 1: Open Extension or Library
Step 2: Select a Gallery to Favorite or Remove from the Library
Issue: App Crashes

### Expected behavior

Expected:
Gallery gets added to the library or removed without crashing the app.

### Actual behavior

App crashes seemingly at random when adding or removing Galleries from the Library

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/12553913/tachiyomi_crash_logs.txt)
[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/12553914/tachiyomi_crash_logs.txt)

### Tachiyomi version

0.14.6

### Android version

Android 13

### Device

Samsung Galaxy Tab S8+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-09-08 02:26
```

09-08 00:26:39.970 12184 21985 E CursorWindow: Failed to read row 742, column 0 from a CursorWindow which has 742 rows, 26 columns.
09-08 00:26:40.139 22008 22035 E SQLiteLog: (283) recovered 619 frames from WAL file /data/user/0/eu.kanade.tachiyomi/databases/tachiyomi.db-wal
09-08 00:26:40.729 22008 22008 E BufferQueueProducer: Unable to open libpenguin.so: dlopen failed: library "libpenguin.so" not found.
09-08 00:27:08.510 22235 22272 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
09-08 00:27:08.859 22235 22235 E BufferQueueProducer: Unable to open libpenguin.so: dlopen failed: library "libpenguin.so" not found.
09-08 00:27:08.931 22235 22273 E SQLiteLog: (284) automatic index on C(manga_id)
09-08 00:27:08.931 22235 22273 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
09-08 00:27:43.519 22640 22640 E BufferQueueProducer: Unable to open libpenguin.so: dlopen failed: library "libpenguin.so" not found.
09-08 00:27:43.575 22640 22880 E SQLiteLog: (284) automatic index on C(manga_id)
09-08 00:27:43.575 22640 22880 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
09-08 00:27:51.495 22640 22852 E CursorWindow: Failed to read row 742, column 0 from a CursorWindow which has 742 rows, 26 columns.
09-08 00:27:51.502 22640 22907 E GlobalExceptionHandler: java.lang.NullPointerException
09-08 00:27:51.502 22640 22907 E GlobalExceptionHandler: 	at tachiyomi.data.data.LibraryViewQueriesImpl$library$1.invoke(DatabaseImpl.kt:17)
09-08 00:27:51.502 22640 22907 E GlobalExceptionHandler: 	at com.squareup.sqldelight.Query.executeAsList(Query.kt:18)
09-08 00:27:51.502 22640 22907 E GlobalExceptionHandler: 	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToList$1$1.invokeSuspend(FlowExtensions.kt:6)
09-08 00:27:51.502 22640 22907 E GlobalExceptionHandler: 	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToList$1$1.invoke(FlowExtensions.kt:13)
09-08 00:27:51.502 22640 22907 E GlobalExceptionHandler: 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:8)
09-08 00:27:51.502 22640 22907 E GlobalExceptionHandler: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:50)
09-08 00:27:51.502 22640 22907 E GlobalExceptionHandler: 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
09-08 00:27:51.502 22640 22907 E GlobalExceptionHandler: 	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToList$$inlined$map$1$2.emit(Collect.kt:76)
09-08 00:27:51.502 22640 22907 E GlobalExceptionHandler: 	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:2)
09-08 00:27:51.502 22640 22907 E GlobalExceptionHandler: 	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:18)
09-08 00:27:51.502 22640 22907 E GlobalExceptionHandler: 	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:1)
09-08 00:27:51.502 22640 22907 E GlobalExceptionHandler: 	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$asFlow$1.invokeSuspend(FlowExtensions.kt:120)
09-08 00:27:51.502 22640 22907 E GlobalExceptionHandler: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
09-08 00:27:51.502 22640 22907 E GlobalExceptionHandler: 	at kotlinx.coroutines.flow.internal.SafeCollector.invokeSuspend(SafeCollector.kt:22)
09-08 00:27:51.502 22640 22907 E GlobalExceptionHandler: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
09-08 00:27:51.502 22640 22907 E GlobalExceptionHandler: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
09-08 00:27:51.502 22640 22907 E GlobalExceptionHandler: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
09-08 00:27:51.502 22640 22907 E GlobalExceptionHandler: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
09-08 00:27:51.502 22640 22907 E GlobalExceptionHandler: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
09-08 00:27:51.502 22640 22907 E GlobalExceptionHandler: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:63)
09-08 00:27:51.502 22640 22907 E GlobalExceptionHandler: 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [CoroutineName(eu.kanade.tachiyomi.ui.library.LibraryTab:eu.kanade.tachiyomi.ui.library.LibraryScreenModel:default:ScreenModelCoroutineScope), StandaloneCoroutine{Cancelling}@f6f5fdf, Dispatchers.IO]
```

**Comment by arkon** [comment] 2023-09-08 02:27
Duplicate of #7997

**Closed by arkon** 2023-09-08 02:27 UTC
Labels: Bug
