### ISSUE TITLE
Category wise lock beside the full app lock

### ISSUE THREAD

**Issue by Anan5a** [tachiyomiorg/tachiyomi#6130] opened 2021-10-18 03:22 UTC
### Describe your suggested feature

Beside having the app lock, it's better to have a lock for categories. For example I want to share my manga Library with others to read together but I definitely wouldn’t be able to share my Doujin/Hentai library with others

Is it possible to add this feature? 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2021-10-18 03:35
Duplicate of #1508

**Closed** 2021-10-18 03:35 UTC
Labels: Feature request
