### ISSUE TITLE
mass source migration 

### ISSUE THREAD

**Issue by kasakaka** [tachiyomiorg/tachiyomi#4477] opened 2021-02-14 17:26 UTC
Mainly for the users who have large library of their collected mangas. The feature can have you mass migrate multiple mangas from source to source especially when some of the source have become obsolete

**Comment by scb261** [comment] 2021-02-14 17:33
Duplicate of #1231 and you probably should read tachiyomiorg/tachiyomi-extensions#5672

**Closed** 2021-02-14 17:44 UTC
Labels: feature
