### ISSUE TITLE
(almost) Permanent white screen by going to quick back

### ISSUE THREAD

**Issue by Icewolf9** [tachiyomiorg/tachiyomi#8618] opened 2022-11-26 13:07 UTC
### Steps to reproduce

1. Search a manga,... from your library in al sources (click on title)
2. Click on a version from a different source
3. Go back as quick as you can with the standard back button on your phone

![Screenshot_20221126_135320](https://user-images.githubusercontent.com/119114404/204089970-f281be1a-3a43-4a75-a577-397a8e50ffab.jpg)

### Expected behavior

Should stay on your last chosen library

### Actual behavior

White screen that only goes away when you force stop the app or use a notification (downloader,...)

![Screenshot_20221126-134759_Tachiyomi](https://user-images.githubusercontent.com/119114404/204090068-3a0f0a25-5508-4ce5-b35c-41a187f3ffe1.jpg)

### Tachiyomi version

0.14.2

### Android version

Android 12

### Device

A52s

### Other details

It goes back to normal if you click on a notification that brings you to one of the pages (downloader,...) or force stop it. 
It is also maybe not a extension problem because it happens with everyone of them.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-11-26 13:11
Duplicate of #8431

**Closed** 2022-11-26 13:12 UTC
Labels: Bug
