### ISSUE TITLE
Check for updates improvement 

### ISSUE THREAD

**Issue by Fir3Soul** [tachiyomiorg/tachiyomi#7474] opened 2022-07-07 06:23 UTC
### Describe your suggested feature

So I'm cool with the fact that you will skip updating certain sources if I have not started reading it or I have unread chapters. But I had this issue where a new chapter was out but it was 5 chapters in advance so instead for chapter 200 it was 205, ofc I did not want to read it cause it's 5 chapters in advance I was waiting for the older ones to come but with the new app since chapter 205 was unread you guys would skip it. My suggestion would be that instead of if there is an unread chapter make it like 10 unread chapters ? Some people do like to make a short backlog before reading a lot in one go.
My work around was to mark that chapter as read then update it and if the chapters appeared awesome stuff

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by SeriousMatters** [comment] 2022-07-07 06:54
Duplicate of [#1177143829](https://github.com/tachiyomiorg/tachiyomi/issues/6916) ?
You even replied there already.

**Comment by Fir3Soul** [comment] 2022-07-07 07:11
Hmm yes, at first I checked stuff but github did not show it to me but then after creating the issue i manage to stumble upon it so yeah will close this

**Closed** 2022-07-07 11:11 UTC
Labels: Feature request
