### ISSUE TITLE
Tachiyomi crashing when pressing back button in some tabs or while manga info is loading

### ISSUE THREAD

**Issue by atmazzerexe** [tachiyomiorg/tachiyomi#7704] opened 2022-08-08 10:18 UTC
### Steps to reproduce

1. Enable "Confirm Exit" Option in Settings -> General (Optional, only for checking how Tachiyomi behave)
2. Go to "More" tab or any other tabs. Or alternatively go to library and click any manga you want
3. Press back button after the tab/section fully loaded (Only in "More" tab) or while loading

![Tachiyomi-Expected Behaviour1-Bug5](https://user-images.githubusercontent.com/14852623/183393346-8231c510-ba5c-45e2-8001-669bedcf8dfc.png)

### Expected behavior

App goes back to previous section (eg. "More" tab -> Library) or triggering the exit prompt

![Tachiyomi-Expected Behaviour2-Bug5](https://user-images.githubusercontent.com/14852623/183393596-03879ed4-87aa-4ee2-9afb-6bbb3f87595f.png)

### Actual behavior

Tachiyomi will suddenly crash. This bug has been tested in following tab/section:

"History" Tab
![Tachiyomi-Actual Behaviour_History-Bug5](https://user-images.githubusercontent.com/14852623/183392929-1d05afaf-478b-4c90-a429-a6674b8002f5.png)

"More" Tab
![Tachiyomi-Actual Behaviour_More-Bug5](https://user-images.githubusercontent.com/14852623/183393034-4a9d642e-27b7-4ca5-9984-0537f091a969.png)

"Update" Tab
![Tachiyomi-Actual Behaviour_Update-Bug5](https://user-images.githubusercontent.com/14852623/183393080-99e3535e-436f-4237-a8ea-14a97ce602d5.png)

"Manga Info" section
![Tachiyomi-Actual Behaviour_MangaInfo-Bug5](https://user-images.githubusercontent.com/14852623/183393166-0f8e99af-48ef-41cb-b21d-7e7cb23468d3.png)

### Crash logs

[tachiyomi_crash_logs8.txt](https://github.com/tachiyomiorg/tachiyomi/files/9280525/tachiyomi_crash_logs8.txt)

### Tachiyomi version

r4739

### Android version

Android 11 (AOSP)

### Device

ASUS Zenfone Max Pro M1

### Other details

Probably related to commit 5e68fe4fe92dfe281662fce84195288c743f5cb7.
This bug will not occur in "Library" tab and manga list from "Source" tab

![Tachiyomi-Expected Behaviour3-Bug5](https://user-images.githubusercontent.com/14852623/183394919-d318816d-fccc-4e87-912b-3b25052242e1.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by DchanN** [comment] 2022-08-08 12:52
kind of duplicate of #7433 because preview in compose rework make manga info page slow to load, same as library load and history and update tab become slow

**Comment by raziel100** [comment] 2022-08-08 20:06
> kind of duplicate of #7433 because preview in compose rework make manga info page slow to load, same as library load and history and update tab become slow

true, you need to wait until it get all information, if not will crash

**Comment by atmazzerexe** [comment] 2022-08-08 20:21
> true, you need to wait until it get all information, if not will crash

Until r4716, the behaviour of "History", "Update", and "More" tabs were basically #7603 though, even if it's still in loading state. Now, it'll just crash outright. At least that's how it is on my device.

**Comment by atmazzerexe** [comment] 2022-08-14 11:15
This bug is almost fully fixed now after updating to r4765, except for a minor one in "Update" tab where it won't go back to "Library" tab if it's still in loading state, although it won't crash the app like before.

![Tachiyomi-Actual Behaviour_Update2-Bug5](https://user-images.githubusercontent.com/14852623/184534094-08eaccf2-bcd4-45ef-9726-2f22bb10333e.png)

**Closed** 2022-09-19 02:38 UTC
Labels: Bug
