### ISSUE TITLE
[Bug] Unable to load the local source cover

### ISSUE THREAD

**Issue by DDXDB** [tachiyomiorg/tachiyomi#3783] opened 2020-09-12 09:11 UTC
## Device information
Tachiyomi version: v0.10.4
Android version: Android 10
Device: one Plus 7 pro
Steps to reproduce

## Steps to reproduce
The cover cannot be loaded if the local source folder name is greater than five Chinese characters

**Comment by scb261** [comment] 2020-09-12 09:37
Try steps in #932

**Comment by scb261** [comment] 2021-01-13 15:15
Tried with "测试测试测试", can't reproduce. Probably just duplicate of #932. If not - provide manga title with the name that causes the error

**Comment by arkon** [comment] 2021-04-17 15:39
Closing as duplicate of #932.

**Closed by arkon** 2021-04-17 15:39 UTC
Labels: bug
