### ISSUE TITLE
[Feature Request] Mark chapter as read if tracker says it's read

### ISSUE THREAD

**Issue by MrDew25** [tachiyomiorg/tachiyomi#4206] opened 2020-12-28 06:18 UTC
## Why/User Benefit/User Problem
This would benefit users that operate on multiple devices, or reads physical versions of the Manga available and updates their Manga tracking service, but not the application. That way, users wouldn't have to wonder whether or not they have already read a chapter, as it would automatically be marked as read.

Assuming that there are no plans for creating a Tachiyomi account system, this would be an easy way to implement something to work across devices.

## What/Requirements
Once refreshing a Manga, be it just one or the whole library, the application would check any trackers that the Manga in the user's library has. If the tracker lists the most recently read chapter as one that is later then the last one read on the device, it will mark all chapters upto what the tracker states.

I.E. MAL marks Manga A as having read up to Chapter 173, but the most recently read chapter in Tachiyomi is Chapter 168. During a refresh, the application sees that Chapter 173 comes after Chapter 168, and marks every chapter marked as unread between 1-173 as marked, leaving Chapter 174 onwards unread.

**Comment by scb261** [comment] 2020-12-28 08:51
Duplicate of #1626

**Closed** 2020-12-28 11:47 UTC
Labels: feature
