### ISSUE TITLE
Delete chapters from "Updates"

### ISSUE THREAD

**Issue by JamesWarlord** [tachiyomiorg/tachiyomi#9080] opened 2023-02-13 10:46 UTC
### Describe your suggested feature

Similarly to how we can delete chapters from "History", I would like to suggest having the same feature on "Updates" to delete entries we don't want to show.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-02-14 22:30
Duplicate of #4133.

There's other open issues for filtering it.

**Closed by arkon** 2023-02-14 22:30 UTC
Labels: Feature request
