### ISSUE TITLE
App freezes sometimes when reading manga

### ISSUE THREAD

**Issue by MrAndre96** [tachiyomiorg/tachiyomi#7828] opened 2022-08-20 20:26 UTC
### Steps to reproduce

1. Open a manwha (webtoon reading mode)
2. Start reading
3. Sometimes it suddenly freezes which leads to a popup to wait or close the app

### Expected behavior

It does not sometimes freeze

### Actual behavior

Sometimes it freezes while reading

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/9387975/tachiyomi_crash_logs.txt)

### Tachiyomi version

r4799

### Android version

Android 11

### Device

Oneplus 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Purkid** [comment] 2022-08-20 21:45
A similar issue was posted fourteen days ago,
 #7692. 
This have been happening to me after recent update as well.
When reading, the app either out a sudden freezes or freezes then returns you to the your app's opening page. I've observed recently that this happens almost all the time when I transition to next chapter.
I hope they could find the remedy soon bc it is very unbearable.

**Comment by MrAndre96** [comment] 2022-08-20 22:01
> A similar issue was posted fourteen days ago, #7692. This have been happening to me after recent update as well. When reading, the app either out a sudden freezes or freezes then returns you to the your app's opening page. I've recently observed that this happens almost all the time when I transition to next chapter.

Saw that but it seems to be a different issue based on the crash logs

**Comment by DchanN** [comment] 2022-08-21 02:21
@MrAndre96 kind of duplicate of #7240 and mayb3 your issue too @Purkid

**Comment by raziel100** [comment] 2022-08-21 06:00
> @MrAndre96 kind of duplicate of #7240 and maybe your issue too @Purkid

Yeah. It's still happening a couple of times, sadly I couldn't find why

**Comment by raziel100** [comment] 2022-08-21 06:13
> > A similar issue was posted fourteen days ago, #7692. This have been happening to me after recent update as well. When reading, the app either out a sudden freezes or freezes then returns you to the your app's opening page. I've recently observed that this happens almost all the time when I transition to next chapter.
> 
> Saw that but it seems to be a different issue based on the crash logs

The logs could be different, but the issue is the same, the application just more or less crash when reading for awhile, and the Android will say that tachiyomi is crashing constantly and if you want to wait ou close, some times here when I go to see the applications report in Android, tachiyomi have more than 50 crashes in 1 day

**Comment by DchanN** [comment] 2022-08-21 06:32
> > > A similar issue was posted fourteen days ago, #7692. This have been happening to me after recent update as well. When reading, the app either out a sudden freezes or freezes then returns you to the your app's opening page. I've recently observed that this happens almost all the time when I transition to next chapter.
> > 
> > 
> > Saw that but it seems to be a different issue based on the crash logs
> 
> The logs could be different, but the issue is the same, the application just more or less crash when reading for awhile, and the Android will say that tachiyomi is crashing constantly and if you want to wait ou close, some times here when I go to see the applications report in Android, tachiyomi have more than 50 crashes in 1 day

#7692 look different maybe because it's related to downloaded chapter, but for this issue crash log from @MrAndre96 same with me in my latest comment in #7240, so seems this issue same/duplicate of #7240

**Comment by vetleledaal** [comment] 2022-08-22 02:45
Duplicate of #7240

**Closed by vetleledaal** 2022-08-22 02:45 UTC
Labels: Bug
