### ISSUE TITLE
Device rotation causes infinite loading on CBR files

### ISSUE THREAD

**Issue by Slusho64** [tachiyomiorg/tachiyomi#6588] opened 2022-02-07 05:57 UTC
### Steps to reproduce

1. Open a local .cbr comic
2. Rotate device 90 degrees

### Expected behavior

Comic and interface should rotate to new orientation

### Actual behavior

Interface rotates fine but comic page is replaced with loading circle animation that never goes away and comic page never returns

### Tachiyomi version

Preview r4139 (tested with stable as well)

### Android version

Android 12

### Device

Samsung Galaxy Tab S7+

### Other details

CBZ files do not exhibit this bug; they work as expected. Available releases seem to be roughly 50/50 on using CBZ/CBR so converting each would not be worth the time.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-07-09 17:23
Duplicate of #6096

**Closed by arkon** 2022-07-09 17:23 UTC
Labels: Bug
