### ISSUE TITLE
[Feature Request] You should be allowed to set a reading mode default in a category

### ISSUE THREAD

**Issue by LandChit** [tachiyomiorg/tachiyomi#5275] opened 2021-06-02 14:46 UTC
## Why/User Benefit/User Problem
(explain why this feature should be added)
Because there would be less time wasted in changing the reading mode

## What/Requirements
(explain how this feature would behave)
In the settings the category tab there should be a cog beside the category name in which you can set the default settings for that category

**Comment by curche** [comment] 2021-06-02 14:52
Duplicate of #2518

**Closed** 2021-06-02 15:20 UTC
Labels: feature
