### ISSUE TITLE
first page of downloaded chapters often crash on loading with the message "image couldn't be loaded"

### ISSUE THREAD

**Issue by WeepingClown13** [tachiyomiorg/tachiyomi#9800] opened 2023-08-04 08:05 UTC
### Steps to reproduce

From my experience:

1. Download some manhwa/manhua from an extension (MangaSee for example, but isn't limited to)
2. Turn off the internet.
3. Open the downloaded content and put it on webtoon mode.

### Expected behavior

Since the chapters are downloaded, they should load without any issues.

### Actual behavior

First one or two pages often crash saying "Image couldn't be loaded" with the buttons "retry" and "open in webview" showing, even though the image is actually loaded behind it. This "first" is not limited to literally the first image of a chapter but from where you stopped reading in the chapter, ie if I stopped at 5th page of a 10 page chapter, next time page 5 could crash when I open it.

### Tachiyomi version

0.14.6

### Android version

Android 13

### Device

Samsung S20 FE 5G

### Other details

 Been facing this issue for quite long across various extensions such as MangaSee, 1stkiss etc. I recently changed my device and it has been persisting nonetheless.
![WhatsApp Image 2023-07-02 at 21 08 25](https://github.com/tachiyomiorg/tachiyomi/assets/95921427/26abba24-9dd7-4629-8296-1a2c4f27bbce)
![WhatsApp Image 2023-07-09 at 14 07 18](https://github.com/tachiyomiorg/tachiyomi/assets/95921427/84c3cae4-3a1f-40fa-b506-17d7a522a3cd)

PS: Can see same issue being closed multiple times before but opening it again as it seems previous fixes did not fix this.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-08-04 13:52
Duplicate of #5687

**Closed by arkon** 2023-08-04 13:52 UTC
Labels: Bug
