### ISSUE TITLE
App crashes when being in categories 

### ISSUE THREAD

**Issue by lvlahraam** [tachiyomiorg/tachiyomi#8426] opened 2022-11-02 14:30 UTC
### Steps to reproduce

When I try to make a category go up or go down the app crashes

### Expected behavior

The category should've gone up or down

### Actual behavior

Changing the position of the category

### Tachiyomi version

0.14.2

### Android version

Android 12

### Device

Xiaomi Note 10 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-11-02 16:50
Duplicate of #8372

**Closed by arkon** 2022-11-02 16:51 UTC
Labels: Bug
