### ISSUE TITLE
Local manga cover not showing

### ISSUE THREAD

**Issue by jak0159** [tachiyomiorg/tachiyomi#5939] opened 2021-09-19 08:32 UTC
### Steps to reproduce

Followed troubleshooting steps to add cover for local manga

### Expected behavior

Local cover manga should have a new cover updated

### Actual behavior

Cover still appears black

### Tachiyomi version

0.12.2

### Android version

Android version 10

### Device

Samsung s9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2021-09-19 12:55
Duplicate of #932

**Closed by arkon** 2021-09-19 12:55 UTC
Labels: Bug
