### ISSUE TITLE
Webtoon pages don't load 

### ISSUE THREAD

**Issue by saidmakkass** [tachiyomiorg/tachiyomi#5945] opened 2021-09-21 07:08 UTC
### Steps to reproduce

Example:
Reading any webtoon that is poorly divided into a small number of pages (7 or 6), rather than a larger number of pages with less content per page (anywhere from 8 to 50 pages)

### Expected behavior

For all pages to be loaded correctly especially when downloaded 

### Actual behavior

Pages that exceed a certain length fail to load completely, and even result in crashes.
This only happens in the webtoon mode, those same pages that fail to load in webtoon mode, load easily in other modes (except continues vertical). 
This issues also hapens when choosing the option to fit width in the other modes.
Pages that are shorter in hight load perfectly fine in the webtoon mode.

### Crash logs

https://pastebin.com/UVAF543h

### Tachiyomi version

0.12.2

### Android version

Android 10

### Device

Galaxy j6+

### Other details

This issues wasn't too big of a deal to me because i was able to just load the problematic pages in the default mode (right to left) and then zoom on the page to fit the width and scrool down, which allowed for a makeshift webtoon mode that was only able to loead a part of the page at a time, where the other parts were blurry and needed time to load fully but it was enought to manage the poorly divided chapters. But as of updating to the new version (0.12.2) that has become impossible (at least i think so), the zooming action has been for some reason severely limited, to the point that it's impossible to read any text from the long webtoon pages loaded in the default modes while zooming all the way in, when it was easy to over zoom when double tapping in the previous version (0.12.1) 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2021-09-21 12:29
Duplicate of #1908

**Closed by arkon** 2021-09-21 12:29 UTC
Labels: Bug
