### ISSUE TITLE
Frame rate drop

### ISSUE THREAD

**Issue by NatsukiBaka** [tachiyomiorg/tachiyomi#6474] opened 2022-01-16 10:51 UTC
### Steps to reproduce

Other chapters smooth & other frame rate drop 

### Expected behavior

When I'm going to next chapter makes my phone slow make frame rate drop

### Actual behavior

First smooth i switch to other chapter it depends if going to slow "frame rate drop in game called fps drop" then after i switch when i reading and swipe too slow like low frame rate 25% to down idk then when it comes i already in last page after i  switching to another chapter it depends if its going to smooth or not

### Tachiyomi version

0.12.3

### Android version

9

### Device

Redmi 8a

### Other details

I think this is from app because firsr I though it was on the comics resolution made but second also other manga have I remember the comics/manga & chapter that where I encounter 
frame rate drop and search & the chapter to other apps but its smooth in my phone also I have 2gb ram & 15gb rom storage pls fix on next update

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment] 2022-01-16 12:37
If  you have 32 bit color, please disable, and try.

**Comment by arkon** [comment] 2022-01-16 13:50
Duplicate of #1908

**Closed by arkon** 2022-01-16 13:50 UTC
Labels: Bug
