### ISSUE TITLE
[Bug] "try again" doesn't try again

### ISSUE THREAD

**Issue by hipek3** [tachiyomiorg/tachiyomi#3605] opened 2020-08-05 11:32 UTC
### Device information
* Tachiyomi version: 0.10.3
* Android version: 6.0
* Device: Alcatel Pixi 4

## Steps to reproduce
1. Mass download chapters of any manga
2. Downloading gets stuck at some chapters
3. Go to reading mode and try to read this chapter, some pages will be "Try again"
4. press "Try again" and see nothing happens

### Expected behavior
It should try to download page again.

### Actual behavior
Nothing happens.

### Other details
This issue doesn't seem to be related to extensions since I have tried on few (ie. Mangadex, Paprika, Webtoons). Page won't download until you go to WebView and load chapter that way. It fixes after loading chapter by WebView so it doesn't seem to be problem on my side either.
Downloading mostly bugs when I try to download many chapters at once.

**Comment by arkon** [comment] 2022-07-09 23:28
Duplicate of #3093

**Closed by arkon** 2022-07-09 23:28 UTC
Labels: Bug
