### ISSUE TITLE
[Bug] Scroll Lag

### ISSUE THREAD

**Issue by Scarlet00** [tachiyomiorg/tachiyomi#4742] opened 2021-03-29 19:11 UTC
## Device information
* Tachiyomi version: 0.10.9
* Android version: 11
* Device: Samsung s20+

## Steps to reproduce
1. Open My Fair Footman from any source
2. Set reader mode to webtoon
3. Open chapter 3 then go to transitiong pages between 2 and 3

### Expected behavior
Smooth Scrolling

### Actual behavior
Scrolling lags

## Other details
I think this happens for the webtoons with pictures that are really long that it would only need 2-3 pages. The quality would also be a factor.

**Comment by scb261** [comment] 2021-03-29 23:11
Duplicate of #1908

**Closed** 2021-03-29 23:12 UTC
Labels: bug
