### ISSUE TITLE
[Feature Request] <Add the ability to choose a translator.>

### ISSUE THREAD

**Issue by zhoozhich** [tachiyomiorg/tachiyomi#5402] opened 2021-06-15 23:54 UTC
## Why/User Benefit/User Problem
There is no way to choose a translator. Forces to read manga through the browser.

## What/Requirements
Add the ability to choose a translator.
https://i.imgur.com/JaR9hXf.jpg

(sorry for bad english. i used google translator.)

**Comment by loocool2** [comment] 2021-06-15 23:59
Duplicate of #969

**Closed by loocool2** 2021-06-15 23:59 UTC
Labels: feature
