### ISSUE TITLE
Invalid download location

### ISSUE THREAD

**Issue by iamdboss** [tachiyomiorg/tachiyomi#4126] opened 2020-12-13 18:31 UTC
Sir can you help me how to fix this in downloader? The other manga that i download is good but the other it says "Invalid download location"..

Please help...
![Screenshot_2020-12-14-02-30-23-151_com android chrome](https://user-images.githubusercontent.com/75558174/102020458-5a1a1b00-3db4-11eb-97e3-a9ffb4317a58.jpg)

**Comment by arkon** [comment] 2020-12-13 18:35
Why didn't you fill out any of the requested information?

**Comment by iamdboss** [comment] 2020-12-14 15:35
I download in other extension and it is good but the extension of tsumino is the one and only that didnt download and its says invalid download location..

**Comment by scb261** [comment] 2020-12-14 18:42
When you were opening the issue, there was a template that you should have filled out, but you didn't. Here, copy this and use it as template for your next comment
```
## Device information
* Tachiyomi version: ?
* Android version: ?
* Device: ?

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
This should happen.

### Actual behavior
This happened instead.

## Other details
Additional details and attachments.
```

**Comment by Izumichi** [comment] 2020-12-17 13:07
I have that problem too, i have v10.5 oppo f7 android 10 it sucks but mine gets fixed when i restart my phone

**Comment by dondeepak** [comment] 2020-12-25 15:23
Same problem for me
## Device information
 App version: 1.4.1 (standard, e1e64c79d, 11)
Preview build: 316
Android version: 10 (SDK 29) 
Android build ID: QP1A.190711.020 release-keys
Device brand: vivo
Device manufacturer: vivo
Device name: 1951
Device model: vivo 1951
Device product name: 1951

## Steps to reproduce
1. Download Wizard of Arsenia from Mangakakalot but keep getting error 

### Expected behavior
Have to download without any errors 

### Actual behavior
Cannot download keep getting error invalid download location 

## Other details
Additional details and attachments.
Clear download and added again but keep getting same error 
![Uploading Screenshot_20201225_205130.jpg…]()

**Comment by Wulvenr** [comment] 2021-01-03 02:26
Here's my fix:

1. Check the location of your download location (SDcard or Internal Storage) and see if its full.
2. Free up space, since you cant download if the download location is full

**Comment by dondeepak** [comment] 2021-01-03 03:25
> Here's my fix:
> 
> 1. Check the source of your download location (SDcard or Internal Storage) and see if its full.
> 2. Free up space, since you cant download if the download location is full

I have more than 50gb free space

**Comment by mataha** [comment] 2021-01-06 05:59
> > Here's my fix:
> > 
> > 1. Check the source of your download location (SDcard or Internal Storage) and see if its full.
> > 2. Free up space, since you cant download if the download location is full
> 
> I have more than 50gb free space

Is your download location an external storage (e.g. SD card)?

**Comment by Wulvenr** [comment] 2021-01-06 06:03
> > > Here's my fix:
> > > 
> > > 1. Check the source of your download location (SDcard or Internal Storage) and see if its full.
> > > 2. Free up space, since you cant download if the download location is full
> > 
> > 
> > I have more than 50gb free space
> 
> Is your download location an external storage (e.g. SD card)?

For me at least, I set my download location to the SD card and when I had this problem I checked if my SD card was full; sure enough, it was full, so i cleared upsome space and it was back to working again.

**Comment by eadwu** [comment] 2021-01-17 20:13
I'm not familiar with how apps are sandboxed in Android but download seems to be pretty buggy on my end (0.10.7).

On a clean installation, `/Tachiyomi/downloads` doesn't exist, neither does `/Android/data/en.kanade.tachiyomi/files`. Using `/Tachiyomi/downloads` as the download location gives the following error, `Downloader: Invalid download location`. Using `/Android/data/en.kanade.tachiyomi/files` seems to work right now but before I was getting some kind of `uiFile` error. Using a custom location `/Download/Tachiyomi` results in a working download (what I was using yesterday when the other two wasn't working) but the `Downloaded` filter for the Library didn't work properly when using the custom location (though I could verify the files were present in the download directory), I'm not sure what exactly the problem is, but it only shows the currently downloading series as `Downloaded`. Viewing the manga information view of the series (not being currently downloaded but downloaded before) also doesn't show the `DOWNLOADED` caption.

Using `/Android/data/en.kanade.tachiyomi/files` seems to be resolving all of these problems for me right now, but I'm not sure how I can copy the files over since I can't seem to find that directory in the file manager.

**Comment by scb261** [comment] 2021-01-29 18:48
* Tachiyomi version: 0.10.7
* Android version: 10
* Device: asus rog phone 3 global version

Has 60 GB of free space.
Default download location `storage/emulated/0/Tachiyomi/downloads` returns the `Invalid download location` error when downloading.
Solved by changing download location in settings.

**Comment by arkon** [comment] 2021-05-29 03:01
Closing due to age. If you come across this, open a new issue with crash logs attached (it should contain a more specific error).

**Closed by arkon** 2021-05-29 03:01 UTC
Labels: bug, needs more info
