### ISSUE TITLE
[Bug] <Multiple Delete of Downloaded Chapters Doesn't Work]

### ISSUE THREAD

**Issue by WhiteFury7** [tachiyomiorg/tachiyomi#5431] opened 2021-06-20 01:25 UTC
---

## Device information
* Tachiyomi version: Stable 0.11.1
* Android version: 11
* Device: POCO X3 NFC

## Steps to reproduce
1.  I selected the finished downloaded chapters that would range from 10 to 100+ chapters.
2. Then I would delete them by clicking the delete button after selecting.

### Expected behavior
The downloaded chapters should be deleted instantly and should work.

### Actual behavior
It did not delete the chapters and is encouraging me to delete them one by one. Which is a hassle.....
I also tried it multiple times but it just won't work. 

## Other details
Additional details and attachments.
This started after the 0.10.1 update....
I hope this will be fixed soon, Thank you.

If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.

**Comment by arkon** [comment] 2021-06-20 04:39
Duplicate of #4286

**Closed by arkon** 2021-06-20 04:39 UTC
Labels: bug
