### ISSUE TITLE
Reader Autoplay with customizable speed

### ISSUE THREAD

**Issue by DanielEnricoBotta94** [tachiyomiorg/tachiyomi#5462] opened 2021-06-26 19:02 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

The autoplay should scroll the manga pages automatically and gradually, based on a configurable speed.
It could be slider, on the bottom of the screen when the autoplay is toggled

**Comment by arkon** [comment] 2021-06-26 19:06
Duplicate of #2093

**Closed by arkon** 2021-06-26 19:06 UTC
Labels: Feature request
