### ISSUE TITLE
Webtoon detection reader when opening manhwa/manhua

### ISSUE THREAD

**Issue by Cjojojojo** [tachiyomiorg/tachiyomi#7424] opened 2022-07-01 01:03 UTC
### Describe your suggested feature

Just like the J2k feature, a manhwa or webtoon may open in Webtoon reading mode

### Other details

Automatic webtoon detection

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment] 2022-07-01 03:10
Duplicate of https://github.com/tachiyomiorg/tachiyomi/issues/1664

**Closed by curche** 2022-07-01 03:10 UTC
Labels: Feature request
