### ISSUE TITLE
Local manga interoperability with other Tachiyomi forks

### ISSUE THREAD

**Issue by lasersPew** [tachiyomiorg/tachiyomi#7480] opened 2022-07-09 01:54 UTC
### Describe your suggested feature

Right now, Tachiyomi can only read local manga from ~/tachiyomi/local. this feature request is about reading local manga from other folders made by other forks such as TachiyomiJ2k, TachiyomiSY, etc. Other forks(only tested on J2K) can read local manga from their own designated folders and tachiyomi's designated folder.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-07-09 01:57
Duplicate of #2086

**Closed by arkon** 2022-07-09 01:57 UTC
Labels: Feature request
