### ISSUE TITLE
The ability to change the sharpness of images

### ISSUE THREAD

**Issue by xeleoss** [tachiyomiorg/tachiyomi#8011] opened 2022-09-14 20:48 UTC
In most cases, manga is published in low resolution. Because of this, the manga is too blurry on high-resolution screens. Because of this, it is not very pleasant to read the text. The ability to change the sharpness would allow the reader to choose between blurring and pixelation.

**Comment by loocool2** [comment] 2022-09-14 21:57
Duplicate of #3337

**Closed by loocool2** 2022-09-14 21:57 UTC
Labels: Feature request

**Comment by xeleoss** [comment] 2022-09-15 08:11
@loocool2  how is sharpness related to image magnification?

**Comment by loocool2** [comment] 2022-09-15 09:01
Apologies, this would more accurately be a duplicate of #855
