### ISSUE TITLE
Tachiyomi doesn't update library

### ISSUE THREAD

**Issue by Giokaisha** [tachiyomiorg/tachiyomi#10337] opened 2024-01-07 16:05 UTC
### Steps to reproduce

I updated today and since then my library isn't doing updates. I'm refreshing it but nothing comes in notifications

### Expected behavior

Before update i got notification from app, something like: 5 skipped and notification about new chapters.

### Actual behavior

Notification appears for split second, then disappears. If i refresh them individually it works.

https://github.com/tachiyomiorg/tachiyomi/assets/153280301/8a8da5f4-83bf-4cd9-bb6b-a5b16527dd99

### Tachiyomi version

App version: 0.15.0 (standard, a3ef360, 115, 2024-01-06T15:41Z) 

### Android version

Android version: 12 

### Device

Xiaomi Poco X3 NFC 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Giokaisha** [comment] 2024-01-07 16:09
I wrote version 0.15.0 because i downloaded old version hoping that would fix it but it didn't. Now I'm using 0.15.1

**Comment by Giokaisha** [comment] 2024-01-07 16:09
I wrote version 0.15.0 because i downloaded old version hoping that would fix it but it didn't. Now I'm using 0.15.1

**Comment by arkon** [comment] 2024-01-07 16:37
Duplicate of #10313

**Closed** 2024-01-07 16:37 UTC
Labels: Bug
