### ISSUE TITLE
[Feature Request] display cover only

### ISSUE THREAD

**Issue by StupidWeeb69** [tachiyomiorg/tachiyomi#6544] opened 2022-02-02 06:00 UTC
### Describe your suggested feature

Add cover only on display mode

### Other details

![1643781341203-01](https://user-images.githubusercontent.com/92006101/152101126-29703761-4f9a-4185-9322-8dbb7d1fd812.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-02-02 13:39
Duplicate of #6517

**Closed by arkon** 2022-02-02 13:39 UTC
Labels: Feature request
