### ISSUE TITLE
Filtering "unknown" status

### ISSUE THREAD

**Issue by UNKNONYM0US** [tachiyomiorg/tachiyomi#9784] opened 2023-08-01 06:13 UTC
### Describe your suggested feature

I believe that there are 3 type of statuses, ongoing, completed, and unknown. There's already a "completed" filter feature that shows or hide comics that has completed feature. I was thinking base on from my experiences that some/most comics that has unknown status might have a problem regarding to updating the comics such as changed url, hiatus on the extension source but might not be on the other sites, see the attach image that shows that a comic has stop updating on one extension but not on other extension. With this feature, I believe that it would be easier to identify which comics doesn't get updated even though it has an update
![Screenshot_2023-08-01-13-26-37-94_afd66b7916d19a60815f56273408b73e](https://github.com/tachiyomiorg/tachiyomi/assets/104273959/2802e7a9-09f3-4283-a143-cc5daff08af1)
![Screenshot_2023-08-01-13-25-27-80_afd66b7916d19a60815f56273408b73e](https://github.com/tachiyomiorg/tachiyomi/assets/104273959/9f17e2aa-acfd-4aec-9183-86cb6664c9b2)

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by UNKNONYM0US** [comment] 2023-08-01 06:16
Found a feature request similar to mine

**Comment by THElegend5** [comment] 2023-08-01 10:33
Duplicate of #6163

**Closed** 2023-08-01 11:34 UTC
Labels: Feature request
