### ISSUE TITLE
Backing Up Custom Manga Covers

### ISSUE THREAD

**Issue by Paradox3759** [tachiyomiorg/tachiyomi#7693] opened 2022-08-06 13:24 UTC
### Describe your suggested feature

For now, Tachiyomi only backs up Custom Manga details , description, etc. and restores them on another device or another fork. It would be great if we get an option to backup custom covers set on a specific Manga as well. A backup option of custom covers would be nice for people who likes to see a clear library with their original covers, not low resolution & low quality covers or manga's first page used as covers from different extension.

I'm aware it will increase the backup size by a lot but that's why I'm asking it as an option feature for those who want to use.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-08-06 14:13
Duplicate of #5836

**Closed by arkon** 2022-08-06 14:13 UTC
Labels: Feature request
