### ISSUE TITLE
Per-category update frequency

### ISSUE THREAD

**Issue by 9cxndy** [tachiyomiorg/tachiyomi#6698] opened 2022-02-24 15:11 UTC
### Describe your suggested feature

I have a really big library, and every time I update it I am basically swarming the source website with requests, which is bad.

So instead of update everything all at once, once per update interval; maybe tachiyomi can spread it out into multiple chunks across the whole update interval. The number of chunks could be made configurable.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by RobindaCoast** [comment] 2022-02-25 12:50
This is a good idea, my library has gotten so big to the point that I have to manually update over half of it!

**Comment by ZekkenID** [comment] 2022-03-02 21:06
Hey dude you can go to settings then open library. You can choose category What you want to get updated. Just little actions

**Comment by ZekkenID** [comment] 2022-03-02 21:10
![IMG_20220303_060854](https://user-images.githubusercontent.com/23666289/156450217-0a99981b-1c31-4a9d-a152-656732f3c140.jpg)

**Comment by yshui** [comment] 2022-03-30 09:16
@ZekkenID how is this relevant? i want to update all of my library.

**Comment by yshui** [comment] 2022-03-30 09:19
@ZekkenID how is this related to this issue? what if i as the user want to update my whole library?

**Comment by arkon** [comment] 2022-04-04 21:44
Duplicate of #822

**Closed by arkon** 2022-04-04 21:44 UTC
Labels: Feature request
