### ISSUE TITLE
Library dedup check

### ISSUE THREAD

**Issue by Saud-97** [tachiyomiorg/tachiyomi#7215] opened 2022-05-28 16:23 UTC
### Describe your suggested feature

Feature to show you which manga you have duplicated and to allow you to select a primary one and remove the other dups.

Very useful for people who have a large library that got created prior implementing the dedup detection feature on library add.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-06-10 13:42
Duplicate of #3596

This app isn't really designed for hoarders.

**Closed by arkon** 2022-06-10 13:42 UTC
Labels: Feature request
