### ISSUE TITLE
Tachiyomi is not responding

### ISSUE THREAD

**Issue by raffyOmega** [tachiyomiorg/tachiyomi#5499] opened 2021-07-03 22:46 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

latest  version

### Android version

11

### Device

vivo y11

### Steps to reproduce

no comment

### Expected behavior

I already achieve the system requiremnts, try to clear the cache but still the app still crash

### Actual behavior

hello admin, any kind of way how to fix this? Whenever I want to read manhua/manwha that has short page like "1/5" it will always crash or not responding or sometimes the scrolling the page will be laggy or slow motion in short.

### Crash logs

![208425663_502394417695078_5229376534607938717_n](https://user-images.githubusercontent.com/85740732/124368353-00ffcf00-dc93-11eb-887f-df5435d9e973.jpg)

### Other details

hello admin, any kind of way how to fix this? Whenever I want to read manhua/manwha that has short page like "1/5" it will always crash or not responding or sometimes the scrolling the page will be laggy or slow motion in short.

**Comment by arkon** [comment] 2021-07-04 16:21
Probably duplicate of #1908.

**Closed by arkon** 2021-07-04 16:21 UTC
Labels: Bug
