### ISSUE TITLE
[Little Issue] Little lag when one scrolls fast in the chapter list

### ISSUE THREAD

**Issue by Palloxin** [tachiyomiorg/tachiyomi#8744] opened 2022-12-15 00:20 UTC
### Steps to reproduce

https://user-images.githubusercontent.com/75091899/207743368-79410ed7-a605-47c2-9df4-c74e338f41ca.mp4

### Expected behavior

Scrolling visually smooth

### Actual behavior

Fast scroll in the chapter list is a bit laggy

### Tachiyomi version

0.14.2

### Android version

Android 8 Miui 8

### Device

Huawei p8 lite 2017

### Other details

In the video watch the scroll bar, it lags a bit

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-12-15 04:22
Duplicate of #8310; we'll continue optimizing/bringing in framework improvements as they get released.

**Closed by arkon** 2022-12-15 04:22 UTC
Labels: Bug
