### ISSUE TITLE
Add an ability to disable the reader menu appearing after the last manga page

### ISSUE THREAD

**Issue by Helltraitor** [tachiyomiorg/tachiyomi#7001] opened 2022-04-24 13:39 UTC
### Describe your suggested feature

After user reaches the last page the reader menu appears. There is no problem to show menu for horizontal manga, but for vertical it may occur ux issues. For example, when I reach last page in webtoon the reader menu appears and I tap at the middle of page progress bar and jump up to the already read manga page - that is very annoying

My request is the option in reader setting for disabling this behavior (As for me I never used menu when I was reaching the las page)

### Other details

Screen recording of the reader menu appearing

https://user-images.githubusercontent.com/95148327/164979043-728e4e09-0ad1-4eb2-be20-25b07d2ca5e4.mp4

Screen recording of jumps when the reader menu appears (example close to reality)

https://user-images.githubusercontent.com/95148327/164979193-2fabb832-7186-489d-9e17-7e18e2f29ee6.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-07-10 03:33
Sort of a duplicate of #7242

**Closed by arkon** 2022-07-10 03:33 UTC
Labels: Feature request
