### ISSUE TITLE
Error: App closes while updating chapters.

### ISSUE THREAD

**Issue by Davehydroman** [tachiyomiorg/tachiyomi#10113] opened 2023-11-05 21:00 UTC
### Steps to reproduce

1.- Refreshing list to update chapters.
2.- Chapters start to update.
3.- The app closes and stops completely.
4.- Creates and error log.
5.- I clear cache and WebView history. 
6.- Update again and app closes again.

### Expected behavior

Chapters update without app closing 

### Actual behavior

App closes completely while updating chapters.

### Crash logs
```
--------- beginning of main
11-05 14:32:31.168 11402 11439 E perf_hint: Session creation failed, mPreferredRateNanos: -1
11-05 14:32:33.170 11402 11439 E perf_hint: Session creation failed, mPreferredRateNanos: -1
11-05 14:32:55.751 11402 11439 E perf_hint: Session creation failed, mPreferredRateNanos: -1
11-05 14:32:57.774 11402 11439 E perf_hint: Session creation failed, mPreferredRateNanos: -1
11-05 14:32:59.778 11402 11439 E perf_hint: Session creation failed, mPreferredRateNanos: -1
11-05 14:33:01.814 11402 11439 E perf_hint: Session creation failed, mPreferredRateNanos: -1
11-05 14:33:08.338 11402 11439 E perf_hint: Session creation failed, mPreferredRateNanos: -1
11-05 14:33:57.182 26582 26626 E SQLiteLog: (283) recovered 178 frames from WAL file /data/user/0/eu.kanade.tachiyomi/databases/tachiyomi.db-wal
11-05 14:33:57.235 26582 26635 E chromium: [1105/143357.234975:ERROR:variations_seed_loader.cc(69)] Failed to open file for reading. Errno: 2
11-05 14:33:57.235 26582 26635 E chromium: [1105/143357.235416:ERROR:variations_seed_loader.cc(69)] Failed to open file for reading. Errno: 2
11-05 14:33:57.559 26582 26628 E libEGL  : pre_cache appList: ,,
11-05 14:33:57.806 26582 26660 E SQLiteLog: (284) automatic index on C(manga_id)
11-05 14:33:57.806 26582 26660 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
11-05 14:33:58.242 26582 26628 E libEGL  : pre_cache appList: ,,
11-05 14:33:58.289 26582 26628 E LB      : fail to open node: No such file or directory
11-05 14:33:58.290 26582 26628 E perf_hint: Session creation failed, mPreferredRateNanos: -1
11-05 14:34:12.614 26582 26628 E perf_hint: Session creation failed, mPreferredRateNanos: -1
11-05 14:34:12.783 26582 26628 E perf_hint: Session creation failed, mPreferredRateNanos: -1
11-05 14:34:30.551 26582 26628 E perf_hint: Session creation failed, mPreferredRateNanos: -1
11-05 14:34:30.612 26582 26628 E perf_hint: Session creation failed, mPreferredRateNanos: -1
11-05 14:34:47.194 26582 26628 E perf_hint: Session creation failed, mPreferredRateNanos: -1
11-05 14:34:47.385 26582 26628 E perf_hint: Session creation failed, mPreferredRateNanos: -1
11-05 14:39:43.375 26582 26628 E perf_hint: Session creation failed, mPreferredRateNanos: -1
11-05 14:39:46.149 26582 26628 E perf_hint: Session creation failed, mPreferredRateNanos: -1
11-05 14:39:47.322 26582 26628 E perf_hint: Session creation failed, mPreferredRateNanos: -1
11-05 14:40:30.338 26582 26582 E chromium: [ERROR:aw_browser_terminator.cc(156)] Renderer process (28553) crash detected (code -1).
11-05 14:42:10.434 26582 26628 E perf_hint: Session creation failed, mPreferredRateNanos: -1
11-05 14:42:57.219 26582 26582 E chromium: [ERROR:aw_browser_terminator.cc(156)] Renderer process (30205) crash detected (code -1).
11-05 14:47:17.922 26582 26791 E CursorWindow: Failed to read row 2160, column 0 from a CursorWindow which has 2160 rows, 14 columns.
11-05 14:47:30.644 26582 30153 E CursorWindow: Failed to read row 2160, column 0 from a CursorWindow which has 2160 rows, 14 columns.
11-05 14:47:30.650 26582 26582 E ACRA    : ACRA caught a NullPointerException for eu.kanade.tachiyomi
11-05 14:47:30.650 26582 26582 E ACRA    : java.lang.NullPointerException
11-05 14:47:30.650 26582 26582 E ACRA    : 	at tachiyomi.data.data.UpdatesViewQueriesImpl$updates$1.invoke(DatabaseImpl.kt:19)
11-05 14:47:30.650 26582 26582 E ACRA    : 	at com.squareup.sqldelight.Query.executeAsList(Query.kt:18)
11-05 14:47:30.650 26582 26582 E ACRA    : 	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToList$1$1.invokeSuspend(FlowExtensions.kt:6)
11-05 14:47:30.650 26582 26582 E ACRA    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
11-05 14:47:30.650 26582 26582 E ACRA    : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
11-05 14:47:30.650 26582 26582 E ACRA    : 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
11-05 14:47:30.650 26582 26582 E ACRA    : 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
11-05 14:47:30.650 26582 26582 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
11-05 14:47:30.650 26582 26582 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:63)
11-05 14:47:30.650 26582 26582 E ACRA    : 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@5f100e6, Dispatchers.Main.immediate]
11-05 14:47:31.392 31466 31504 E SQLiteLog: (283) recovered 255 frames from WAL file /data/user/0/eu.kanade.tachiyomi/databases/tachiyomi.db-wal
11-05 14:47:31.523 31466 31566 E chromium: [1105/144731.522376:ERROR:variations_seed_loader.cc(69)] Failed to open file for reading. Errno: 2
11-05 14:47:37.666 31781 31819 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
11-05 14:47:38.003 31781 31821 E libEGL  : pre_cache appList: ,,
11-05 14:47:38.228 31781 31855 E SQLiteLog: (284) automatic index on C(manga_id)
11-05 14:47:38.228 31781 31855 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
11-05 14:47:38.672 31781 31821 E LB      : fail to open node: No such file or directory
11-05 14:47:38.673 31781 31821 E perf_hint: Session creation failed, mPreferredRateNanos: -1
App version: 0.14.7 (standard, c8d6859, 102, 2023-10-25T16:11Z)
Android version: 13 (SDK 33)
Android build ID: TKQ1.221114.001 test-keys
Device brand: POCO
Device manufacturer: Xiaomi
Device name: redwood
Device model: 22101320G
Device product name: redwood_global
```

### Tachiyomi version

O.14.7

### Android version

Android 13

### Device

Poco 5X Pro

### Other details

The problem persists since 3 days ago. After that, It worked perfectly.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-11-05 21:01
Duplicate of #8400

**Closed by arkon** 2023-11-05 21:01 UTC
Labels: Bug
