### ISSUE TITLE
Forced Close When Migrate

### ISSUE THREAD

**Issue by MoXerous** [tachiyomiorg/tachiyomi#10092] opened 2023-10-31 14:53 UTC
### Steps to reproduce

1. Click on the Browse section
2. Go to migrate
3. I'm trying to migrate from Manga Startz source to Mangalek (مانجا ليك)
4. Migrate a manga
5. After Migrated The App Shutdown (Force Close)

### Expected behavior

The App should continue working

### Actual behavior

The App Shutdown (Force Close)

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/13217891/tachiyomi_crash_logs.txt)

### Tachiyomi version

0.14.7

### Android version

Android 10

### Device

Samsung galaxy note 9 (SM-N960F)

### Other details

App version: 0.14.7 (standard, c8d6859, 102, 2023-10-25T16:11Z)
Android version: 10 (SDK 29)
Android build ID: QP1A.190711.020.N960FXXU9FVK1
Device brand: samsung
Device manufacturer: samsung
Device name: crownlte
Device model: SM-N960F
Device product name: crownltexx

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-11-02 13:12
```
10-31 17:41:07.648  7889  7889 E ACRA    : java.lang.NullPointerException
10-31 17:41:07.648  7889  7889 E ACRA    : 	at tachiyomi.data.data.UpdatesViewQueriesImpl$updates$1.invoke(DatabaseImpl.kt:19)
10-31 17:41:07.648  7889  7889 E ACRA    : 	at com.squareup.sqldelight.Query.executeAsList(Query.kt:18)
10-31 17:41:07.648  7889  7889 E ACRA    : 	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToList$1$1.invokeSuspend(FlowExtensions.kt:6)
10-31 17:41:07.648  7889  7889 E ACRA    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
10-31 17:41:07.648  7889  7889 E ACRA    : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
10-31 17:41:07.648  7889  7889 E ACRA    : 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
10-31 17:41:07.648  7889  7889 E ACRA    : 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
10-31 17:41:07.648  7889  7889 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
10-31 17:41:07.648  7889  7889 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:63)
10-31 17:41:07.648  7889  7889 E ACRA    : 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@e47ad04, Dispatchers.Main.immediate]
```

**Comment by arkon** [comment] 2023-11-02 13:12
Duplicate of #8400

**Closed by arkon** 2023-11-02 13:12 UTC
Labels: Bug
