### ISSUE TITLE
[Feature Request] Save Filter Setting

### ISSUE THREAD

**Issue by Goharn** [tachiyomiorg/tachiyomi#3026] opened 2020-05-02 04:37 UTC
Hey, 
I was thinking if we could get an option to save the filter settings instead of it getting reset everytime we open browse. 

Thanks!

**Comment by Jaykoerner** [comment] 2020-06-27 18:16
Agreed

**Comment by arkon** [comment] 2021-01-04 21:52
Duplicate of #1484

**Closed by arkon** 2021-01-04 21:52 UTC
Labels: feature
