### ISSUE TITLE
Migrate page UI crashes

### ISSUE THREAD

**Issue by TechyAditya** [tachiyomiorg/tachiyomi#10228] opened 2023-12-11 19:08 UTC
### Steps to reproduce

1. Have any 2 sourced extensions installed (in my case, mangareader and toonily)
2. Open migrate tab
3. Open extension number 1. -> List renders
4. Press back and open extension number 2 instantaneously. -> It crashes

### Expected behavior

Expected to open migrate page without issues 

### Actual behavior

App crashes

### Crash logs

--------- beginning of main
12-12 00:18:31.022 20809 20875 E anade.tachiyomi: No package ID 7a found for ID 0x7a0b0007.
12-12 00:18:31.022 20809 20875 E anade.tachiyomi: No package ID 7a found for ID 0x7a0b0007.
12-12 00:18:31.484 20809 20845 E SQLiteLog: (284) automatic index on C(manga_id)
12-12 00:18:31.484 20809 20845 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
12-12 00:29:34.934 20809 20809 E ACRA    : ACRA caught a IllegalArgumentException for eu.kanade.tachiyomi
12-12 00:29:34.934 20809 20809 E ACRA    : java.lang.IllegalArgumentException: Key eu.kanade.tachiyomi.ui.browse.migration.manga.MigrationMangaScreen:transition:lifecycle was used multiple times 
12-12 00:29:34.934 20809 20809 E ACRA    : 	at androidx.compose.runtime.saveable.SaveableStateHolderImpl$SaveableStateProvider$1$1.invoke(SaveableStateHolder.kt:71)
12-12 00:29:34.934 20809 20809 E ACRA    : 	at androidx.compose.runtime.DisposableEffectImpl.onRemembered(Effects.kt:7)
12-12 00:29:34.934 20809 20809 E ACRA    : 	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:94)
12-12 00:29:34.934 20809 20809 E ACRA    : 	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:81)
12-12 00:29:34.934 20809 20809 E ACRA    : 	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:6)
12-12 00:29:34.934 20809 20809 E ACRA    : 	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:218)
12-12 00:29:34.934 20809 20809 E ACRA    : 	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:9)
12-12 00:29:34.934 20809 20809 E ACRA    : 	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:34)
12-12 00:29:34.934 20809 20809 E ACRA    : 	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:13)
12-12 00:29:34.934 20809 20809 E ACRA    : 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1299)
12-12 00:29:34.934 20809 20809 E ACRA    : 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
12-12 00:29:34.934 20809 20809 E ACRA    : 	at android.view.Choreographer.doCallbacks(Choreographer.java:923)
12-12 00:29:34.934 20809 20809 E ACRA    : 	at android.view.Choreographer.doFrame(Choreographer.java:847)
12-12 00:29:34.934 20809 20809 E ACRA    : 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
12-12 00:29:34.934 20809 20809 E ACRA    : 	at android.os.Handler.handleCallback(Handler.java:942)
12-12 00:29:34.934 20809 20809 E ACRA    : 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-12 00:29:34.934 20809 20809 E ACRA    : 	at android.os.Looper.loopOnce(Looper.java:226)
12-12 00:29:34.934 20809 20809 E ACRA    : 	at android.os.Looper.loop(Looper.java:313)
12-12 00:29:34.934 20809 20809 E ACRA    : 	at android.app.ActivityThread.main(ActivityThread.java:8762)
12-12 00:29:34.934 20809 20809 E ACRA    : 	at java.lang.reflect.Method.invoke(Native Method)
12-12 00:29:34.934 20809 20809 E ACRA    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
12-12 00:29:34.934 20809 20809 E ACRA    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
12-12 00:29:34.934 20809 20809 E ACRA    : 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@11a655f, androidx.compose.ui.platform.MotionDurationScaleImpl@99a4bac, StandaloneCoroutine{Cancelling}@cc8d075, AndroidUiDispatcher@82980a]
12-12 00:29:36.848 27689 27730 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
12-12 00:29:36.882 27689 27750 E chromium: [1212/002936.881851:ERROR:variations_seed_loader.cc(37)] Seed missing signature.
12-12 00:29:36.896 27689 27748 E anade.tachiyomi: No package ID 7a found for ID 0x7a0b0007.
12-12 00:29:36.897 27689 27748 E anade.tachiyomi: No package ID 7a found for ID 0x7a0b0007.
12-12 00:29:37.217 27689 27784 E SQLiteLog: (284) automatic index on C(manga_id)
12-12 00:29:37.217 27689 27784 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
12-12 00:29:45.504 27689 27689 E ACRA    : ACRA caught a IllegalArgumentException for eu.kanade.tachiyomi
12-12 00:29:45.504 27689 27689 E ACRA    : java.lang.IllegalArgumentException: Key eu.kanade.tachiyomi.ui.browse.migration.manga.MigrationMangaScreen:transition:lifecycle was used multiple times 
12-12 00:29:45.504 27689 27689 E ACRA    : 	at androidx.compose.runtime.saveable.SaveableStateHolderImpl$SaveableStateProvider$1$1.invoke(SaveableStateHolder.kt:71)
12-12 00:29:45.504 27689 27689 E ACRA    : 	at androidx.compose.runtime.DisposableEffectImpl.onRemembered(Effects.kt:7)
12-12 00:29:45.504 27689 27689 E ACRA    : 	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:94)
12-12 00:29:45.504 27689 27689 E ACRA    : 	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:81)
12-12 00:29:45.504 27689 27689 E ACRA    : 	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:6)
12-12 00:29:45.504 27689 27689 E ACRA    : 	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:218)
12-12 00:29:45.504 27689 27689 E ACRA    : 	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:9)
12-12 00:29:45.504 27689 27689 E ACRA    : 	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:34)
12-12 00:29:45.504 27689 27689 E ACRA    : 	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:13)
12-12 00:29:45.504 27689 27689 E ACRA    : 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1299)
12-12 00:29:45.504 27689 27689 E ACRA    : 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
12-12 00:29:45.504 27689 27689 E ACRA    : 	at android.view.Choreographer.doCallbacks(Choreographer.java:923)
12-12 00:29:45.504 27689 27689 E ACRA    : 	at android.view.Choreographer.doFrame(Choreographer.java:847)
12-12 00:29:45.504 27689 27689 E ACRA    : 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
12-12 00:29:45.504 27689 27689 E ACRA    : 	at android.os.Handler.handleCallback(Handler.java:942)
12-12 00:29:45.504 27689 27689 E ACRA    : 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-12 00:29:45.504 27689 27689 E ACRA    : 	at android.os.Looper.loopOnce(Looper.java:226)
12-12 00:29:45.504 27689 27689 E ACRA    : 	at android.os.Looper.loop(Looper.java:313)
12-12 00:29:45.504 27689 27689 E ACRA    : 	at android.app.ActivityThread.main(ActivityThread.java:8762)
12-12 00:29:45.504 27689 27689 E ACRA    : 	at java.lang.reflect.Method.invoke(Native Method)
12-12 00:29:45.504 27689 27689 E ACRA    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
12-12 00:29:45.504 27689 27689 E ACRA    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
12-12 00:29:45.504 27689 27689 E ACRA    : 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@3649586, androidx.compose.ui.platform.MotionDurationScaleImpl@306ae47, StandaloneCoroutine{Cancelling}@4dc0674, AndroidUiDispatcher@d5e479d]
12-12 00:29:47.136 27914 27951 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
12-12 00:29:47.152 27914 27959 E chromium: [1212/002947.152658:ERROR:variations_seed_loader.cc(37)] Seed missing signature.
12-12 00:29:47.161 27914 27954 E anade.tachiyomi: No package ID 7a found for ID 0x7a0b0007.
12-12 00:29:47.161 27914 27954 E anade.tachiyomi: No package ID 7a found for ID 0x7a0b0007.
12-12 00:29:47.538 27914 27990 E SQLiteLog: (284) automatic index on C(manga_id)
12-12 00:29:47.538 27914 27990 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
12-12 00:29:54.217 27914 27914 E ACRA    : ACRA caught a IllegalArgumentException for eu.kanade.tachiyomi
12-12 00:29:54.217 27914 27914 E ACRA    : java.lang.IllegalArgumentException: Key eu.kanade.tachiyomi.ui.browse.migration.manga.MigrationMangaScreen:transition:lifecycle was used multiple times 
12-12 00:29:54.217 27914 27914 E ACRA    : 	at androidx.compose.runtime.saveable.SaveableStateHolderImpl$SaveableStateProvider$1$1.invoke(SaveableStateHolder.kt:71)
12-12 00:29:54.217 27914 27914 E ACRA    : 	at androidx.compose.runtime.DisposableEffectImpl.onRemembered(Effects.kt:7)
12-12 00:29:54.217 27914 27914 E ACRA    : 	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:94)
12-12 00:29:54.217 27914 27914 E ACRA    : 	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:81)
12-12 00:29:54.217 27914 27914 E ACRA    : 	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:6)
12-12 00:29:54.217 27914 27914 E ACRA    : 	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:218)
12-12 00:29:54.217 27914 27914 E ACRA    : 	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:9)
12-12 00:29:54.217 27914 27914 E ACRA    : 	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:34)
12-12 00:29:54.217 27914 27914 E ACRA    : 	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:13)
12-12 00:29:54.217 27914 27914 E ACRA    : 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1299)
12-12 00:29:54.217 27914 27914 E ACRA    : 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
12-12 00:29:54.217 27914 27914 E ACRA    : 	at android.view.Choreographer.doCallbacks(Choreographer.java:923)
12-12 00:29:54.217 27914 27914 E ACRA    : 	at android.view.Choreographer.doFrame(Choreographer.java:847)
12-12 00:29:54.217 27914 27914 E ACRA    : 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
12-12 00:29:54.217 27914 27914 E ACRA    : 	at android.os.Handler.handleCallback(Handler.java:942)
12-12 00:29:54.217 27914 27914 E ACRA    : 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-12 00:29:54.217 27914 27914 E ACRA    : 	at android.os.Looper.loopOnce(Looper.java:226)
12-12 00:29:54.217 27914 27914 E ACRA    : 	at android.os.Looper.loop(Looper.java:313)
12-12 00:29:54.217 27914 27914 E ACRA    : 	at android.app.ActivityThread.main(ActivityThread.java:8762)
12-12 00:29:54.217 27914 27914 E ACRA    : 	at java.lang.reflect.Method.invoke(Native Method)
12-12 00:29:54.217 27914 27914 E ACRA    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
12-12 00:29:54.217 27914 27914 E ACRA    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
12-12 00:29:54.217 27914 27914 E ACRA    : 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@d7b035b, androidx.compose.ui.platform.MotionDurationScaleImpl@bc857f8, StandaloneCoroutine{Cancelling}@eb34d1, AndroidUiDispatcher@8e35b36]
12-12 00:29:55.724 28104 28139 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
12-12 00:29:55.754 28104 28137 E anade.tachiyomi: No package ID 7a found for ID 0x7a0b0007.
12-12 00:29:55.755 28104 28137 E anade.tachiyomi: No package ID 7a found for ID 0x7a0b0007.
12-12 00:29:55.759 28104 28137 E FA      : Failed to load metadata: Package name not found: android.content.pm.PackageManager$NameNotFoundException: org.chromium.chrome: m.dr.a(:com.google.android.gms.dynamite_measurementdynamite@234855039@23.48.55 (190408-0):7)
12-12 00:29:55.759 28104 28137 E FA      : Failed to load metadata: Metadata bundle is null
12-12 00:29:55.760 28104 28146 E chromium: [1212/002955.759101:ERROR:variations_seed_loader.cc(37)] Seed missing signature.
12-12 00:29:56.155 28104 28174 E SQLiteLog: (284) automatic index on C(manga_id)
12-12 00:29:56.155 28104 28174 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
12-12 00:30:09.289 28104 28104 E ACRA    : ACRA caught a IllegalArgumentException for eu.kanade.tachiyomi
12-12 00:30:09.289 28104 28104 E ACRA    : java.lang.IllegalArgumentException: Key eu.kanade.tachiyomi.ui.browse.migration.manga.MigrationMangaScreen:transition:lifecycle was used multiple times 
12-12 00:30:09.289 28104 28104 E ACRA    : 	at androidx.compose.runtime.saveable.SaveableStateHolderImpl$SaveableStateProvider$1$1.invoke(SaveableStateHolder.kt:71)
12-12 00:30:09.289 28104 28104 E ACRA    : 	at androidx.compose.runtime.DisposableEffectImpl.onRemembered(Effects.kt:7)
12-12 00:30:09.289 28104 28104 E ACRA    : 	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:94)
12-12 00:30:09.289 28104 28104 E ACRA    : 	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:81)
12-12 00:30:09.289 28104 28104 E ACRA    : 	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:6)
12-12 00:30:09.289 28104 28104 E ACRA    : 	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:218)
12-12 00:30:09.289 28104 28104 E ACRA    : 	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:9)
12-12 00:30:09.289 28104 28104 E ACRA    : 	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:34)
12-12 00:30:09.289 28104 28104 E ACRA    : 	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:13)
12-12 00:30:09.289 28104 28104 E ACRA    : 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1299)
12-12 00:30:09.289 28104 28104 E ACRA    : 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
12-12 00:30:09.289 28104 28104 E ACRA    : 	at android.view.Choreographer.doCallbacks(Choreographer.java:923)
12-12 00:30:09.289 28104 28104 E ACRA    : 	at android.view.Choreographer.doFrame(Choreographer.java:847)
12-12 00:30:09.289 28104 28104 E ACRA    : 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
12-12 00:30:09.289 28104 28104 E ACRA    : 	at android.os.Handler.handleCallback(Handler.java:942)
12-12 00:30:09.289 28104 28104 E ACRA    : 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-12 00:30:09.289 28104 28104 E ACRA    : 	at android.os.Looper.loopOnce(Looper.java:226)
12-12 00:30:09.289 28104 28104 E ACRA    : 	at android.os.Looper.loop(Looper.java:313)
12-12 00:30:09.289 28104 28104 E ACRA    : 	at android.app.ActivityThread.main(ActivityThread.java:8762)
12-12 00:30:09.289 28104 28104 E ACRA    : 	at java.lang.reflect.Method.invoke(Native Method)
12-12 00:30:09.289 28104 28104 E ACRA    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
12-12 00:30:09.289 28104 28104 E ACRA    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
12-12 00:30:09.289 28104 28104 E ACRA    : 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@dfc01f9, androidx.compose.ui.platform.MotionDurationScaleImpl@c7ce53e, StandaloneCoroutine{Cancelling}@afaaf9f, AndroidUiDispatcher@23968ec]
12-12 00:30:10.740 28304 28379 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
12-12 00:30:10.774 28304 28383 E anade.tachiyomi: No package ID 7a found for ID 0x7a0b0007.
12-12 00:30:10.774 28304 28383 E anade.tachiyomi: No package ID 7a found for ID 0x7a0b0007.
12-12 00:30:10.791 28304 28405 E chromium: [1212/003010.791496:ERROR:variations_seed_loader.cc(37)] Seed missing signature.
12-12 00:30:11.107 28304 28418 E SQLiteLog: (284) automatic index on C(manga_id)
12-12 00:30:11.107 28304 28418 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
12-12 00:30:15.867 28304 28304 E ACRA    : ACRA caught a IllegalArgumentException for eu.kanade.tachiyomi
12-12 00:30:15.867 28304 28304 E ACRA    : java.lang.IllegalArgumentException: Key eu.kanade.tachiyomi.ui.browse.migration.manga.MigrationMangaScreen:transition:lifecycle was used multiple times 
12-12 00:30:15.867 28304 28304 E ACRA    : 	at androidx.compose.runtime.saveable.SaveableStateHolderImpl$SaveableStateProvider$1$1.invoke(SaveableStateHolder.kt:71)
12-12 00:30:15.867 28304 28304 E ACRA    : 	at androidx.compose.runtime.DisposableEffectImpl.onRemembered(Effects.kt:7)
12-12 00:30:15.867 28304 28304 E ACRA    : 	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:94)
12-12 00:30:15.867 28304 28304 E ACRA    : 	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:81)
12-12 00:30:15.867 28304 28304 E ACRA    : 	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:6)
12-12 00:30:15.867 28304 28304 E ACRA    : 	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:218)
12-12 00:30:15.867 28304 28304 E ACRA    : 	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:9)
12-12 00:30:15.867 28304 28304 E ACRA    : 	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:34)
12-12 00:30:15.867 28304 28304 E ACRA    : 	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:13)
12-12 00:30:15.867 28304 28304 E ACRA    : 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1299)
12-12 00:30:15.867 28304 28304 E ACRA    : 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
12-12 00:30:15.867 28304 28304 E ACRA    : 	at android.view.Choreographer.doCallbacks(Choreographer.java:923)
12-12 00:30:15.867 28304 28304 E ACRA    : 	at android.view.Choreographer.doFrame(Choreographer.java:847)
12-12 00:30:15.867 28304 28304 E ACRA    : 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
12-12 00:30:15.867 28304 28304 E ACRA    : 	at android.os.Handler.handleCallback(Handler.java:942)
12-12 00:30:15.867 28304 28304 E ACRA    : 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-12 00:30:15.867 28304 28304 E ACRA    : 	at android.os.Looper.loopOnce(Looper.java:226)
12-12 00:30:15.867 28304 28304 E ACRA    : 	at android.os.Looper.loop(Looper.java:313)
12-12 00:30:15.867 28304 28304 E ACRA    : 	at android.app.ActivityThread.main(ActivityThread.java:8762)
12-12 00:30:15.867 28304 28304 E ACRA    : 	at java.lang.reflect.Method.invoke(Native Method)
12-12 00:30:15.867 28304 28304 E ACRA    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
12-12 00:30:15.867 28304 28304 E ACRA    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
12-12 00:30:15.867 28304 28304 E ACRA    : 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@dc10dbf, androidx.compose.ui.platform.MotionDurationScaleImpl@e1d3c8c, StandaloneCoroutine{Cancelling}@b2d9fd5, AndroidUiDispatcher@cde23ea]
12-12 00:30:17.332 28546 28582 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
12-12 00:30:17.356 28546 28581 E anade.tachiyomi: No package ID 7a found for ID 0x7a0b0007.
12-12 00:30:17.356 28546 28581 E anade.tachiyomi: No package ID 7a found for ID 0x7a0b0007.
12-12 00:30:17.360 28546 28591 E chromium: [1212/003017.360274:ERROR:variations_seed_loader.cc(37)] Seed missing signature.
12-12 00:30:17.701 28546 28608 E SQLiteLog: (284) automatic index on C(manga_id)
12-12 00:30:17.701 28546 28608 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.14.7 (standard, c8d6859, 102, 2023-10-25T16:11Z)
Android version: 13 (SDK 33)
Android build ID: TP1A.220624.014.G990EXXS7EWK2
Device brand: samsung
Device manufacturer: samsung
Device name: r9s
Device model: SM-G990E
Device product name: r9sxxx

### Tachiyomi version

0.14.7

### Android version

Android 12, OneUI 5.1

### Device

Samsung Galaxy S21 FE (Exynos)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-12-12 02:42
Duplicate of #9352

**Closed by arkon** 2023-12-12 02:42 UTC
Labels: Bug
