### ISSUE TITLE
Cut x pages out of start of chapter

### ISSUE THREAD

**Issue by OrestesK** [tachiyomiorg/tachiyomi#8754] opened 2022-12-17 01:47 UTC
### Describe your suggested feature

Add an option for the current manga to set a **manual** number of pages that should not be displayed/loaded. For example, if set to 2, the first 2 pages would be skipped within **each** chapter.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment] 2022-12-17 02:33
Duplicate of https://github.com/tachiyomiorg/tachiyomi/issues/3228

**Closed by curche** 2022-12-17 02:33 UTC
Labels: Feature request
