### ISSUE TITLE
[Bug] crashing

### ISSUE THREAD

**Issue by darker1046** [tachiyomiorg/tachiyomi#5029] opened 2021-05-06 05:36 UTC
So, I came here for help, just updated and, now, my webtoons are chashig the app as soon as I open them, don't  know what  version I was before but it didn't happen, can't even open old ones, tried some sujetions (split chapters/side padding) but nothing helped,  i apreciate any help, even just teaching me how to rollback because i tried and it says app not installed 

## Device information
* Tachiyomi version: 10.12
* Android version: 10
* Device: galaxy tab A

## Steps to reproduce
1. open any webtoon
2. thats it

### Expected behavior
load images

### Actual behavior
crashes and closes

## Other details
- beginning of main
05-06 01:48:02.334 22218 22218 E DecorView: mWindow.mActivityCurrentConfig is null
05-06 01:48:02.368 22218 22218 E DecorView: mWindow.mActivityCurrentConfig is null
05-06 01:48:03.857 22218 22218 E ViewRootImpl: sendUserActionEvent() mView returned.
05-06 01:48:41.668 25601 25601 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
05-06 01:48:42.918 25601 27539 E SQLiteLog: (284) automatic index on C(manga_id)
05-06 01:48:42.918 25601 27539 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
05-06 01:49:07.186 25601 25601 E DecorView: mWindow.mActivityCurrentConfig is null
05-06 01:49:07.228 25601 25601 E DecorView: mWindow.mActivityCurrentConfig is null
05-06 01:49:08.880 25601 25601 E ViewRootImpl: sendUserActionEvent() mView returned.
05-06 01:51:07.263 26695 26695 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
05-06 01:51:08.556 26695 28808 E SQLiteLog: (284) automatic index on C(manga_id)
05-06 01:51:08.557 26695 28808 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
05-06 01:51:25.273 27565 27565 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
05-06 01:51:29.452 27565 29903 E SQLiteLog: (284) automatic index on C(manga_id)
05-06 01:51:29.452 27565 29903 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
05-06 01:51:49.050 27565 27565 E DecorView: mWindow.mActivityCurrentConfig is null
05-06 01:51:49.084 27565 27565 E DecorView: mWindow.mActivityCurrentConfig is null
05-06 01:51:50.505 27565 27565 E ViewRootImpl: sendUserActionEvent() mView returned.
05-06 01:52:45.091 31440 31440 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
05-06 02:03:21.980   680   680 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
05-06 02:03:56.865   680   739 E SQLiteLog: (284) automatic index on C(manga_id)
05-06 02:03:56.865   680   739 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
05-06 02:07:50.054   680   680 E DecorView: mWindow.mActivityCurrentConfig is null
05-06 02:07:51.968   680   680 E ViewRootImpl: sendUserActionEvent() mView returned.
05-06 02:08:15.991   680   680 E DecorView: mWindow.mActivityCurrentConfig is null
05-06 02:08:18.965   680   680 E ViewRootImpl: sendUserActionEvent() mView returned.
05-06 02:13:45.263  2718  2718 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
05-06 02:13:46.558  2718  4452 E SQLiteLog: (284) automatic index on C(manga_id)
05-06 02:13:46.558  2718  4452 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.10.12 (standard, 6aff438, 59)
Android version: 10 (SDK 29)
Android build ID: QP1A.190711.020.T510XXS5BUC2
Device brand: samsung
Device manufacturer: samsung
Device name: gta3xlwifi
Device model: SM-T510
Device product name: gta3xlwifixx

**Comment by darker1046** [comment] 2021-05-06 05:56
so, with a lot o fear i was able to go back to 10.9,its working again, i would like to update so would still like the help

**Comment by Mohammed-D** [comment] 2021-05-07 18:44
To be more precise, it only happens in webtoons with really long images, ie having 3-5 pages per chapter. The app doesn't crash if there are 10 or so pages. I've been having to read my webtoons in the gallery app due to this bug.

**Comment by AntoineGS** [comment] 2021-05-21 01:19
I haven't been able to replicate this, could you give a specific extension, webtoon and chapter that does this? Thanks

**Comment by Mohammed-D** [comment] 2021-05-21 03:22
Try chapter 2 of "I want to know her" via the toonily extension. (NSFW warning)
Make sure you download the chapter and then open it. I'm not sure if it happens while reading online.

**Comment by AntoineGS** [comment] 2021-05-23 14:00
Hmm I even took out my Tab A to try and replicate this one on the same device and that manga works fine on it.
I am not sure what else to do, the log you posted also do not seem to indicate an application crash.

Have you tried deleting and redownloading the manga after doing the upgrade?
If that does not help maybe create a backup, reinstall and restore the backup.
At this point there is not much more I can do.

**Comment by AntoineGS** [comment] 2021-05-23 14:02
I just saw that akron is working on a similar issue, it could be a possible duplicate of #5151, can you try the preview version he posted here?:
https://github.com/tachiyomiorg/tachiyomi/issues/5151#issuecomment-846567730

**Comment by Mohammed-D** [comment] 2021-05-23 14:07
It tried many things but it kept happening. Eventually I read that chapter directly from my phone gallery. Its not a frequent problem, maybe related to RAM.

**Comment by AntoineGS** [comment] 2021-05-23 14:27
Did you try the preview version?

**Comment by Mohammed-D** [comment] 2021-05-23 14:34
Nope, as I said, it hasnt happened now for a while so I dont mind waiting for the stable version.

**Comment by AntoineGS** [comment] 2021-05-23 14:56
Alright then, when you do update please let us know if it fixes it so we can close this, for now I'll assume it is the same.

**Comment by AntoineGS** [comment] 2021-05-23 14:56
Duplicate of #5151

**Closed** 2021-05-29 02:47 UTC
Labels: bug
