### ISSUE TITLE
[Feature Request] Default tags/filters for sources

### ISSUE THREAD

**Issue by hyoretsu** [tachiyomiorg/tachiyomi#4402] opened 2021-02-07 20:23 UTC
Every time I use... "A certain extension" I have to re-filter with a copy of tag exclusions I've pinned. It'd be a neat feature if we could make some of those be persistent across searches. Shouldn't be hard to implement, aside from UI-wise.

**Comment by scb261** [comment] 2021-02-07 20:28
Duplicate of #1484

**Closed** 2021-02-07 20:29 UTC
Labels: feature
