### ISSUE TITLE
A way to filter out the nsfw sources

### ISSUE THREAD

**Issue by Palloxin** [tachiyomiorg/tachiyomi#6240] opened 2021-11-16 10:01 UTC
### Describe your suggested feature

![IMG_20211116_104224](https://user-images.githubusercontent.com/75091899/141962503-1b9319a8-b043-47bd-8962-eea8879b762a.jpg)
It should look like this edited screenshot.
switching OFF the switch "NSFW" in the read circle the app should filter out all the nsfw sources when you do a global search.
Why? you know what the nsfw is used for, so why should you slow down the global search of non-nsfw mangas including nsfw sources since you are not.. looking for them ;) . In addition there are sources that mix in their database both so i would like the user to be able to add them in a whitelist (or something similar) so that when i switch off the switch "nsfw" i could still use these kind of sources with nsfw content mixed (like HolyManga).

### Other details
When the switch is ON, the global search should only use nsfw sources.

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment] 2021-11-16 21:12
Duplicate of #6240

**Closed by loocool2** 2021-11-16 21:12 UTC
Labels: Feature request
