### ISSUE TITLE
Store alternative names

### ISSUE THREAD

**Issue by SrW0nka** [tachiyomiorg/tachiyomi#6584] opened 2022-02-06 12:03 UTC
### Describe your suggested feature

Some sources use alternatives names (English, Japanese, ...) however only the main title is stored and used for searches in library.

Example: Aida ni Hatachi is the japanese title, however "20 years apart" is also a name for this series and if you search for the 2nd one the search don't find a match.  (mangadex)
 
This will help to find titles in your library and make #6579 more useful.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-02-06 13:18
Duplicate of #2190

**Closed by arkon** 2022-02-06 13:18 UTC
Labels: Feature request
