### ISSUE TITLE
line separator of categories and library cuts off

### ISSUE THREAD

**Issue by mobi2002** [tachiyomiorg/tachiyomi#8077] opened 2022-09-25 14:38 UTC
### Steps to reproduce

Add two categories

### Expected behavior

The line separator between categories and library should be to the end

### Actual behavior

The line separator is cut half way where categories finish 

### Tachiyomi version

r4963

### Android version

12

### Device

Tecno spark 6

### Other details

![Screenshot_20220925-193337](https://user-images.githubusercontent.com/48650614/192149422-8779671b-ff10-433d-a356-b68b12c47edd.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by ghostbear** [comment] 2022-09-25 14:39
Duplicate of #7789

**Closed** 2022-09-25 14:40 UTC
Labels: Bug
