### ISSUE TITLE
Chapter downloaded icon doesn't change after autodeleting

### ISSUE THREAD

**Issue by Horodep** [tachiyomiorg/tachiyomi#5649] opened 2021-08-03 06:56 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 11 (One UI 3.1)

### Device

Samsung A71

### Steps to reproduce

1. Enable "delete chapter after reading" setting
2. Download an unread chapter
3. Read it
4. Go back from reader to chapter list
5. Chapter is marked as read, but download icon still looks like as if chapter is downloaded 
6. If fact chapter is deleted, it can be checked if you go back to the library and reopen title page

### Expected behavior

Chapter should be marked as deleted 

### Actual behavior

Chapter is not marked as deleted:
![Screenshot_20210803-104250_Tachiyomi](https://user-images.githubusercontent.com/8913017/127971242-9012640e-76bd-4f3b-9a54-aa2de6045951.jpg)

**Comment by simplepad** [comment] 2021-08-15 12:26
Version 0.12.1, behaviour is as expected, icon changes when chaper is read.

**Comment by Riztard** [comment] 2021-08-15 12:43
probably just android 11 issue

**Comment by simplepad** [comment] 2021-08-15 12:46
Forgot to mention, tested on Android 11 :)

**Comment by Horodep** [comment] 2021-08-15 20:06
Reinstall also didn't help. 

Current state:
https://user-images.githubusercontent.com/8913017/129491164-4961f951-2b15-4b88-a64c-76637984cc3f.mp4

**Comment by arkon** [comment] 2021-08-15 20:10
Duplicate of #4286

**Closed by arkon** 2021-08-15 20:10 UTC
Labels: Bug
