### ISSUE TITLE
Start reading quickly

### ISSUE THREAD

**Issue by Doddddd** [tachiyomiorg/tachiyomi#7428] opened 2022-07-01 07:12 UTC
### Describe your suggested feature

Click the comics on the bookshelf, skip the catalog page and read directly (long press to enter the catalog page)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-07-01 13:34
Duplicate of #3071

**Closed by arkon** 2022-07-01 13:35 UTC
Labels: Feature request
