### ISSUE TITLE
Feature for delete many from the history.

### ISSUE THREAD

**Issue by sinnghabhay80** [tachiyomiorg/tachiyomi#8956] opened 2023-01-21 19:36 UTC
### Describe your suggested feature

So for now we have the option to delete one entry from the history or to clear the complete history logs altogether.

The requested feature should let you select specific entries from the history i.e. more than one but not all and then you can delete those specific entries from the history.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2023-01-21 20:04
Duplicate of #5993

**Closed by stevenyomi** 2023-01-21 20:04 UTC
Labels: Feature request
