### ISSUE TITLE
Novel / light novel Support ?

### ISSUE THREAD

**Issue by bakrg98** [tachiyomiorg/tachiyomi#10017] opened 2023-10-14 22:29 UTC
### Pretty much self explanatory

Being able to read novels / light novels

### Other details

Perhaps in the form of an extension or something like that 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2023-10-14 22:32
Duplicate of #685

**Closed by Seishirou101** 2023-10-14 22:32 UTC
Labels: Feature request
