### ISSUE TITLE
WebtoonXYZ failed to bypass Cloudflare

### ISSUE THREAD

**Issue by KFA999** [tachiyomiorg/tachiyomi#7568] opened 2022-07-21 04:22 UTC
### Steps to reproduce

When refreshing or updating for the latest update, WebtoonXYZ will always says : Failed to bypass Cloudflare as the issue on the report (this is on the latest version 1.3.25).

Even when using the webview in Tachiyomi for WebtoonXYZ i'm always stuck at the "Checking your browser before accessing www.webtoon.xyz" / cloudflare screen and never getting pass through it. At first I think its the host problem so I tried to open it at google chrome but to my suprise it works perfectly fine. So I am very grateful if a fix can be made. Thank you so much.

### Expected behavior

Supposedly everything should be normal : WebtoonXYZ shows all the manga for searches and latest updated manga

![Screenshot_20220721-121910_Chrome](https://user-images.githubusercontent.com/109713508/180129120-053208f5-1d5e-4884-8a0d-ebddb68ad6e2.jpg)

### Actual behavior

I'm stuck on the cloudflare page when in webview and never getting pass through it. On normal search on the extension it will say failed to bypass cloudflare. I've even use all the "use dns over https" option but to no avail it didn't work

![Screenshot_20220721-120610_Tachiyomi](https://user-images.githubusercontent.com/109713508/180129285-506945a2-5973-4612-a59f-981ab014888c.jpg)

![Screenshot_20220721-120619_Tachiyomi](https://user-images.githubusercontent.com/109713508/180129293-a9a7b846-2b61-415f-9e9a-ebe75f9754f0.jpg)

### Tachiyomi version

0.13.5

### Android version

12

### Device

Samsung Galaxy S20 Plus

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment] 2022-07-21 05:17
>  If this is an issue with an extension, I should be opening an issue in the extensions repository.

Please read what you actually acknowledge...

Duplicate of https://github.com/tachiyomiorg/tachiyomi-extensions/issues/6738

**Closed by curche** 2022-07-21 05:17 UTC
Labels: Bug

**Comment by KFA999** [comment] 2022-07-21 05:59
> > If this is an issue with an extension, I should be opening an issue in the extensions repository.
> 
> Please read what you actually acknowledge...
> 
> Duplicate of [tachiyomiorg/tachiyomi-extensions#6738](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/6738)

Sorry for not doing it under the extension but okay. So until the website lowers the cloud protection level, i can't surf it on tachiyomi is what it means on the link given right?

**Comment by curche** [comment] 2022-07-21 12:20
Yes
