### ISSUE TITLE
Can't check skipped manga

### ISSUE THREAD

**Issue by Enlil50** [tachiyomiorg/tachiyomi#7739] opened 2022-08-13 08:14 UTC
### Steps to reproduce

1. Update library

### Expected behavior

When an error occurs, tachiyomi generates a file so you can read what Manga gave an error.
When Manga are skipped, it would be better to generate a file, so you can check which of yours were skipped.

### Actual behavior

When Manga are skipped, it doesn't generate a file, instead it leads you to the website.

### Tachiyomi version

0.13.5

### Android version

Android 12

### Device

Samsung S21FE

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-08-13 12:43
Duplicate of #6985

**Closed by arkon** 2022-08-13 12:43 UTC
Labels: Bug
