### ISSUE TITLE
[Feature Request] Saving of search filters. 

### ISSUE THREAD

**Issue by DarAmetis** [tachiyomiorg/tachiyomi#4551] opened 2021-02-26 13:25 UTC
Please add saving of search filters. 

I do not know what can be said about the need for this function. She is needed! This is the only reason why I am sitting on a different fork. With a dozen exclusive genres in your sample, it’s annoying and time-consuming to re-enter everything when looking for a new manga every time.

Keeping a list of filters while searching is the best you can think of for a program at the moment.
Thank.

**Comment by scb261** [comment] 2021-02-26 13:27
Duplicate of #1484

**Closed** 2021-02-26 13:30 UTC
Labels: feature

**Comment by DarAmetis** [comment] 2021-02-26 13:35
The first request was over 2 years ago. Does this mean that this feature will not be introduced?
