### ISSUE TITLE
[Feature Request] Ability to delete leftover downloaded manga not in library and/or Recycle Bin feature

### ISSUE THREAD

**Issue by LycorisNagami** [tachiyomiorg/tachiyomi#4567] opened 2021-03-01 05:56 UTC
## Why/User Benefit/User Problem
To avoid running out of storage space due to accumulated leftover downloaded manga removed from library. Happens mostly when migrating to another source when previous source has downloaded chapters. If Recycle Bin feature then all Downloaded Manga not in library will be displayed thier then user decides either to Restore or Delete

## What/Requirements
Clear Database is already an in app feature which deletes manga history not in library so why not add in a few code wherein it also checks and deletes the manga folder in storage regardless if it's empty folder/s or has chapters in it (Empty folders eat storage too). If Recycle Bin feature then all Manga not in Library but has downloaded Chapter/s will be displayed in Bin, from their user decides either to Restore it back to Library(a prompt is displayed when a Duplicate Manga with different source is found in Library) or Delete it all (Manga History and Folder in storage)

**Comment by LycorisNagami** [comment] 2021-03-01 07:03
Issue #4449 is related to this, when you Clear Database the Manga history is cleared but the downloaded chapters is still in storage. Manga is shows as unread and not downloaded but I can read everything without net connection.

**Comment by scb261** [comment] 2021-03-01 10:21
Duplicate of #1767

**Comment by LycorisNagami** [comment] 2021-03-01 11:30
> Duplicate of #1767

Is that issue active? That's from 2018

**Closed** 2021-03-01 12:31 UTC
Labels: feature
