### ISSUE TITLE
The image is cut off

### ISSUE THREAD

**Issue by mozzaru** [tachiyomiorg/tachiyomi#9620] opened 2023-06-20 15:38 UTC
### Steps to reproduce

The image is cut off and when the application is released it is normal again then returns to normal

### Expected behavior

The image is cut off and when the application is released it is normal again then returns to normal
Mode WebView normal

### Actual behavior

The image is cut off and when the application is released it is normal again then returns to normal
Mode WebView normal

### Tachiyomi version

r5845

### Android version

Android 11

### Device

Realme 7i

### Other details

![Screenshot_2023-06-20-22-33-36-66_79aa9bf7c61e266c5f841e42245e214b](https://github.com/tachiyomiorg/tachiyomi/assets/100791931/75190560-e90e-44cf-9f23-f21e2dfa1c5b)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment] 2023-06-20 15:39
Disable split tall image (Beta) from reader settings

**Comment by arkon** [comment] 2023-06-20 22:09
Duplicate of #8433

**Closed** 2023-06-20 22:10 UTC
Labels: Bug
