### ISSUE TITLE
[Feature Request] Group issues into chapters manually

### ISSUE THREAD

**Issue by zedseven** [tachiyomiorg/tachiyomi#4651] opened 2021-03-14 23:39 UTC
## Why/User Benefit/User Problem
Some series are only available with individual chapters as their own entries, and it bloats the Library view to have multiple chapters of one manga sitting there. By manually grouping them into one entry with each as a chapter, this problem is resolved.

## What/Requirements
I was thinking either as a manual chapter assignment that behaves similar to how chapters currently work, or as a grouping mechanism that allows the user to just group similar entries together in a sub-Library view.

**Comment by scb261** [comment] 2021-03-14 23:51
Merging chapters from different manga entries probably will be denied. Grouping is duplicate of #1803.

**Closed** 2021-03-15 13:24 UTC
Labels: feature
