### ISSUE TITLE
[Feature Request] Freely Organize Library

### ISSUE THREAD

**Issue by danrleylfd** [tachiyomiorg/tachiyomi#5041] opened 2021-05-07 18:27 UTC
## Why/User Benefit/User Problem
I believe it would be interesting to be able to - organize the books freely.

## What/Requirements
Organize books lists in a personalized way, as well as in downloads.

Thank you very much in advance. 👏👏👏

**Comment by arkon** [comment] 2021-05-07 22:16
Duplicate of #4548

**Closed by arkon** 2021-05-07 22:16 UTC
Labels: feature
