### ISSUE TITLE
Manga kept in background will go to a random page

### ISSUE THREAD

**Issue by 3bdenour** [tachiyomiorg/tachiyomi#9515] opened 2023-05-18 10:47 UTC
### Steps to reproduce

When keeping a manga reading mode  for some time in the background and going to it afterward

### Expected behavior

Its expected to resume where you were the last time.

### Actual behavior

You will get into a random page  or chapter ( most of the time you ll get those you already opened some time ago ) 

### Tachiyomi version

0.14.6

### Android version

Android 13

### Device

OnePlus 9 Pro 

### Other details

i already noticed this behavior on other phones that uses ColorOs; 
OPPO ( colorOs) 
Realme (RealmeUi) 
Oneplus( OxygenOs )

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment] 2023-05-18 17:22
Duplicate of #9440

**Closed** 2023-05-18 17:22 UTC
Labels: Bug, Duplicate
