### ISSUE TITLE
Show last Backup time

### ISSUE THREAD

**Issue by Riztard** [tachiyomiorg/tachiyomi#8695] opened 2022-12-07 15:29 UTC
### Describe your suggested feature

show latest backup time for manual and auto 
kinda similar to `library last updated` in `updates` tab

maybe something like this
```
Last auto backup: 07 Dec 2022 10:20 AM
Last manual backup: 07 Dec 2022 10:20 AM
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-12-07 15:44
Duplicate of #3474

**Closed** 2022-12-07 15:44 UTC
Labels: Feature request

**Comment by Riztard** [comment] 2022-12-09 01:14
ah didnt see that
