### ISSUE TITLE
Default reading mode for different sources

### ISSUE THREAD

**Issue by Georgeee0707** [tachiyomiorg/tachiyomi#9496] opened 2023-05-13 15:43 UTC
### Describe your suggested feature

Select default reading mode for different sources. Something in the options that could specify what reading more for selected source

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-05-13 16:12
Duplicate of #3318

**Closed by arkon** 2023-05-13 16:12 UTC
Labels: Feature request
