### ISSUE TITLE
[Feature Request] Scrolling speed control for webtoon view

### ISSUE THREAD

**Issue by asdkant** [tachiyomiorg/tachiyomi#2785] opened 2020-03-29 22:38 UTC
### Why/User Benefit/User Problem
It'd be a nice usability improvement to have a way to change the speed at which webtoon-view content is scrolled when swiping on te page, since:
- it's common to read a screenful of content, then scroll down to the next screenful of content (and tap-scrolling is not intelligent enough to scroll the right amount, which can be lariable within a single chapter)
- a lot of webtoons have long transitions with blanks / color gradients and scrolling through that gets old pretty fast

This feature would be especially helpful if zoom-out for webtoon (meaning it'd take less than the full width of the screen) as per #1675 is implemented.

### What/Requirements
I've seen this implemented in MiMangaNu and working really well:
- a global setting for the default
- a box in the right-hand which controls the speed within the webtoon view when the controls are visible (basically a plus button, a minus button, and a number with the scroll speed multiplier)

**Comment by arkon** [comment] 2020-03-29 22:39
Duplicate of #2093.

Feel free to add the info about MiMangaNu in that issue so it isn't lost.

**Comment by asdkant** [comment] 2020-03-30 00:00
@akron I'm not referring to autoscroll speed, I'm referring to regular scrolling (I saw the autoscroll issue but thought this was distinct enough)

**Comment by arkon** [comment] 2020-03-30 00:03
I'm not sure I understand. Do you mean the speed that it scrolls when you press the side of the page?

**Comment by asdkant** [comment] 2020-03-30 00:50
Ah, my mistake in explaining then.

I'm referring to the relative speed of the page moving when you swipe across the screen.

**Comment by Soitora** [comment] 2020-04-21 01:42
So, in relative speed you mean to say that for example swiping my finger 2cm wont drag the page by 2cm, but an adjusted rate like (let's say) 4cm?

**Comment by asdkant** [comment] 2020-04-21 15:20
@Soitora yes, exactly

**Comment by habolo-groo** [comment] 2021-01-19 03:49
May I ask: What is the status of this feature request.? Seems still open, but not comment since April 21, 2020 (nearly 9 months).

I'd like to request that this feature be given higher priority, since it is an issue of Access for Persons with Disabilities. I work with students on the autism spectrum. One of them is very keen to read comics independently like he reads books on the Kindle App, but his manual dyspraxia (weakness of fine motor control in the hand and fingers) makes it impossible for him to control the scrolling of WebToons app with the needed level of accuracy. He swipes up on the touchscreen, but the scrolling goes flying too fast and he ends up skipping over frames without having a chance to read them. A feature to make the adjust the level of scrolling speed /sensitivity would allow some people who have no access to Webtoons at all today to become regular users.

Note: Kindle app works for e-books for individuals such as these, because each swipe advances a set amount, i.e. exactly 1 page. Thanks.

**Comment by arkon** [comment] 2022-01-05 22:22
Closing in favour of #6419, since it'd probably make sense for pager reader modes too.

**Closed by arkon** 2022-01-05 22:22 UTC
Labels: Feature request
