### ISSUE TITLE
Generate and edit directly "details.json" in Tachiyomi

### ISSUE THREAD

**Issue by lb-fes** [tachiyomiorg/tachiyomi#9193] opened 2023-03-10 10:30 UTC
### Describe your suggested feature

I have many local manga.

If can add a button to generate and edit directly "details.json" in Tachiyomi，that would be very convenient.

### Other details

thanks developers

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-03-11 03:37
Duplicate of #5890

**Closed by arkon** 2023-03-11 03:37 UTC
Labels: Feature request
