### ISSUE TITLE
New Setting Feature to Delete All Non-Favorited Downloaded Chapters

### ISSUE THREAD

**Issue by psyscope** [tachiyomiorg/tachiyomi#9608] opened 2023-06-12 16:40 UTC
### Describe your suggested feature

Can a feature be added, under "Advanced" to check for any manga, that is not favorited, but has been downloaded to either be show in a specific menu, or even give us the option to delete them all?  This way when we migrate and forget to delete the episodes, we can free up space more easily. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2023-06-12 17:13
Duplicate of #1767

**Closed by Seishirou101** 2023-06-12 17:13 UTC
Labels: Feature request
