### ISSUE TITLE
[Feature Request] Directly read from Local

### ISSUE THREAD

**Issue by ARiyou2000** [tachiyomiorg/tachiyomi#5226] opened 2021-05-28 19:54 UTC
Instead of adding folders and manga in "Storage/Tachiyomi/Local" can Browse Storage itself directly and chose specific file or chapter at whatever directory.

**Comment by loocool2** [comment] 2021-05-28 19:57
Duplicate of #2086

**Closed** 2021-05-28 20:00 UTC
Labels: feature
