### ISSUE TITLE
[Reading Bug] Pressing Resume button starts on final chapter

### ISSUE THREAD

**Issue by otakuomid** [tachiyomiorg/tachiyomi#4910] opened 2021-04-20 02:18 UTC
When I press resume or start on any manga, it takes me to the final chapter of the manga. For example, if I want to to resume on chapter 248 of Naruto, it takes me to chapter 700 no matter what I do.

**Comment by arkon** [comment] 2021-04-20 02:26
Marking as duplicate of #4909

**Closed by arkon** 2021-04-20 02:26 UTC
Labels: bug
