### ISSUE TITLE
No cover when using local manga

### ISSUE THREAD

**Issue by diksm8** [tachiyomiorg/tachiyomi#932] opened 2017-08-14 05:10 UTC
No cover when using local manga. Changing the cover using the edit button updates the cover.png file but the cover does not update. Tried rebooting phone and using the app for a while but it still does not show.

Version: 0.6.1
OxygenOS 4.5.8 Android 7.1.1

**Comment by aaether32323** [comment] 2017-09-13 02:24
I had the same problem, same OS. Reinstalling the app fixed it for me.

**Comment by Basha0** [comment] 2017-09-28 15:05
U can fix that by choosing the Manga with no cover, go then to info and refresh the info, the the cover gets updated and it will be shown.

**Comment by arkon** [comment] 2020-03-09 21:17
As mentioned in #2681:


1. Unbookmark the manga / remove it from your library (Optionally move the manga out of the local manga folder.
1. Clear Database in advanced settings
1. Re-add the manga from local manga

This would be a method to fully remove the manga from the internal database so it can be added with a fresh cover.

**Comment by arkon** [comment] 2020-03-09 21:19
Related PR: #1669

**Comment by Neshura87** [comment] 2020-05-18 10:57
Local Manga Cover not showing up in Library, cover.jpg is inside the manga directory, path is Phone/Tachiyomi/local/Manga/cover.jpg so I hope that is the correct one.
Followed the Trouble Shooting steps but this did not solve the issue

**Comment by scb261** [comment] 2020-10-02 15:19
There was PR with attempt to fix it (and was closed for some reason) so I'm not sure if the source of the problem was found, but here are steps to reproduce the issue:
1. Create folder `/Tachiyomi/local/Manga`.
1. Leave the folder empty or create wrong structure that Tachiyomi doesn't understand (for example add pages directly in the manga folder without chapter folders). Don't add any `cover.jpg`.
1. Go to *Local source* and see blank cover (since there isn't any `cover.jpg` and the app doesn't see any chapters to take cover from it).
1. Now fix the manga folder: add `cover.jpg` and/or add chapter folders with images
1. Go back to the manga in the app. You can also try to reopen the app hopping that will reload covers.

Expected behavior: the app loads cover from `cover.jpg` or from first chapter.

Actual behavior: the cover stays blank and you need to clear database to fix it.

**Comment by naxil** [comment] 2021-01-14 18:06
Fix for me the "refresh manga cover" on advanced settings

**Comment by sQVe** [comment] 2021-09-10 04:31
I saw this issue as and had to downgrade to 0.11.1 for it to work again and generate the proper covers.

**Comment by raniesantos** [comment] 2021-10-02 06:51
So this is a bug where the cause of it is just unknown???????

**Comment by Nonamow** [comment] 2021-10-03 15:31
I cleaned the database(with first removing bookmarks), but this error remained.

**Comment by Nonamow** [comment] 2021-10-03 18:22
Well... I tried to create a new totally clean emulator. It still doesn't work.

![image](https://user-images.githubusercontent.com/46028249/135766316-294f241a-c5eb-4607-9710-10df5a8a1934.png)
![image](https://user-images.githubusercontent.com/46028249/135766502-710de268-f1d2-457a-ab79-bfcebd8b715b.png)

**Comment by Nonamow** [comment] 2021-10-03 18:38
Ok. I manually created cover and then clicked "refresh library manga covers" (actually the manga wasn't in the library). It works. Win? I don't think so.

**Comment by Nonamow** [comment] 2021-10-03 19:13
Or maybe you should use both refresh lib and clear db.

**Comment by it0na72** [comment] 2021-10-18 19:50
Tried everything in this page that was suggested - including the guidelines on the website and still didn't work. What worked was downloading the preview version, clicking on a random picture and "set as cover" inside the app. However, it only worked for 1 manga, then stopped working. Any info on this?

**Comment by it0na72** [comment] 2021-10-18 21:31
@Nonamow yea that worked, however that only worked when I downgraded to the version @sQVe mentioned. Everything seems to be sorted now. Hopefully this gets fixed eventually in the next versions. Thanks guys.

**Comment by Nonamow** [comment] 2021-10-18 21:42
This situation...
I must automatized my solution! Run this python script at "Tachiyomi/local" and it will copy cover from "default cover" (you should create it) to all folder without cover.jpg (only jpg?! not ok. But jist for now):

```import os
import shutil

def default_cover_error(err_code):
    print(err_code)
    
def main():
    if os.path.isdir("default cover"):
        if os.path.isfile("default cover/cover.jpg"):
            for obj in os.listdir():
                if (os.path.isdir(obj) and not (obj == "default cover") and not (os.path.isfile(obj+"/cover.jpg"))):
                    shutil.copy("default cover/cover.jpg", obj+"/cover.jpg")
                    
        else:
            default_cover_error("cover")
    else:
        default_cover_error("dir")
    
if __name__ == "__main__":
    main()

**Comment by arkon** [comment] 2021-10-30 16:18
Potentially fixed by #6127. Please open another issue (if there isn't one) if the issue still persists in the next preview/stable build.

**Closed by arkon** 2021-10-30 16:18 UTC
Labels: Bug

**Comment by sQVe** [comment] 2021-10-30 19:51
@arkon Great news 🎉

How do I know if this fix is included in a preview releases? 🤔

**Comment by arkon** [comment] 2021-10-30 21:16
It's in the most recent release: https://github.com/tachiyomiorg/tachiyomi-preview/releases/tag/r3931

**Comment by sQVe** [comment] 2021-10-31 06:57
@arkon Covers are working fine for me on latest preview after nuking cache etc! 🥳
