### ISSUE TITLE
Update library 

### ISSUE THREAD

**Issue by Abdallah-amara021** [tachiyomiorg/tachiyomi#10346] opened 2024-01-07 20:02 UTC
### Steps to reproduce

1-open the app
2-go to history
3-click on update library 
4-the update library end without give me any new found

### Expected behavior

After I click on update library it Supposed to found new chapter for the manga I put it in the library 

### Actual behavior

The library update end without give me anything 

### Tachiyomi version

0.15.1

### Android version

8.1.0

### Device

Galaxy tab A

### Other details

The update library was work in the version 0.14.7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2024-01-07 22:34
Duplicate of #10151

**Closed by arkon** 2024-01-07 22:34 UTC
Labels: Bug

**Comment by Abdallah-amara021** [comment] 2024-01-08 13:39
> Duplicate of #10313

I have fix it go to MORE then setting then library smart update make it unselected all thing and that's it
![Screenshot_20240108-153650_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/104996176/65ead412-6f38-40cb-ab77-a6b585c040ae)
![Screenshot_20240108-153655_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/104996176/2591a092-6b79-442e-a3fa-2b4b874183fd)
![Screenshot_20240108-153705_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/104996176/1d8dd1bb-35a7-4360-855c-a2652044388f)
![Screenshot_20240108-153708_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/104996176/0db8d820-4088-4be5-b092-041936e59674)
