### ISSUE TITLE
Hope to add double page reading feature

### ISSUE THREAD

**Issue by SenaJun** [tachiyomiorg/tachiyomi#7680] opened 2022-08-04 05:57 UTC
### Describe your suggested feature

Hello developers!

I am an Android phone and Android tablet user

When using an Android tablet to read comics, Tachiyomi only supports single-page reading and double-page splitting, so the tablet cannot make good use of the screen space when reading in landscape, resulting in a lot of free space on the screen.

I hope to add a function that can merge two single-page comics into two-page comics, which can not only effectively use the screen space of the tablet when it is in landscape orientation, but also greatly improve the comic reading experience!

Hope to accept!

您好开发者！

我是安卓手机及安卓平板的用户

在使用安卓平板进行漫画阅读的时候，Tachiyomi 由于仅支持单页阅读以及双页拆分的功能，导致平板电脑在横屏阅读时无法很好的利用屏幕空间，导致屏幕空余的空间很多。

希望能够添加一个能够将两张单页漫画合并成双页漫画的功能，这样不仅能够有效利用平板电脑横屏时的屏幕空间，还能大幅度的提高漫画阅读体验！

望采纳！

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment] 2022-08-04 05:58
Duplicate of #149

**Closed by loocool2** 2022-08-04 05:58 UTC
Labels: Feature request
