### ISSUE TITLE
[Feature Request] Extending width of Vertical Scrolling Area in Reading Modes.

### ISSUE THREAD

**Issue by samuelthng** [tachiyomiorg/tachiyomi#4219] opened 2020-12-30 02:33 UTC
## Why/User Benefit/User Problem

Reading Modes: 
 - Webtoon
 - Continuous vertical

Small improvement, when viewing manga at less than the viewport width, we are currently only able to scroll up and down when touch is initiated on the image. 

The pillars/blackbox on the side won't detect scrolls, it would be slightly more intuitive if the scroll area covers the entire viewport area instead of just the manga images, similar to the other horizontally scrolling reading modes.

## What/Requirements

Extend the scroll area for webtoon and continuous vertical to the edges of the viewport horizontally.

**Comment by scb261** [comment] 2020-12-30 11:06
Duplicate of #3127

**Closed** 2020-12-30 11:46 UTC
Labels: feature
