### ISSUE TITLE
Category update priority/frequency

### ISSUE THREAD

**Issue by mm12** [tachiyomiorg/tachiyomi#6856] opened 2022-04-03 01:38 UTC
### Describe your suggested feature

Have priority settings of some kind for automatically checking for updates. These priorities also dictate how often it is checked. 
For example, a low priority category would be checked once a week (ie, maybe series you have on hold or are waiting for the next volume to be dropped on), while a high priority category would get updated at your normal frequency. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-04-03 01:42
Duplicate of #6698

**Closed by arkon** 2022-04-03 01:42 UTC
Labels: Feature request

**Comment by mm12** [comment] 2022-04-03 01:52
my bad, i searched "category frequency" and similar but only saw closed issues.
