### ISSUE TITLE
Manga chapter not deleting when closing the app right after deleting the chapter

### ISSUE THREAD

**Issue by MrAndre96** [tachiyomiorg/tachiyomi#8094] opened 2022-09-26 20:24 UTC
### Steps to reproduce

1. Delete a chapter
2. Close the app
3. reopen the app

### Expected behavior

The chapter should be deleted

### Actual behavior

The chapter is not deleted

### Tachiyomi version

r4963

### Android version

Android 11

### Device

Oneplus 7

### Other details

https://user-images.githubusercontent.com/6564956/192372989-3c214b36-c8e9-4e1b-b74e-58007483aaf5.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-09-26 21:11
Is it fine if you _don't_ immediately kill the app?

**Comment by MrAndre96** [comment] 2022-09-26 21:27
> Is it fine if you _don't_ immediately kill the app?

if you wait 10s or something it will be deleted but for example with 5s it is still not deleted

**Comment by arkon** [comment] 2022-09-26 21:29
Duplicate of #4286

Your best bet is to give the app/system some time to actually delete the file.

**Closed by arkon** 2022-09-26 21:29 UTC
Labels: Bug
