### ISSUE TITLE
Chapters showing Black pages

### ISSUE THREAD

**Issue by kingtie** [tachiyomiorg/tachiyomi#7759] opened 2022-08-14 13:24 UTC
### Steps to reproduce

Trying to view chapters from multiple sources
![Screenshot_2022 08 14_22 19 10 845](https://user-images.githubusercontent.com/62863320/184539155-f58bbe04-aaaa-449d-9cb9-e2bb3d687259.png)
![Screenshot_2022 08 14_22 19 23 270](https://user-images.githubusercontent.com/62863320/184539162-618f2be9-eeba-4108-8e3e-a1e834e031b4.png)
![Screenshot_2022 08 14_22 19 59 257](https://user-images.githubusercontent.com/62863320/184539169-ae6fc8de-746b-4739-9f51-1b571fda725a.png)

### Expected behavior

Each page should be visible.

### Actual behavior

When trying to view any chapter the 1sr-2nd pages shows up perfectly fine while all the rest of the pages show up black even when downloaded.

### Tachiyomi version

13.5

### Android version

Android 12, 11 and 6

### Device

Galaxy s22 Ultra, Galaxy s20 plus, and BlueStacks 5

### Other details

The only way I found to get the pages to properly load is to use the Page bar and constantly move between pages and it forces it to load for some reason.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by DrakeWK** [comment] 2022-08-16 01:18
The screenshot of the file explorer clearly shows the pages aren't downloaded as black, meaning the problem comes from the loading of the image, might it be linked to the layout you use, have you tried changing it?

**Comment by arkon** [comment] 2022-08-16 01:26
Pretty sure it's just a duplicate of #1908

Try the split tall images option in 0.13.6

**Closed by arkon** 2022-08-16 01:26 UTC
Labels: Bug
