### ISSUE TITLE
Scroll with lag at specific times

### ISSUE THREAD

**Issue by MrChuw** [tachiyomiorg/tachiyomi#5490] opened 2021-07-02 19:10 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

Android 11

### Device

Poco M3

### Steps to reproduce

1.  Open a chapter. (in this case the most recent I found this issue, "the blade of evolution-walking alone in the dungeon - isekaiscan)
2. Scroll until you notice the lag.
3. As in the video.

https://user-images.githubusercontent.com/14945734/124318860-b164ba80-db4f-11eb-8e3c-34a9e51e6723.mp4

### Expected behavior

Smooth scroll.

### Actual behavior

This terrible lag on the scroll as you can see.

**Comment by arkon** [comment] 2021-07-02 22:18
Duplicate of #1908

**Closed by arkon** 2021-07-02 22:18 UTC
Labels: Bug
