### ISSUE TITLE
The reader does not store position correctly and can make huge jumps after rotation changes

### ISSUE THREAD

**Issue by zszabo2000** [tachiyomiorg/tachiyomi#6326] opened 2021-12-07 01:32 UTC
### Steps to reproduce

Start reading Tower of God chapter 520 on 1stKissManga. The source probably doesn't matter, but right now I'm reading that chapter of that manga from that site on a Nokia 2.3 (running Android 11 -- although again, this bug is observable on other devices with other screen aspect ratios/resolutions,, running other/older versions of Android). The aspect ratio / resolution in this case is 9:19 / 720 x 1520 in portrait mode.

The attached images demonstrate the problem: the first image starts with an arbitrary location in portrait mode. The second image show the screen after rotation to landscape. The third image shows the screen after rotation  back from landscape to portrait.

While this effect is somewhat exaggerated by the disproportional screen aspect ratio (19:9), the point nevertheless stands: even while the reader shows the same page number (bottom-center), the three screen shots show completely different content. Since the reader appears to jump back to the top of the current image, this becomes unacceptable when the content encompasses the equivalent of multiple vertically stacked pages.

![SSHOT-INITIAL-PORTRAIT](https://user-images.githubusercontent.com/3099330/144947411-6a400ac4-0f79-40cb-bee2-7a0f81e2a499.png)
![SSHOT-FIRST-ROTATION](https://user-images.githubusercontent.com/3099330/144947410-5af8205b-5b40-4702-86d8-e6ff5532577a.png)
![SSHOT-SECOND-ROTATION](https://user-images.githubusercontent.com/3099330/144947408-7510e3c2-e458-413e-866f-35a9b78ade11.png)

### Expected behavior

The reader should return to the same vertical offset of the same source image that was being read prior to rotation / reading mode change.

### Actual behavior

The reader currently returns to the same source image, but not to the same vertical offset within that image. Because there are some source images that are very, very long vertically, this current situation frequently requires to scroll down many page-equivalents to get back to the location they were at prior to mode / rotation change. 

### Tachiyomi version

Stable 0.12.3 (10/6/21 20:06)

### Android version

11

### Device

Nokia 2.3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2021-12-07 03:43
Duplicate of #3322

**Closed by arkon** 2021-12-07 03:43 UTC
Labels: Bug
