### ISSUE TITLE
Downloaded entries in sdcard are ignored

### ISSUE THREAD

**Issue by jooomoooj** [tachiyomiorg/tachiyomi#10225] opened 2023-12-10 06:44 UTC
### Steps to reproduce

Launch Tachiyomi
Download any entry
Turn off internet
Read the downloaded entry

https://github.com/tachiyomiorg/tachiyomi/assets/101556532/c8c4b67f-3fb8-4b5d-aa11-660aec561c80

### Expected behavior

It should not require internet to open since the downloaded entry exists.

### Actual behavior

Even the entries are downloaded, it still required to turn on internet to load and open.

### Tachiyomi version

0.14.7-r6274

### Android version

Android 13

### Device

Xiaomi A1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jbvasc** [comment] 2023-12-10 15:22
No meu Samsung tab s8 acontece a mesma coisa , mas somente na versão de desenvolvimento,  na versão normal isto não ocorre.

**Comment by arkon** [comment] 2023-12-10 17:00
What's your storage location set to and what appears in that folder?

**Comment by jbvasc** [comment] 2023-12-10 21:17
/storage/f299-fa97/multimidia/Hqs
Android 13 one ui 5.1.1
Mensagem que aparece 
Unable to resolvendo host " nome página (muda conforme a extensao) " no Andress associate With hostname

**Comment by arkon** [comment] 2023-12-10 22:02
I can't seem to reproduce this, can you show your storage location setting and what's actually in the selected folder?

**Comment by jbvasc** [comment] 2023-12-10 22:05
![Screenshot_20231210_190447_My Files](https://github.com/tachiyomiorg/tachiyomi/assets/153444393/be7294ae-737c-49ff-b238-b557d11bec8f)

**Comment by jbvasc** [comment] 2023-12-10 22:06
![Screenshot_20231210_190618_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/153444393/847f35e6-8c26-4a6c-a440-240304cd3fa9)

**Comment by jbvasc** [comment] 2023-12-10 22:07
![Screenshot_20231210_190717_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/153444393/30d29cec-7005-42f4-b44c-8880e851686b)

**Comment by arkon** [comment] 2023-12-10 22:08
It'll be mentioned in the stable build release notes, but the folder structure now needs to follow:

```
<selected folder>
|- downloads
    |- Source name (LANG)
        |- Title
            |- Chapter01.cbz
            |- Chapter02.cbz 
            |- ...
        |- Other title
            |- Chapter01.cbz
            |- Chapter02.cbz 
            |- ...
```

**Comment by jbvasc** [comment] 2023-12-10 22:12
Ao tentar mudar surge esta mensagem 
![Screenshot_20231210_191130_Files](https://github.com/tachiyomiorg/tachiyomi/assets/153444393/7a9c7dee-2bfc-4e7a-821c-87a264298e90)

**Comment by arkon** [comment] 2023-12-10 22:15
> ![Screenshot_20231210_190447_My Files](https://private-user-images.githubusercontent.com/153444393/289389644-be7294ae-737c-49ff-b238-b557d11bec8f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNDY2NTQsIm5iZiI6MTcwMjI0NjM1NCwicGF0aCI6Ii8xNTM0NDQzOTMvMjg5Mzg5NjQ0LWJlNzI5NGFlLTczN2MtNDlmZi1iMjM4LWI1NTdkMTFiZWM4Zi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMFQyMjEyMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZjlmYjE4MGJkOTVjMTc1YTE3N2VmZjU5ZGIzNTY1ODIyYjdjYjc4NzczYjY3NjdhZjNkNTk0NjA0YWE3MjkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IuG96CVyqK5KMQ-_s_i-__rlebwVW6ksikIZIVTS9LU)

I meant you need to move the source folders here into the `downloads` folder that's there.

**Comment by jbvasc** [comment] 2023-12-10 22:21
Ok vou tentar . Obrigado

**Comment by arkon** [comment] 2023-12-11 03:12
> Im following but still it wont work /SanDisk/Tachiyomi/Downloads/Mangakatana/(Manga)/Chapter 01.cbz

Is your setting set to `/SanDisk/Tachiyomi`, and is `Downloads` actually `downloads`? What happens when you download a new chapter (where does it show up if you look at a file manager)?

**Comment by jbvasc** [comment] 2023-12-11 10:45
Também não consegui. apaguei todos os arquivos e estou baixando de novo . Qd baixo aparecem marcados como baixados , mas qd inválido o índice de downloads desmarca. Mas ainda ficam salvos e posso ler normalmente . Só não aparecem marcados não importa qts vezes invalide o índice.

**Comment by arkon** [comment] 2023-12-11 14:15
Duplicate of #10218

**Closed by arkon** 2023-12-11 14:15 UTC
Labels: Bug, Needs more info, Stable release blocker
