### ISSUE TITLE
The zoom start position.

### ISSUE THREAD

**Issue by Xeiniac** [tachiyomiorg/tachiyomi#1628] opened 2018-09-22 13:09 UTC
**App version:**
0.7.4
**Issue/Request:**
Is it possible to make the zoom start position manga based like viewer for this series? I ask this because I use Smart fit since my device isn't 16:9 and for the pages where they have a long strip (2 pages combines) the zoom start position is different for manga and manhua since manga is read right to left while manhua is read left to right.

**Comment by stevenyomi** [comment] 2023-04-27 17:55
Duplicate of #5865

**Closed by stevenyomi** 2023-04-27 17:55 UTC
Labels: Feature request
