### ISSUE TITLE
Pressing Copy button crashes the app

### ISSUE THREAD

**Issue by Meliodas-Sama** [tachiyomiorg/tachiyomi#9192] opened 2023-03-10 05:07 UTC
### Steps to reproduce

1. Open a manga from library.
2. Select text from its description.
3. Press the back button or arrow.
4. Press the copy button that moved to the upper left corner.
5. The app crashes.

### Expected behavior

The copy button should disappear after pressing the back button. 

### Actual behavior

The copy butten moves to the upper left corner and it crashes the app when pressed. 

### Tachiyomi version

0.14.5 (standard, b690de5, 98, 2023-02-19T20:35Z)

### Android version

10 (SDK 29) Android build ID: QP1A.190711.020

### Device

Xiaomi, Redmi Note 8 Pro, begonia. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-03-10 13:29
Duplicate of #9073

**Closed** 2023-03-10 13:29 UTC
Labels: Bug

**Comment by Meliodas-Sama** [comment] 2023-03-11 03:55
Thanks for the reply, I didn't think about searching for the text selection as it didn't show after pressing back on my device only the button did, I well try better next time.
