### ISSUE TITLE
Scroll for long pages

### ISSUE THREAD

**Issue by hecode** [tachiyomiorg/tachiyomi#10274] opened 2023-12-28 04:04 UTC
### Describe your suggested feature

For example for webseries/webcomics/Manwha a lot of them have very long pages, the progress bar at the bottom is good for series where each page is 1 full view but for series like them where one page is like maybe 5 full screens it would be nice if they can be scrolled through. (using the bottom bar would skip a few pages rather than just 1).

so I suggest for webtoon and continuous vertical modes to have a vertical progress scroll that can scroll the content regardless of the current page.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by hecode** [comment] 2024-01-03 12:59
I found the splitting feature of long images helps for the horizontal bar but still a vertical scroll would be much more convenient

**Comment by arkon** [comment] 2024-01-08 03:53
Duplicate of #3322

**Closed by arkon** 2024-01-08 03:53 UTC
Labels: Feature request
