### ISSUE TITLE
Ошибка, не обновляется библиотека! 

### ISSUE THREAD

**Issue by MM001-r** [tachiyomiorg/tachiyomi#4208] opened 2020-12-28 13:13 UTC
[Bug] Nothing happens when you update the library manga 
---

## Device information
* Tachiyomi version: Last
* Android version: 9
* Nothing happens when you update the library manga. 
* Device: honor 9 lite

## Steps to reproduce
1. Open the app 
2. Обновить библиотеку манги посредством нажатия кнопки в верхнем правом углу или резко листнуть сверху вниз 

## Issue/Request
?

## Other details
Additional details and attachments.

**Comment by scb261** [comment] 2020-12-28 13:21
1. Make sure you have enabled notifications from Tachiyomi
2. Go to *More > Settings> Library* and:
- Disable *Only update ongoing manga*
- Make sure you have categories you want in *categories to include in global update*
- Try to enable *Show update errors notifications* to see if there are any errors

P.S. *Last* is not a version, go to *More > About* to see what version do you have

**Comment by MM001-r** [comment] 2020-12-28 13:28
It didn't help. 
A notification about the manga update pops up, but it shuts down immediately

**Comment by scb261** [comment] 2020-12-28 13:38
Did you enable *Show update errors notifications* and did it show errors after updating? Also maybe battery optimization kills the update process, check out https://dontkillmyapp.com

**Comment by MM001-r** [comment] 2020-12-28 13:46
I turned on the error notifications, but he didn't show them, and about what kills the library, I turned it off a long time ago. Everything worked 2 days ago, and then the app stopped updating the library!

**Comment by arkon** [comment] 2020-12-28 15:05
There's no useful information here for us to help you. You'd need to try to provide logs if you think there's an error happening, or try other things like using a different version and seeing if that works.

**Comment by MM001-r** [comment] 2020-12-28 19:40
java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
When he updates individual tights, it makes this error.

**Comment by arkon** [comment] 2020-12-29 01:02
Duplicate of https://github.com/tachiyomiorg/tachiyomi-extensions/issues/5264

**Closed by arkon** 2020-12-29 01:02 UTC
Labels: needs more info
