### ISSUE TITLE
Categories Tab in Library got Scrolled to Random after Opening Manga Page or when Updating 

### ISSUE THREAD

**Issue by om3gakais3t** [tachiyomiorg/tachiyomi#6934] opened 2022-04-15 14:21 UTC
### Steps to reproduce

1. Have more than 5 Categories (Or the names are long enough for the tabs to be able to be scrolled for one or two screens)
2. Open one of the categories

> 

3. Open one of the manga and then back

> 

4. Also happens during updating library

### Expected behavior

After opening a manga page and press back, the active category tab should be (or used to be) seen on the screen

### Actual behavior

The category tab was scrolled to random position, often that the active tab couldn't be seen

### Tachiyomi version

0.13.2

### Android version

Android 11

### Device

Xiaomi Poco M3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-04-20 22:21
Duplicate of #5064

**Closed by arkon** 2022-04-20 22:21 UTC
Labels: Bug
