### ISSUE TITLE
[Feature Request] Select source destination when migrating 

### ISSUE THREAD

**Issue by Bexa2** [tachiyomiorg/tachiyomi#2613] opened 2020-02-20 16:00 UTC
Instead of having to scroll through all the sources we might have we could select source and destination and the it only shows those 2.
I'd like to migrate as many of my mangas as possible on Mangarock to Mangadex and with all the sources I have I have to scroll down a lot and also wait for the sources to load.

**Comment by Bexa2** [comment] 2020-02-20 16:04
Not interested in downloading another app (J2k)

**Comment by joseph619** [comment] 2020-02-20 19:53
This is not coming to Dev anytime soon (if ever), so you would have to be very patient.

**Comment by Bexa2** [comment] 2020-02-20 20:48
> This is not coming to Dev anytime soon (if ever), so you would have to be very patient.

No problem, just giving some feedback.

**Comment by Skcyte** [comment] 2020-02-21 15:31
Either you download a fork or just hoping the feature get implemented in the main app.
Someone make a fork because they think like you but did it themselves.

**Comment by arkon** [comment] 2020-02-21 15:32
It's a valid request for the main app, it's just a matter of prioritization.

**Comment by arkon** [comment] 2022-10-08 17:32
Duplicate of #6654

**Closed by arkon** 2022-10-08 17:32 UTC
Labels: Feature request
