### ISSUE TITLE
Manga Cover To be Display

### ISSUE THREAD

**Issue by Irfan000666** [tachiyomiorg/tachiyomi#8571] opened 2022-11-20 03:56 UTC
### Describe your suggested feature

Currently if you have downloaded alot of Manga and want to read offline some of the manga covers won't be shown and sometimes you forgot the name of the Manga you want to read and depend on the cover to know which is the one.. hopefully you are able to make all the Manga cover downloaded to be shown even though if you go offline. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment] 2022-11-20 07:53
Duplicate of #8476

**Closed by AntsyLich** 2022-11-20 07:53 UTC
Labels: Feature request
