### ISSUE TITLE
[Feature Request] Bookmarking of Filters

### ISSUE THREAD

**Issue by RedCrafterLP** [tachiyomiorg/tachiyomi#4200] opened 2020-12-27 15:51 UTC
I regularly check for new content uploaded under a certain combination of filter. I find it pretty annoying to always have to dial in my filter. So I thought it would be a good idea being able to save filter settings to find new content faster. It would be nice if you could consider my idea. Thanks for this great app.

**Comment by arkon** [comment] 2021-01-04 20:48
Duplicate of #1484

**Closed by arkon** 2021-01-04 20:48 UTC
Labels: feature
