### ISSUE TITLE
Categories in sources/extensions

### ISSUE THREAD

**Issue by MakuSensei** [tachiyomiorg/tachiyomi#1904] opened 2019-03-18 16:37 UTC
I wanted to recommend, that in the extensions section. Are grouped by content. Mangas, Hentai, Comics. 
That way it would be easier to know what sources to install.

**Comment by qwertyuser1983** [comment] 2019-04-22 07:39
A little problem.

A "wide" site like Mangadex, which has either mangas and hentais, would be listed twice or thrice. 

Except if You means tagging as opposed to categorising. A site can have several tags. :)

**Comment by joaoandre120** [comment] 2021-04-01 23:20
> A little problem.
> 
> A "wide" site like Mangadex, which has either mangas and hentais, would be listed twice or thrice.
> 
To avoid it, we could have the possibility to create category/lists for the installed extensions, like for the library, and choose then individually.

**Comment by Palloxin** [comment] 2021-08-11 15:59
I wish the app could create 2 categories of extensions (adult and not-adult extensions) where you could do your search without clogging and slowing the search with results of adult extensions and vice versa (when you look for adult stuff).

**Comment by arkon** [comment] 2022-07-09 22:51
Duplicate of #1758

**Closed by arkon** 2022-07-09 22:51 UTC
Labels: Feature request
