### ISSUE TITLE
[Feature Request] Have Webtoon Format remember position on page

### ISSUE THREAD

**Issue by Malkierian** [tachiyomiorg/tachiyomi#5042] opened 2021-05-07 20:40 UTC
Right now, when reading some webtoons with really long pages, the reader only remembers what page you're on, but sometimes these pages can be the equivalent of anywhere from 5-10 normal manga pages, and if you leave the webtoon and come back, it starts you back at the top of the page and you have to scroll, sometimes a significant distance, to get back to where you are. Instead, Tachiyomi should remember the x offset of the current page to make sure that the user only has to scroll maybe a screen's worth at most in order to return to their previous spot in the webtoon.

**Comment by kiriya-aoi** [comment] 2021-05-30 19:41
Duplicate of https://github.com/tachiyomiorg/tachiyomi/issues/3322

**Closed** 2021-05-30 20:42 UTC
Labels: feature
