### ISSUE TITLE
Ignore Categories And Search Entire Library When Using Search

### ISSUE THREAD

**Issue by zinklog2** [tachiyomiorg/tachiyomi#8613] opened 2022-11-25 09:43 UTC
### Describe your suggested feature

Because I have so many categories I have to manually swipe a lot to make sure it is not in my library. A setting to always search the entire library and display result would be nice
Alternatively it would be even better if the results of different categories are displayed on a single page under its category heading if multiple results from different categories are found.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-11-27 03:17
Duplicate of #3800

**Closed by arkon** 2022-11-27 03:17 UTC
Labels: Feature request
