### ISSUE TITLE
Daily Reading Limit

### ISSUE THREAD

**Issue by Jainex17** [tachiyomiorg/tachiyomi#9586] opened 2023-06-05 16:19 UTC
### Describe your suggested feature

The app currently lacks a daily reading limit feature, which can be problematic for users who want to manage their manga consumption and prevent excessive reading. I suggest addressing this issue by adding a daily reading limit option to the app.

Expected Behavior:

- Users should be able to set a maximum number of chapters they can read per day.
- Once the daily reading limit is reached, the app should prevent users from reading additional chapters.
- Users should have the option to reset the daily reading limit either manually or automatically.

### Other details

Additional Considerations:-

- The daily reading limit should be configurable in the app's settings.
- It is important to provide clear notifications or indicators when users approach or reach their daily reading limit.
- The implementation should be user-friendly and intuitive, ensuring a seamless experience.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2023-06-05 16:40
Duplicate of #4521

**Closed by Seishirou101** 2023-06-05 16:40 UTC
Labels: Feature request
