### ISSUE TITLE
Downloaded only doesn't actually skip undownloaded chapters when reading.

### ISSUE THREAD

**Issue by brandon-dodds** [tachiyomiorg/tachiyomi#8858] opened 2023-01-07 21:19 UTC
### Steps to reproduce

1. Download a chapter.
2. Read said chapter.
3. Next chapter will be one that isn't downloaded.

### Expected behavior

Downloaded only should only let you read chapters that are downloaded. This *is* the behaviour of manually selected the Downloaded filter, but on the Downloaded only global filter, it doesn't seem to work the same way.

### Actual behavior

The next chapter is shown instead, downloaded or not. 

### Tachiyomi version

0.14.3

### Android version

Android 13

### Device

Samsung Galaxy Note 10 Lite

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-01-07 21:22
Duplicate of #5463

**Closed by arkon** 2023-01-07 21:22 UTC
Labels: Bug
