### ISSUE TITLE
Tachiyomi claiming more and more internal storage despite saving downloaded chapters to SD card

### ISSUE THREAD

**Issue by Clavus** [tachiyomiorg/tachiyomi#5570] opened 2021-07-18 09:57 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

7.1.2

### Device

Nvidia Shield Tablet

### Steps to reproduce

I've set the download location to the external SD card (\storage\3A99-1900\) ever since I installed Tachiyomi. I verified with file browsing apps that the downloaded chapters are being stored on the SD card.

### Expected behavior

Downloaded chapters should only take up space on the SD card.

### Actual behavior

Downloaded chapters appear to also take up space on internal storage, besides the SD card storage. The system's storage browser shows Tachiyomi's "Data" taking up 6.54GB of internal storage. I'm now getting "storage space is running out" warnings on my tablet, while Tachiyomi is the only app I use on this device. Using file browsing apps I've tried to find any files on my internal storage that could be the cause (paying special attention to \Android\data\eu.kanade.tachiyomi\) but I can't find anything.

### Other details

Running Lineage OS 14.1.

**Comment by arkon** [comment] 2021-07-18 14:00
Have you cleared the chapter cache from the advanced settings?

**Comment by Clavus** [comment] 2021-07-18 14:22
I tried that, shows chapter cache as 0 bytes in size now.

**Comment by Clouddark75** [comment] 2021-07-20 16:41
Yah, it happens to me since the new stable builds, the data just keeps growing up at an alarming rate. For me right now is just eating 1.5 GB. I only had a couple of Mangas on the library. I have a duplicate of my library and history on another device with an old version of Tachi (0.10.12) and the data is just 120 MB (with the database updated as the same with my main device, it's just weird). For me, everything did start with the build 0.11.0. I don't have root access to none of my devices so, I can't check what's happening on that data folder.

**Comment by arkon** [comment] 2021-07-20 16:47
It's probably the cover cache. We'd need either more aggressively clear it or provide an advanced settings to do it.

**Comment by Clavus** [comment] 2021-07-20 16:47
I seem to have found a way to circumvent running out of space for now:

- Ran Tachiyomi's backup and saved it to my Google Drive
- I renamed the 'tachiyomi' folder on my SD card to avoid it being deleted in the next step
- Using the system's app browser I hit "clear data" on Tachiyomi, this freed up my internal storage
- Renamed the folder on the SD card back to 'tachiyomi' and checked that the download folder in the app points to it
- Open the app and restored the backup from my Google Drive

All my manga and their downloaded status are intact, but Tachiyomi no longer takes up a load of internal storage for now. I expect I'll have to do this periodically until this issue is fixed.

**Comment by Clavus** [comment] 2021-07-20 16:49
> It's probably the cover cache. We'd need either more aggressively clear it or provide an advanced settings to do it.

I doubt that's the case unless it's been saving duplicates of the same cover each check or something. The files of the cover cache also showed up in the internal storage where I'd expect them to be and the amount and file size didn't look out of the ordinary.

**Comment by ivaniskandar** [comment] 2021-07-20 16:57
In system settings can you check the detailed disk usage of tachiyomi? Like [this one here](https://user-images.githubusercontent.com/12537387/126364727-4a127f52-7426-4f81-80df-762bf84e3ba9.png).

**Comment by Clavus** [comment] 2021-07-20 17:00
On my OS it showed "Data" instead of "App Size", it was at over 6GB. Cache was minimal (~20MB, and easily cleared at the time), User Data was minimal. Total was over 6GB.

**Comment by paulo27ms** [comment] 2021-07-20 19:09
I'm not experiencing such alarming increases but also wondering where all this space is going:
Preview stats:
![IMG_20210720_194100](https://user-images.githubusercontent.com/13546823/126380841-7985afc4-a981-4799-8c36-51fde5a1c38a.jpg)

After clearing cache/database:
![IMG_20210720_194109](https://user-images.githubusercontent.com/13546823/126380864-1d7c031c-1dae-4890-a1de-b9bd8212cb72.jpg)

After importing backup to stable:
![IMG_20210720_194145](https://user-images.githubusercontent.com/13546823/126380879-276cc2b3-b434-4439-a5c7-4c4091e789d4.jpg)


My library is ~520 manga, 412 cover images on cover folder (for preview), stable had 22 covers initially so first I refresh all the manga metadata:
![IMG_20210720_200049](https://user-images.githubusercontent.com/13546823/126381340-e71ad85a-fc79-474e-b7f5-0d95a64b0b77.jpg)

Then I waited until all covers generated fully (almost, got to 390 cover files):
![IMG_20210720_200555](https://user-images.githubusercontent.com/13546823/126381418-67f1e585-f96b-448a-bd90-225ab4525252.jpg)

So my observations are that in Tachiyomi the storage space being used is either counting the cover folder or Tachiyomi is double loading covers (I guess for speed and validation purposes), which is fine.
But in my case preview is consuming much more space than it should compared to a fresh install and the cache is also ridiculous and the setting in the app doesn't clear it.

**Comment by arkon** [comment] 2023-02-12 22:35
I still think this has something to do with the cover cache (which I think changed around that old version with the migration to Coil). Related issue: #6215

There was also an advanced setting to clear WebView data, which might help a bit depending on how much stuff accumulated from that.

**Closed by arkon** 2023-02-12 22:35 UTC
Labels: Bug
