### ISSUE TITLE
Include/exclude categories from global updates 

### ISSUE THREAD

**Issue by zayin02** [tachiyomiorg/tachiyomi#5598] opened 2021-07-22 14:46 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

Preview r3606

### Android version

Android 11

### Device

SM-A015F

### Steps to reproduce

1. Go to More>Settings>Library>Global updates 
2. Try changing the include/exclude from global updates. 

### Expected behavior

The categories selected by the user should change to how they set it.

### Actual behavior

The categories stay to same no matter how the user changes it. 

### Other details

Someone reported today on discord but didn't open an issue on it. I tried it and had the same problem. 

Here is the video from the person:

https://user-images.githubusercontent.com/76571965/126658983-56ef4f66-26a2-4feb-969b-88acc210f80c.mp4

**Comment by paulo27ms** [comment] 2021-07-22 18:18
There's an ok button you have to click.

**Comment by zayin02** [comment] 2021-07-22 18:20
There is no "ok" button

**Comment by FourTOne5** [comment] 2021-07-22 18:21
Duplicate of #5562

**Comment by zayin02** [comment] 2021-07-22 18:21
Oh, I see #5562 explains why

**Closed** 2021-07-22 18:21 UTC
Labels: Bug

**Comment by zayin02** [comment] 2021-07-22 18:24
> Duplicate of #5562

I realized
