### ISSUE TITLE
Ability to manually change status of series

### ISSUE THREAD

**Issue by burner8557** [tachiyomiorg/tachiyomi#5515] opened 2021-07-08 06:20 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

A button in a series' options to change the status of a series.

Thank you, good app.

**Comment by CrepeTF** [comment] 2021-07-08 07:03
There's already a pull request for this
https://github.com/tachiyomiorg/tachiyomi/pull/5488

**Comment by arkon** [comment] 2023-10-28 21:09
Duplicate of #4398

**Closed by arkon** 2023-10-28 21:09 UTC
Labels: Feature request
