### ISSUE TITLE
Crash app when scroll manhwa in "Long Strip"

### ISSUE THREAD

**Issue by WiNE-iNEFF** [tachiyomiorg/tachiyomi#9635] opened 2023-06-24 22:51 UTC
### Steps to reproduce

1. Chouse manhwa with "long strip"
2. Scroll manhwa fast or slow
3. At some point, the application will close and will not even show errors

### Expected behavior

Can't crash app when i scroll chapter 

### Actual behavior

App crash

### Crash logs
```
06-25 01:47:51.936 32131 32131 E ACRA    : ACRA caught a FileNotFoundException for eu.kanade.tachiyomi.debug
06-25 01:47:51.936 32131 32131 E ACRA    : java.io.FileNotFoundException: /data/user/0/eu.kanade.tachiyomi.debug/cache/chapter_disk_cache/c3aca3946eb049001b2982db75e11894.0: open failed: ENOENT (No such file or directory)
06-25 01:47:51.936 32131 32131 E ACRA    : 	at libcore.io.IoBridge.open(IoBridge.java:574)
06-25 01:47:51.936 32131 32131 E ACRA    : 	at java.io.FileInputStream.<init>(FileInputStream.java:160)
06-25 01:47:51.936 32131 32131 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.loader.HttpPageLoader$_loadPage$2.invoke(SourceFile:15)
06-25 01:47:51.936 32131 32131 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.viewer.webtoon.WebtoonPageHolder$setImage$2.invokeSuspend(SourceFile:6)
06-25 01:47:51.936 32131 32131 E ACRA    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:12)
06-25 01:47:51.936 32131 32131 E ACRA    : 	at kotlinx.coroutines.DispatchedTask.run(SourceFile:112)
06-25 01:47:51.936 32131 32131 E ACRA    : 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(SourceFile:4)
06-25 01:47:51.936 32131 32131 E ACRA    : 	at kotlinx.coroutines.scheduling.TaskImpl.run(SourceFile:3)
06-25 01:47:51.936 32131 32131 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(SourceFile:1)
06-25 01:47:51.936 32131 32131 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:63)
06-25 01:47:51.936 32131 32131 E ACRA    : 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@c9db613, Dispatchers.Main]
06-25 01:47:51.936 32131 32131 E ACRA    : Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
06-25 01:47:51.936 32131 32131 E ACRA    : 	at libcore.io.Linux.open(Native Method)
06-25 01:47:51.936 32131 32131 E ACRA    : 	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
06-25 01:47:51.936 32131 32131 E ACRA    : 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
06-25 01:47:51.936 32131 32131 E ACRA    : 	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
06-25 01:47:51.936 32131 32131 E ACRA    : 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8263)
06-25 01:47:51.936 32131 32131 E ACRA    : 	at libcore.io.IoBridge.open(IoBridge.java:560)
06-25 01:47:51.936 32131 32131 E ACRA    : 	... 9 more
06-25 01:47:53.585  5550  5629 E SQLiteLog: (283) recovered 23 frames from WAL file /data/user/0/eu.kanade.tachiyomi.debug/databases/tachiyomi.db-wal
06-25 01:47:55.927  5881  5929 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
06-25 01:47:57.033  5881  6102 E SQLiteLog: (284) automatic index on C(manga_id)
06-25 01:47:57.033  5881  6102 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.14.6-5845 (standard, 344f5afd5, 103, 2023-06-17T21:08Z)
Android version: 13 (SDK 33)
Android build ID: TP1A.220624.014 release-keys
Device brand: vivo
Device manufacturer: vivo
Device name: V2205
Device model: V2205
Device product name: V2205_RU
```

### Tachiyomi version

App version: 0.14.6-5845 (standard, 344f5afd5, 103, 2023-06-17T21:08Z) 

### Android version

Android 13

### Device

Vivo y35

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by manavchaudhary1** [comment] 2023-06-25 06:02
I don't know why this is happening with most of the users BUT
Here's a solution to your problem 
OPEN  SETTINGS in tachiyomi >READER> then in paged section you will find "spilt wide page" option TURN IT ON .
My problem solved with it hope it will solve yours too.

**Comment by WiNE-iNEFF** [comment] 2023-06-25 16:02
> I don't know why this is happening with most of the users BUT
> Here's a solution to your problem 
> OPEN  SETTINGS in tachiyomi >READER> then in paged section you will find "spilt wide page" option TURN IT ON .
> My problem solved with it hope it will solve yours too.

I'll try to see what happens. Maybe it really will work

**Comment by WiNE-iNEFF** [comment] 2023-06-25 16:22
> I don't know why this is happening with most of the users BUT
> Here's a solution to your problem 
> OPEN  SETTINGS in tachiyomi >READER> then in paged section you will find "spilt wide page" option TURN IT ON .
> My problem solved with it hope it will solve yours too.

No, its no work

**Comment by arkon** [comment] 2023-07-01 02:31
Duplicate of #9564

**Closed by arkon** 2023-07-01 02:31 UTC
Labels: Bug
