### ISSUE TITLE
There should be a way to view downloaded chapters of migrated title that are not on the library

### ISSUE THREAD

**Issue by pseudo-demon** [tachiyomiorg/tachiyomi#8586] opened 2022-11-21 15:05 UTC
### Issues
When migrating, downloaded chapters does not migrate.
### 1. Add to Sorting
- [X] Downloaded ⬇️ (expand)
  - ✅ Show that already migrated

Would then show the title (this is an example):
* Solo leveling
* One-Punch Man

Then when you click on the _manga_ or _manhwa_ or _manhua_, it should not have "❤️ **In library**" on them, but "🖤 **Add to library**" with downloaded chapters inside.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-11-21 15:46
Duplicate of #2108

**Closed** 2022-11-21 15:46 UTC
Labels: Feature request

**Comment by pseudo-demon** [comment] 2022-11-21 18:33
### ⬅️ Worn and Torn Newbie 🔍 
Note: When migrating, your downloaded chapters will not be migrated. If you want to see the downloaded chapters, go to Tachiyomi/downloads using file explorer

extension_a
extension_b
