### ISSUE TITLE
[Feature Request] add rotation for this series

### ISSUE THREAD

**Issue by Noname-noragami** [tachiyomiorg/tachiyomi#4485] opened 2021-02-15 09:47 UTC
## Why/User Benefit/User Problem
(explain why this feature should be added)
For comfort (size of page, font size, the ratio between size of font and page) of  each series have it own style of rotation so we don't need to zoom in and out.
## What/Requirements
(explain how this feature would behave)
Rotation for this series

**Comment by scb261** [comment] 2021-02-15 09:56
Duplicate of #3521

**Closed** 2021-02-15 13:19 UTC
Labels: feature
