### ISSUE TITLE
Copy button stays and crashes app when pressed

### ISSUE THREAD

**Issue by strangeirdo** [tachiyomiorg/tachiyomi#9354] opened 2023-04-17 05:49 UTC
### Steps to reproduce

1. open any manga with a description
2. hold down on the description so that the copy button appears
3. leave the page, the copy button will now be at the top left
4. press the copy button
5. the app crashes

### Expected behavior

the copy button shouldn't stay after leaving the page

### Actual behavior

copy button permanently stays on the top left until you restart the app, staying even after a chapter.

### Crash logs

--------- beginning of main
04-17 01:18:20.069 10337 10337 E USNET   : USNET: appName: eu.kanade.tachiyomi
04-17 01:18:20.300 10337 10378 E SQLiteLog: (283) recovered 945 frames from WAL file /data/user/0/eu.kanade.tachiyomi/databases/tachiyomi.db-wal
04-17 01:18:48.836 11487 11487 E USNET   : USNET: appName: eu.kanade.tachiyomi
04-17 01:18:49.136 11487 11569 E FA      : Failed to load metadata: Package name not found: android.content.pm.PackageManager$NameNotFoundException: org.chromium.chrome: cq.a(:com.google.android.gms.dynamite_measurementdynamite@231312045@23.13.12 (190408-0):0)
04-17 01:18:49.136 11487 11569 E FA      : Failed to load metadata: Metadata bundle is null
04-17 01:18:50.067 11487 11777 E SQLiteLog: (284) automatic index on C(manga_id)
04-17 01:18:50.067 11487 11777 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
--------- beginning of crash
04-17 01:37:20.743 11487 11487 E AndroidRuntime: FATAL EXCEPTION: main
04-17 01:37:20.743 11487 11487 E AndroidRuntime: Process: eu.kanade.tachiyomi, PID: 11487
04-17 01:37:20.743 11487 11487 E AndroidRuntime: java.lang.IllegalArgumentException: Failed requirement.
04-17 01:37:20.743 11487 11487 E AndroidRuntime: 	at androidx.compose.foundation.text.selection.SelectionManager.requireContainerCoordinates$foundation_release(SelectionManager.kt:25)
04-17 01:37:20.743 11487 11487 E AndroidRuntime: 	at androidx.compose.foundation.text.selection.SelectionManager.copy$foundation_release(SelectionManager.kt:1)
04-17 01:37:20.743 11487 11487 E AndroidRuntime: 	at androidx.compose.foundation.text.selection.SelectionManager$showSelectionToolbar$1$1.invoke(SelectionManager.kt:3)
04-17 01:37:20.743 11487 11487 E AndroidRuntime: 	at androidx.compose.ui.platform.actionmodecallback.TextActionModeCallback.onActionItemClicked(TextActionModeCallback.android.kt:20)
04-17 01:37:20.743 11487 11487 E AndroidRuntime: 	at androidx.compose.ui.platform.actionmodecallback.FloatingTextActionModeCallback.onActionItemClicked(FloatingTextActionModeCallback.android.kt:3)
04-17 01:37:20.743 11487 11487 E AndroidRuntime: 	at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onActionItemClicked(DecorView.java:5202)
04-17 01:37:20.743 11487 11487 E AndroidRuntime: 	at com.android.internal.view.FloatingActionMode$3.onMenuItemSelected(FloatingActionMode.java:97)
04-17 01:37:20.743 11487 11487 E AndroidRuntime: 	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:788)
04-17 01:37:20.743 11487 11487 E AndroidRuntime: 	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
04-17 01:37:20.743 11487 11487 E AndroidRuntime: 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:935)
04-17 01:37:20.743 11487 11487 E AndroidRuntime: 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:925)
04-17 01:37:20.743 11487 11487 E AndroidRuntime: 	at com.android.internal.view.FloatingActionMode.lambda$setFloatingToolbar$0$FloatingActionMode(FloatingActionMode.java:128)
04-17 01:37:20.743 11487 11487 E AndroidRuntime: 	at com.android.internal.view.FloatingActionMode$$ExternalSyntheticLambda0.onMenuItemClick(Unknown Source:2)
04-17 01:37:20.743 11487 11487 E AndroidRuntime: 	at com.android.internal.widget.FloatingToolbar$FloatingToolbarPopup$2.onClick(FloatingToolbar.java:461)
04-17 01:37:20.743 11487 11487 E AndroidRuntime: 	at android.view.View.performClick(View.java:7792)
04-17 01:37:20.743 11487 11487 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7769)
04-17 01:37:20.743 11487 11487 E AndroidRuntime: 	at android.view.View.access$3800(View.java:910)
04-17 01:37:20.743 11487 11487 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:30218)
04-17 01:37:20.743 11487 11487 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
04-17 01:37:20.743 11487 11487 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-17 01:37:20.743 11487 11487 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
04-17 01:37:20.743 11487 11487 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
04-17 01:37:20.743 11487 11487 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8663)
04-17 01:37:20.743 11487 11487 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-17 01:37:20.743 11487 11487 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
04-17 01:37:20.743 11487 11487 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
04-17 01:37:20.746 11487 11487 E ACRA    : ACRA caught a IllegalArgumentException for eu.kanade.tachiyomi
04-17 01:37:20.746 11487 11487 E ACRA    : java.lang.IllegalArgumentException: Failed requirement.
04-17 01:37:20.746 11487 11487 E ACRA    : 	at androidx.compose.foundation.text.selection.SelectionManager.requireContainerCoordinates$foundation_release(SelectionManager.kt:25)
04-17 01:37:20.746 11487 11487 E ACRA    : 	at androidx.compose.foundation.text.selection.SelectionManager.copy$foundation_release(SelectionManager.kt:1)
04-17 01:37:20.746 11487 11487 E ACRA    : 	at androidx.compose.foundation.text.selection.SelectionManager$showSelectionToolbar$1$1.invoke(SelectionManager.kt:3)
04-17 01:37:20.746 11487 11487 E ACRA    : 	at androidx.compose.ui.platform.actionmodecallback.TextActionModeCallback.onActionItemClicked(TextActionModeCallback.android.kt:20)
04-17 01:37:20.746 11487 11487 E ACRA    : 	at androidx.compose.ui.platform.actionmodecallback.FloatingTextActionModeCallback.onActionItemClicked(FloatingTextActionModeCallback.android.kt:3)
04-17 01:37:20.746 11487 11487 E ACRA    : 	at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onActionItemClicked(DecorView.java:5202)
04-17 01:37:20.746 11487 11487 E ACRA    : 	at com.android.internal.view.FloatingActionMode$3.onMenuItemSelected(FloatingActionMode.java:97)
04-17 01:37:20.746 11487 11487 E ACRA    : 	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:788)
04-17 01:37:20.746 11487 11487 E ACRA    : 	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
04-17 01:37:20.746 11487 11487 E ACRA    : 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:935)
04-17 01:37:20.746 11487 11487 E ACRA    : 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:925)
04-17 01:37:20.746 11487 11487 E ACRA    : 	at com.android.internal.view.FloatingActionMode.lambda$setFloatingToolbar$0$FloatingActionMode(FloatingActionMode.java:128)
04-17 01:37:20.746 11487 11487 E ACRA    : 	at com.android.internal.view.FloatingActionMode$$ExternalSyntheticLambda0.onMenuItemClick(Unknown Source:2)
04-17 01:37:20.746 11487 11487 E ACRA    : 	at com.android.internal.widget.FloatingToolbar$FloatingToolbarPopup$2.onClick(FloatingToolbar.java:461)
04-17 01:37:20.746 11487 11487 E ACRA    : 	at android.view.View.performClick(View.java:7792)
04-17 01:37:20.746 11487 11487 E ACRA    : 	at android.view.View.performClickInternal(View.java:7769)
04-17 01:37:20.746 11487 11487 E ACRA    : 	at android.view.View.access$3800(View.java:910)
04-17 01:37:20.746 11487 11487 E ACRA    : 	at android.view.View$PerformClick.run(View.java:30218)
04-17 01:37:20.746 11487 11487 E ACRA    : 	at android.os.Handler.handleCallback(Handler.java:938)
04-17 01:37:20.746 11487 11487 E ACRA    : 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-17 01:37:20.746 11487 11487 E ACRA    : 	at android.os.Looper.loopOnce(Looper.java:226)
04-17 01:37:20.746 11487 11487 E ACRA    : 	at android.os.Looper.loop(Looper.java:313)
04-17 01:37:20.746 11487 11487 E ACRA    : 	at android.app.ActivityThread.main(ActivityThread.java:8663)
04-17 01:37:20.746 11487 11487 E ACRA    : 	at java.lang.reflect.Method.invoke(Native Method)
04-17 01:37:20.746 11487 11487 E ACRA    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
04-17 01:37:20.746 11487 11487 E ACRA    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
04-17 01:37:21.394 17814 17814 E USNET   : USNET: appName: eu.kanade.tachiyomi:acra
04-17 01:37:21.661 17814 17839 E SQLiteLog: (283) recovered 175 frames from WAL file /data/user/0/eu.kanade.tachiyomi/databases/tachiyomi.db-wal
04-17 01:37:22.624 17878 17878 E USNET   : USNET: appName: eu.kanade.tachiyomi
04-17 01:37:22.812 17878 17939 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
04-17 01:37:23.389 17878 18177 E SQLiteLog: (284) automatic index on C(manga_id)
04-17 01:37:23.389 17878 18177 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
04-17 01:37:42.963 17878 17878 E DecorView[]: Destroying unexpected ActionMode instance of TYPE_FLOATING; com.android.internal.view.FloatingActionMode@ffc3bac was not the current floating action mode! Expected null
04-17 01:37:54.240 17878 17878 E AndroidRuntime: FATAL EXCEPTION: main
04-17 01:37:54.240 17878 17878 E AndroidRuntime: Process: eu.kanade.tachiyomi, PID: 17878
04-17 01:37:54.240 17878 17878 E AndroidRuntime: java.lang.IllegalArgumentException: Failed requirement.
04-17 01:37:54.240 17878 17878 E AndroidRuntime: 	at androidx.compose.foundation.text.selection.SelectionManager.requireContainerCoordinates$foundation_release(SelectionManager.kt:25)
04-17 01:37:54.240 17878 17878 E AndroidRuntime: 	at androidx.compose.foundation.text.selection.SelectionManager.copy$foundation_release(SelectionManager.kt:1)
04-17 01:37:54.240 17878 17878 E AndroidRuntime: 	at androidx.compose.foundation.text.selection.SelectionManager$showSelectionToolbar$1$1.invoke(SelectionManager.kt:3)
04-17 01:37:54.240 17878 17878 E AndroidRuntime: 	at androidx.compose.ui.platform.actionmodecallback.TextActionModeCallback.onActionItemClicked(TextActionModeCallback.android.kt:20)
04-17 01:37:54.240 17878 17878 E AndroidRuntime: 	at androidx.compose.ui.platform.actionmodecallback.FloatingTextActionModeCallback.onActionItemClicked(FloatingTextActionModeCallback.android.kt:3)
04-17 01:37:54.240 17878 17878 E AndroidRuntime: 	at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onActionItemClicked(DecorView.java:5202)
04-17 01:37:54.240 17878 17878 E AndroidRuntime: 	at com.android.internal.view.FloatingActionMode$3.onMenuItemSelected(FloatingActionMode.java:97)
04-17 01:37:54.240 17878 17878 E AndroidRuntime: 	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:788)
04-17 01:37:54.240 17878 17878 E AndroidRuntime: 	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
04-17 01:37:54.240 17878 17878 E AndroidRuntime: 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:935)
04-17 01:37:54.240 17878 17878 E AndroidRuntime: 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:925)
04-17 01:37:54.240 17878 17878 E AndroidRuntime: 	at com.android.internal.view.FloatingActionMode.lambda$setFloatingToolbar$0$FloatingActionMode(FloatingActionMode.java:128)
04-17 01:37:54.240 17878 17878 E AndroidRuntime: 	at com.android.internal.view.FloatingActionMode$$ExternalSyntheticLambda0.onMenuItemClick(Unknown Source:2)
04-17 01:37:54.240 17878 17878 E AndroidRuntime: 	at com.android.internal.widget.FloatingToolbar$FloatingToolbarPopup$2.onClick(FloatingToolbar.java:461)
04-17 01:37:54.240 17878 17878 E AndroidRuntime: 	at android.view.View.performClick(View.java:7792)
04-17 01:37:54.240 17878 17878 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7769)
04-17 01:37:54.240 17878 17878 E AndroidRuntime: 	at android.view.View.access$3800(View.java:910)
04-17 01:37:54.240 17878 17878 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:30218)
04-17 01:37:54.240 17878 17878 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
04-17 01:37:54.240 17878 17878 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-17 01:37:54.240 17878 17878 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
04-17 01:37:54.240 17878 17878 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
04-17 01:37:54.240 17878 17878 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8663)
04-17 01:37:54.240 17878 17878 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-17 01:37:54.240 17878 17878 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
04-17 01:37:54.240 17878 17878 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
04-17 01:37:54.241 17878 17878 E ACRA    : ACRA caught a IllegalArgumentException for eu.kanade.tachiyomi
04-17 01:37:54.241 17878 17878 E ACRA    : java.lang.IllegalArgumentException: Failed requirement.
04-17 01:37:54.241 17878 17878 E ACRA    : 	at androidx.compose.foundation.text.selection.SelectionManager.requireContainerCoordinates$foundation_release(SelectionManager.kt:25)
04-17 01:37:54.241 17878 17878 E ACRA    : 	at androidx.compose.foundation.text.selection.SelectionManager.copy$foundation_release(SelectionManager.kt:1)
04-17 01:37:54.241 17878 17878 E ACRA    : 	at androidx.compose.foundation.text.selection.SelectionManager$showSelectionToolbar$1$1.invoke(SelectionManager.kt:3)
04-17 01:37:54.241 17878 17878 E ACRA    : 	at androidx.compose.ui.platform.actionmodecallback.TextActionModeCallback.onActionItemClicked(TextActionModeCallback.android.kt:20)
04-17 01:37:54.241 17878 17878 E ACRA    : 	at androidx.compose.ui.platform.actionmodecallback.FloatingTextActionModeCallback.onActionItemClicked(FloatingTextActionModeCallback.android.kt:3)
04-17 01:37:54.241 17878 17878 E ACRA    : 	at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onActionItemClicked(DecorView.java:5202)
04-17 01:37:54.241 17878 17878 E ACRA    : 	at com.android.internal.view.FloatingActionMode$3.onMenuItemSelected(FloatingActionMode.java:97)
04-17 01:37:54.241 17878 17878 E ACRA    : 	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:788)
04-17 01:37:54.241 17878 17878 E ACRA    : 	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
04-17 01:37:54.241 17878 17878 E ACRA    : 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:935)
04-17 01:37:54.241 17878 17878 E ACRA    : 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:925)
04-17 01:37:54.241 17878 17878 E ACRA    : 	at com.android.internal.view.FloatingActionMode.lambda$setFloatingToolbar$0$FloatingActionMode(FloatingActionMode.java:128)
04-17 01:37:54.241 17878 17878 E ACRA    : 	at com.android.internal.view.FloatingActionMode$$ExternalSyntheticLambda0.onMenuItemClick(Unknown Source:2)
04-17 01:37:54.241 17878 17878 E ACRA    : 	at com.android.internal.widget.FloatingToolbar$FloatingToolbarPopup$2.onClick(FloatingToolbar.java:461)
04-17 01:37:54.241 17878 17878 E ACRA    : 	at android.view.View.performClick(View.java:7792)
04-17 01:37:54.241 17878 17878 E ACRA    : 	at android.view.View.performClickInternal(View.java:7769)
04-17 01:37:54.241 17878 17878 E ACRA    : 	at android.view.View.access$3800(View.java:910)
04-17 01:37:54.241 17878 17878 E ACRA    : 	at android.view.View$PerformClick.run(View.java:30218)
04-17 01:37:54.241 17878 17878 E ACRA    : 	at android.os.Handler.handleCallback(Handler.java:938)
04-17 01:37:54.241 17878 17878 E ACRA    : 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-17 01:37:54.241 17878 17878 E ACRA    : 	at android.os.Looper.loopOnce(Looper.java:226)
04-17 01:37:54.241 17878 17878 E ACRA    : 	at android.os.Looper.loop(Looper.java:313)
04-17 01:37:54.241 17878 17878 E ACRA    : 	at android.app.ActivityThread.main(ActivityThread.java:8663)
04-17 01:37:54.241 17878 17878 E ACRA    : 	at java.lang.reflect.Method.invoke(Native Method)
04-17 01:37:54.241 17878 17878 E ACRA    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
04-17 01:37:54.241 17878 17878 E ACRA    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
04-17 01:37:55.836 18595 18595 E USNET   : USNET: appName: eu.kanade.tachiyomi
04-17 01:37:56.009 18595 18635 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
04-17 01:37:56.550 18595 18788 E SQLiteLog: (284) automatic index on C(manga_id)
04-17 01:37:56.550 18595 18788 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
04-17 01:38:08.446 18595 18595 E AndroidRuntime: FATAL EXCEPTION: main
04-17 01:38:08.446 18595 18595 E AndroidRuntime: Process: eu.kanade.tachiyomi, PID: 18595
04-17 01:38:08.446 18595 18595 E AndroidRuntime: java.lang.IllegalArgumentException: Failed requirement.
04-17 01:38:08.446 18595 18595 E AndroidRuntime: 	at androidx.compose.foundation.text.selection.SelectionManager.requireContainerCoordinates$foundation_release(SelectionManager.kt:25)
04-17 01:38:08.446 18595 18595 E AndroidRuntime: 	at androidx.compose.foundation.text.selection.SelectionManager.copy$foundation_release(SelectionManager.kt:1)
04-17 01:38:08.446 18595 18595 E AndroidRuntime: 	at androidx.compose.foundation.text.selection.SelectionManager$showSelectionToolbar$1$1.invoke(SelectionManager.kt:3)
04-17 01:38:08.446 18595 18595 E AndroidRuntime: 	at androidx.compose.ui.platform.actionmodecallback.TextActionModeCallback.onActionItemClicked(TextActionModeCallback.android.kt:20)
04-17 01:38:08.446 18595 18595 E AndroidRuntime: 	at androidx.compose.ui.platform.actionmodecallback.FloatingTextActionModeCallback.onActionItemClicked(FloatingTextActionModeCallback.android.kt:3)
04-17 01:38:08.446 18595 18595 E AndroidRuntime: 	at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onActionItemClicked(DecorView.java:5202)
04-17 01:38:08.446 18595 18595 E AndroidRuntime: 	at com.android.internal.view.FloatingActionMode$3.onMenuItemSelected(FloatingActionMode.java:97)
04-17 01:38:08.446 18595 18595 E AndroidRuntime: 	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:788)
04-17 01:38:08.446 18595 18595 E AndroidRuntime: 	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
04-17 01:38:08.446 18595 18595 E AndroidRuntime: 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:935)
04-17 01:38:08.446 18595 18595 E AndroidRuntime: 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:925)
04-17 01:38:08.446 18595 18595 E AndroidRuntime: 	at com.android.internal.view.FloatingActionMode.lambda$setFloatingToolbar$0$FloatingActionMode(FloatingActionMode.java:128)
04-17 01:38:08.446 18595 18595 E AndroidRuntime: 	at com.android.internal.view.FloatingActionMode$$ExternalSyntheticLambda0.onMenuItemClick(Unknown Source:2)
04-17 01:38:08.446 18595 18595 E AndroidRuntime: 	at com.android.internal.widget.FloatingToolbar$FloatingToolbarPopup$2.onClick(FloatingToolbar.java:461)
04-17 01:38:08.446 18595 18595 E AndroidRuntime: 	at android.view.View.performClick(View.java:7792)
04-17 01:38:08.446 18595 18595 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7769)
04-17 01:38:08.446 18595 18595 E AndroidRuntime: 	at android.view.View.access$3800(View.java:910)
04-17 01:38:08.446 18595 18595 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:30218)
04-17 01:38:08.446 18595 18595 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
04-17 01:38:08.446 18595 18595 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-17 01:38:08.446 18595 18595 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
04-17 01:38:08.446 18595 18595 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
04-17 01:38:08.446 18595 18595 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8663)
04-17 01:38:08.446 18595 18595 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-17 01:38:08.446 18595 18595 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
04-17 01:38:08.446 18595 18595 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
04-17 01:38:08.447 18595 18595 E ACRA    : ACRA caught a IllegalArgumentException for eu.kanade.tachiyomi
04-17 01:38:08.447 18595 18595 E ACRA    : java.lang.IllegalArgumentException: Failed requirement.
04-17 01:38:08.447 18595 18595 E ACRA    : 	at androidx.compose.foundation.text.selection.SelectionManager.requireContainerCoordinates$foundation_release(SelectionManager.kt:25)
04-17 01:38:08.447 18595 18595 E ACRA    : 	at androidx.compose.foundation.text.selection.SelectionManager.copy$foundation_release(SelectionManager.kt:1)
04-17 01:38:08.447 18595 18595 E ACRA    : 	at androidx.compose.foundation.text.selection.SelectionManager$showSelectionToolbar$1$1.invoke(SelectionManager.kt:3)
04-17 01:38:08.447 18595 18595 E ACRA    : 	at androidx.compose.ui.platform.actionmodecallback.TextActionModeCallback.onActionItemClicked(TextActionModeCallback.android.kt:20)
04-17 01:38:08.447 18595 18595 E ACRA    : 	at androidx.compose.ui.platform.actionmodecallback.FloatingTextActionModeCallback.onActionItemClicked(FloatingTextActionModeCallback.android.kt:3)
04-17 01:38:08.447 18595 18595 E ACRA    : 	at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onActionItemClicked(DecorView.java:5202)
04-17 01:38:08.447 18595 18595 E ACRA    : 	at com.android.internal.view.FloatingActionMode$3.onMenuItemSelected(FloatingActionMode.java:97)
04-17 01:38:08.447 18595 18595 E ACRA    : 	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:788)
04-17 01:38:08.447 18595 18595 E ACRA    : 	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
04-17 01:38:08.447 18595 18595 E ACRA    : 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:935)
04-17 01:38:08.447 18595 18595 E ACRA    : 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:925)
04-17 01:38:08.447 18595 18595 E ACRA    : 	at com.android.internal.view.FloatingActionMode.lambda$setFloatingToolbar$0$FloatingActionMode(FloatingActionMode.java:128)
04-17 01:38:08.447 18595 18595 E ACRA    : 	at com.android.internal.view.FloatingActionMode$$ExternalSyntheticLambda0.onMenuItemClick(Unknown Source:2)
04-17 01:38:08.447 18595 18595 E ACRA    : 	at com.android.internal.widget.FloatingToolbar$FloatingToolbarPopup$2.onClick(FloatingToolbar.java:461)
04-17 01:38:08.447 18595 18595 E ACRA    : 	at android.view.View.performClick(View.java:7792)
04-17 01:38:08.447 18595 18595 E ACRA    : 	at android.view.View.performClickInternal(View.java:7769)
04-17 01:38:08.447 18595 18595 E ACRA    : 	at android.view.View.access$3800(View.java:910)
04-17 01:38:08.447 18595 18595 E ACRA    : 	at android.view.View$PerformClick.run(View.java:30218)
04-17 01:38:08.447 18595 18595 E ACRA    : 	at android.os.Handler.handleCallback(Handler.java:938)
04-17 01:38:08.447 18595 18595 E ACRA    : 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-17 01:38:08.447 18595 18595 E ACRA    : 	at android.os.Looper.loopOnce(Looper.java:226)
04-17 01:38:08.447 18595 18595 E ACRA    : 	at android.os.Looper.loop(Looper.java:313)
04-17 01:38:08.447 18595 18595 E ACRA    : 	at android.app.ActivityThread.main(ActivityThread.java:8663)
04-17 01:38:08.447 18595 18595 E ACRA    : 	at java.lang.reflect.Method.invoke(Native Method)
04-17 01:38:08.447 18595 18595 E ACRA    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
04-17 01:38:08.447 18595 18595 E ACRA    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
04-17 01:38:09.843 18899 18899 E USNET   : USNET: appName: eu.kanade.tachiyomi
04-17 01:38:10.002 18899 18936 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
04-17 01:38:10.525 18899 19100 E SQLiteLog: (284) automatic index on C(manga_id)
04-17 01:38:10.525 18899 19100 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.14.6 (standard, c615f4d, 101, 2023-04-16T15:14Z)
Android version: 12 (SDK 31)
Android build ID: SP1A.210812.016.G970WVLS8IWA1
Device brand: samsung
Device manufacturer: samsung
Device name: beyond0q
Device model: SM-G970W
Device product name: beyond0qltecs

### Tachiyomi version

0.14.6

### Android version

Android 12

### Device

Samsung Galaxy S10e

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment] 2023-04-17 05:54
Duplicate of #9073

**Closed** 2023-04-17 05:54 UTC
Labels: Bug, Duplicate
