### ISSUE TITLE
Unable to browse "Local source" after manually add manga(s) to sdcard

### ISSUE THREAD

**Issue by mancoi** [tachiyomiorg/tachiyomi#7511] opened 2022-07-11 11:35 UTC
### Steps to reproduce

1. Update Tachiyomi to v0.13.5
2. Copy one or more comics to the "local" folder of Tachiyomi on sdcard. For example: I want to add manga X, then I follow these steps: Create X folder → Put X.cbz inside X folder → Copy X folder to sdcard/Tachiyomi/local/
3. Open Tachiyomi
4. Navigate to "Browse" tab
5. Tap on "Local source"

### Expected behavior

The "Local source" screen should be opened and show the manga "X"

### Actual behavior

Error screen appeared saying:
 /storage/<sdcard name>/Tachiyomi/local/<manga name>/cover.jpg: open failed: EACCES (Permission denied)

### Crash logs

--------- beginning of main
07-11 17:28:35.451  7698  7698 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
07-11 17:28:35.586  7698  7730 E Perf    : Fail to get file list eu.kanade.tachiyomi
07-11 17:28:35.586  7698  7730 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
07-11 17:28:35.586  7698  7730 E Perf    : Fail to get file list oat
07-11 17:28:35.586  7698  7730 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
07-11 17:28:36.156  7698  7772 E SQLiteLog: (284) automatic index on C(manga_id)
07-11 17:28:36.156  7698  7772 E SQLiteLog: (284) automatic index on R(manga_id)
07-11 17:28:36.156  7698  7772 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
07-11 17:28:46.277  7884  7884 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
07-11 17:28:46.412  7884  7917 E Perf    : Fail to get file list eu.kanade.tachiyomi
07-11 17:28:46.412  7884  7917 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
07-11 17:28:46.412  7884  7917 E Perf    : Fail to get file list oat
07-11 17:28:46.413  7884  7917 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
07-11 17:28:46.832  7884  7949 E SQLiteLog: (284) automatic index on C(manga_id)
07-11 17:28:46.832  7884  7949 E SQLiteLog: (284) automatic index on R(manga_id)
07-11 17:28:46.832  7884  7949 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
07-11 17:28:50.116  7884  7884 E BrowseSourceController: java.io.FileNotFoundException: /storage/A157-1651/Tachiyomi/local/Online - The Comic/cover.jpg: open failed: EACCES (Permission denied)
07-11 17:28:50.116  7884  7884 E BrowseSourceController: 	at libcore.io.IoBridge.open(IoBridge.java:496)
07-11 17:28:50.116  7884  7884 E BrowseSourceController: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
07-11 17:28:50.116  7884  7884 E BrowseSourceController: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
07-11 17:28:50.116  7884  7884 E BrowseSourceController: 	at eu.kanade.tachiyomi.source.LocalSource$Companion.updateCover(LocalSource.kt:12)
07-11 17:28:50.116  7884  7884 E BrowseSourceController: 	at eu.kanade.tachiyomi.source.LocalSource.access$updateCover(LocalSource.kt:12)
07-11 17:28:50.116  7884  7884 E BrowseSourceController: 	at eu.kanade.tachiyomi.source.LocalSource$fetchSearchManga$3$1.invokeSuspend(LocalSource.kt:15)
07-11 17:28:50.116  7884  7884 E BrowseSourceController: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
07-11 17:28:50.116  7884  7884 E BrowseSourceController: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
07-11 17:28:50.116  7884  7884 E BrowseSourceController: 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:21)
07-11 17:28:50.116  7884  7884 E BrowseSourceController: 	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:4)
07-11 17:28:50.116  7884  7884 E BrowseSourceController: 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:10)
07-11 17:28:50.116  7884  7884 E BrowseSourceController: 	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
07-11 17:28:50.116  7884  7884 E BrowseSourceController: 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:2)
07-11 17:28:50.116  7884  7884 E BrowseSourceController: 	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
07-11 17:28:50.116  7884  7884 E BrowseSourceController: 	at eu.kanade.tachiyomi.source.LocalSource.fetchSearchManga(LocalSource.kt:18)
07-11 17:28:50.116  7884  7884 E BrowseSourceController: 	at eu.kanade.tachiyomi.source.LocalSource.fetchPopularManga(LocalSource.kt:1)
07-11 17:28:50.116  7884  7884 E BrowseSourceController: 	at eu.kanade.tachiyomi.ui.browse.source.browse.SourcePager.requestNextPage$suspendImpl(SourcePager.kt:6)
07-11 17:28:50.116  7884  7884 E BrowseSourceController: 	at eu.kanade.tachiyomi.ui.browse.source.browse.SourcePager.requestNextPage(Unknown Source:0)
07-11 17:28:50.116  7884  7884 E BrowseSourceController: 	at eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourcePresenter$requestNext$1.invokeSuspend(BrowseSourcePresenter.kt:4)
07-11 17:28:50.116  7884  7884 E BrowseSourceController: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
07-11 17:28:50.116  7884  7884 E BrowseSourceController: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
07-11 17:28:50.116  7884  7884 E BrowseSourceController: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
07-11 17:28:50.116  7884  7884 E BrowseSourceController: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
07-11 17:28:50.116  7884  7884 E BrowseSourceController: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
07-11 17:28:50.116  7884  7884 E BrowseSourceController: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)
07-11 17:28:50.116  7884  7884 E BrowseSourceController: Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
07-11 17:28:50.116  7884  7884 E BrowseSourceController: 	at libcore.io.Linux.open(Native Method)
07-11 17:28:50.116  7884  7884 E BrowseSourceController: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
07-11 17:28:50.116  7884  7884 E BrowseSourceController: 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
07-11 17:28:50.116  7884  7884 E BrowseSourceController: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
07-11 17:28:50.116  7884  7884 E BrowseSourceController: 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7317)
07-11 17:28:50.116  7884  7884 E BrowseSourceController: 	at libcore.io.IoBridge.open(IoBridge.java:482)
07-11 17:28:50.116  7884  7884 E BrowseSourceController: 	... 24 more
07-11 17:29:49.217  7884  7884 E BrowseSourceController: java.io.FileNotFoundException: /storage/A157-1651/Tachiyomi/local/Online - The Comic/cover.jpg: open failed: EACCES (Permission denied)
07-11 17:29:49.217  7884  7884 E BrowseSourceController: 	at libcore.io.IoBridge.open(IoBridge.java:496)
07-11 17:29:49.217  7884  7884 E BrowseSourceController: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
07-11 17:29:49.217  7884  7884 E BrowseSourceController: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
07-11 17:29:49.217  7884  7884 E BrowseSourceController: 	at eu.kanade.tachiyomi.source.LocalSource$Companion.updateCover(LocalSource.kt:12)
07-11 17:29:49.217  7884  7884 E BrowseSourceController: 	at eu.kanade.tachiyomi.source.LocalSource.access$updateCover(LocalSource.kt:12)
07-11 17:29:49.217  7884  7884 E BrowseSourceController: 	at eu.kanade.tachiyomi.source.LocalSource$fetchSearchManga$3$1.invokeSuspend(LocalSource.kt:15)
07-11 17:29:49.217  7884  7884 E BrowseSourceController: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
07-11 17:29:49.217  7884  7884 E BrowseSourceController: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
07-11 17:29:49.217  7884  7884 E BrowseSourceController: 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:21)
07-11 17:29:49.217  7884  7884 E BrowseSourceController: 	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:4)
07-11 17:29:49.217  7884  7884 E BrowseSourceController: 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:10)
07-11 17:29:49.217  7884  7884 E BrowseSourceController: 	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
07-11 17:29:49.217  7884  7884 E BrowseSourceController: 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:2)
07-11 17:29:49.217  7884  7884 E BrowseSourceController: 	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
07-11 17:29:49.217  7884  7884 E BrowseSourceController: 	at eu.kanade.tachiyomi.source.LocalSource.fetchSearchManga(LocalSource.kt:18)
07-11 17:29:49.217  7884  7884 E BrowseSourceController: 	at eu.kanade.tachiyomi.source.LocalSource.fetchPopularManga(LocalSource.kt:1)
07-11 17:29:49.217  7884  7884 E BrowseSourceController: 	at eu.kanade.tachiyomi.ui.browse.source.browse.SourcePager.requestNextPage$suspendImpl(SourcePager.kt:6)
07-11 17:29:49.217  7884  7884 E BrowseSourceController: 	at eu.kanade.tachiyomi.ui.browse.source.browse.SourcePager.requestNextPage(Unknown Source:0)
07-11 17:29:49.217  7884  7884 E BrowseSourceController: 	at eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourcePresenter$requestNext$1.invokeSuspend(BrowseSourcePresenter.kt:4)
07-11 17:29:49.217  7884  7884 E BrowseSourceController: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
07-11 17:29:49.217  7884  7884 E BrowseSourceController: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
07-11 17:29:49.217  7884  7884 E BrowseSourceController: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
07-11 17:29:49.217  7884  7884 E BrowseSourceController: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
07-11 17:29:49.217  7884  7884 E BrowseSourceController: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
07-11 17:29:49.217  7884  7884 E BrowseSourceController: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)
07-11 17:29:49.217  7884  7884 E BrowseSourceController: Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
07-11 17:29:49.217  7884  7884 E BrowseSourceController: 	at libcore.io.Linux.open(Native Method)
07-11 17:29:49.217  7884  7884 E BrowseSourceController: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
07-11 17:29:49.217  7884  7884 E BrowseSourceController: 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
07-11 17:29:49.217  7884  7884 E BrowseSourceController: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
07-11 17:29:49.217  7884  7884 E BrowseSourceController: 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7317)
07-11 17:29:49.217  7884  7884 E BrowseSourceController: 	at libcore.io.IoBridge.open(IoBridge.java:482)
07-11 17:29:49.217  7884  7884 E BrowseSourceController: 	... 24 more
07-11 17:32:33.094  8599  8599 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
07-11 17:32:33.755  8599  8631 E Perf    : Fail to get file list eu.kanade.tachiyomi
07-11 17:32:33.755  8599  8631 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
07-11 17:32:33.759  8599  8631 E Perf    : Fail to get file list oat
07-11 17:32:33.760  8599  8631 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
07-11 17:32:34.588  8599  8662 E SQLiteLog: (284) automatic index on C(manga_id)
07-11 17:32:34.588  8599  8662 E SQLiteLog: (284) automatic index on R(manga_id)
07-11 17:32:34.588  8599  8662 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
07-11 17:32:34.714  8599  8710 E chromium: [ERROR:simple_backend_impl.cc(756)] Simple Cache Backend: cache directory inaccessible right after creation; path: /data/user/0/eu.kanade.tachiyomi/cache/WebView/Default/HTTP Cache/Code Cache/wasm
07-11 17:32:34.723  8599  8711 E chromium: [ERROR:disk_cache.cc(204)] Unable to create cache
07-11 17:32:38.144  8599  8599 E BrowseSourceController: java.io.FileNotFoundException: /storage/A157-1651/Tachiyomi/local/Online - The Comic/cover.jpg: open failed: EACCES (Permission denied)
07-11 17:32:38.144  8599  8599 E BrowseSourceController: 	at libcore.io.IoBridge.open(IoBridge.java:496)
07-11 17:32:38.144  8599  8599 E BrowseSourceController: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
07-11 17:32:38.144  8599  8599 E BrowseSourceController: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
07-11 17:32:38.144  8599  8599 E BrowseSourceController: 	at eu.kanade.tachiyomi.source.LocalSource$Companion.updateCover(LocalSource.kt:12)
07-11 17:32:38.144  8599  8599 E BrowseSourceController: 	at eu.kanade.tachiyomi.source.LocalSource.access$updateCover(LocalSource.kt:12)
07-11 17:32:38.144  8599  8599 E BrowseSourceController: 	at eu.kanade.tachiyomi.source.LocalSource$fetchSearchManga$3$1.invokeSuspend(LocalSource.kt:15)
07-11 17:32:38.144  8599  8599 E BrowseSourceController: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
07-11 17:32:38.144  8599  8599 E BrowseSourceController: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
07-11 17:32:38.144  8599  8599 E BrowseSourceController: 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:21)
07-11 17:32:38.144  8599  8599 E BrowseSourceController: 	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:4)
07-11 17:32:38.144  8599  8599 E BrowseSourceController: 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:10)
07-11 17:32:38.144  8599  8599 E BrowseSourceController: 	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
07-11 17:32:38.144  8599  8599 E BrowseSourceController: 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:2)
07-11 17:32:38.144  8599  8599 E BrowseSourceController: 	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
07-11 17:32:38.144  8599  8599 E BrowseSourceController: 	at eu.kanade.tachiyomi.source.LocalSource.fetchSearchManga(LocalSource.kt:18)
07-11 17:32:38.144  8599  8599 E BrowseSourceController: 	at eu.kanade.tachiyomi.source.LocalSource.fetchPopularManga(LocalSource.kt:1)
07-11 17:32:38.144  8599  8599 E BrowseSourceController: 	at eu.kanade.tachiyomi.ui.browse.source.browse.SourcePager.requestNextPage$suspendImpl(SourcePager.kt:6)
07-11 17:32:38.144  8599  8599 E BrowseSourceController: 	at eu.kanade.tachiyomi.ui.browse.source.browse.SourcePager.requestNextPage(Unknown Source:0)
07-11 17:32:38.144  8599  8599 E BrowseSourceController: 	at eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourcePresenter$requestNext$1.invokeSuspend(BrowseSourcePresenter.kt:4)
07-11 17:32:38.144  8599  8599 E BrowseSourceController: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
07-11 17:32:38.144  8599  8599 E BrowseSourceController: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
07-11 17:32:38.144  8599  8599 E BrowseSourceController: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
07-11 17:32:38.144  8599  8599 E BrowseSourceController: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
07-11 17:32:38.144  8599  8599 E BrowseSourceController: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
07-11 17:32:38.144  8599  8599 E BrowseSourceController: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)
07-11 17:32:38.144  8599  8599 E BrowseSourceController: Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
07-11 17:32:38.144  8599  8599 E BrowseSourceController: 	at libcore.io.Linux.open(Native Method)
07-11 17:32:38.144  8599  8599 E BrowseSourceController: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
07-11 17:32:38.144  8599  8599 E BrowseSourceController: 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
07-11 17:32:38.144  8599  8599 E BrowseSourceController: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
07-11 17:32:38.144  8599  8599 E BrowseSourceController: 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7317)
07-11 17:32:38.144  8599  8599 E BrowseSourceController: 	at libcore.io.IoBridge.open(IoBridge.java:482)
07-11 17:32:38.144  8599  8599 E BrowseSourceController: 	... 24 more
App version: 0.13.5 (standard, 26ddc6e, 81, 2022-07-08T20:12Z)
Android version: 10 (SDK 29)
Android build ID: 52.1.A.3.49
Device brand: Sony
Device manufacturer: Sony
Device name: H8266
Device model: H8266
Device product name: H8266

### Tachiyomi version

0.13.5

### Android version

Android 10

### Device

Sony Xperia XZ2

### Other details

This issue only occur when the "X" folder only exists on sdcard. I noticed on version 0.13.4 Tachiyomi automatically create a folder with the same name with the "X" folder on sdcard, but since upgraded to 0.13.5, Tachiyomi isn't creating any so I tried manually created an empty folder named "X" on the internal storage → restart Tachiyomi → Able to browse the local source. 

And, if the X manga folder is originally copied to the internal storage, this problem does not occur. 

To summary:
Manga folder only exists on sdcard/Tachiyomi/local/ → Problem occurs
Manga folder only exists on internal storage/Tachiyomi/local/ → All is good

I guess Tachiyomi is trying to open the X folder on the internal storage without creating it, so this problem occured.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-07-23 15:16
Should be a duplicate of #7577

**Closed by arkon** 2022-07-23 15:16 UTC
Labels: Bug
