### ISSUE TITLE
[Bug] r3417 broke "tap title to search" feature

### ISSUE THREAD

**Issue by ptoump** [tachiyomiorg/tachiyomi#5221] opened 2021-05-28 15:50 UTC
## Device information
* Tachiyomi version: r3417
* Android version: 11
* Device: tab S7+

## Steps to reproduce
1. Go to any manga chapter list
2. Tap on the manga name

## Issue/Request
Search is not initiated by taping on the manga name.
Search still works on the author's name.

## Other details
UI on portrait in tablet was perfectly fine before, didn't need to change.. Side by side on portrait is awkward (I believe because of this change and moving the etitle to the top, the search functionality broke - so it's not totally irrelevant...)

**Comment by arkon** [comment] 2021-05-28 16:14
Duplicate of #5175

**Closed by arkon** 2021-05-28 16:14 UTC
