### ISSUE TITLE
Save Filters at Source 

### ISSUE THREAD

**Issue by derinakcay8** [tachiyomiorg/tachiyomi#9087] opened 2023-02-13 22:06 UTC
### Describe your suggested feature

Instead of constantly selecting the filter one by one, I think it would be much better if we could save the filter and directly click on it and apply the filters.
![6ba1fda3-f124-409d-bbb0-ed51e6356af5](https://user-images.githubusercontent.com/121522858/218584480-c3e00529-fa26-43ea-a399-975576845df9.jpg)

### Other details

this photo from tachiyomisy.İf you ask me why you dont use tachiyomisy,its because reading history and reading history  on tachiyomi only backup manga in library 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-02-14 22:27
Duplicate of #1484

**Closed by arkon** 2023-02-14 22:27 UTC
Labels: Feature request
