### ISSUE TITLE
[Bug] "Download Successful" notification that keeps coming back

### ISSUE THREAD

**Issue by kjgeyumubdutmjtuyj** [tachiyomiorg/tachiyomi#4335] opened 2021-01-23 10:32 UTC
## Device information
* Tachiyomi version: Preview r3013
* Android version: 10 QKQ1.191215.002 (MIUI 12.0.3.0)
* Device: Redmi Note 9S

## Steps to reproduce
1. Settings > Downloads > Delete chapters > After reading: Last read chapter (Unsure if this is the root cause, was told by someone from discord)
2. Finish reading a chapter from any source
3. "Download successful" notification in notification shade without pop up or sound

### Expected behavior
Swipe away to remove the notification or tap to go to download screen to get rid of the notification

### Actual behavior
Notification gone but comes back after repeating Steps 2

## Other details
Issues persisted after clearing data, uninstall then reinstall

**Comment by scb261** [comment] 2021-01-23 11:38
Duplicate of #4309, fixed, wait for next release

**Closed** 2021-01-23 14:28 UTC
Labels: bug
