### ISSUE TITLE
New reading mode double page

### ISSUE THREAD

**Issue by hayderalsal** [tachiyomiorg/tachiyomi#6187] opened 2021-11-02 11:00 UTC
### Describe your suggested feature

Hi guys i have been using this amazing app for years and. 2 years ago i bought a table and i thought it would be amazing if two pages reading mode add to the app like that photo
![Screenshot_20211102-125619_Chrome](https://user-images.githubusercontent.com/59695204/139834499-75b50f9c-5a84-4c2e-a128-c085bc26f924.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment] 2021-11-02 11:21
Duplicate of #149

**Closed by loocool2** 2021-11-02 11:21 UTC
Labels: Feature request
