### ISSUE TITLE
Grouping/Folder feature needed

### ISSUE THREAD

**Issue by kaedea** [tachiyomiorg/tachiyomi#8337] opened 2022-10-29 16:37 UTC
### Describe your suggested feature

For some mangas, I have to subscribe the same one from several Sources, and these sources are alawys displayed in disorder in the homepage.

I think it is a good solution to group the same manga of different sources into a folder and then display just one folder in the homepage, therefore we can checkout all the same manga in just one folder.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-10-29 16:38
Duplicate of #1803

**Closed by arkon** 2022-10-29 16:38 UTC
Labels: Feature request
