### ISSUE TITLE
Extension installing crash add update install limit for extension update 

### ISSUE THREAD

**Issue by Character95** [tachiyomiorg/tachiyomi#8864] opened 2023-01-08 10:31 UTC
### Steps to reproduce

1.open app
2.Browse/Extensions
3.update all button
4.app crash.

### Expected behavior

Add a button for installing first 10-30extension installing (staging app for install) to avoid crash

### Actual behavior

Trying to install 200-300 extension by clicking button (update all) app crash...

### Crash logs

tachiyomi_crash_logs

--------- beginning of crash
12-31 03:24:10.048 27869 27869 E AndroidRuntime: FATAL EXCEPTION: main
12-31 03:24:10.048 27869 27869 E AndroidRuntime: Process: eu.kanade.tachiyomi.debug, PID: 27869
12-31 03:24:10.048 27869 27869 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{eu.kanade.tachiyomi.debug/eu.kanade.tachiyomi.ui.webview.WebViewActivity}: java.io.IOException: You must setup the Address to communicate with Kavita
12-31 03:24:10.048 27869 27869 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3576)
12-31 03:24:10.048 27869 27869 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3748)
12-31 03:24:10.048 27869 27869 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
12-31 03:24:10.048 27869 27869 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
12-31 03:24:10.048 27869 27869 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
12-31 03:24:10.048 27869 27869 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2187)
12-31 03:24:10.048 27869 27869 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-31 03:24:10.048 27869 27869 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:236)
12-31 03:24:10.048 27869 27869 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8057)
12-31 03:24:10.048 27869 27869 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-31 03:24:10.048 27869 27869 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
12-31 03:24:10.048 27869 27869 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
12-31 03:24:10.048 27869 27869 E AndroidRuntime: Caused by: java.io.IOException: You must setup the Address to communicate with Kavita
12-31 03:24:10.048 27869 27869 E AndroidRuntime: 	at eu.kanade.tachiyomi.extension.all.kavita.Kavita.doLogin(Kavita.kt:1103)
12-31 03:24:10.048 27869 27869 E AndroidRuntime: 	at eu.kanade.tachiyomi.extension.all.kavita.Kavita.headersBuilder(Kavita.kt:854)
12-31 03:24:10.048 27869 27869 E AndroidRuntime: 	at eu.kanade.tachiyomi.source.online.HttpSource$headers$2.invoke(HttpSource.kt:2)
12-31 03:24:10.048 27869 27869 E AndroidRuntime: 	at eu.kanade.tachiyomi.source.online.HttpSource$headers$2.invoke(HttpSource.kt:1)
12-31 03:24:10.048 27869 27869 E AndroidRuntime: 	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:21)
12-31 03:24:10.048 27869 27869 E AndroidRuntime: 	at eu.kanade.tachiyomi.source.online.HttpSource.getHeaders(HttpSource.kt:3)
12-31 03:24:10.048 27869 27869 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.webview.WebViewActivity.onCreate(WebViewActivity.kt:105)
12-31 03:24:10.048 27869 27869 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8142)
12-31 03:24:10.048 27869 27869 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8114)
12-31 03:24:10.048 27869 27869 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
12-31 03:24:10.048 27869 27869 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3549)
12-31 03:24:10.048 27869 27869 E AndroidRuntime: 	... 11 more
--------- beginning of system
--------- beginning of main
App version: 0.14.3-5405 (standard, 30e030bb8, 93, 2023-01-07T21:09Z)
Android version: 11 (SDK 30)
Android build ID: RP1A.200720.011
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: begonia
Device model: Redmi Note 8 Pro
Device product name: begonia_eea

### Tachiyomi version

0.14.3-5405 (standard, 30e030bb8, 93, 2023-01-07T21:09Z)

### Android version

Android version: 11 (SDK 30)

### Device

Xiaomi Redmi Note 8 Pro

### Other details

i can install around 30 app extensions simultaneously  without crashing app on this phone.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-01-08 15:50
Duplicate of #7694

**Closed by arkon** 2023-01-08 15:50 UTC
Labels: Bug
