### ISSUE TITLE
Global search not working

### ISSUE THREAD

**Issue by fuuimz** [tachiyomiorg/tachiyomi#10122] opened 2023-11-07 15:08 UTC
### Steps to reproduce

I search manga name browse tab (global search)
page is blank no indication of loading and doesn't load
when i search manga name in single extension it works though

### Expected behavior

Manga to be searched in every extension and result tab to show so i can add manga to library from many extension filters

### Actual behavior

blank page nothing happens after i click search

### Crash logs

![Screenshot_20231107-165224_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/87863966/baf50575-c21c-403d-b3a7-610e59b661e9)

### Tachiyomi version

0.14.7

### Android version

Android 11

### Device

Samsung A30

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-11-08 03:20
Duplicate of #8919

You'll want to either pin some sources or disable that setting.

**Closed by arkon** 2023-11-08 03:20 UTC
Labels: Bug
