### ISSUE TITLE
Add "+/-" buttons to tracker

### ISSUE THREAD

**Issue by leveste** [tachiyomiorg/tachiyomi#6332] opened 2021-12-08 08:20 UTC
### Describe your suggested feature

Basically just a small QOL. It'd be nice if next to the chapter count in the tracker, we had an option to increment or decrement the count by one(a "+" on the right and a "-" on the left), rather than having to go and manually select the number, which is more useful when binging.

I know there's an option to automatically increment the count when a chapter has been read, but I tend to keep it off due to stuff like weird chapter numbering or because the chapter was a speedscan and I want to re-read the proper release.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-01-05 23:21
Duplicate of #2139

Note that you can just swipe up/down.

**Closed by arkon** 2022-01-05 23:21 UTC
Labels: Feature request
