### ISSUE TITLE
Filter / search for tags in sources

### ISSUE THREAD

**Issue by theindomie** [tachiyomiorg/tachiyomi#2284] opened 2019-10-16 15:11 UTC
###  Why/Project's Benefit/Existing Problem
Personally using ninehentai and scrolling the tag was fine at first, then it became more annoying when you have to scroll just to exclude some tag you dont want ~~like ugly bastard~~.
Idk how many ppl out there using ninehentai source, but it surely will make the life better if there is search for tag. 

### Other Details

**Comment by xKelvin** [comment] 2021-07-26 11:45
Any update on this? 

This would also be especially handy for sources which have a mix of SFW and ecchi content. With this feature you could easily exclude the `ecchi` tag for example (assuming content is correctly tagged) when you want only SFW content of a particular source.

**Comment by stevenyomi** [comment] 2023-01-23 23:11
Duplicate of #5539

**Closed by stevenyomi** 2023-01-23 23:11 UTC
Labels: Feature request
