### ISSUE TITLE
Issue with dual pages split

### ISSUE THREAD

**Issue by Light1712** [tachiyomiorg/tachiyomi#5696] opened 2021-08-10 16:02 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.0](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.12.0)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.12.1

### Android version

Android 10

### Device

Xiaomi Pocophone F1

### Steps to reproduce

Dual page split

### Expected behavior

When using dual pages split you should see both halves of the dual page

### Actual behavior

Sometimes the second half of the page does not appear and immediately skips to the next page.

**Comment by arkon** [comment] 2023-03-06 00:13
Duplicate of #6719

**Closed by arkon** 2023-03-06 00:13 UTC
Labels: Bug
