### ISSUE TITLE
[Feature Request] orphan uninstall and form

### ISSUE THREAD

**Issue by binyaminyblatt** [tachiyomiorg/tachiyomi#4691] opened 2021-03-22 12:31 UTC
---

## Why/User Benefit/User Problem
I feel when a extension becomes decrepit and is removed and therefore should be removed from everybody else's device it would help people to know which mangas are being orphaned as well as it would help to know which extensions are actually being used￼￼ ￼￼

## What/Requirements
Before clicking on the uninstall button there should be a confirmation that you are aware that this list of mangas will be orphaned and if you uninstall￼ and possibly the ability to migrate before uninstalling￼

**Comment by scb261** [comment] 2021-03-22 17:08
Duplicate of #3787

**Closed** 2021-03-22 17:11 UTC
Labels: feature

**Comment by binyaminyblatt** [comment] 2021-03-23 07:44
￼sorry I was told that it wasn't open on discord
