### ISSUE TITLE
Bulk Migration from one source to another

### ISSUE THREAD

**Issue by Naresh-Babu** [tachiyomiorg/tachiyomi#8502] opened 2022-11-11 17:04 UTC
### Describe your suggested feature

Most often when we find that a source is deprecated/removed we would have to move the mangas to another source one by one and this is not feasible for large libraries such as 100+ entries .

It would be nice to have a bulk migration feature.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-11-11 17:08
Duplicate of #1729

**Closed** 2022-11-11 17:08 UTC
Labels: Feature request
