### ISSUE TITLE
[Google Drive Backup] <Allows users to backup data to Google drive>

### ISSUE THREAD

**Issue by notsheldon** [tachiyomiorg/tachiyomi#4831] opened 2021-04-13 06:44 UTC
**PLEASE READ THIS**

I acknowledge that:

- I have updated to the latest version of the app (stable is v0.10.10)
- I have updated all extensions
- If this is an issue with an extension, that I should be opening an issue in https://github.com/tachiyomiorg/tachiyomidssxtensio

---

## Why/User Benefit/User Problem
In the event a user's device breaks unexpectedly, the user will have a back up to Google drive/OneDrive automatically. This cuts out the user having to manually back up data to a cloud service

## What/Requirements
(explain how this feature would behave) 
Create folder in cloud service called "Tachiyomi backups" and uses that folder to save backups. User can delete manually or can save how many backups are wanted

**Comment by joseph619** [comment] 2021-04-13 09:01
Duplicate of #912

**Closed** 2021-04-13 12:31 UTC
Labels: feature
