### ISSUE TITLE
Function support. Can you add support for webdav or other remote backup records in the later update.

### ISSUE THREAD

**Issue by thereone** [tachiyomiorg/tachiyomi#9208] opened 2023-03-14 10:04 UTC
### Describe your suggested feature

Function support. Can you add support for webdav or other remote backup records in the later update.
For example, the synchronization of backup software such as Google cloud onedrive S3storage webdav and the private cloud

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2023-03-14 13:12
Duplicate of #912

**Closed by stevenyomi** 2023-03-14 13:12 UTC
Labels: Feature request
