### ISSUE TITLE
Wrong date when updating library

### ISSUE THREAD

**Issue by timeholder0** [tachiyomiorg/tachiyomi#6618] opened 2022-02-10 09:45 UTC
### Steps to reproduce

1. update library manually
2. it shows all the manga updated today but labelled as updated yesterday

### Expected behavior

It should say it was updated today

### Actual behavior

It says it was updated yesterday

### Tachiyomi version

0.13.1

### Android version

11

### Device

Poco x3 pro

### Other details

I'm in "stable" miui

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by FourTOne5** [comment] 2022-02-10 10:25
can you give screenshot?

**Comment by timeholder0** [comment] 2022-02-10 11:54
> 

![Uploading Screenshot_2022-02-10-08-50-18-333_eu.kanade.tachiyomi.jpg…]()

**Comment by arkon** [comment] 2022-03-06 03:28
Duplicate of #6709

**Closed by arkon** 2022-03-06 03:28 UTC
Labels: Bug
