### ISSUE TITLE
Randomly crashes while reading

### ISSUE THREAD

**Issue by Enzycal** [tachiyomiorg/tachiyomi#8409] opened 2022-11-01 15:34 UTC
### Steps to reproduce

1. Open a manga chapter
2. Tachiyomi sometimes randomly crashes while reading

### Expected behavior

Would expect it to not crash

### Actual behavior

Tachiyomi crashes

### Crash logs

--------- beginning of crash
11-01 15:45:38.220 12761 12761 E AndroidRuntime: FATAL EXCEPTION: main
11-01 15:45:38.220 12761 12761 E AndroidRuntime: Process: eu.kanade.tachiyomi, PID: 12761
11-01 15:45:38.220 12761 12761 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Index: 21, Size: 19
11-01 15:45:38.220 12761 12761 E AndroidRuntime: 	at java.util.ArrayList.add(ArrayList.java:483)
11-01 15:45:38.220 12761 12761 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.pager.PagerViewerAdapter.setChapters(PagerViewerAdapter.kt:179)
11-01 15:45:38.220 12761 12761 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.pager.PagerViewer.setChaptersInternal(PagerViewer.kt:63)
11-01 15:45:38.220 12761 12761 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.pager.PagerViewer.access$setIdle(PagerViewer.kt:9)
11-01 15:45:38.220 12761 12761 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.pager.PagerViewer$1.onPageScrollStateChanged(PagerViewer.kt:8)
11-01 15:45:38.220 12761 12761 E AndroidRuntime: 	at androidx.viewpager.widget.DirectionalViewPager.setScrollState(DirectionalViewPager.java:29)
11-01 15:45:38.220 12761 12761 E AndroidRuntime: 	at androidx.viewpager.widget.DirectionalViewPager$3.run(DirectionalViewPager.java:4)
11-01 15:45:38.220 12761 12761 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1108)
11-01 15:45:38.220 12761 12761 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:866)
11-01 15:45:38.220 12761 12761 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:792)
11-01 15:45:38.220 12761 12761 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
11-01 15:45:38.220 12761 12761 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
11-01 15:45:38.220 12761 12761 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-01 15:45:38.220 12761 12761 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
11-01 15:45:38.220 12761 12761 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
11-01 15:45:38.220 12761 12761 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8663)
11-01 15:45:38.220 12761 12761 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-01 15:45:38.220 12761 12761 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
11-01 15:45:38.220 12761 12761 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
11-01 16:30:40.730  2677  2677 E AndroidRuntime: FATAL EXCEPTION: main
11-01 16:30:40.730  2677  2677 E AndroidRuntime: Process: eu.kanade.tachiyomi, PID: 2677
11-01 16:30:40.730  2677  2677 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Index: 23, Size: 20
11-01 16:30:40.730  2677  2677 E AndroidRuntime: 	at java.util.ArrayList.add(ArrayList.java:483)
11-01 16:30:40.730  2677  2677 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.pager.PagerViewerAdapter.setChapters(PagerViewerAdapter.kt:179)
11-01 16:30:40.730  2677  2677 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.pager.PagerViewer.setChaptersInternal(PagerViewer.kt:63)
11-01 16:30:40.730  2677  2677 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.pager.PagerViewer.access$setIdle(PagerViewer.kt:9)
11-01 16:30:40.730  2677  2677 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.pager.PagerViewer$1.onPageScrollStateChanged(PagerViewer.kt:8)
11-01 16:30:40.730  2677  2677 E AndroidRuntime: 	at androidx.viewpager.widget.DirectionalViewPager.setScrollState(DirectionalViewPager.java:29)
11-01 16:30:40.730  2677  2677 E AndroidRuntime: 	at androidx.viewpager.widget.DirectionalViewPager$3.run(DirectionalViewPager.java:4)
11-01 16:30:40.730  2677  2677 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1108)
11-01 16:30:40.730  2677  2677 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:866)
11-01 16:30:40.730  2677  2677 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:792)
11-01 16:30:40.730  2677  2677 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
11-01 16:30:40.730  2677  2677 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
11-01 16:30:40.730  2677  2677 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-01 16:30:40.730  2677  2677 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
11-01 16:30:40.730  2677  2677 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
11-01 16:30:40.730  2677  2677 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8663)
11-01 16:30:40.730  2677  2677 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-01 16:30:40.730  2677  2677 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
11-01 16:30:40.730  2677  2677 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
--------- beginning of main
11-01 16:30:40.730  2677  2677 E ACRA    : ACRA caught a IndexOutOfBoundsException for eu.kanade.tachiyomi
11-01 16:30:40.730  2677  2677 E ACRA    : java.lang.IndexOutOfBoundsException: Index: 23, Size: 20
11-01 16:30:40.730  2677  2677 E ACRA    : 	at java.util.ArrayList.add(ArrayList.java:483)
11-01 16:30:40.730  2677  2677 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.viewer.pager.PagerViewerAdapter.setChapters(PagerViewerAdapter.kt:179)
11-01 16:30:40.730  2677  2677 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.viewer.pager.PagerViewer.setChaptersInternal(PagerViewer.kt:63)
11-01 16:30:40.730  2677  2677 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.viewer.pager.PagerViewer.access$setIdle(PagerViewer.kt:9)
11-01 16:30:40.730  2677  2677 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.viewer.pager.PagerViewer$1.onPageScrollStateChanged(PagerViewer.kt:8)
11-01 16:30:40.730  2677  2677 E ACRA    : 	at androidx.viewpager.widget.DirectionalViewPager.setScrollState(DirectionalViewPager.java:29)
11-01 16:30:40.730  2677  2677 E ACRA    : 	at androidx.viewpager.widget.DirectionalViewPager$3.run(DirectionalViewPager.java:4)
11-01 16:30:40.730  2677  2677 E ACRA    : 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1108)
11-01 16:30:40.730  2677  2677 E ACRA    : 	at android.view.Choreographer.doCallbacks(Choreographer.java:866)
11-01 16:30:40.730  2677  2677 E ACRA    : 	at android.view.Choreographer.doFrame(Choreographer.java:792)
11-01 16:30:40.730  2677  2677 E ACRA    : 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
11-01 16:30:40.730  2677  2677 E ACRA    : 	at android.os.Handler.handleCallback(Handler.java:938)
11-01 16:30:40.730  2677  2677 E ACRA    : 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-01 16:30:40.730  2677  2677 E ACRA    : 	at android.os.Looper.loopOnce(Looper.java:226)
11-01 16:30:40.730  2677  2677 E ACRA    : 	at android.os.Looper.loop(Looper.java:313)
11-01 16:30:40.730  2677  2677 E ACRA    : 	at android.app.ActivityThread.main(ActivityThread.java:8663)
11-01 16:30:40.730  2677  2677 E ACRA    : 	at java.lang.reflect.Method.invoke(Native Method)
11-01 16:30:40.730  2677  2677 E ACRA    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
11-01 16:30:40.730  2677  2677 E ACRA    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
11-01 16:30:41.313 24941 24941 E USNET   : USNET: appName: eu.kanade.tachiyomi:acra
11-01 16:30:41.414 24941 24966 E SQLiteLog: (283) recovered 278 frames from WAL file /data/user/0/eu.kanade.tachiyomi/databases/tachiyomi.db-wal
11-01 16:30:46.746 25107 25107 E USNET   : USNET: appName: eu.kanade.tachiyomi
11-01 16:30:47.144 25107 25146 E SQLiteLog: (5) statement aborts at 1: [PRAGMA journal_mode=TRUNCATE] database is locked
11-01 16:30:50.282 25107 25250 E SQLiteLog: (284) automatic index on C(manga_id)
11-01 16:30:50.282 25107 25250 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.14.2 (standard, 3222247, 91, 2022-10-31T21:42Z)
Android version: 12 (SDK 31)
Android build ID: SP1A.210812.016.N975FXXU8HVGA
Device brand: samsung
Device manufacturer: samsung
Device name: d2s
Device model: SM-N975F
Device product name: d2seea

### Tachiyomi version

0.14.2

### Android version

Android 12

### Device

Samsung Galaxy Note 10+

### Other details

Doesn't happen often

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-12-05 20:37
Duplicate of #6523

**Closed by arkon** 2022-12-05 20:37 UTC
Labels: Bug
