### ISSUE TITLE
[Feature Request] New Sources Disabled on Install

### ISSUE THREAD

**Issue by clem193** [tachiyomiorg/tachiyomi#4305] opened 2021-01-17 18:42 UTC
## Why/User Benefit/User Problem
Everytime a multi-sources agregator extension update itself it (often) come with new source(s) that always get enabled by default, so the user need to manually disable these new sources every single time so it doesn't clog up his source list with unwanted sources and doesn't slow down his global (multi sources) searches by searching on dozen of sources the user doesn't care about.

## What/Requirements
Simply have a toggable option somewhere so newly installed sources can be disabled by default on the source list.

**Comment by arkon** [comment] 2021-01-17 19:32
Duplicate of #2821

**Closed by arkon** 2021-01-17 19:32 UTC
Labels: feature
