### ISSUE TITLE
Option to skip folder selection to store files with SAF or Storage permission in Android 9 and earlier

### ISSUE THREAD

**Issue by sam-gq** [tachiyomiorg/tachiyomi#10353] opened 2024-01-08 00:07 UTC
### Describe your suggested feature

I would like to skip an option at setting up storage in Android 9. I have nothing to do if I open the files on it from file managers and other apps.
![Screenshot_20240108-073902](https://github.com/tachiyomiorg/tachiyomi/assets/80607823/86cfb692-c6b4-4764-8d74-4d1687cf4c68)

So I suggest to add an option to store all files and stuff to `../Android/data/eu.kanade.tachiyomi/` without granting storage permission, or using SAF in Android 10 or 11+ which I think is my best option not to mess my files and folders.

In favor of increasing privacy and speed that I do strictly deny some apps still requiring setting up storage permission or SAF.

And I think some file managers can't see that directory, so its desired to change later in settings by setting up just like the same way in `0.15.1`.

### Other details

_no response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2024-01-08 00:15
Duplicate of #10270

**Closed** 2024-01-08 00:15 UTC
Labels: Feature request
