### ISSUE TITLE
Library not updating but individual update works

### ISSUE THREAD

**Issue by wel21** [tachiyomiorg/tachiyomi#10373] opened 2024-01-08 16:06 UTC
### Steps to reproduce

Manually trigger update library thru pull down gesture on Library or Updates tab or any method to update library (do not close or minimize the app)

### Expected behavior

Upon update, manhwa/manga/manhua that has updates on web should be captured

### Actual behavior

No updates captured after updating library. Instead, the update will be captured if you go to the manhwa and update it manually. I also noticed that the completion progress of update is quite fast.

Sample with flame comics extension.

The God of War Who Regressed to Level 2 has update 1hr ago in 
![Screenshot_20240108_233701_Samsung Internet (1)](https://github.com/tachiyomiorg/tachiyomi/assets/32331198/d19790fe-0e0e-45b6-b596-c402c24e4276)

No updates captured after updating library.
![Screenshot_20240108_233543_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/32331198/fdcb6229-dd86-43a2-a15a-46cb96478df9)

Update the manhwa manually
![Screenshot_20240108_233709_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/32331198/2a8f634b-e0de-4fc9-909e-3bcff87705de)
![Screenshot_20240108_233715_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi/assets/32331198/64da1d90-9c90-461d-b37e-c6e4816584db)

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/13863370/tachiyomi_crash_logs.txt)

### Tachiyomi version

0.15.1

### Android version

14

### Device

Samsung S23 Ultra

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2024-01-08 19:09
Duplicate of #10313

**Closed by arkon** 2024-01-08 19:09 UTC
Labels: Bug
