### ISSUE TITLE
Pages become bluer.

### ISSUE THREAD

**Issue by mcOz1** [tachiyomiorg/tachiyomi#5828] opened 2021-08-31 08:55 UTC
### Steps to reproduce

1. Open chapter on manga
2. click arrow in keyboard

### Expected behavior

Pages scroll

### Actual behavior

Pages scroll and become bluer.

### Tachiyomi version

0.12.1

### Android version

Android 9

### Device

nox player samsung galaxy s10

### Other details

I'm using emulator. This bug appears only in reader mod. In browser at application, nothing changes.
when open chapter:
![on open](https://user-images.githubusercontent.com/71328023/131473212-b29b0522-7098-4a21-a48b-5b0b6c63b102.PNG)
after click on arrow:
![after click](https://user-images.githubusercontent.com/71328023/131473220-cbaf1d22-aa08-4cbf-9aea-358cfb5f97a0.PNG)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2021-08-31 12:32
Duplicate of #5727

**Closed by arkon** 2021-08-31 12:32 UTC
Labels: Bug
