### ISSUE TITLE
Can't install extensions

### ISSUE THREAD

**Issue by Xorio71** [tachiyomiorg/tachiyomi#7415] opened 2022-06-30 00:08 UTC
### Steps to reproduce

1. Enter Tachiyomi
2. Go to the extensions.
3. Tap on "Install".

### Expected behavior

Extensions should be downloaded and then I should be prompted to install them.

### Actual behavior

I tap "download", "pending" appears for a second, before it changes to "retry".

### Crash logs

[2022-06-30_02.58.zip](https://github.com/tachiyomiorg/tachiyomi/files/9015251/2022-06-30_02.58.zip)

### Tachiyomi version

0.13.4

### Android version

Android 12

### Device

Redmi Note 9 Pro

### Other details

I'm using a custom ROM called PixelOS (AOSP based), which has spoofed my device as a Google Pixel 6 Pro.

Also, I've cleared the data of the Package Installer application.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-07-03 21:15
Duplicate of #4106

**Closed by arkon** 2022-07-03 21:15 UTC
Labels: Bug
