### ISSUE TITLE
Define time for the sources update frequency

### ISSUE THREAD

**Issue by Soviann** [tachiyomiorg/tachiyomi#5929] opened 2021-09-18 09:58 UTC
### Describe your suggested feature

Currently you can only set the frequency at which the sources are updated, it would be nice to be able to specify a time to serve as the basis for that.
Exemple : I set the time at 6AM and the frequency at 12 hours, the updates will happen at 6AM and 6PM.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by paulo27ms** [comment] 2021-09-18 10:42
Duplicate of https://github.com/tachiyomiorg/tachiyomi/issues/3589

**Closed** 2021-09-18 10:43 UTC
Labels: Feature request
