### ISSUE TITLE
Migrate All

### ISSUE THREAD

**Issue by Dexter0211** [tachiyomiorg/tachiyomi#6203] opened 2021-11-06 10:59 UTC
### Describe your suggested feature

It should migrate "all" manga/manhwa/manhua to other source cause it's time consuming transfering all my manga/manhwa/manhua one by one because the source was down , can't be open and slow update.. there should be a "all migrate feature"..
Example Manhwa top is currently down for about 3 weeks? So I want to migrate all my "Things" to mangahub..

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment] 2021-11-06 10:59
Duplicate of #1729

**Closed by loocool2** 2021-11-06 10:59 UTC
Labels: Feature request
