### ISSUE TITLE
App crashes when search for extension 

### ISSUE THREAD

**Issue by Astrokinng** [tachiyomiorg/tachiyomi#10075] opened 2023-10-27 20:17 UTC
### Steps to reproduce

1.open app
2.go to browse
3.got to extension
4.search extension
5.app closes 

### Expected behavior

The app shouldnt close or crash down when searching for extension. 

### Actual behavior

The app crashes 

### Tachiyomi version

App version: 0.14.6-6132

### Android version

Android 13

### Device

Samsung galaxy s23ultra 

### Other details

https://github.com/tachiyomiorg/tachiyomi/assets/89287848/314adb94-59d5-4f73-833e-111cf9c900c4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-10-27 20:31
Duplicate of #10069

**Closed by arkon** 2023-10-27 20:31 UTC
Labels: Bug
