### ISSUE TITLE
[Bug] tachiyomi Crash

### ISSUE THREAD

**Issue by deividgabrielpeira** [tachiyomiorg/tachiyomi#5170] opened 2021-05-24 12:18 UTC
## Device information
* Tachiyomi version: 0.10.12
* Android version: Android 8.1 Oreo
* Device: Samsung Galaxy J4+

## Steps to reproduce
1. read any manga or stand still for 2 minutes with 20 seconds, doing nothing (in my case it happens)
2. Quickly go to reading any comic

### Expected behavior
Normal comic opens(manga).

### Actual behavior
App crashes

## Other details
[Crash #1.](https://app.box.com/s/1lgguxninsxvngwz9ys8uqit3ae8x1vp)
[Crash #2](https://app.box.com/s/qra5s9z9fr95jfrcfqw4ypn18pznwlkn)

**Comment by arkon** [comment] 2021-05-24 13:33
Duplicate of #5151

**Closed by arkon** 2021-05-24 13:33 UTC
Labels: bug
