### ISSUE TITLE
Feature Request : Automatic Download When Connected to a WiFi Network

### ISSUE THREAD

**Issue by TheKingTermux** [tachiyomiorg/tachiyomi#7198] opened 2022-05-25 11:58 UTC
### Describe your suggested feature

Requires auto download feature if connected to a Wi-Fi network

### Other details

I think that by adding the auto download feature if connected to a WiFi network, it can auto-download comics that are already in the download queue, without having to go to the download queue and click the start download button.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-05-28 13:26
Duplicate of #959

**Closed by arkon** 2022-05-28 13:26 UTC
Labels: Feature request
