### ISSUE TITLE
Saves new copies of images instead of overwriting old ones

### ISSUE THREAD

**Issue by aaaaaad333** [tachiyomiorg/tachiyomi#9943] opened 2023-09-17 22:41 UTC
### Steps to reproduce

1. Open a chapter
2. Long tap an image
3. Tap "Save"

### Expected behavior

If the image already exists, it's overwritten.

### Actual behavior

New copies of a saved image are created, with an increasing number in parentheses eg. (2), (3), (4), etc.

### Tachiyomi version

0.14.6

### Android version

12

### Device

Nokia 5.4

### Other details

I know this was fixed in [#8162](https://github.com/tachiyomiorg/tachiyomi/pull/8162) but I'm experiencing the problem all the same. It occurred to me now that maybe the fix hasn't made it to the stable release yet, if so let me know and I'll close this issue.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-09-21 02:21
That was supposedly released in v0.14.0 and I can't reproduce it on my device nor in emulators.

**Comment by arkon** [comment] 2023-09-21 12:28
Ah it only happens if you have the setting to have them in folders enabled.

**Closed** 2023-09-22 20:16 UTC
Labels: Bug
