### ISSUE TITLE
History view feature.

### ISSUE THREAD

**Issue by Missionevitable10** [tachiyomiorg/tachiyomi#8558] opened 2022-11-18 14:44 UTC
### Describe your suggested feature

Return the old history page, where the last read chapter can be viewed regard less of the chapters read. New history page has a round about method, which kinda feel annoying.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-11-18 15:44
Duplicate of #8454

**Closed by arkon** 2022-11-18 15:44 UTC
Labels: Feature request
