### ISSUE TITLE
Webtoon Viewer Zoom Issues

### ISSUE THREAD

**Issue by jsilvermist** [tachiyomiorg/tachiyomi#9445] opened 2023-05-03 23:18 UTC
### Steps to reproduce

The webtoon viewer seems to be causing some invisible scaling issues after you zoom out past 100% once.

When you zoom out past 100% (ie. having bars on the right and left since the width is less than 100% from zooming out) and then zoom back to fit screen by double tapping, the touch targets and end of chapter are both bugged.

### Expected behavior

When you zoom out and back in, you should be able to see all the way to the bottom of the last page, and the touch targets should remain centered and unscaled.

### Actual behavior

When you are zoomed out and go back to 100%, the invisible touch targets become actually zoomed as well (vertically bound at top), so instead of touching the middle to show the overlay, you have to touch ~75% down the page, or more or less depending on the max previous zoom out.

Another issue is that for the last chapter (ie. no existing next chapter), you can't scroll all the way to the bottom by the same offset as the touch controls. (ie. if the middle touch target is ~80% down the page, ~80% of the screen height worth of page is unscrollable)

### Tachiyomi version

0.14.6

### Android version

Android 13

### Device

Google Pixel 6 Pro

### Other details

Please let me know if this isn't clear, I wasn't entirely sure how to explain it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-05-04 01:58
Duplicate of #4875

**Closed by arkon** 2023-05-04 01:58 UTC
Labels: Bug
