### ISSUE TITLE
Tracking chapter input and Tracker Chaper bug.

### ISSUE THREAD

**Issue by tranric** [tachiyomiorg/tachiyomi#9312] opened 2023-04-09 09:00 UTC
### Describe your suggested feature

Tracking on chapters used to have a keypad input to fix; now it only has scroll bar which is hard and takes a long time to fix the randomly incorrect data with no other way to input which takes a long time to fix from thousands to scroll back up to a lower number. This was a previous feature that used to be in an older version of Tachiyomi, unsure why it was taken out. I would suggest to re-enable the manual input instead of only a scroll bar for tracker chapter edit.

### Steps to reproduce
I have no idea how to reproduce it, happened randomly with some manga on my library.

### Expected behavior
To have the tracker be properly set to the chapter automatically.

### Actual behavior
Tracker on read chapter randomly set to current year (this manga in photos have only 40 chapters).
![Screenshot_20230409-044137_Tachiyomi](https://user-images.githubusercontent.com/55151012/230763606-348f897f-7a00-46a7-91ec-8ad7aab7060a.jpg)
![Screenshot_20230409-044846_Tachiyomi](https://user-images.githubusercontent.com/55151012/230763613-d50be9b3-962c-4ac1-9741-8fe9ababe67f.jpg)

### Crash logs:
No response

### Tachiyomi version:
0.14.5

### Android version:
Android 10

### Device:
Samsung Galaxy Note 9

### Other details:
No response

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2023-04-09 09:13
duplicate of the general issue #8799

**Closed by Seishirou101** 2023-04-09 09:13 UTC
Labels: Feature request
