### ISSUE TITLE
Paginated view for sources for easier navigation

### ISSUE THREAD

**Issue by pantmanik** [tachiyomiorg/tachiyomi#7262] opened 2022-06-07 05:25 UTC
### Describe your suggested feature

If Tachiyomi could have paginated views that would be great. It would help in keeping track of where I was when I read mangas for a certain search category.

For example, if I start reading slice of life mangas, I may end up reading a lot of them. Every time I have to painfully scroll down to find out which manga to continue from. With paginated view, I can simply remember which page of the search results I was in, making it much easier to continue from that manga onwards.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2022-06-07 15:52
Duplicate of #407 basically

**Closed by Seishirou101** 2022-06-07 15:52 UTC
Labels: Feature request
