### ISSUE TITLE
aliases for mangas on library.

### ISSUE THREAD

**Issue by imagochan** [tachiyomiorg/tachiyomi#10087] opened 2023-10-30 02:51 UTC
### Describe your suggested feature

I would like to be able to change the name of the manga or manwha in my library so that I am able to organize my library better because sometimes source have wrong titles.

It should work like an alias for a existing manga or manwha in my library.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2023-10-30 12:22
Duplicate of #4398

**Closed by Seishirou101** 2023-10-30 12:22 UTC
Labels: Feature request
