### ISSUE TITLE
Migration to Local Manga

### ISSUE THREAD

**Issue by joelchrono12** [tachiyomiorg/tachiyomi#6686] opened 2022-02-21 13:17 UTC
### Describe your suggested feature

Right now, when choosing the Migrate option from any manga, it gets looked up on whatever extensions I got installed. But I don't see a way to migrate to a local manga. 
I would love to see local manga among the suggestion to migrate to. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment] 2022-02-21 13:36
Duplicate of #2289

**Closed by curche** 2022-02-21 13:36 UTC
Labels: Feature request
