### ISSUE TITLE
I have problem

### ISSUE THREAD

**Issue by Chahinpirate** [tachiyomiorg/tachiyomi#9659] opened 2023-07-02 07:12 UTC
### Steps to reproduce

Please fix the image can't be loaded 
Mangaswat / Arabic source
I have more than 2 days have the same issue 

### Expected behavior

Thank you for helping me 

### Actual behavior

Thanks 

### Crash logs

Thank you 

### Tachiyomi version

0.14.6

### Android version

Android 12

### Device

Poco x 3 pro

### Other details

Thanks for helping me 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2023-07-02 07:39
Duplicate of https://github.com/tachiyomiorg/tachiyomi-extensions/issues/16952

**Comment by stevenyomi** [comment] 2023-07-02 07:39
Also
> If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).

**Closed by stevenyomi** 2023-07-02 07:39 UTC
Labels: Bug
