### ISSUE TITLE
Chapter count in tracker not synced with tachiyomi's tracker causing large numbers of unread chapter

### ISSUE THREAD

**Issue by rsmyst** [tachiyomiorg/tachiyomi#5756] opened 2021-08-20 06:41 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.0](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.12.0)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.12.1

### Android version

Android 10

### Device

galaxy S9+

### Steps to reproduce

I would expect Tachiyomi to automatically mark the completed chapters as read by using the tracker
For some reason this does not happen. SO, when I sort by unread, i have random manga that i've already caught up to showing in the top with 200 chapters unread.
The tracker already has been updated to say 350.

### Expected behavior

While adding tracker to a manga, the read chapters should be synced with it so that only the correct number of unread is displayed.

### Actual behavior

Just shows every chpater i didn't read in tachiyomi as unread. 
I occasionally read chapters on my pc and this is a pain to manage.

**Comment by Seishirou101** [comment] 2021-08-20 06:55
Not a bug it's one way sync. Duplicate of #1626

**Comment by rsmyst** [comment] 2021-08-20 09:05
> Not a bug it's one way sync. Duplicate of #1626

will this feature be implemented some time soon? I'd think this is a pretty vital feature to an app like tachi but sure

**Closed** 2021-08-20 11:00 UTC
Labels: Bug
