### ISSUE TITLE
Remove .tmp folder after download is cancelled/failed

### ISSUE THREAD

**Issue by einstein95** [tachiyomiorg/tachiyomi#1501] opened 2018-06-21 19:31 UTC
**App version:**
0.7.4

**Issue/Request:**
Remove .tmp folder left over from a cancelled download

**Other details:**
After the downloads are cleared, a .tmp folder is left over. This also counts towards the download count icon on the manga listing (if enabled).

**Comment by wopian** [comment] 2018-06-21 21:58
Somewhat a duplicate of #1193

**Comment by arkon** [comment] 2022-07-10 14:14
Closing in favour of #7492

**Closed by arkon** 2022-07-10 14:14 UTC
Labels: Feature request
