### ISSUE TITLE
Possible to scroll outside the bounds of the manga panel

### ISSUE THREAD

**Issue by cykyu** [tachiyomiorg/tachiyomi#7606] opened 2022-07-24 23:56 UTC
### Steps to reproduce

1. Open up any manga in Webtoon or continuous vertical mode
2. Zoom into the panel 
3. Scroll to the left edge of the manga panel
4. Double tap to zoom out
5. While the zoom out animation is happening, quickly swipe to left

https://user-images.githubusercontent.com/109923504/180670654-70cd4eab-be97-4fb4-8a01-0d10f213ba67.mp4

### Expected behavior

The screen should stop at the edge of the manga panel.

### Actual behavior

The screen scrolls past the edge of the manga panel and gets stuck with half of the panel offscreen. While stuck like this you are unable to scroll left or right. Zooming in or out will fix this.

### Tachiyomi version

0.13.5

### Android version

Android 12

### Device

Samsung S20

### Other details

This works in both continuous vertical and webtoons mode.
I took a look through the code and I'm pretty sure this issue occurs in WebtoonRecyclerView, specifically the zoom function where the currentScale variable isn't set until after the zoom animation ends which results in scrolling being possible during the zoom out animation.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-07-24 23:59
Duplicate of #3127

**Comment by cykyu** [comment] 2022-07-25 00:02
This is a different issue from that. This is about being able to scroll past the edge of the panel while not being zoomed in and getting stuck like that.

**Closed** 2023-01-14 23:38 UTC
Labels: Bug
