### ISSUE TITLE
[Bug] Case sensitivity relies on underlying filesystem

### ISSUE THREAD

**Issue by MushKPN** [tachiyomiorg/tachiyomi#4814] opened 2021-04-11 22:33 UTC
Hi !

## Device information
* Tachiyomi version: 0.10.10
* Android version: 5.0.2
* Device: Asus ZenPad 10 (P023)

## Steps to reproduce
1. After installing version 0.10.10, I updated my library in order to get the latest chapters
2. As soon as I try to read a chapter, the reader opens an instantly closes with a little message showing at the bottom : "Case sensitivity relies on underlying filesystem"
3. Extensions are up to date and I have this problem on all mangas, wether the chapter is read or unread.

## Issue/Request
Can you fix this new version or provide a way to avoid this ? 

## Other details
![Screenshot_2021-04-12-00-31-01](https://user-images.githubusercontent.com/59181467/114323640-69249600-9b26-11eb-90f8-42af2c209359.jpg)

Thanks !

**Comment by CrepeTF** [comment] 2021-04-11 22:33
Install the new new 0.10.10 version.
https://github.com/tachiyomiorg/tachiyomi/releases/download/v0.10.10/tachiyomi-v0.10.10.apk

**Comment by arkon** [comment] 2021-04-11 22:36
Duplicate of #4813

**Closed by arkon** 2021-04-11 22:36 UTC

**Comment by MushKPN** [comment] 2021-04-11 22:37
Thanks for the quick fix ! :) And sorry about the duplicate ticket
