### ISSUE TITLE
Migration button(?) in pop-up.

### ISSUE THREAD

**Issue by evd27** [tachiyomiorg/tachiyomi#7422] opened 2022-06-30 18:09 UTC
### Describe your suggested feature

When I try to add a title in my library but it's already there, a pop-up shows, asking to either 'show manga', 'cancel' or 'add'. Integrating there somehow (I don't know how), the option to migrate would go a long way to help better the experience.

### Other details

Migration on the stable release is more of an inconvenience compared to the forks. This might close the gap hopefully.
![Screenshot_20220630-231230__01](https://user-images.githubusercontent.com/87810818/176747164-ce57c0a9-1b17-4b98-beb8-ecb1b06a1344.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-07-03 21:53
Duplicate of #7094

**Closed by arkon** 2022-07-03 21:53 UTC
Labels: Feature request
