### ISSUE TITLE
Add a check option called "private" to the track window of Anilist

### ISSUE THREAD

**Issue by Palloxin** [tachiyomiorg/tachiyomi#7298] opened 2022-06-12 15:42 UTC
### Describe your suggested feature

![IMG_20220612_135220](https://user-images.githubusercontent.com/75091899/173241234-833ea3b8-83c0-4489-8793-882f9ed5325f.jpg)

This is a third party app of Anilist and when i add a manga (or anime) the app makes avaiable this option letting us choose if the users want to keep it private or not.
Now, i will say it; this option is perfect for an hentai dedicated fork of tachiyimi since users might want to hide 'their dirt' keeping them hidden from the public, but still wanting them on their list.

### Other details

the app of the screenshot is Anilib and it is on github if you need the code as a reference or something

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-06-12 15:43
Duplicate of #1671

**Closed by arkon** 2022-06-12 15:43 UTC
Labels: Feature request

**Comment by Palloxin** [comment] 2022-06-12 15:44
mm, 3 years and a half. i already lost hope 😔
