### ISSUE TITLE
True false inside toggle loaded chapters and incognito

### ISSUE THREAD

**Issue by ve1mi** [tachiyomiorg/tachiyomi#7050] opened 2022-05-01 11:23 UTC
### Steps to reproduce

Mb only in Russian localization, this bug has been around for a month or two
![Screenshot_20220501-141351_Tachiyomi](https://user-images.githubusercontent.com/45261656/166143624-9ec68caa-4707-4830-8a14-ac3407ce768e.png)

### Expected behavior

.

### Actual behavior

.

### Tachiyomi version

App version: 0.12.1-3691 (standard, 071bad123, 67, 2021-08-15T22:21Z) Android version: 11 (SDK 30) Android build ID: RKQ1.201022.002 release-keys Device brand: Redmi Device manufacturer: Xiaomi Device name: sunny Device model: M2101K7AG Device product name: sunny_global

### Android version

Android 12

### Device

Redmi note 10 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment] 2022-05-01 11:59
Duplicate of #7004

**Closed by curche** 2022-05-01 11:59 UTC
Labels: Bug
