### ISSUE TITLE
[Feature Requests] option to only check for updates on non recently updated Mangas. 

### ISSUE THREAD

**Issue by Bexa2** [tachiyomiorg/tachiyomi#2295] opened 2019-10-21 22:43 UTC
What the title says, it would lessen the load on the servers and speed up the process if it skips Mangas that were updated, say less than 24 hours ago.

**Comment by arkon** [comment] 2022-07-09 23:17
Duplicate of #6154

**Closed by arkon** 2022-07-09 23:17 UTC
Labels: Feature request
