### ISSUE TITLE
Duplicate library entries

### ISSUE THREAD

**Issue by Leunsensei** [tachiyomiorg/tachiyomi#8423] opened 2022-11-02 13:30 UTC
### Describe your suggested feature

![Screenshot_2022-11-02-14-27-34-881_eu kanade tachiyomi](https://user-images.githubusercontent.com/98178685/199501878-e23f9bda-f12f-44c3-8b87-516f54b3638e.jpg)

As the app detects a duplicate entry, it would be nice to have the option to migrate from there.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-11-02 13:32
Duplicate of #7094

**Closed by arkon** 2022-11-02 13:32 UTC
Labels: Feature request
