### ISSUE TITLE
Per-category Delete After Read (Read/Marked as Read) setting

### ISSUE THREAD

**Issue by edishiiii** [tachiyomiorg/tachiyomi#1412] opened 2018-05-10 18:09 UTC
IDK if this has already been posted but anyway, please take the time to read this. And oh, I'm no programmer and I know it's hard to be one. I just wanna post this in case someone takes an interest in making a fix for em. I really like the app so far. (Ignore the manga rock app... It's just that I just found and installed tachiyomi yesterday.)

App Version: v7.3

**Part A**
**Problem 1**:  Tracking doesn't track the chapters that are only marked as read manually (but not actually read).

**Problem 2**: If I only "Mark as Read" a chapter, or a certain amount of them, I have to actually open one chapter so that those marked as read will be tracked.

**Problem 3**: If I marked a certain amount of chapters as read, for example, I marked 40 chapters as read, then I opened page 1 of chapter 33, only 33 chapters are tracked as read but not 40. 

**Here, take a look.** 
**1)** Here's a manga I'm reading. Clearly, nothing is marked as read. 
![1](https://user-images.githubusercontent.com/39167978/39885390-0984775c-54bf-11e8-87f1-8b8978ee379d.png)

**2)** Here's the initial status of this manga that I'm reading. 
![2](https://user-images.githubusercontent.com/39167978/39885428-2b0f996a-54bf-11e8-8188-5439983d9cf1.png)

**3)** Now, I'm marking all 38 chapters as read.
![3](https://user-images.githubusercontent.com/39167978/39885457-4018e974-54bf-11e8-98c4-64cd67806c27.png)

**4)** Clearly, all 38 chapters are now "MARKED" as read.
![4](https://user-images.githubusercontent.com/39167978/39885489-51bfd318-54bf-11e8-8443-a10cacd27982.png)

**5)** Still, the status of this manga isn't updated. No read chapters has been tracked.
![5](https://user-images.githubusercontent.com/39167978/39885493-53442662-54bf-11e8-8314-75426b5af859.png)

**6)** Now I'm opening **page one of chapter 37**.
![6](https://user-images.githubusercontent.com/39167978/39885495-560a5100-54bf-11e8-8d27-6855a04e9a11.png)

**7)** Only 37 chapters has been marked as read. 
![7](https://user-images.githubusercontent.com/39167978/39885496-57ad796a-54bf-11e8-9dbb-655086942753.png)

**8)** Now, I'm opening chapter 38
![8](https://user-images.githubusercontent.com/39167978/39885502-59a3684c-54bf-11e8-9b77-da0341d8d76c.png)

**9)** Now 38 chapters has been tracked.
![9](https://user-images.githubusercontent.com/39167978/39885513-5beaca6e-54bf-11e8-908a-a61928a1947e.png)

**Part B**
Suggestion: I hope that the "Remove after read" be changed in such way that it will only affect one category that I made. 

For example, I have two categories. One for the Mangas and one for the Hentai Mangas. I only want the "Remove after read" to take effect on the mangas since I want to keep my hentai mangas saved even though I've already finished reading them. 

Idea for fix: Add a "Categories to include in Remove after read". Something like what's in the "Categories to include in download".

**Comment by Deterio** [comment] 2018-05-12 13:26
Also want part B

**Comment by arkon** [comment] 2020-01-04 21:41
Part A: duplicate of #389

**Comment by scb261** [comment] 2020-05-14 11:27
Wanted to create an issue but found this one. Also want part B, but in my case it would be better to do it for certain mangas rather than categories. Maybe make both, and manga setting would overwrite category setting? If not, categories still would be good.

Also similar to this, not sure if I should create new issue. I guess it's rare use case (I even forgot when and why I did that, only remember that it irritated me some time ago). When you read chapters not in order, it removes nth to last chapter even if you still didn't read it. Maybe check if it's read and remove only if it is.

And one more. Since I've disabled removing nth to last to keep some mangas, I remove manually and it would be good to have "remove previous". Maybe add something like "select all previous" and than choose remove/download/mark as read/mark as unread.

**Comment by scb261** [comment] 2020-06-05 09:09
> Also want part B, but in my case it would be better to do it for certain mangas rather than categories

I think it would be better to add option to exclude categories. So I could create category 'plan to reread' and chose to remove if manga isn't in that category.

**Closed** 2021-04-04 21:15 UTC
Labels: feature
