### ISSUE TITLE
autoscroll

### ISSUE THREAD

**Issue by staticshock129** [tachiyomiorg/tachiyomi#8343] opened 2022-10-29 20:37 UTC
### Describe your suggested feature

autoscroll with different speeds since it will make life scrolling so much easier when one is busy and cant keep scrolling

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-10-29 20:38
Duplicate of #2093

**Closed by arkon** 2022-10-29 20:38 UTC
Labels: Feature request
