### ISSUE TITLE
[Feature Request] Bulk extension "Update All" button

### ISSUE THREAD

**Issue by QuantumStar101** [tachiyomiorg/tachiyomi#5259] opened 2021-06-01 20:08 UTC
## Device information
* Tachiyomi version: Stable 0.11.1
* Android version: 11
* Kernel version: 4.9.237-g4291d86870f1-ab7185835
* Build number: RQ2A.210505.002
* Device: Google Pixel 3XL

## Request
Add a button in the browse extension menu to "Update All" extensions.

**Comment by arkon** [comment] 2021-06-01 20:21
Duplicate of #4815

**Closed by arkon** 2021-06-01 20:21 UTC
