### ISSUE TITLE
MangaSwat HTTP Error 404

### ISSUE THREAD

**Issue by MrPunisher6** [tachiyomiorg/tachiyomi#9502] opened 2023-05-14 10:56 UTC
### Steps to reproduce

It's been 6 days for now that this issue occurred, the web view is working fine but direct use ain't. 

### Expected behavior

It should open

### Actual behavior

It says " HTTP Error 404: Check website in webview" 

### Tachiyomi version

0.14.6

### Android version

Android 10

### Device

Huawei MED-LX9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment] 2023-05-14 11:37
Duplicate of https://github.com/tachiyomiorg/tachiyomi-extensions/issues/16231

> If this is an issue with an extension, I should be opening an issue in the extensions repository.

**Closed** 2023-05-14 11:37 UTC
Labels: Bug
