### ISSUE TITLE
Recommendations based on current manga

### ISSUE THREAD

**Issue by amant555** [tachiyomiorg/tachiyomi#5628] opened 2021-07-30 05:23 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

Hey, to all the manga readers. For me sometimes it becomes quite difficult to find new mangas to read. Major websites already provide the feature of similar/ recommendations based on manga that have been read or which is currently open. 

It would be great if the team can add a section in UI and display recommendations in every manga that we open.

**Comment by loocool2** [comment] 2021-07-30 05:36
Duplicate of #376

**Closed by loocool2** 2021-07-30 05:36 UTC
Labels: Feature request
