### ISSUE TITLE
less stresses to developers (Url changer)

### ISSUE THREAD

**Issue by T3MYA11** [tachiyomiorg/tachiyomi#9980] opened 2023-10-03 19:50 UTC
### Describe your suggested feature

the "override baseUrl" option in some extension's can be a solution for a lot of bugs and save time /work for developers. if you could make a single tab in the general settings of the app show's the (Url) of the all installed extension's and the option to change the url manually as a user it will become much easier for both sides 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-10-03 20:33
Duplicate of #9928

**Closed** 2023-10-03 20:33 UTC
Labels: Feature request
