### ISSUE TITLE
Force closes when pressing down (🔽) in Edit categories

### ISSUE THREAD

**Issue by pseudo-demon** [tachiyomiorg/tachiyomi#8584] opened 2022-11-21 10:54 UTC
### Steps to reproduce

1. Go to Settings - Library - Edit categories
2. Press Down (🔽) or Up (🔼) on the categories
![Edit categories](https://user-images.githubusercontent.com/118722936/203052498-2e2ee464-9faa-458d-a140-31baff3ad145.png)
3. Crash.jpg ([bgm](https://youtube.com/watch?v=mrOWDPkYyP0)) ![Force closed](https://user-images.githubusercontent.com/118722936/203052555-b84d1872-9ef1-4fca-8247-6617a2249818.png)

### Expected behavior

Categories should change its position properly.

### Actual behavior

Failure to sort categories.
App crashed after pressing Down (🔽) in the Edit categories.

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/10055699/tachiyomi_crash_logs.txt)

### Tachiyomi version

0.14.2

### Android version

Android 7.1.2

### Device

Redmi 5A

### Other details

> - [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.

This is not a copy paste, duplicate of _recent_ ticket, if there is.
> - [ ] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).

Guide not found.
> - [X] I have updated all installed extensions.

Yes, i have. And it's not related to extensions
### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [ ] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment] 2022-11-21 11:27
```
--------- beginning of crash
11-04 19:37:54.944  8988  9257 E AndroidRuntime: FATAL EXCEPTION: Thread-9
11-04 19:37:54.944  8988  9257 E AndroidRuntime: Process: eu.kanade.tachiyomi, PID: 8988
11-04 19:37:54.944  8988  9257 E AndroidRuntime: java.lang.RuntimeException: saveIcon exception
11-04 19:37:54.944  8988  9257 E AndroidRuntime: 	at miui.security.SecurityManager.saveIcon(SecurityManager.java:277)
11-04 19:37:54.944  8988  9257 E AndroidRuntime: 	at com.miui.internal.os.Native.invoke(Native Method)
11-04 19:37:54.944  8988  9257 E AndroidRuntime: 	at miui.reflect.Method.invoke(SourceFile:120)
11-04 19:37:54.944  8988  9257 E AndroidRuntime: 	at miui.content.res.ThemeRuntimeManager.saveIconInner(SourceFile:185)
11-04 19:37:54.944  8988  9257 E AndroidRuntime: 	at miui.content.res.ThemeRuntimeManager.-wrap1(SourceFile)
11-04 19:37:54.944  8988  9257 E AndroidRuntime: 	at miui.content.res.ThemeRuntimeManager$ThemeServiceThread.run(SourceFile:159)
11-04 19:37:54.944  8988  9257 E AndroidRuntime: Caused by: android.os.DeadObjectException
11-04 19:37:54.944  8988  9257 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
11-04 19:37:54.944  8988  9257 E AndroidRuntime: 	at android.os.BinderProxy.transact(Binder.java:618)
11-04 19:37:54.944  8988  9257 E AndroidRuntime: 	at miui.security.ISecurityManager$Stub$Proxy.saveIcon(ISecurityManager.java:1510)
11-04 19:37:54.944  8988  9257 E AndroidRuntime: 	at miui.security.SecurityManager.saveIcon(SecurityManager.java:275)
11-04 19:37:54.944  8988  9257 E AndroidRuntime: 	... 5 more
11-04 19:37:55.003  8988  8988 E AndroidRuntime: FATAL EXCEPTION: main
11-04 19:37:55.003  8988  8988 E AndroidRuntime: Process: eu.kanade.tachiyomi, PID: 8988
11-04 19:37:55.003  8988  8988 E AndroidRuntime: DeadSystemException: The system died; earlier logs will point to the root cause
11-10 11:21:58.397  7437  7437 E AndroidRuntime: FATAL EXCEPTION: main
11-10 11:21:58.397  7437  7437 E AndroidRuntime: Process: eu.kanade.tachiyomi, PID: 7437
11-10 11:21:58.397  7437  7437 E AndroidRuntime: android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@60c7002 is not valid; is your activity running?
11-10 11:21:58.397  7437  7437 E AndroidRuntime: 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:699)
11-10 11:21:58.397  7437  7437 E AndroidRuntime: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:347)
11-10 11:21:58.397  7437  7437 E AndroidRuntime: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
11-10 11:21:58.397  7437  7437 E AndroidRuntime: 	at android.widget.Toast$TN.handleShow(Toast.java:461)
11-10 11:21:58.397  7437  7437 E AndroidRuntime: 	at android.widget.Toast$TN$2.handleMessage(Toast.java:344)
11-10 11:21:58.397  7437  7437 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-10 11:21:58.397  7437  7437 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:163)
11-10 11:21:58.397  7437  7437 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6205)
11-10 11:21:58.397  7437  7437 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-10 11:21:58.397  7437  7437 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
11-10 11:21:58.397  7437  7437 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
11-12 15:33:20.891 23255 23255 E AndroidRuntime: FATAL EXCEPTION: main
11-12 15:33:20.891 23255 23255 E AndroidRuntime: Process: eu.kanade.tachiyomi, PID: 23255
11-12 15:33:20.891 23255 23255 E AndroidRuntime: android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@2fbf85e is not valid; is your activity running?
11-12 15:33:20.891 23255 23255 E AndroidRuntime: 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:699)
11-12 15:33:20.891 23255 23255 E AndroidRuntime: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:347)
11-12 15:33:20.891 23255 23255 E AndroidRuntime: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
11-12 15:33:20.891 23255 23255 E AndroidRuntime: 	at android.widget.Toast$TN.handleShow(Toast.java:461)
11-12 15:33:20.891 23255 23255 E AndroidRuntime: 	at android.widget.Toast$TN$2.handleMessage(Toast.java:344)
11-12 15:33:20.891 23255 23255 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-12 15:33:20.891 23255 23255 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:163)
11-12 15:33:20.891 23255 23255 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6205)
11-12 15:33:20.891 23255 23255 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-12 15:33:20.891 23255 23255 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
11-12 15:33:20.891 23255 23255 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
11-14 21:08:57.746  7556  7556 E AndroidRuntime: FATAL EXCEPTION: main
11-14 21:08:57.746  7556  7556 E AndroidRuntime: Process: eu.kanade.tachiyomi, PID: 7556
11-14 21:08:57.746  7556  7556 E AndroidRuntime: android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@835a2f6 is not valid; is your activity running?
11-14 21:08:57.746  7556  7556 E AndroidRuntime: 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:699)
11-14 21:08:57.746  7556  7556 E AndroidRuntime: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:347)
11-14 21:08:57.746  7556  7556 E AndroidRuntime: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
11-14 21:08:57.746  7556  7556 E AndroidRuntime: 	at android.widget.Toast$TN.handleShow(Toast.java:461)
11-14 21:08:57.746  7556  7556 E AndroidRuntime: 	at android.widget.Toast$TN$2.handleMessage(Toast.java:344)
11-14 21:08:57.746  7556  7556 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-14 21:08:57.746  7556  7556 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:163)
11-14 21:08:57.746  7556  7556 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6205)
11-14 21:08:57.746  7556  7556 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-14 21:08:57.746  7556  7556 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
11-14 21:08:57.746  7556  7556 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
11-19 19:24:52.126 22378 22378 E AndroidRuntime: FATAL EXCEPTION: main
11-19 19:24:52.126 22378 22378 E AndroidRuntime: Process: eu.kanade.tachiyomi, PID: 22378
11-19 19:24:52.126 22378 22378 E AndroidRuntime: android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@717c6c6 is not valid; is your activity running?
11-19 19:24:52.126 22378 22378 E AndroidRuntime: 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:699)
11-19 19:24:52.126 22378 22378 E AndroidRuntime: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:347)
11-19 19:24:52.126 22378 22378 E AndroidRuntime: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
11-19 19:24:52.126 22378 22378 E AndroidRuntime: 	at android.widget.Toast$TN.handleShow(Toast.java:461)
11-19 19:24:52.126 22378 22378 E AndroidRuntime: 	at android.widget.Toast$TN$2.handleMessage(Toast.java:344)
11-19 19:24:52.126 22378 22378 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-19 19:24:52.126 22378 22378 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:163)
11-19 19:24:52.126 22378 22378 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6205)
11-19 19:24:52.126 22378 22378 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-19 19:24:52.126 22378 22378 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
11-19 19:24:52.126 22378 22378 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
--------- beginning of system
--------- beginning of main
11-21 16:38:58.940 12561 12671 E SQLiteLog: (284) automatic index on C(manga_id)
11-21 16:38:58.940 12561 12671 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
11-21 16:39:08.158 12718 12718 E ResourceType: Style contains key with bad entry: 0x0101056c
11-21 16:39:08.494 12718 12718 E ResourceType: Style contains key with bad entry: 0x0101056c
11-21 16:39:08.500 12718 12718 E ResourceType: Style contains key with bad entry: 0x0101056d
11-21 16:39:08.500 12718 12718 E ResourceType: Style contains key with bad entry: 0x0101058c
11-21 16:39:08.500 12718 12718 E ResourceType: Style contains key with bad entry: 0x01010604
11-21 16:39:08.500 12718 12718 E ResourceType: Style contains key with bad entry: 0x01010605
11-21 16:39:10.325 12718 12845 E SQLiteLog: (284) automatic index on C(manga_id)
11-21 16:39:10.325 12718 12845 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
11-21 16:39:35.787 12718 12898 E ACRA    : ACRA caught a IndexOutOfBoundsException for eu.kanade.tachiyomi
11-21 16:39:35.787 12718 12898 E ACRA    : java.lang.IndexOutOfBoundsException: Index: 3, Size: 2
11-21 16:39:35.787 12718 12898 E ACRA    : 	at java.util.ArrayList.add(ArrayList.java:457)
11-21 16:39:35.787 12718 12898 E ACRA    : 	at eu.kanade.domain.category.interactor.ReorderCategory$await$2.invokeSuspend(ReorderCategory.kt:161)
11-21 16:39:35.787 12718 12898 E ACRA    : 	at eu.kanade.domain.category.interactor.ReorderCategory$await$2.invoke(ReorderCategory.kt:13)
11-21 16:39:35.787 12718 12898 E ACRA    : 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:8)
11-21 16:39:35.787 12718 12898 E ACRA    : 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:50)
11-21 16:39:35.787 12718 12898 E ACRA    : 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
11-21 16:39:35.787 12718 12898 E ACRA    : 	at eu.kanade.tachiyomi.util.lang.CoroutinesExtensionsKt.withNonCancellableContext(CoroutinesExtensions.kt:3)
11-21 16:39:35.787 12718 12898 E ACRA    : 	at eu.kanade.domain.category.interactor.ReorderCategory.await(ReorderCategory.kt:14)
11-21 16:39:35.787 12718 12898 E ACRA    : 	at eu.kanade.tachiyomi.ui.category.CategoryPresenter$moveDown$1.invokeSuspend(CategoryPresenter.kt:49)
11-21 16:39:35.787 12718 12898 E ACRA    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
11-21 16:39:35.787 12718 12898 E ACRA    : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
11-21 16:39:35.787 12718 12898 E ACRA    : 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
11-21 16:39:35.787 12718 12898 E ACRA    : 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
11-21 16:39:35.787 12718 12898 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
11-21 16:39:35.787 12718 12898 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:66)
11-21 16:39:35.787 12718 12898 E ACRA    : 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@3192e10, Dispatchers.IO]
11-21 16:39:36.030 12718 12835 E ACRA    : ACRA caught a IndexOutOfBoundsException for eu.kanade.tachiyomi
11-21 16:39:36.030 12718 12835 E ACRA    : java.lang.IndexOutOfBoundsException: Index: 3, Size: 2
11-21 16:39:36.030 12718 12835 E ACRA    : 	at java.util.ArrayList.add(ArrayList.java:457)
11-21 16:39:36.030 12718 12835 E ACRA    : 	at eu.kanade.domain.category.interactor.ReorderCategory$await$2.invokeSuspend(ReorderCategory.kt:161)
11-21 16:39:36.030 12718 12835 E ACRA    : 	at eu.kanade.domain.category.interactor.ReorderCategory$await$2.invoke(ReorderCategory.kt:13)
11-21 16:39:36.030 12718 12835 E ACRA    : 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:8)
11-21 16:39:36.030 12718 12835 E ACRA    : 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:50)
11-21 16:39:36.030 12718 12835 E ACRA    : 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
11-21 16:39:36.030 12718 12835 E ACRA    : 	at eu.kanade.tachiyomi.util.lang.CoroutinesExtensionsKt.withNonCancellableContext(CoroutinesExtensions.kt:3)
11-21 16:39:36.030 12718 12835 E ACRA    : 	at eu.kanade.domain.category.interactor.ReorderCategory.await(ReorderCategory.kt:14)
11-21 16:39:36.030 12718 12835 E ACRA    : 	at eu.kanade.tachiyomi.ui.category.CategoryPresenter$moveDown$1.invokeSuspend(CategoryPresenter.kt:49)
11-21 16:39:36.030 12718 12835 E ACRA    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
11-21 16:39:36.030 12718 12835 E ACRA    : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
11-21 16:39:36.030 12718 12835 E ACRA    : 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
11-21 16:39:36.030 12718 12835 E ACRA    : 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
11-21 16:39:36.030 12718 12835 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
11-21 16:39:36.030 12718 12835 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:66)
11-21 16:39:36.030 12718 12835 E ACRA    : 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@894e3be, Dispatchers.IO]
11-21 16:39:40.321 13082 13082 E ResourceType: Style contains key with bad entry: 0x0101056c
11-21 16:39:40.887 13082 13082 E ResourceType: Style contains key with bad entry: 0x0101056c
11-21 16:39:40.895 13082 13082 E ResourceType: Style contains key with bad entry: 0x0101056d
11-21 16:39:40.895 13082 13082 E ResourceType: Style contains key with bad entry: 0x0101058c
11-21 16:39:40.895 13082 13082 E ResourceType: Style contains key with bad entry: 0x01010604
11-21 16:39:40.895 13082 13082 E ResourceType: Style contains key with bad entry: 0x01010605
11-21 16:39:43.196 13082 13193 E SQLiteLog: (284) automatic index on C(manga_id)
11-21 16:39:43.196 13082 13193 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.14.2 (standard, 3222247, 91, 2022-10-31T21:42Z)
Android version: 7.1.2 (SDK 25)
Android build ID: N2G47H
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: riva
Device model: Redmi 5A
Device product name: riva
```

**Comment by pseudo-demon** [comment] 2022-11-21 12:21
![Hamstiger](https://user-images.githubusercontent.com/118722936/203053506-a492820e-5f7d-4614-8605-ee563bf447d2.jpg)

**Comment by arkon** [comment] 2022-11-21 13:03
Duplicate of #8372

**Closed by arkon** 2022-11-21 13:03 UTC
Labels: Bug
