### ISSUE TITLE
Browse source filter sheet doesn't expand when expanding a group

### ISSUE THREAD

**Issue by thecrazypozavnist** [tachiyomiorg/tachiyomi#6462] opened 2022-01-11 17:14 UTC
### Steps to reproduce

1. Go to any source that has a checkbox style genre selection (ie. mangasee, mangadex) 
2. Click on filter
3. Click on the genres tab

### Expected behavior

The filters tab should expand and fill the whole available screen area it requires, since there is usually a vast selection of genres available there is no reason i can think of for the filters tab to stay put in the bottom part of the screen without expanding. 
![Screenshot_20220111-180837_Tachiyomi](https://user-images.githubusercontent.com/95861424/148988864-f3714343-13af-41dd-8f68-4d203f098acc.jpg)

### Actual behavior

The filters tab remains collapsed on the bottom part of the screen, expanding only when a genre is selected. 
![Screenshot_20220111-180735_Tachiyomi](https://user-images.githubusercontent.com/95861424/148988711-a8606032-75c9-4a7b-a318-ad283c3c72f2.jpg)

### Tachiyomi version

0.12.3

### Android version

Android 11 and 12

### Device

Lg v30, Samsung galaxy tab s7, Huawei mediapad m3

### Other details

I think what I described is the correct and expected behaviour, thus it seems appropriate to me to report it as an issue, but it might as well be a feature request. Since the manga list doesn't update live while searching there is no reason I can think of for the filters tab not to occupy the whole screen.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MohitMandalia** [comment] 2022-01-20 05:15
I am not able to reproduce this on my Pixel 4a  can you tell what exactly did you follow?

**Comment by MohitMandalia** [comment] 2022-01-20 05:18
Ok so just to confirm issue is when clicking on genres it is expanding but not occupying full screen instead we manually have to pull it up is that the issue?

**Comment by ThePromidius** [comment] 2022-01-20 05:26
I saw this when i was developing one extension. 

If you expand any of the filters group (to show the checkboxes) and try to expand again, total height gets updated and expected result is obtained.

I can reproduce in Samsung tab a10 and xiaomi remi 9 pro.

**Comment by MohitMandalia** [comment] 2022-01-20 05:39
Yes it's a little buggy.

**Comment by thecrazypozavnist** [comment] 2022-01-20 07:18
> Ok so just to confirm issue is when clicking on genres it is expanding but not occupying full screen instead we manually have to pull it up is that the issue?

Even if trying to manually pull it up, it does not work. I have to select a genre first. In the first screenshot as soon as I selected "Action" it expanded correctly.

**Comment by stevenyomi** [comment] 2022-08-20 06:41
Hoping this can be fixed in the Compose rewrite. (or not)

**Comment by stevenyomi** [comment] 2023-02-01 11:12
/edit-title "Browse source filter sheet doesn't expand when expanding a group"

**Comment by arkon** [comment] 2023-02-23 23:43
Duplicate of #4967

**Closed by arkon** 2023-02-23 23:43 UTC
Labels: Bug
