### ISSUE TITLE
Marks newer chapters as read that haven't been open. 

### ISSUE THREAD

**Issue by mvevitsis** [tachiyomiorg/tachiyomi#9648] opened 2023-06-27 12:00 UTC
### Steps to reproduce

1. Open a chapter (e.g., 1)
2. It will mark the chapter as read, but will also mark newer chapters (e.g. 8, 13) as read as well.

### Expected behavior

Only the chapter that was read should be greyed out 

### Actual behavior

The chapter that was opened, and other unopened chapters are greyed out

### Tachiyomi version

0.14.6

### Android version

Android 12

### Device

Galaxy s10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by wel21** [comment] 2023-06-30 21:55
Got the same issue. Titles are greyed out while scrolling.
[Screen capture link](https://drive.google.com/file/d/10zoNVD79SCW7ZJ58B40-5ncLQLerd9wj/view?usp=drivesdk)

**Comment by arkon** [comment] 2023-06-30 22:38
Duplicate of #9043, it's fixed in preview.

**Closed by arkon** 2023-06-30 22:38 UTC
Labels: Bug
