### ISSUE TITLE
Setting for automatically setting reading on tracker status

### ISSUE THREAD

**Issue by NotMoumix** [tachiyomiorg/tachiyomi#7344] opened 2022-06-19 20:13 UTC
### Describe your suggested feature

Hello,
Would it be possible to add a settings to cancel the automatic setting on 'reading" on tracker status when a chapter is finished.
Some people have their own methods to sort their Mangas/Manhwas, that feature ruins completely my sort and i find that feature really intrusive.

Thanks for reading

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-06-19 20:14
Duplicate of #5588, which was already shared with you on Discord.

**Closed by arkon** 2022-06-19 20:14 UTC
Labels: Feature request

**Comment by NotMoumix** [comment] 2022-06-19 20:22
That's your words on #5588, "I'm fine with it (updating states/dates logically like J2K) potentially be a setting", so why do you still don't make it

**Comment by arkon** [comment] 2022-06-19 20:23
Don't cherry-pick my words for your argument; read the rest of the issue discussion.
