### ISSUE TITLE
Use webdav to automatically

### ISSUE THREAD

**Issue by onecreeper** [tachiyomiorg/tachiyomi#8819] opened 2022-12-29 17:21 UTC
### Describe your suggested feature

使用webdav去实现自动同步，这样可以在不同平台不同设备同步，多设备用户十分需要的功能

Use webdav to automatically synchronize unlimited platforms

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-12-29 17:26
Duplicate of #7691

**Closed** 2022-12-29 17:27 UTC
Labels: Feature request
