### ISSUE TITLE
Seperate hidden Category/Library/Tab/Filter for NSFW 

### ISSUE THREAD

**Issue by AlyAzeemi** [tachiyomiorg/tachiyomi#6197] opened 2021-11-05 06:35 UTC
### Describe your suggested feature

Give us something to hide our doujins in. I'm one accidental swipe away from exposing my fetishes to the people sitting next to me. I'm sure this is something alot of people would be grateful for.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2021-11-05 06:37
Duplicate of #1508

**Closed** 2021-11-05 06:37 UTC
Labels: Feature request
