### ISSUE TITLE
The libraries don't update

### ISSUE THREAD

**Issue by BiancaneveSporca** [tachiyomiorg/tachiyomi#10342] opened 2024-01-07 18:39 UTC
### Steps to reproduce

The libraries don't update and don't show new chapters when I click on the update button

### Expected behavior

when I click or drag down in the library menu it should update all the libraries present, showing me the released chapters.  

### Actual behavior

instead when I click or drag down in the library menu it starts loading with the percentage but in the end it doesn't really update them, I tried to manually update one manga at a time and that's how it works, but if I try them all at once it doesn't work.

### Tachiyomi version

0.15.1

### Android version

Android 13

### Device

Poco f3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2024-01-07 18:39
Duplicate of #10313

**Closed by arkon** 2024-01-07 18:39 UTC
Labels: Bug
