### ISSUE TITLE
Automatic downloads not functioning

### ISSUE THREAD

**Issue by amethyyyst** [tachiyomiorg/tachiyomi#10347] opened 2024-01-07 21:45 UTC
### Steps to reproduce

I have been using this feature for a long time and when the first two chapters are already downloaded, the next chapters are not being automatically downloaded while reading

### Expected behavior

While reading, the next 5 chapters should automatically download as the first 2 chapters were already downloaded

### Actual behavior

The chapters are not downloading as expected and only the previous manually downloaded chapters are saved as downloaded

### Tachiyomi version

App version: 0.15.0 (standard, a3ef360, 115, 2024-01-06T15:41Z) 

### Android version

Android 12

### Device

OPPO Reno 4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2024-01-07 21:46
Duplicate of #10151

**Closed by arkon** 2024-01-07 21:46 UTC
Labels: Bug
