### ISSUE TITLE
Partial grey on unread chapter

### ISSUE THREAD

**Issue by Helltraitor** [tachiyomiorg/tachiyomi#9435] opened 2023-05-01 21:23 UTC
### Steps to reproduce

Possible steps to reproduce:
1. Make library index (reindex) downloades chapters
2. Choose some manga
3. Push your luck

### Expected behavior

Unread chapters fully white

### Actual behavior

Some chapters (always one as I remember) partial white (date) and grey (name)

### Tachiyomi version

0.14.6

### Android version

Android 11

### Device

Realme 8 Pro

### Other details

![Screenshot_2023-05-01-12-45-12-54_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/95148327/235533629-33684203-dfbf-4082-9909-a5266d796522.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Helltraitor** [comment] 2023-05-01 21:28
First enter to large one (tried to reproduce). Thats lead to flush indexed data (?), but application wasn't closed
![Screenshot_2023-05-02-00-25-05-06_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/95148327/235534547-6dba030a-19f5-4889-982d-05f4ce3cd371.jpg)

Then I reenter and app updates index, but bag moves to other chapter
![Screenshot_2023-05-02-00-25-14-19_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/95148327/235534646-d3408b93-2f85-4c4d-af45-4f69253dc006.jpg)

**Comment by arkon** [comment] 2023-05-01 21:45
Duplicate of #9043. This is fixed in preview, but the fix hasn't made it to a stable release yet.

**Closed by arkon** 2023-05-01 21:45 UTC
Labels: Bug
