### ISSUE TITLE
[Bug] Tachiyomi is not loading manga

### ISSUE THREAD

**Issue by Bbk2468** [tachiyomiorg/tachiyomi#5004] opened 2021-05-02 03:00 UTC
PLEASE READ THIS*

I acknowledge that:

I have updated:
To the latest version of the app (stable is v0.10.12)
All extensions
I have tried the troubleshooting guide: https://tachiyomi.org/help/guides/troubleshooting-problems/
If this is an issue with an extension, that I should be opening an issue in https://github.com/tachiyomiorg/tachiyomi-extensions
I have searched the existing issues and this is new ticket NOT a duplicate or related to another open issue
I will fill out the title and the information in this template
Note

Device information
Tachiyomi version: 0.10.12
Android version: Android 11
Device: Samsung M21
Steps to reproduce
Open apps
Browse the manga
Expected behavior
Apps is running normally

Actual behavior
Most of the extension is not working. Only work on webview.

Other details
![Screenshot_20210502-083753_Tachiyomi](https://user-images.githubusercontent.com/60810986/116800623-9dd2ae80-ab22-11eb-86a5-bc7b2ce8edf8.jpg)
![Screenshot_20210502-083803_Tachiyomi](https://user-images.githubusercontent.com/60810986/116800625-9f9c7200-ab22-11eb-8713-dda25b6509e5.jpg)
![Screenshot_20210502-083949_Tachiyomi](https://user-images.githubusercontent.com/60810986/116800626-a0cd9f00-ab22-11eb-8dd0-7e1eacecff15.jpg)

**Comment by arkon** [comment] 2021-05-02 17:15
Duplicate of #5003

**Closed by arkon** 2021-05-02 17:15 UTC
Labels: bug
