### ISSUE TITLE
Reader lags with high res images

### ISSUE THREAD

**Issue by weedsnorkeler** [tachiyomiorg/tachiyomi#5884] opened 2021-09-10 17:59 UTC
### Steps to reproduce

1. Read a manga with high res images (I'm reading Ultimate Spider-Man via ReadComicOnline)
2. Scroll over a widescreen page (i believe thats the issue since it lags a lot when there is a widescreen page either before or after the page im currently reading)

### Expected behavior

It not to lag while zooming in/out or scrolling across the page.

### Actual behavior

It lags a lot for a good few seconds.

### Tachiyomi version

0.12.1

### Android version

Android 9

### Device

Galaxy A20s

### Other details

Unsure if this is just my phone being slow or not but this wasn't a problem in previous versions.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2021-09-10 18:47
Duplicate of #1908

**Closed** 2021-09-10 18:47 UTC
Labels: Bug
