### ISSUE TITLE
Scrolling outside of the manga (scrolling on black bars while zoomed out)

### ISSUE THREAD

**Issue by gosndule** [tachiyomiorg/tachiyomi#7362] opened 2022-06-24 13:22 UTC
### Describe your suggested feature

I usually read manga with my phone placed horizontally. I love that this app provides the option to zoom out, but I have to place my finger on the manga pages themselves for it to scroll. It'd be nice if there was an option in the settings where you can toggle scrolling even on the outside of the manga (black bars on both sides of the page).

Thanks for your work, it's an amazing app!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-06-26 02:21
Duplicate of #3127

**Closed by arkon** 2022-06-26 02:21 UTC
Labels: Feature request
