### ISSUE TITLE
Option to Retain Zoom Settings on a Page

### ISSUE THREAD

**Issue by floppygibbon** [tachiyomiorg/tachiyomi#8332] opened 2022-10-29 12:12 UTC
### Describe your suggested feature

Is it practical to add a setting that would allow you to cache the zoom percentage/position for a given image after you turn the page?  The app currently retains your zoomed orientation as long as you turn back to the original page before advancing twice, so it would be neat if users could extend that range to the whole chapter or something.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-10-29 13:10
Duplicate of #1822

**Closed** 2022-10-29 13:11 UTC
Labels: Feature request
