### ISSUE TITLE
[Feature Request] <Write short description her>
Source migration feature to return it

### ISSUE THREAD

**Issue by mohammedjtf** [tachiyomiorg/tachiyomi#4438] opened 2021-02-10 19:18 UTC
---

## Why/User Benefit/User Problem
(explain why this feature should be added)
It's too troublesome to migrate more
 than 500 manga one by one 

## What/Requirements
(explain how this feature would behave)
 To migrate more than one manga to another source

**Comment by Seishirou101** [comment] 2021-02-10 19:21
duplicate of #1729

**Closed** 2021-02-10 19:26 UTC
Labels: feature
