### ISSUE TITLE
[Feature Request] A feature to hide manga saved in the library

### ISSUE THREAD

**Issue by tripathi-abhishek** [tachiyomiorg/tachiyomi#4458] opened 2021-02-12 05:40 UTC
## Why/User Benefit/User Problem
Sometimes we read doujins but don't want others to know specially non-manga reader. This feature will help us hide it.

## What/Requirements
There should be a three vertical dots at upper right corner on library page, there we can have a 'hide feature' as an option. Same for 'unhide' too.

**Comment by scb261** [comment] 2021-02-12 11:18
Duplicate of #1508

**Closed** 2021-02-12 13:54 UTC
Labels: feature

**Comment by tripathi-abhishek** [comment] 2021-02-13 05:06
Ok, I didn't know this was already there. Sorry for the trouble. :)
