### ISSUE TITLE
Filter chapters by upload source

### ISSUE THREAD

**Issue by Xhyus** [tachiyomiorg/tachiyomi#8385] opened 2022-10-31 08:11 UTC
### Describe your suggested feature

In some extensions like "TuMangaOnline" or others they allow more than one source to upload the chapters from some manga, so sometimes you get a list with 3 stacked “Chapter 1” and it's a little annoying to skip the chapter three times to get to the next. I feel like the filter must be for upload author, so you can see only the chapters from that upload source or something like that.
Here's an image to show the list of chapters.

![image](https://user-images.githubusercontent.com/77308423/198960664-2400e25b-52aa-46f3-a4ab-8c73769fdc13.jpeg)

### Other details

Maybe I'm wrong uploading this issue for the app and not the extension but I feel this must be on this repo because it's a filter for every extension? And not a particular solution for just one extension.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-10-31 12:28
Duplicate of #969

**Closed** 2022-10-31 12:29 UTC
Labels: Feature request
