### ISSUE TITLE
Auto Update

### ISSUE THREAD

**Issue by Benimaruuu** [tachiyomiorg/tachiyomi#4205] opened 2020-12-27 22:04 UTC
Suggestion: If I update my anilist (chapters) it should automatically make the chapter on the manga darkened.
![Screenshot_20201227-170534_Tachiyomi](https://user-images.githubusercontent.com/76666556/103180661-c2add100-4865-11eb-900d-14489d4f3bd9.jpg)
![Screenshot_20201227-170435_Tachiyomi](https://user-images.githubusercontent.com/76666556/103180662-c7728500-4865-11eb-97a4-20269e9dff58.jpg)

**Comment by scb261** [comment] 2020-12-27 22:08
Duplicate of #1626

**Closed** 2020-12-27 22:16 UTC
Labels: feature
