### ISSUE TITLE
[Bug] <Tracker mistake>

### ISSUE THREAD

**Issue by MarcosSouza2004** [tachiyomiorg/tachiyomi#4811] opened 2021-04-11 17:58 UTC
## Device information
* Tachiyomi version: 0.10.9
* Android version: 10
* Device: Galaxy A80

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
This should happen: (Hypothetical situation) You were reading some manga at tachiyomi and switched (the reading) to your pc, read some chapters and returned to tachiyomi, now you "mark as read" the chapterss you readed on pc.... but the traker dont update the chapters who you "mark as read"

## Other details
Prints to exemplify: 
![image](https://user-images.githubusercontent.com/76596575/114315624-25a23b80-9ad6-11eb-8d95-a3ba3f9a57b7.png)

![image](https://user-images.githubusercontent.com/76596575/114315634-2dfa7680-9ad6-11eb-9875-41d7945a63db.png)

![image](https://user-images.githubusercontent.com/76596575/114315642-35ba1b00-9ad6-11eb-9f77-f6b8a4f60e6b.png)

(Sorry for the english, i'm not fluent)

If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.

**Comment by arkon** [comment] 2021-04-11 18:05
Duplicate of #1626, to be addressed by #3705.

**Closed by arkon** 2021-04-11 18:05 UTC
Labels: bug
