### ISSUE TITLE
[Feature Request] Add a feature where you can name bookmarks or rename a chapter and an option where you can backup the bookmarks and or chapters that have been renamed.

### ISSUE THREAD

**Issue by NotPageD** [tachiyomiorg/tachiyomi#4425] opened 2021-02-09 15:55 UTC
## Request
I would like for the lovely developers to add a feature to name bookmarks or maybe just a feature to rename chapters and also an option where you can backup either of them. 

You guys can choose whichever is easiest for you guys to code, i don't really care but if you do add it, man it would be so good.

## Why/User Benefit/User Problem
I put bookmarks on chapters a lot so i can instantly see what chapters contain the beginning of a certain volume so it would be so useful if the chapters can be renamed and or bookmarks can be named and you can also backup those things so when you wanna move your library you wouldn't have to painstakingly do it all over again.

## What/Requirements
What i explained above, if you're asking for codes. I can't code to save my life but please implement this, it would be just such a quality of reading improvement and so many other readera can also benefit from it. 

Thank you very much.

**Comment by arkon** [comment] 2021-05-29 02:56
Closing as duplicate of #5043, which is more clearly written.

**Closed by arkon** 2021-05-29 02:56 UTC
Labels: feature
