### ISSUE TITLE
zip/cbz not working 

### ISSUE THREAD

**Issue by mobi2002** [tachiyomiorg/tachiyomi#9464] opened 2023-05-07 00:03 UTC
### Steps to reproduce

1. Download a chapter
2. Read

### Expected behavior

Zip file opened successfully and shown in reader 

### Actual behavior

Errors

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/11413602/tachiyomi_crash_logs.txt)

### Tachiyomi version

r5766

### Android version

Android 13

### Device

Tecno spark 6 

### Other details
[Sample cbz](https://cdn.discordapp.com/attachments/364330965444853761/1104559816095051856/Chapter_1.cbz)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-05-07 02:48
Duplicate of #9465

**Closed by arkon** 2023-05-07 02:48 UTC
Labels: Bug
