### ISSUE TITLE
[Feature Request] <Measure the speed in the updated manga (TMO And maybe others if they need it)>

### ISSUE THREAD

**Issue by lonjaz** [tachiyomiorg/tachiyomi#4473] opened 2021-02-14 05:07 UTC
## Why/User Benefit/User Problem
(explain why this feature should be added)
This is more due to personal use but it can favor others who consume manga in Spanish, Since TMO (TuMangaOnline) always occurs the error 429 on its page due to excess requests, it can be avoided I know, but it is that almost all the manga  What consumption is on your page, I do not know English (bad part of me) and I do not have that page because in most or almost all of what I consume there may be an alternative but it is not at all comfortable with that if it  that manga or not.  Well, what I wish it was would be the speed of updating the chapters, if it is slower or faster depending on which page it is, in tmo the excess makes your ip banned and well, I have seen in other apps, one of  them in "My Manga Nu" that when updating chapters it does so slowly and that error never occurs, absolutely never, even if you have more than 1000 manga added to the library.

## What/Requirements
(explain how this feature would behave)
The function could make more people achieve comfortable with any extension without fear that you should migrate a certain amount to each one, but hey, I say it more for the people who consume much more manga than normal. And that will depend on one if you want or not. This functioning would be in settings but it would be something with conditions, if you have a certain amount you can only use with that function because if others were used, overload the extension of which you use, if it only outside for someone who has less than 10 sleeves added by giving an example. That is why it is something more experimental.

**Comment by lonjaz** [comment] 2021-02-14 05:08
Perhaps it is something that has already been discussed and discussed, but I would like if it were possible to implement it.

**Comment by scb261** [comment] 2021-02-14 05:24
It's a bit hard to understand you, do you want
- statistics for requests that were sent
- configurable rate limiting by user
- something else

?

**Comment by lonjaz** [comment] 2021-02-14 05:37
Because I use translator, it is not well understood, but to sum it up.

I give an example: I have more than 700 manga added and I want to update all of them without making that error because there are many.  In "My manga Nu", that amount of updates whether or not you have chapters, you never get that error because it is slow when updating. In tachiyomi it does that to you in minutes and generates error 429 because it is much faster when making requests and TMO takes you as a bot. In tachiyomi in a few minutes you have it, in my manga nu, you have it in more than 1 hour updating.  It is preferable to avoid excesses of error 429 (that of excessive requests), that you can customize the speed of update of the manga you have. Since this way, you avoid problems

**Comment by DarremMolko** [comment] 2021-02-14 11:28
> It's a bit hard to understand you, do you want
> 
> * statistics for requests that were sent
> * configurable rate limiting by user
> * something else
> 
> ?

Definitely the second option.

**Comment by scb261** [comment] 2021-02-14 13:18
Duplicate of #2976

**Comment by arkon** [comment] 2021-02-14 14:21
If TMO needs rate limiting, open an issue for that in the extensions repo.

**Closed by arkon** 2021-02-14 14:21 UTC
Labels: feature

**Comment by lonjaz** [comment] 2021-02-14 19:49
Okay
