### ISSUE TITLE
select and/or filter

### ISSUE THREAD

**Issue by pavonismc** [tachiyomiorg/tachiyomi#7720] opened 2022-08-11 04:27 UTC
### Describe your suggested feature

the filter list under each anime and manga could have an or gate option like downloaded or unseen chapters are to be seen

### Other details

visual representation of what I meant by filter list:
https://screenshotflow.com/?open=1COYNPO8x9nvx8YmWsVFN_OGPqD7zOGiX
example of the feature:
https://screenshotflow.com/?open=1JyhD0KCbdOUV6qp2n7CMFeiRwyIyz8ug

https://github.com/tachiyomiorg/tachiyomi/issues/6958
didn't search at all sorry

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-08-11 12:02
Duplicate of #6958

**Closed by arkon** 2022-08-11 12:02 UTC
Labels: Feature request
