### ISSUE TITLE
[Bug] <Android 6.x no longer supported when checking for updates>

### ISSUE THREAD

**Issue by edwardthehuman** [tachiyomiorg/tachiyomi#5035] opened 2021-05-07 00:32 UTC
**PLEASE READ THIS**

I acknowledge that:

- I have updated:
  - To the latest version of the app (stable is v0.10.12)
  - All extensions
- I have tried the troubleshooting guide: https://tachiyomi.org/help/guides/troubleshooting-problems/
- If this is an issue with an extension, that I should be opening an issue in https://github.com/tachiyomiorg/tachiyomi-extensions
- I have searched the existing issues and this is new ticket **NOT** a duplicate or related to another open issue
- I will fill out the title and the information in this template

Note that the issue will be automatically closed if you do not fill out the title or requested information.

## Device information
* Tachiyomi version: Stable v0.10.12
* Android version: 6.0.1
* Device: LG Nexus 5

## Steps to reproduce
1. About>Check for updates

### Expected behavior
it should say "No new updates available"
 
### Actual behavior
It says my Android version (6.0.1) is no longer supported. As far as I know only 5.x has been dropped. 

## Other details
On the latest preview r3346 I still get the usual "No new updates available" prompt.

**Comment by arkon** [comment] 2021-05-07 00:34
Duplicate of #4992

**Closed by arkon** 2021-05-07 00:34 UTC
Labels: bug
