### ISSUE TITLE
Chapters not removed when migrating

### ISSUE THREAD

**Issue by JarekDerp** [tachiyomiorg/tachiyomi#9020] opened 2023-02-04 10:42 UTC
### Steps to reproduce

1. Add a Manga to library
2. Download all the chapters (i.e. 2GB of chapters)
3. Migrate manga to different server 
4. Download all the chapters from the new server 
5. Now in the tachi's folders you have 4GB taken, as the chapters don't get deleted. Even when you delete the chapters from the source you're currently reading, the chapters from the previous server will keep hogging 2GB.

### Expected behavior

Chapters downloaded from the previous server are removed when migrating.

### Actual behavior

Chapters downloaded from the server before migrating will always live on your phone, buried in the folders.

### Tachiyomi version

0.14.3

### Android version

Android 11

### Device

Motorola G60

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-02-04 14:58
Duplicate of #2108

**Closed by arkon** 2023-02-04 14:58 UTC
Labels: Bug
