### ISSUE TITLE
A randomize button for manga in the library.

### ISSUE THREAD

**Issue by NotPageD** [tachiyomiorg/tachiyomi#5608] opened 2021-07-26 01:21 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

Pretty self explanatory. Basically, if you have too many manga like i do in the library and having trouble choosing which to read, you can just press the randomize button and then the app randomly picks a manga from your library to read.

**Comment by loocool2** [comment] 2021-07-26 01:22
Duplicate of #1248

**Closed by loocool2** 2021-07-26 01:22 UTC
Labels: Feature request
