### ISSUE TITLE
Chapter Notification, Chapters Not Updating

### ISSUE THREAD

**Issue by SiyanLuwi** [tachiyomiorg/tachiyomi#10327] opened 2024-01-07 10:14 UTC
### Steps to reproduce

1. I tried updating the whole library
2. Manual updating each category

### Expected behavior

There should be a notification where the update or updating shows and notify me if it is updated

### Actual behavior

The Library shows "updating library" but not showing if it's updating via the notification bar, couple minutes passed then nothing happened 
and when I tried to check the site there is an update for a novel that I'm reading.

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/13852946/tachiyomi_crash_logs.txt)

### Tachiyomi version

0.15.0

### Android version

Android 12

### Device

Tecno Pova 4

### Other details

Here is a screenshot sample also I already check the notification settings and it is all turned on and the library doesn't update ever since I updated the app

![Screenshot_20240107-181253](https://github.com/tachiyomiorg/tachiyomi/assets/145175874/42cdd3c0-78db-4c83-8f23-7da216839466)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Achuabdu** [comment] 2024-01-07 10:33
@SiyanLuwi  bro can u tell me the name of the last manga in the ss

**Comment by SiyanLuwi** [comment] 2024-01-07 10:34
> @SiyanLuwi  bro can u tell me the name of the last manga in the ss

Helmut: The Forsaken Child

**Comment by Achuabdu** [comment] 2024-01-07 10:36
> > @SiyanLuwi  bro can u tell me the name of the last manga in the ss
> 
> Helmut: The Forsaken Child 

Tnx bro

**Comment by arkon** [comment] 2024-01-07 14:38
Duplicate of #10313

**Closed by arkon** 2024-01-07 14:38 UTC
Labels: Bug
