### ISSUE TITLE
Scroll allowed in black bars (zoomed out) in continuous vertical reading mode

### ISSUE THREAD

**Issue by ScaredDoggo** [tachiyomiorg/tachiyomi#6176] opened 2021-10-30 11:27 UTC
### Describe your suggested feature

I use a Tablet and almost all the time I need to zoom out but scrolling is difficult since my thumb has to reach the page area to scroll, it would be much better if I can scroll through black bars also

### Other details

![tachiyomi issue](https://user-images.githubusercontent.com/73882678/139531104-ef459ef4-0ee8-4c87-97f4-85342c211f96.jpeg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2021-10-30 13:01
Duplicate of #3127

**Closed by arkon** 2021-10-30 13:01 UTC
Labels: Feature request
