### ISSUE TITLE
[Feature Request] Show second half of double page when tapping

### ISSUE THREAD

**Issue by pig-cop** [tachiyomiorg/tachiyomi#3853] opened 2020-09-27 12:52 UTC
I don't know if I missed some option this time too (:P) but tapping when using smartfit now jumps to the next page even in case of double pages.
The only way to see the other half part of the double page is by swiping.
While it's fine in double pages that are clearly cut in half, for some manga (like OnePice) it's not always so evident and sometimes it happens to skip the second half of the double page by tapping, without immediately realizing it.

See this video to see what I mean: https://files.catbox.moe/fpy52o.webm

**Comment by arkon** [comment] 2021-01-04 22:37
Duplicate of #2161

**Closed by arkon** 2021-01-04 22:37 UTC
Labels: feature
