### ISSUE TITLE
Keep and show the downloaded chapters in the list even if the source deleted them from their website

### ISSUE THREAD

**Issue by Palloxin** [tachiyomiorg/tachiyomi#8992] opened 2023-01-27 20:20 UTC
### Describe your suggested feature

If a source deletes some chapters of an entry from their website and i have these chapters saved (downloaded) don't make them disappear.

### Other details

KissManga lost some chapters but i had entries saved in my library and a lot of chapters downloaded. Now that i refreshed to update some entries (kissmanga continue to updates their entries despite the previous ones not being present) the downloaded chapters disappeared from my list but they are still counted.

https://user-images.githubusercontent.com/75091899/215189351-ba0d8681-17fa-4307-a5bf-faba8de0fc9e.mp4

In the video you can see that i have 6 downloaded chapters but once i refreshed that entry they disappeared from my list BUT they are still there (downloaded)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2023-01-28 00:58
Duplicate of #3958

**Closed by stevenyomi** 2023-01-28 00:58 UTC
Labels: Feature request

**Comment by curche** [comment] 2023-01-28 01:56
Also better option is: #2289
