### ISSUE TITLE
Switch mangas from manga screen as well

### ISSUE THREAD

**Issue by radha1990kumari** [tachiyomiorg/tachiyomi#7388] opened 2022-06-26 20:09 UTC
### Describe your suggested feature

For eg you have 4 mangas on main screen and then you open one of the manga (where chapters and details are shown) now on swiping left or right on this screen will correspondingly load next or previous manga from the list. 

Currently one has to open a manga page refresh it to see the updates then go back then open other to see if new chapters have arrived.
This will reduce the double transition  from manga to manga list screen. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-06-26 20:11
Duplicate of #6162/#4602

**Closed by arkon** 2022-06-26 20:11 UTC
Labels: Feature request
