### ISSUE TITLE
Touch & hold to use "Magnifying Lens" to view content under touch inside a Zoom-box-view

### ISSUE THREAD

**Issue by AsifulHaque** [tachiyomiorg/tachiyomi#9734] opened 2023-07-18 06:21 UTC
### Describe your suggested feature

For regular mobile screens most of the times the lettering is too hard to read due to their small size. Apps like "[Comictrim](https://play.google.com/store/search?q=comictrim&c=apps)" solved this issue by using a **_Zoom-Preview-Box_** feature. 

Basically when you touch and hold on anywhere on a page then a **_Zoom-Preview-Box_** appears on one side of the screen in which the content currently under finger-touch is zoomed and previewed. The **_Zoom-Preview-Box_** disappears as soon as the finger-touch is let go. The location of the **_Zoom-Preview-Box_** is determined simply by reading the location of the touch on the screen from the center and placing the **_Zoom-Preview-Box_** on the other side.

Here is a link to a video on how it works: https://youtu.be/3bs434cDgsc

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment] 2023-07-18 07:14
Duplicate of #2599

**Closed by loocool2** 2023-07-18 07:14 UTC
Labels: Feature request
