### ISSUE TITLE
2 column view

### ISSUE THREAD

**Issue by Qihai-Weng** [tachiyomiorg/tachiyomi#10033] opened 2023-10-18 02:29 UTC
### Describe your suggested feature

the space on the screen is not optimized when using large-screen devices such as foldable phones. Please add 2 column/page view, the experience using the app will be much better on big devices.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-10-18 02:34
Duplicate of #149

**Closed by arkon** 2023-10-18 02:34 UTC
Labels: Feature request
