### ISSUE TITLE
Pages not showing in webtoon view

### ISSUE THREAD

**Issue by RamishSiddiqui** [tachiyomiorg/tachiyomi#5954] opened 2021-09-22 10:40 UTC
### Steps to reproduce

1. Select tomb raider king manga from comick.fun extension.
2. Load chapter 240.
3. Go to 2nd or 3rd page.
4. Switch to webtoon view.

### Expected behavior

Should load the chapters pages.

### Actual behavior

Shows a blank screen. 

### Tachiyomi version

0.12.2

### Android version

Android 7

### Device

Oppo A57

### Other details

It happens when the pages are long. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by scb261** [comment] 2021-09-22 13:48
Duplicate of #3514. Maybe add `Oppo` to the title of #3514?

And just to confirm about *It happens when the pages are long* - do you mean that small pages in Webtoon mode are shown without issues? If yes, then it looks like #1908, and Oppo just won't display images instead of lagging/crashing like most of other devices.

**Comment by RamishSiddiqui** [comment] 2021-09-22 14:44
It displays just fine in another views just have zoom it manually and read it but in webtoon view if the page is long blank screen is shown. If the page is short it works perfectly. The issue resides with the long pages.

**Comment by arkon** [comment] 2021-11-19 22:27
Duplicate of #1908

**Closed by arkon** 2021-11-19 22:27 UTC
Labels: Bug
