### ISSUE TITLE
[Bug] Webtoon and continous vertical navigation bugs after zooming out

### ISSUE THREAD

**Issue by developedby** [tachiyomiorg/tachiyomi#3555] opened 2020-08-02 03:15 UTC
### Device information
* Tachiyomi version: Preview r2601
* Android version: 8.1.0
* Device: Motorola Moto G 5

## Steps to reproduce
1. Open a chapter
2. Set reading mode to Webtoon or Continuous Vertical
3. Zoom out
4. Tap the screen to scroll

### Expected behavior
Should move up if tapping the top, etc.

### Actual behavior
Most of the screen moves up. Tapping the very bottom does what the middle should do (shows menu).

### Other details
If zooming in again by double tapping, the bug persists even when not zoomed out, or if double-tapped again, even when zoomed in.

If zooming in by streching with two fingers, the behaviour goes back to normal after reaching normal zoom level.

Most likely related to #3052 , they occur together as far as I've tested.

**Comment by von-wa** [comment] 2020-08-03 03:53
i also noticed this since i accidentally zoom in quite a lot. exiting the manga and opening again fix the issue but it's quite the hassle.

**Comment by stevenyomi** [comment] 2023-01-24 16:38
Duplicate of #4875

**Closed by stevenyomi** 2023-01-24 16:38 UTC
Labels: Bug
