### ISSUE TITLE
Restoring a 5mb backup takes more than 2 hours ._.

### ISSUE THREAD

**Issue by AethersKz** [tachiyomiorg/tachiyomi#9533] opened 2023-05-22 00:45 UTC
### Steps to reproduce

I mainly use J2K and wanted to migrate to another tachiyomi. Before the backups were restored in 5 minutes at most, but now it takes hours.

The backup is from J2K, I tried to restore it in SY, SY Preview and the official Tachiyomi, but in all of them the same thing happens.
![IMG_20230521_193043](https://github.com/tachiyomiorg/tachiyomi/assets/96607644/83be3366-6c2c-4595-b306-67edbb774585)
The backup only has 3500 comics, I never finished restoring it because I got tired of waiting....

### Expected behavior

.

### Actual behavior

.

### Tachiyomi version

0.14.6

### Android version

Android 11

### Device

Redmi 9A

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by THElegend5** [comment] 2023-05-22 20:23
Duplicate of #8853.

**Comment by arkon** [comment] 2023-05-22 20:32
Also if it isn't actually making any progress -- https://dontkillmyapp.com/xiaomi

**Closed by arkon** 2023-05-22 20:32 UTC
Labels: Bug
