### ISSUE TITLE
Set manga that i started reading as 'Currently reading' and completed manga as 'Completed' on mal

### ISSUE THREAD

**Issue by soredake** [tachiyomiorg/tachiyomi#5618] opened 2021-07-27 18:12 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

Would be nice if tachiyomi can set manga that i started reading as 'Currently reading' and completed manga as 'Completed' on mal.

### Other details

Currently, i started reading manga from PTW list, and tachiyomi just updates status in PTW without putting it to CR list, and after completing manga is not marked as completed on mal.

**Comment by arkon** [comment] 2021-07-31 03:17
Duplicate of #4598

**Closed by arkon** 2021-07-31 03:17 UTC
Labels: Feature request
