### ISSUE TITLE
Rolling Download

### ISSUE THREAD

**Issue by dmuller104** [tachiyomiorg/tachiyomi#7567] opened 2022-07-20 21:05 UTC
### Describe your suggested feature

I suggest a feature called "rolling download" (or something similar). The user has the option to activate "rolling download" for a manga. This causes the app to automatically download the next 2 (or so) chapters after the current reading point, and it would automatically mark to delete chapters before the most recent one read.

For example,
I have completely read chapters 1,2,3,4, and 5 of a manga with 10 current chapters. If I activate "rolling download" for this manga then chapters 5,6,7 are marked to be downloaded. Once I have fully read chapter 6, chapter 5 is marked to be deleted and chapter 8 is marked to be downloaded. 
Once I have read all 10 chapters then chapter 10 is the only one that remains downloaded. Upon the release of chapter 11, chapter 11 would be downloaded as well.

There could be an added option to let the user define how many chapters in advance to download vs how far back the chapters should wait before deleting.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment] 2022-07-20 21:05
Duplicate of #3295

**Closed** 2022-07-20 21:05 UTC
Labels: Feature request
