### ISSUE TITLE
[Bug] Local source manga in the library shows checkbox for "Downloaded chapters"

### ISSUE THREAD

**Issue by CPterion** [tachiyomiorg/tachiyomi#5243] opened 2021-05-30 22:26 UTC
## Device information
* Tachiyomi version: Stable 0.10.12
* Android version: 6.0
* Device: Huawei Mate 8

## Steps to reproduce
1. Add a manga to the Local source
2. Add that manga to the Default library (doesn't matter which one)
3. Remove downloaded chapters

### Expected behavior
The chapters would be deleted in the device and also in the Local source.

### Actual behavior
They are still in there, both in the device and Local.

## Other details
There's no delete icon for the chapters in the Local source, so is this the expected behavior? Technically it's correct as the added manga were not downloaded from the app, but it's tedious to switch to the file manager just to delete the chapters.

**Comment by arkon** [comment] 2021-05-30 22:30
Duplicate of #1770

**Comment by CPterion** [comment] 2021-05-30 22:39
I think it's different. The local manga was added to the library, and shows a checkbox for the "Downloaded chapters" when the delete icon is chosen.

**Comment by arkon** [comment] 2021-05-30 22:51
I see, we should hide that. The delete options were intentionally removed since:

- it didn't work
- some people may be under the impression that it just removed it from Tachiyomi and then get upset that it deleted the actual data

**Closed** 2021-09-12 17:09 UTC
Labels: Bug
