### ISSUE TITLE
feature request : last chapter number in library under each manga icon

### ISSUE THREAD

**Issue by pheonix727** [tachiyomiorg/tachiyomi#4801] opened 2021-04-09 11:29 UTC
i dont like to open the updates section to know if there are new chapters
i have the same manga favourited 5 times from 5 different sources and becomes a hassle to know if the new chapter notification here is actually a chapter that i have read or a new one
 
example in photo

![SmartSelectImage_2021-04-09-13-28-01](https://user-images.githubusercontent.com/38658320/114173725-e6d67f00-9937-11eb-9dd5-5d995e1f6194.jpg)

**Comment by arkon** [comment] 2021-05-29 02:51
Duplicate of #2014

**Closed by arkon** 2021-05-29 02:51 UTC
Labels: feature
