### ISSUE TITLE
Start Date is not set

### ISSUE THREAD

**Issue by joaoandre120** [tachiyomiorg/tachiyomi#9203] opened 2023-03-12 17:05 UTC
### Steps to reproduce

1-Add a manga to list 
2-Add a tracker 
3-Read the first and second chapter
4-Open tracker list, the start date won't be set

PS. If you read the first chapter and open the tracker list it's going to set the start date.

### Expected behavior

Should set the start date, regardless of opening the list of trackers or not.

### Actual behavior

https://user-images.githubusercontent.com/7441934/224559855-ecc16e02-3f6a-46ca-bd82-4e5c09512eee.mp4

### Tachiyomi version

0.14.5

### Android version

Android 10

### Device

Umidigi A9 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-03-12 17:08
Duplicate of #6734

**Closed by arkon** 2023-03-12 17:08 UTC
Labels: Bug

**Comment by scb261** [comment] 2023-03-12 17:13
I think it's different?
#6734 is about adding the tracker after you started reading.
This one is adding the tracker before you started reading. Lately I've noticed the same issue.

**Comment by arkon** [comment] 2023-03-12 17:14
They're sort of the same thing, it should set the start date regardless.

**Comment by scb261** [comment] 2023-03-12 17:16
#6734 says it does set the date, it's just the current date instead of the actual date when they've read 1st chapter

> When the tracking service finally adds these series and we track them, there will be no issues if we haven't read them yet, but if we have, it will mention reading, which is correct. The date it adds, however, is the current date.

**Comment by arkon** [comment] 2023-03-12 17:17
It's just generally inconsistent and broken. I'll update the other issue to make that more clear.
