### ISSUE TITLE
0.14.0 update - Library's Unread Count sorting behavior changed for series with no unread chapters

### ISSUE THREAD

**Issue by estellise-sidos** [tachiyomiorg/tachiyomi#8336] opened 2022-10-29 15:46 UTC
### Steps to reproduce

1. Sort library by "Unread Count", ascending.

### Expected behavior

Series with unread chapters are sorted to the top of library, in order of fewest unread chapters to most.

Series with no unread chapters are shown after them, sorted alphabetically by title (this was the behavior prior to the 0.14.0 update).

### Actual behavior

Series with unread chapters are sorted correctly.

Series with no unread chapters are sorted the same way they are by the "Last manga update" setting instead of alphabetically. 

There does not appear to be any way to designate the desired secondary sort behavior, and the new behavior is, in my opinion, not useful. This change in secondary sort behavior does not appear to be mentioned in the update notes for 0.14.0, so I suspect it is unintentional.

### Tachiyomi version

0.14.0

### Android version

Android 12

### Device

Google Pixel 3a

### Other details

https://www.reddit.com/r/Tachiyomi/comments/xv8zvy/spooktober_2022_your_library_will_be_gone_tomorrow/iu6k86g/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-10-29 15:48
Duplicate of #7461

**Closed by arkon** 2022-10-29 15:48 UTC
Labels: Bug
