### ISSUE TITLE
Tracking issues

### ISSUE THREAD

**Issue by VorAndVik** [tachiyomiorg/tachiyomi#5810] opened 2021-08-28 04:05 UTC
### Steps to reproduce

1.Take a title with tracking
2.Migrate it to another source.

### Expected behavior

Continuing correct tracking.

### Actual behavior

Stops automatically tracking chapters read.

### Tachiyomi version

0.12.1

### Android version

Android 6

### Device

Xiaomi Redmi note 4x

### Other details

Removing and reinstalling manga and tracking not working.
Perhaps the bug is due to the fact that after the migration, all chapters were marked as read.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2021-09-18 20:35
Not sure how to reproduce this, especially the "Perhaps the bug is due to the fact that after the migration, all chapters were marked as read." part.

**Comment by VorAndVik** [comment] 2021-09-19 11:39
> Not sure how to reproduce this, especially the "Perhaps the bug is due to the fact that after the migration, all chapters were marked as read." part.

When all the chapters (from the first source) were read I migrated to another source with more chapters.
Perhaps I was able to avoid it when I marked the last chapter as unread (not tracking) and then migrated.
Sorry for possible mistakes. I'm not good at English.

**Comment by arkon** [comment] 2021-11-19 15:34
Couldn't reproduce. If you still have the issue, open another issue with more specific steps (exact sources/manga/etc.).

**Closed by arkon** 2021-11-19 15:34 UTC
Labels: Bug
