### ISSUE TITLE
Deleting Comic Problem

### ISSUE THREAD

**Issue by TheKingTermux** [tachiyomiorg/tachiyomi#7056] opened 2022-05-01 21:49 UTC
### Steps to reproduce

When I delete a comic by deleting it from the library and downloaded chapters, and the comic still keeps the chapter.  This makes it even more difficult for me if I have to delete them one by one with the condition that the comics have been deleted from the library

### Expected behavior

All the comic chapters that have been downloaded are deleted

### Actual behavior

Comics still save chapters and can't be deleted in their entirety

### Tachiyomi version

0.13.4

### Android version

Android 11

### Device

Realme 7i

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by raziel100** [comment] 2022-05-01 22:28
Sometimes this happens to me. The chapter in download folder become even broken the name and in forced to go manually deleting it.

**Comment by FourTOne5** [comment] 2022-05-04 02:10
From the discord server
![image](https://user-images.githubusercontent.com/59261191/166614472-80c8ab05-3b17-423a-a615-1b945e65f4bd.png)

The command:
```
adb shell cmd appops set eu.kanade.tachiyomi
android:legacy_storage allow
```

**Comment by TheKingTermux** [comment] 2022-05-04 12:13
> From the discord server ![image](https://user-images.githubusercontent.com/59261191/166614472-80c8ab05-3b17-423a-a615-1b945e65f4bd.png)
> 
> The command:
> 
> ```
> adb shell cmd appops set eu.kanade.tachiyomi
> android:legacy_storage allow
> ```

How to use this command ?

**Comment by raziel100** [comment] 2022-05-04 16:03
> > From the discord server ![image](https://user-images.githubusercontent.com/59261191/166614472-80c8ab05-3b17-423a-a615-1b945e65f4bd.png)
> > The command:
> > ```
> > adb shell cmd appops set eu.kanade.tachiyomi
> > android:legacy_storage allow
> > ```
> 
> How to use this command ?

It's simple, download android debug bridge(adb), you can download it from Google or Android studio, after that enable the developer options in your phone and enable in it the option USB debugging. Connect your phone in your pc and use the adb. You can use cmd or power shell for that. Make sure you're inside the folder that has the adb.exe in the terminal

If you want for stable version do like this in a single line in cmd
. \adb.exe shell cmd appops set eu.kanade.tachiyomi android:legacy_storage allow

And if you want for weekly preview version the command is like this

adb shell cmd appops set eu.kanade.tachiyomi.debug android:legacy_storage allow

**Comment by TheKingTermux** [comment] 2022-05-04 18:47
> > > From the discord server ![image](https://user-images.githubusercontent.com/59261191/166614472-80c8ab05-3b17-423a-a615-1b945e65f4bd.png)
> > > The command:
> > > ```
> > > adb shell cmd appops set eu.kanade.tachiyomi
> > > android:legacy_storage allow
> > > ```
> > 
> > 
> > How to use this command ?
> 
> It's simple, download android debug bridge(adb), you can download it from Google or Android studio, after that enable the developer options in your phone and enable in it the option USB debugging. Connect your phone in your pc and use the adb. You can use cmd or powershell for that. Make sure you're inside the folder that has the adb.exe in the terminal
> 
> If you want for stable version do like this in a single line in cmd . \adb.exe shell cmd appops set eu.kanade.tachiyomi android:legacy_storage allow
> 
> And if you want for weekly preview version the command is like this
> 
> .\adb.exe shell cmd appops set eu.kanade.tachiyomi.debug android:legacy_storage allow

Thanks for the tutorial

**Comment by arkon** [comment] 2022-10-21 21:46
Duplicate of #4286 for slow deletion issue.

**Closed by arkon** 2022-10-21 21:46 UTC
Labels: Bug
