### ISSUE TITLE
drop-down button next to page header, so we can skip chapters without closing it.

### ISSUE THREAD

**Issue by HaraDesu** [tachiyomiorg/tachiyomi#2748] opened 2020-03-22 13:14 UTC
### Why/User Benefit/User Problem
it would make quick chapter skip easier, like when you found that this chapter story is directly issued with 8 chapter before this current chapter, you can directly change chapter without having hassle to click back again.

### What/Requirements
so it behave like drop-down button next to current chapter header (see image below)
when user click it, it shows list of every chapter from this current manga, and user should be able to choose chapter wherever they want, without closing image viewer and searching again.

![image](https://user-images.githubusercontent.com/32463794/77250192-c7ab7780-6c78-11ea-9121-1271cc44022c.png)

ps: my english sucks. but i hope you got the point :)

**Comment by arkon** [comment] 2021-03-13 21:11
Closing this since having a duplicate of the chapters list stuff is a bit redundant.

**Closed by arkon** 2021-03-13 21:11 UTC
Labels: feature
