### ISSUE TITLE
Black screen when viewing pages in Webtoon mode

### ISSUE THREAD

**Issue by alsheikhhusam** [tachiyomiorg/tachiyomi#8081] opened 2022-09-26 00:59 UTC
### Steps to reproduce

1. Open App
2. Click on chapter you want to read
3. Make sure "Webtoon" mode is selected as the reading mode
4. Black screen on all chapters (except the title/cover page)

### Expected behavior

What should happen is all the pages/chapters load normally as they have done previously

### Actual behavior

What actually happens is that the pages don't load but instead turn into black screens. It doesn't crash but just doesn't load the pages/chapters.

### Tachiyomi version

App version: 0.13.6 (standard, 1f79444, 82, 2022-08-14T15:52Z) Android version: 7.1.1 (SDK 25) Android build ID: ONEPLUS A5000_23_171031 Device brand: OnePlus Device manufacturer: OnePlus Device name: OnePlus5 Device model: ONEPLUS A5000 Device product name: OnePlus5

### Android version

7.1.1 - Nougat 64bit

### Device

Bluestacks 5 Emulator

### Other details

When viewing in continuous vertical or sometimes vertical mode, scrolling a few chapters forward or all the way to the end will load the chapters instead of a black screen

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-09-26 01:04
Duplicate of #1908

**Comment by alsheikhhusam** [comment] 2022-09-26 01:05
I have launched the app using Bluestacks X instead of Bluestacks 5 and issue seems to be resolved somehow and no longer seeing a black screen using webtoon mode

**Closed by arkon** 2022-09-26 01:04 UTC
Labels: Bug
