### ISSUE TITLE
Create personal reading list

### ISSUE THREAD

**Issue by Deonchest** [tachiyomiorg/tachiyomi#7214] opened 2022-05-28 15:03 UTC
### Describe your suggested feature

I suggest creating the ability to make our own reading lists to facilitate reading comics or manga from different sources. It should be in the library with the other mangas, with your own chosen title and chosen cover. In the list we can import the chapters and order from different mangas and sources. For example, I want to read marvel comics, but it's really hard for me to get into it because I'll need to find individual comic issues from different sources. E.g. if the order I want to read is Ironman #172, avengers #42, x-men #77, then I've got to get the 3 comics in the library and remember which chapter from each issue that I have to read, and in a particular order. With a reading list, I can just import the required chapters of different comics into the list, arrange the order, and read it like I would read a manga.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-05-28 15:40
Duplicate of #2282

**Closed by arkon** 2022-05-28 15:40 UTC
Labels: Feature request
