### ISSUE TITLE
[Feature Request] Hide individual chapters

### ISSUE THREAD

**Issue by Mugen007** [tachiyomiorg/tachiyomi#4642] opened 2021-03-13 16:45 UTC
## Why/User Benefit/User Problem
(I think this feature can benefit users because they can have the ability to hide duplicated or unwanted chapter/s.) 
## What/Requirements
(1. select the chapter/s you want to hide. 
2. then you have to tap an icon (it could be on the top or bottom) which would hide the selected chapters.
3. the hidden chapters would be placed on a 3-dot drop down menu on top-right corner of the screen which would then be labeled 'hidden chapters' (or something like that) 
4. if you change your mind or want to retrieve a hidden chapter, select the chapter you want and a pop up dialogue appears saying 'show selected chapters'
The hidden chapters should still have all the normal functions like downloading or marked as read.)

**Comment by arkon** [comment] 2021-03-20 13:51
Duplicate of #2542

**Closed by arkon** 2021-03-20 13:51 UTC
Labels: feature
