### ISSUE TITLE
[Feature Request] Library Subcategories

### ISSUE THREAD

**Issue by TheoDrHashiriya** [tachiyomiorg/tachiyomi#4925] opened 2021-04-21 15:02 UTC
## Why/User Benefit/User Problem
- An added option to organize library
- Easier access
- Increase productivity

## What/Requirements
- Can be used to separate different genres, types, languages, styles, etc... of works.

(E.g.
↓SFW
      ↓Marvel Comics
            >Action
            >Drama
      ↓Mangas
            >Slice of Life
            >Romance
or
↓Japanese Content
      ↓English Translations
             ↓SFW
                    >Mangas
                    >Manhwas
                    >NSFW
                    >Other
)

**Comment by Seishirou101** [comment] 2021-04-21 15:06
Duplicate of #1803

**Comment by TheoDrHashiriya** [comment] 2021-04-21 15:08
> Duplicate of #1803

Ah, I apologize. Should I delete it?

**Comment by CrepeTF** [comment] 2021-04-21 15:09
You can close it or wait for a mod to close it

**Comment by TheoDrHashiriya** [comment] 2021-04-21 15:12
> You can close it or wait for a mod to close it

I see, I will do the latter, thanks!

**Closed** 2021-04-21 15:30 UTC
Labels: feature
