### ISSUE TITLE
Extract bookmarked chapter names and the pages along with

### ISSUE THREAD

**Issue by ShockedCoder** [tachiyomiorg/tachiyomi#8153] opened 2022-10-07 20:34 UTC
### Describe your suggested feature

1. button to extract
2. get JSON full of images(base64 or smth) and the bookmarked chapters

### Other details

Where is the raw info for bookmarked chapters?

Mangahub pulled a bitch, but I really wanna keep my bookmarked chapters.

Is there a way to extract the bookmarked chapters? Or the chapter names?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by ShockedCoder** [comment] 2022-10-07 20:35
I have a manhua that's almost 1000 chapters long, and I really don't want to re-read the entire thing and manually bookmark the chapters again.

**Comment by Seishirou101** [comment] 2022-10-07 20:38
Duplicate of #1393 essentially, you can decode the backup and look at that particular manga entry

**Closed by Seishirou101** 2022-10-07 20:38 UTC
Labels: Feature request

**Comment by ShockedCoder** [comment] 2022-10-07 20:40
Mangahub basically returns just 5 chapters, Tachiyomi wouldn't have removed the bookmarks, right?

**Comment by ShockedCoder** [comment] 2022-10-07 20:41
Also, I don't have backups from before Mangahub did this. Since both my updates and backups are automatic the backups containing the info (if it's erased), doesn't exist anymore.

**Comment by Seishirou101** [comment] 2022-10-07 20:43
then it's gone can't bookmark a chapter that is no longer there

**Comment by ShockedCoder** [comment] 2022-10-07 20:49
Shit
