### ISSUE TITLE
[Feature Request] Modular tracker system

### ISSUE THREAD

**Issue by binyaminyblatt** [tachiyomiorg/tachiyomi#4290] opened 2021-01-14 08:25 UTC
Could the tracker system be removed from the app and instead we made into an some form of extension system  so that
A. the app does not need to be re-compiled with an API update to one of the trackers
B. it gives more options for third parties to create trackers for instants comic ￼trackers or manga trackers and allowance for local trackers in lesser ￼used languages￼￼
C. It also means that I don't have to have trackers that I don't need potentially ￼reducing the size of the app￼

**Comment by arkon** [comment] 2021-01-14 13:38
Duplicate of #2187

A. It doesn't happen that often.
B. It being in the app isn't a barrier to entry for other trackers. It's no harder to add it to the app directly than it would be separately.
C. The size impact would be very insignificant.

There's also issues where if it needs to be more complex (which one of the MAL revisions was as it relied on WebView) did require changes to the base app itself.

**Closed by arkon** 2021-01-14 13:38 UTC
Labels: feature
