### ISSUE TITLE
Immediate Exit from Browse Panel

### ISSUE THREAD

**Issue by haganbmj** [tachiyomiorg/tachiyomi#7679] opened 2022-08-04 04:30 UTC
Application exits when navigating to the Browse panel. The panel appears to draw, but exits some number of milliseconds after switching to it. 

Re-launching opens the primary library panel without the loading splash, so I have to assume it's not treating this as a hard crash. The issue then persists until I kill the application and restart entirely, at which point the Browse panel _might_ work as expected. I've had it do this on 3 separate occasions, but is useable in between. 

App version: 0.13.5-4716 (standard, 039fe4a61, 81, 2022-07-30T21:08Z)
Android version: 11 (SDK 30)
Android build ID: GM1917_21_220617
Device brand: OnePlus
Device manufacturer: OnePlus
Device name: OnePlus7Pro
Device model: GM1917
Device product name: OnePlus7Pro

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/9256640/tachiyomi_crash_logs.txt)

**Comment by arkon** [comment] 2022-08-04 13:18
Duplicate of #7642

Please do not bypass the issue templates when creating issues.

**Closed by arkon** 2022-08-04 13:18 UTC

**Comment by haganbmj** [comment] 2022-08-04 14:48
> Duplicate of #7642
> 
> Please do not bypass the issue templates when creating issues.

Ah apologies, it seems like the mobile application I was using doesn't handle issue templates.
