### ISSUE TITLE
[Bug] updated chapter show at notification but doesn't enter download queue

### ISSUE THREAD

**Issue by samanta-widjaja** [tachiyomiorg/tachiyomi#4409] opened 2021-02-08 10:20 UTC
## Device information
* Tachiyomi version: 0.10.8
* Android version: 7.1.1
* Device: xiaomi mi max 2

## Steps to reproduce
1. Library update running automatically according to setting
2. Notification about updated chapter show up
3. None of the chapter in the notification are downloaded or in the download queue

### Expected behavior
The updated chapter should be downloaded because the setting download new chapter is on

### Actual behavior
Updated chapter only show up in notification and not downloaded

**Comment by scb261** [comment] 2021-02-08 10:26
Did you include corresponding categories in the auto-download settings? Looks like duplicate of #4393

**Comment by samanta-widjaja** [comment] 2021-02-08 10:48
I don't have categories. In the setting it said all. But when i click it, it only show default checkbox and not the previous value from the begore version, which is "all'

**Comment by samanta-widjaja** [comment] 2021-02-09 03:24
I found the cause. The chapter is added to the queue after all manga in the library is check. When the network is not stable or cut off in the middle, the chapter is not added at all. My suggestion is the chapter added right after it's found, not after all the checked is done. Thanks

**Comment by arkon** [comment] 2021-02-09 04:09
Do you get an error notification in that case?

**Comment by samanta-widjaja** [comment] 2021-02-09 04:18
I get notification on the download error. But no notification on library update. But when my connection stable like today, it's enter the queue finely

**Comment by arkon** [comment] 2021-02-09 22:56
> When the network is not stable or cut off in the middle, the chapter is not added at all. My suggestion is the chapter added right after it's found

I'm confused. If the network connection drops and we can't check if there's no chapters, how can we queue them?

**Comment by samanta-widjaja** [comment] 2021-02-09 23:20
I Saw from the update tab. There are new chapter detected in there. But it's not in the download queue or downloaded file. The notification from tachiyomi if the network dropped is "no network connection available"

**Comment by arkon** [comment] 2021-02-09 23:31
Still not sure what the issue is, but closing as a duplicate of #4393.

**Closed by arkon** 2021-02-09 23:31 UTC
Labels: bug
