### ISSUE TITLE
Download ahead does not work

### ISSUE THREAD

**Issue by DakshKK** [tachiyomiorg/tachiyomi#9478] opened 2023-05-08 13:58 UTC
### Steps to reproduce

Initial setup
- Manga added to collection in Tachiyomi.
- Configure download ahead to next `n` chapters (5 in my case).
- Initial download of 5 chapters.
- Start reading.

### Expected behavior

When I read 1 chapter, and reach the second chapter, an auto download for the 6th chapter should start.

### Actual behavior

There is no download ahead occuring. I read 5 chapters, and then when I reach the 6th chapter, buffering starts, since on the go download is taking place.

### Tachiyomi version

App version: 0.14.6-5774 (standard, 71f6e07e7, 103, 2023-05-08T02:11Z)

### Android version

9 (SDK 28)

### Device

vivo 1902

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-05-09 02:24
Duplicate of #9471

**Closed by arkon** 2023-05-09 02:24 UTC
Labels: Bug
