### ISSUE TITLE
Tap center seems to slip

### ISSUE THREAD

**Issue by Lagicrus** [tachiyomiorg/tachiyomi#8815] opened 2022-12-28 09:07 UTC
### Steps to reproduce

1. Use the app for an extended period of time
2. Click the centre
3. scrolls down
4. Click bottom 3/4
5. shows menu stuff 

### Expected behavior

When I tap the centre, it shouldn't scroll and instead should title/menus/etc

### Actual behavior

When I tap the centre it scrolls

### Tachiyomi version

0.14.2

### Android version

13

### Device

Pixel 6

### Other details

I am not exactly sure of the repro steps this moment, only that after a while of going through the same manga (without breaks), tapping the same place as I normally do doesn't work and I need to tap quite obviously much lower for it to work

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by RS156** [comment] 2022-12-29 05:13
I will try picking this issues.

**Comment by RS156** [comment] 2022-12-29 08:00
On further triage, this issue is reproducible when user zooms in or zooms out. Then tap center seems to slip. I am new to this project. Will try to look for the package which handles this. Meanwhile, if anyone knows where this issue will likely be found in code, please inform me.

**Comment by arkon** [comment] 2022-12-29 13:36
Duplicate of #4875

**Closed** 2022-12-29 13:36 UTC
Labels: Bug
