### ISSUE TITLE
Mangadoom still has a pop up message about nullnode its been a year and still hasn't been resolved.

### ISSUE THREAD

**Issue by lovablesweet35** [tachiyomiorg/tachiyomi#6701] opened 2022-02-25 18:19 UTC
### Steps to reproduce

1.opening a manga on mangadoom
2.showing a pop up "attempt to invoke virtual 'java.lang.stringorg.jsoup.nodes.Element.owntext()'.on a null object reference.
3.reading is still working but it keeps popping up.

### Expected behavior

No pop ups just being able to read.

### Actual behavior

Keeps on showimg a pop up

### Crash logs

![Screenshot_20220226-021510_Tachiyomi](https://user-images.githubusercontent.com/53226633/155766921-c2a36406-94eb-4422-93cd-171240ba6a5a.jpg)

### Tachiyomi version

0.13.1

### Android version

S21

### Device

S21

### Other details

Please what is the problem??

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-02-25 18:27
Wrong repo / duplicate of https://github.com/tachiyomiorg/tachiyomi-extensions/issues/8701

**Closed by arkon** 2022-02-25 18:27 UTC
Labels: Bug
