### ISSUE TITLE
[Bug]  tracking kitsu

### ISSUE THREAD

**Issue by rafalohaki** [tachiyomiorg/tachiyomi#4324] opened 2021-01-21 00:17 UTC
![image](https://user-images.githubusercontent.com/20607107/105256629-66994c80-5b86-11eb-9591-01fa0f386f4b.png)

Kitsu says it's logged in
But its not
version: preview latest

**Comment by ghostbear** [comment] 2021-01-21 14:50
Can't reproduce on stable v0.10.7 or preview r3013

Also, can you provide app version, android version, and device
```
Tachiyomi version: ?
Android version: ?
Device: ?
```

**Comment by scb261** [comment] 2021-01-21 15:07
I thought I reproduced it, but turns out I typed in username instead of email. After entering email it works just fine. But there is still a bug to be fixed: if you enter wrong credentials (e.g. username instead of email), r3013 shows *Logged in* message, while 0.10.7 shows *HTTP 401* message

**Comment by rafalohaki** [comment] 2021-01-21 18:33
> Can't reproduce on stable v0.10.7 or preview r3013
> 
> Also, can you provide app version, android version, and device
> 
> ```
> Tachiyomi version: ?
> Android version: ?
> Device: ?
> ```

device: mi 9
android: 10
tachi version: r3013
i put email and it sais logged in but it doesnt

**Comment by ghostbear** [comment] 2021-01-21 19:16
Make sure you use the correct email and password associated with your Kitsu account when trying to login.

As for it always showing "Logged in" it will be fixed by #4329

**Closed** 2021-01-21 20:04 UTC
Labels: bug
