### ISSUE TITLE
Edit the manga informations

### ISSUE THREAD

**Issue by eouuuu** [tachiyomiorg/tachiyomi#6283] opened 2021-11-26 22:50 UTC
### Describe your suggested feature

Please add an edit function. There are extensions where the title is very long and very messy and it gets in the way of tracking too since I need to remove a lot of words. The summaries too. There are some symbols in between the letters and it’s very annoying to look at.

Please add it. Thank you

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2021-11-26 23:01
Duplicate of #6281

Why are you creating duplicates?

**Closed by arkon** 2021-11-26 23:01 UTC
Labels: Feature request

**Comment by eouuuu** [comment] 2021-11-26 23:15
I thought it disappeared. I’m sorry
