### ISSUE TITLE
Error/Warning icon

### ISSUE THREAD

**Issue by maxdd** [tachiyomiorg/tachiyomi#7818] opened 2022-08-19 17:05 UTC
### Describe your suggested feature

Hello,
Sometimes there are manga which fails to update for various reasons.
The current log file is poorly integrated and you are forced to go back and forth and remember which manga failed so that you can migrate.
I propose to have a simple icon (e.g a red or yellow ! based on the type of failure) on the right of title instead where e.g. the available chapters icon normally is to signal the failure

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment] 2022-08-19 17:13
Duplicate of #4616

**Comment by maxdd** [comment] 2022-08-19 17:15
Having a list dedicated to failing manga is similar but definitely another beast.
The proposal here is to track in all the list the status of the manga if different from normal

**Closed** 2022-08-19 17:14 UTC
Labels: Feature request
