### ISSUE TITLE
Automatic skipping of duplicate chapters on Mangadex doesn't work

### ISSUE THREAD

**Issue by LeVaporub** [tachiyomiorg/tachiyomi#6218] opened 2021-11-09 19:25 UTC
### Steps to reproduce

This has been tested on Mangadex, but should apply to other extensions that have duplicate chapters from multiple sources/uploaders. 

1. Locate a manga with duplicate chapters from multiple sources/uploaders.
2. Filter>sort by>chapter number.
3. Read the manga. After finishing one chapter, the reader will load the next chapter, even if it is a duplicate chapter number.

### Expected behavior

When there are duplicate chapters on Mangadex uploaded by different groups, using 'sort by chapter number' is supposed to automatically skip duplicate chapters.

### Actual behavior

When there are duplicate chapters on Mangadex, even when using 'sort by chapter number' the duplicate chapters are not skipped.

### Tachiyomi version

0.12.3

### Android version

Android 11

### Device

Poco X3

### Other details

Advised to log a report after consulting the support channel on the Discord server.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment] 2021-11-09 19:35
Duplicate of #5420

**Closed by alessandrojean** 2021-11-09 19:35 UTC
Labels: Bug
