### ISSUE TITLE
Customizable reader tap zones

### ISSUE THREAD

**Issue by Doddddd** [tachiyomiorg/tachiyomi#7427] opened 2022-07-01 06:54 UTC
### Describe your suggested feature

Divide the screen into 9 areas, and each area can be customized as "next page", "previous page", "menu", etc.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-07-10 00:20
Duplicate of #5706

**Closed by arkon** 2022-07-10 00:20 UTC
Labels: Feature request
