### ISSUE TITLE
[Feature Request] Can group extension like on discord

### ISSUE THREAD

**Issue by 54RaSuWi** [tachiyomiorg/tachiyomi#4881] opened 2021-04-17 03:53 UTC
## Why/User Benefit/User Problem
Can group extension according user (Like Manhwa source, Manhua source, Manga source).

## What/Requirements
Can do grouping an extension.

**Comment by Seishirou101** [comment] 2021-04-17 04:05
duplicate of #1904

**Closed** 2021-04-17 11:50 UTC
Labels: feature
