### ISSUE TITLE
Browse Extensions Filter for Scan Groups

### ISSUE THREAD

**Issue by nopeha** [tachiyomiorg/tachiyomi#9098] opened 2023-02-16 23:38 UTC
### Describe your suggested feature

My title probably could be better, but I'd like to suggest a filter for the Browse section's Extension tab.

I know it's important to diversify a Tachi library's sources and that it's better to use the scan group's extension if at all possible, but just searching "scans" in the extension list doesn't include all the scan group extensions.

So, in conjunction with the language filter for the Extension tab, I'd like to be able to filter for "Scan Groups" as well. I believe this will help expand a user's sources.

(I'd suggest having a filter for sites that cover western comics or solely manhwa or manhua, but I understand that gets muddied with aggregator sites.)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment] 2023-02-17 02:08
I don't think this would be worth implementing since we'd prefer not to push users toward certain sources, even if superficially. Along with that, I don't think we have nsfw sources all tagged yet.

**Comment by arkon** [comment] 2023-02-19 15:38
Duplicate of #8891

**Closed by arkon** 2023-02-19 15:38 UTC
Labels: Feature request
