### ISSUE TITLE
Searching inside the extension list causes a crash

### ISSUE THREAD

**Issue by MrAndre96** [tachiyomiorg/tachiyomi#10085] opened 2023-10-29 08:21 UTC
### Steps to reproduce

1. Open the browse view and click on the extensions tab
2. Search 'manhwat' or 'aa' and a crash occurs

### Expected behavior

Show a list of extensions based on the search

### Actual behavior

The app closes

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/13197550/tachiyomi_crash_logs.txt)

### Tachiyomi version

r6132

### Android version

Android 11

### Device

Oneplus 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-10-29 13:50
Duplicate of #10069. Please make sure you've updated the app before filing issues.

**Closed by arkon** 2023-10-29 13:50 UTC
Labels: Bug
