### ISSUE TITLE
[Bug] click on tachiyomi update aviable notification do nothing

### ISSUE THREAD

**Issue by kavillock** [tachiyomiorg/tachiyomi#4852] opened 2021-04-14 19:01 UTC
## Device information
* Tachiyomi version: 0.10.9
* Android version: 10
* Device: Nokia 6.1 

## Steps to reproduce
1. Click on tachiyomi update aviable notification 
2. Nothing

### Expected behavior
Idk, maybe open app and update? 

### Actual behavior
Nothing happened

**Comment by arkon** [comment] 2021-04-14 19:02
You need to tap the "Install action"

**Comment by kavillock** [comment] 2021-04-14 19:06
Oh, sorry, I forgot to mention, it's about notification, when I click in app update works smoothly

**Comment by arkon** [comment] 2021-04-14 19:23
Duplicate of #4825, I think.

**Closed by arkon** 2021-04-14 19:23 UTC
Labels: bug
