### ISSUE TITLE
Local Files Not Loading In Amazon Fire HD 10 (2019)

### ISSUE THREAD

**Issue by jahidrjrm** [tachiyomiorg/tachiyomi#10319] opened 2024-01-07 06:52 UTC
### Steps to reproduce

1. Loaidng For a long time and not opening any CBR files.

### Expected behavior

2. Just load quickly as like previous version, Some of us using this app for reading local files only.
3. No need to download any cover for local files. We will add cover as we like it.

### Actual behavior

After selecting any local Comic the reader screen just keep loading and nothing is opening, i have waited more then 5 minutes but the screen is just keep loading and loading.

### Crash logs

None found

### Tachiyomi version

0.15.0

### Android version

Android 9

### Device

Amazon Fire HD 10 (2019)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2024-01-07 13:08
Duplicate of #10302

**Closed** 2024-01-07 13:08 UTC
Labels: Bug
