### ISSUE TITLE
[Bug] Not showing PT-BR extensions

### ISSUE THREAD

**Issue by kreyr** [tachiyomiorg/tachiyomi#4170] opened 2020-12-21 10:38 UTC
## Device information
* Tachiyomi version: Preview r2903 (tried on stable build too).
* Android version: 10
* Device: Xiaomi Mi A2 Lite

## Steps to reproduce
1. Click on browse
2. Click on sources

### Expected behavior
Show my installed PT-BR extensions.

### Actual behavior
Not showing anything.

## Other details
The problem is only with PT-BR, another extensions like English, or Spanish are working. Because of this I can't search PT-BR mangas.

![5c16330b-02c4-40fb-9d1d-38aaed5509a8](https://user-images.githubusercontent.com/24763061/102768122-60ce0280-435f-11eb-9566-5cb4eddac3f0.jpg)
![b3f0aef2-cf88-4b76-90a1-72cd3655aaa1](https://user-images.githubusercontent.com/24763061/102768123-61ff2f80-435f-11eb-8da3-ba826b5e6c77.jpg)

**Comment by HaruSasaki** [comment] 2020-12-21 11:33
Make sure you enable the Português (Brasil) in source filter. The source filter is in the top right corner.

**Comment by kreyr** [comment] 2020-12-21 16:33
> Make sure you enable the Português (Brasil) in source filter. The source filter is in the top right corner.

Oh lol, that's it, I never saw this option. Just a question, why only the PT-BR is disabled? I installed stable build, preview, hard reset my phone, and the PT-BR never showed (I'm also not using any backup).

Also, thanks!

**Comment by HaruSasaki** [comment] 2020-12-21 21:07
> > Make sure you enable the Português (Brasil) in source filter. The source filter is in the top right corner.
> 
> Oh lol, that's it, I never saw this option. Just a question, why only the PT-BR is disabled? I installed stable build, preview, hard reset my phone, and the PT-BR never showed (I'm also not using any backup).
> 
> Also, thanks!

I dunno, but the default language are enabled when I use Tachiyomi is English.

**Comment by arkon** [comment] 2020-12-21 22:11
It should have your device's language enabled by default.

Closing since the issue is resolved.

**Closed by arkon** 2020-12-21 22:11 UTC
Labels: bug
