### ISSUE TITLE
Global update is not working

### ISSUE THREAD

**Issue by En79r** [tachiyomiorg/tachiyomi#10340] opened 2024-01-07 17:41 UTC
### Steps to reproduce

Global update is not working no matter what i do

### Expected behavior

Previous version was working okay until i installed the new version. Therefore the new update might have some bug.

### Actual behavior

Since global update said no new chapter i scrolled through the sources and found a lot of new chapters that is not coming out on global update window.

### Tachiyomi version

Latest version

### Android version

Android 12

### Device

Realme 9 pro 5g

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2024-01-07 17:49
Duplicate of #10313

**Closed** 2024-01-07 17:49 UTC
Labels: Bug
