### ISSUE TITLE
Reading mode webtoon and continuously vertical not working r4841

### ISSUE THREAD

**Issue by joerimonge** [tachiyomiorg/tachiyomi#7884] opened 2022-08-28 09:53 UTC
### Steps to reproduce

1 open a chapter
2 change the reading mode to webtoon or continuously vertical.
3 close the chapter.
4 than re-enter the same or a different chapter from the same series.

### Expected behavior

The pages loading in and being able to Scroll down.

### Actual behavior

The pages are not loading in and sometimes the app c

https://user-images.githubusercontent.com/74346601/187068105-84300974-f301-4aff-bc23-0c43c1682931.mp4

rashes

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/9439402/tachiyomi_crash_logs.txt)

### Tachiyomi version

r4841

### Android version

MIUI 13.0.9.0 stable, Android 12

### Device

Xiaomi 11 Lite 5G NE

### Other details

Other rereading modes work just fine as shown in the video.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment] 2022-08-28 12:02
Duplicate of #7881

**Closed** 2022-08-28 12:02 UTC
Labels: Bug
