### ISSUE TITLE
[Feature Request] Grouping sources in folders - Adding global search options

### ISSUE THREAD

**Issue by LovelessGenesis** [tachiyomiorg/tachiyomi#5192] opened 2021-05-25 14:27 UTC
- **Why/User Benefit/User Problem**

> Whenever I search for a specific type of content globally, every single source engages in the search, greatly increasing the time it takes to find a specific comic. 
> 
> Having sources organised into custom folders could greatly decrease the time it takes to find a specific kind of comic. If for example I am looking for an American comic I already Know I won't find it in any Manga or Nsfw source. So having more search options next to Global search would really be useful 

- **What/Requirements**

> I'm sure the team might find a more elegant solution, but here is what I propose:
> Adding a submenú in settings where sources can be grouped/tagged into custom values defined by the user (eg; American comic, Manga, Hentai, etc). Maybe just as categories are set for individual Comics but set to target sources
>
>Then at the time of searching from the library simply add other lines of text under 'search globally' that includes the other tags, eh. 'search Manga', etc. From the browsing page I guess easiest way to implement would be as a filter.
> 
> ![Screenshot_20210525-161338__01](https://user-images.githubusercontent.com/58740321/119513730-bf673480-bd74-11eb-99b9-371642409fa1.jpg)
> 
> Thank you for your time
>

**Comment by curche** [comment] 2021-05-25 14:36
Duplicate of #1758

**Closed** 2021-05-25 15:21 UTC
Labels: feature
