### ISSUE TITLE
[Bug] Migrating manga from one source to other doesn't migrate reader settings which were originally applied

### ISSUE THREAD

**Issue by rsmyst** [tachiyomiorg/tachiyomi#4745] opened 2021-03-30 05:06 UTC
## Device information
* Tachiyomi version: 0.10.9
* Android version: 10
* Device: S9+

## Steps to reproduce
1. Set default reader mode to right to left
2. Open a comic. 
3. Set reader mode to webtoon

### Expected behavior
Reading from the new migrated source should use the old settings and open in webtoon mode

### Actual behavior
Uses default reader mode i.e. right to left

**Comment by arkon** [comment] 2021-04-03 14:37
Can't reproduce in latest preview version, so closing this. Open another issue if you're still seeing this after the next stable release.

**Closed by arkon** 2021-04-03 14:37 UTC
Labels: bug
