### ISSUE TITLE
[Feature Request] Option to allow old UI on tablet

### ISSUE THREAD

**Issue by ronfar-x** [tachiyomiorg/tachiyomi#5291] opened 2021-06-03 13:09 UTC
---

## Why/User Benefit/User Problem
On smaller tablets like 7 inch/ 8 inch tablets, the new UI that is forced for tablets with side navigation and columns is difficult to use because there is a small screen. Pre 0.11 UI was spot on, and worked well with smaller tablets, but the new UI from 0.11 smooshes everything in the columns and is difficult to read, side navigation is not user friendly. 
Currently the only viable option to get the older (small screen tablet friendly) UI is to downgrade to pre 0.11.

## What/Requirements
Allow the user to choose if they want the UI from pre 0.11 (bottom screen navigation, chapter lists from mid to bottom of screen) or the new UI from 0.11 (side navigation, chapter lists in columns) freely, instead of forcing UI based on the device.

**Comment by loocool2** [comment] 2021-06-03 13:10
Duplicate of #5258

**Closed by loocool2** 2021-06-03 13:10 UTC
Labels: feature

**Comment by ronfar-x** [comment] 2021-06-03 13:18
Why is there no discussion allowed on this poor design choice?
