### ISSUE TITLE
Tachiyomi keeps stopping/crashing in webtoon mode

### ISSUE THREAD

**Issue by EdwinRodger** [tachiyomiorg/tachiyomi#6790] opened 2022-03-18 12:58 UTC
### Steps to reproduce

1. Take any vertical comic
2. Set it's reading mode to webtoon
3. After scrolling few pages down Tachiyomi stops/crashes

### Expected behavior

App should run normally

### Actual behavior

App stops/crashes

### Crash logs

MIUI Crash Log :- [MIUI Crash Log.txt](https://github.com/tachiyomiorg/tachiyomi/files/8304479/MIUI.Crash.Log.txt)

Tachiyomi Crash Log :- [Tachiyomi Crash Log.txt](https://github.com/tachiyomiorg/tachiyomi/files/8304480/Tachiyomi.Crash.Log.txt)
 
Both Crash Logs :- https://srcb.in/aA211mlrix

### Tachiyomi version

0.13.1

### Android version

Android 7 

### Device

Redmi Note 4

### Other details

I tried this bug with
1. _Release That Witch_ on NovelMic
2. _The Devil Butler_ on NovelMic
3. _The Gamer_ on Mangafreak
4. _Sss-Class Suicide Hunter_ on Mangakakalot and
5. _The Gangster Boss Is 16 Again_ on Mangakakalot **(Bug happens most in this webtoon)**

After the app crashes, the page count of that comic resets and when I try to go to same page, app crashes again!
To read one chapter of _The Gangster Boss Is 16 Again_, app crashes 4-5 times which is obviously inconvenient

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-03-19 01:51
```
03-18 17:56:08.074 32429 32506 E SubsamplingScaleImageView: Failed to initialise bitmap decoder
03-18 17:56:08.074 32429 32506 E SubsamplingScaleImageView: java.lang.Exception: Image decoder failed to initialize and get image size
03-18 17:56:08.074 32429 32506 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.decoder.ImageDecoder.init(ImageDecoder.java:6)
03-18 17:56:08.074 32429 32506 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:8)
03-18 17:56:08.074 32429 32506 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1)
03-18 17:56:08.074 32429 32506 E SubsamplingScaleImageView: 	at android.os.AsyncTask$2.call(AsyncTask.java:304)
03-18 17:56:08.074 32429 32506 E SubsamplingScaleImageView: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-18 17:56:08.074 32429 32506 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
03-18 17:56:08.074 32429 32506 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
03-18 17:56:08.074 32429 32506 E SubsamplingScaleImageView: 	at java.lang.Thread.run(Thread.java:760)
03-18 17:56:08.075 32429 32507 E SubsamplingScaleImageView: Failed to initialise bitmap decoder
03-18 17:56:08.075 32429 32507 E SubsamplingScaleImageView: java.lang.Exception: Image decoder failed to initialize and get image size
03-18 17:56:08.075 32429 32507 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.decoder.ImageDecoder.init(ImageDecoder.java:6)
03-18 17:56:08.075 32429 32507 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:8)
03-18 17:56:08.075 32429 32507 E SubsamplingScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1)
03-18 17:56:08.075 32429 32507 E SubsamplingScaleImageView: 	at android.os.AsyncTask$2.call(AsyncTask.java:304)
03-18 17:56:08.075 32429 32507 E SubsamplingScaleImageView: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-18 17:56:08.075 32429 32507 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
03-18 17:56:08.075 32429 32507 E SubsamplingScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
03-18 17:56:08.075 32429 32507 E SubsamplingScaleImageView: 	at java.lang.Thread.run(Thread.java:760)
```

**Comment by arkon** [comment] 2022-03-19 01:52
Duplicate of #1908, this is relatively prevalent on weaker devices.

**Closed by arkon** 2022-03-19 01:52 UTC
Labels: Bug
