### ISSUE TITLE
Recommendation system

### ISSUE THREAD

**Issue by 01Moonlight** [tachiyomiorg/tachiyomi#4239] opened 2021-01-03 21:37 UTC
# Why:
-To help people to find more manga from their own genre. 
#User benefit:
-Less time searching for a new manga. 
-More time reading without problems. 
#User Problem:
-Wasting time on websites searching for new manga. 
## What/Requirements
-at the end of the Manga main page they can find some Manga recommended by the system with the same Manga genre or writer.

**Comment by scb261** [comment] 2021-01-03 21:43
Duplicate of #376

**Closed** 2021-01-03 21:53 UTC
Labels: feature
