### ISSUE TITLE
Pagemark

### ISSUE THREAD

**Issue by Kodzuken29** [tachiyomiorg/tachiyomi#9988] opened 2023-10-07 08:11 UTC
### Describe your suggested feature

The way this feature works is similar to bookmark. The difference is, if bookmark is to selected chapters, this feature can select pages in the chapter. Basically it allows reader to only read pages they want, because sometimes there's both hated moment and enjoyable moment in one chapter.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-10-07 12:47
Duplicate of #565

**Closed** 2023-10-07 12:47 UTC
Labels: Duplicate, Feature request
