### ISSUE TITLE
nHentai option to enable pages instead of infinite scroll + Save last search location

### ISSUE THREAD

**Issue by MatteCrystal** [tachiyomiorg/tachiyomi#4350] opened 2021-01-25 01:51 UTC
I was told I should request this feature here, Original request is here https://github.com/tachiyomiorg/tachiyomi-extensions/issues/5548

Infinite scroll is great in many ways but can be a massive downside if you're browsing multiple pages worth of content deep. Each time you start a new browsing section it will reset and scroll to the top. This means if you want to continue browsing at that same location you'll have to scroll down a lot and the longer you do this the further you will have to scroll.

In these cases it's much more simple to have a simple page system. If I left off on page 8 I can just say go to page 8 next time I browse.

Somewhat related to this is the ability to save what page my search is on. So same as above, I might be on page 8. However, in this case I won't have to remember as I can just resume search after closing the app and it will start on page 8.

You could also get a little creative (this is not absolutely necessary) and make a system where it keeps track of what page you are on but it does it in a way that will dynamically update depending on how many new manga are added in the time between your browsing sessions.

For example: lets say there are 50 manga per page. and you are on page 10. But what if you save on page 10 and then 200 more new manga are added. In this case in order to resume where you left off you would need to start at page 14. So what I was thinking was what if you take the id of the topmost manga on a page (lets call it naruto) and use that id to determine where to resume the search from. So you you were on page 10 and naruto was the first manga on that page and then the next day 220 manga were added. Then just find out what page then naruto manga is on (page 14 in this example) so we know to resume from page 14. However, Notice it's not required for the naruto manga to be the first result of page 14. It's only necessary for naruto manga to be contained within page 14.

And of course there will be a failsafe, if the naruto manga doesn't exist anymore because the id changed or it was removed then we default to going to page 10.

It would also be great if this you were allowed multiple searches at once. which you could view from a list. So for example I might be on page 5 of a search using Tag A, And I could have another search on page 8 using Tag B. This way you can keep track of and search different things without losing your spot for other searches.

Also if a paging system is added then the option for the user to determine how many manga appear per page would be great.

**Comment by CarlosEsco** [comment] 2021-01-25 12:51
1 request per an issue.

From the wall of text, if I am understanding correctly.  You want the app to save which page of the browse/search you are on and resume to it next time you browse that source.

**Comment by MatteCrystal** [comment] 2021-01-25 21:21
Basically yes with a few extra features. The ability to choose between infinite scroll and paged view. The ability to resume from the same location next time I browse. And The ability to make a list of saved browsing sessions to resume from. So you don't lose progress of one search if you decide you want to do a quick lookup for pancakes or something.

**Comment by CarlosEsco** [comment] 2021-01-25 21:25
Page view could be built into an extension.  Save browse page and that dynamic stuff your mentioning isn't gonna happen. Sounds like a nightmare to code and maintain.

**Comment by arkon** [comment] 2021-01-25 22:31
Duplicate of #407.

**Closed by arkon** 2021-01-25 22:31 UTC
Labels: feature

**Comment by MatteCrystal** [comment] 2021-01-26 18:16
> 1 request per an issue.
> 
> From the wall of text, if I am understanding correctly. You want the app to save which page of the browse/search you are on and resume to it next time you browse that source.

I would keep it 1 Item per request but the second Item about saving location is dependent on the first part of about paging instead of infinite scroll. In situations like this How should I submit and request for the prior if the former isn't complete? If there is a format I should be following to accomplish this then could you point me in the right direction?

**Comment by CarlosEsco** [comment] 2021-01-26 18:21
you can open an issue and refer to it as a follow on of #407 in that you would the location saved.  but to tbh it will probably just stay in open ticket hell.
