### ISSUE TITLE
Coco漫畫改路徑

### ISSUE THREAD

**Issue by a1102321** [tachiyomiorg/tachiyomi#5644] opened 2021-08-02 04:56 UTC
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1

### Android version

11

### Device

Note 9

### Steps to reproduce

Coco漫畫路徑改了，從google連到coco漫畫是可以看的

### Expected behavior

連到正確的網站

### Actual behavior

連到被駭客的網站

**Comment by loocool2** [comment] 2021-08-02 04:57
wrong repo, and duplicate of a issue anyway

**Closed by loocool2** 2021-08-02 04:57 UTC
Labels: Bug
