### ISSUE TITLE
[Feature Request] Upscale

### ISSUE THREAD

**Issue by LazarusProMax** [tachiyomiorg/tachiyomi#5316] opened 2021-06-05 01:55 UTC
A large amount of manga is laid out in poor quality and this is especially noticeable on large screens, but if you apply almost any algorithm to improve the quality of the pages, the situation becomes much better.  

Now the application has almost everything to be the top, but by adding the image quality enhancement function to the reader, this program will be out of competition.

**Comment by loocool2** [comment] 2021-06-05 01:58
Duplicate of #3337

**Closed by loocool2** 2021-06-05 01:58 UTC
Labels: feature
