### ISSUE TITLE
[Bug] <Can't delete downloaded manga>

### ISSUE THREAD

**Issue by 54RaSuWi** [tachiyomiorg/tachiyomi#4872] opened 2021-04-16 10:54 UTC
## Device information
* Tachiyomi version: Stable 0.10.10
* Android version: 11
* Device: Vivo rev 6.8.7

## Steps to reproduce
1. write command on adb "adb shell cmd appops set eu.kanade.tachiyomi android:legacy_storage allow"
2. Update apps from 0.10.09 to 0.10.10

### Expected behavior
manga can be deleted via apps and file explorer

### Actual behavior
manga **only** can be deleted via file explorer

## Other details
I had done the instruction **Storage Issues With Android 11** and still can't delete the downloaded manga.
<img width="960" alt="ADB" src="https://user-images.githubusercontent.com/47868660/115014178-2d9a1b00-9edc-11eb-88ac-9728d0848992.png">
The downloaded manga can be deleted from apps but only one for one with interval 10 second, but if i want delete all chapter the downloaded manga icon seem dissapear but the icon will be back if i close the apps or manga.
This issue happen after i update my phone to android 11.

If you're experiencing crashes, share the crash logs from More → Settings → Advanced → Dump crash logs.

**Comment by arkon** [comment] 2021-04-16 12:24
Duplicate of #4286

**Closed by arkon** 2021-04-16 12:24 UTC
Labels: bug
