### ISSUE TITLE
New Tracking Service and Recommendation tab

### ISSUE THREAD

**Issue by Happygamma123** [tachiyomiorg/tachiyomi#9695] opened 2023-07-10 07:11 UTC
### Describe your suggested feature

Hi 👋. I was wondering is it possible to add animeplanet (website) for tracking services. We can track both manga and anime too.
Also is it ok to add a recommendation tab which gives recommendations based on the manga we are reading from sources like mal, anilist, mangaupdates or even animeplanet too.

Thanks

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment] 2023-07-10 07:12
Duplicate of #4849

**Closed by AntsyLich** 2023-07-10 07:12 UTC
Labels: Feature request
