### ISSUE TITLE
Tachiyomi crashing while reading downloaded chapters 

### ISSUE THREAD

**Issue by HAMBURBERS** [tachiyomiorg/tachiyomi#7692] opened 2022-08-06 10:41 UTC
### Steps to reproduce

There's no steps

### Expected behavior

It should be fine and the I should be able to read downloads 

### Actual behavior

While reading downloaded chapters tachiyomi freezes and keep crashing

### Crash logs

--------- beginning of crash
08-06 09:35:44.584  3632  4116 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 4116 (AsyncTask #3)
08-06 09:37:38.420  5863  6010 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 6010 (AsyncTask #1)
08-06 09:38:07.924  7205  7381 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 7381 (AsyncTask #1)
08-06 09:42:40.604  7671  9589 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 9589 (AsyncTask #4)
08-06 09:43:03.553 10751 10884 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 10884 (AsyncTask #3)
08-06 09:46:10.889 11126 12314 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 12314 (AsyncTask #2)
08-06 09:49:02.778 13312 14051 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 14051 (AsyncTask #5)
08-06 09:51:20.406 15313 15450 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 15450 (AsyncTask #3)
08-06 09:52:38.182 16956 17105 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 17105 (AsyncTask #1)
08-06 09:53:47.952 17915 18077 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 18077 (AsyncTask #3)
08-06 09:54:17.423 18756 18978 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 18978 (AsyncTask #1)
08-06 09:55:33.998 19209 19369 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 19369 (AsyncTask #1)
08-06 09:58:15.368 20109 20244 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 20244 (AsyncTask #3)
08-06 10:03:13.027 22025 25098 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 25098 (AsyncTask #5)
08-06 10:04:10.382 25455 25618 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 25618 (AsyncTask #1)
08-06 10:09:00.953 26154 26591 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 26591 (AsyncTask #7)
08-06 10:10:31.837 26617 26686 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 26686 (AsyncTask #2)
08-06 10:12:04.320 26711 26782 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 26782 (AsyncTask #2)
08-06 10:17:07.190 26804 26875 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 26875 (AsyncTask #2)
08-06 10:22:10.323 26898 27006 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 27006 (AsyncTask #6)
08-06 10:24:00.378 27017 27089 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 27089 (AsyncTask #3)
08-06 10:25:24.893 27118 27191 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 27191 (AsyncTask #2)
08-06 10:26:51.833 27214 27284 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 27284 (AsyncTask #2)
08-06 10:28:23.165 27296 27363 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 27363 (AsyncTask #1)
08-06 10:29:28.653 27399 27496 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 27496 (AsyncTask #6)
08-06 10:31:59.245 27505 27574 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 27574 (AsyncTask #3)
08-06 10:33:29.880 27600 27677 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 27677 (AsyncTask #3)
08-06 10:34:19.591 27708 27779 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 27779 (AsyncTask #2)
08-06 10:36:54.551 27796 27872 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 27872 (AsyncTask #2)
08-06 10:37:16.416 27909 27981 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 27981 (AsyncTask #3)
08-06 10:39:09.677 27991 28058 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 28058 (AsyncTask #3)
08-06 10:40:52.702 28086 28154 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 28154 (AsyncTask #2)
08-06 10:44:26.577 28172 28252 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 28252 (AsyncTask #4)
08-06 10:46:24.502 28270 28339 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 28339 (AsyncTask #2)
08-06 10:47:05.556 28357 28435 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 28435 (AsyncTask #3)
08-06 14:00:06.671 31780 31884 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 31884 (AsyncTask #2)
08-06 14:20:30.067 31892 32107 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 32107 (AsyncTask #13)
08-06 14:22:01.117 32114 32217 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 32217 (AsyncTask #4)
08-06 14:22:23.708 32228 32300 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 32300 (AsyncTask #2)
08-06 17:53:46.788 13595 14535 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 14535 (AsyncTask #1)
--------- beginning of main
08-06 18:22:29.176 21237 21237 E ResourceType: Style contains key with bad entry: 0x0101056c
08-06 18:22:29.189 21237 21237 E ResourceType: Style contains key with bad entry: 0x0101056d
08-06 18:22:29.189 21237 21237 E ResourceType: Style contains key with bad entry: 0x0101058c
08-06 18:22:29.189 21237 21237 E ResourceType: Style contains key with bad entry: 0x01010604
08-06 18:22:29.189 21237 21237 E ResourceType: Style contains key with bad entry: 0x01010605
08-06 18:22:33.960 21237 21271 E         : appName=eu.kanade.tachiyomi, acAppName=/system/bin/surfaceflinger
08-06 18:22:33.960 21237 21271 E         : 0
App version: 0.13.5 (standard, 26ddc6e, 81, 2022-07-08T20:12Z)
Android version: 7.0 (SDK 24)
Android build ID: alps-mp-n0.mp2-V1_6580.we.n_P136
Device brand: CloudFone
Device manufacturer: CloudFone
Device name: Thrill_Boost_2
Device model: Thrill Boost 2
Device product name: Thrill_Boost_2

### Tachiyomi version

Latest version 

### Android version

Android 7

### Device

Cloudfone Thrill Boost 2

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2022-08-06 14:14
The included logs don't include useful info. You could try a different way of getting logs:

- https://help.getpocket.com/article/1073-retrieving-a-pocket-crash-log-on-android
- https://play.google.com/store/apps/details?id=com.dp.logcatapp&hl=en_CA

This is likely just because your device seems to be incredibly underpowered though.

**Comment by Enzycal** [comment] 2022-08-07 04:00
Can confirm it is not due to an underpowered device. I'm using a Galaxy Note 10+ and  have been experiencing the same issue since I updated to the latest version today.

It happens on a specific page of a chapter even after reatarting the app. But then it randomly goes away if you revisit the same page.

**Comment by Enzycal** [comment] 2022-08-13 19:31
After having no crashes for a while, it happened again.

Only ever happened with downloaded chapters but I can't say for sure that the problem is limited to them. 

`--------- beginning of main
08-13 21:07:33.913 15485 15485 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-13 21:07:33.913 15485 15485 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-13 21:07:34.745 15485 15485 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-13 21:07:34.745 15485 15485 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-13 21:07:38.066 15485 15485 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-13 21:07:38.067 15485 15485 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-13 21:07:40.845 15485 15485 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-13 21:07:40.845 15485 15485 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-13 21:07:40.867 15485 15485 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-13 21:07:40.867 15485 15485 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-13 21:07:44.659 15485 15485 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-13 21:07:44.659 15485 15485 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-13 21:07:45.427 15485 15485 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-13 21:07:45.427 15485 15485 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-13 21:07:49.774 15485 15485 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-13 21:07:49.775 15485 15485 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-13 21:07:49.788 15485 15485 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-13 21:07:49.788 15485 15485 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-13 21:07:50.289 15485 15485 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-13 21:07:50.289 15485 15485 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-13 21:07:50.303 15485 15485 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-13 21:07:50.303 15485 15485 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-13 21:07:50.539 15485 15485 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-13 21:07:50.539 15485 15485 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-13 21:07:50.599 15485 15485 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-13 21:07:50.599 15485 15485 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-13 21:07:52.887 15485 15485 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-13 21:07:52.887 15485 15485 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-13 21:07:52.902 15485 15485 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-13 21:07:52.902 15485 15485 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-13 21:07:52.921 15485 15485 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-13 21:07:52.921 15485 15485 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-13 21:08:01.229 15485 15485 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-13 21:08:01.229 15485 15485 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-13 21:08:01.231 15485 15485 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-13 21:08:01.231 15485 15485 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-13 21:08:01.272 15485 15485 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-13 21:08:01.272 15485 15485 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-13 21:08:06.104 15485 15485 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-13 21:08:06.104 15485 15485 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-13 21:08:06.372 15485 15485 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-13 21:08:06.372 15485 15485 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-13 21:08:07.456 15485 15485 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-13 21:08:07.456 15485 15485 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-13 21:08:07.474 15485 15485 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-13 21:08:07.474 15485 15485 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-13 21:08:08.458 15485 15485 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-13 21:08:08.458 15485 15485 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
08-13 21:12:55.596 15485 15485 E AndroidRuntime: FATAL EXCEPTION: main
08-13 21:12:55.596 15485 15485 E AndroidRuntime: Process: eu.kanade.tachiyomi, PID: 15485
08-13 21:12:55.596 15485 15485 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Index: 15, Size: 13
08-13 21:12:55.596 15485 15485 E AndroidRuntime: 	at java.util.ArrayList.add(ArrayList.java:483)
08-13 21:12:55.596 15485 15485 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.pager.PagerViewerAdapter.setChapters(PagerViewerAdapter.kt:16)
08-13 21:12:55.596 15485 15485 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.pager.PagerViewer.setChaptersInternal(PagerViewer.kt:8)
08-13 21:12:55.596 15485 15485 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.pager.PagerViewer.access$setIdle(PagerViewer.kt:3)
08-13 21:12:55.596 15485 15485 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.viewer.pager.PagerViewer$1.onPageScrollStateChanged(PagerViewer.kt:1)
08-13 21:12:55.596 15485 15485 E AndroidRuntime: 	at androidx.viewpager.widget.DirectionalViewPager.setScrollState(DirectionalViewPager.java:12)
08-13 21:12:55.596 15485 15485 E AndroidRuntime: 	at androidx.viewpager.widget.DirectionalViewPager$3.run(DirectionalViewPager.java:1)
08-13 21:12:55.596 15485 15485 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1108)
08-13 21:12:55.596 15485 15485 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:866)
08-13 21:12:55.596 15485 15485 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:792)
08-13 21:12:55.596 15485 15485 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
08-13 21:12:55.596 15485 15485 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
08-13 21:12:55.596 15485 15485 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-13 21:12:55.596 15485 15485 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
08-13 21:12:55.596 15485 15485 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
08-13 21:12:55.596 15485 15485 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8663)
08-13 21:12:55.596 15485 15485 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-13 21:12:55.596 15485 15485 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
08-13 21:12:55.596 15485 15485 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
08-13 21:12:55.597 15485 15485 E ACRA    : ACRA caught a IndexOutOfBoundsException for eu.kanade.tachiyomi
08-13 21:12:55.597 15485 15485 E ACRA    : java.lang.IndexOutOfBoundsException: Index: 15, Size: 13
08-13 21:12:55.597 15485 15485 E ACRA    : 	at java.util.ArrayList.add(ArrayList.java:483)
08-13 21:12:55.597 15485 15485 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.viewer.pager.PagerViewerAdapter.setChapters(PagerViewerAdapter.kt:16)
08-13 21:12:55.597 15485 15485 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.viewer.pager.PagerViewer.setChaptersInternal(PagerViewer.kt:8)
08-13 21:12:55.597 15485 15485 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.viewer.pager.PagerViewer.access$setIdle(PagerViewer.kt:3)
08-13 21:12:55.597 15485 15485 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.viewer.pager.PagerViewer$1.onPageScrollStateChanged(PagerViewer.kt:1)
08-13 21:12:55.597 15485 15485 E ACRA    : 	at androidx.viewpager.widget.DirectionalViewPager.setScrollState(DirectionalViewPager.java:12)
08-13 21:12:55.597 15485 15485 E ACRA    : 	at androidx.viewpager.widget.DirectionalViewPager$3.run(DirectionalViewPager.java:1)
08-13 21:12:55.597 15485 15485 E ACRA    : 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1108)
08-13 21:12:55.597 15485 15485 E ACRA    : 	at android.view.Choreographer.doCallbacks(Choreographer.java:866)
08-13 21:12:55.597 15485 15485 E ACRA    : 	at android.view.Choreographer.doFrame(Choreographer.java:792)
08-13 21:12:55.597 15485 15485 E ACRA    : 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
08-13 21:12:55.597 15485 15485 E ACRA    : 	at android.os.Handler.handleCallback(Handler.java:938)
08-13 21:12:55.597 15485 15485 E ACRA    : 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-13 21:12:55.597 15485 15485 E ACRA    : 	at android.os.Looper.loopOnce(Looper.java:226)
08-13 21:12:55.597 15485 15485 E ACRA    : 	at android.os.Looper.loop(Looper.java:313)
08-13 21:12:55.597 15485 15485 E ACRA    : 	at android.app.ActivityThread.main(ActivityThread.java:8663)
08-13 21:12:55.597 15485 15485 E ACRA    : 	at java.lang.reflect.Method.invoke(Native Method)
08-13 21:12:55.597 15485 15485 E ACRA    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
08-13 21:12:55.597 15485 15485 E ACRA    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
08-13 21:12:56.313 25069 25069 E .tachiyomi:acr: Not starting debugger since process cannot load the jdwp agent.
08-13 21:12:56.317 25069 25069 E USNET   : USNET: appName: eu.kanade.tachiyomi:acra
08-13 21:13:05.930 25175 25175 E anade.tachiyom: Not starting debugger since process cannot load the jdwp agent.
08-13 21:13:05.933 25175 25175 E USNET   : USNET: appName: eu.kanade.tachiyomi
08-13 21:13:06.503 25175 25277 E SQLiteLog: (284) automatic index on C(manga_id)
08-13 21:13:06.503 25175 25277 E SQLiteLog: (284) automatic index on R(manga_id)
08-13 21:13:06.503 25175 25277 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 0.13.5 (standard, 26ddc6e, 81, 2022-07-08T20:12Z)
Android version: 12 (SDK 31)
Android build ID: SP1A.210812.016.N975FXXS8HVF3
Device brand: samsung
Device manufacturer: samsung
Device name: d2s
Device model: SM-N975F
Device product name: d2seea`

**Comment by kevin01523** [comment] 2022-08-14 20:40
I do experience this a random freeze or lag while reading after updating about 15-8 days ago it  still does persist on recent version it goes away of you wait it out a bit. Basically tachiyomi stops responding

**Comment by Humam-Hamdan** [comment] 2022-08-17 04:17
Same here, it usuallu crashes only when i bookmark a chapter after leaving it open for about 2 hours... but now? it's... worse.

**Comment by Lindsor** [comment] 2022-08-30 20:51
Started happening to me as well after update to latest. I'm on Samsung Galaxy S20+

**Comment by mlengka93** [comment] 2022-09-08 07:48
I have same issue like this, are you saving the download chapter on external SD card? Before, i use my sd card as internal and this problem never happen to me, but i revert it back to normal and this problem keep happening

**Comment by mlengka93** [comment] 2022-09-08 08:44
I have the same issue, I think the problem is trying to read *.CBZ downloaded file, if i read the downloaded chapter from "folder and image (old style)" its completely fine. I have already tried it same chapter convert it vice versa, and result is read cbz file always crash randomly.

**Comment by charicner** [comment] 2022-09-08 11:20
I do have the manga saved on external and I also switched to cbz recently. I'm try switching off cbz and test it

**Comment by arkon** [comment] 2022-12-05 20:38
Duplicate of #5987

**Closed by arkon** 2022-12-05 20:38 UTC
Labels: Bug, Needs more info
