### ISSUE TITLE
[Bug] <download button>

### ISSUE THREAD

**Issue by kasakaka** [tachiyomiorg/tachiyomi#4942] opened 2021-04-22 23:53 UTC
## Device information
* Tachiyomi version: 0.10.11
* Android version: 10
* Device: samsung a10s

## Steps to reproduce
1. go to a manga you want to read
2. tap the download icon on the upper right then press any of the option exceot unread

### Expected behavior
download the next chapter you should be reading 

### Actual behavior
The chapter that will be downloaded will be the latest updated chaptet and if you choose more than 1 to download it downloads in descending order

**Comment by arkon** [comment] 2021-04-22 23:55
Duplicate of #4916

**Closed by arkon** 2021-04-22 23:55 UTC
Labels: bug
