### ISSUE TITLE
[Feature Request] <Allow the filtering out of manga already in your library when using browse>

### ISSUE THREAD

**Issue by IIOMNIVERSEII** [tachiyomiorg/tachiyomi#4789] opened 2021-04-07 08:57 UTC
## Why/User Benefit/User Problem
(explain why this feature should be added)
This feature will hide all the manga currently in your library when using a source with a filter in order to save time and speed up the process when adding new manga.I end up scrolling for upto 20 minutes anytime I look for a new manga since I have most things added to my library and sorting using time becomes less and less effective with the more stuff I add/read.
## What/Requirements
(explain how this feature would behave)
1.Make it so that when a manga is added to your library it gets a tag called "library" as its last tag to show its in your library and make filtering them out easier.
2.When you click on the filter in browse for a source my main sources being mangakakalot & nhentai the first thing to appear should be a small checkbox with [hide all manga currently in library] next to it when the checkbox is checked all manga that have the tag "library" will be filtered out leaving only stuff you haven't added.

**Comment by Seishirou101** [comment] 2021-04-07 09:30
duplicate of #2941

**Closed** 2021-04-07 12:04 UTC
Labels: feature
