### ISSUE TITLE
Unable to open CBR files

### ISSUE THREAD

**Issue by sQVe** [tachiyomiorg/tachiyomi#10302] opened 2024-01-06 20:56 UTC
### Steps to reproduce

Open a CBR file

### Expected behavior

Should work like it has previously 

### Actual behavior

It just shows a spinner that spins indefinitely 

### Tachiyomi version

0.15.0

### Android version

Android 13

### Device

Samsung Tab 7+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/docs/faq/general) and [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.0](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment] 2024-01-06 20:58
Duplicate of #3988

**Comment by AntsyLich** [comment] 2024-01-06 20:59
Are those RAR5? It's not supported as it is proprietary

**Comment by sQVe** [comment] 2024-01-06 21:04
> Are those RAR5? It's not supported as it is proprietary 

I don't know. It has worked perfectly fine before though. Has something changed in how this is handled with the latest version?

**Comment by sQVe** [comment] 2024-01-06 21:17
I just went through some files (which is CBR) that I've read the last two weeks and none of them work now with the latest version.

**Comment by arkon** [comment] 2024-01-06 21:17
Do other file formats work?

**Comment by sQVe** [comment] 2024-01-06 21:28
> Do other file formats work?

Yes. Both plain images and CBZ work fine.

**Closed** 2024-01-06 22:09 UTC
Labels: Bug
