### ISSUE TITLE
Migrate From Jetpack Compose to Flutter 

### ISSUE THREAD

**Issue by kanniprab03** [tachiyomiorg/tachiyomi#10134] opened 2023-11-13 03:29 UTC
### Describe your suggested feature

It would be best one codebase for all devices

### Other details

For iOS devices they can use using non jailbreak method 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment] 2023-11-13 03:30
Duplicate of #9664

**Closed by arkon** 2023-11-13 03:30 UTC
Labels: Feature request
