### ISSUE TITLE
[Feature Request] Hope to add the function of splicing across pages automatically

### ISSUE THREAD

**Issue by 1024kilobytes** [tachiyomiorg/tachiyomi#5199] opened 2021-05-26 08:12 UTC
Hope to add the function of splicing across pages automatically
Some comic pages are spread across pages, and the default is to separate them when reading

**Comment by arkon** [comment] 2021-05-26 12:21
I'm not sure I understand.

**Comment by arkon** [comment] 2021-05-29 02:44
I assume this is a duplicate of #149 if I'm reading it correctly.

**Closed by arkon** 2021-05-29 02:44 UTC
Labels: feature
