### ISSUE TITLE
[Feature Request] Unified crossovers' chapters

### ISSUE THREAD

**Issue by LeonGuerreroGit** [tachiyomiorg/tachiyomi#4142] opened 2020-12-15 15:30 UTC
## Why/User Benefit/User Problem
A feature that automatically fetches various chapters and put them together in the same place would be so useful.
Marvel, for example, tells stories involving various comics so it isn't easy to look for X-Men #13 and read it, then go back, look for Marauders #2 and read it, then go back, look for another comics etc
It'd be awesome if you could fetch reading order somewhere (if there's any source that offers a simple rest API or you could also scrape some well knows websites) and put together all the comics needed to finish a narrative arc.

**Comment by joseph619** [comment] 2020-12-15 21:39
Possibly duplicate of #886

**Comment by CarlosEsco** [comment] 2020-12-16 12:23
This is way outside the scope of this app  (finding random issues in random comics, in random order, all this ordered by a source that doesnt provide something like this).  The best solution for this would be #2282 being implemented.

**Closed by CarlosEsco** 2020-12-16 12:23 UTC
Labels: feature
